### PR TITLE
Fix RVec move constructor and assignment operators

### PR DESCRIPTION
**Pull request by amadio**
Related JIRA issue: [ROOT-10079](https://sft.its.cern.ch/jira/browse/ROOT-10079).

### CODE REVIEW

**Comment by dpiparo** [comment]
it looks like a regression has been introduced.

**Comment by amadio** [comment]
@phsft-bot build just on windows10/default

**Comment by amadio** [comment]
Trying on Windows again...

**Comment by amadio** [comment]
The failure is not related.
```
11:19:57 C:\build\workspace\root-pullrequests-build\root\tree\dataframe\test\dataframe_nodes.cxx(97): error C3493: 'nBinsExpected' cannot be implicitly captured because no default capture mode has been specified [C:\build\workspace\root-pullrequests-build\build\tree\dataframe\test\dataframe_nodes.vcxproj]
```

**Comment by pcanal** [comment]
When reverting, please enhance the commit message with the reason for the reversions.  thanks.

**Pull request merged**
