### PR TITLE
cling PR 169

### PR DESCRIPTION
**Pull request by Axel-Naumann**
https://github.com/root-project/cling/pull/169

### CODE REVIEW

**Comment by bellenot** [comment]
According to this [Appveyor build](https://ci.appveyor.com/project/bellenot/cling/build/1.0.277/job/gk9h7ml1fbxwkiu8), this doesn't look to fix any test (not even CodeGeneration/Statics.C):
```
  Failing Tests (11):
      Cling :: CodeGeneration/Statics.C
      Cling :: CodeGeneration/Symbols.C
      Cling :: CodeGeneration/TLSVars.C
      Cling :: CodeUnloading/PCH/VTablesClingPCH.C
      Cling :: Driver/Gnu.C
      Cling :: Lookup/data.C
      Cling :: Lookup/func.C
      Cling :: NullDeref/MethodCalls.C
      Cling :: Prompt/OutputRedirect.C
      Cling :: Prompt/ValuePrinter/Regression.C
      Cling :: Utils/Transform.C
  
    Expected Passes    : 109
    Expected Failures  : 12
    Unsupported Tests  : 1
    Unexpected Failures: 11
```

**Comment by marsupial** [comment]
Appveyor is also saying it is generating a warning which it should not be doing.
What does it do/say when applied locally?
I just tried locally with ELF & Release and it passed...

**Comment by marsupial** [comment]
And prior Appveyor builds show CodeGeneration/Statics.C was just crashing, so it does fix _something_.

**Comment by bellenot** [comment]
Sorry @marsupial, I overlooked at the log, I just saw the same tests failing before and after...

**Comment by bellenot** [comment]
BTW, the indentation in this PR is not consistent (sometimes two spaces, sometimes four...)

**Comment by marsupial** [comment]
I assume you are talking about EmuTLS.cpp?
The original is from compiler-rt, which poached it from gcc.
Keeping the indentation at 4 makes it easier to re-integrate when updates occur.

BTW, could you look at https://github.com/root-project/cling/pull/174

**Comment by bellenot** [comment]
OK, I understand, it makes sense, thanks for the explanation. And see my comment on the [PR-174](https://github.com/root-project/cling/pull/174)

**Comment by vgvassilev** [comment]
Does #177 supersede this one? Shall we close it?

**Comment by marsupial** [comment]
This is a subset, but crashes OS X & linux too (see test/CodeGeneration/TLSVars.C) so might be worth dealing with on its own as it can easily be taken out of 177.

177 is huge and contains everything necessary for Windows to pass.
(As far as i know https://ci.appveyor.com/project/bellenot/cling/build/1.0.312)

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -Dclingtest=On now that I've fixed the cling tests.

**Comment by etejedor** [comment]
@bellenot is it understood why the windows build fails here? It this WIP?

**Comment by oshadura** [comment]
@phsft-bot build with flags -Dclingtest=On

**Comment by etejedor** [comment]
@bellenot do we need to rescue this PR or it is obsolete?

**Comment by etejedor** [comment]
@bellenot do we need to rescue this PR or it is obsolete?

**Comment by lmoneta** [comment]
@bellenot  do we declare it obsolete ?

**Comment by bellenot** [comment]
@moneta I would keep it for the time being (it is not clear what has been taken and what not...)

**Pull request closed without merging**
