### PR TITLE
Use direct cast to double to avoid warnings in StringConv.hxx

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by linev** [comment]
Trying to solve frequent failure in **assertHumanReadable** tests. Typical output:

```
[NON-XML-CHAR-0x1B][1m/mnt/build/wsincrmaster/LABEL/ROOT-ubuntu1804-clangHEAD/SPEC/noimt/build/include/ROOT/StringConv.hxx:103:18: [NON-XML-CHAR-0x1B][0m[NON-XML-CHAR-0x1B][0;1;35mwarning: [NON-XML-CHAR-0x1B][0m[NON-XML-CHAR-0x1B][1mimplicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-int-float-conversion][NON-XML-CHAR-0x1B][0m
         if (v < std::numeric_limits<T>::max()) {
[NON-XML-CHAR-0x1B][0;1;32m               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[NON-XML-CHAR-0x1B][0m[NON-XML-CHAR-0x1B][1m/mnt/build/wsincrmaster/LABEL/ROOT-ubuntu1804-clangHEAD/SPEC/noimt/roottest/root/core/assertHumanReadable.cxx:9:29: [NON-XML-CHAR-0x1B][0m[NON-XML-CHAR-0x1B][0;1;30mnote: [NON-XML-CHAR-0x1B][0min instantiation of function template specialization 'ROOT::FromHumanReadableSize<long long>' requested here[NON-XML-CHAR-0x1B][0m
   auto parseResult = ROOT::FromHumanReadableSize(input,res);
[NON-XML-CHAR-0x1B][0;1;32m                            ^
[NON-XML-CHAR-0x1B][0m1 warning generated.
```

**Comment by linev** [comment]
Duplication for https://github.com/root-project/root/pull/4289, closing this

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@Axel-Naumann 
Should it be picked into 6.18 branch - error appears there time to time.
Like recently: https://epsft-jenkins.cern.ch/job/root-incremental-v6-18-00-patches/LABEL=ROOT-ubuntu1804-clangHEAD,SPEC=noimt/119/

**Comment by Axel-Naumann** [comment]
Done, https://github.com/root-project/root/commit/53e39563f7f88338605686f494e69634aa1847d4

**Pull request merged**
