### PR TITLE
[ROOT-10936] Adapt TMVA to support cuDNN 8

### PR DESCRIPTION
**Pull request by kgizdov**
WIP: As the title says - trying to update TMVA to support cuDNN 8, but also be backwards compatible.

More commits to come

### CODE REVIEW

**Comment by lmoneta** [comment]
Looks good to me. I would need however Cudnn version 8 to test. I'll try to do it soon

**Comment by kgizdov** [comment]
@lmoneta don't worry, this is work in progress (marked WIP), not ready yet. Another commit to fix the convolution is needed too. I'm working on it.

**Comment by lmoneta** [comment]
OK, I will wait for the other commits. Thank you for providing these patches !

**Comment by kgizdov** [comment]
@lmoneta if you've got a test script or something, I can test once I finish. We have CUDA11 and cuDNN 8 on Arch.

**Comment by lmoneta** [comment]
Hi, 
you can run the tutorials:
`tutorials/tmva/TMVA_CNN_Classification.C` and 
`tutorials/tmva/TMVA_RNN_Classification.C`

They will use GPU (and cud for the convolutional and recurrent networks) if it is available (tmva-gpu=On cudnn=On

**Comment by kgizdov** [comment]
@lmoneta cool, thanks - initial work is done, I will test - in the meantime, it would be awesome if you check my math and naming interpretations of parameters, cheers

**Comment by kgizdov** [comment]
I'm having an issue with following some of the login - there is either a bug or I'm very confused:
```c++
// First it's like this
cudnnConvolutionFwdPreference_t preferenceFwd = (CNNOptions::ConvMaxWorkspaceSize !=0) ? 
    CUDNN_CONVOLUTION_FWD_PREFER_FASTEST :
    CUDNN_CONVOLUTION_FWD_NO_WORKSPACE;
// same for backward data, but
// then it's the reverse
cudnnConvolutionBwdFilterPreference_t preferenceBwdFilter = (CNNOptions::ConvMaxWorkspaceSize != 0) ?
    CUDNN_CONVOLUTION_BWD_FILTER_NO_WORKSPACE :
    CUDNN_CONVOLUTION_BWD_FILTER_PREFER_FASTEST;
// for backward filter
```
The docs only say `CNNOptions::ConvMaxWorkspaceSize` is `0` by default to let `cuDNN` choose and `-1` indicating use no workspace. Not sure how to interpret.

**Comment by lmoneta** [comment]
Hi, 
I think this is a bug. It should choose the NO_WORKSPACE case when CNNOptions::ConvMaxWorkspaceSize=-1 and the fastest option when is zero. 

Thank you for finding this out 

Best

Lorenzo

**Comment by lmoneta** [comment]
Hi, 
Sorry I have double check this issue: 
-  CNNOptions::ConvMaxWorkspaceSize=-1 is the default In this cease CUDNN decides the best algorithm. and the preference should be CUDNN_CONVOLUTION_FWD_PREFER_FASTEST or CUDNN_CONVOLUTION_BWD_FILTER_PREFER_FASTEST (for backward)
- CNNOptions::ConvMaxWorkspaceSize=0  is the option when the algorithm does not use any workspace  (less memory for GPU)
- CNNOptions::ConvMaxWorkspaceSize= maxvalue.  Maximum value passed by the user for the workspace size

Are these preference parameters different now in Cud version 8 ? 
Otherwise I can provide later a PR for fixing this

Lorenzo

**Comment by kgizdov** [comment]
@lmoneta the logic is a bit different now and it needed to be re-implemented, as cudnn no longer provides equivalent helper algos, nor does it have those enums for preference. I have implemented a backwards compatible solution and reduced some branch complexity. Have a look here - https://github.com/root-project/root/pull/6058/files#diff-5bdcb6011937edc2089e7a0de3c8d62fR343-R400

**Comment by lmoneta** [comment]
The code looks good to me. Please test with the new cudnn version 8 if it works. 
I will try to check with cudnn version 7

**Comment by kgizdov** [comment]
@lmoneta all finally compiles and is C++11 compatible - templated lambdas are only from C++14, so I had to improvise. Please have a look at anything I might have missed and you should be able to compile and test for yourself.

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
Thank you for completing this. Looks good to me. I have tested on cudnn 7 and it works fine. Unfortunately I cannot test now on cudnn 8. 
@kgzidov Can you please verify if running all TMVA  tests on cudnn 8 works ? 
You should configure cmake with` -Dtesting=On` and then run the TMVA tests with 
`ctest -R TMVA`
If all tests pass I will merge it 
Thank you 
Lorenzo

**Comment by kgizdov** [comment]
@lmoneta sure, but before that I have to fix [this](https://github.com/root-project/root/blob/2b857fff8a552b74192ddc43fbbef83c5b90e8f1/tmva/tmva/src/DNN/Architectures/Cudnn.cu#L17-L22) because it is broken with CUDA 11 and C++17.

**Comment by lmoneta** [comment]
Ah , I see. What is the error you get with C++17 and Cuda 11 ? Is Cuda 11 supporting C++ 17 now ?

**Comment by kgizdov** [comment]
Yes, see #6079 

Error is:
```
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooChiSquarePdf.cxx.o
/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(32): error: "basic_string_view" has already been declared in the current scope

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(35): error: invalid redeclaration of type name "std::string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(589): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(36): error: invalid redeclaration of type name "std::u16string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(596): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(37): error: invalid redeclaration of type name "std::u32string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(597): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(38): error: invalid redeclaration of type name "std::wstring_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(591): here

5 errors detected in the compilation of "/build/root/src/root-6.22.00-cuda/tmva/tmva/src/DNN/Architectures/Cuda/CudaMatrix.cu".
make[2]: *** [tmva/tmva/CMakeFiles/TMVA.dir/build.make:2253: tmva/tmva/CMakeFiles/TMVA.dir/src/DNN/Architectures/Cuda/CudaMatrix.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooDecay.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooDstD0BG.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooExponential.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooFunctor1DBinding.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooFunctorBinding.cxx.o
/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(32): error: "basic_string_view" has already been declared in the current scope

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(35): error: invalid redeclaration of type name "std::string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(589): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(36): error: invalid redeclaration of type name "std::u16string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(596): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(37): error: invalid redeclaration of type name "std::u32string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(597): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(38): error: invalid redeclaration of type name "std::wstring_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(591): here

5 errors detected in the compilation of "/build/root/src/root-6.22.00-cuda/tmva/tmva/src/DNN/Architectures/Cuda/CudaTensor.cu".
make[2]: *** [tmva/tmva/CMakeFiles/TMVA.dir/build.make:2266: tmva/tmva/CMakeFiles/TMVA.dir/src/DNN/Architectures/Cuda/CudaTensor.cu.o] Error 1
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooGamma.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooGaussian.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooGaussModel.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooGExpModel.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooHistConstraint.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooIntegralMorph.cxx.o
/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(32): error: "basic_string_view" has already been declared in the current scope

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(35): error: invalid redeclaration of type name "std::string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(589): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(36): error: invalid redeclaration of type name "std::u16string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(596): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(37): error: invalid redeclaration of type name "std::u32string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(597): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(38): error: invalid redeclaration of type name "std::wstring_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(591): here

5 errors detected in the compilation of "/build/root/src/root-6.22.00-cuda/tmva/tmva/src/DNN/Architectures/Cuda.cu".
make[2]: *** [tmva/tmva/CMakeFiles/TMVA.dir/build.make:2227: tmva/tmva/CMakeFiles/TMVA.dir/src/DNN/Architectures/Cuda.cu.o] Error 1
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooJeffreysPrior.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooKeysPdf.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooLandau.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooLognormal.cxx.o
[ 95%] Building CXX object roofit/roofit/CMakeFiles/RooFit.dir/src/RooMathCoreReg.cxx.o
/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(32): error: "basic_string_view" has already been declared in the current scope

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(35): error: invalid redeclaration of type name "std::string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(589): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(36): error: invalid redeclaration of type name "std::u16string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(596): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(37): error: invalid redeclaration of type name "std::u32string_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(597): here

/build/root/src/root-6.22.00-cuda/core/foundation/inc/ROOT/RStringView.hxx(38): error: invalid redeclaration of type name "std::wstring_view"
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/c++/string_view(591): here

5 errors detected in the compilation of "/build/root/src/root-6.22.00-cuda/tmva/tmva/src/DNN/Architectures/Cudnn.cu".
make[2]: *** [tmva/tmva/CMakeFiles/TMVA.dir/build.make:2292: tmva/tmva/CMakeFiles/TMVA.dir/src/DNN/Architectures/Cudnn.cu.o] Error 1
```

**Comment by lmoneta** [comment]
@kgizdov : is this one ready to be merged ?

**Comment by lmoneta** [comment]
@kgizdov : is this one ready to be merged ?

**Comment by lmoneta** [comment]
@kgizdov : is this one ready to be merged ?

**Comment by lmoneta** [comment]
@kgizdov : is this one ready to be merged ?

**Comment by kgizdov** [comment]
@lmoneta testing as we speak, give me 2 hours

**Comment by kgizdov** [comment]
I'm running into trouble
```
/build/root/src/root-6.22.00-cuda/tmva/tmva/test/Method/TestMethodDNNValidationSize.cxx: In member function ‘size_t TMVA::TestMethodDNNValidationSize::GetProcessedValidationOption(TString)’:
/build/root/src/root-6.22.00-cuda/tmva/tmva/test/Method/TestMethodDNNValidationSize.cxx:54:80: error: ‘defualtOptions’ was not declared in this scope
   54 |       IMethod *m = fFactory->BookMethod(fDataLoader.get(), Types::kDNN, "DNN", defualtOptions + options);
      |                                                                                ^~~~~~~~~~~~~~
```

**Comment by kgizdov** [comment]
#6148

**Comment by kgizdov** [comment]
So depending on #6148 #6079 and this all seems to work:
```
$ env CTEST_OUTPUT_ON_FAILURE=1 ctest -R TMVA
Test project /build/root/src/build-cuda
...
100% tests passed, 0 tests failed out of 71

Label Time Summary:
tutorial    = 132.26 sec*proc (18 tests)

Total Test time (real) = 287.13 sec
```

**Comment by lmoneta** [comment]
Thank you. I will then merge it

Cheers

L.

**Pull request merged**
