### PR TITLE
[Vecops] Sorting docs

### PR DESCRIPTION
**Pull request by stwunsch**
Dependent on #2329

### CODE REVIEW

**Comment by stwunsch** [comment]
Should I translate this as well to python?

**Comment by etejedor** [comment]
@stwunsch it would be great but `Take` is not supported (yet) from Python.

**Comment by etejedor** [comment]
LGTM!
My only doubt here is if we will ever want `RVec`s to be used from Python, or we will just expose them as NumPy arrays, but it certainly does not hurt to have this tutorial.

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@dpiparo do you think the python tutorial makes sense?

**Comment by stwunsch** [comment]
I'll adapt the docs based on #2351.

**Comment by stwunsch** [comment]
Gonna be included in #2351.

**Pull request closed without merging**
