### PR TITLE
[windows] work-around a compiler bug with VS 2022 v17.6.0

### PR DESCRIPTION
**Pull request by bellenot**
Fix a crash in root.exe due to a compiler bug with Visual Studio 2022 v17.6.0. The fix works the same way than it is supposed to do, since the (never reached) `default: break;` statement make the function returns `HasREX` anyway. To be reviewed and removed as soon as VS works again

### CODE REVIEW

**Comment by hahnjo** [comment]
sorry for the warning, addressed by https://github.com/root-project/root/pull/13073

**Review by hahnjo — CHANGES_REQUESTED** [review]
This needs to be synced into the monorepo. I can take care of that tomorrow, if we also agree on merging soon after (I'd like https://github.com/root-project/root/pull/13049 to go in before Monday).

**Comment by bellenot** [comment]
> Did you have a look if that’s not already fixed in llvm upstream and possibly backport the fix/workaround?

Yes, the whole file is completely different...

**Comment by hahnjo** [comment]
> > Did you have a look if that’s not already fixed in llvm upstream and possibly backport the fix/workaround?
> 
> Yes, but the whole file is completely different

The `switch` statement is still there:
https://github.com/llvm/llvm-project/blob/3ea8f2526541884e03d5bd4f4e46f4eb190990b6/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp#L812-L815
However, there are now function calls before the `return`, so potentially the compiler bug doesn't trigger...

**Review by hahnjo — APPROVED** [review]
I updated the monorepo and changed `interpreter/llvm/llvm-project.tag`, so should be good from that perspective.

I discussed with Bertrand, and this work-around is required to get ROOT compiling with the latest compiler. I think we should do this, even temporarily, until the compiler is fixed.

**Review by vgvassilev — APPROVED** [review]

**Pull request merged**
