### PR TITLE
Adding function to normalize TH1 objects.

### PR DESCRIPTION
**Pull request by dvotaw**

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
Is it really worth it introducing a new method while `TH1::Scale(1.0)` does exactly the same?

**Comment by lmoneta** [comment]
I think it is worth having this method, also to clarify the confusion happening when normalising histograms, see https://root-forum.cern.ch/t/different-ways-of-normalizing-histograms/15582

I would however add the option "width" which will internally call 
hist->Scale(1./integral, "width") which will normalising by dividing the bin width. 

Lorenzo

**Comment by bellenot** [comment]
@dvotaw please fork also roottest in order to prevent the build failure on `windows10/cxx14`

**Comment by dvotaw** [comment]
@bellenot, I've forked roottest now too. Is there a way to try the build again?

@phsft-bot build

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by dvotaw** [comment]
@bellenot I don't see how TH1::Scale(1.0) does the same thing. Doesn't that just scale the histogram by 1.0, leaving it exactly the same? This function scales it to unit integral.

@lmoneta I didn't realize that TH1::Scale() had the "option" argument. I'll rewrite this function to include the bin width option, as you suggested.

**Pull request closed without merging**
