### PR TITLE
Revert "[DF] Disable also distributed tutorials on Mac ARM"

### LINKED ISSUE #10061: Distributed RDataFrame test failures on Mac/ARM
### Describe the bug

Distributed RDataFrame roottest has been failing for a while on Mac (11 or 12) on ARM. Here is an example stacktrace (up until the calls to cling)

```
-- TEST COMMAND -- 
cd /Users/sftnight/build/workspace/roottest-pullrequests-build/build/roottest/python/distrdf/dask
/usr/bin/python3 /Users/sftnight/build/workspace/roottest-pullrequests-build/roottest/python/distrdf/dask/test_backend.py --fixcling
-- BEGIN TEST OUTPUT --
Assertion failed: (isInt<33>(Addend) && "Invalid page reloc value."), function encodeAddend, file /Users/sftnight/build/workspace/roottest-pullrequests-build/root/interpreter/llvm/src/lib/ExecutionEngine/RuntimeDyld/Targets/RuntimeDyldMachOAArch64.h, line 210.
 *** Break *** abort
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCore.6.27.01.so] TUnixSystem::DispatchSignals(ESignals) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/usr/lib/system/libsystem_pthread.dylib] pthread_kill (no debug info)
[/usr/lib/system/libsystem_c.dylib] abort (no debug info)
[/usr/lib/system/libsystem_c.dylib] err (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::RuntimeDyldMachOAArch64::encodeAddend(unsigned char*, unsigned int, llvm::MachO::RelocationInfoType, long long) const (.cold.6) (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::RuntimeDyldMachOAArch64::encodeAddend(unsigned char*, unsigned int, llvm::MachO::RelocationInfoType, long long) const (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::RuntimeDyldImpl::resolveLocalRelocations() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::RuntimeDyldImpl::resolveRelocations() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::RuntimeDyld::finalizeWithMemoryManagerLocking() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::orc::LegacyRTDyldObjectLinkingLayer::ConcreteLinkedObject<std::__1::shared_ptr<llvm::RuntimeDyld::MemoryManager> >::finalize() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::orc::LegacyRTDyldObjectLinkingLayer::ConcreteLinkedObject<std::__1::shared_ptr<llvm::RuntimeDyld::MemoryManager> >::getSymbolMaterializer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::'lambda'()::operator()() const (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::JITSymbol::getAddress() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::orc::LazyEmittingLayer<llvm::orc::LegacyIRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler> >::EmissionDeferredModule::find(llvm::StringRef, bool, llvm::orc::LegacyIRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler>&)::'lambda'()::operator()() const (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] llvm::JITSymbol::getAddress() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] cling::IncrementalJIT::getSymbolAddress(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] cling::IncrementalExecutor::getPointerToGlobalFromJIT(llvm::StringRef) const (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] cling::Interpreter::compileFunction(llvm::StringRef, llvm::StringRef, bool, bool) (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] TClingCallFunc::make_wrapper() (no debug info)
[/Users/sftnight/build/workspace/roottest-pullrequests-build/build/lib/libCling.6.27.01.so] TClingCallFunc::IFacePtr() (no debug info)
```

Currently, the interested tests are disabled in roottest https://github.com/root-project/roottest/pull/839 .
The PR https://github.com/root-project/root/pull/10050 wasn't enough to fix these tests, so further debugging is needed. 

### Expected behavior

Tests should pass on all Mac ARM platforms

### PR DESCRIPTION
**Pull request by hahnjo**
This reverts commit 4c669d4ead82c3b328eaebc7f160a119c4dad31d.

Fixes #10061

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11arm/default, mac12arm/default, mac13arm/default

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11arm/default, mac12arm/default, mac13arm/default

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11arm/default, mac12arm/default, mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by hahnjo** [comment]
The two `distrdf00*` tutorials passed on `mac13arm` :smiley:

**Review by vepadulano — APPROVED** [review]
Nice :smile:

**Pull request merged**
