### PR TITLE
[JupyROOT][11048] Fixes in imports

### LINKED ISSUE #11048: Resolve the alerts produced by "LGTM analysis: Python"
`LGTM analysis: Python` is "picking" code inside of ROOT, which has unnecessary imports. 
We saw that only writing `import ROOT` led to 4 alerts from the LGTM tool.
Example:
> This pull request **introduces 4 alerts** and **fixes 10** when merging 30c5db08c504abc8f4c3f7b822defecf5157dcc4 into 56c28ff3b846c74f8c36c53320d381545f6b31f9 - [view on LGTM.com](https://lgtm.com/projects/g/root-project/root/rev/pr-90c6dd66f4cf355944bc8bc93a3e2749fe003f60)
> 
> **new alerts:**
> 
> * 2 for Unused import
> * 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
> 
> **fixed alerts:**
> 
> * 10 for Module\-level cyclic import

(https://github.com/root-project/root/pull/11038#issuecomment-1194049285)

fyi: @j-mathe

### PR DESCRIPTION
**Pull request by etejedor**
Fixes #11048 according to the LGTM report:

https://lgtm.com/projects/g/root-project/root/rev/pr-90c6dd66f4cf355944bc8bc93a3e2749fe003f60

### CODE REVIEW

**Review by ikabadzhov — APPROVED** [review]
Great! Thank you Enric :)

**Comment by ikabadzhov** [comment]
> This pull request **fixes 2 alerts** when merging [e61c8e2](https://github.com/root-project/root/commit/e61c8e28c12e7be3499173582c3e276443a42e58) into [60e14f2](https://github.com/root-project/root/commit/60e14f283e4034ed7b85b58f3a26e4eb282983b8) - [view on LGTM.com](https://lgtm.com/projects/g/root-project/root/rev/pr-5e457dc1573e05d74adef855680dd865dab49179)
> 
> **fixed alerts:**
> 
> * 1 for Unused import
> * 1 for Module is imported with 'import' and 'import from'

@etejedor oh oh! that doesn't look good!

**Comment by etejedor** [comment]
@ikabadzhov what does not look right?

**Comment by ikabadzhov** [comment]
> @ikabadzhov what does not look right?

2 fixed alerts. It is all good. Sorry for the noise.

**Pull request merged**
