### PR TITLE
Backport ROOT-9872 and ROOT-9660

### PR DESCRIPTION
**Pull request by yamaguchi1024**
ROOT-9872 is a fix of ROOT-9660, which was backported to 6.14, but not in 6.16.

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
@phsft-bot build

**Comment by yamaguchi1024** [comment]
@dpiparo , it's ok to backport 1bee3d132c8a1df5fe84ba5cb77949e2fe5db09f to 6.16, right?

**Comment by Axel-Naumann** [comment]
Yes let's backport. Yuka, could you have a look at the rebase conflicts?

**Comment by yamaguchi1024** [comment]
Hah, it looks that someone already merged those commits

**Pull request closed without merging**
