### PR TITLE
[RF] Support changing constant vs. floating parameter flag for fits with gradients from codegen AD

### PR DESCRIPTION
**Pull request by guitargeek**
For our users, it's important to fix certain parameters in the likelihood easily with any overhead.

So far, this didn't work when using gradients from AD, because the gradients were only produced for the parameters that are floating at the time where the likelihood is created. However, it has no additional runtime overhead in backwards AD mode to simply generate the gradient for **all** parameters, and then filter out the right elements in the the RooMinimizer-related code.

This is what is implemented in the second commit of this PR.

Some changes in the RooAbsMinimizerFcn were necessary to do this filtering: so far it didn't store any information on all the parameters in order. It only stored two separate lists for floating and constant parameters.

The first commit in this PR adds the necessary data members (`_allParams` and `_allParamsInit`) to the RooAbsMinimizerFcn for the filtering of parameters. Furthermore, the previous datamembers that stored the parameters separately are removed to avoid duplication and possible desync of information. On this occasion, the parameter management was completely rewritten to be more concise and robust. This will also help later when we integrate the discrete profiling from CMS combine, where changing the state and filtering of minimization parameters is also relevant.

It was validated with the ATLAS and CMS likelihoods from ICHEP 2024 that this PR results in no performance regression, even though we are now generating the gradient for more parameters (roughly up to two times more, because for every floating nuisance parameter there is usually one constant global observable that constrains it).

### CODE REVIEW

**Review by vgvassilev — COMMENTED** [review]
Any chance for a test?

**Comment by guitargeek** [comment]
Good idea. I have beefed up an existing unit test to cover the functionality, and added a commit for it. Another commit fixes a possible out-of-bounds access that I noticed on the way.

**Comment by guitargeek** [comment]
That's true, we need to think how we can reuse the benchmarks from `rootbench` as tests without causing too much duplication

**Review by vgvassilev — APPROVED** [review]
A weak LGTM. If you are not confident that's enough probably wait for @lmoneta.

**Comment by guitargeek** [comment]
Thanks a lot! Understandable, this is quite a big refactoring, even if it shouldn't change any behavior other than adding better support for flipping constant and floating parameters in codegen.

**Pull request merged**
