### PR TITLE
Set builtin_afterimage=ON for all platforms

### PR DESCRIPTION
**Pull request by bellenot**
See the Github issue #14247

### CODE REVIEW

**Review by guitargeek — APPROVED** [review]

**Review by dpiparo — APPROVED** [review]
For me the change is fine. Thanks.
Perhaps a question at this point: what is the point of offering the option of having a builtin afterimage if we know it does not work?

**Comment by bellenot** [comment]
> For me the change is fine. Thanks. Perhaps a question at this point: what is the point of offering the option of having a builtin afterimage if we know it does not work?

Good question. Maybe @couet knows why we have this option?

**Comment by ferdymercury** [comment]
> > For me the change is fine. Thanks. Perhaps a question at this point: what is the point of offering the option of having a builtin afterimage if we know it does not work?
> 
> Good question. Maybe @couet knows why we have this option?

I guess that in the past, bugs found by the ROOT team were backported to the upstream repo, see e.g.:
https://salsa.debian.org/debian/afterstep/-/blame/69faf352072daddf6e311dea3717734a45c6ac2d/libAfterImage/asimage.c (see copyright from Valeriy Onouchin from CERN)
https://root.cern.ch/root/v520/Version520.news.html

But upstream is now completely frozen.
So... (unless someone wants to upstream the changes again), maybe we could mark the builtin_afterimage option as deprecated now and remove it in a later release.

**Comment by sashavasko** [comment]
I have not done anything with it in at least 10 years, so yeah, you no
longer have to upstream the changes.

Thanks!
Sasha.

**Pull request merged**
