### PR TITLE
CI: remove stray parathensis.

### PR DESCRIPTION
**Pull request by pcanal**
Solves the problem seen at: https://github.com/root-project/root/actions/runs/12508911424/job/34897691604

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]

**Comment by dpiparo** [comment]
Thanks. Does this relate to this PR https://github.com/root-project/root/pull/17335 ? can that one be closed *w/o* merging if this one is merged?

**Comment by dpiparo** [comment]
we did not see any last night: what problem?

**Comment by pcanal** [comment]
I don't know why this code is sometimes run sometimes not but it is clearly incorrect (too many closing parenthesis) and is explicitly the cause of the problem seen at https://github.com/root-project/root/actions/runs/12508911424/job/34897691604 on Fedora.

**Comment by pcanal** [comment]
The Windows issues are unrelated.

**Pull request merged**
