### PR TITLE
imt should depend on MultiProc for TExecutor

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
As we discussed it is the correct way to go! LGTM!

**Comment by bellenot** [comment]
FYI multiproc is not supported on Windows

**Comment by xvallspl** [comment]
> FYI multiproc is not supported on Windows. See [these lines in core/CMakeLists.txt](https://github.com/root-project/root/blob/master/core/CMakeLists.txt#L73-L75)

Forgot about that :upside_down_face:

**Comment by hahnjo** [comment]
@xvallspl as reported by Jenkins in multiple builds, this PR leads to failures in `pyunittests-pyroot-import-load-libs` and `roottest-root-tree-fastcloning-execCheckClusterRange` (can reproduce locally). The first looks like it just needs an update to the whitelist, not sure about the second one.

**Comment by xvallspl** [comment]
I'm building locally my patch to the first one already, thanks!

**Pull request merged**
