### PR TITLE
[ntuple] use namespace ROOT::Experimental in RNTupleDescriptor.cxx

### PR DESCRIPTION
**Pull request by silverweed**
precursor of https://github.com/root-project/root/pull/16166

### CODE REVIEW

**Review by hahnjo — COMMENTED** [review]
I don't have a strong opinion on this, I agree it shortens quite a few identifiers and will even make it easier to move classes out of `Experimental`

**Comment by enirolf** [comment]
IMO if we change it here, we should be consistent and change it everywhere and I'm not sure if that is worth the effort. Using the namespace might make it *slightly* easier to move out of `Experimental` but a search and replace all also wouldn't take much effort..

**Comment by silverweed** [comment]
The move out of `Experimental` is not really a driving motivation for this change (I hadn't even considered that), but making the file more information-dense is. Maybe it's only me, but I find it akin to obfuscation to have half of the page covered in namespaces and it makes the code harder to read for no real benefit (in this case).

I agree that we should be consistent with it, but I think it can be a gradual process as there is no practical harm in having an inconsistent state for some time (less harm than, say, having some of the files not being properly clang-formatted, which is a real waste of time in some cases).

**Comment by jblomer** [comment]
As discussed, let's close it for the time being. The situation will look different with RNTuple classes moving out of experimental.

**Pull request closed without merging**
