### PR TITLE
Partially revert the previous commit (only keep what is really needed)

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
Could you be more explicit in the commit log (i.e. which commit is being reverted and why)?  Thanks.

**Comment by bellenot** [comment]
Well, there is simply no need of `gSystem->UnixPathName` all over the place...

**Comment by pcanal** [comment]
Fair enough.  The commit log is still a bit cryptic without looking at the content and then 'guessing' which 'previous' commit this is reverting :)

**Comment by bellenot** [comment]
I agree, sorry...

**Comment by bellenot** [comment]
@phsft-bot build please

**Comment by bellenot** [comment]
@phsft-bot build just on slc6/gcc62

**Pull request merged**
