### PR TITLE
clang-format on minuit2

### PR DESCRIPTION
**Pull request by HDembinski**
This applies clang-format according to ROOT's .clang-format style to the whole Minuit2 code.

### CODE REVIEW

**Comment by HDembinski** [comment]
@lmoneta This is a follow-up on the discussion in #6705, to apply clang-format to the Minuit2 code. This will probably trigger quite a few warnings from clang-tidy, although the patch should not change any code meaning. I would be interested in a follow up PR to fix the clang-tidy.

**Comment by HDembinski** [comment]
Whoops, the clang-format test is rejecting my clang-formatting https://travis-ci.org/github/root-project/root/jobs/747788436, I will fix that (passing that is the whole point of this patch...).

The other complaints by clang-tidy and clang-tidy-modernize should be addressed in another PR.

**Comment by HDembinski** [comment]
I investigated the Travis output of the clang-format job and I think the differences come from the fact that I am using clang-format-10, while Travis uses clang-format-7. The changes that clang-format-7 wants are fairly awkward, see e.g.
https://travis-ci.org/github/root-project/root/jobs/747788436#L1313
where it inserts a line break between the class and `operator()`. I would say that the clang-format-10 syntax looks much more reasonable.

Should we keep clang-format-10 or should I try to make it conform to clang-format-7? If I do the latter, it fixes the build now but the formatting will become a problem again once clang-format is eventually updated on Travis.

**Comment by HDembinski** [comment]
I applied clang-format-7, now it should be good. It would be great to merge this quickly, because I have a few other patches prepared that depend on this change.

**Comment by pcanal** [comment]
I would side with using clang-format 10 (more future proof).  This will lead to *this* PR failing but will only affect negatively the PR that touches the lines of code where v7 and v10 disagree.

**Comment by lmoneta** [comment]
Hi Hans, 
Are these only format changes ? Or there are some real code modifications, e.g. for fixing clang-tidy ?

**Comment by lmoneta** [comment]
phsft-bot build with flags -Dminuit2=On

**Comment by lmoneta** [comment]
@phsft-bot build with flags -Dminuit2=On

**Comment by lmoneta** [comment]
clang-format is ok, but there are still failures in clang-tidy. 
Since some of them are related also to the previous ref pointer, I think those can be fixed by a separate PR

**Comment by HDembinski** [comment]
> Hi Hans,
> Are these only format changes ? Or there are some real code modifications, e.g. for fixing clang-tidy ?

@lmoneta There are only automatic formatting changes. I applied clang-format and submitted the output. The only thing I touched by hand is the LinkDef https://github.com/root-project/root/pull/6917/files#diff-11aff2250058e06f01c03bd90530e5299443707f6b06ba7c7c1939c1906bd33e, which clang-format did not format properly. It broke the pragma link C++, so I fixed that manually. That is the only change I did by hand.

**Review by lmoneta — APPROVED** [review]

**Comment by lmoneta** [comment]
Thanks for the reply. It looks good , I will then merge it now

**Pull request merged**
