### PR TITLE
[PyROOT] Add back initializer list pythonization to CPyCppyy

### PR DESCRIPTION
**Pull request by guitargeek**
The patch that disables the initializer list pythonization should in principle not be necessary.

@aaronj0, let's see which tests were actually failing because of this.

### CODE REVIEW

**Comment by aaronj0** [comment]
This fixes https://github.com/root-project/root/issues/16469

**Review by aaronj0 — APPROVED** [review]
LGTM!

**Comment by aaronj0** [comment]
Hi, @hahnjo, yes we probably want to look into why this fails on python 3.8...
This enabled an aggregate initializer constructor that was required to fix a user issue and also got rid of a patch. I don't see anything in that block that could vary with python versions but it would be helpful if you can provide the verbose error log

**Comment by guitargeek** [comment]
We will investigate and reproduce the error. I can still install Python 3.8 from the Arch User Repository, fortunately :)

It's true that Python 3.8 is the oldest version that we still support. That was defined last year, because Python 3.8 was the oldest version that was not EOL yet. However, 3.8 will be end-of-life next month: https://devguide.python.org/versions/

So maybe something to ask @vepadulano: did you intend to follow the precedent of 6.32 and only support Python versions that are not EOL by the release of 6.34?

**Comment by hahnjo** [comment]
Running `roottest-python-basic-datatype` under `gdb`:
```
#0  0x00007ffff63ee52f in raise () from /lib64/libc.so.6
#1  0x00007ffff63c1e65 in abort () from /lib64/libc.so.6
#2  0x00007ffff63c1d39 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ffff63e6e86 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffeab9b265 in cling::Transaction::addNestedTransaction (this=<optimized out>, nested=<optimized out>) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Transaction.cpp:98
#5  0x00007fffeaad2f23 in cling::IncrementalParser::beginTransaction (this=0x555555c3bee0, Opts=...) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:496
#6  0x00007fffeaac4776 in cling::Interpreter::PushTransactionRAII::PushTransactionRAII (this=0x7fffffff7338, i=<optimized out>)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:105
#7  0x00007fffeaa5b252 in ClingMemberIterInternal::DCIter::DCIter (this=0x7fffffff73d0, DC=0x555557208818, interp=0x0) at /home/jhahnfel/ROOT/src/core/metacling/src/TClingMemberIter.cxx:21
#8  0x00007fffeaa57951 in TClingMemberIter::TClingMemberIter (this=0x7fffffff73b8, interp=0x555555803e60, DC=0x7fffffff6ff0) at /home/jhahnfel/ROOT/src/core/metacling/src/TClingMemberIter.h:145
#9  TClingDataMemberIter::TClingDataMemberIter (this=0x7fffffff73b8, interp=0x555555803e60, DC=0x7fffffff6ff0, selection=TDictionary::EMemberSelection::kNoUsingDecls)
    at /home/jhahnfel/ROOT/src/core/metacling/src/TClingDataMemberInfo.h:66
#10 TClingDataMemberInfo::TClingDataMemberInfo (this=0x55555b2f2b30, interp=0x555555803e60, ci=<optimized out>, selection=TDictionary::EMemberSelection::kNoUsingDecls)
    at /home/jhahnfel/ROOT/src/core/metacling/src/TClingDataMemberInfo.cxx:115
#11 0x00007fffea9c66da in TCling::DataMemberInfo_Factory (this=0x555555b29730, clinfo=0x55555a9b6510, selection=TDictionary::EMemberSelection::kNoUsingDecls)
    at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:8599
#12 0x00007ffff09982d1 in TListOfDataMembers::Load (this=0x55555a9a6d40) at /home/jhahnfel/ROOT/src/core/meta/src/TListOfDataMembers.cxx:469
#13 0x00007ffff098162e in TClass::CreateListOfDataMembers (this=0x55555a9df5b0, data=..., selection=TDictionary::EMemberSelection::kNoUsingDecls, load=true)
    at /opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/atomic_base.h:837
#14 0x00007fffea9c2cce in TCling::InvalidateCachedDecl (this=0x555555b29730, Lists=..., D=0x55555b60ad18) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:6928
#15 0x00007fffea9a161f in TCling::UpdateListsOnUnloaded (this=0x555555b29730, T=...) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:6866
#16 0x00007fffeaacfd7c in cling::MultiplexInterpreterCallbacks::TransactionUnloaded (this=<optimized out>, T=...)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/MultiplexInterpreterCallbacks.h:109
#17 0x00007fffeaacc901 in cling::Interpreter::unload (this=0x555555803e60, T=...) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:1543
#18 0x00007fffeaad3f97 in cling::IncrementalParser::commitTransaction (this=0x555555c3bee0, PRT=..., ClearDiagClient=true)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:609
#19 0x00007fffeaad4ab1 in cling::IncrementalParser::Compile (this=0x555555c3bee0, input=..., Opts=...) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:849
#20 0x00007fffeaac91af in cling::Interpreter::DeclareInternal (this=this@entry=0x555555803e60,
    input="namespace __cppyy_internal {\nvoid init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}) {\n  self = new tuple<strin
g,unsigned lo"..., CO=..., T=T@entry=0x0) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:1369
#21 0x00007fffeaac7599 in cling::Interpreter::declare (this=0x555555803e60,
    input="namespace __cppyy_internal {\nvoid init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}) {\n  self = new tuple<strin
g,unsigned lo"..., T=0x0) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:1001
#22 0x00007fffea9b4595 in TCling::LoadText (this=this@entry=0x555555b29730,
    text=text@entry=0x55555b5ea750 "namespace __cppyy_internal {\nvoid init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}) {\
n  self = new tuple<string,unsigned lo"...) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:7513
#23 0x00007fffea9b43a8 in TCling::Declare (this=0x555555b29730,
    code=0x55555b5ea750 "namespace __cppyy_internal {\nvoid init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}) {\n  self = n
ew tuple<string,unsigned lo"...) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:3110
#24 0x00007fffd791d557 in CPyCppyy::Pythonize (pyclass=pyclass@entry=0x55555b20f290, name="tuple<string,unsigned long>")
    at /home/jhahnfel/ROOT/src/bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx:1778
```

**Comment by aaronj0** [comment]
Thanks!

This acutually does not work on any python version, since this code block enables the aggregate initializer list constructor for all classes even those in the `std` namespace that don't have them. Then the call to `Cppyy::Compile` does not work since it's invalid.

We should do a scope check different from  `name.compare(0, 5, "std::", 5) != 0` since ROOT drops the `std` namespace

**Comment by guitargeek** [comment]
I suspect that in the case of the failing tests it's more tricky than that. We're dealing with `std::tuple` there, which internally is represented by `TEmulatedTuple` for IO reasons. That's what is tripping up the Pythonization code, which suddenly thinks `std::tuple` is an aggregate just because `TEmulatedTuple` is.

Does the crash go away if you're extending the relevant if statement like this?
```python
    if (Cppyy::IsAggregate(((CPPClass*)pyclass)->fCppType)
            && name.compare(0, 6, "tuple<", 6) != 0
            && name.compare(0, 5, "std::", 5) != 0) {
```
https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx#L1723C9-L1723C59

Sorry, I can't test it myself because on my Python 3.8 there is no crash.

**Comment by guitargeek** [comment]
Reproducer of the ROOT meta behavior, which rightfully confuses cppyy:
```txt
root [0] TClass *cl = gROOT->GetClass("tuple<int,float,string,double>");
root [1] cl->ClassProperty() && kClassIsAggregate;
(bool) true
```

**Comment by hahnjo** [comment]
> Does the crash go away if you're extending the relevant if statement like this?

Yes, this fixes the two tests on my end AFAICT :tada: I'll re-run all tests now to see if it has any other unintended effect.

**Comment by hahnjo** [comment]
@aaronj0 @guitargeek can we do something about this? The tests are still failing for me :anguished:

**Pull request merged**
