### PR TITLE
[ntuple] Add ROOTv7 revised climate tutorial

### PR DESCRIPTION
**Pull request by JohnYoon13**

### CODE REVIEW

**Comment by JohnYoon13** [comment]
Replaces previous #6808.

**Review by linev — APPROVED** [review]
Yes, finally we get it right!

**Comment by oshadura** [comment]
@phsft-bot build!

**Review by eguiraud — COMMENTED** [review]
Hi,
sorry for being a bore, RDF still performs around 6 event loops rather than 1, e.g. these are 2 event loops:

```c++
   auto minimum_value = df.Min("AverageTemperature");
   cout << "\nThe Minimum temperature is: " << *minimum_value << std::endl;
   auto max_value = df.Max("AverageTemperature");
   cout << "The Maximum temperature is: " << *max_value << std::endl;
```

and these are other 2:

```c++
   auto decade_1993_to_2002_Count = *df1993_to_2002.Count();
   auto decade_2003_to_2013_Count = *df2003_to_2013.Count();
```

Can we book all operations before using the results?
You can also call out the start of the event loop explicitly by using [RunGraphs](https://root.cern/doc/master/namespaceROOT_1_1RDF.html#a593de50d0cdd34b731b23ef4729918b1) if you prefer.

In case it helps: in current master you can now activate RDF's verbose mode that will notice of event loop starts/ends with:

```c++
auto logRAII = ROOT.Experimental.RLogScopedVerbosity(ROOT.Detail.RDF.RDFLogChannel(), ROOT.Experimental.ELogLevel.kInfo);
```

**Comment by bellenot** [comment]
@JohnYoon13 please fork also [roottest](https://github.com/root-project/roottest), in order to prevent timeout in the Windows nodes. Thanks

**Review by couet — APPROVED** [review]
looks nice to me

**Comment by jblomer** [comment]
> Can we book all operations before using the results?

@eguiraud Thanks! We are going to change it.  I'm wondering if this pattern won't eventually create problems for larger analysis macros because it stretches the space between booking an operation and actually performing the operation.  Has this ever been an issue?

**Comment by jblomer** [comment]
@phsft-bot build!

**Comment by eguiraud** [comment]
> Has this ever been an issue?

not really, but maybe I don't understand the question. what problems would you expect?

**Comment by jblomer** [comment]
> not really, but maybe I don't understand the question. what problems would you expect?

I'm thinking of a macro where somewhere in the first 100 lines you define filters, derived columns, etc. and eventually a Histo1D `histAbc`.  The macro goes on.  In line 300, you start using `histAbc`, position the legend, tune the axis, etc.  At this point, however, you don't see anymore what the histogram contains because it has been defined way up. A bit like variable declarations in Pascal, where they always have to be at the beginning of a function.

**Comment by eguiraud** [comment]
I'm afraid the "book everything first, use results later" is the price to pay to run everything in a single event loop: we need to know what to run before we run it, and at the same time we have to run the event loop to produce the result if you do things with it.

However, by the time you lose track of where things were defined because your analysis is too complex, you probably should restructure your code so that you don't keep everything in a single function. Analyses that produce hundreds or thousands of histograms typically have some bookkeeping logic, they don't keep all results at main scope. Some of the more complex RDF tutorials show some possible ways to do it, e.g. in Python we keep `RResultPtr<TH1D>`s in a dictionary.

There are other possible designs, like e.g. continuations on futures, but I don't think they increase readability/clarity in general.

Anyway, the empirical reply to the original question: we never got the feedback that the "book first, use later" programming model made users lose track of the results.

**Review by jblomer — APPROVED** [review]

**Pull request merged**
