### PR TITLE
Enable I/O for RCutFlowReport

### LINKED ISSUE #14815: Allow ROOT::RDF::RCutFlowReport and ROOT::RDF::TCutInfo to be written to a file.
### Explain what you would like to see improved and how.

Currently you cannot read a ROOT::RDF::RCutFlowReport back from a file because ROOT::RDF::TCutInfo does not have a public constructor. It would be really great to be able to store the RCutFlowReport in a file together with the snapshot of the resulting RDataFrame. This would allow an easy way to keep track of the cut flow in filtered data that is stored back into ROOT files.

It would be nice if you could do (PyROOT example here):

```
import ROOT as R
df = R.RDataFrame("Data","data_file.root")
df_filtered = df.Filter("x>10","xcut").Filter("y>10","ycut")
report = df_filtered.Report()
df_filtered.SnapShot("tmp","test_file.root")
file = R.TFile("test_file.root","UPDATE")
file.WriteObject(report.GetValue(),"cut_flow")
file.Close()
```

The above code works, but the "cut_flow" in the file cannot be read back. 
I am not sure this is because TCutInfo cannot be read back from a file because of the lack of a public constructor, but it appears to be the case.

### ROOT version

ROOT 6.31/01 

### Installation method

build from source obtained from GitHub master

### Operating system

MacOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #14815

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]
Thanks for this improvement and test. At the time of writing, the persistification was not considered, but makes sense. Could you please also select in the LinkDef file TCutInfo as well?

**Comment by dpiparo** [comment]
And also, apologies for this, should we rename TCutInfo to RCutInfo before making it writeable? I think we simply forgot to rename that ancillary class when TDataFrame was renamed into RDataFrame...

**Comment by vepadulano** [comment]
> And also, apologies for this, should we rename TCutInfo to RCutInfo before making it writeable? I think we simply forgot to rename that ancillary class when TDataFrame was renamed into RDataFrame...

This class has been in the public namespace for years, so I don't think we can do that. What we can do is we can make an `RCutInfo` class, then alias `using TCutInfo = RCutInfo;`. How does that sound?

**Comment by dpiparo** [comment]
Thanks: that escaped my attention. I propose we keep the name as it is and select it in the Linkdef.

**Pull request merged**
