### PR TITLE
[winxxmodules] Create vcruntime.modulemap for use in Windows

### PR DESCRIPTION
**Pull request by gargvaibhav64**
This PR continues the work in #5376. It creates a vcruntime.modulemap file which is loaded before libc and std modulemaps in order to fix several include errors.

@vgvassilev @bellenot

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by bellenot** [comment]
Check the [formatting report](https://travis-ci.org/github/root-project/root/jobs/685505719)

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by gargvaibhav64** [comment]
vcruntime.pcm is now successfully generated. 

Also, @bellenot Travis CI should pass now.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
