### PR TITLE
[wincxxmodules] Fix std and libc modules on Windows

### PR DESCRIPTION
**Pull request by gargvaibhav64**
This PR fixes compilation issues of std.modulemap and libc.modulemap on Windows. This is a core step towards Enabling the Modules support in Windows.

@vgvassilev @bellenot

### CODE REVIEW

**Comment by gargvaibhav64** [comment]
Removed commented out header used in testing.

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@gargvaibhav64 looks like we need some more adjustment. The header `bit` seems to be missing on that particular platform. Could you check if there is some documentation available hinting if that's expected?

**Comment by gargvaibhav64** [comment]
@vgvassilev, Yes, bit requires C++20 support according to the official Microsoft documentation [here](https://github.com/microsoft/STL/blob/master/stl/inc/bit#L12). Hence, build failed as it was compiled on C++14.

**Comment by bellenot** [comment]
> @vgvassilev, Yes, bit requires C++20 support according to the official Microsoft documentation [here](https://github.com/microsoft/STL/blob/master/stl/inc/bit#L12). Hence, build failed as it was compiled on C++14.

Can you use the `__cplusplus macro` to check the c++ version and protect unsupported headers?

**Comment by gargvaibhav64** [comment]
> Can you use the `__cplusplus` macro to check the c++ version and protect unsupported headers?

I have added a [check](https://github.com/root-project/root/blob/39fc632526d243bafc171ac1b0bf872b2b192a72/interpreter/cling/include/cling/std_msvc.modulemap#L23) in the modulemap files to detect C++ versions for the headers that require a specific version. I am not sure if `__cplusplus` macro can be used in the modulemap files.

Please run the build so that we can test it.

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by gargvaibhav64** [comment]
@bellenot Please also build on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by bellenot** [comment]
> @bellenot Please also build on windows10/cxx14 with flags -Druntime_cxxmodules=On

Will do, after the current build is over

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@gargvaibhav64 I suspect we need the same of `xthreads.h`.

**Comment by gargvaibhav64** [comment]
@vgvassilev, Yes, added

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

@Axel-Naumann can we whitelist @gargvaibhav64 to trigger the bot automatically on a PR change?

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=ON

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=ON

**Comment by Axel-Naumann** [comment]
> can we whitelist @gargvaibhav64 to trigger the bot automatically on a PR change?

I've invited him!

**Comment by gargvaibhav64** [comment]
Thanks a lot sir @Axel-Naumann!

**Pull request merged**
