### PR TITLE
[CI] Add `xgboost` and `scikit-learn` to requirements

### PR DESCRIPTION
**Pull request by guitargeek**
This should be added so we can test RBDT in the CI.

### CODE REVIEW

**Comment by vepadulano** [comment]
Every platform will fail for the following reasons:

* On linux, because the images at https://github.com/root-project/root-ci-images only pick up the requirements.txt file from master, and are rebuilt nightly. The changes in this PR are not picked up by the linux images, but they are seen by the `dependency_versions.py` unit test which checks for all the packages present in the `requirements.txt`
* On other platforms, also because this addition will not trigger an actual installation of the package

The issue here is that if we merge this as-is, our nightlies will go red until every non-linux node gets this package installed...

**Comment by guitargeek** [comment]
Thank you so much @vepadulano for installing the packages on the mac nodes!

The existing RBDT tests are failing, which is good to see so that means they are executed. It's probably the first time ever they get run with XGBoost 2.0 on any CI.

I will add a commit that fixes the tests.

**Comment by vepadulano** [comment]
>  It's probably the first time ever they get run with XGBoost 2.0 on any CI.

It is the first time ever they are run! https://github.com/root-project/root/blob/e3aecd6e49fe19a323c1fcc56572eb99c6f1b46e/tmva/tmva/test/CMakeLists.txt#L34-L39

**Comment by guitargeek** [comment]
Great that we see the result of these tests now. I added a commit to fix them (the breakage was because of some major changes in the recently-released XGBoost 2.0).

**Comment by vepadulano** [comment]
After the latest commit, I tested this on my Mac machine and I see the following categories of errors for the test
```
Traceback (most recent call last):
  File "/Users/vpadulan/Programs/rootproject/rootsrc/tmva/tmva/test/rbdt_xgboost.py", line 113, in test_XGBRegression_branchless
    _test_XGBRegression("TMVA::Experimental::BranchlessForest<float>", "branchlessForest")
  File "/Users/vpadulan/Programs/rootproject/rootsrc/tmva/tmva/test/rbdt_xgboost.py", line 39, in _test_XGBRegression
    ROOT.TMVA.Experimental.SaveXGBoost(xgb, "myModel", "testXGBRegression{}.root".format(label), num_inputs=10)
  File "/Users/vpadulan/Programs/rootproject/rootbuild/xgboost-testing/lib/ROOT/_pythonization/_tmva/_tree_inference.py", line 93, in SaveXGBoost
    fill_arrays(tree, 0, len_inputs * i_tree, len_thresholds * i_tree)
  File "/Users/vpadulan/Programs/rootproject/rootbuild/xgboost-testing/lib/ROOT/_pythonization/_tmva/_tree_inference.py", line 72, in fill_arrays
    thresholds[thresholds_base + index] = node["leaf"]
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float& std::vector<float>::operator[](vector<float>::size_type __n) =>
    TypeError: must be real number, not NoneType
```

```
======================================================================
FAIL: test_XGBBinary_branchless (__main__.RBDT.test_XGBBinary_branchless)
Test BranchlessForest backend for model trained with binary XGBClassifier
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vpadulan/Programs/rootproject/rootsrc/tmva/tmva/test/rbdt_xgboost.py", line 77, in test_XGBBinary_branchless
    _test_XGBBinary("TMVA::Experimental::BranchlessForest<float>", "branchlessForest")
  File "/Users/vpadulan/Programs/rootproject/rootsrc/tmva/tmva/test/rbdt_xgboost.py", line 29, in _test_XGBBinary
    np.testing.assert_array_almost_equal(y_xgb, y_bdt)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/vpadulan/Programs/python-venvs/root-dev/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1034, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/vpadulan/Programs/python-venvs/root-dev/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

Mismatched elements: 1000 / 1000 (100%)
Max absolute difference: 0.34220904
Max relative difference: 0.78311133
 x: array([0.698255, 0.875646, 0.785947, 0.813333, 0.254368, 0.882497,
       0.74103 , 0.150452, 0.859295, 0.71447 , 0.637931, 0.218663,
       0.338688, 0.2761  , 0.488564, 0.569222, 0.849197, 0.854105,...
 y: array([0.697412, 0.87521 , 0.785273, 0.812725, 0.26237 , 0.882081,
       0.740262, 0.149942, 0.817386, 0.713653, 0.637007, 0.555826,
       0.326997, 0.275301, 0.487565, 0.568241, 0.848684, 0.853606,...
```

Which is a further demonstration that this test was never run. I propose we disable the test, to avoid having the CI needlessly red.

The test should be re-enabled then by https://github.com/root-project/root/pull/15173 which is the actual fix for this buggy behaviour

**Review by vepadulano — APPROVED** [review]
Thank you for the quick debugging!

**Pull request merged**
