### PR TITLE
[df] Add function to check if dataframe origin is TTree or TChain

### PR DESCRIPTION
**Pull request by kristupaspranc**

### CODE REVIEW

**Comment by pcanal** [comment]
In which context is this needed/useful?

**Comment by kristupaspranc** [comment]
For RBatchGenerator. @vepadulano will review the code and say if it is needed.
Apologies for not providing the context.

**Comment by vepadulano** [comment]
Thank you @kristupaspranc for this addition! Indeed in the RBatchGenerator this information is nice to have. It turns out that a similar approach improves also the code for distributed RDataFrame, I opened a PR https://github.com/root-project/root/pull/15554 that I believe gives you respects functionally the same goal as this one. In your case you could just check in the batch generator code for `if (GetDataSourceLabel(df) == "TTreeDS")`.

**Comment by kristupaspranc** [comment]
Yes, the functionality is exactly what the `RBatchGenerator` also needs. The primary idea itself was copied from the inner file of `RDataFrame`. Closing the PR

**Pull request closed without merging**
