### PR TITLE
Allow for dynamic switching of system of units between Geant4 units a…

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
- Allow to steer the unit switching between Geant4 units and ROOT units with an unlock mechanism. The (un)lock mechanism can be enabled by a static member of the TGeoManager
- Adapt the GDML parser and writer accordingly to output the correct units.

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build please

**Review by agheata — CHANGES_REQUESTED** [review]
This is fine, but we need the usage explained in a README_units.md file if possible.

**Review by agheata — APPROVED** [review]

**Comment by ianna** [comment]
@smuzaffar - we'll need an update to our external root tool including this PR. This will also trigger an update to dd4hep.
@cvuosalo, @civanch and @dpiparo - FYI

**Comment by smuzaffar** [comment]
sure @ianna . I guess we need these changes in ROOT 6.22 branch too.

**Comment by agheata** [comment]
Squashed in a single commit

**Comment by Axel-Naumann** [comment]
@agheata can you backport to v6.22, please?

**Comment by oshadura** [comment]
Hi @MarkusFrankATcernch @agheata! I am getting a failure in my PR that could be related to these changes: 
```  UpperLimitMCSModule.cxx
17:05:33  TGDMLParse.obj : error LNK2019: unresolved external symbol "protected: static enum TGeoManager::EDefaultUnits TGeoManager::fgDefaultUnits" (?fgDefaultUnits@TGeoManager@@1W4EDefaultUnits@1@A) referenced in function "public: __thiscall TGDMLParse::TGDMLParse(void)" (??0TGDMLParse@@QAE@XZ) [C:\build\workspace\root-pullrequests-build\build\geom\gdml\Gdml.vcxproj]
17:05:33  TGDMLWrite.obj : error LNK2001: unresolved external symbol "protected: static enum TGeoManager::EDefaultUnits TGeoManager::fgDefaultUnits" (?fgDefaultUnits@TGeoManager@@1W4EDefaultUnits@1@A) [C:\build\workspace\root-pullrequests-build\build\geom\gdml\Gdml.vcxproj]
17:05:33  C:\build\workspace\root-pullrequests-build\build\bin\libGdml.dll : fatal error LNK1120: 1 unresolved externals [C:\build\workspace\root-pullrequests-build\build\geom\gdml\Gdml.vcxproj]```

**Comment by Axel-Naumann** [comment]
@bellenot - see https://github.com/root-project/root/pull/7165#issuecomment-777607810 - use of static in inline function?

**Comment by agheata** [comment]
> @agheata can you backport to v6.22, please?

Done in 6-22-00-patches

**Comment by agheata** [comment]
@MarkusFrankATcernch why does the enum need to be static?

**Comment by MarkusFrankATcernch** [comment]
I thought of moving it from a static class member (what it was before) to a object member.
Normally this would be better, but then there may be problems when reading files in GDML:
what should be the proper default there, a TGeoManager is the result of reading a GDML file....

**Comment by agheata** [comment]
> However, having the static in an inline accessor is probably a mistake. Should I submit a PR
> with a proper function ?
Yes please

**Pull request merged**
