### PR TITLE
Make sure df103_NanoAODHiggsAnalysis.py can be converted as notebook

### PR DESCRIPTION
**Pull request by couet**
df103_NanoAODHiggsAnalysis.py could not be converted as notebook.
Fix suggested by @vepadulano

### CODE REVIEW

**Review by vepadulano — APPROVED** [review]
The error `run_fast is not defined` seems impossible to me since the function signature literally provides a definition for the variable. Looks more like a bug in jupyter or nbconvert, but if that's really the case then this alternative looks ok to me. A notebook user will just see the comment and decide whether running on the skimmed dataset or the full one.

**Comment by couet** [comment]
Exactly, It looks like a bug in `nbconvert`. This polite the ref guide build.

**Comment by etejedor** [comment]
The problem is that the tutorial is run as a function, and the conversion tool (not `nbconvert`, our tool) ignores the `if __name__ == '__main__'` part, which is what defines `run_fast`.

**Comment by couet** [comment]
Can I merge ?

**Comment by vepadulano** [comment]
> ignores the `if __name__ == '__main__'` part, which is what defines `run_fast`

But shouldn't `run_fast`  be anyway defined since it is a keyword argument of the function?

**Comment by etejedor** [comment]
> But shouldn't run_fast be anyway defined since it is a keyword argument of the function?

No because the function signature is removed, and the code of the function unindented:
https://nbviewer.org/url/root.cern/doc/master/notebooks/df103_NanoAODHiggsAnalysis.py.nbconvert.ipynb

**Comment by couet** [comment]
So the fix is ok ?

**Comment by vepadulano** [comment]
> No because the function signature is removed, and the code of the function unindented:

Ah ok so there's a major change between the python script and the notebook

**Comment by couet** [comment]
Yes it is not all the same.

**Pull request merged**
