### PR TITLE
[RF] Add fully parametrized RooCrystalBall class

### PR DESCRIPTION
**Pull request by guitargeek**
RooFit currently includes the `RooCBShape` and `RooDSCBShape` to
represent the family of crystal ball distributions. The `RooCBShape`
only has a left tail, and `RooDSCBShape` has two independently
parametrized tails.

Some users also want a crystal ball where the width of the Gaussian
core is different on the left and the right side (see e.g. Jira ticket
[ROOT-10388](https://sft.its.cern.ch/jira/browse/ROOT-10388)).

To make the RooFit code more maintainable and also cover the use case
of an asymmetric Gaussian core, this commit implements a new
`RooCrystalBall` class that should cover all classes of crystal ball
shapes, such that `RooCBShape` and `RooDSCBShape` are in principle not
necessary anymore.

The new features of the `RooCrystalBall` class that make it different
from `RooDSCBShape` are:

 - possibility to set sigma of left side and right side of Gaussian
   core separately

 - code modernization and using `std::` math functions

 - three constructors: fully parametrized, symmetric Gaussian core
   (to replace `RooDSCBShape`), only left tail (to replace
   `RooCBShape`)

 - useage of inlined helper functions to avoid code duplication

It is also carefully tested in `testRooCrystalBal`:

 - test the fully parameterized case

 - test the constructor for left-tail only case and compare values
   with `RooCBShape`

 - test the constructor with symmetric Gaussian core and compare
   values with `RooDSCBShape`

 - test the constructor for right-tail only and symmetric tails

 - test integration with many possible combinations integration
   ranges to cover all branches of integration code

### CODE REVIEW

**Comment by goi42** [comment]
Hi, @guitargeek, sounds good to me! Thanks for doing this.

**Comment by hageboeck** [comment]
> Hi, @guitargeek, sounds good to me! Thanks for doing this.

Only conditionally sounds good to me. If old code doesn't work, any more, users will be really angry that you broke their code. Therefore, and existing model in a file, a script or a framework needs to be able to run with the old definitions.

It's totally fine, though, to write in the docs of the old implementations that for a *new* analysis, one should use the generalised version.

Is that the plan?

**Comment by lmoneta** [comment]
The new class, RooDSShape, has not been release yet, so I think it is still fine to change and mention in the doc. 
Of course we cannot break code using RooCBShape

**Review by lmoneta — APPROVED** [review]
Very nice contribution! Looks great ! 
Thank you Jonas for this !!!

**Pull request merged**
