### PR TITLE
Use nullptr in cling

### PR DESCRIPTION
**Pull request by linev**
Avoid warnings when -Wzero-as-null-pointer-constant is specified

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
I'd really like to avoid having to deal with the conflicts between this and the llvm upgrade. Can we close this and have a new version once the llvm upgrade is in?

**Comment by linev** [comment]
I would like to keep it open - just to have possibility to test against current master.
We can return to the PR once LLVM upgrade done.

**Comment by vgvassilev** [comment]
I would prefer merging #12116 before this change.

**Review by vgvassilev — APPROVED** [review]
LGTM!

@Axel-Naumann, do we need reviews for these trivial/tool-driven refactorings?

**Pull request merged**
