### PR TITLE
[tcling] Temporarily disable loading rdict files.

### PR DESCRIPTION
**Pull request by vgvassilev**
We want to use this pull request to measure the impact on the cmssw.

cc: @smuzaffar, @davidlange6, @Axel-Naumann

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@smuzaffar we'll need your help to know what to do, based on realistic numbers. We would *very* much appreciate if you could compare:

- a ROOT build *without modules*, and *with* this PR (i.e. without rdict.pcm files),
- compared to a ROOT build  *without modules* (still!), *without* this PR (i.e. *with* rdict.pcm files)

I.e. always non-modularized ROOT, with vs without this PR.

We're interested in the change in RSS and real time, for a reco on say a single event with a small event size, e.g. minbias. Do you think you could help us with this?

**Comment by smuzaffar** [comment]
@vgvassilev , please open a PR for cms-sw/root branch cmscxx/master/daff082e92 (which is based on root coomit daff082e92 + changes needed for cxxmodules). Once we have the PR then we can test and integrate it in CXXMODULE IBs

**Comment by vgvassilev** [comment]
@smuzaffar, this is not a modules improvement. We are considering dropping the rdict files for ROOT in general. Should I still open it there?

**Comment by smuzaffar** [comment]
ah ok, yes please then open it against cms/master/007e5f1 branch

**Comment by vgvassilev** [comment]
Thanks. Moved to cms-sw/root#134.

**Pull request closed without merging**
