### PR TITLE
[graf2d] improving TGraph, TCutG, TLine and TArrow classes

### PR DESCRIPTION
**Pull request by linev**
1. Provide support of NDC for TArrow. 
2. Fix interactive movement of TLine/TArrow when NDC coordinates are used
3. Fix TCutG assign operator
4. Provide TGraph::MovePoints() method

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build

**Comment by couet** [comment]
Let me know when you want me to merge

**Comment by linev** [comment]
I just add "trivial" commit to re-start jenkins build.
From my side - code is ready

**Comment by couet** [comment]
let see what if te test will pass

**Comment by linev** [comment]
> let see what if te test will pass

Yes. 
Typically when Jenkins build fails, I have to add new commit to let run builds again - otherwise after `phsft-bot build` message builds aborted very soon

**Comment by couet** [comment]
May be we wait Monday to merge ? always a bit risky to merge just before the week end .....

**Comment by linev** [comment]
> May be we wait Monday to merge ? 

No problem. It is not urgent.

**Comment by couet** [comment]
Ok.. let's do like that.

**Comment by linev** [comment]
@couet Can we merge this PR?

**Comment by couet** [comment]
Yes we can merge I think

**Pull request merged**
