### PR TITLE
Roc curve weights + update

### PR DESCRIPTION
**Pull request by ashlaban**
- ROC curve and integral now respects event weights
- Includes changes introduced by https://github.com/root-project/root/pull/454
- Fixes bug in GetROCIntegral were you would get a different result if called two times in a row
- Fixes line interpolation in plotting
- Some display fixes like labelling of axes

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by ashlaban** [comment]
Fails with this message:
- projectroot.roottest.root.dataframe.roottest_root_dataframe_test_snapshot (from CTest)
- Failing for the past 7 builds (Since #94 )

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by ashlaban** [comment]
I'm still fixing the clang-tidy error :O

Should be done in a minute.

Cheers,
Kim

Lorenzo Moneta wrote:

**Comment by lmoneta** [comment]
Thank you for the PR. It is now merged in the master

 Lorenzo

**Comment by ashlaban** [comment]
Ok!

**Pull request merged**
