### PR TITLE
Make the web gui doc visible in the ref guide

### PR DESCRIPTION
**Pull request by couet**
Many changes to make the webgui doc visible in the ROOT reference guide.
May be the doc could me make a bit more verbose in some places, but at least the structure is there now.

### CODE REVIEW

**Review by bellenot — APPROVED** [review]
Thanks Olivier !

**Review by linev — APPROVED** [review]
Thank Olivier!

**Comment by couet** [comment]
Let's finish the test and we will merge after.

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
There is some failing test but it seems not related to the changes in web gui doc. @linev @bellenot @axel do you think I can merge nevertheless ? .. I guess so...

**Comment by Axel-Naumann** [comment]
Yes please merge

**Pull request merged**
