### PR TITLE
Support for the LZ4 algorithm

### PR DESCRIPTION
**Pull request by bbockelm**
This pull request adds support for the LZ4 compression algorithm (https://code.google.com/p/lz4/).  The code is BSD-licensed.  The pull-request includes a source tarball (allowing a "builtin_lz4" option in CMake analogous to "builtin_lzma").  I am unable to test this on Windows currently.

The LZ4 algorithm focuses on decompression speed while sacrificing compression ratio.  Compression level < 4 uses the "LZ4 compression" algorithm while compression level >= 4 uses "LZ4HC" (HC = high compression) variant.  LZ4HC is comparable to zlib in speeds, but has approximately 20% larger file size.

To evaluate, I use the Event executable in the test/ directory.  I extend this to allow the compression algorithm be specified via CLI.  Example invocation:

time ./Event 4000 6 99 1 1000 4; time ./Event 4000 4 99 0 1000 4

Here, the CLI arguments are:
- 1: Number of events (4000)
- 2: Compression ratio (6)
- 3: Split level (99)
- 4: 1 for write, 0 for read.
- 5: Number of tracks per event (1000).
- 6: Compression algorithm (1 = zlib, 2 = lzma, 4 = lz4.  3 is the deprecated zlib-like algorithm)

I extended MainEvent.cxx to include TTreePerfStats information, which gives us access to the compression-time-only rates.

Performance results (testing on a 2.6GHz Intel Westmere E56xx-based VM) summary:

LZ4HC compression:
- File size: 231MB
- 14.7MB/s CPU time for writing.

ZLIB level-6 compression:
- File size: 189MB
- 10.5MB/s CPU time for writing.
  Summary: LZ4HC compression resulted in a file 20% larger.  Compression time was 44% faster.

LZMA level-6 compression:
- File size: 163MB
- .62MB/s CPU time for writing.
  Summary: LZMA compression resulted in a file 13% smaller.  Compression time was 16x slower than ZLIB level-6

LZ4 decompression:
- 233MB/s CPU time for decompression only.
- 189MB/s CPU time for reading.

ZLIB decompression:
- 118MB/s CPU time for decompression only
- 104MB/s CPU time for reading.
  Summary: LZ4 decompression was 97% faster, resulting in 81%  faster reading for this case.

LZMA decompression:
- 15.4MB/s CPU time for decompression only
- 14.7MB/s CPU time for reading.
  Summary: LZMA decompression was 7x slower than zlib.

### CODE REVIEW

**Comment by bbockelm** [comment]
Note: I plan on doing additional measurements with a CMSSW-produced file.  Doing the PR now so @pcanal can start to provide advice / feedback.

**Comment by bbockelm** [comment]
@pcanal - with regards to my email about TFile::MakeProject bombing out when fed a CMS file - do you have any sample CMS files that ROOT6 can parse without CMS-generated dictionaries?

**Comment by pcanal** [comment]
Hi Brian,

Yes, a much older file:

https://root.cern.ch/files/CMS_7250E9A5-682D-DF11-8701-002618943934.root

Cheers,
Philippe.

**Comment by vgvassilev** [comment]
Could you rebase, please?

**Comment by bbockelm** [comment]
This PR was resubmitted as #590.

**Pull request closed without merging**
