### PR TITLE
[skip-ci][tmva] Add tmva python requirements

### PR DESCRIPTION
**Pull request by lobis**
# This Pull request:

## Changes or fixes:

Add TMVA python optional packages. CI should now run some additional tests that were skipped due to missing packages.

I tested the installation of the requirements.txt on python 3.10.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes https://github.com/root-project/root/issues/14553

### CODE REVIEW

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
Running this through CI won't do much; the interesting time will be once this is merged and the CI images are rebuilt

**Comment by dpiparo** [comment]
This change would clarify the contract with our users: @vepadulano would you agree?

**Comment by guitargeek** [comment]
Hello @lobis! Can you pls rebase the PR on top of ROOT  `master`? Thanks!

**Comment by lobis** [comment]
> Hello @lobis! Can you pls rebase the PR on top of ROOT `master`? Thanks!

Done. Sorry about the spam, I did the rebasing quickly and modified a bunch of unintended files which triggered these many reviewers (I cannot remove them).

**Review by guitargeek — APPROVED** [review]
Thanks for the PR!

Sorry that it needed rebasing again, we updated the `requirements.txt` file a bit too much recently.

I rebased and cleaned up your commit a little bit, so that you can move on:

* avoid duplicate entries
* sort entries alphabetically
* add `onnx`, which is a requirement for TMVA SOFIE. Many platforms fail right now because this requirement is missing.
* comment `graph_nets` and `sonnet` out for now. We don't want to install any new optional dependencies on the CI platforms right now: the CI is very unstable because of TMVA, and we don't want to add new tests for now that would suddenly pop up because of the added optional dependency

This should probably be backported to the 6.32 branch, such that the release advocates the right dependencies.

**Pull request closed without merging**
