### PR TITLE
[RF] Clear out `RooFit.h` header with outdated compiler fix

### PR DESCRIPTION
**Pull request by guitargeek**
Title says it all. This commit removes also all includes of the now completely empty `RooFit.h`.

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build just on windows10/cxx14

**Review by lmoneta — APPROVED** [review]
Good you remove this un-needed inclusion of an header file, which was included by all .cxx files. 
in case we need something later on, I think it will be better to add only where needed. 
I see also RooFit.h was including RConfig.h. 
I think RConfig.h is probably already included by some other ROOT headers, however, we should maybe be sure that this not does not cause a problem

**Comment by guitargeek** [comment]
Thanks! I think if not including `RConfig.h` would cause a problem, I think we'd have some compiler errors here. If some problems unexpectedly pop up later, we can probably find them easily and fix them in a followup.

**Pull request merged**
