### PR TITLE
RBrowser: support different tabs types

### PR DESCRIPTION
**Pull request by linev**
@Falcort I rebase your branch and creating PR for master
Do you want to submit it now or later?

### CODE REVIEW

**Comment by Falcort** [comment]
I just looked into your branch, and everything is working for me
I am able to display images as well as root plots
The only thing missing is that the Root6 canvas and Root7 canvas actually do the same thing
But for me it is fine, unless you want me to improve something maybe ?

**Comment by linev** [comment]
Strange, for me it was not working.
I will check again (and fix it when needed).
Later today I will merge it into the master

**Comment by Falcort** [comment]
I tried 

Images :
- SVG
- PNG
- GIF
- ICO

Canvas : 
- Hsimple/hpx
- Hsimple/hpxpy
- Hsimple/hprof

And they were all working

**Comment by linev** [comment]
@Falcort Now it is really working as designed
I will merge it once all builds are completed
There are many items to improve - I will send you list via email

**Comment by Falcort** [comment]
Finally less console.log output !

**Comment by linev** [comment]
Last change is trivial - merging

**Pull request merged**
