### PR TITLE
[cmake][cuda] Add a check for CUDA. Fixes #15139

### LINKED ISSUE #15139: cmake option -Dall=YES breaks the cmake
### Check duplicate issues.

- [X] Checked for duplicates

### Description

On macOS, running with cmake option `-Dall=YES` breaks cmake on `master`, on `v6.30.*` is works fine:

`cmake -G Ninja -Dall=YES -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..`

```CMake Error: CMake can not determine linker language for target: RooBatchCompute_CUDA
CMake Error in roofit/batchcompute/CMakeLists.txt:
  Exporting the target "RooBatchCompute_CUDA" is not allowed since its linker
  language cannot be determined


CMake Error: CMake can not determine linker language for target: RooBatchCompute_CUDA
CMake Error in roofit/batchcompute/CMakeLists.txt:
  Exporting the target "RooBatchCompute_CUDA" is not allowed since its linker
  language cannot be determined


-- Generating done (0.8s)
CMake Generate step failed.  Build files cannot be regenerated correctly.```

### Reproducer

On `master` branch, on macOS, do:

```cmake -G Ninja -Dall=YES -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..```

### ROOT version

master branch of today.

### Installation method

Build from source

### Operating system

macOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]
LGTM

**Review by guitargeek — CHANGES_REQUESTED** [review]
I don't agree with these changes for two reasons:

* The default is `cuda=OFF`, and if the user passes `cuda=ON` explicitly, it can be annoying if it is switched off at compile time because for example some environment variables were missing. We had complaints about this in the past. That's why I suggested to not have this fallback for features that are by default `OFF`.
* I would argue that it's not correct to set `cuda=ON` if `all=ON`. Enabling cuda disables TMVA CPU, so clearly you don't get `all` features but different ones. That's why many distros like Arch Linux have a separate `root` and `root-cuda` package. Unless this is fixed, I think the right solution to the problem is to not switch cuda on if `all=ON`.

See also: https://github.com/root-project/root/pull/14834

**Comment by dpiparo** [comment]
> I don't agree with these changes for two reasons:
> 
>     * The default is `cuda=OFF`, and if the user passes `cuda=ON` explicitly, it can be annoying if it is switched off at compile time because for example some environment variables were missing. We had complaints about this in the past. That's why I suggested to not have this fallback for features that are by default `OFF`. See also: [[cmake] Some improvements related to feature detection #14834](https://github.com/root-project/root/pull/14834).
> 
>     * I would argue that it's not correct to set `cuda=ON` if `all=ON`. Enabling cuda disables TMVA CPU, so clearly you don't get `all` features but different ones. That's why many distros like Arch Linux have a separate `root` and `root-cuda` package. Unless this is fixed, I think the right solution to the problem is to not switch cuda on if `all=ON`.

This sounds like a perfectly legitimate solution

**Comment by guitargeek** [comment]
Ok, I will open a PR with this, but first I need to look at the code again to back up my claim that ROOT with `cuda=ON` is not a strict superset of ROOT with `cuda=OFF`. I was rushing a bit to write my first comment to make sure I post it before the PR got merged.

**Comment by bellenot** [comment]
@guitargeek don't worry, I will not merge it before your approval. And FYI, cuda is ON if one set the `all` flag: https://github.com/root-project/root/blob/master/cmake/modules/RootBuildOptions.cmake#L222 so would you prefer not to set it to `ON` in this case? I would prefer to keep it the way it is and keep it ON if cuda is available (as in my PR)
I'll let you decide what is the best option anyway (I never tried CUDA on Windows, and have no plan to do it anytime soon 😉 )

**Comment by guitargeek** [comment]
> I don't agree with these changes for two reasons:
> 
>     * The default is `cuda=OFF`, and if the user passes `cuda=ON` explicitly, it can be annoying if it is switched off at compile time because for example some environment variables were missing. We had complaints about this in the past. That's why I suggested to not have this fallback for features that are by default `OFF`. See also: [[cmake] Some improvements related to feature detection #14834](https://github.com/root-project/root/pull/14834).
> 
>     * I would argue that it's not correct to set `cuda=ON` if `all=ON`. Enabling cuda disables TMVA CPU, so clearly you don't get `all` features but different ones. That's why many distros like Arch Linux have a separate `root` and `root-cuda` package. Unless this is fixed, I think the right solution to the problem is to not switch cuda on if `all=ON`.

Indeed, I was wrong with the second bullet point here. I remembered it wrongly because when building with `tmva-gpu`, some tutorials use the GPU backend of TMVA by default. This first argument still holds though!

I made an alternative suggestion: https://github.com/root-project/root/pull/15155

This one also fixes the problem that the `cuda` flag is checked before it is set. It simplifies the logic also a bit: the `cuda` flag is not determining anymore if CMake will look for the CUDA language and add it to the project. It only determines if ROOTs CUDA sources are actually built.

**Comment by guitargeek** [comment]
Superseded by:
  * https://github.com/root-project/root/pull/15155

**Pull request closed without merging**
