### PR TITLE
Revert "Work around vtable index issue due to base class definition b…

### PR DESCRIPTION
**Pull request by Axel-Naumann**
…eing replaced by later PCM."

This reverts commit fc1cb8039199c081f3029c437c758dd11ae0eff8.
And brings that file back to the original clang version.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

@Axel-Naumann shall we merge that in?

**Comment by Axel-Naumann** [comment]
@vgvassilev I'd prefer to first get a status update from say CMS and LHCb: they need to have a green build *now*, such that we can confirm that this reversed patch doesn't break them. I *think* this one was (also) visible in LHCb. Could you contact Marco and DavidA to assert that they get a green build with the master?

**Comment by vgvassilev** [comment]
@davidlt, could we validate if with this PR CMSSW is still fine? @Axel-Naumann I do not have Marco's git handle.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
