### PR TITLE
[dictgen] Do not complain about headers in byproducts:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
During ROOT's build of Core.pcm, byproduct modules are built. rootcling was complaining about some headers not appearing in Core.pcm, despite them ending up in the byproduct pcms.

Simply don't complain about headers not in the pcm if these headers are actually in a byproduct. In the same vein, do not forcefully include them in teh pcm, as they are already included in the byproduct which should be sufficient.

This circumvents the warnings:

```
[2751/6001] Generating G__Core.cxx, ../lib/Core.pcm
Warning in <CheckModuleValid>: after creating module "Core" the following headers are not part of that module:
  strlcpy.h (already part of top-level module "ROOT_Foundation_C")
  snprintf.h (already part of top-level module "ROOT_Foundation_C")
  ESTLType.h (already part of top-level module "ROOT_Foundation_Stage1_NoRTTI")
  TClassEdit.h (already part of top-level module "ROOT_Foundation_Stage1_NoRTTI")
  ThreadLocalStorage.h (already part of top-level module "ROOT_Foundation_C")
  ROOT/RStringView.hxx (already part of top-level module "ROOT_Foundation_Stage1_NoRTTI")
  TIsAProxy.h (already part of top-level module "ROOT_Foundation_Stage1_NoRTTI")
  TVirtualIsAProxy.h (already part of top-level module "ROOT_Foundation_Stage1_NoRTTI")
```

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
I don't want to bikeshed on this PR but why did you end up with so much code - wasn't just looking at the `gOptModuleByproducts` enough?

**Comment by Axel-Naumann** [comment]
> I don't want to bikeshed on this PR but why did you end up with so much code - wasn't just looking at the `gOptModuleByproducts` enough?

Please propose a PR; I don't see how else to do it. And btw "so much code": it's adding 15 lines; the rest just moves code around to help the logic / control flow.

**Comment by vgvassilev** [comment]
> > I don't want to bikeshed on this PR but why did you end up with so much code - wasn't just looking at the `gOptModuleByproducts` enough?
> 
> Please propose a PR; I don't see how else to do it. And btw "so much code": it's adding 15 lines; the rest just moves code around to help the logic / control flow.

I think this is good to go, thus added an approval - no need to spend tons of time to optimize a diagnostic ;)

**Comment by Axel-Naumann** [comment]
> I think this is good to go, thus added an approval - no need to spend tons of time to optimize a diagnostic ;)

Just FYI, it's more, there *is* a functional change: missing headers that are in byproducts won't be forcefully added to the main PCM anymore.

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac12/noimt, windows10/cxx14

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac12/noimt

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac12/noimt

**Comment by Axel-Naumann** [comment]
v6.28: https://github.com/root-project/root/pull/12097

**Pull request merged**
