### PR TITLE
Replace `sprintnf` calls with `snprintf` in multiple packages

### PR DESCRIPTION
**Pull request by guitargeek**
This is to suppress the warnings we see now in the nightlies on the
macbeta nodes:

https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=macbeta,SPEC=cxx17,V=master/lastBuild/parsed_console/

After this PR, there will only be a final PR necessacy to fix these
warnings in TMVA.

### CODE REVIEW

**Review by bellenot — APPROVED** [review]
LGTM, for the GUI part

**Review by lmoneta — APPROVED** [review]

**Review by couet — APPROVED** [review]
LGMT. Thanks Jonas!

**Review by linev — APPROVED** [review]
Ok for XML-related changes

**Comment by Axel-Naumann** [comment]
I think all the relevant people have reviewed their part; this is good to go, @linev !

**Comment by linev** [comment]
I guess, Jonas create PR and can merge it now

**Comment by guitargeek** [comment]
Yep, thanks everyone!

**Pull request merged**
