### PR TITLE
[cxxmodules] Add missing dependencies to MathCore.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
If we are hit by this then so will be many, many users. Please make sure this (requesting Core != requesting Core + MathCore) gets added to the release notes!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
Failures seem unrelated.

@Axel-Naumann, we are only hit by this because of cxxmodules. There are header dependencies (usually Math/Math.h) and the pcm generation requires this. For regular ROOT that's not an issue.

**Comment by Axel-Naumann** [comment]
I don't see this in the release notes yet, as per my comment? Please consider adding.

**Pull request merged**
