### PR TITLE
[ROOT-10527][RDF] Split tests and add test for Display action and fix bug for displaying std::string

### PR DESCRIPTION
**Pull request by stwunsch**
* Split dataframe_simple.cxx by moving tests for the Display action into
  dataframe_display.cxx
* Add test for displaying a std::string
* Test added due to bug reported in ROOT-10527

### CODE REVIEW

**Comment by stwunsch** [comment]
Put the fix before the test so that we don't have a broken commit on master.

**Comment by stwunsch** [comment]
As also asked on [JIRA](https://sft.its.cern.ch/jira/browse/ROOT-10527): Should `ROOT::TypeTraits::IsContainer` select `std::string` as such or is it a bug in `RDisplay`?

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@Axel-Naumann shall we go with this solution? there is still the open question how we should treat the trait `IsContainer` regarding strings (you wanted a clarification on this). You can find the discussion in the jira ticket here: https://sft.its.cern.ch/jira/browse/ROOT-10527

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@bluehood @pcanal Your input is requested on jira ;) -> https://sft.its.cern.ch/jira/browse/ROOT-10527

**Comment by Axel-Naumann** [comment]
OOM on fed29 and the pcanal-v6-18-00-patches error should be fixed

**Comment by stwunsch** [comment]
The issue is that with changing the logic of `IsContainer` excluding `std::string`, the `FillHelper` of `RDataFrame::Histo1D` does not support `std::string` anymore.

**Comment by stwunsch** [comment]
So we could specialize on the level of the `FillHelper` or retain the `IsContainer` logic in addition to the `IsDataContainer` trait.

**Comment by bluehood** [comment]
The SFINAE check on IsContainer could become a check on IsDataContainer || IsStdString?

**Comment by stwunsch** [comment]
Yep that works ofc, but then it looks uglier than before. It feels more like a step back than foward.

**Comment by stwunsch** [comment]
@bluehood Do we want to support filling a histogram with the characters of a `std::string`? I could also just make some compile time error, that we don't support filling histograms from `std::string`.

**Comment by bluehood** [comment]
The question is rather whether we want to _stop_ supporting it. I realize that it's not a very useful feature, but why change the behavior from one version to the other if we don't have to?

> then it looks uglier than before.

It's just an extra `||`. Even if we want to disable filling histograms with std::strings, that will require extra code (e.g. an extra template specialization).

With this said, I would accept either solution. Let's try to fix the original bug without expanding the scope of this PR further though :D

**Comment by stwunsch** [comment]
I know, I'm overthinking the issue. Though, don't want to leave in a worse state than before :sweat_smile:

**Comment by stwunsch** [comment]
So, now it's done

**Comment by bluehood** [comment]
I'll do a final review ~tomorrow ok?

**Comment by stwunsch** [comment]
Whenever you like :)

**Comment by eguiraud** [comment]
Well, resolving conflicts via github's web interface failed spectacularly

**Comment by eguiraud** [comment]
@stwunsch my attempt at fixing the conflicts via the github web interface failed spectacularly, so I rebased on master, fixed conflicts, and force-pushed to your branch.

Now doing one last pass of review

**Comment by stwunsch** [comment]
@phsft-bot build

**Pull request merged**
