### PR TITLE
Protect TThreadExecutor against uninitializations.

### PR DESCRIPTION
**Pull request by xvallspl**
Thanks to @agarciamontoro that noticed this in his use cases and suggested the solution 👌

### CODE REVIEW

**Comment by amadio** [comment]
I don't get it. What is an "uninitialization"?

**Comment by xvallspl** [comment]
@amadio 

2 cases solved here:

1. When chunking and fitting the right amount of elements per chunk I may end up with empty chunks at the end. This chunks will still consist of N elements per chunk, but they will not be initialized. Accessing them was a problem. Solved by reducing the number of chunks (not allowing empty chunks)

2. Although the evaluation loop finishes early when, in the last chunk, the iteration reaches the last data element, the partial results vector was of size step. That means we were reducing over elements that may have not been initialized. Solved by changing the size of the partial results vector.

**Comment by amadio** [comment]
@xvallspl That makes a lot more sense. Could you please change the commit message accordingly? That is, add your comment as an explanation with `git commit --amend`. I think it helps if we have to look at the code later again.

**Comment by xvallspl** [comment]
Yes, I was going to do that once I saw the tests were passing :)

**Comment by amadio** [comment]
Oh, I was hoping it would fix the LogLExecPolicy test, but I guess that's not the case.
Any progress on that one?

**Comment by xvallspl** [comment]
@amadio none so far

**Comment by xvallspl** [comment]
The update for the commit message was not there yet! Oh well

**Comment by amadio** [comment]
@xvallspl Oops, sorry about that. I thought it was.

**Pull request merged**
