### PR TITLE
[TDF] Replace the name TResultProxy with TResultPtr

### PR DESCRIPTION
**Pull request by dpiparo**
- Rename the template
- Add the default constructor
- Remove the TResultProxy.hxx header from the PCH
- Include the TResultPtr.hxx header from within the TResultProxy.hxx and create alias for the TResultPtr called TResultProxy. Add a compiler warning about this change.

This addresses https://sft.its.cern.ch/jira/browse/ROOT-9350 and relates to roottest PR https://github.com/root-project/roottest/pull/156

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @bluehood, 
answers in revrese order.
I am not a fan of adapting to old interfaces accepting pointers and a fan of value semantics but I think that adding a method which correspods to *_ptr::get is a good thing.

- It would be cheap to add Reset . But for example, TDF is the only entity that should fill these ptrs. What does Reset actually mean? To what TDF is the pointer linked?
- Comparison with nullptr (and implicit conversion): it would not be too much used, but cheap to add. Do you have a usecase in mind.
- Assignments: I agree.

**Comment by bluehood** [comment]
* I agree about Reset, not a good idea
* Comparisons with nullptr and implicit conversion to bool become useful now that one can default-construct a TResultPtr, to check whether it has been filled with something yet

**Comment by pcanal** [comment]
I still think that the suffix Ptr is a bit misleading due to the fact that operator-> is/can-be a very heavy operation and as such we may want to consider TResultHandle.

> Comparisons with nullptr and implicit conversion to bool ...

Would those two operations 'provoke' the execution or looks at the 'current' state?

**Comment by bluehood** [comment]
> Would those two operations 'provoke' the execution or looks at the 'current' state?

They would refer to the current state. They answer the question "does this object point to the same value as this other object?", just as for other smart pointers

**Comment by bluehood** [comment]
> I still think that the suffix Ptr is a bit misleading due to the fact that operator-> is/can-be a very heavy operation and as such we may want to consider TResultHandle.

I think `TResultHandle` would suffer from the same problems as `TResultProxy`: the name is too generic, the average physicist will not know how to use it, it's not clear if I can make a `std::vector` of those, default construct one, assign one, copy....

`operator->` will be heavy for the first time the first result is accessed, and that is _the one thing_ to know about TDataFrame: event loop runs upon first access to one of the results.
Subsequent usages of `operator->` will be fast.

**Comment by pcanal** [comment]
> They would refer to the current state. 

This not obvious :) especially for a Ptr.  For example, would expect this to result false (it does in your scenario):
```
(bool) resultPtr && resultPtr->IsValid() && (bool) resultPtr
```
Cheers,
Philippe.

**Comment by bluehood** [comment]
> This not obvious

I think you are misunderstanding. `operator bool` will have the exact same semantics as in `shared_ptr` and `unique_ptr`: converts to `true` if I can safely dereference, converts to false otherwise.

Dereferencing the `TResultPtr` _does not_ change its `true/false` conversion.

**Comment by pcanal** [comment]
> I think TResultHandle would suffer from the same problems as TResultProxy: the name is too generic, the average physicist will not know how to use it, it's not clear if I can make a std::vector of those, default construct one, assign one, copy....

One could give the exact same argument against TResultPtr ;) .... One difference with a pointer is the life-time of the pointee.

> the average physicist will not know how to use it,

A lot of the frameworks have the concept of 'Handle' already to indicate this kind of delay-loaded accessor.

**Comment by bluehood** [comment]
> One could give the exact same argument against TResultPtr
I don't get it: all ROOT users are familiar with the concept of a pointer, while not every PhD student is familiar with the concept of a Handle. If it's a pointer, I know that I can access the contents with `*p` or `->`, and I know what happens when I copy it, assign one thing to the other, etc....
If it's a Handle I know none of these things. We might as well stick with `TResultProxy`.

[The idea](https://sft.its.cern.ch/jira/browse/ROOT-9350) was to convey _how to use it_, not _how it works_. As stated in the jira issue the problem we are trying to solve is that users do not know what to do with a "proxy" -- but they do know what to do with a pointer.

**Comment by bluehood** [comment]
_One_ of the results will do something similar to a future (but not quite, because futures in C++ are associated with asynchronous execution).

I still think that the average physicist will get as little insight in the semantics of the type from the denomination "Handle" as they get from "Proxy". Even ROOT has a `TFileOpenHandle` which does not have the semantics you describe.
There is a slice of our users which are not familiar with the experiment frameworks and/or do not use one.

If you feel strongly that this is not the way to go and we need a name that clearly conveys both pointer semantics and the fact that the first access triggers the event loop, I think we'll need a discussion outside of this PR :smile:

**Comment by pcanal** [comment]
> that rather than a smart_ptr this entity is close to an std::future ....

Actually this brings me to another question to answer before a final decision.   What are the advantage and disadvantage of splitting TResultProxy into distinct entity: a future and a (more regular) smart ptr?

**Comment by pcanal** [comment]
> because futures in C++ are associated with asynchronous execution

Yes technically it is not a future but (beside the threading implementation details) behaves very much like it.

**Comment by bluehood** [comment]
> What are the advantage and disadvantage of splitting TResultProxy into distinct entity: a future and a (more regular) smart ptr?

Can you give an example of how that would look from the user perspective? (again note that future usually means asynchronous execution in c++..)

**Comment by pcanal** [comment]
> (again note that future usually means asynchronous execution in c++.

Right .... this is a major difference.

> Can you give an example of how that would look from the user perspective?

Did not really think about it in details.  I suppose.
```
Auto filter = tdf.something( filter_lamba, branches ); // Guarantee 'fast'
auto histo = filter.GetResult(); // access the disk ...
```

**Comment by pcanal** [comment]
@Axel-Naumann Opinions?

**Comment by bluehood** [comment]
I see. `TResultProxy` already has a `GetValue` helper method that returns a reference to the stored value (and triggers its computation if need be).

It's meant to be used mostly from python, where there is no `->`.
It's more awkward than `->` because for N histograms I have to call `GetValue` N times.

**Comment by dpiparo** [comment]
One of the main difficulties to start developing in CMSSW (and this is common to other fwks) is the jeargon permeating all corners of the software, for example "Handle" means really little while "pointer" is something which can be accessed with "->". 

We have signs on the forum of user not even noticing/caring enough what type the return value of action was (this is a success) *and* have a huge amount of code still to develop to implement our long term vision of ROOT. I support being pragmatic before anything else :)

**Comment by Axel-Naumann** [comment]
Apologies for joining the party only after it's over. My opinion:

`ptr` is fine because I don't see how (regular) people would notice / care *when* the cost occurs, this should be opaque to them. If they ever notice, they can be told and learn. `TTree::Draw()` sort of suffers from a similar mismatch of interface announcement ("register in the pad") and runtime cost that `ptr` has in this case. And we survived.

I find the argument convincing that `ptr`, unlike `handle`, conveys the usage: `handle` often means "opaque thing that you don't know what to do with but someone else will" and is thus not very helpful for interfaces.

I find the usage cost for separating trigger and value access too high.

**Comment by pcanal** [comment]
Fair enough.  I still somewhat disagree with the decision but we now explicitly listed everybody's opinion on the pros and cons and Ptr wins (for now ? :) ).

**Comment by dpiparo** [comment]
Sure. For now. We still have 1 month: I really want progress, we can refine these things later.

**Pull request merged**
