### PR TITLE
[cmake] Remove deprecated alien option, deprecate gfal gsl_shared jemalloc monalisa pyroot_legacy tcmalloc xproofd.

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by gganis** [comment]
Hi @Axel-Naumann, apologies for the late reply.
It looks good to me.
You might want to remove also TGrid and related classes (TGrid...), as they were introduced  for TAlien and used only there.

**Review by gganis — APPROVED** [review]
TGrid and related classes (TGrid...) can be removed as well, as they are used only by TAlien.

**Comment by Axel-Naumann** [comment]
Thanks @gganis !

> TGrid and related classes (TGrid...) can be removed as well

I see `net/monalisa/src/TMonaLisaWriter.cxx` `#include`s `TGrid.h`; we're deprecating that only here, so I'll try to remember to remove this once monalisa gets removed!

That said, `TDataSetManagerAliEn` seems to be something we can remove in this PR, too? Let me try :-)

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by Axel-Naumann** [comment]
Errors seem unrelated, merging.

**Pull request merged**
