### PR TITLE
TMVA Userguide Update

### PR DESCRIPTION
**Pull request by abhinavmoudgil95**
Added Variance Threshold method to Data Preprocessing section.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Could you rebase this PR?

**Comment by abhinavmoudgil95** [comment]
@phsft-bot All the changes of this PR have been committed to the repository, hence closed this.

**Comment by abhinavmoudgil95** [comment]
@vgvassilev Sorry, I got busy in my mid term examinations, so couldn't reply. I rebased my branch and my commits of this PR are there in the master branch of root. But `TMVAUserGuide.pdf` is not updated with respect to changes in tex files. Should I open a separate PR for updating TMVA User Guide pdf?

**Comment by abhinavmoudgil95** [comment]
@vgvassilev Sorry, I got busy in my mid term examinations, so couldn't reply. I rebased my branch and my commits of this PR are there in the master branch of root. But `TMVAUserGuide.pdf` is not updated with respect to changes in tex files. Should I open a separate PR for updating TMVA User Guide pdf? 
cc: @lmoneta

**Pull request closed without merging**
