### PR TITLE
[RF] Remove Python version of outdated `rf204_extrangefit` tutorial

### PR DESCRIPTION
**Pull request by sayang14**
# This Pull request:
rf204_extrangefit.py translated to C++
## Changes or fixes:
 Whole python code was translated to C++ with code description as written in rf204_extrangefit.py. Hope this helps. Thanks!  

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by sayang14** [comment]
Hi @guitargeek , I have tried to translate rf204_extrangefit.py to C++ as you have told in one of the good first issues. So , here is my first pull request . Can you please verify once? It will be grateful. Thanks!

**Comment by guitargeek** [comment]
I apologize, I realize now that the `rf204_extrangefit` tutorial should not be translated to C++, because it is an outdated tutorial. The C++ version already got removed as it should, but the Python version was still there. Hence, the translation was not needed, and I updated the PR to also remove the Python version of the tutorial instead. Once the unit tests pass, I will merge this PR then.

I'm sorry for the inconvenience! Thanks a lot anyway for looking into our issues :)

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]

**Pull request merged**
