### PR TITLE
[RM] Add a RAII to TClingBaseClassInfo

### PR DESCRIPTION
**Pull request by yamaguchi1024**
This fixes the errors in #3222. Patch by Oksana and me!

### CODE REVIEW

**Comment by Teemperor** [comment]
What's the RM tag btw?

**Comment by yamaguchi1024** [comment]
RM -> Runtime Modules :D

**Comment by yamaguchi1024** [comment]
@phsft-bot build

**Comment by oshadura** [comment]
@phsft-bot build with -Dctest_test_exclude_none=on

**Comment by oshadura** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
@yamaguchi1024 @hageboeck , would it be possible to have a unit test, even in core perhaps as part of the TClass suite of tests?

**Comment by yamaguchi1024** [comment]
@dpiparo I think the failing tests in #3222 will work as a unit test for this issue, but I'm not sure if I understood your suggestion correctly.

**Comment by yamaguchi1024** [comment]
@phsft-bot build

**Pull request merged**
