### PR TITLE
[webgui] improve `rootssh`, let use web widgets with default gui factory

### PR DESCRIPTION
**Pull request by linev**
1. Rename `rootssh.sh` -> `rootssh`
2. Let run commands on remote node with `rootssh` like
 ```
[shell] rootssh  user@remotehost "source path/to/bin/thisroot.sh; root --web=server -e 'new TBrowser'"
``` 
3. Let specify local port and browser kind for `rootssh`:
```
[shell] rootssh  --port 7575 -browser chromium user@remotehost "source path/to/bin/thisroot.sh; root --web=server -e 'new TBrowser'"
``` 
4. Provide usage printout when `rootssh` called without arguments
 
5. Add possibility to create `TWebCanvas` and `RBrowser` in base `TGuiFactory` class via plugin mechanism when web display is configured. Let use these web-based widgets when only `gBatchGuiFactory` is created.
6. Remove dependency of `TWebCanvas` from `Gui` library, no need for special gui factory while now base class can be used.
7. Provide plugin to be able caret `TWebCanvas` via plugin manager.
8. Fix problem in `TBrowserImp` plugins definition - `Option_t *` was not mentioned in methods signatures.
9. Update release notes

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]

**Comment by hahnjo** [comment]
As seen above, CentOS 8 is quite unhappy about the changes here. I bisected the failures (except for `fit/graph2dfit.C` and `hist/hstack.C`, which will be taken care of by https://github.com/root-project/root/pull/11830) to commit 3ac1d584c821d21e4fae789f595eddf5833848c0. @linev do you see an obvious problem / have an idea?

**Comment by linev** [comment]
Changes in https://github.com/root-project/root/commit/3ac1d584c821d21e4fae789f595eddf5833848c0 should only have effect when `root --web` is called. How it should happen when running tutorials?

**Comment by hahnjo** [comment]
@linev no, it *is* this precise commit 3ac1d584c821d21e4fae789f595eddf5833848c0. I bisected it, the one before works and that one doesn't.

**Comment by linev** [comment]
No, hstack.C was not touch by that commit. It was another one - from Olivier:
https://github.com/root-project/root/commit/e97f74d67e4cf4133d431ffabda283e924fb1bb6#diff-4d833bf7ff2b5f7c1afb111e5a55a51d6c295f09ee45cc45917a012faac8e327

**Comment by hahnjo** [comment]
https://github.com/root-project/root/pull/11822#issuecomment-1337446119 is not about `hstack.C` (please note the "except" in my comment). It is about the other failing tests reported in https://github.com/root-project/root/pull/11822#issuecomment-1335125359 and still present, see for example https://github.com/root-project/root/pull/11830#issuecomment-1337503041

**Pull request merged**
