### PR TITLE
TDavixFile: add support for cross-protocol metalinks

### PR DESCRIPTION
**Pull request by mlassnig**
Original patch by Georgios Bitzes, manual rebase onto master.

Compiles and works correctly against upstream/master on CC7.

See here for more information: https://tmaier.web.cern.ch/tmaier/ROOTDavixRedirection/davix-root-fix.html

Please also backport this patch to 6-08 and 6-10.

Thanks!
Mario

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by mlassnig** [comment]
The test hit a timeout (***Timeout 3600.04 sec)... I hope it's not related to this patch.

**Comment by Axel-Naumann** [comment]
@mlassnig it is not related; it's a pre-existing failure. Sorry about that.

**Comment by pcanal** [comment]
@mlassnig @gbitzes Could you provide a subsequent PR bringing the TDavixFile and TDavixFileInternal in line with the naming convention.  Namely all data member's name must start with an f, followed by CamelCase and all member function's name must be came case.

Thanks,
Philippe.

**Comment by gbitzes** [comment]
Hi Philippe - sure, I'll make a new PR soon.

Cheers,
Georgios

**Pull request merged**
