### PR TITLE
Do not ignore build artifacts in source directory

### PR DESCRIPTION
**Pull request by amadio**
ROOT uses out of source builds only, so we do want to see when files are created within the source directory.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Does this actually work? What's the output of
```
cd $ROOTSYS; cmake -Dall=On ../src; make -j 8; ctest -j 8
cd ../src
git status
```

**Comment by amadio** [comment]
I wanted to make a "no functional change" PR, but looking at `.gitignore` I realized we had all those useless lines. I never see the source directory of ROOT being polluted with build artifacts (i.e. your git status would come clean). The same is not true for roottest, though. I think we can safely remove these lines from the `.gitignore`.

**Comment by amadio** [comment]
The Fedora 29 failures are due to what I talked about before lunch. I think it's caused by recent changes to roottest that now pick up any installed ROOT over the one from the build directory that was configured with `-Droottest=ON`. @oshadura said she will take a look.

**Comment by Axel-Naumann** [comment]
Right. Could you paste the output of the commands I stated above? Thanks!

**Comment by Axel-Naumann** [comment]
Can we please *not* install ROOT on the nodes we use for Jenkins? Thanks! (I really want to make sure we're not mixing versions etc - I do understand that this helped us discover a bug in this case, but still.) Can you remove it from the build nodes, please?

**Comment by amadio** [comment]
Well, right now roottest is picking up the wrong root for me, so I'd have to uninstall 3 versions of root to make it work. Once roottest is fixed I will do it, but that is something I often check, so I'm pretty sure the git status will come clean.

**Comment by amadio** [comment]
The only way to really make it sure is to have it installed! :-) If versions are mixed, tests will start failing. That's exactly why I installed it.

**Comment by amadio** [comment]
Let's please at least fix roottest first, then I can remove it.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@Axel-Naumann I just ran the ROOT build + ctest and `git status` comes out clean (no files are created in the source directory). Can we merge this now?

**Pull request merged**
