### PR TITLE
Do not fire any RecursiveRemove calls by accident in TH1::LabelsInflate

### PR DESCRIPTION
**Pull request by ponyisi**
LabelsInflate creates a temporary histogram which has its properties copied from the original histogram (via TNamed::Copy -> TObject::Copy), including the state of kMustCleanup. But this temporary histogram is immediately detached from any directory and the deletion of the temporary shouldn't trigger a recursive cleanup.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
Could you enhance the commit log by including the text from the intro to this PR?  Thanks.

**Comment by ponyisi** [comment]
@pcanal  - Do you mean add the text from the first comment as an extended commit message? (Sorry - more familiar with the gitlab workflow for these things...)

**Comment by bellenot** [comment]
@ponyisi please fork also [roottest](https://github.com/root-project/roottest) to prevent timeouts on the Windows build nodes, thanks

**Comment by pcanal** [comment]
>  Do you mean add the text from the first comment as an extended commit message? (Sorry - more familiar with the gitlab workflow for these things...)

@ponyisi yes :)

**Comment by pcanal** [comment]
Thank you very much.

**Pull request merged**
