### PR TITLE
Test coverage compilation flag

### PR DESCRIPTION
**Pull request by martinmine**
Added coverage compilation flag -Dtestcoverage which is by default set to OFF.

### CODE REVIEW

**Comment by martinmine** [comment]
Running the PR on an experimental Jenkins instance (accessible at CERN only): http://epsft-jenkins-pipeline.cern.ch:8080/job/single-build/10/

**Comment by peremato** [comment]
@phsft-bot build

**Comment by peremato** [comment]
@phsft-bot build

**Comment by peremato** [comment]
@phsft-bot build

**Comment by peremato** [comment]
@phsft-bot build

**Pull request merged**
