### PR TITLE
[reve] Print warning on missing  eve element dictionary

### PR DESCRIPTION
**Pull request by alja**
Print warning if eve element does not have a dictionary. The commit   264404b also fixes the crash on streaming to client when element's dictionary is not existing and does not need non-REveElement remote method invocation. 

The other 3 commits contains minor corrections to the problems located in testing of CMS event display (table view layout, debug prints, background color setting at connect time).

### CODE REVIEW

**Comment by alja** [comment]
@linev @osschar Please check.

**Comment by alja** [comment]
@linev @osschar Please check.

**Comment by alja** [comment]
@linev I have corrected the warning. Thanks for the review!

**Comment by linev** [comment]
@alja 

You forget to remove increment of `cnt` variable as well.
 I modify your last commit - probably it will compile now

**Review by linev — APPROVED** [review]

**Pull request merged**
