### PR TITLE
[TDF] More string_views, less strings.

### PR DESCRIPTION
**Pull request by bluehood**
Prefer string_view in function signatures.
Avoid instantiating strings whenever possible.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @bluehood , wouldn't the method to_string be more appropriate in many cases (see http://en.cppreference.com/w/cpp/header/string_view)? We need to back port it but then the PR would be greatly simplified, wouldn't it?

**Comment by bluehood** [comment]
Hi @dpiparo, thanks for looking at the PR!
As far as I understand using `to_string` would just mean that wherever I had to write `std::string(strview)` to create a string from a string view I would write `std::to_string(strview)` instead?

**Comment by dpiparo** [comment]
That page is quite busy but I think that would be a method of `string_view`: `my_strview.to_string()` should be its final form.

**Comment by Axel-Naumann** [comment]
There is not `string_view::to_string()` anymore, that web page's synopsis is broken. It's now called `explicit std::string(string_view)`. (I'm happy to explain why outside this PR.)

**Comment by dpiparo** [comment]
Hi @Axel-Naumann , @bluehood : I did not know the page was broken. In this case my original comment is not relevant anymore.

**Pull request merged**
