### PR TITLE
isDefined might cause deserialization.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
I do not see how these failures are connected to the changes in this PR.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The failure in projectroot.runtutorials.tutorial_tmva_envelope_classification are unique to this PR.

The failure from jupiter on MacOS seems infrastructure related (but not seen consistently in other PR).  

The failure projectroot.runtutorials.tutorial_multicore_imt101_parTreeProcessing is also not consistently seen elsewhere but the complain seem unrelated to this PR (error while opening input file).

**Comment by vgvassilev** [comment]
Indeed the failure is due to this PR.

**Comment by vgvassilev** [comment]
That's solved in a different way.

**Pull request closed without merging**
