### PR TITLE
[PyROOT][CMake] pyroot and pyroot_legacy interplay

### PR DESCRIPTION
**Pull request by etejedor**
As pointed out by @bellenot , we need to cover the case in which the specified flags are (wrongly) `-Dpyroot=OFF` and `-Dpyroot_legacy=ON`.

The proposed solution in this PR shows a fatal error message saying "please reconfigure with pyroot=ON too". Alternatively, we could automatically enable `pyroot` if `pyroot_legacy` has been set to ON. To be discussed with the reviewers.

This assumes:
1. `-Dpyroot=ON` means "build me PyROOT".
2. `-Dpyroot_legacy=ON` means "from the PyROOTs you have, build me the old one!"

So (1) activates PyROOT and (2) selects which PyROOT to build.

Please shout if you have a different point of view.

### CODE REVIEW

**Comment by etejedor** [comment]
@oshadura done!

**Comment by oshadura** [comment]
@etejedor small idea: lets add that it is deprecated from 6.22, so in 624 we can put a FATAL.
""pyroot_experimental is a deprecated flag starting from 6.22.00. To build the new PyROOT, just configure with -Dpyroot=ON.""

**Comment by Axel-Naumann** [comment]
> @etejedor small idea: lets add that it is deprecated from 6.22, so in 6.24 we can put a FATAL.
""pyroot_experimental is a deprecated flag starting from 6.22.00. To build the new PyROOT, just configure with -Dpyroot=ON.""

As I pointed out in another review (where I might have been wrong, too :-) `pyroot_experimental` was always experimental. So IMO we can just remove it.

This PR seems to be about `pyroot_legacy`. I assumed (in line with other modules) that `pyroot` and `pyroot_legacy` are mutually exclusive, i.e. `pyroot_legacy` turns on a different module than `pyroot`. That's my naive expectation; I understand that @etejedor sees `pyroot_legacy` as a modifier to `pyroot`. It's sufficient if the ReleaseNotes state the behavior.

In any case, this is a legacy flag; we should soon deprecate it, so let's not make it too perfect :-)

**Comment by etejedor** [comment]
Added a few more release notes to explain how to use `pyroot` and `pyroot_legacy`, and to state that `pyroot_experimental` should not be used anymore : https://github.com/root-project/root/pull/5801

**Pull request merged**
