### PR TITLE
[Tutorial] Add tutorial for fitting a histogram in a file.

### PR DESCRIPTION
**Pull request by hageboeck**
Tutorial submitted by Eckhard v. Toerne.

Apparently, a tutorial showing the complete workflow of retrieving a histogram from a file, fitting it, and plotting the results is missing. This is demonstrated here.

### CODE REVIEW

**Comment by hageboeck** [comment]
The tutorial was updated, and now allows for naming of parameters and easier bookkeeping. The resulting plot now looks like this:
Screenshot from 2020-08-24 11-34-14

**Review by lmoneta — APPROVED** [review]
LGTM

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by eguiraud** [comment]
that failure in dataframe_helpers should have been fixed by Stefan's PR #6431

**Comment by oshadura** [comment]
@eguiraud so it could/should be merged? Can you please check?

**Comment by eguiraud** [comment]
@phsft-bot build

**Pull request merged**
