### PR TITLE
[WIP] Remove ModuleGenForModules

### PR DESCRIPTION
**Pull request by Teemperor**
So, we just removed the assert that makes us aware that we need to
rethink this flag. I don't see a clear solution at the moment, but
this PR at least makes us aware that we need to solve this issue.

For now I just removed it and we see what exactly Jenkins complains
about when it runs the tests.

### CODE REVIEW

**Comment by Teemperor** [comment]
Do not merge because this is obviously mostly to discuss/tests things.

**Comment by Teemperor** [comment]
@phsft-bot build

and don't crash pls

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On

**Pull request closed without merging**
