### PR TITLE
Try to fix https://sft.its.cern.ch/jira/browse/ROOT-9409

### PR DESCRIPTION
**Pull request by couet**

### CODE REVIEW

**Comment by amadio** [comment]
@phsft-bot build just on centos7/gcc7 with flags -Dcxx14=ON -Droot7=ON -Druntime_cxxmodules=ON

**Comment by Teemperor** [comment]
The `#include <ROOT/TPadPos.hxx> ` seems to be gone, but the `#include <ROOT/TPad.hxx>` is still a wrong dependency it seems.

**Comment by couet** [comment]
So I need to move TPad also ... ?

**Comment by Axel-Naumann** [comment]
We should probably fix the `#include`s. Why does `TLine.hxx` need to `#include "ROOT/TPad.hxx"`? Can we survive without / forward declaration?

And if this renders `TLine` unusable: yes, then we probably need to move `TPad` in the primitives.

**Comment by couet** [comment]
The error is now:

[centos7-gcc7-Debug] ### Errors:
[centos7-gcc7-Debug] - Error: Had to build non-system module ROOTGpadv7 implicitly. You first need to 
[centos7-gcc7-Debug] - Error: /mnt/build/jenkins/workspace/root-pullrequests-build/build/bin/rootcling: compilation failure (/mnt/build/jenkins/workspace/root-pullrequests-build/build/lib/libROOTGraphicsPrimitives958fc13e42_dictUmbrella.h) 

The error message seems truncated . 
Some ideas on what the problem is now ?

**Comment by couet** [comment]
@phsft-bot build just on centos7/gcc7 with flags -Dcxx14=ON -Droot7=ON -Druntime_cxxmodules=ON

**Comment by couet** [comment]
The error message we get is not very explicit ... at least for me. 
@Axel-Naumann, @vgvassilev do you have an idea to go further with this PR ?

**Comment by vgvassilev** [comment]
```
14:16:07 In file included from input_line_13:10:
14:16:07 /mnt/build/jenkins/workspace/root-pullrequests-build/build/include/ROOT/TLine.hxx:23:10: remark: building module 'ROOTGpadv7' as '/mnt/build/jenkins/workspace/root-pullrequests-build/build/lib/ROOTGpadv7.pcm' [-Rmodule-build]
14:16:07 #include <ROOT/TPadPainter.hxx>
14:16:07          ^
14:16:07 Error: Had to build non-system module ROOTGpadv7 implicitly. You first need to
14:16:07 generate the dictionary for ROOTGpadv7 or mark the C++ module as a system
14:16:07 module if you provided your own system modulemap file:
14:16:07 ROOTGpadv7 [system] { ... }
14:16:07 While building module 'ROOTGraphicsPrimitives':
14:16:07 While building module 'ROOTGpadv7' imported from /mnt/build/jenkins/workspace/root-pullrequests-build/build/include/ROOT/TLine.hxx:23:
14:16:07 In file included from <module-includes>:1:
14:16:07 In file included from /mnt/build/jenkins/workspace/root-pullrequests-build/build/include/ROOT/TCanvas.hxx:19:
14:16:07 /mnt/build/jenkins/workspace/root-pullrequests-build/build/include/ROOT/TPad.hxx:23:10: fatal error: cyclic dependency in module 'ROOTGraphicsPrimitives': ROOTGraphicsPrimitives -> ROOTGpadv7 -> ROOTGraphicsPrimitives
14:16:07 #include "ROOT/TDrawingAttr.hxx"
14:16:07          ^
14:16:07 In file included from input_line_13:10:
14:16:07 /mnt/build/jenkins/workspace/root-pullrequests-build/build/include/ROOT/TLine.hxx:23:10: fatal error: could not build module 'ROOTGpadv7'
14:16:07 #include <ROOT/TPadPainter.hxx>
14:16:07  ~~~~~~~~^
14:16:07 Error: /mnt/build/jenkins/workspace/root-pullrequests-build/build/bin/rootcling: compilation failure (/mnt/build/jenkins/workspace/root-pullrequests-build/build/lib/libROOTGraphicsPrimitivesd47c8c6918_dictUmbrella.h)
14:16:07 [7257/9834] Linking CXX shared library lib/libMatrix.so
```

@couet, this error shows two problems. First is that we *must* build a dictionary before we use a header file. We are likely missing a build dependency on `ROOTGpadv7`.

I believe you are trying to fix the second problem. Namely, `TLine.hxx` includes `TPadPainter.hxx` which includes `TDisplayItem.hxx` and you end up with the cycle `ROOTGraphicsPrimitives -> ROOTGpadv7 -> ROOTGraphicsPrimitives`. It seems that `ROOTGraphicsPrimitives` is a foundational module its header `TLine.hxx` should not depend on headers in `ROOTGpadv7`. @Teemperor is right, `TLine.hxx` should not depend on `TPadPainter.hxx`.

You can break that loop by introducing a forward declarations of `TPadPainter.hxx` entities where necessary if definitions are not required.

This is how the current master's modulemap looks like (maybe this helps to see the cycle).
```
 module "ROOTGraphicsPrimitives" {
   requires cplusplus
   module "ROOT/TColor.hxx" { header "ROOT/TColor.hxx" export * }
   module "ROOT/TDisplayItem.hxx" { header "ROOT/TDisplayItem.hxx" export * }
   module "ROOT/TDrawingAttr.hxx" { header "ROOT/TDrawingAttr.hxx" export * }
   module "ROOT/TDrawingOptsBase.hxx" { header "ROOT/TDrawingOptsBase.hxx" export * }
   module "ROOT/TLine.hxx" { header "ROOT/TLine.hxx" export * }
   module "ROOT/TMarker.hxx" { header "ROOT/TMarker.hxx" export * }
   module "ROOT/TPalette.hxx" { header "ROOT/TPalette.hxx" export * }
   module "ROOT/TStringEnumAttr.hxx" { header "ROOT/TStringEnumAttr.hxx" export * }
   module "ROOT/TStyle.hxx" { header "ROOT/TStyle.hxx" export * }
   module "ROOT/TText.hxx" { header "ROOT/TText.hxx" export * }
   export *
 }
 
 module "ROOTGpadv7" {
   requires cplusplus
   module "ROOT/TCanvas.hxx" { header "ROOT/TCanvas.hxx" export * }
   module "ROOT/TFrame.hxx" { header "ROOT/TFrame.hxx" export * }
   module "ROOT/TMenuItem.hxx" { header "ROOT/TMenuItem.hxx" export * }
   module "ROOT/TObjectDrawable.hxx" { header "ROOT/TObjectDrawable.hxx" export * }
   module "ROOT/TPad.hxx" { header "ROOT/TPad.hxx" export * }
   module "ROOT/TPadDisplayItem.hxx" { header "ROOT/TPadDisplayItem.hxx" export * }
   module "ROOT/TPadExtent.hxx" { header "ROOT/TPadExtent.hxx" export * }
   module "ROOT/TPadLength.hxx" { header "ROOT/TPadLength.hxx" export * }
   module "ROOT/TPadPainter.hxx" { header "ROOT/TPadPainter.hxx" export * }
   module "ROOT/TPadPos.hxx" { header "ROOT/TPadPos.hxx" export * }
   module "ROOT/TPadUserAxis.hxx" { header "ROOT/TPadUserAxis.hxx" export * }
   module "ROOT/TVirtualCanvasPainter.hxx" { header "ROOT/TVirtualCanvasPainter.hxx" export * }
   export *
 }
```

**Comment by couet** [comment]
`TPadPainter` is used in `TLine.cxx` in the following code. My attempts to "forward declare" TPadPainter did not work until now.

```
   void Paint(Internal::TPadPainter &topPad) final
   {
      topPad.AddDisplayItem(
         std::make_unique<ROOT::Experimental::TOrdinaryDisplayItem<ROOT::Experimental::TLine>>(this));
   }
```

**Comment by couet** [comment]
This PR is not valid anymore since the T -> R names changes.

**Comment by vgvassilev** [comment]
That's #2999.

**Pull request closed without merging**
