### PR TITLE
parse correctly the compiler version

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Fixes the incorrect parsing of the gcc version on Ubuntu 18 or 20.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes https://github.com/root-project/root/issues/8551

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
Thanks, @ferdymercury ! (Note so self: we should really ask CMake to generate that header for us...)

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
GCC 4.8 doesn't like `-dumpfullversion`:
```
cc1plus: warning: unrecognized gcc debugging option: u [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: m [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: f [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: u [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: l [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: l [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: v [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: e [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: r [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: s [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: i [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: o [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: n [enabled by default]
Compiler returned: 0
```

Let's wait for tonight, we might not care about GCC 4.8 after this afternoon.

**Comment by ferdymercury** [comment]
Or shall I maybe make an 'if gccversion < 5 then ... else ...' ?

**Comment by Axel-Naumann** [comment]
Turns out we now require C++14 in master which excludes GCC 4.8 :-P ;-) So this PR is good to go, thanks, @ferdymercury !

**Pull request merged**
