### PR TITLE
Added Spherical and Cartesian TVector3 Conversion methods and Sign Function 

### PR DESCRIPTION
**Pull request by AdvaitDhingra**
# This Pull request:

Backstory:

During my internship in January 2021, I had to convert between Sphericla and Cartesian Coordinates a lot and while this is possible in GenVector, it is not in TVector3. This should add that functionality. Furthermore I also added a Sign() function to mathcore as I couldnt find this elsewhere in ROOT.

## Changes or fixes:

See above

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Comment by AdvaitDhingra** [comment]
Built it locally on Ubuntu 20.04 and the build succeeded and I got the desired result.

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by AdvaitDhingra** [comment]
The phsft-bot build succeeded

**Comment by AdvaitDhingra** [comment]
@lmoneta is the formatting and the Doxygen comments ok? Can this be merged?

**Comment by AdvaitDhingra** [comment]
@lmoneta is everything good to go?

**Review by lmoneta — COMMENTED** [review]
Hi,
Why do you need to add these functions in TVector3 ? Could you not just use the GenVector equivalent. We would lprefer to not add functionality in TVector3 to maintain as it is for backward compatibility..

Then there is already a TMath::Sign function, with a slightly different signature and there is also `TMath::SignBit`. They are defined in the header TMathBase.h

**Comment by AdvaitDhingra** [comment]
> Hi,
> Why do you need to add these functions in TVector3 ? Could you not just use the GenVector equivalent. We would lprefer to not add functionality in TVector3 to maintain as it is for backward compatibility..
> 
I've used TVector3 for a lot of my projects and it would be really helpful if I could convert to a spherical Vector and back without having to type the whole conversion into the code. Is there Any way to use the GenVector equivalent with TVector3? Because TVector3 has some properties that are better in some cases than GenVector. 

Oh, and I'll remove the Sign Function I just thought it would be cool. I didn't know it already existed. 

Thanks for your help!

**Comment by lmoneta** [comment]
> Because TVector3 has some properties that are better in some cases than GenVector.

Which properties are you referring to ? 
The only think missing is inheritance of TObject and a virtual destructor. This can cause some slowdown in TVector3 when creating many temporary vector objects.  
You should be able to use the Genvector as a TVector3. If some functionality is missing, please let me know

**Comment by AdvaitDhingra** [comment]
> > Because TVector3 has some properties that are better in some cases than GenVector.
> 
> Which properties are you referring to ? 
> The only think missing is inheritance of TObject and a virtual destructor. This can cause some slowdown in TVector3 when creating many temporary vector objects.  
> You should be able to use the Genvector as a TVector3. If some functionality is missing, please let me know

Ah, my bad, I mustve gotten it confused with another class. Thanks for your patience.

**Pull request closed without merging**
