### PR TITLE
[DF] Correct token used in RSampleInfo creation

### PR DESCRIPTION
**Pull request by vepadulano**

### CODE REVIEW

**Comment by eguiraud** [comment]
This is a breaking change, why do we need it?

**Comment by vepadulano** [comment]
I just encountered it while working on other stuff. It is the only remaining usage of the `/` token to separate file name and tree name in the dataframe library. I understand it's a minimal change and if it breaks existing tests it may be not worthwhile

**Comment by eguiraud** [comment]
Users won't expect the `?#` syntax. IIRC we use it internally because otherwise TChain gets the tree name wrong in case the filename does not end in `.root`.

**Comment by vepadulano** [comment]
Yes indeed. Ok I understand this is also information exposed to users, fair enough. This can be closed

**Pull request closed without merging**
