### PR TITLE
[cmake] simplify include dirs handling in ROOT_GENERATE_DICTIONARY

### PR DESCRIPTION
**Pull request by linev**
Keep list with plain directories names, 
only for rootcling executable provide list with prefixed -I

### CODE REVIEW

**Comment by vgvassilev** [comment]
I think it is too late to merge that change for 6.22 given the fact this is externally used facility.

**Comment by linev** [comment]
@vgvassilev If I see it correctly - it is just cleanup of historical code. No any real changes.

**Comment by vgvassilev** [comment]
> @vgvassilev If I see it correctly - it is just cleanup of historical code. No any real changes.

That's what I am worried about. When this code changes even for NFCs there is always somebody that complains something broke. Doing it before branching leaves almost no place for testing even from within the team and experiments which build often against the master.

The question is whether it pays off to change that so late and then potentially fix things under pressure asap, backport patches and make urgent patch releases. I think it does not. If @Axel-Naumann thinks otherwise, go ahead...

**Comment by linev** [comment]
@vgvassilev It can wait until 6.22 branching. I have in mind to submit several other PRs, which definitely have to wait

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@oshadura Can you approve it?

**Pull request merged**
