### PR TITLE
Add macros to flag legacy functions/classes.

### PR DESCRIPTION
**Pull request by hageboeck**
Functions and classes that are outdated, but will probably never be removed, can be flagged with deprecation warnings at the discretion of the user. This was a request by the experiments during the Sarajevo workshop.
The macros would be used as follows:
```
class BetterNotUse {
} R__SUGGEST_CLASS("NewerClass");
```
```
TIterator* createIterator() const
R__SUGGEST_FUNCTION("begin(), end() or range-based for loops.")
{
  return new RooLinkedListIter(makeLegacyIterator());
}
```
Since this uses class/function attributes, these need to be put *after* the class body and *before* the function body.

Defining `R__SUGGEST_FASTER_FUNCTIONS`, the compiler will e.g. issue:
```
root-src/roofit/roofitcore/src/RooAbsCollection.cxx:725:21: warning: 'fwdIterator' is deprecated:
This function has faster/more secure alternatives:
begin(), end() and range-based for loops. [-Wdeprecated-declarations]
    RooFIter iter = fwdIterator() ;
                    ^
```
With `R__SUGGEST_FASTER_CLASSES`, one gets:
```
/home/shageboe/root-dbg/include/RooStats/RooStatsUtils.h:64:7: warning: 'RooLinkedListIter' is deprecated: This class has a faster/more secure alternative: The ROOFIter is faster. [-Wdeprecated-declarations]
      RooLinkedListIter it = set->iterator();
```
PS: Names are totally up for debate.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks! Can you add one use case, to verify that we can actually apply the new macro?

ROOT preprocessor macros start with `R__` - note the double underscore. Could you please adjust your macro accordingly?

**Comment by hageboeck** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-O2 -DNDEBUG -DR__SUGGEST_FASTER_FUNCTIONS -DR__SUGGEST_FASTER_CLASSES"

**Comment by hageboeck** [comment]
@phsft-bot build just on ROOT-performance-centos7-multicore/default with flags -DCMAKE_CXX_FLAGS=\"-O2 -DNDEBUG -DR__SUGGEST_FASTER_FUNCTIONS -DR__SUGGEST_FASTER_CLASSES\"

**Comment by hageboeck** [comment]
@phsft-bot build just on ROOT-performance-centos7-multicore/default with flags -DCMAKE_CXX_FLAGS=\\"-O2 -DNDEBUG -DR__SUGGEST_FASTER_FUNCTIONS -DR__SUGGEST_FASTER_CLASSES\\"

**Comment by Axel-Naumann** [comment]
Super nice, thanks!

So `R__SUGGEST_CLASS` and `R__SUGGEST_FUNCTION` are now renamed to `R__SUGGEST_FASTER_...`? It's not always about speed, I actually prefer the original names.

Can we spell the diagnostic as `it has a superior alternative` such that we do not need to distinguish class/ function anymore?

And the maybe simply `R__SUGGEST` or `R__USE_INSTEAD`?

(I wanted to write this down so I don't forget; it's likely more efficient to chat about this in person in January! 🎆 )

**Comment by dpiparo** [comment]
I like the idea of being able to suggest methods and functions, @hageboeck . As a matter of fact, I would immediately use this strategy to complement the implementation of the `GetStatistics` method of DataFrame which will superseed for example `Get{Mean,StdDev}`...

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags just on ROOT-performance-centos7-multicore/default -DCMAKE_CXX_FLAGS=-DR__SUGGEST_NEW_INTERFACE

**Comment by hageboeck** [comment]
@phsft-bot build with flags just on ROOT-performance-centos7-multicore/default -DCMAKE_CXX_FLAGS=-DR__SUGGEST_NEW_INTERFACE

**Comment by hageboeck** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS=-DR__SUGGEST_NEW_INTERFACE just on ROOT-performance-centos7-multicore/default

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-performance-centos7-multicore/default with flags -DCMAKE_CXX_FLAGS=-DR__SUGGEST_NEW_INTERFACE

**Pull request merged**
