### PR TITLE
Fix ROOT-8839

### PR DESCRIPTION
**Pull request by vgvassilev**
Turns out that we forgot to link in ZLIB in libCore.

@oshadura could you test? We should make sure the tests are running if we are in `-Dbuiltin_zlib=On/Off`

### CODE REVIEW

**Comment by vgvassilev** [comment]
This failure does not seem caused by the PR.

**Comment by vgvassilev** [comment]
@bbockelm does that fix the issue for you?

**Comment by oshadura** [comment]
@vgvassilev Thanks for investigation!  I am testing if it fixing a problem for zlib 1.2.11!

**Comment by bbockelm** [comment]
@vgvassilev - not clear why you mentioned me in the above comment?  Did you mean to address Oksana instead?

**Comment by vgvassilev** [comment]
@bbockelm I got the impression you've been working together on this.

**Comment by vgvassilev** [comment]
The llvm patched is tracked in [D39002](https://reviews.llvm.org/D39002).

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
