### PR TITLE
[clad] Bump clad version to v0.7.

### PR DESCRIPTION
**Pull request by vgvassilev**
The new release includes some improvements:
  * Implement hessian matrices via the clad::jacobian interface.

See more at: https://github.com/vgvassilev/clad/blob/v0.7/docs/ReleaseNotes.md

This patch should be the last part of the fix for ROOT-10886.

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Review by oshadura — APPROVED** [review]

**Review by oshadura — CHANGES_REQUESTED** [review]
@vgvassilev actually I see there is a problem with windows http://cdash.cern.ch/viewBuildError.php?buildid=26144 Maybe @bellenot can help us please with logs from this machine?

**Comment by oshadura** [comment]
Ha, I believe it is simply a problem with this typo https://github.com/vgvassilev/clad/commit/9401215ba3b07ceec26ba460cea6b4a3d128e8c2#r42285026

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
ROOT-fedora31/noimt: no space left on device.

**Comment by pcanal** [comment]
macos: stale pcm files.

**Comment by vgvassilev** [comment]
That was not ready for merging as I think it breaks windows...

Let's wait for @bellenot and see how to fix it in another PR...

**Comment by pcanal** [comment]
I fixed the windows build when I pushed 464ea5ca718c293a6a7d76db948ced04eab6be8f to your branch and indeed I don't see a failure on Windows thereafter.

**Comment by vgvassilev** [comment]
Okay, thanks!

**Pull request merged**
