### PR TITLE
[cling] Fix build with `MacOSX15.0.sdk`

### PR DESCRIPTION
**Pull request by hahnjo**
Remove some headers from `std_darwin.modulemap` and backport https://github.com/llvm/llvm-project/commit/09ec0004eee2d9929d25cf519956cc470ffb33dd to fix the build of `std.pcm`.

---

This fixes the build but still has five failing tests:
```
The following tests FAILED:
        206 - gtest-math-mathcore-test-CladDerivatorTests (Failed)
        232 - gtest-roofit-histfactory-test-testHistFactory (Failed)
        235 - gtest-roofit-hs3-test-testRooFitHS3 (Failed)
        267 - gtest-roofit-roofitcore-test-testRooFuncWrapper (Failed)
        1729 - roottest-root-io-compression-make (Failed)
```

There seem to be at least two problems: an `UNREACHABLE executed`
```
builtin functions are handled elsewhere
UNREACHABLE executed at /Users/sftnight/jonas/root.src/interpreter/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:2036!
```

and Clad not being able to differentiate `__builtin_pow`:
```
[ RUN      ] CladDerivator.power
In module 'std' imported from input_line_1:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__math/exponential_functions.h:162:55: warning: Unsupported declaration
  using __result_type = typename __promote<_A1, _A2>::type;
                                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__math/exponential_functions.h:153:10: warning: function '__builtin_pow' was not differentiated because clad failed to d
ifferentiate it and no suitable overload was found in namespace 'custom_derivatives', and function may not be eligible for numerical differentiation.
  return __builtin_pow(__x, __y);
         ^
/Users/sftnight/jonas/root.src/math/mathcore/test/CladDerivatorTests.cxx:43: Failure
Expected equality of these values:
  48
  value->GetAsDouble()
    Which is: 0
[  FAILED  ] CladDerivator.power (6 ms)
```

I'm still investigating, starting with the first.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@petrozarytskyi, can you help out with the Clad issue here? We probably fail to find the propagator for __builtin_pow.

cc: @vaithak.

**Comment by hahnjo** [comment]
It seems the `UNREACHABLE` is connected to the issue regarding `__builtin_pow`, at least that is the builtin function that Clad's generated code tries to cast into a function pointer. The failure of `roottest-root-io-compression-make` was because I was building without `builtin_zstd` and the compressed size was different than expected.

From that point of view, the build fixes are complete. Note that the backport still needs to be synchronized to https://github.com/root-project/llvm-project/ before merging.

**Review by vgvassilev — APPROVED** [review]
Lgtm!

**Review by devajithvs — APPROVED** [review]

**Review by dpiparo — APPROVED** [review]

**Comment by dpiparo** [comment]
The failures are unrelated and most likely due to a glitch in the EOS based file server.

**Comment by dpiparo** [comment]
I propose to:
1. Disable CLAD on macbeta in master and merge this PR
2. Port this PR to 6.32, disable CLAD on macbeta and merge the PR
3. If the work is little, backport to 6.28 and 6.30 and disable clad. Otherwise, disable macbeta builds on 6.28 and 6.30 


OK with everybody @hahnjo @vgvassilev ?

**Comment by dpiparo** [comment]
Irrespective of the plan above or any modification to it, I believe we should sit down and understand how to deploy an automated way to build the module map. For example, internal headers will always be changed and it will be harder and harder to keep present versions of the sdk working and fix new ones.

**Comment by vgvassilev** [comment]
> I propose to:
> 
> 1. Disable CLAD on macbeta in master and merge this PR
> 2. Port this PR to 6.32, disable CLAD on macbeta and merge the PR
> 3. If the work is little, backport to 6.28 and 6.30 and disable clad. Otherwise, disable macbeta builds on 6.28 and 6.30
> 
> OK with everybody @hahnjo @vgvassilev ?

Makes sense. Could you also open a bug report and assign me on it?

**Comment by hahnjo** [comment]
> I propose to:
> 
> 1. Disable CLAD on macbeta in master and merge this PR

I decided to merge this PR as-is; `clad=OFF` for `mac-beta` is done in https://github.com/root-project/root/pull/15910

> 2. Port this PR to 6.32, disable CLAD on macbeta and merge the PR

Agreed; let's wait for the PR above to be merged and then we can backport the two.

> 3. If the work is little, backport to 6.28 and 6.30 and disable clad. Otherwise, disable macbeta builds on 6.28 and 6.30

We'll need to test how LLVM 13 in general behaves for the new SDK. I can hopefully do this today.

**Comment by hahnjo** [comment]
> Could you also open a bug report and assign me on it?

Done: https://github.com/root-project/root/issues/15912

**Pull request merged**
