### PR TITLE
update df103*.py

### PR DESCRIPTION
**Pull request by couet**
When generating the reference guide tutorial pages the doxygen ROOT filter invokes the Python script `makeimage.py` to generate the pictures produce by the tutorials. This Python script relies on the fact the canvases produced by the tutorial (Python ones) are still in memory after execution. They are retrieved with `ROOT.gROOT.GetListOfCanvases()`  . 
In the case of most `df*.py` examples it works fine: the later command gives the list of canvases. But  with `df103_NanoAODHiggsAnalysis.py` it gives an empty list of canvases because the canvases are created in a sub-function called `plot`. Python does some memory clean up at the end of `plot` and delete the canvas in memory. Adding `ROOT.SetOwnership(d, False)` allows to keep the canvases alive in the list of canvases after the macro execution.

### CODE REVIEW

**Comment by couet** [comment]
done

**Comment by couet** [comment]
@stwunsch can you approve this one so we can merge it ?

**Comment by stwunsch** [comment]
I would love to, but you just edited the GitHub comment and not the commit itself. Could you update the message there?

**Comment by couet** [comment]
ah ? Sorry but i do not know how to do that ....

**Comment by stwunsch** [comment]
Exactly, you can use `git commit --amend`!

**Comment by stwunsch** [comment]
Also, taggin the commit with something like `[RDF] <your short message>` is helpful for the commit history. Further, take care that you have a "short head message" and a "body", if you do it like this:

```
[RDF] Fix tutorial df103

<Here goes the long explanation!>
```

The long explanation the shows only up if you click on the commit on GitHub, which is a nice thing!

**Comment by couet** [comment]
I did something ..... not sure it worked ...

**Comment by couet** [comment]
@stwunsch : I did `git commit --amend`... is it ok ? ....

**Comment by stwunsch** [comment]
No ;) I'm judging from the commits associated to this PR. Most likely you have to force push to this branch. Actually, I'm not sure if you change only the commit message.

**Comment by stwunsch** [comment]
Have you pushed?

**Comment by couet** [comment]
yes..

**Comment by couet** [comment]
so ... ???

**Comment by stwunsch** [comment]
It's not here, try again :)

**Comment by couet** [comment]
Grrrr........

**Comment by stwunsch** [comment]
I'm sorry!

**Comment by couet** [comment]
I will redo the PR .... It is faster .....

**Comment by eguiraud** [comment]
this should work:

```bash
git checkout update-df103
git commit --amend # and change the commit message
git push --force upstream update-df103 # or maybe origin instead of upstream depending on your setup
```

**Comment by stwunsch** [comment]
:( @couet Please reopen this one! @eguiraud just sent a step by step explanation.

**Pull request closed without merging**
