### PR TITLE
Rename based fix for RConfig on case-insensitive systems

### PR DESCRIPTION
**Pull request by henryiii**
This is an alternative fix vs. #3360 mentioned on Mattermost; this renames `root/ROOT/RConfig.h` to `root/ROOT/RConfig.hxx` so that on case insensitive filesystems `root/RConfig.h` doesn't end up including itself if a user has the base directory ROOT is installed in before the `root` include in the include path. A file `root/ROOT/RConfig.h` is provided that also points at `root/ROOT/RConfig.hxx` for backward compatibility, and it prints a removal message. Since including `ROOT/RConfig.h` is probably quite rare, this could be dropped. Or it could avoid printing a message because it does no harm. (Even `RConfig.h` probably tends to be included mostly by ROOT). If most/all other includes are `.h`, this might be better for consistency.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
For the sake of (git) history, could you split this in two commits, one renaming `ROOT/RConfig.h` to `ROOT/RConfig.hxx` and and everything else (e.g. changing the `#include`s), and the other adding the forwarding, backward compatible `ROOT/RConfig.h`? This will allow `git` to realize that the history of `ROOT/RConfig.hxx` is that of `ROOT/RConfig.h` before the rename.

**Comment by henryiii** [comment]
@Axel-Naumann Good idea, I hadn't thought of that. Is this better?

**Comment by henryiii** [comment]
Github's overall diff is still claiming it is a delete and replace, but the history is correct if you look at the two commits by themselves. Reminder to merger: sure to rebase-and-merge instead of squash-and-merge.

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on windows10/default

**Comment by Axel-Naumann** [comment]
Thanks, @henryiii - with 25 yo projects, git history becomes really valuable to make sense of code :-)

**Comment by henryiii** [comment]
What about getting this into at least the 6.16 branch?

**Pull request merged**
