### PR TITLE
you can now select how MAKEEXE is building the test executable in cas…

### PR DESCRIPTION
**Pull request by pcanal**
…e of failure.

This is a follow up of f52497607d370f688e93df316da41af9ed1ff297 and a fix for ROOT-10632

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@oshadura The manual phsft-bot build did correctly cancel the automatic one but github is showing the build has failed rather than still building (which is the state of the manual build as of this writing).

**Comment by pcanal** [comment]
Failure are unrelated.

**Comment by pcanal** [comment]
> in MAKEXE `$BXX \$Opt \$ObjectFiles ...` (third subcommand) ?

Thanks!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
failures are unrelated

**Pull request merged**
