### PR TITLE
[bugfix] [core] Extend the message ID type to Long_t

### PR DESCRIPTION
**Pull request by andriish**
Extend the message ID type to Long_t to fix overflow described in #6715

### CODE REVIEW

**Comment by bellenot** [comment]
@pcanal can you take a look, please?

**Comment by andriish** [comment]
Hi @pcanal ,

this is quite a simple PR, would you have a look just to reduce the number of pull requests...

Best regards,

Andrii

**Review by pcanal — CHANGES_REQUESTED** [review]
Looks like the Print function needs to be updated but otherwise it looks good.

**Comment by andriish** [comment]
Hi @pcanal ,

thanks! I've updated the `Print` function.  The type conversion is not perfect there, it is an improvement to some extend. 

Best regards,

Andrii

**Comment by pcanal** [comment]
Can you also check the Print format they looks off.

**Comment by andriish** [comment]
Hi @pcanal ,

yes, my fault. ``5d`` -> ``5ld``.
The others should be ok.
Hopefully haven't overlooked any other places.

Best regards,

Andrii

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The failures are pre-existing.

**Comment by pcanal** [comment]
Thank you very much.

**Pull request merged**
