### PR TITLE
[DF] Add cross-checks for jitted expression type vs column type

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by ikabadzhov** [comment]
Changes are fine, only indentation in the test file should be fixed (so clang-tools do not complain)

**Comment by eguiraud** [comment]
I can't reproduce the crash, what's the stacktrace and what does valgrind say?

**Comment by eguiraud** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by ikabadzhov** [comment]
seg fault at trying to access nominal actually, sorry for the confusion. Minimal reproducer:
```C++
auto df = ROOT::RDataFrame(10).Define("x", [] { return 1.f; });
       auto s2 = df.Define("y", [] { return 1; })
                   .Vary({"x", "y"}, "ROOT::RVec<ROOT::RVecD>{{x*0.1}, {y*0.1}}", 1, "broken")
                   .Sum("y");
 auto ss2 = VariationsFor(s2);
 ```
 Giving:
 ```
 ===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
   rax 0xfffffffffffffe00   rbx 0x0000000000000000      rcx 0x00007ff8fd947d1a
   rdx 0x0000000000000000   rsi 0x00007ffd2ca04298      rdi 0x000000000009a1ac
   rbp 0x00007ffd2ca04298   rsp 0x00007ffd2ca04288       r8 0x00007ffd2ca03ff0
    r9 0x0000000000000000   r10 0x0000000000000000      r11 0x0000000000000246
   r12 0x00007ffd2ca04300   r13 0x00007ffd2ca042c0      r14 0x0000000001617200
   r15 0x00007ffd2ca046e0   rip 0x00007ff8fd947d1a   eflags [ PF ZF IF ]      
    cs 0x00000033            ss 0x0000002b               ds 0x00000000        
    es 0x00000000            fs 0x00000000               gs 0x00000000        
#0  0x00007ff8fd947d1a in wait4 () from /lib64/libc.so.6
#1  0x00007ff8fd8ba26b in do_system () from /lib64/libc.so.6
#2  0x00007ff8ff5b1285 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1617200) at [...]/root/core/unix/src/TUnixSystem.cxx:2108
#3  TUnixSystem::StackTrace (this=0x1617200) at [...]/root/core/unix/src/TUnixSystem.cxx:2399
#4  0x00007ff8ff5aea15 in TUnixSystem::DispatchSignals (this=0x1617200, sig=kSigSegmentationViolation) at [...]/root/core/unix/src/TUnixSystem.cxx:3619
#5  <signal handler called>
#6  0x00007ff8f689a3c8 in ?? ()
#7  0x0000000000000000 in ?? ()
===========================================================
 ```
 A `valgind ./execuatbe` gave me very long message: https://codimd.web.cern.ch/vglD-rvTSZq4p-90Ag_V3A?view.
 
 
 I only hid my path to root. Everything is direct as what I produced.

**Review by ikabadzhov — APPROVED** [review]

**Comment by eguiraud** [comment]
@phsft-bot build please

**Pull request merged**
