### PR TITLE
Drop deprecated register storage class from libAfterImage

### PR DESCRIPTION
**Pull request by amadio**
Fix for these warnings: http://cdash.cern.ch/viewBuildError.php?type=1&buildid=454389. No functional change otherwise.

I still need to test that with external libAfterImage this is not a problem, so please let me merge this myself.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Isn't `register` only deprecated in C++?

**Comment by amadio** [comment]
@vgvassilev Yes, for C++17, but it's not really used in C anymore either. In any case, I will close this in favor of just suppressing the warning. Axel is right, it's better to avoid diverging too much from upstream.

**Comment by vgvassilev** [comment]
If we see the warning when compiling *.c files that'd mean that we compile them in C++ mode. Otherwise, we probably should #include the c header files in an extern C context.

**Comment by amadio** [comment]
Hi @vgvassilev that's actually a good point. I will make sure that's the case (extern C).

**Pull request closed without merging**
