### PR TITLE
[RDF][Doc] Return non-zero exit code for df026 

### PR DESCRIPTION
**Pull request by stwunsch**
* Increases the test coverage of interacting with third-party python packages
* Improve message to user if the pandas package is not found

### CODE REVIEW

**Comment by stwunsch** [comment]
@etejedor @Axel-Naumann @eguiraud Feel free to argue for or against it!

**Comment by eguiraud** [comment]
@stwunsch as discussed, my opinion is that the previous message was user-friendlier than an actual python runtime error, and to increase test coverage it should be enough to change `exit()` to `exit(1)`.

**Comment by Axel-Naumann** [comment]
Would it be nicer to catch and help the user "please install python-pandas to run this tutorial" and then exit 1 (aka error)? Else there will be an import error that users might not understand without Google's help? I'm asking, I don't have an opinion yet :-)

**Comment by stwunsch** [comment]
@Axel-Naumann You said this very nicely. That's basically my questions :dagger: 
Or also: How shall we treat such dependencies in tutorial consistently? In tests, we agreed on "just import and fail". Here, we still have the option.

**Comment by Axel-Naumann** [comment]
I agree with @eguiraud that we need `exit(1)` if the import fails.

**Comment by etejedor** [comment]
The idea of making the tutorials fail more gracefully than tests sounds good to me. Messages should be more user friendly (@Axel-Naumann already provided a good suggestion for this one). Also agree with the `exit(1)`.

**Comment by stwunsch** [comment]
Alrighty, so I put there again the try/except guards and just return `exit(1)`, let's see how it goes!

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
Either something is wrong or we have everywhere pandas installed :thinking:

**Comment by stwunsch** [comment]
Indeed, I checked a few systems and pandas is there.

**Pull request merged**
