### PR TITLE
[gpad] Introduce `TPad::Add()`, `TPad::AddFirst()` and `TPad::Remove()` methods

### PR DESCRIPTION
**Pull request by linev**
Let add and remove primitives from the pad without set of `gPad` pointer.

Automatically set modified flag when primitives are changing.

Use methods in `TObject::Draw()`, `TObject::DrawClone()`, `TObject::Pop()` methods

Also in webgui and `graf2d/gpad` classes

### CODE REVIEW

**Comment by couet** [comment]
LGTM, There are more TLIst::Addxxx methods that might be interesting to have. FindObject also may be. Some tutorials can be also changed:
```
eve/SplitGLView.C:   fPad->GetListOfPrimitives()->Delete();
eve/SplitGLView.C:   fPad->GetListOfPrimitives()->Add(gGeoManager->GetTopVolume());
eve7/lego.C:      p->GetListOfPrimitives()->Add(h, "LEGO2");
eve7/lego.C:      p->GetListOfPrimitives()->Add(s);
eve7/lego.C:      p->GetListOfPrimitives()->Add(line, "LINE");
geom/csgdemo.C:      bool drawn = gPad->GetListOfPrimitives()->FindObject(top);
geom/geodemo.C:      bool drawn = gPad->GetListOfPrimitives()->FindObject(top);
webgui/qtweb/ExampleWidget.cpp:   canv->GetListOfPrimitives()->Add(geom,"");
webgui/qtweb/ExampleWidget.cpp:   canv->GetListOfPrimitives()->Add(pm,"");
webgui/qtweb/ExampleWidget.cpp:   canv->GetListOfPrimitives()->Add(pl,"");
```

**Comment by linev** [comment]
> There are more TLIst::Addxxx methods

`AddLast` and `Add` are equivalent. 
Also there is no need duplicate methods with and without draw option.

And TList::Delete method is too specialized and therefore I prefer to keep it.

Idea of PR is provide shortcuts for very basic manipulation with primitives - add and remove.
Mainly in different tutorials. More specific code can still be done with `pad->GetListOfPrimitives()`

**Comment by couet** [comment]
It looks good as first approch

**Review by couet — APPROVED** [review]

**Review by vepadulano — CHANGES_REQUESTED** [review]
Can we please think twice before adding new public methods to a long virtual inheritance chain such as the one of `TVirtualPad`? Can we maybe make these methods private and only use them internally in ROOT?

**Comment by vepadulano** [comment]
Alright, at a first glance I completely missed the point of the changes! Thanks for the clarification. Let me see if I understand this correctly. With these changes, in principle, one could drive a ROOT graphics program with the following (pseudo) code pattern?

```cpp

ROOT::RDataFrame df{...};
auto histoptr = df.Histo1D();

TCanvas c;
c.Add(histoptr.GetPtr()) // GetPtr() returns a TH1D* in this case
c.Draw();
```

That is without needing to ask the histogram to draw itself?

**Comment by linev** [comment]
> That is without needing to ask the histogram to draw itself?

Yes.

**Comment by linev** [comment]
> c.Add(histoptr.GetPtr());

In some cases one need to use `c.Add(histoptr.GetPtr()->Clone())` if handle with original histogram will be deleted at the end of the macro

**Comment by vepadulano** [comment]
> Yes.

But this is *wonderful*! This is a fantastic approach imho! Can I just throw in another suggestion then. Since we are introducing these new API methods from scratch and they do not belong already to any of the base classes of `TVirtualPad`, maybe we can take the opportunity to give them some more meaningful name.

For example, `Add` could be `RegisterDrawable` or `AdoptDrawable` or just `Register`/`Adopt`. I would be in this sense very much in favour of having `Adopt(std::shared_ptr<TObject> obj)` so that the memory ownership is clear. This would for example enable any use case where the drawable object is not registered with the list of global cleanups.

In the same spirit, I don't see (yet) the need for `AddFirst` and `Remove`. What are the user-side reasons for these?
In the current changes:
* `AddFirst` is defined in the class but never used anywhere else, so it should be removed.
* `Remove` is used only for internal purposes and could be made a private method.

**Comment by linev** [comment]
`Drawable` is "reserved" word for the ROOT7 classes :) 
Drawing of `TObject` in ROOT6 is just adding it to list of canvas primitives.

My idea is to move **some** `TList` methods of primitives to `TPad`, ensure list exist and automatically mark pad modified after that. 

`TPad::Remove()` is not internal method. 
`TObject::Pop()` and `TPad::Pop()` used them. Also it is just contrary to `TPad::Add()`.

**Comment by couet** [comment]
This is a nice way to avoid having the concept of "current pad".

**Comment by vepadulano** [comment]
> Also it is just contrary to TPad::Add().

Not enough reason for me to make a new public method just to provide some vague simmetry.

> TObject::Pop() and TPad::Pop() used them.

Exactly! So `TPad::Remove` is internal to ROOT classes only. It can be a private method of `TVirtualPad` and then the `Pop` methods can access it (`TPad::Pop` will be able to access it because it inherits from `TVirtualPad`, `TObject` can easily access the method with an `Internal` helper such as `ROOT::Internal::GraphicsUtils::CallTVirtualPadRemove`)

We should strive imho to minimize the public surface of our APIs so we do not increase the maintenance burden.

> Drawable is "reserved" word for the ROOT7 classes :)

Fine, not too big of an issue I guess, still `Register` or `Adopt` sound better but that is probably just my own opinion. I would still very much encourage the addition of a memory-safe API with smart pointers anyway.

> TPad::AddFirst is not used by this PR, but can appear later.
For instance TFrame object always must be first in list of primitives.
Or one can add as first primitive histogram drawing axis - after all other objects already created.

Again from this description everything sounds internal to ROOT only and not something the user should care about. So I insist also `AddFirst` is removed from this PR or at least made private

**Comment by linev** [comment]
>>    Also it is just contrary to TPad::Add().

> Not enough reason for me to make a new public method just to provide some vague simmetry.

It is. One creates canvas, store image, remove and delete temporary object, create next image or let canvas running.
We did not have such interface up to now - therefore we did not provide such demos. Now it can be possible.


>>    TPad::AddFirst is not used by this PR, but can appear later.

> Again from this description everything sounds internal to ROOT only and not something the user should care about. 

No, it can be very well used in tutorials. Manipulating primitives order was not easy before. With such few methods it will be easy. 


> Fine, not too big of an issue I guess, still Register or Adopt sound better but that is probably just my own opinion

I prefer to stay in `ROOT6`/`TList` logic and naming used there. `TPad` is just list of primitives and can be considered so in  tutorials.

**Comment by vepadulano** [comment]
> It is. One creates canvas, store image, remove and delete temporary object, create next image or let canvas running.
We did not have such interface up to now - therefore we did not provide such demos. Now it can be possible.

> No, it can be very well used in tutorials. Manipulating primitives order was not easy before. With such few methods it will be easy.

Again, why is any of this something a final ROOT user would want to do? This sounds very complicated and old imperative approach and I do not see the appeal of it for new code, as much as it may be living in core parts of the codebase.

I could maybe, just maybe see this approach being used when creating plotting extensions based on ROOT graphics, but I strongly believe we should not provide new public APIs unless there is an explicit request from users/github issue/forum post or something similar. Of all the changes of this PR, only the `Add` method fits in this description.

And again let me ask for providing a modern memory safe API with proper memory management in place by default.

**Comment by linev** [comment]
> And again let me ask for providing a modern memory safe API with proper memory management in place by default.

This need redesign of pad list of primitives. Finally we just need other pad classes. This PR is not change of `TPad` memory management by simple extension of existing API. I had in mind `df027` tutorial which now looks like:

```
new TCanvas(); // assign gpad
...
histo->Draw()
```

I want to avoid gpad - for that I need to write now:
```
auto c1 = new TCanvas();
...
if (c1->GetListOfPrimitives()) {
   c1->GetListOfPrimitives()->Add(histo);
   c1->Modified();
}
```

This is main pattern for 90% of graphical tutorials which I want to be looking:
```
auto c1 = new TCanvas();
...
c1->add(histo);
```

**Review by vepadulano — COMMENTED** [review]
Thanks @linev for the discussion and the many insights into your design process! This is the summary of my opinions given the discussion so far:

* I *really* like the approach of the changes given by the `Add` method, which removes the need for a global object in user-facing code with ROOT graphics (traditional and web based alike)
* I do not like providing new public APIs without a strong reason and the justifications for `AddFirst` and `Remove` are not enough in my opinion
* I would have preferred a memory safe API, but I will admit that it might not be trivial to make it work with all the inner machineries of the rest of the traditional ROOT graphics system which does not take memory ownership into account.

All in all, I cannot give a full approval of the PR, but I definitely like at least the spirit and the direction of the changes that simplify end-user code and hide unnecessary complexity.

**Review by vepadulano — COMMENTED** [review]
Extra comment just to check if my explicit approval is actually necessary or not

**Pull request merged**
