### PR TITLE
[Experimental PyROOT] Generic pythonizations

### PR DESCRIPTION
**Pull request by stwunsch**
There are generic pythonizations to be added. I've started with the pretty printing feature.

Additionally, I've added a `test` directory with the unit-tests and adjusted the build system.

More generic possible pythonizations:

 - `__cppname__` attribute (It vanished in the new cppyy? I could do a workaround/pythonization.)
- Ideas?

### CODE REVIEW

**Comment by stwunsch** [comment]
To be checked: `TNamed` and `TObject` are not piped through the pythonizations in the new cppyy (?)

**Comment by stwunsch** [comment]
I can confirm that `TObject` does not enter any pythonizor function (checked by putting a print statement into a pythonization function, which are activated by the C++ class name).

**Comment by stwunsch** [comment]
For all practical use-cases it should be fine. However, the missing `TObject`, `TNamed`, ... (?) pythonizations should be mention somewhere so that we do not forget about it.

**Comment by etejedor** [comment]
@wlav confirmed that those classes do not go through the pythonization pipeline because `TInterpreter` and its base classes are touched early, before the pythonizations are installed.
@stwunsch is there anything else you would like to add/modify in this PR? Perhaps adding a comment about the aforementioned fact?

**Comment by stwunsch** [comment]
@etejedor added comments about the pythonization of `TNamed` and `TObject` to the test. i'll do a PR build to check the code again and merge afterwards.

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by wlav** [comment]
In PyROOT-land, the EnableAutoloading also lives in cppyy.py. I'm pretty sure though that you can defer it to e.g. a call inside the constructor of TPyROOTApplication. You can test that and if it works okay, remove the call in experimental, see whether that solves the issue. I can move the call down to the backend as well (only reason not to do so is that current cppyy works with ancient PyPy and such a move would break that).

**Comment by etejedor** [comment]
Commenting out the call to `gbl.gInterpreter.EnableAutoLoading` in the cppyy of experimental does not seem to have any effect - e.g. `TNamed` and `TObject` are still not pythonized. Perhaps there is something else that touches them early?
In the current PyROOT there a few pythonizations for `TObject`, we can have a closer look to this issue when we move them to experimental.

**Comment by wlav** [comment]
Found it: in cppyy/_cpython_cppyy.py, the call "add_default_paths()" touches gSystem. Remove that as well, and things work.

**Comment by etejedor** [comment]
Still not there, even after removing `add_default_paths`, if I run:
```python
import ROOT
o = ROOT.TObject()
n = ROOT.TNamed()
s = ROOT.TString()
```
my pythonizor function only processes `TString`.

**Comment by wlav** [comment]
That's in ROOT, not cppyy. I had a quick look around and noticed for example:
```
void PyROOT::Init()
{
   // Initialize and acquire the GIL to allow for threading in ROOT
   PyEval_InitThreads();

   // Bind ROOT globals that will be needed in ROOT.py
   AddToGlobalScope("gROOT", "TROOT.h", gROOT, Cppyy::GetScope(gROOT->IsA()->GetName()));
   AddToGlobalScope("gSystem", "TSystem.h", gSystem, Cppyy::GetScope(gSystem->IsA()->GetName()));
   AddToGlobalScope("gInterpreter", "TInterpreter.h", gInterpreter, Cppyy::GetScope(gInterpreter->IsA()->GetName()));
}
```
(which, aside, should not be necessary at all anymore).

Note that these base classes that will pop up everywhere do not need to be pythonized with a callback. You can just fix them up after their binding, but before returning from "import ROOT". The point of callbacks is purely to allow everything to remain as lazy as possible, which doesn't apply to TObject.

**Comment by etejedor** [comment]
As for the `AddToGlobalScope` calls, I kept them for now until I know how much of the current content of `ROOT.py` we need to keep (they are used from there a few times).

**Pull request merged**
