### PR TITLE
More cmake fixes for cudnn 

### PR DESCRIPTION
**Pull request by lmoneta**
port last two commits of #5103  in the master

### CODE REVIEW

**Comment by pcanal** [comment]
The file ```cmake/modules/#SearchInstalledSoftware.cmake#``` (note the # characters) seems to have been inadvertently added to the commit.

**Comment by lmoneta** [comment]
> The file `cmake/modules/#SearchInstalledSoftware.cmake#` (note the # characters) seems to have been inadvertently added to the commit.

Thank you Philippe for noticing this ! It is removed now

**Comment by oshadura** [comment]
@lmoneta, can I ask you please to remove empty lines (it makes code look more uniform). Thank you so much!

**Comment by lmoneta** [comment]
ok, I'll do it

**Comment by oshadura** [comment]
@phsft-bot build on ROOT-performance-centos7-multicore/default with flags -Dfail-on-missing=ON

**Comment by Axel-Naumann** [comment]
Starting build on ROOT-performance-centos7-multicore/default with flags -Dfail-on-missing=ON -Dcudnn=On

**Comment by oshadura** [comment]
@phsft-bot build on ROOT-performance-centos7-multicore/default with flags -Dfail-on-missing=ON -Dcudnn=On

**Comment by oshadura** [comment]
@phsft-bot build on ROOT-performance-centos7-multicore/default with flags -Dfail-on-missing=ON -Dcudnn=On -Dcuda=ON -Dtmva-gpu=ON

**Comment by oshadura** [comment]
Having `-Dfail-on-missing=ON -Dcudnn=On -Dcuda=ON -Dtmva-gpu=ON` -> makes build fail (OK) https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/71742/console , while `Dfail-on-missing=ON -Dcudnn=On` -> no... @amadio what is expected behavior that should be here?

**Comment by lmoneta** [comment]
If you have -DCudnn=On but Cuda=Off and TMVA-gpu=Off then the flag has no effect. This is expected

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
I expect that `-Dfail-on-missing=On -Dcudnn=On` fails if it cannot build CuDNN.

**Pull request merged**
