### PR TITLE
thisroot: Clean JUPYTER related variables possibly set by ROOT 6.

### PR DESCRIPTION
**Pull request by Jeremias1229**
Thanks to Wile E Coyote

### CODE REVIEW

**Comment by pcanal** [comment]
This PR is trying to merge the v5-34 patches branch with the master which probably not what you meant :)

**Comment by pcanal** [comment]
And the (Likely) commits that do "[thisroot: Clean JUPYTER related variables possibly set by ROOT 6](https://github.com/root-project/root/pull/11680#top)" have already been merged in the v5-34-00-patches branches (earlier today)

**Comment by Jeremias1229** [comment]
.patch

**Comment by Jeremias1229** [comment]
.patch

**Comment by Jeremias1229** [comment]
.patch

**Comment by Jeremias1229** [comment]
.patch

**Pull request closed without merging**
