### PR TITLE
Afterimage fixes

### PR DESCRIPTION
**Pull request by ellert**
# This Pull request:

## Changes or fixes:

Since the possibillity to use an external libAfterImage was removed, the built-in version needs some fixes.
See commit messages for details.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by ferdymercury** [comment]
Thanks a lot for this @ellert ! Out of curiosity: have you explored if it's feasible to migrate towards a CMakeLists and add_subdirectory, instead of a configure script?

**Comment by bellenot** [comment]
> @bellenot you already implemented such a CMakeLists.txt for Windows, right? Would it be doable also for the other platforms?

I guess so

**Comment by ferdymercury** [comment]
> I guess so

Oh, I see now the switch of WIN32 in line 414 of SearchInstalled...

**Comment by ellert** [comment]
> Thanks a lot for this @ellert ! Out of curiosity: have you explored if it's feasible to migrate towards a CMakeLists and add_subdirectory, instead of a configure script?

libAfterImage uses two different build systems, one for windows (nmake) and one for the rest (autotools).
The one for windows uses a pre-generated configuration file win32/config.h and does not support any customizations.
The other one uses a configure script to generate the config.h from config,h,in.
The conversion of the windows build to cmake is easy, since there is no need to generate any files.
For the other platforms one has to generate config.h, which makes changing the build system a bigger task in this case.

**Comment by ferdymercury** [comment]
Thanks!! LGTM. Related PR: https://github.com/root-project/root/pull/15044

**Review by guitargeek — APPROVED** [review]
Thanks!

Why was this not reviewed so far? To me, this looks like a change that needs to be in the 6.32 release, if we want to make the packaging job possible!

**Comment by guitargeek** [comment]
Unfortunately, this broke things on macOS beta:
https://github.com/root-project/root/actions/runs/9177178669/job/25234168412
```txt
2024-05-21T15:30:21.5677370Z Undefined symbols for architecture arm64:
2024-05-21T15:30:21.5679910Z   "_AddExtensionBlock", referenced from:
2024-05-21T15:30:21.5680410Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5681620Z   "_DGifCloseFile", referenced from:
2024-05-21T15:30:21.5682200Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5682650Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5683040Z       _gif2ASImage in libAfterImage.a[77](import.o)
2024-05-21T15:30:21.5683320Z   "_DGifGetExtension", referenced from:
2024-05-21T15:30:21.5683610Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5684190Z   "_DGifGetExtensionNext", referenced from:
2024-05-21T15:30:21.5684600Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5685300Z   "_DGifGetImageDesc", referenced from:
2024-05-21T15:30:21.5685720Z       _get_gif_image_desc in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5686420Z   "_DGifGetLine", referenced from:
2024-05-21T15:30:21.5686680Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5689120Z   "_DGifGetRecordType", referenced from:
2024-05-21T15:30:21.5689450Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5689740Z   "_DGifOpen", referenced from:
2024-05-21T15:30:21.5690010Z       _open_gif_read in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5691170Z   "_EGifCloseFile", referenced from:
2024-05-21T15:30:21.5691590Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5694000Z   "_EGifOpenFileHandle", referenced from:
2024-05-21T15:30:21.5694590Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5695030Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5696720Z   "_EGifPutExtension", referenced from:
2024-05-21T15:30:21.5697000Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5697300Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5698100Z       _write_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5699050Z   "_EGifPutExtensionFirst", referenced from:
2024-05-21T15:30:21.5699840Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5700500Z   "_EGifPutExtensionLast", referenced from:
2024-05-21T15:30:21.5701670Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5702160Z   "_EGifPutImageDesc", referenced from:
2024-05-21T15:30:21.5702440Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5702730Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5703040Z       _write_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5703590Z   "_EGifPutLine", referenced from:
2024-05-21T15:30:21.5703970Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5706030Z       _write_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5706480Z   "_EGifPutScreenDesc", referenced from:
2024-05-21T15:30:21.5711850Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5713970Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5714740Z   "_FreeExtension", referenced from:
2024-05-21T15:30:21.5715580Z       _free_gif_saved_image in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5716070Z       _free_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5716550Z       _get_gif_image_desc in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5716890Z       _get_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5717330Z   "_FreeMapObject", referenced from:
2024-05-21T15:30:21.5717610Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5717900Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5718200Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5718490Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5718790Z       _free_gif_saved_image in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5719110Z       _free_gif_saved_images in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5719430Z       _get_gif_image_desc in libAfterImage.a[80](ungif.o)
2024-05-21T15:30:21.5719690Z       ...
2024-05-21T15:30:21.5719850Z   "_GifErrorString", referenced from:
2024-05-21T15:30:21.5720130Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5720420Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5720700Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5721000Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5721280Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5721550Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5721830Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5722110Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5722390Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5722680Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5722920Z       ...
2024-05-21T15:30:21.5723160Z [ 85%] Building CXX object gui/gui/CMakeFiles/Gui.dir/src/TGGC.cxx.o
2024-05-21T15:30:21.5723490Z   "_MakeMapObject", referenced from:
2024-05-21T15:30:21.5723750Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5724050Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5724340Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5724780Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5725050Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5725330Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5725610Z       _ASImage2gif in libAfterImage.a[75](export.o)
2024-05-21T15:30:21.5725850Z       ...
2024-05-21T15:30:21.5726030Z ld: symbol(s) not found for architecture arm64
2024-05-21T15:30:21.5726600Z clang: error: linker command failed with exit code 1 (use -v to see invocation)
2024-05-21T15:30:21.5738220Z make[2]: *** [lib/libASImage.so] Error 1
2024-05-21T15:30:21.5741270Z make[1]: *** [graf2d/asimage/CMakeFiles/ASImage.dir/all] Error 2
2024-05-21T15:30:21.5742270Z make[1]: *** Waiting for unfinished jobs....
```

This needs to be hotfixed

**Pull request merged**
