### PR TITLE
Reduce the size difference between title and text in issue template

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
What about the other templates? :-)

**Comment by pcanal** [comment]
Other templates also updated.

**Review by Axel-Naumann — APPROVED** [review]

**Comment by pcanal** [comment]
macos failure:
```
10:08:09  error: could not read '.git/rebase-apply/head-name': No such file or directory
```
windows failure is pre-existing.

**Comment by pcanal** [comment]
ROOT-debian10-i386/cxx14 : cancelled manually .. taking too long to acquire a worker node.

**Pull request merged**
