### PR TITLE
[hist] increase precision of TH1's and TGraph's SavePrimitive to double

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Fixes https://github.com/root-project/root/issues/16687

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by dpiparo** [comment]
Thanks! Does it make sense to restore the previous precision once done, i.e. not altering the state of `std::cout`?

**Comment by ferdymercury** [comment]
> Thanks! Does it make sense to restore the previous precision once done, i.e. not altering the state of `std::cout`?

Hmmm, Thats already the case with the sstream, see last line in the code. Or you mean sth else?

**Comment by dpiparo** [comment]
I really meant that and missed that line. Thanks for the clarification!

**Comment by dpiparo** [comment]
The two failures on Windows are real. The test that fails is `gtest-hist-hist-testMapCppName`.

What I believe it should be done is to increase the tolerance from 200 to 211 here: https://github.com/root-project/root/blob/master/hist/hist/test/test_MapCppName.cxx#L48

**Comment by pcanal** [comment]
> What I believe it should be done is to increase the tolerance from 200 to 211 here: [master/hist/hist/test/test_MapCppName.cxx#L48](https://github.com/root-project/root/blob/master/hist/hist/test/test_MapCppName.cxx?rgh-link-date=2024-11-18T14%3A02%3A38Z#L48)

Isn't it the base that changed rather than the tolerance?

**Comment by ferdymercury** [comment]
Thanks, fixed

**Pull request merged**
