### PR TITLE
[cxxmodules] TCling needs to autoparse headers which it has no module for:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Fixes roottest/cling/reflex/classVersion_rflx.log.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
Depends on #2375 and #2356

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
Cherry picked in #2716 to integrate with root-project/roottest#220

**Pull request closed without merging**
