### PR TITLE
Remove empty file

### PR DESCRIPTION
**Pull request by ellert**
I don't think these should be in the repo.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by ellert** [comment]
I rebased this pull request because of conflicts.
Two of the empty files in the original request were already removed from master since the PR was first created. A third empty file in the original request in now no longer empty, so this file was also dropped from the PR.

**Comment by ellert** [comment]
Everything in the original version of this PR has been gradually fixed by other commits, except for the removal of the  tree/dataframe/test/.gdb_history file. So the rebased proposed change is now quite small.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Pull request merged**
