### PR TITLE
Add ROOT7 RBrowser using OpenUI5

### PR DESCRIPTION
**Pull request by bellenot**
First implementation of the ROOT7 Browser, using OpenUI5 Web GUI
To try it:
root[0] #include "ROOT/RBrowser.hxx"
root[1] using namespace ROOT:Experimental;
root[2] RBrowser browser;

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build with-flags -Droot7=ON

**Comment by bellenot** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by bellenot** [comment]
@phsft-bot build just on ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags -Droot7=ON

**Comment by bellenot** [comment]
@linev FYI, in order to make it work in its current state, one need to install the code editor from OpenUI5...

**Comment by linev** [comment]
You mean - I have to add it into openui5 package.
In principle, it is easy, but probably we could postpone it for the moment when @amadio is back.
Idea was to modify cmake files and place openui5 package outside of the ROOT repository.
For now you could activate following line in the html file:
```
openui5src: "https://openui5.hana.ondemand.com/"
```
It should be enough for the moment, I guess

**Pull request merged**
