### PR TITLE
[TMVA] Fix tensor operations for const RTensor

### PR DESCRIPTION
**Pull request by axmat**
This should fix Copy, Transpose, Squeeze, ExpandDims, and Reshape for const RTensor.

### CODE REVIEW

**Review by ashlaban — APPROVED** [review]
Thanks axmat for providing!

The patch seems straight forward enough: fix const correctness. Looks good to me.

**Review by stwunsch — APPROVED** [review]
Nice, many thanks!

**Comment by stwunsch** [comment]
Ah, wait. We haven't run the CI yet. @phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot build

**Pull request merged**
