### PR TITLE
[cmake] Update XRootD to v5.4.3

### PR DESCRIPTION
**Pull request by matthewfeickert**
# This Pull request:

This PR is a backport of PR #10725 for `v6.26`.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@phsft-bot build

**Review by bellenot — APPROVED** [review]
Thanks Matthew!

**Comment by matthewfeickert** [comment]
@bellenot @Axel-Naumann small ping on this so it doesn't fall off the view (though there isn't much rush on this and I appreciate that there is plenty of other work that legitimately needs attention).

**Comment by bellenot** [comment]
Sorry @matthewfeickert

**Comment by matthewfeickert** [comment]
Nothing to be sorry about! Thanks for the review and merge. :)

**Pull request merged**
