### PR TITLE
External nlohmann::json does not have json_fwd.hpp

### PR DESCRIPTION
**Pull request by ellert**

### CODE REVIEW

**Comment by linev** [comment]
Again same problem? On which platform?

I have external `hlohmann/json.hpp` (OpenSUSE) and it provided with `json_fwd.hpp`.
By default ROOT always tries first to build against external version - mean in my case it will try to build with full headers.

**Comment by ellert** [comment]
> Again same problem? On which platform?

Fedora 34:
```
$ rpm -q json-devel
json-devel-3.9.1-2.fc34.x86_64
$ rpm -ql json-devel
/usr/include/nlohmann
/usr/include/nlohmann/json.hpp
/usr/lib64/cmake/nlohmann_json
/usr/lib64/cmake/nlohmann_json/nlohmann_jsonConfig.cmake
/usr/lib64/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake
/usr/lib64/cmake/nlohmann_json/nlohmann_jsonTargets.cmake
/usr/lib64/pkgconfig/nlohmann_json.pc
/usr/share/doc/json-devel
/usr/share/doc/json-devel/README.md
/usr/share/licenses/json-devel
/usr/share/licenses/json-devel/LICENSE.MIT
```

**Comment by linev** [comment]
I have better variant - I will provide PR soon.
One could test from cmake if forward declaration exists

**Comment by linev** [comment]
Here alternative: https://github.com/root-project/root/pull/8345
Please try it on your platform.
Please compile with `-Droot7=ON -Dwebgui=ON -DCMAKE_CXX_VERSION=14` flags and then try `tutorials/eve7/event_demo.C` macro. I have doubt that cling like ifdefs such this in public includes.

**Comment by linev** [comment]
I closing with PR while https://github.com/root-project/root/pull/8345 merged and should solve the problem

**Pull request closed without merging**
