### PR TITLE
cppcheck: fix some reports

### PR DESCRIPTION
**Pull request by serval2412**
[graf2d/asimage/src/libAfterImage/afterbase.c:1282]: (style) Array index 'i' is used before limits check
[graf2d/asimage/src/libAfterImage/libungif/gifalloc.c:61]: (error) Memory leak: Object
[graf2d/win32gdk/src/TGWin32.cxx:4540]: (error) Memory leak: GIFarr
[graf3d/eve/src/TEveCalo2DGL.cxx:169]: (error) Memory leak: sliceVal
[graf3d/eve/src/TEveCalo2DGL.cxx:169]: (error) Memory leak: sliceValRef
[graf3d/eve/src/TEveCalo2DGL.cxx:369]: (error) Memory leak: sliceValsUp
[graf3d/eve/src/TEveCalo2DGL.cxx:369]: (error) Memory leak: sliceValsLow
[graf3d/eve/src/TEveCalo2DGL.cxx:369]: (error) Memory leak: sliceValsUpRef
[graf3d/eve/src/TEveCalo2DGL.cxx:369]: (error) Memory leak: sliceValsLowRef
[graf3d/eve/src/TEvePointSet.cxx:354]: (error) Memory leak: subarr

[graf3d/gl/src/gl2ps.cxx:1382] -> [graf3d/gl/src/gl2ps.cxx:1382]: (style) Same expression on both sides of '|'
see http://octave.org/doxygen/3.6/d3/d9c/gl2ps_8c_source.html#1343

[hist/hist/src/TFormula.cxx:1741]: (style) Array index 'i' is used before limits check.
[hist/hist/src/TFormula.cxx:1810]: (style) Array index 'i' is used before limits check.
[hist/hist/src/TGraphSmooth.cxx:173]: (style) Array index 'imin' is used before limits check
[hist/hist/src/TPrincipal.cxx:714]: (error) Memory leak: hX
[hist/hist/src/TPrincipal.cxx:714]: (error) Memory leak: hD
[hist/hist/src/TPrincipal.cxx:714]: (error) Memory leak: hP

[hist/histpainter/src/TGraph2DPainter.cxx:416]: (style) Array index 'js' is used before limits check.
[hist/histpainter/src/TGraph2DPainter.cxx:455]: (style) Array index 'js' is used before limits check.
[interpreter/llvm/src/tools/bugpoint/ToolRunner.cpp:386]: (error) When Pos==CommandLine.size(), CommandLine[Pos] is out of bounds

+Prefer prefix ++/-- operators for non-primitive types

### CODE REVIEW

**Comment by serval2412** [comment]
Argh, I must revert all llvm part... I won't be able to do this before 2 days...

**Comment by serval2412** [comment]
vgvassilev: I reverted all llvm part, hope it's ok now.

**Comment by vgvassilev** [comment]
Thanks, I'd defer reviewing to the other code owners.

**Comment by serval2412** [comment]
Any update?

**Comment by lmoneta** [comment]
These changes are fine for me. Thanks for the fixes 
Lorenzo

**Comment by Axel-Naumann** [comment]
@phsft-bot build because you're stuck.

**Comment by Axel-Naumann** [comment]
@serval2412 it doesn't build... Please fix your PR, then I'll make sure roottest works and merge.

**Comment by serval2412** [comment]
I removed the 2 wrong delete

**Comment by osschar** [comment]
+1 for eve/gl

**Comment by serval2412** [comment]
After having install XPM headers, I tried to build root to not repeat the same error but had this:
Making include/compiledata.h
g++ -O2 -DNDEBUG -pipe -m64 -std=c++11 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -Iinclude   -pthread  -MMD -MP -o core/base/src/TObject.o -c /home/julien/projects/root/core/base/src/TObject.cxx
In file included from include/TObject.h:16:0,
                 from /home/julien/projects/root/core/base/src/TObject.cxx:38:
include/RConfigure.h:39:2: error: invalid preprocessing directive #@
 #@has_found_attribute_always_inline@ R__HAS_ATTRIBUTE_ALWAYS_INLINE /**/
  ^

I searched about this error and found https://root-forum.cern.ch/t/compile-error-related-to-directive-in-rconfigure-h/23546/3

I also tried to follow the INSTALL file but:
1) there's not "root" directory but there's a "rootx" directory
however "cmake ../rootx" (from <main dir>/build) displays some config and seems ok
2) "cmake --build ." does nothing (no console message, no build) idem for "make -j"

In brief, I don't know how to build :-(

I'm on x86-64 with Debian testing:
gcc (Debian 7.2.0-12) 7.2.1 20171025
cmake version 3.9.3
ldd (Debian GLIBC 2.24-17) 2.24

**Comment by Axel-Naumann** [comment]
@serval2412 I'll have a look at the INSTALL file - you can try the procedure described here: https://root.cern.ch/building-root

Or you can just wait - our PR builder is currently looking at your latest commit and will report back soon...

**Comment by serval2412** [comment]
I know but it was just to avoid more noise from a simple mistake :-)

**Comment by serval2412** [comment]
@phsft-bot build because you're stuck.

**Comment by Axel-Naumann** [comment]
@serval2412 There's a Jenkins github integration bug; we expect to have it fixed within the next days.

**Comment by Axel-Naumann** [comment]
@phsft-bot build now that you're back on your feet!

**Comment by amadio** [comment]
@serval2412 Could you please address the formatting issues and merge conflicts? Thanks!

**Comment by serval2412** [comment]
Thank you Amadio for your feedback. I don't know what are the formatting pbs because I can't see travis results but I fixed conflicts.

**Comment by serval2412** [comment]
I finally understood how to fix format when re reading Travis logs.
I installed clang-format-3.9 and used this command:
./interpreter/llvm/src/tools/clang/tools/clang-format/git-clang-format --commit 10c61dc6964fe8f0fc33321e9338a3247e78be83  --binary clang-format-3.9

**Comment by serval2412** [comment]
Each time a format pb is fixed another format pb appears.
It seems clang-format should be called on the whole code but  some (all?) pull requests would be in conflict.
Should I keep on fixing format pb commit after commit hoping to reach the end within some steps only?

**Comment by serval2412** [comment]
After some time, I realized I could call several times clang-format locally, each time amending the last commit. Now clang-format doesn't complain anymore locally, hope Travis will be ok.

**Comment by Axel-Naumann** [comment]
@serval2412 thanks for trying so hard! It's very unfortunate that our format checker doesn't stop where a human would stop - e.g. re-formatting external packages makes really no sense :-( I will pick the reasonable subset of your commits and merge on Monday - thanks a lot for all your efforts!

**Comment by amadio** [comment]
@serval2412 Sorry for the trouble with clang-format! I usually keep a `git-reformat` in `$HOME/bin` with the following contents:
```bash
#!/bin/sh
git rebase -i --autosquash -x 'git clang-format master && git commit -a --amend --no-edit' master
```
Then, keeping clang-format happy is easy, just call `git reformat` before pushing the branch, or after each commit if you are touching the same lines in multiple commits (to avoid conflicts).

Thanks a lot for your effort!

**Comment by Axel-Naumann** [comment]
Thanks a lot, @serval2412 ! Your changes have been merged as PR #1330. We will reduce the strength of clang-format's recommendations, also as a consequence of all the work you invested here. Apologies this took so long!

**Pull request closed without merging**
