### PR TITLE
disable unicode (UTF-8) in the console for the time being, since it c…

### PR DESCRIPTION
**Pull request by bellenot**
…auses problems on Windows 10

### CODE REVIEW

**Comment by marsupial** [comment]
Perhaps using CP_UTF8 on Vista or above is a better solution?
https://stackoverflow.com/questions/10882277/properly-print-utf8-characters-in-windows-console
What is the output that is failing? Is it a properly encoded UTF-8 string?

I'm really only interested in Windows Terminal Output for testing which I won't have time for until next week (if at all).

**Comment by bellenot** [comment]
Thanks for the comment @marsupial ! The problem is appearing when deleting characters in the prompt (via backspace or del), the remaining of the line is filled with empty squares

**Comment by bellenot** [comment]
OK, I merge it for now, but this will have to be reviewed somehow

**Comment by marsupial** [comment]
Just thought on how you're describing the issue:
Could it be the problem is not actually output, but the handling/deletion of a multi-byte UTF-8 character removing only one byte on the stream leaving an invalid UTF-8 encoded buffer?

**Comment by bellenot** [comment]
Not really, I managed to fix the deletion problem, but then the problem goes somewhere else... So this will need a proper fix

**Pull request merged**
