### PR TITLE
[DF] Fix long int + Snapshot test on 32 bit platforms

### PR DESCRIPTION
**Pull request by eguiraud**
An alternative to #10302 .

Co-authored-by: @ellert

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Comment by ferdymercury** [comment]
@ellert do you think that ticket https://its.cern.ch/jira/browse/ROOT-8500 could be closed?
(Test failures on 32 bit ARM on Fedora 24-26)

**Comment by ferdymercury** [comment]
Thanks for the swift reply! Could you or @dpiparo close it then? (I don't have permission)

**Comment by ellert** [comment]
> I don't have permission

Nether do I. "You don't have permission to transition this issue."

**Comment by guitargeek** [comment]
Closed! Thanks for looking into this

**Pull request merged**
