### PR TITLE
Fix bug in TBits

### PR DESCRIPTION
**Pull request by will-cern**
Was initially miffed why the following example would give "7" instead of "2", but then I spotted the bug!

```
TBits b(50); b.SetBitNumber(1); b.SetBitNumber(7); b.CountBits(1)
```

### CODE REVIEW

**Comment by will-cern** [comment]
Incidentally, couldnt one avoid that loop over the bits at that bit of the code by just doing `count += nbit[fAllBits[startByte]>>ibit]` ?

**Comment by Axel-Naumann** [comment]
I would feel *way* more confident if we had any test for this :-/ Would you be kind enough (and I really mean it...) to provide one? It's fairly simple, just copy `core/base/test/TNamedTests.cxx` to `core/base/test/TBitsTests.cxx` and use the usual `EXPECT_EQ` to check for the output to be what you'd expect. *Then* we can simplify things! :-) Let us know, please!

**Comment by will-cern** [comment]
Hey! Remember at least one of us here doesn't get paid to make ROOT better ;-)

Never-the-less, on this occasion your wish is my command. Test added!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
I totally realize that, and I tried to ask as softly as possible, see my wording:

> Would you be kind enough (and I really mean it...) to provide one?

which I had hoped would get across that this is *totally* not your job :-/ Thank you so much for helping with this!

**Review by pcanal — APPROVED** [review]
Thank you very much!

**Comment by Axel-Naumann** [comment]
Thanks, @will-cern ! Last thing - could you drop the commit / revert pair in this branch so I can apply this with rebase? If you prefer I can do that for you :-)

(And never mind the Windows test failure - it's a bug in our infra that forces people to clone https://github.com/root-project/roottest or else that build fails...)

**Comment by will-cern** [comment]
Couldnt figure out why it wouldn't let me drop both commits just the revert one, so I've made a new history and force-pushed it. Now it should only feature the two commits that fix the bug and add the test

**Pull request merged**
