### PR TITLE
[TDF] Internal renaming and namespace refactoring

### PR DESCRIPTION
**Pull request by bluehood**
Second and last PR to resolve [ROOT-8780](https://sft.its.cern.ch/jira/browse/ROOT-8780) ("Less namespace verbosity and more uniform namings for TDataFrame").

### CODE REVIEW

**Comment by pcanal** [comment]
For the header files, I think technically we ought to have the header declaring classes inside a namespace (excluding/ignoring Experimental and possibly Details) in a subdirectory (see include/Math)

Since TDataFrame.hxx (the only user header file If I understood correctly) pull TDataFrame into the ROOT namespace I will keep it in [include]/ROOT but I would move all the other header in ROOT/TDF (and ROOT/Details) to keep things tidier.

**Comment by bluehood** [comment]
@pcanal the namespaces we use are `ROOT::{Detail,Experimental,Internal}::TDF`, so I do not totally understand your proposal. Also `$ROOTSYS/tree/treeplayer/inc/ROOT/TDF` is an awful long pathname, but if that's the rule I will make the necessary changes to comply of course.

**Comment by pcanal** [comment]
It would be ```$ROOTSYS//ROOT/TDF/DetailsHeader.hxx``` and would only be used by our own headers not by the user. (and yes the files in git would in  tree/treeplayer/inc/ROOT/TDF)

**Comment by dpiparo** [comment]
I am in favour of keeping things tidy. Still I find more informative/maintainable to have names for headers which refer to what they contains rather than a generic "Details".
If we want to change the policy related to paths in general for ROOT it is perhaps worth thinking this through  and maybe go for it in November?

**Comment by bluehood** [comment]
`clang-format` complains about the usual markdown tables longer than 120 lines (I have not changed them).

Test builds look good enough...mac did not finish due to a seemingly unrelated failure, while `root_dataframe_functiontraits` is fixed by a related PR in `roottest`.

**Pull request merged**
