### PR TITLE
Correcting incorrectly rounded coefficient in dilogarithm

### PR DESCRIPTION
**Pull request by Expander**
Dear ROOT developers,

I think I've found a little typo in the second coefficient of the Chebyshev expansion of the dilogarithm, implemented in `TMath::DiLog(Double_t x)`:

In the current implementation in ROOT (which dates back to an implementation of K. S. Kölbig from 19 Oct. 1966) the second coefficient reads

   0.40975987533077105

In [Yudell L. Luke: Mathematical functions and their approximations, Academic Press Inc., New York 1975, p.67, Table 3.12] this coefficient has been calculated with more digits to be:

   0.40975987533077105847

Rounding this number to the 17'th digit after the decimal point yields

   0.40975987533077106

which is different (in the last digit) from the coefficient found in `TMath::DiLog(Double_t x)`. I.e. the coefficient has been incorrectly rounded.

The incorrectly rounded coefficient is also present in CERNLIB's `RDILOG(X)` function [time stamp: dilog64.F,v 1.1.1.1 1996/04/01 15:02:05 mclareni Exp].

Note: I can reproduce the coefficients from [Yudell L. Luke] with the following Mathematica script:

~~~
(* interval mappings [a,b] <-> [-1,1] *)
a = -1;
b = 0;

y[x_] := (a + b - 2*x)/(a - b)

x[y_] := y * (b - a)/2 + (b + a)/2

(* function to approximate *)
f = -PolyLog[2, x[-#]]&

(* number of terms from Chebyshev series *)
n = 20

(* zeros of Chebyshev polynomials *)
xk = Pi (Range[n] - 1/2)/n

(* Chebyshev coefficients *)
c[j_] := 2/n Total[Cos[j xk] (f /@ Cos[xk])];

coeffs = Table[c[k], {k, 0, n-1}];
coeffs[[1]] *= 1/2;

(* precision *)
prec = 17

Print @ DecimalForm[#,{prec, prec}]& @ Re @ N[#, prec]& @ coeffs
~~~

Best regards
Alexander Voigt

P.S.: The implementation from K. S. Kölbig is an amazing piece of software! It is extremely fast due to the smart implementation, while providing full double precision.

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by amadio** [comment]
Nice catch. However, both `0.40975987533077105` and `0.40975987533077106`, when rounded to the nearest representable double, are the same number:
```
epsftws ~ $ root.exe -l
root [0] double x = 0.40975987533077105;
root [1] double y = 0.40975987533077106;
root [2] cout << ((x == y) ? "true" : "false") << '\n';
true
root [3] printf("%.20g\n", x);
0.40975987533077107283
root [4] printf("%.20g\n", y);
0.40975987533077107283
root [5] .q
```

**Comment by Expander** [comment]
Many thanks for checking!

Is your observation about the rounding to the nearest representable double platform-independent?

**Comment by amadio** [comment]
No, it's valid only for platforms using the IEEE Standard for Floating-Point Arithmetics. However, most platforms use it. Only small processors that do floating point in software don't follow IEEE.

**Comment by Expander** [comment]
I see. So, then it is actually questionable whether this PR is actually needed on IEEE-conforming platforms, right? On those platforms it would at most be a "visual" change, I guess.

**Comment by lmoneta** [comment]
Yes it is just a visual change, and it will not produce any difference in the obtained result.
I agree anyway to merge it in case somebody is going to take the code to use with higher precision.

**Comment by lmoneta** [comment]
One more thing before merging: 
can you maybe add in the commit message a note that this is just a visual change and it has no effect

**Comment by Expander** [comment]
@lmoneta I've changed the commit message accordingly (force-pushed to overwrite the previous commit with the old commit message).

Anyway, thank you both for your feedback!

**Comment by lmoneta** [comment]
Thank you for the PR. It is now merged in ROOT master

**Pull request merged**
