### PR TITLE
[clang] Revert patch to `Sema::computeDeclContext`

### PR DESCRIPTION
**Pull request by hahnjo**
This line was introduced by commit 0f1f12931f in 2016, in what looks like an unrelated change. All ROOT tests pass after removing it.

@Axel-Naumann unless you happen to remember why this was introduced, I will synchronize this to the monorepo and we get rid of another patch...

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On -Druntime_cxxmodules=OFF

**Comment by hahnjo** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by hahnjo** [comment]
I think this looks mostly good, the failures on `ROOT-debian10-i386` are timeouts (even though it's suspicious that the same tests timed out as the last time)

**Review by vgvassilev — APPROVED** [review]
Ok, if tests are ok, let’s move forward!

**Pull request merged**
