### PR TITLE
[math] Disable `QuarticPolynomial.FindRoots_4RealDegRootsR0` test

### PR DESCRIPTION
**Pull request by guitargeek**
It fails on the `macOS ARM` platforms, until this is fixed, the test should be disabled.

Also, some general code improvements in the test:

  * use complex literals for brevity

  * don't use test fixture (fixtures make sense if you need to re-use data, but here the members were reset in every test anyway)

  * disable verbose output by default

### CODE REVIEW

**Review by hahnjo — CHANGES_REQUESTED** [review]
Please see https://github.com/root-project/root/pull/14291 for what I think is a proper fix. Also for the feature, please consider not changing the entire file and disabling one test, this makes it impossible to just revert to re-enable the test...

**Comment by guitargeek** [comment]
Ok fair enough! For removing the `DISABLED` I would have not used `git revert` though, it's a one-line change that could have been done just like that. But I see the point of mixing formatting and functional changes.

**Comment by hahnjo** [comment]
After merging https://github.com/root-project/root/pull/14291, I guess you want to remove the second commit and only keep the code improvements?

**Comment by guitargeek** [comment]
See #14291 for the proper fix.

**Pull request closed without merging**
