### PR TITLE
Add support for arrow 0.15.0+

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Axel-Naumann as discussed privately. I think I actually can easily support new and old versions of arrow, so I would suggest we do to simplify porting also in the ALICE framework.

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@ktf could you fork roottest? (Sorry, it's a long-standing bug in our infra...)

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-ubuntu2004

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default

**Comment by ktf** [comment]
I just forked it.

**Comment by ktf** [comment]
I am not sure I am smart enough to find the actual error. Could someone point me to it?

**Comment by eguiraud** [comment]
@ktf it does not look like it's the PR's fault:

```
10:21:39  CMake Error at cmake/modules/SearchInstalledSoftware.cmake:1617 (target_include_directories):
10:21:39    Cannot specify include directories for imported target "gtest".
10:21:39  Call Stack (most recent call first):
10:21:39    CMakeLists.txt:183 (include)
10:21:39  
10:21:39  
10:21:39  CMake Error at cmake/modules/SearchInstalledSoftware.cmake:1618 (target_include_directories):
10:21:39    Cannot specify include directories for imported target "gmock".
10:21:39  Call Stack (most recent call first):
10:21:39    CMakeLists.txt:183 (include)
```

Let's try again, might have been a glitch

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default

**Comment by ktf** [comment]
Same glitch?

**Comment by eguiraud** [comment]
Yes, sorry about that. Your changes look ok at a quick glance (and anyway, the CI errors are definitely unrelated). We'll try to resolve this asap.

**Comment by eguiraud** [comment]
#5396 should fix the problem with the CI, wip

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default

**Pull request merged**
