### PR TITLE
Coverity fixes 82576, 82575, 68746, 68745, 68856, 61279, 61577

### PR DESCRIPTION
**Pull request by vgvassilev**
These are the missing items from #524.

### CODE REVIEW

**Comment by dpiparo** [comment]
@phsft-bot build please.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
dbdff174711c9bf63cc71735e34be374e7c1ec0c causes crash in stressHistogram.  Do we understand why it was not seen/caught by the jenkins builds?

**Comment by vgvassilev** [comment]
Hmm... please feel free to revert this commit. Maybe @harveyj1953 knows what's going on there.

**Comment by pcanal** [comment]
@vgvassilev I am looking into the commit itself (which by the way had already been commit and reverted once).  *However* might questions was really about jenkins.  I.e. this failure is seen in the incremental builds (https://phsft-jenkins.cern.ch/job/root-incremental-master-noimt/BUILDTYPE=Debug,COMPILER=gcc49,LABEL=centos7/466/testReport/projectroot/test/test_stresshistogram/)  ... and so my questions (to try to improve the process/infrastructure) is why it was not seen in the build made from the PR (i.e. is stressHistogram not run? did the build not finish? or something else?).  thanks.

**Comment by pcanal** [comment]
@vgvassilev Do *you* recall whether the build had (seemed to) succeeded?

@martinmine Is it expected that a closed PR has not trace left of the link to the builds?

**Pull request merged**
