### PR TITLE
Miscellaneous fixes for the build system and some tests

### PR DESCRIPTION
**Pull request by amadio**
@vgvassilev Please review the changes to disable optional LLVM components.
@Axel-Naumann Please review the commit to fix `TClingTests` when binaries are built as PIE.
@etejedor @oshadura Please review the creation of a relative symlink for installing PyROOT and if it works for you too.

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
LGTM for core/metacling/test/TClingTests.cxx - thanks!

**Comment by amadio** [comment]
Travis failure (clang-tidy, clang-modernize) happens in RooFit, so not related to my changes.

**Review by oshadura — APPROVED** [review]
LGTM Thanks a lot for an elegant solution with symlinks and catching mini bugs in the build system!

**Review by etejedor — APPROVED** [review]
Looks good, thanks @amadio !

**Pull request merged**
