### PR TITLE
Adjust a modulemap file to be able to treat separate .c files

### PR DESCRIPTION
**Pull request by oshadura**
Patch by Vassil Vassilev.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On

**Comment by oshadura** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On

**Pull request merged**
