### PR TITLE
TRatioPlot: use Left/Right pad margins from gStyle

### LINKED ISSUE #15883: Initialize TRatioPlot margins from Pad margins set in the current style
### Explain what you would like to see improved and how.

At the moment the Pad margins of a TRatioPlot are always initialised with fixed values
https://github.com/root-project/root/blob/0a395208b9cb64188b11fd48eaa81128dd9c0acf/graf2d/gpad/inc/TRatioPlot.h#L128-L136
resulting in the plots having different margins than other plots and therefore also a different aspect ratio, making quick by-eye comparisons harder. (When using a custom style that changes the Pad margins)

While I understand that the Top and Bottom margins require a bit more tuning for this kind of plot, at least the Left and Right margin could be set from the PadLeftMargin and PadRightMargin values in gStyle.

This would result in TRatioPlots having the same horizontal width as other plots (histograms, graphs, etc.) by default.

### ROOT version

any

### Installation method

any

### Operating system

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Zehvogel**
# This Pull request:

## Changes or fixes:

[before.pdf](https://github.com/user-attachments/files/15914243/before.pdf)
[after.pdf](https://github.com/user-attachments/files/15914241/after.pdf)

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #15883 

@dpiparo @couet

### CODE REVIEW

**Comment by couet** [comment]
Yes, good point. @Zehvogel can you try to do the same for those and see if that's works ?

**Comment by couet** [comment]
Okay then, a newer TStyle parameter would be required. Let's keep it that way. If the defaults are reasonable, then it is fine. Anyway, that can be changed when needed by the class setters.

**Comment by linev** [comment]
I would not use `gStyle` as initializer in header files.
In some special cases header files may be accessed without loading appropriate library - and then gStyle can be also not initialized. 
I would prefer to move such members initialization into `TRatioPlot` constructor.

**Comment by Zehvogel** [comment]
I can offer you this @linev

**Review by linev — APPROVED** [review]
It is much better!

**Comment by Zehvogel** [comment]
Sorry for commenting on an already merged PR but there was a part left open here:

> Thanks! Maybe a naive question: why the top and bottom margins are still hard coded?

Which back then I was unable to solve:

> When I naively set `SetLowBottomMargin(gStyle->GetPadBottomMargin())` and `SetUpTopMargin(gStyle->GetPadTopMargin())` they end up being different than for a simple histogram, i.e. axis labels that should fit disappear.

Because I did not understand what the margins actually mean. I think I have understood it now.
The margins are relative to the pad, so if it is split in two like here, the margins of the subpads need to be scaled up by the inverse relative subpad size.
I.e. it should be possible to have the correct overall bottom margin of the whole ratio plot by initialising
```
fLowBottomMargin(gStyle->GetPadBottomMargin * (1. / fSplitFraction))
```
and similarly for `fUpTopMargin`.

I don't have time to implement and test this at the moment, but maybe someone wants to give it a go?

**Pull request merged**
