### PR TITLE
[RF] Consistently use ROOT::Math::KahanSum everywhere in RooNLLVar

### PR DESCRIPTION
**Pull request by guitargeek**
This PR is addressing one of the `TODO`s left by @hageboeck in the RooFit code:

https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooNLLVar.cxx#L326

I hope this goes in the good direction. I still have to see how I can cover all the changes with tests, so this is a draft PR for now.

The most controversial part is probably the `_offset` subtraction: https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooNLLVar.cxx#L454.

It originally looked like this:

```C++
Double_t y = -_offset - (carry + _offsetCarry);
Double_t t = result + y;
carry = (t - result) - y;
result = t;
```

I'm not sure if that works. By definition, `_offset` is in the same order of magnitude as `result`, so the `carry + _offsetCarry` is lost when adding it with `_offset`, no? I think to subtract KahanSums of the same order of magnitude, one should better add the sums and carries individually and then make a dummy addition such that the carry can "spill over" into the sum if it got large enough after addition:

```C++
KahanSum<T, N>& operator-=(KahanSum<T, N> const& other) {
    fSum[0]   -= other.Sum();
    fCarry[0] -= other.Carry();
    // add zero such that if the summed carry is large enough to be partly represented in the sum, it will happen
    Add(T{});
    return *this;
}
```

@lmoneta

### CODE REVIEW

**Comment by bellenot** [comment]
@guitargeek please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks

**Comment by hageboeck** [comment]
Since this is a very central part for fitting, you should see lots of test failures if you get it wrong.
Not, though, if you get it only slightly wrong.

Good luck with your new project, there are lots of things to do! 👍

**Review by lmoneta — COMMENTED** [review]
Looks good to me, very nice improvements !
What you are seeing about the subtraction of the offset and the carry correction seems correct to me. It would be good to have a test showing also the difference with compare to what we have it before. The difference is probably small and it will be difficult to see in the current tests, but it is possible that some fits now can con converge better due to an improved precision.

**Comment by guitargeek** [comment]
Hi, thanks for your comments! I tested the code now with a modified `rooArgusModel` example from https://root.cern/manual/roofit/.

What I changed:
* Number of generated toy events increased from 2000 to 200000
* Changed fitting command to `model.fitTo(*data, RooFit::Offset(true), RooFit::Extended(false));`. The offset has to be enabled to cover the changes suggested in this PR. The extended term has to be disabled for the same reason that the offset subtraction has been changed in this PR: the extra term is of the similar order of magnitude as the Kahan sum over events but is summed with the Kahan algorithm. Therefore, the carry is lost and becomes zero. But if the carry is zero, we can't see what's different in the offset subtraction with this PR.

In the first three iterations, I printed the result and carry before and after offset subtraction (without this PR):
```
Without PR

1. Step:
before offset subtraction : -500453.65447450732 carry -1.2374989921681845e-11 
ater offset subtraction   :                   0 carry                       0

2. Step:
before offset subtraction : -500454.29148114444  carry 1.4085621558024286e-11
ater offset subtraction   : -0.63700663711642846 carry                      0

3. Step:
before offset subtraction : -500452.91000359994 carry -1.0619505275144547e-11
ater offset subtraction   : 0.74447090737521648 carry                       0
```
As expected, the carry becomes zero.

Now with the PR I print 3 lines: 
1) before offset subtraction
2) after subtracting the offset sum from the result and the offset carry from the result carry
3) after the dummy addition of `0.0`

```
After PR

1. Step:
before offset subtraction : -500453.65447450732 carry -1.2374989921681845e-11 
ater offset subtraction   :                   0 carry                       0
after +-= 0.0              :                   0 carry                       0

2. Step:
before offset subtraction : -500454.29148114444  carry 1.4085621558024286e-11
ater offset subtraction   : -0.63700663711642846 carry 2.6460611479706131e-11
after += 0.0              : -0.63700663714288908 carry                      0

3. Step:
before offset subtraction : -500452.91000359994 carry -1.0619505275144547e-11
ater offset subtraction   : 0.74447090737521648 carry  1.7554846465372975e-12
after += 0.0              : 0.744470907373461   carry                       0
```

The result in the second lines is identical to the final result without this PR, indicating that the carries of offset and result were indeed lost before the PR. After the dummy addition of zero, the result changes visibly. This is expected, because after the offset subtraction the result shrinks by orders of magnitudes and can absorb (parts of) the carry. What is surprising is that the carry is zero afterwards. I would have expected that a carry of around 1e-17 remains (i.e. that it shrinks in order of magnitude like the result after offset subtraction but it doesn't become zero)

So except for the carry unexpectedly zero in the end, this PR does what it should.

**Comment by guitargeek** [comment]
I added another commit because there was another `TODO` that I missed in the same file. The "batching up" of the squared weight sums was implemented for the normalization term just like in `computeBatched`: https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooNLLVar.cxx#L529

**Comment by guitargeek** [comment]
> @guitargeek please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks

Hi @bellenot, I have now forked [roottest](https://github.com/root-project/roottest), but the Windows build is still failing. Should I do something else besides just forking? Thanks for your help!

**Comment by bellenot** [comment]
> > @guitargeek please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks
> 
> Hi @bellenot, I have now forked [roottest](https://github.com/root-project/roottest), but the Windows build is still failing. Should I do something else besides just forking? Thanks for your help!

Hi @guitargeek No, now the failure is a real one, see the log:
```
17:41:07    CMake Error at C:/build/workspace/root-pullrequests-build/build/TBB-prefix/src/TBB-stamp/TBB-configure-Release.cmake:49 (message):
17:41:07      Command failed: 1
17:41:07    
17:41:07       'devenv.exe' '/useenv' '/upgrade' 'build/vs2013/makefile.sln'
17:41:07    
17:41:07      See also
17:41:07    
17:41:07        C:/build/workspace/root-pullrequests-build/build/TBB-prefix/src/TBB-stamp/TBB-configure-*.log
17:41:07    
```

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by lmoneta — APPROVED** [review]
Looks good ! I think we can merge this one. .
Thank you !

**Pull request merged**
