### PR TITLE
Fixes regression and corresponding tests

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
Could you address the travis complaints?

**Comment by xvallspl** [comment]
@vgvassilev I can adress the space before the comment text thing, but I don't agree with the other suggested changes (one liners or line splitters).

I'm building again on that mac to see if it fails again.

**Comment by xvallspl** [comment]
@phsft-bot  build on mac1012/native

**Comment by xvallspl** [comment]
@phsft-bot build!

**Pull request merged**
