### PR TITLE
[DF] Extend parsing capabilities of CSV data source

### PR DESCRIPTION
**Pull request by jblomer**
# This Pull request:

Adds more advanced options to parse CSV files:
  
  - Left/right trimming
  - Skipping of a given number of header/footer lines
  - Comment character to skip lines / line remainders
  - Impose column names

It brings the CSV datasource closer to the Pandas CSV parsing capabilities and should avoid in many cases the need for users to implement custom text file parsing code.

## Checklist:

- [X] tested changes locally
- [ ] add tutorial
- [x] add pythonization for `FromCSV` that uses named arguments for all the new options in `RCsvDS::ROptions`
- [ ] update release notes
- [ ] Update RCsvDS class documentation

### CODE REVIEW

**Comment by dpiparo** [comment]
This PR looks great. @jblomer would you prefer I wait for all the items in the checklist to be addressed to review it or should I proceed?

**Comment by jblomer** [comment]
Thank you, @dpiparo. Let me address the PyROOT issue first, which I haven't understood yet.

**Comment by jblomer** [comment]
> One suggestion/alternative that might be easier for outsourcing long-term maintenance is to use a header-only C++ csv parsing library, such as e.g.: https://github.com/ferdymercury/text-csv

That may be a good idea! I'll have a look for options. I think that should be a follow-up PR though.

**Review by dpiparo — APPROVED** [review]
Thanks for completing this PR. I agree that the proposed CSV parsing lib is quite good and should be considered in a follow-up PR, only once this is successfully integrated.

**Pull request merged**
