### PR TITLE
Fix DNN in tutorial examples

### PR DESCRIPTION
**Pull request by ashlaban**
Removes the DNN option with Architecture=Standard from ordinary
and multiclass settings.

Smaller fixups for output and homogenisation of DNN options.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by dpiparo** [comment]
Hi @ashlaban,
since this change is related to DNN, I allow myself to point you to this failure: http://cdash.cern.ch/testDetails.php?test=25539356&build=359962
It's a segfault linked to DNNs. Perhaps it's worth having a look before putting on top something else?

**Comment by ashlaban** [comment]
Hi @dpiparo, Thanks for pointing me to the failure. This PR removes the DNN implementation that causes this issue from the publicly visible examples. This since we are aware of problems in this implementation. There should be a TMVA Dev meeting tomorrow where I will bring this conversation up .

You can consider me as looking into the issue.

**Comment by vgvassilev** [comment]
Shall we merge this?

**Comment by ashlaban** [comment]
Please rebuild and merge if everything looks fine

**Pull request merged**
