### PR TITLE
Cling lambda support

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On -Dvc=OFF -Dimt=ON -Dccache=ON -DCMAKE_GENERATOR="Unix Makefiles"

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On -Dvc=OFF -Dimt=ON -Dccache=ON

**Comment by vgvassilev** [comment]
@marsupial, I do not understand that fix but I am sure @Axel-Naumann would review it. This is at least to make sure that works for ROOT, too.

It seems, this is fixing the symptom. I think the real issue is that we are mishandling the way we extract decls at first place. See https://github.com/vgvassilev/cling/issues/124

**Comment by marsupial** [comment]
Well https://github.com/root-project/cling/pull/148/commits/9313dbca01b00f1399b14b256925b3f99f0be97b fixes a real bug. Not everything has a destructor (or even needs to run it if it does).

https://github.com/root-project/cling/pull/148/commits/6b550ad6d0b762adcdb07abbff27ddd5691ed7c1 just warns the user that capture by copy doesn't work.

I understand there may be other issues with lambda's but generally capture by copy in general should not be supported at the global scope.
1. Because it would mean the entire program/Interpreter state would need to be held by the lambda.
2. It wouldn't be standard compliant:
```
#include <stdio.h>
int Var = 42;

auto LC = [=] { return Var; };

int main(int argc, const char** argv) {
	++Var;
	printf("%d\n", LC());
	return 0;
}
  
```
=> 43

**Comment by vgvassilev** [comment]
It seems that gcc is fairly happy with it: https://godbolt.org/g/cM5Mg1

**Comment by marsupial** [comment]
Don't understand, 'happy with' what?
I see the issue is that interpreter the behavior is a bit different than someone might reasonably expect and showing a warning is probably worthwhile.

That is the current behavior is dependent on all variables in the Interpreter being globals, which is an implementation detail not known to all users.

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On -Dvc=OFF -Dimt=ON -Dccache=ON -DCMAKE_GENERATOR="Unix Makefiles"

**Comment by Axel-Naumann** [comment]
In the current C++ working paper:
[expr.prim.lambda]/10: "A lambda-expression whose smallest enclosing scope is a block scope (3.3.3) is a local lambda expression; any other lambda-expression shall not have a capture-default or simple-capture in its lambda-introducer."

As we decl-extract lambdas we should forbid capture-defaults. But we decl-extract after Sema. So indeed - a post-processing step makes sense, but it should complain about *any* capture default.

[expr.prim.lambda]/11: "An entity that is designated by a simple-capture...and shall be *this ... or a variable with automatic storage duration": this should be noticeable by Sema, except for transactions that declare both the variable and the capture in the same input. So here, too, we'll need a postprocessing step - but it's not as urgent.

@marsupial - do you think you could widen the first check (i.e. forbid *any* capture default)?

And yes, we need https://github.com/root-project/cling/commit/9313dbca01b00f1399b14b256925b3f99f0be97b

**Comment by marsupial** [comment]
I'm against forbidding except if **-Wpedantic** is used just so things can be copy/pasted easier.
It seems the warning could be expanded if any default is given, but what is gained from that?

I.e. `auto LC = [&] { /*blah blah*/ };`
behaves exactly as one would intend/expect, and the fact it is being put into a global scope from a local one seems like an impl. detail that doesn't have to annoy users.

I guess at one point DeclExtraction may go away and if ever evaluated in the global scope the example would fail, but is it necessary to punish now for something that may happen in the future?

**Comment by Axel-Naumann** [comment]
That's an excellent point. And your check for copy makes perfect sense to me. Thanks! Merged.

**Pull request merged**
