### PR TITLE
Use proper printing interface in RDataFrame

### PR DESCRIPTION
**Pull request by yamaguchi1024**
gInterpreter->Evaluate is a proper interface for printing purposes.

### CODE REVIEW

**Comment by bluehood** [comment]
hi @yamaguchi1024 , thank you for the PR!
I'm out of the loop unfortunately, can you elaborate on what was wrong with the previous implementation and how the changes fix it?

**Comment by yamaguchi1024** [comment]
Hi @bluehood ,
In #2201 and in #2591, we discussed what is the appropriate interface for asking Interpreter  printing. Possible options were "Use printValue and declare RuntimePrintValue.h at Cling startup time" or to "Use gInterpreter->Evaluate", and people prefered latter.

This Evaluate interface is a bit tedious than calling printValue, but it saves startup time as we don't have to declare one more header.

So when you want to print something from Interpreter, it'll be nice if you could use this interface :)
```
       auto value = gInterpreter->CreateTemporary();
￼       if (gInterpreter->Evaluate(<something you want to print>, *value) == 1 /*success*/)
￼         str = value->ToTypeAndValueString().second;
￼       delete value;
```

**Comment by bluehood** [comment]
@yamaguchi1024 if this is a pattern that you would like to see applied in several places couldn't we have a helper function that makes it a one-liner again?

**Comment by yamaguchi1024** [comment]
Yeah, it'll be nice to have something like gInterpreter->Print(const char*) which already returns a string. It'll be a wrapper function of Evaluate and ToTypeAndValueString in TCling.

What do you think @Axel-Naumann and @vgvassilev ?

**Comment by dpiparo** [comment]
@yamaguchi1024 how much does this improve the startup time and memory saving?
As @bluehood says, I think that something more "contained" than the few lines could be the right solution.

**Comment by yamaguchi1024** [comment]
Hi Danilo,
I'm also for the "one line solution". As Axel said, we'll make `cling::printValue()` interface available.

**Comment by dpiparo** [comment]
@yamaguchi1024 can we close this given https://github.com/root-project/root/pull/2664 ?

**Comment by yamaguchi1024** [comment]
#2698 is overtaking this

**Pull request closed without merging**
