### PR TITLE
[TDF] Extend gtest for friends in MT

### PR DESCRIPTION
**Pull request by etejedor**
Introduce MT testing for the TDataFrame with friends scenario.

### CODE REVIEW

**Comment by bluehood** [comment]
Thank you a lot!! Is it worth to also test the friends-of-friends case?

**Comment by etejedor** [comment]
I'm afraid friends of friends are not supported in TTreeProcessorMT itself. I was not aware of this use case, this means that when I read a tree I can also see the branches of the friends of the friends (of the friends of the friends etc.) of that tree?

**Comment by pcanal** [comment]
> I'm afraid friends of friends are not supported in TTreeProcessorMT itself. I was not aware of this use case, this means that when I read a tree I can also see the branches of the friends of the friends (of the friends of the friends etc.) of that tree?

Yes.

**Comment by dpiparo** [comment]
I propose to document this feature clearly unless it can be easily implemented. Technically it's a bug fix, I do not see issues in dealing with it for 6.12 too.

**Pull request merged**
