### PR TITLE
Add suspend autoload raii

### PR DESCRIPTION
**Pull request by vgvassilev**
Note the separate commits are intended to simplify bisecting if necessary as this is very fragile logic in ROOT.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
> [tcling] Use the autoload raii autoload object in RegisterModule. NFC 

Could you extend the commit log to explain why the change is NFC (despite some of the call being 'conditional' in the old code and not in the new code).

**Comment by vgvassilev** [comment]
Sure, done.

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
the travis failure are pre-existing infrastructure issues;
```
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
+RESULT_OUTPUT='/home/travis/build/root-project/root/core/base/src/TApplication.cxx:47:10: error: '\''TApplicationCommandLineOptionsHelp.h'\'' file not found [clang-diagnostic-error]
#include "TApplicationCommandLineOptionsHelp.h"
         ^
/home/travis/build/root-project/root/core/base/src/TROOT.cxx:73:10: error: '\''RGitCommit.h'\'' file not found [clang-diagnostic-error]
#include "RGitCommit.h"
         ^
/home/travis/build/root-project/root/core/dictgen/src/rootcling_impl.cxx:18:10: error: '\''rootclingCommandLineOptionsHelp.h'\'' file not found [clang-diagnostic-error]
#include "rootclingCommandLineOptionsHelp.h"
         ^
/home/travis/build/root-project/root/interpreter/llvm/src/tools/clang/include/clang/Basic/AttrSubjectMatchRules.h:22:10: error: '\''clang/Basic/AttrSubMatchRulesList.inc'\'' file not found [clang-diagnostic-error]
#include "clang/Basic/AttrSubMatchRulesList.inc"
         ^'
```

**Comment by pcanal** [comment]
Most of the clang-format recommendation should be followed (only visible mistake from clang-format part is the alignment of the method name in the header file).

**Comment by pcanal** [comment]
Looks good. Thanks!

**Pull request merged**
