### PR TITLE
Reduce calls to enable autoloading, reduce cxxmodules work at shutdown

### PR DESCRIPTION
**Pull request by vgvassilev**
This PR has misc improvements and depends on PR #3769.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
the travis failure are pre-existing infrastructure issues;
```
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
+RESULT_OUTPUT='/home/travis/build/root-project/root/core/base/src/TApplication.cxx:47:10: error: '\''TApplicationCommandLineOptionsHelp.h'\'' file not found [clang-diagnostic-error]
#include "TApplicationCommandLineOptionsHelp.h"
         ^
/home/travis/build/root-project/root/core/base/src/TROOT.cxx:73:10: error: '\''RGitCommit.h'\'' file not found [clang-diagnostic-error]
#include "RGitCommit.h"
         ^
/home/travis/build/root-project/root/core/dictgen/src/rootcling_impl.cxx:18:10: error: '\''rootclingCommandLineOptionsHelp.h'\'' file not found [clang-diagnostic-error]
#include "rootclingCommandLineOptionsHelp.h"
         ^
/home/travis/build/root-project/root/interpreter/llvm/src/tools/clang/include/clang/Basic/AttrSubjectMatchRules.h:22:10: error: '\''clang/Basic/AttrSubMatchRulesList.inc'\'' file not found [clang-diagnostic-error]
#include "clang/Basic/AttrSubMatchRulesList.inc"
         ^'
```

**Comment by pcanal** [comment]
Most of the clang-format recommendation should be followed (only visible mistake from clang-format part is the alignment of the method name in the header file).

**Pull request merged**
