### PR TITLE
[TDF] Fix ROOT-8979: write c-style arrays with Snapshot

### PR DESCRIPTION
**Pull request by bluehood**
The fix relies on:
- users only ever using `array_view<T>` in `Define`, `Filter` and TDF
  actions to read c-style arrays from TTrees, and not for std::vector,
  for example
- the fact that for TTree branches that contain c-style arrays one can
  use the title of the input branch as the title of the output branch,
  as is

The fix requires to `const_cast` away the constess of the pointer
returned by `array_view::data` to pass it to `TTree::Branch` as `void *`.

Because of this last issue and because of the first point above,
in the future it might be better to not use `array_view` but our
own custom type `TDFArray` to let users signal c-style arrays.
Or maybe `TTree::Branch` could be made to accept a `const void*`, I'm not sure about that.

### CODE REVIEW

**Comment by dpiparo** [comment]
This is a breakthrough: thanks for insisting to the end.
The code looks good to me.
Assumption 1) can be clarified in the doc. Assumption 2) is deeply rooted inside the very concept of tree. As for the const cast, it's less than optimal but I agree this can wait for 6.14 given also that at the moment we not only do not write out C arrays but we do that in a bogus fashion.

I can merge this PR as soon as the tests and the coding conventions checks are green. The present 2 test failures can be fixed easily and are not due to this change.

**Comment by bluehood** [comment]
The more I think about it the more I am convinced that giving this special meaning to array_view will bring trouble in the future.

Users might define a column of type vector and then try to read it with an array_view with bad conconsequences.

I would prefer breaking the interface now than having to do it later to solve weird bugs. I propose we adopt `TArrayBranch´ as a generic c-style-array-in-a-ttree-branch type. It would live in the same namespace as TDF and would serve no other purpose than letting users indicate that the branch they are reading is a fixed or variable size c-style array.

**Comment by amadio** [comment]
What's the problem with `std::vector<T>` or a reference to fixed-size array?
```
template<unsigned int N>
void func(const char(&str)[N])
{
    // Whatever...
}

int main()
{
    func("test"); // Works, N is 5
}
```

**Comment by bluehood** [comment]
We need a type that means "this is a c-style-array stored in a TTree branch", because that case is special: we need to use `TTreeReaderArray` for reading and we need to take special care to specify the branch title correctly when writing.

`std::vector` is a no go because it is a type of its own that is perfectly good to read and write.
Template functions like `func` cannot be passed to `Filter` or `Define` because the nodes would not be able to detect the type of the inputs and outputs from the function signature.

It would be nice to be able to write
```
tdf.Define("front", [](int arr[]) { return arr[0]; }, {"arr"});
```
but that's not valid syntax.

I think it's reasonable to have a specific type that has the meaning specified above.

**Comment by pcanal** [comment]
Naive question :)
Could we use:
```
template<typename T, unsigned int N>
... Define(T(&arr)[N]) { return DefinedArray<T>(&arr[0],N); }
```?

**Comment by bluehood** [comment]
Sorry I don't understand the idea :sweat_smile:

When users call `Filter` or `Define` we need to deduce right there the return type and the argument types of the callable that has been passed, because we need to instantiate the corresponding `TTreeReaderValue`s or `TTreeReaderArray`s or `T*`s.

**Comment by bluehood** [comment]
@Axel-Naumann just suggested another strong argument for swapping `array_view` with our own type: the former is forcing us to check that what we are reading is contiguous in memory, the latter might be able to not care, and just transparently yield whatever `TTreeReaderArray` returns.

**Comment by bluehood** [comment]
I would merge this and keep working on Snapshot with other PRs:

- better check for correctness of multi-thread snapshot of c-style array
- switch usage of `array_view` to a custom type

**Comment by dpiparo** [comment]
I agree.

**Pull request merged**
