### PR TITLE
Revert assertion check in Declbase.cpp

### PR DESCRIPTION
**Pull request by tapaswenipathak**
# This Pull request:

Revert https://github.com/vgvassilev/clang/commit/1c6cc386f62f9a5a87cf268b4d35199721aec0f4.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
Can you expand on how the reversion is helping (and/or the original is no longer needed)?

**Comment by vgvassilev** [comment]
In https://github.com/llvm/llvm-project/commit/0cb7e7ca0c864e052bf49978f3bcd667c9e16930 we have reworked the lookup addition and deletion to be protected operations. We wanted to check this patch if was necessary, however, looking at it we thought that it was maybe not needed even for the current llvm we have as the infrastructure wrt modules/pch has changed significantly since the development of this patch.

If we have less patches in our clang fork, it will likely mean faster/smoother llvm upgrades.

**Review by vgvassilev — APPROVED** [review]
According to our bots, this change is not needed anymore. It was introduced in 613765489a3b1c607ed8b39a14fdc6e5041659c0, could you do `git revert 613765489a3b1c607ed8b39a14fdc6e5041659c0` to track better in the git history?

**Pull request merged**
