### PR TITLE
[tmva][sofie] Fix error message in Tanh operator

### PR DESCRIPTION
**Pull request by lmoneta**

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default, ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default, ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -Dtmva-sofie=On

**Review by sanjibansg — COMMENTED** [review]
Thanks for this correction.
Now that I saw this, I noticed this in other files as well
https://github.com/lmoneta/root/blob/tmva_sofie_fixes/tmva/sofie/inc/TMVA/ROperator_Sigmoid.hxx#L50

**Comment by lmoneta** [comment]
Thank you Sanjiban, I will fix the other files as well!

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default, ROOT-ubuntu18.04/nortcxxmod

**Pull request merged**
