### PR TITLE
[RDF] Add Python version of Dimuon tutorial

### PR DESCRIPTION
**Pull request by stwunsch**
Add python version of RDF tutorial producing dimuon spectrum from CMS Open Data.

This PR depends on #3571.

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot

**Comment by stwunsch** [comment]
@phsft-bot build on windows10/default

**Comment by stwunsch** [comment]
Let's rebuild tomorrow, #3571 built fine, but here windows fails to find `M_PI`.

**Comment by stwunsch** [comment]
@phsft-bot build on windows10/default

**Comment by stwunsch** [comment]
Following https://godbolt.org/z/Ay4mOJ, `M_PI` should be there now.

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
@JavierCVilla look at this :) this is great for PyRDF!

**Comment by JavierCVilla** [comment]
@dpiparo We can add it as a demo to PyRDF once merged.

**Comment by JavierCVilla** [comment]
Btw, this PR should supersede #3416 , so I guess it can be closed.

**Comment by stwunsch** [comment]
@phsft-bot build on windows10/default

**Comment by stwunsch** [comment]
Ok, I've no idea why it does not work in the PR build. It should be fine following the msvc docs and godbolt (?)

**Comment by stwunsch** [comment]
@phsft build on ROOT-performance-centos7-multicore/default, ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default

**Comment by stwunsch** [comment]
@phsft-bot build on ROOT-performance-centos7-multicore/default, ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default

**Comment by stwunsch** [comment]
@phsft-bot build on windows10/default

**Comment by stwunsch** [comment]
@phsft-bot build

**Pull request merged**
