### PR TITLE
[RF] RooFitHS3 performance improvements

### PR DESCRIPTION
**Pull request by cburgard**
# This Pull request:

This PR refactors the iterator implementation for the JSON interface to avoid performance issues with reading workspaces from JSON.

## Changes or fixes:

Reading JSON files is much faster now.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by cburgard** [comment]
not sure why clang-format fails, but from my side the MR is good to go

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
LGTM, thanks a lot for implementing this speedup!

**Pull request merged**
