### PR TITLE
[RF] Less Windows-specific RooFit code 

### PR DESCRIPTION
**Pull request by guitargeek**
In particular, don't exclude tests that are now running fine on Windows.

### CODE REVIEW

**Comment by bellenot** [comment]
FYI, the windows build failed because the node was out of disk space. This is now fixed

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
Fixed conflicts

**Review by bellenot — APPROVED** [review]
Fine with me, if the builds are green

**Pull request merged**
