### PR TITLE
[Experimental PyROOT] Fix pretty-printing for cxx modules

### PR DESCRIPTION
**Pull request by stwunsch**

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by stwunsch** [comment]
@vgvassilev Good to merge?

**Comment by stwunsch** [comment]
@vgvassilev feel free to hit merge if you don't see any problems.

**Comment by vgvassilev** [comment]
LGTM!

**Pull request merged**
