### PR TITLE
[TDF] Misc fixes

### PR DESCRIPTION
**Pull request by bluehood**
* fix issue in interaction of named filters and range logic (fixes test_report on noimt builds)
* throw instead of crashing when wrong branch names are used for jitted actions
* only call `ProcessLine` if there is something to jit
* use `ULong64_t` instead of `Long64_t` for number of events to generate with TDF

### CODE REVIEW

**Comment by bluehood** [comment]
@admins This PR should be built with imt=OFF to check that test_reports goes back to green.

**Comment by vgvassilev** [comment]
@phsft-bot build with  flags -Dvc=OFF -Dimt=OFF -Dccache=ON

**Comment by vgvassilev** [comment]
@phsft-bot build on gcc49/centos7, native/mac1012, gcc49/slc6, gcc62/slc6, native/ubuntu14 with flags -Dvc=OFF -Dimt=OFF -Dccache=ON

**Comment by vgvassilev** [comment]
@phsft-bot build just on gcc62/slc6 with flags -Dcxxmodules=On -Dccache=Off

**Comment by vgvassilev** [comment]
@phsft-bot build just on gcc62/slc6 with flags -Dcxxmodules=On -Dccache=Off

**Comment by vgvassilev** [comment]
@phsft-bot build just on clang_gcc62 with flags -Dcxxmodules=On -Dccache=Off

**Pull request merged**
