### PR TITLE
Use mathjax 3. It is faster than mathjax 2.

### PR DESCRIPTION
**Pull request by couet**
https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#improved-speed

Also the size of the tar file is smaller

### CODE REVIEW

**Comment by couet** [comment]
fix: https://github.com/root-project/root/issues/10067

**Review by bellenot — APPROVED** [review]
Good for me, if it works 😉

**Comment by ferdymercury** [comment]
Thanks! The new tar file is missing?

**Comment by ferdymercury** [comment]
Thanks!!

**Pull request merged**
