### PR TITLE
Timeout parameter added to ExternalProject

### PR DESCRIPTION
**Pull request by Harshalzzzzzzz**
@Axel-Naumann @oshadura 
Pull request for the issue https://github.com/root-project/root/issues/6635.

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot  build

**Comment by bellenot** [comment]
@Harshalzzzzzzz please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks

**Comment by Harshalzzzzzzz** [comment]
@bellenot I should directly fork this right?
Or should this be pulled to a particular location?

**Comment by bellenot** [comment]
> @bellenot I should directly fork this right?
> Or should this be pulled to a particular location?
> Thank you for your inputs.

Yes, simply forking is enough, thanks!

**Comment by Harshalzzzzzzz** [comment]
@bellenot Completed 
Can any of the mentors please review this ?
Thanks in advance !

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by Harshalzzzzzzz** [comment]
PR Completed.
Thanks in advance ! 
@oshadura @Axel-Naumann @bellenot

**Review by oshadura — APPROVED** [review]

**Comment by oshadura** [comment]
@Harshalzzzzzzz changes looks good, but because of LLVM upgrade your branch needs to be rebased? can you please do it? Thanks!

**Review by oshadura — COMMENTED** [review]
@Harshalzzzzzzz in fact looking in a source of conflict I see you added `TIMEOUT` in interpreter/llvm/src/ directory. Can I ask you please to add timeout only to `builtins` directory? The problem is that the `interpreter/llvm/src/` directory is synchronized from LLVM repository and we try to reduce unneeded patches on top of this directory.

**Comment by Harshalzzzzzzz** [comment]
@oshadura I've pushed a commit with the suggested changes. 
Thanks !

**Comment by oshadura** [comment]
@Harshalzzzzzzz wonderful! Can you as well add TIMEOUT to other dependencies please here: https://github.com/root-project/root/blob/master/cmake/modules/SearchInstalledSoftware.cmake

**Comment by Harshalzzzzzzz** [comment]
@oshadura Can you please check if the changes are fine?

**Comment by oshadura** [comment]
@phsft-bot build!

**Review by oshadura — APPROVED** [review]
LGTM! Let's see if there are no problems with builds (which I don't expect) and this PR is ready to be merged.

**Pull request merged**
