### PR TITLE
[cmake] Update XRootD to v5.4.2

### PR DESCRIPTION
**Pull request by matthewfeickert**
# This Pull request:

Is a follow up to PR #9992 that includes additional bug fixes.

## Changes or fixes:

Updates XRootD from [`v5.4.1`](https://github.com/xrootd/xrootd/releases/tag/v5.4.1) to patch release [`v5.4.2`](https://github.com/xrootd/xrootd/releases/tag/v5.4.2).

## Checklist:

- [x] tested changes locally
   - I didn't build ROOT from source (though c.f. https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/65 for a source build with effectively this change), but PR #9992 builds and 
```console
$ curl -sLO https://github.com/xrootd/xrootd/archive/v5.4.2.tar.gz
$ sha256sum v5.4.2.tar.gz 
84e8a9a2bcad116df479f94e985c287dd99fbac0613d4fbb61f4ccc0cef81fa3  v5.4.2.tar.gz
```

so as this PR is mirroring 9992 it should be fine.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
> Can one of the admins verify this patch?

In addition to Bertrand I'll tag @Axel-Naumann.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Review by Axel-Naumann — APPROVED** [review]

**Comment by matthewfeickert** [comment]
@Axel-Naumann @bellenot I'm not familiar enough with the test suite to know if these failed tests are relevant. From looking at [`tutorials/rcanvas/df105.py`](https://github.com/root-project/root/blob/d6104649df2fea76793a4b3d59d9d8dc63130167/tutorials/rcanvas/df105.py), and that you approved this PR, I assume no, but I thought I'd ask if there's anything else that you need me to look at.

**Comment by bellenot** [comment]
> 

@matthewfeickert no problem, the errors are unrelated. Thanks for the PR. Merging

**Pull request merged**
