### PR TITLE
[tmva][pymva]Various  fixes in pymva

### PR DESCRIPTION
**Pull request by lmoneta**
These PR fixes several issues in pymva: 

 - the scikit-learn methods require some update for new version of scikit-learn
 - the disabling of eager execution for model prediction causes an issue on MacOS with the multi-processing. The tests are automatically restarted by the multi-processing. This is now avoided by not disabling eager-execution on MacOS platform. 
 - Using .keras file is problematic for MacOS arm. (load_models does not work). Go back using .h5 files

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vepadulano** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod, mac11/noimt, mac12arm/cxx20 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by sanjibansg — APPROVED** [review]
LGTM!

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod, mac11/noimt, mac12arm/cxx20 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod, mac11/noimt, mac12arm/cxx20

**Pull request merged**
