### PR TITLE
[hist] Remove old code which always evaluates to true.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/default

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by linev** [comment]
Probably, one also can remove RVersion.h include - here and in all other similar PRs

**Comment by vgvassilev** [comment]
Good point. I will do that later for this pr and the other changes that went in.

**Pull request merged**
