### PR TITLE
THDFSFile fixes

### PR DESCRIPTION
**Pull request by evgeny-boger**
This set of patches makes THDFSFile work again. 
It also enables CMake build and allows linking against libhdfs3 (experimental native HDFS client implementation).

Kind of major change: HDFS URLs are now absolute instead of relative as it was before. I.e. one have to use "hdfs:///user/username/dir1/file2.root" notation to access file in the home directory. 
This makes HDFS URLs somewhat standard in the sense that they could be used interchangeably between ROOT and Hadoop API and command-line utilities.

### CODE REVIEW

**Comment by pcanal** [comment]
> Kind of major change: HDFS URLs are now absolute

Is this change necessary?  Main reasons to ask are
   a) it is somewhat backward incompatible (however I have no idea how many user might be relying on this)
   b) without it, the user can still decide to use absolute path to have the "could be used interchangeably between ROOT and Hadoop API " part.

**Comment by evgeny-boger** [comment]
Well, it isn't necessary.

Without this change user have to specify the absolute path by adding one more / in front of it. E.g.

hdfs://host:port//user/username/dir/file

(note the extra slash after host).

I personally think that's kind of weird.

Anyway, the problem is that there is no way (to my knowledge) to point to relative path in Hadoop using hdfs:// prefix. So Hadoop uses single slash to point to absolute url. This URL will be parsed incorrectly by current THDFSFile by assuming that the path is relative to user directory.

The absolute URLs with extra leading slashes are, however, correctly parsed by Hadoop. So there is a compatibility to some extent.

**Comment by pcanal** [comment]
@smithdh Would you be able to review (and rebase) this PR?

**Comment by vgvassilev** [comment]
@smithdh ping...

**Comment by smithdh** [comment]
Hello @evgeny-boger Could you select "allow edits from maintainers" for this PR (I think this may not be set at the moment), so that I can rebase?
Thank you, David

**Comment by evgeny-boger** [comment]
@smithdh, done

**Comment by vgvassilev** [comment]
@phsft-bot build!

@smithdh and @evgeny-boger thanks rebasing!

**Comment by smithdh** [comment]
hi @vgvassilev Yes, intend to fix the clang-format result. I'm running some checks using libhdfs or libhdfs3 on a test hdfs instance as part of review and check.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
