### PR TITLE
[hist] Fix assertion failure (invalid comparator)

### PR DESCRIPTION
**Pull request by bellenot**
Fix the following error (visible with the `/RTC1` flag on Windows)
```
libHist: Debug Assertion Failed!
Expression: invalid comparator
```

### CODE REVIEW

**Review by pcanal — CHANGES_REQUESTED** [review]
If/Since this changes are needed we also need to update the function documentations and enhance the commit message to point/hint to the part of the standard indicating whether the comparators should strict (existing code) or not (this PR).

**Comment by bellenot** [comment]
> If/Since this changes are needed we also need to update the function documentations and enhance the commit message to point/hint to the part of the standard indicating whether the comparators should strict (existing code) or not (this PR).

You mean this: https://en.cppreference.com/w/cpp/named_req/Compare

**Comment by pcanal** [comment]
> You mean this: [en.cppreference.com/w/cpp/named_req/Compare](https://en.cppreference.com/w/cpp/named_req/Compare)

Yes something like that .. except that I am reading it as asking for strict comparison ... `For all a, comp(a, a) == false.`

**Comment by bellenot** [comment]
> > You mean this: [en.cppreference.com/w/cpp/named_req/Compare](https://en.cppreference.com/w/cpp/named_req/Compare)
> 
> Yes something like that .. except that I am reading it as asking for strict comparison ... `For all a, comp(a, a) == false.`

Yes, I know, but the original code is from 2003 (see the [commit here](https://github.com/root-project/root/commit/10871c3c027666ef297b032672a59a6a75bb9d62) and was not using `std::stable_sort`, should I completely rewrite those methods?

**Comment by guitargeek** [comment]
The solution of changing the comparator functions is not sustainable, because if one would do `TGraph::Sort()` with `ascending=false` the comparator is not inverted anymore and then it's not strict again.

I think the more sustainable and simpler solution is:
  * https://github.com/root-project/root/pull/18916

**Comment by guitargeek** [comment]
Superseded by:
  * https://github.com/root-project/root/pull/18916

**Pull request closed without merging**
