### PR TITLE
Multi builtin package zlib-CF & zlib

### PR DESCRIPTION
**Pull request by oshadura**
```
Zlib-CF
===
200 events and 55491936 bytes processed.
RealTime=0.691160 seconds, CpuTime=0.650000 seconds
compression settings=101, split=1, arg4=1
You write 80.288122 Mbytes/Realtime seconds
You write 85.372209 Mbytes/Cputime seconds
event:0, rtime=0.042453 s

Master
===
200 events and 55491936 bytes processed.
RealTime=1.384166 seconds, CpuTime=1.080000 seconds
compression settings=101, split=1, arg4=1
You write 40.090521 Mbytes/Realtime seconds
You write 51.381422 Mbytes/Cputime seconds
event:0, rtime=0.104979 s
```

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
Can you rebase this PR?  thanks.

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
On some platform the compression seems better.  Do we have a corresponding update to roottest?

**Comment by oshadura** [comment]
@pcanal yes we have, it is https://github.com/root-project/roottest/pull/274.
I think I am almost ready here, I need to fix only few warnings visible for gcc 8.2 (see fedora 29)

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot on ROOT-performance-centos7-multicore/default, ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot on ROOT-performance-centos7-multicore/default, ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The only failure is due to missing Windows nodes.   It is unclear why the Jenkins CI build is stuck in the "Pending - Building" phase.   See https://epsft-jenkins.cern.ch/job/root-pullrequests-handler/8935/console for the actual results.

**Pull request merged**
