### PR TITLE
bindings/pyroot: remove globbing for Python module files

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Comment by amadio** [comment]
Failures are unrelated, please feel free to merge @Axel-Naumann.

**Comment by amadio** [comment]
This change is just for ROOT-5998, but I think that the build system for the Python stuff in `bindings/pyroot` needs a more thorough rework to fix the problem that it doesn't update if you update the source directory (reported to me by Massimiliano). The problem is with using `file(COPY ...)`, which has no notion it needs to be rerun if the file to be copied is newer. We need a custom target or (the better choice) to write a setup.py or equivalent Python native build, then use CMake to just call `python setup.py` or equivalent. This would make it easy to install ROOT with several Python versions since you'd just have to call the installation procedure with each Python interpreter.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
> This would make it easy to install ROOT with several Python versions since you'd just have to call the installation procedure with each Python interpreter.

Would it also make it easy to have one python version with several ROOT versions?

**Comment by amadio** [comment]
If we rely on PYTHONPATH, only one ROOT version and one Python version will work properly. If we use setup.py, then we can have multiple versions of Python with the same version of ROOT. However, I do not know of a way in which you can have multiple versions of ROOT and multiple versions of Python without requiring some sort of virtualenv or a setup script to set PYTHONPATH, which is a no go for me, or requiring users to `import ROOT-6.16` or similar in Python code, which is also a no go. Maybe someone with more knowlegde about installing multiple versions of a given package in Python can give some clues.

**Comment by Axel-Naumann** [comment]
> If we rely on PYTHONPATH, only one ROOT version and one Python version will work properly.

Can I not redefine `PYTHONPATH` to handle multiple versions of python or ROOT?

**Comment by etejedor** [comment]
> Can I not redefine PYTHONPATH to handle multiple versions of python or ROOT?
Yes, we could handle everything just relying on environment variables (multiple python versions, multiple ROOT versions). I believe the point of @amadio is to move away from the `$PYTHONPATH` strategy and install PyROOT just like any other Python package. That would solve installing PyROOT for multiple Python versions. Regarding multiple ROOT versions, we could rely on systems like Conda to create environments where the user configures the set of packages and their versions.

**Comment by Axel-Naumann** [comment]
As discussed, having multiple ROOT versions is super common for our users. This means:
- we need to continue to support using multiple ROOT versions with python, also outside conda.
- we must not run `setup.py` as part of a ROOT installation ("make install" / package install); this needs to be an explicit action for python experts.
- we should warn if setup.py is about to replace an existing ROOT version, to be helpful to python novices.
It would be great if `import ROOT` can auto-detect which `libPython` (python2 or python3) to load; that would take care of the multi-python case after `source thisroot.sh`.

**Comment by amadio** [comment]
> Can I not redefine PYTHONPATH to handle multiple versions of python or ROOT?

If you set `PYTHONPATH` for Python 3.x, and say `python2 -c 'import ROOT'` it will fail. That's what I mean when I say that by relying on `PYTHONPATH` only one version will work.

> we need to continue to support using multiple ROOT versions with python, also outside conda

That is always possible, but it requires setup scripts. I'm usually talking here about the situation in which you do `yum install root`, and it should work out of the box, without any extra setup. Same for other distributions. This is already the case in Fedora, but they have to go through hoops to make it work, like using alternatives for `libPyROOT.so` in `/etc/alternatives`. That's what I'd like to address.

> we must not run setup.py as part of a ROOT installation

This makes it much harder to do the right thing during installation in order for things to work properly. PyROOT is a python package afterall, so what's the problem in using Python's native methods of installation as part of `make install`?

> It would be great if import ROOT can auto-detect which libPython (python2 or python3) to load; that would take care of the multi-python case after source thisroot.sh

At the moment, `libPyROOT.so` can only work with either Python 2.x or 3.x, not both. We need to change compile-time checks into runtime checks to make the same library work with both Python 2.x and 3.x (there are many `#ifdef`s on the Python version, for example).

Finally, `thisroot.sh` is totally evil and should be deprecated. It messes up the environment when sourcing it, by potentially removing things from the path that should not be removed. It also assumes things about how ROOT was installed, so if ROOT's libraries are not in `$ROOTSYS/lib` (e.g., if they are in `$ROOTSYS/lib64`, or `$ROOTSYS/root/lib` with `gnuinstall=ON`) the script won't work. It also uses a colon for separator in `CMAKE_PREFIX_PATH`, which is separated by semicolons, among other problems. My advice to people is to just stop using the script.

Anyway, this is all a digression from this PR. Please merge it so I can close [ROOT-5998](https://sft.its.cern.ch/jira/browse/ROOT-5998), as after this, globbing is only used in places that do not matter for the purposes of incremental builds.

**Comment by Axel-Naumann** [comment]
This is going waaay out of the scope of this PR :-) Maybe we discuss this outside this PR? To summarize here, there are many assumptions, expectations and assertions in your reply that I do not share, so that cannot yet be the final answer. Again, let's continue outside this PR.

**Comment by amadio** [comment]
Yes, perhaps having something in Jira for this is useful. I didn't find anything on a quick search. I know that the opinions on the topic diverge, so indeed it's best to discuss this in the appropriate channels.

That said, can we merge this? It passed the checks, and is safe to merge for the release.

**Pull request merged**
