### PR TITLE
[DF] Do not use C++14 in RArrowDS

### PR DESCRIPTION
**Pull request by eguiraud**
:sweat_smile:

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Pull request merged**
