### PR TITLE
[IO][ROOT-6145] Allow user to set the size of the memory block of TMemFiles

### PR DESCRIPTION
**Pull request by dpiparo**
and adapt the size of the block for TBufferMergerFile

### CODE REVIEW

**Comment by pcanal** [comment]
> Set the block size for TBufferMergerFile to 1MB

What's the rational/measurement leading to that choice?

**Comment by dpiparo** [comment]
Reduce the memory usage by 50% in some usecases, e.g. atlas susy.

**Comment by pcanal** [comment]
What is the size of the file/cluster in that case?

**Comment by dpiparo** [comment]
not sure.

**Comment by pcanal** [comment]
The question I am pondering is whether we need to tweak the default (as done in the PR) or just the specific case (as now allowed by this PR).

**Pull request merged**
