### PR TITLE
Add example CODEOWNERS file.

### PR DESCRIPTION
**Pull request by bbockelm**
The code owner's file helps establish a relationship between individuals / groups and code.  Currently, it's used to provide hints as to who should be a reviewer for a specific PR.  It's a hint, not a requirement -- although GitHub has the ability to require a review for protected branches.

See https://github.com/blog/2392-introducing-code-owners for more information.

Certainly the ownership is quite incomplete - but should provide a sufficient starting point.

### CODE REVIEW

**Comment by bbockelm** [comment]
@phsft-bot build!

**Comment by dpiparo** [comment]
Hi,
I am not overly enthusiastic to attach owners to directories. Everybody should feel responsible for the project as a whole. I think it's limiting to restrict ownership to individual directories.

**Comment by bbockelm** [comment]
Despite the filename saying "owners" - I think of it more as "suggested reviewers".

You can certainly have something like:
```
* @dpiparo
```

and you will show up as a suggested reviewer for all PRs.

**Comment by martinmine** [comment]
@dpiparo this is a new feature GitHub added last month. Despite the term "code owners", it is a way of telling GitHub who should review certain parts of our code base when we receive PRs. Have a look: https://github.com/blog/2392-introducing-code-owners

**Comment by vgvassilev** [comment]
@bbockelm thanks for the PR. Could you elaborate which issue this is supposed to address/solve?

**Comment by bbockelm** [comment]
@vgvassilev - it's precisely the case outlined in the text of the PR.  This provides a programmatic way for GitHub to provide reasonable suggestions of reviewers.

ROOT is a really distributed project in terms of maintainers of different pieces.  External contributors - particularly, those that contribute infrequently - may not know who owns or is responsible for a particular module.  Heck, I don't.  For example, if I make a PR against a GUI component, GitHub currently may suggest that Danilo review the PR because he was the last one to edit the file -- even if it was just a whitespace change.

This is all about making ROOT a friendlier project for newbies.

**Comment by peremato** [comment]
I have updated the list of 'owners' and would like to see (experimentally) what is the effect of it for assigning PR. Clearly we need to fine tune the list with more fine grain assignments.

**Pull request merged**
