### PR TITLE
[cxxmodule] Fix a warning in modules build

### PR DESCRIPTION
**Pull request by yamaguchi1024**
Not expose ROOT/RConfig.h to rootcling, but to add the header to ROOT_Config pcm.

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
FYI, the warning is https://epsft-jenkins.cern.ch/job/root-nightly-master/LABEL=ROOT-ubuntu18.04,SPEC=rtcxxmod/2039/parsed_console/

**Comment by Axel-Naumann** [comment]
I cannot tell whether it's better to expose this header to `rootcling` and add it to modules.map, or vice versa... @amadio what's your take? IIUC, before your change, `ROOT/Rconfig.h` wasn't part of the headers passed to `rootcling`.

**Comment by amadio** [comment]
If it wasn't part of the headers, removing it is fine, but you know better than me in case you want to add it to the module map.

**Comment by yamaguchi1024** [comment]
Thanks! Yeah this header is already in ROOT_Config module

**Comment by Axel-Naumann** [comment]
No it's not, that's why brought it up. We have `RConfig.h` (the backward-compatibility header) in the modules.map, not `ROOT/RConfig.hxx`, the real one.

**Comment by yamaguchi1024** [comment]
Hi, added ROOT/RConfig.h to ROOT_Config module and removed the exposure to rootcling.

**Pull request merged**
