### PR TITLE
optimise includes in math

### PR DESCRIPTION
**Pull request by pseyfert**
cleaning up a few includes in math/mathmore and math/physics.
NB:
1. root builds for me with these changes but i didn't check for platform independence (when it comes to system headers)
2. removing includes from headers may break 3rd party code including those headers i manipulated.

### CODE REVIEW

**Comment by sbogacz** [comment]
This is my first foray into this project, but there are a few instances of commenting out the includes instead of fully removing them. If they can in fact be safely removed regardless of the target platform, then the lines should be removed to avoid cluttering up the code base.

**Comment by vgvassilev** [comment]
@pseyfert, good work! Could you rebase and remove the redundant lines instead of commenting them out?

**Comment by pseyfert** [comment]
- Rebased and deleted includes instead of commenting out.
- I didn't rerun IWYU so I'm curious if the build still succeeds.
- Also the rebase failed on math/physics/inc/TVector3.h where I used the master for simplicity.

**Comment by vgvassilev** [comment]
@phsft-bot: build.

**Comment by vgvassilev** [comment]
@phsft-bot: build!

**Comment by vgvassilev** [comment]
@phsft-bot: build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@pseyfert, do you think you can optimise the rest of the includes in ROOT in a similar manner in a new PR?

**Comment by pseyfert** [comment]
need to check. i didn't get iwyu running with cmake and haven't used ./configure since quite a while.
i had tried it back then for roofit and realised it caused problems in my own "third party" code if a class A has a method to return a pointer to an instance of class B, but A.h doesn't include B.h.

**Comment by vgvassilev** [comment]
It seems that there are two ways to use it within cmake: http://stackoverflow.com/questions/30951492/how-to-use-the-tool-include-what-you-use-together-with-cmake-to-detect-unused-he

Vassil
Msg sent from my phone. Please excuse my brevity.

**Comment by vgvassilev** [comment]
Merged, thanks! I'd be happy to review a PR, running IWYU on the rest of the ROOT codebase!

**Comment by pseyfert** [comment]
cool, will notify you once i came around running it.

**Comment by pseyfert** [comment]
@vgvassilev I put the output of a first run /afs/cern.ch/work/p/pseyfert/public/iwyu.log It's quite big (and i didn't even build all components) and also involves parts I don't dare to touch (llvm). I'll clean up my changes to the cmake files and factorise the suggestions a bit.

**Comment by vgvassilev** [comment]
Good progress. I do not understand why it says we should remove the `.o` files. Do you have an in-source build somehow?

**Comment by pseyfert** [comment]
changes to cmake now available here: https://github.com/pseyfert/root/tree/IWYU .
It's not an in-source build, but I iterated a few times with
```
cd ../build
rm -rf *
cmake ../root -G Ninja .......
cmake --build .
```
and once i saw the first iwyu output (realising i put the parts together correctly), I didn't do an `rm -rf` (don't touch a running system) and ran:
```
cmake --build . --clean-first -- -v
```

**Comment by vgvassilev** [comment]
Ok, looks very good. Can we implement this as a travis check. I don't expect people to run it locally.

**Pull request closed without merging**
