### PR TITLE
Remove BasicXYZ

### PR DESCRIPTION
**Pull request by HDembinski**
Minuit2 uses the Pimpl idiom with a shared_ptr to avoid frequent copies, but the implementation is not good. The full interface of each class is duplicated, which is not necessary and makes the code confusing and difficult to change. This patch simplifies the implementation but keeps the semantics the same.

This patch is a precursor of some improvements that I have prepared.

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build

**Comment by HDembinski** [comment]
Regarding the clang-tidy fail: https://travis-ci.org/github/root-project/root/jobs/767085481#L4062

This is unrelated to this patch. I plan to replace the StackAllocator in a follow-up patch, because it does not work with multi-threading. There is a better/safer way of achieving this.

Regarding the clang-format fail: https://travis-ci.org/github/root-project/root/jobs/767085483#L254

This is the issue we had before, the CI bot uses an order version of clang-format, which based on the same style file, produces these weird formatting. I locally use version 9.0 of clang-format and the formatting actually looks more reasonable. Perhaps it would be better to update the clang-format version that the CI bot uses?

**Comment by eguiraud** [comment]
Feel free to ignore the clang-format complaints if you already applied clang-format with a newer version. And the test failures on debian 32bits are unrelated of course (will be fixed soon).

**Comment by Axel-Naumann** [comment]
`...compr_level9` failures are now fixed in master.

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by HDembinski** [comment]
To give some context, why I am touching these classes. An iminuit user noticed that Migrad does not stop when the call limit is reached in certain corner cases. While tracing that issue, I found the core issue in MnHesse, which does not report back if the call limit is reached while it runs. The fit is correctly aborted then, but the fit state is not "call limit reached", instead the minimum is reported as valid. So while this only happens in certain corner cases, it is nevertheless a bad bug, since Migrad says the minimum is fine although that is not the case.

**Comment by lmoneta** [comment]
What is the relation of this PR with this bug reported in iminuit ? 
https://github.com/scikit-hep/iminuit/issues/637 

Should we then open an issue for this in ROOT ?

**Comment by HDembinski** [comment]
@lmoneta I can open an issue, but my plan was to submit a PR to fix this after this patch is merged.

**Comment by lmoneta** [comment]
Ah great, if you have a PR already for this,then yes, just submit it after this one
Thanks

**Pull request merged**
