### PR TITLE
Fix incorrect navigation when exactly on the frontier of an overlapping volume

### PR DESCRIPTION
**Pull request by arekfu**
This is a backport of commit 68509691, fixing bug [ROOT-9907](https://sft.its.cern.ch/jira/browse/ROOT-9907).

Do you guys plan to release a new patch to the v6.12 series?

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by agheata** [comment]
@phsft-bot build

**Comment by agheata** [comment]
There are lots of configuration errors on this branch on different platforms, unrelated to this PR.

**Comment by arekfu** [comment]
@agheata @Axel-Naumann Are there any plans on your side to make a new patch release to the v6.12 series? That would be very helpful for my team, but I don't know if it is compatible with your schedule.

Also, I am not sure this is the correct place to ask. Should I open a new issue?

**Comment by Axel-Naumann** [comment]
We were indeed considering a patch release to v6.12 - also for other reasons than your commit. Could I ask for your use-case / experiment / some motivation? I.e. if this is mission critical for an experiment's DAQ (doubt it for this patch ;-) then we'll hurry up!

**Comment by arekfu** [comment]
For the context, I belong to the team that develops the TRIPOLI-4 Monte-Carlo particle transport code, which uses ROOT as (among other things) a geometry engine. We are not in a terrible hurry (hopefully in a month or two though?), but we would greatly appreciate a new patch release on top of the v6.12 branch. That would largely cut on the amount of validation work that we need to do for our next release.

Thanks!

**Comment by arekfu** [comment]
@Axel-Naumann any news about the patch release to v6.12? Thanks.

**Comment by Axel-Naumann** [comment]
I will do that on Tuesday!

**Pull request merged**
