### PR TITLE
[Do not merge] Check clad's master before releasing

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by hahnjo** [comment]
@vgvassilev do we need this open, are there followups to the failing tests?

**Comment by vgvassilev** [comment]
> @vgvassilev do we need this open, are there followups to the failing tests?

Yes, on the clad side. We should keep this open for a little longer.

**Comment by vgvassilev** [comment]
@guitargeek, could you help us reduce the current problem and get a standalone reproducer?

**Comment by guitargeek** [comment]
> @guitargeek, could you help us reduce the current problem and get a standalone reproducer?

I still have a reproducer in one of the open Clad issues:
https://github.com/vgvassilev/clad/issues/681

Or is that one fixed now?

**Comment by vgvassilev** [comment]
> > @guitargeek, could you help us reduce the current problem and get a standalone reproducer?
> 
> I still have a reproducer in one of the open Clad issues: [vgvassilev/clad#681](https://github.com/vgvassilev/clad/issues/681)
> 
> Or is that one fixed now?

That one should have been fixed. I suspect that’s a new issue.

**Comment by guitargeek** [comment]
I boiled down the failures to a simple extension of the issue that I already reported:
https://github.com/vgvassilev/clad/issues/681#issuecomment-1904660655

**Comment by vgvassilev** [comment]
> Build failed on ROOT-ubuntu2204/nortcxxmod. Running on root-ubuntu-2204-3.cern.ch:/home/sftnight/build/workspace/root-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/193778/console).
> ### Failing tests:
> 
>     * [projectroot.roofit.histfactory.test.gtest_roofit_histfactory_test_testHistFactory](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/193778/testReport/projectroot.roofit.histfactory/test/gtest_roofit_histfactory_test_testHistFactory/)

@guitargeek, can you give us a hand again?

**Comment by vgvassilev** [comment]
> I boiled down the failures to a variation of the issue with the double loop that I already reported: [vgvassilev/clad#681 (comment)](https://github.com/vgvassilev/clad/issues/681#issuecomment-1917122065)

Thank you, @guitargeek!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
The windows failure boils down to:
```
cern\sftnight@ROOT-VS2019 C:\vvasilev-root-dev\vvbuild>root.exe -l
root [0] #include "Math/CladDerivator.h"
root [1] double arr[2] = {0,1};
root [2] clad::array_ref<Double_t> _d_pi(arr);
root [3] double _r0 = 1;
root [4] _d_pi[0] = 1;
ROOT_prompt_4:1:6: error: use of overloaded operator '[]' is ambiguous (with operand types 'clad::array_ref<Double_t>' (a
ka 'array_ref<double>')
      and 'int')
_d_pi[0] = 1;
~~~~~^~
C:/vvasilev-root-dev/vvbuild\etc\/cling\plugins/include/clad/Differentiator/ArrayRef.h:66:23: note: candidate function   
  CUDA_HOST_DEVICE T& operator[](std::size_t i) { return m_arr[i]; }
                      ^
C:/vvasilev-root-dev/vvbuild\etc\/cling\plugins/include/clad/Differentiator/ArrayRef.h:67:29: note: candidate function   
  CUDA_HOST_DEVICE const T& operator[](std::size_t i) const { return m_arr[i]; }
                            ^
ROOT_prompt_4:1:6: note: built-in candidate operator[](double *, int)
_d_pi[0] = 1;
     ^
ROOT_prompt_4:1:6: note: built-in candidate operator[](const double *, int)
ROOT_prompt_4:1:6: note: built-in candidate operator[](volatile double *, int)
ROOT_prompt_4:1:6: note: built-in candidate operator[](const volatile double *, int)
```

I am not sure why this works elsewhere and does not work on Windows. Perhaps we somehow get more builtin operators?

@vaithak, do you have any clue?

**Comment by vaithak** [comment]
I think this is because array_ref has both operators - conversion to pointer, as well as array indexing, which is making ambiguity.
I think we can safely remove the operator[]; that should fix it. 
Found a similar Stackoverflow question: https://stackoverflow.com/questions/49607565/error-use-of-overloaded-operator-is-ambiguous-while-building-for-i386

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@guitargeek, could we get a reproducer for the windows failure by any chance?

In addition, maybe now it is a good time to check performance of clad. Do you think you can do this on this PR while we are working on getting things merged properly in the clad master?

**Pull request closed without merging**
