### PR TITLE
[TMVA] Add API Support for Adadelta Optimizer.

### PR DESCRIPTION
**Pull request by ravikiran0606**
* Implement Adagrad Optimizer.
* Add Unit tests and MethodDL tests.

Reference Implementation: [Tensorflow Adadelta Optimizer](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adadelta)

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by ravikiran0606** [comment]
@stwunsch  @lmoneta  I rebased the PR. Can you please trigger the build?

**Comment by ravikiran0606** [comment]
@stwunsch  @lmoneta  I rebased the PR. Can you please trigger the build?

**Comment by lmoneta** [comment]
@phsft-bot build !

**Comment by lmoneta** [comment]
Hi Ravi, 
Can you add MaxEpochs=50 or even less in the test to avoid the timeout. We should also understand why the test error continues to decrease

 Lorenzo

**Comment by ravikiran0606** [comment]
@lmoneta  @stwunsch  I updated the PR with MaxEpochs = 100. Can you please re-trigger the build?

**Comment by lmoneta** [comment]
@phsft-bot build !

**Comment by ravikiran0606** [comment]
@lmoneta @stwunsch I guess we are good to merge now :smiley:

**Pull request merged**
