### PR TITLE
Fix ROOT for musl libc - part 2

### LINKED ISSUE #9253: ROOT does not compile on musl libc
I'm trying to compile ROOT v6.24/06 on Void Linux with musl libc, however the build fails with the following error message:
```cc
/builddir/root-6.24.06/core/clib/src/mmapsup.c:47:15: error: conflicting types for 'getpagesize'
   47 | extern size_t getpagesize PARAMS ((void));
      |               ^~~~~~~~~~~
In file included from /builddir/root-6.24.06/core/clib/res/mmprivate.h:56,
                 from /builddir/root-6.24.06/core/clib/src/mmapsup.c:26:
/usr/include/unistd.h:163:5: note: previous declaration of 'getpagesize' was here
  163 | int getpagesize(void);
      |     ^~~~~~~~~~~
```

The relevant part of `mmapsup.c` is:
```c
#if defined(R__LINUX) && !defined(R__GLIBC) && !defined(__CYGWIN__) \
   || (defined(__CYGWIN__) && (CYGWIN_VERSION_API_MAJOR > 0 || CYGWIN_VERSION_API_MINOR < 213))
extern size_t getpagesize PARAMS ((void));
#else
extern int getpagesize PARAMS ((void));
#endif
```

My understanding is that as musl doesn't define `R__GLIBC`, the condition resolves in favor of declaring `getpagesize` return value as `size_t`. However, this conflicts with the declaration present in `unistd.h` (which is included several lines above this), which declares it as `int` (in accordance with the POSIX standard).

The same code snippet also causes error during `core/clib/src/mvalloc.c` compilation.

It's not entirely clear to me why should `getpagesize` be declared in the first place, as it is declared in the included `unistd.h` file - my guess is for some kind of compatibility, although POSIX dropped it twenty years ago and Cygwin seems to have implemented it at least four years ago, likely more, I am not sure how this works on Windows - let alone as `size_t`. Thus my suggestion is to remove the above code block from both of the mentioned files entirely, which seems to fix the problem for me (at least until the compilation fails on another problem, which I haven't analyzed yet; and I'm still able to compile for glibc too) and my question is: would it break anything crucial (as I mentioned, `getpagesize` has been deprecated for more than twenty years now (at least on UNIX-like systems), so keeping support for some potentially obscure platforms which still expect it with `size_t` return value may not be of high importance (but again, I do not know what the situation is on Windows))? And if so, what is the right way to solve this?

Here's a [link](https://root-forum.cern.ch/t/compiling-error-conflicting-types-alpine-linux/28193) to a ROOT forum thread which describes the same problem (but does not provide any more information than is stated above).

### PR DESCRIPTION
**Pull request by balejk**
Continuation of #9260, closes #9253. Successfully compiles and launches with both musl and glibc, however the affected features were **not** specifically tested so please make sure to review carefully.

With musl, compilation only succeeds without builtin XRootD and TBB and without SSL support - the former need to be fixed in the respective projects, the latter would probably require a little more effort as the `ruserok` function used by `net/rpdutils/src/rpdutils.cxx` is not available in musl - this implies `-Dxrootd=OFF -Dimt=OFF -Dssl=OFF` `cmake` options.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by balejk** [comment]
@Axel-Naumann Just to make sure: is anything required of me right now or will you review and diagnose the problems yourself when you have the time? If the former, would you please inform me how to get a CERN account which seems to be mandatory in order to access the build logs?

**Review by Axel-Naumann — APPROVED** [review]
Thanks for pinging me! I believe this is good to go - these failures happened one night, apparently due to a network issue at CERN. I will re-run the test suite, but there's nothing for you to be done here.

Note that we expect to have publicly accessible logs starting next year, i.e. yes, agrees, we see that as a problem, too!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by balejk** [comment]
@Axel-Naumann Network issues again?

**Comment by Axel-Naumann** [comment]
No, Python / macOS install issues this time :-/ This is good to go!

**Comment by balejk** [comment]
Thank you!

**Pull request merged**
