### PR TITLE
[TDF] Let TDataFrame use TDataSources to read data

### PR DESCRIPTION
**Pull request by bluehood**
Test PR to check build issues and incompatibilities with current test suite.

### CODE REVIEW

**Comment by dpiparo** [comment]
Working on the tdatasource in parallel here (https://github.com/dpiparo/tdatasource). The interface designed for it seems to do the job well. Still some issues in reading root files - working on them!

**Comment by bluehood** [comment]
The only big thing missing is support for data-source columns in jitted actions (jitted transformations should work). It requires a bit of refactoring, I will get to it once we know the implementation is sound.

**Comment by bluehood** [comment]
The work @dpiparo has done has been merged into this branch:
* trivial data-source implementation (has just one column that contains the entry number)
* ROOT data-source implementation: allows reading ROOT files via the data-source interface
* documentation for `TDataSource`
* google tests for both data-sources

Thanks Danilo!!

**Comment by bluehood** [comment]
**To do**

- [ ] gtest for support of non-copiable types in TDF+TDS
- [ ] gtest for support of non-default-constructible types in TDF+TDS
- [ ] gtests for multi-thread execution of TDF+TDS

**Pull request merged**
