### PR TITLE
Do not use cling pointer checks for TDF

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by bluehood** [comment]
Great!!!
I ran the following snippet against this patch (on a tree containing 1e8 floats in branch "x"):

```c++
#include "ROOT/TDataFrame.hxx"
#include "TROOT.h"
#include <iostream>

int main()
{
   const auto poolSize = 4; // the higher, the worse
   ROOT::EnableImplicitMT(poolSize);
   std::cout << "pool size: " << poolSize << std::endl;

   ROOT::Experimental::TDataFrame d("tree", "file.root");
   auto h = d.Histo1D("x");
   std::cout << "stddev: " << h->GetStdDev() << std::endl;
   return 0;
}
```

Before the patch:
before

and after
after

One can see that runtime is now spent doing useful work.
I'm currently running all of TDataFrame tests in a loop just to be sure.

Before merging I would like to add a commit that substitutes `ProcessLine` with `Calc` also in the remaining occurrences, but besides this the PR is absolutely green for me.

**Comment by bluehood** [comment]
Running the tests I saw the same deadlock that we had after the changes to cling that allowed not jitting `gROOTMutex->UnLock()` (due to a lock being recursively taken in a signal handler after cling crashed). I believe this is due to a "dirty" incremental.

I'll test again after building ROOT from scratch.

**Comment by Axel-Naumann** [comment]
@bluehood Thanks! Do you have objections against me merging this?

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by bluehood** [comment]
@Axel-Naumann I see a deadlock even after rebuilding ROOT from scratch

**Comment by pcanal** [comment]
Can you reproduce in a debugger and/or can you attach a debugger to the deadlocked process and print/show the set of stack traces.  This should tell us who are the two threads holding the same lock.

**Comment by bluehood** [comment]
Hi @pcanal, please find a stacktrace below. It is one single thread recursively locking a mutex.
This is an issue I had before, also after a change in cling.
I rebuilt ROOT from scratch and retested again, I believe it was an artifact of a bad build. Probably some dependencies missing.

I'd ask @Axel-Naumann to merge [this PR of mine](https://github.com/Axel-Naumann/root/pull/196) into this branch of his. I'll trigger another round of tests (as soon as possible) just to be sure everything works as intended, then everything is green as far as I'm concerned. Thanks again for the fix!

**Comment by pcanal** [comment]
@bluehood please find a stacktrace below. 

github is hiding it from me ... do you know where to find it?

**Comment by bluehood** [comment]
my bad:
```
#0  __lll_lock_wait_private () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
#1  0x00007fd43ffaafd2 in __GI___libc_malloc (bytes=140549586459392) at malloc.c:2926
#2  0x00007fd440a967a8 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fd440b24fd5 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fd440b1911e in std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::overflow(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fd440b23549 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fd440b08cae in std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<unsigned long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, unsigned long) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fd440b08ded in std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::do_put(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, unsigned long) const
    () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fd440b14cba in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fd441061c1e in std::ostream::operator<< (__n=<optimized out>, this=0x7fff30eaf700) at /usr/include/c++/6/ostream:185
#10 textinput::TerminalDisplayUnix::HandleResizeSignal (this=<optimized out>) at /home/eguiraud/ROOT/root/core/textinput/src/textinput/TerminalDisplayUnix.cpp:148
#11 <signal handler called>
#12 malloc_consolidate (av=av@entry=0x7fd4402c9b00 <main_arena>) at malloc.c:4211
#13 0x00007fd43ffa8dca in _int_malloc (av=av@entry=0x7fd4402c9b00 <main_arena>, bytes=bytes@entry=1536) at malloc.c:3488
#14 0x00007fd43ffaaf34 in __GI___libc_malloc (bytes=1536) at malloc.c:2928
#15 0x00007fd440a967a8 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fd43bfb375a in llvm::DenseMap<clang::Decl const*, clang::CodeGen::Address, llvm::DenseMapInfo<clang::Decl const*>, llvm::detail::DenseMapPair<clang::Decl const*, clang::CodeGen::Address> >::grow(unsigned int) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#17 0x00007fd43c0c386a in clang::CodeGen::CodeGenFunction::EmitParmDecl(clang::VarDecl const&, clang::CodeGen::CodeGenFunction::ParamValue, unsigned int) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#18 0x00007fd43c09b812 in clang::CodeGen::CodeGenFunction::EmitFunctionProlog(clang::CodeGen::CGFunctionInfo const&, llvm::Function*, clang::CodeGen::FunctionArgList const&) ()
   from /home/eguiraud/ROOT/root_build/lib/libCling.so
#19 0x00007fd43bfd73b5 in clang::CodeGen::CodeGenFunction::StartFunction(clang::GlobalDecl, clang::QualType, llvm::Function*, clang::CodeGen::CGFunctionInfo const&, clang::CodeGen::FunctionArgList const&, clang::SourceLocation, clang::SourceLocation) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#20 0x00007fd43bfda500 in clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#21 0x00007fd43bff48aa in clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#22 0x00007fd43c000ffc in clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#23 0x00007fd43c00119b in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#24 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#25 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#26 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#27 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#28 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#29 0x00007fd43c0011b7 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#30 0x00007fd43c001261 in clang::CodeGen::CodeGenModule::Release() () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#31 0x00007fd43bf6cb97 in clang::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#32 0x00007fd43bf14df7 in cling::IncrementalParser::codeGenTransaction(cling::Transaction*) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#33 0x00007fd43bf14a62 in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#34 0x00007fd43bf17c4e in cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#35 0x00007fd43bebca8b in cling::Interpreter::EvaluateInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#36 0x00007fd43bebcd31 in cling::Interpreter::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::Value*, cling::Transaction**, bool) ()
   from /home/eguiraud/ROOT/root_build/lib/libCling.so
#37 0x00007fd43bf4d3bf in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#38 0x00007fd43be441aa in HandleInterpreterException (metaProcessor=0x558e2aa2dcc0, 
    input_line=0x558e32ba5ec0 "reinterpret_cast<ROOT::Experimental::TDF::TInterface<ROOT::Detail::TDF::TFilterBase>*>(0x7fff30eb3a10)->Snapshot<int, vector<float>, int, float>(\"a/myTree\", \"test_snapshot_inDirectory_output.root\", *r"..., compRes=@0x7fff30eb351c: cling::Interpreter::kSuccess, result=result@entry=0x7fff30eb3640) at /home/eguiraud/ROOT/root/core/metacling/src/TCling.cxx:1927
#39 0x00007fd43be5331e in TCling::ProcessLine (this=this@entry=0x558e2a66d6f0, line=<optimized out>, error=error@entry=0x7fff30eb390c) at /home/eguiraud/ROOT/root/core/metacling/src/TCling.cxx:2085
#40 0x00007fd4359a3504 in ROOT::Experimental::TDF::TInterface<ROOT::Detail::TDF::TFilterBase>::Snapshot (this=this@entry=0x7fff30eb41a0, treename=..., filename=..., 
    columnList=std::vector of length 4, capacity 32 = {...}) at /home/eguiraud/ROOT/root_build/include/ROOT/TDFInterface.hxx:403
#41 0x00007fd4359a55ba in ROOT::Experimental::TDF::TInterface<ROOT::Detail::TDF::TFilterBase>::Snapshot (this=0x7fff30eb41a0, treename=..., filename=..., columnNameRegexp=...)
    at /home/eguiraud/ROOT/root_build/include/ROOT/TDFInterface.hxx:458
#42 0x00007fd436299f11 in do_work(char const*, char const*, char const*, char const*) () from /home/eguiraud/ROOT/root_build/roottest/root/dataframe/test_snapshot_C.so
#43 0x00007fd43629ac08 in runTest() () from /home/eguiraud/ROOT/root_build/roottest/root/dataframe/test_snapshot_C.so
#44 0x00007fd43629ac26 in test_snapshot() () from /home/eguiraud/ROOT/root_build/roottest/root/dataframe/test_snapshot_C.so
#45 0x00007fd4417ef083 in ?? ()
#46 0x0000558e2ae71b40 in ?? ()
#47 0x00007fd4417ef060 in ?? ()
#48 0x0000000000000000 in ?? ()
```

**Comment by pcanal** [comment]
Is there really only one thread?

**Comment by bluehood** [comment]
yes, the deadlock happens before fanning out to multi-threading. but as I said I cannot reproduce it now with a clean build.

**Comment by pcanal** [comment]
Ok. Fair enough.  The 'dead-lock' is a red-herring.  It is due to the sig-fault handler attempting to allocate memory (we have a proposal to fix that which is waiting on me to do some cleanups).

The 'real' problem is:
```
#12 malloc_consolidate (av=av@entry=0x7fd4402c9b00 <main_arena>) at malloc.c:4211
#13 0x00007fd43ffa8dca in _int_malloc (av=av@entry=0x7fd4402c9b00 <main_arena>, bytes=bytes@entry=1536) at malloc.c:3488
#14 0x00007fd43ffaaf34 in __GI___libc_malloc (bytes=1536) at malloc.c:2928
#15 0x00007fd440a967a8 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fd43bfb375a in llvm::DenseMap<clang::Decl const*, clang::CodeGen::Address, llvm::DenseMapInfo<clang::Decl const*>, llvm::detail::DenseMapPair<clang::Decl const*, clang::CodeGen::Address> >::grow(unsigned int) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#17 0x00007fd43c0c386a in clang::CodeGen::CodeGenFunction::EmitParmDecl(clang::VarDecl const&, clang::CodeGen::CodeGenFunction::ParamValue, unsigned int) () from /home/eguiraud/ROOT/root_build/lib/libCling.so
#18 0x00007fd43c09b812 in clang::CodeGen::CodeGenFunction::EmitFunctionProlog(clang::CodeGen::CGFunctionInfo const&, llvm::Function*, clang::CodeGen::FunctionArgList const&) ()
   from /home/eguiraud/ROOT/root_build/lib/libCling.so
```

I.e. a crash (out-of-memory?) during malloc during JIT compilation.   I recommend running with valgrind to get some more information. (And/or disabling the ROOT signal handler to see the real issue a little better).

**Comment by bluehood** [comment]
@pcanal you don't think it was due to a dirty build dir? I can't reproduce it anymore.

**Comment by Axel-Naumann** [comment]
@phsft-bot build, please

**Comment by pcanal** [comment]
> but as I said I cannot reproduce it now with a clean build.
> you don't think it was due to a dirty build dir? I can't reproduce it anymore.

Sorry I misread.  My diagnostic is completely compatible with a bad build (i.e crazy malloc because two of the .o files disagree on the size of something for example ....)

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Pull request merged**
