### PR TITLE
[PyROOT] PyROOT backports

### PR DESCRIPTION
**Pull request by stwunsch**
Backports of `RDataFrame.AsNumpy` and bugfixes for the memory adoption mechanism.

Do not merge yet, I'm gonna have a second look for fixes I could have forgotten.

### CODE REVIEW

**Comment by stwunsch** [comment]
Let's rebuild and check what the problem is. @etejedor Do you remember the problems above with failing string proxies? `PyROOT::CreateScopeProxy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*)` leads to a segfault. Probably it's the cxx11 ABI?

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by etejedor** [comment]
@stwunsch no I do not remember this, the issue is with `CreateScopeProxy` in general or it is crashing when trying to get the proxy of a particular class? This shoud be easily reproducible since `CreateScopeProxy` can be even called from Python.

**Comment by stwunsch** [comment]
Well, I found a missing commit. Note to myself: Make the backport earlier :see_no_evil:

**Comment by stwunsch** [comment]
For now, put on hold.

**Pull request closed without merging**
