### PR TITLE
[RF] Backport RooFit banner removal (6.26)

### PR DESCRIPTION
**Pull request by henryiii**
This PR is a backport of #9965 (see #9954) for 6.26. Optional, but it would be nice to avoid patching conda-forge root https://github.com/conda-forge/root-feedstock/issues/160.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Thanks @henryiii! I agree this would be super nice to see.

**Review by guitargeek — APPROVED** [review]
Thanks a lot for the backport! Unfortunately the release procedure in on the way done by @Axel-Naumann, so merging to this branch is blocked. I guess we can merge again and then put this into ROOT 6.26.02.

@henryiii, please also do a backport of https://github.com/root-project/roottest/pull/834 to the 6.26 branch there (it needs to be done by the same person with the same branch name as in this PR for the CI to test the PRs together). Once the tests are all passing we can merge!

**Comment by matthewfeickert** [comment]
> Thanks a lot for the backport! Unfortunately the release procedure in on the way done by @Axel-Naumann, so merging to this branch is blocked. I guess we can merge again and then put this into ROOT 6.26.02.

Thanks for this fast response @guitargeek. So if I understand this correctly, we can't get this backported to the next ROOT release `v6.26.0` and so we should get a patch like described in https://github.com/conda-forge/root-feedstock/issues/160 into conda-forge root, and then if Henry backports this into `v6.26.02` then in that release the banner onwards the banner will be gone (and then in conda-forge root we can drop the previous patch). Do I have that correct? If so, sounds good to me.

**Comment by guitargeek** [comment]
Hi @matthewfeickert, yes that's correct, but I think it's not worth to make an intermediate patch in conda. The next point release usually comes only a few weeks after the initial release.

**Comment by guitargeek** [comment]
As stated in https://github.com/root-project/roottest/pull/840#issuecomment-1097650315, this PR will be closed because it was decided to not backport the banner removal to the 6.26 branch.

**Pull request closed without merging**
