### PR TITLE
[hist] Port to Win64 (replace Long_t by Longptr_t + pointer formatting)

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Review by couet — APPROVED** [review]
It looks good to me.

**Review by lmoneta — APPROVED** [review]
Looks good to me !
For curiosity, why you need to use ULong_t and not size_t for pointer formatting ?

**Comment by bellenot** [comment]
> Looks good to me !
> For curiosity, why you need to use ULong_t and not size_t for pointer formatting ?

Thanks! And you mean the opposite, right? I use `%zx` and `size_t` because it is architecture dependent and correct for both 32 and 64 bit, otherwise the compiler complains either in 32 or in 64 bit (one would need either `%llx` or `%lx`)

**Comment by lmoneta** [comment]
Thanks. It makes sense

**Pull request merged**
