### PR TITLE
Convolutional Layer in CUDA

### PR DESCRIPTION
**Pull request by steremma**
This is a PR including a lot of work on the convolutional layer.

It can be logically divided the following parts:

1. Back propagation in CUDA (this was the most complex)

2. Forward propagation in CUDA (this was a comparatively simpler task)

3. Helper static methods such as a column based sum reduction and matrix equality checkers for every architecture.

4. An element by element detailed test case for backward and forward propagation. The one on forward propagation was designed and solved on paper. I was not able to do the same for back-propagation, instead I considered the CPU implementation to be correct and asserted that the CUDA outputs the same result.

5. Trivial bug fixes.

### CODE REVIEW

**Comment by lmoneta** [comment]
Hi Manos, 

Now that we have the Pooling layer PR is merged, can you please fix this conflicts. 
Thanks a lot

Lorenzo

**Comment by steremma** [comment]
Hey Lorenzo!

Certainly, I will start Right now. This PR is considerably more complex and currently includes copy pasted parts from the merged PRs (I had to do it for temporary tests before we had merged them as the convolutional layer depends on them). As a result a simple rebase and conflict fix would be simple, but would also leave a very messy history. What I can do instead is start a new branch from the updated master and carefully choose the new changes with better messages. I should be able to do that within 1-2 days and it will yield a clean history. Unless w are in a big hurry I plan to go with th me second approach but please let me know if you prefer the first one!

**Comment by lmoneta** [comment]
Hi Manos, 

 we are not in a hurry. So please go ahead with your second approach

 Cheers

 Lorenzo

**Comment by steremma** [comment]
As discussed with @lmoneta I opened a new pull request which is rebased against the updated master, fixes conflicts with previous PRs as well as all warnings. Please refer to #2301

**Pull request closed without merging**
