### PR TITLE
[wincxxmodules] Backport D51910 and add stub windows modulemaps

### PR DESCRIPTION
**Pull request by vgvassilev**
This PR should unblock the progress made in #5284

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@gargvaibhav64, could you move your work here. So first we need to enumerate all top-most libc and std headers, in a similar way how it was done for the non-windows modulemap files. This would likely bring you back to the initial error you tried to fix.

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
I think we should find where `_CRT_END_C_HEADER` is defined. If we ask google it may give wrong results, so we should be scanning the msvc files instead. Once we locate the definition we can try adding that header file to the libc_msvc.modulemap (maybe as textual module).

**Comment by gargvaibhav64** [comment]
`_CRT_END_C_HEADER` is also defined in `vcruntime.h`, I tried adding it to libc_msvc.modulemap as a textual header as you suggested, but no success. 
Full error [here](https://pastebin.com/3WupiXjb).

**Comment by vgvassilev** [comment]
Can you show the diff of how you did that?

**Comment by gargvaibhav64** [comment]
```diff
--- a/interpreter/cling/include/cling/libc_msvc.modulemap
+++ b/interpreter/cling/include/cling/libc_msvc.modulemap
@@ -2,6 +2,10 @@ module "libc" [system] [extern_c] [no_undeclared_includes] {
   requires msvc

   export *
+  module "vcruntime.h" {
+    export *
+    textual header "vcruntime.h"
+  }
   module "assert.h" {
     export *
     textual header "assert.h"
```

**Comment by vgvassilev** [comment]
Could you try sticking both in assert? Eg:

```
module "assert.h" {
     export *
     textual header "vcruntime.h"
     textual header "assert.h"
}
```

**Comment by gargvaibhav64** [comment]
I tried doing that, those errors still exist. Full error log [here](https://pastebin.com/Z4vCkbQT).

**Comment by vgvassilev** [comment]
Okay, let's wait @bellenot or @oshadura to greenlight this PR and merge it in the master as it work for all other platforms and then I can try to debug it on a windows machine.

**Comment by vgvassilev** [comment]
@phsft-bot build on ROOT-debian10-i386/cxx14, ROOT-performance-centos7-multicore/default, ROOT-fedora29/python3, ROOT-fedora30/cxx14, ROOT-fedora31/noimt, ROOT-ubuntu16/nortcxxmod, mac1015/cxx17, windows10/cxx14

**Pull request merged**
