### PR TITLE
Adopt upstream llvm-project monorepo directory layout

### PR DESCRIPTION
**Pull request by hahnjo**
This will be required for future LLVM upgrades that rely on a common `cmake/` directory next to `clang/` and `llvm/`.

---

To have any chance at reviewing this change, the mechanical moving is in the first commit and the other two commits are the actual changes (build system, then `llvm-diff` workflow). I will squash the commits on merge because the state after the first commit obviously won't build.

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Looks reasonable to me!

**Comment by Axel-Naumann** [comment]
Before I review and out of curiosity, did you consider `interpreter/llvm`, `interpreter/clang`, `interpreter/cling`,  `interpreter/cmake`, etc? Is that worse because the top-most directory doesn't correspond to upstream anymore?

If so, would `interpreter/llvm-project/llvm` be better than `interpreter/llvm/llvm`, because it's signalling that this is from upstream?

**Comment by hahnjo** [comment]
> Before I review and out of curiosity, did you consider `interpreter/llvm`, `interpreter/clang`, `interpreter/cling`, `interpreter/cmake`, etc? Is that worse because the top-most directory doesn't correspond to upstream anymore?

Yes, and two consequences thereof: (a) I want to avoid a conflict further down the line if LLVM ever puts a `CMakeLists.txt` in their top-level directory, and (b) we had the proposal at some point to replace our copy in `interpreter/llvm/` by a submodule, which requires a directory on its own.

> If so, would `interpreter/llvm-project/llvm` be better than `interpreter/llvm/llvm`, because it's signalling that this is from upstream?

Yes, I'm open to that - I thought about it, but it requires changing a few more paths to `interpreter/llvm/ROOT/` and I was lazy. Btw do we still need those headers with C++ modules? `core/clingutils/CMakeLists.txt` even copies some headers from the build system...

**Comment by hahnjo** [comment]
> Btw do we still need those headers (in `interpreter/llvm/ROOT/`) with C++ modules? `core/clingutils/CMakeLists.txt` even copies some headers from the build system...

ie what breaks with https://github.com/root-project/root/pull/13054 ?

**Comment by Axel-Naumann** [comment]
> it requires changing a few more paths

Never mind then, I don't have a strong enough opinion on this to trigger extra work.

**Review by Axel-Naumann — APPROVED** [review]

**Comment by hahnjo** [comment]
I'm willing to spend that extra work if it's the better layout - it's likely to survive quite some time, so I think it's better not to compromise right now...

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-debian10-i386/soversion, windows10/cxx14

**Comment by hahnjo** [comment]
The warning on `ROOT-debian10-i386/soversion` is unrelated and taken care of by https://github.com/root-project/root/pull/13073

Some Windows machines have problems applying the diff; let's try again:
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
Now everything seems clean, and I will proceed to merge this during the weekend - incremental builds across this change won't work very nicely, I will post a note on Mattermost after it's in.

**Pull request merged**
