### PR TITLE
[RF] RooLagrangianMorphing improvements

### PR DESCRIPTION
**Pull request by cburgard**
# This Pull request:

Adds small improvements to RooLagrangianMorphing and RooPolyFunc.

## Changes or fixes:

 - RooLagrangianMorphing now allows observable names to be controlled more explicitly
 - RooLagrangianMorphing now correctly handles normalization sets
 - RooPolyFunc now provides a method to obtain the function as a string

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by jalopezg-r00t** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
Thank you for these updates, LGTM! I will just combine the commits, push again, run the CI and then merge

**Comment by guitargeek** [comment]
@phsft-bot build

**Pull request merged**
