### PR TITLE
V614 catchup

### PR DESCRIPTION
**Pull request by pcanal**
backport to v6-14 of:

https://github.com/root-project/root/pull/2960
https://github.com/root-project/root/pull/2959

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -Dctest_test_exclude_none=on

**Comment by pcanal** [comment]
ubuntu16/native failed with
```
20:59:22 Caused: java.io.IOException: Remote call on sft-ubuntu-1604-1 failed
20:59:22 	at hudson.remoting.Channel.call(Channel.java:838)
20:59:22 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
20:59:22 	at com.sun.proxy.$Proxy91.withRepository(Unknown Source)
20:59:22 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
```
i.e. git problem of sort.

**Comment by Axel-Naumann** [comment]
This gave an infinite loop on slc6/GCC62: https://epsft-jenkins.cern.ch/job/root-pullrequests-build/47970/consoleFull

**Comment by pcanal** [comment]
On the same machine, I went as far back as 95d8156769 and the problem is 'already' there ... no clue how anything ever worked ... actually isn't that the module build?  should we disable it for v6.14?

**Comment by pcanal** [comment]
windows and 'modules' build failures are unrelated.

**Pull request merged**
