### PR TITLE
Change clang-format settings to avoid if statement and its body on the same line

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Comment by vgvassilev** [comment]
Thanks for doing this. IIRC, that change was planned by @Axel-Naumann.

**Comment by amadio** [comment]
@vgvassilev Yes, I remember that. Unfortunately, it was never merged and I cannot find the PR to merge it either, so I created a new one.

**Comment by amadio** [comment]
@vgvassilev I meant to have a discussion before merging this, but oh well... Let's just hope no one complains. Please ask me before merging in the future. My commit message had a small typo that I intended to fix prior to merging, but I didn't push to avoid triggering an extra build just for that.

**Comment by vgvassilev** [comment]
@amadio, it seems that we already had that discussion. We had consensus about that and it was a matter of who does it (Please see Axel's email). Don't worry about the typo, it is not a precedent.

**Pull request merged**
