### PR TITLE
Fix lazy loading of template specializations

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11/cxx17, mac11arm/cxx17, mac12/cxx17, mac12arm/cxx17, mac13/cxx20, mac13arm/cxx20

**Comment by vgvassilev** [comment]
> Build failed on mac13/cxx20. Running on macphsft21.dyndns.cern.ch:/Users/sftnight/build/workspace/root-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/178636/console).
> ### Failing tests:
> 
>     * [projectroot.roottest.python.distrdf.common.roottest_python_distrdf_common_test_all](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/178636/testReport/projectroot.roottest.python.distrdf/common/roottest_python_distrdf_common_test_all/)
> 
>     * [projectroot.roottest.python.distrdf.dask.roottest_python_distrdf_dask_test_all](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/178636/testReport/projectroot.roottest.python.distrdf/dask/roottest_python_distrdf_dask_test_all/)
> 
>     * [projectroot.roottest.python.distrdf.spark.roottest_python_distrdf_spark_test_all](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/178636/testReport/projectroot.roottest.python.distrdf/spark/roottest_python_distrdf_spark_test_all/)

I believe we need to put a `cling::Interpreter::PushTransactionRAII` in `cling::ParseProto::Parse` because with the new patch we might trigger a deserialization.

**Comment by hahnjo** [comment]
> I believe we need to put a `cling::Interpreter::PushTransactionRAII` in `cling::ParseProto::Parse` because with the new patch we might trigger a deserialization.

Ok, not sure I fully understand what you propose... Can you add this change before the final "fixup" commit? You can push to the PR, right, or do I need to enable this somehow?

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11/cxx17, mac11arm/cxx17, mac12/cxx17, mac12arm/cxx17, mac13/cxx20, mac13arm/cxx20 with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by hahnjo** [comment]
@phsft-bot build with flags -Druntime_cxxmodules=OFF -DCTEST_TEST_EXCLUDE_NONE=ON

**Review by vgvassilev — APPROVED** [review]
That's really a great job, @hahnjo!

**Pull request merged**
