### PR TITLE
multiproc: Exit worker without cleanup

### PR DESCRIPTION
**Pull request by hahnjo**
This intends to solve issues when a spawned thread, while the main thread calls `fork()`, holds a lock that is needed during shutdown.
Such situation can happen in two cases for roottest:
 * In `tExecutor`, there are still threads from TBB around that can call into `tbbmalloc` while `TProcessExecutor` calls `fork()`, leading to a hang during shutdown where the library is repeatedly calling `sched_yield()`.
 * On Mac, there is a `com.apple.NSEventThread`. This can lead to hangs during shutdown of `libdispatch`, even in `processExecutor` that is not spawning threads itself.

### CODE REVIEW

**Comment by eguiraud** [comment]
Thanks Jonas! We might have to call some ROOT clean-up routine that is usually called by the ROOT-injected exit handler to make sure TFiles are closed correctly and similar. @pcanal might know if there is a simple way to do that.

**Comment by hahnjo** [comment]
> Thanks Jonas! We might have to call some ROOT clean-up routine that is usually called by the ROOT-injected exit handler to make sure TFiles are closed correctly and similar. @pcanal might know if there is a simple way to do that.

I think that's `gSystem->Exit(0)` that was used before. You can pass a second parameter (called `mode` and effectively undocumented AFAICT) that makes it call `_exit()` instead of `exit()`. However, I'm not sure if we need to close `TFile`s because the workers don't open them, the parent should handle them.

**Comment by pcanal** [comment]
I indeed see in the man page for pthread_atfork(3)  http://manpages.courier-mta.org/htmlman3/pthread_atfork.3.html
```
When fork(2) is called in a multithreaded process, only the calling thread is duplicated in the child process. The original intention of pthread_atfork() was to allow the calling thread to be returned to a consistent state. For example, at the time of the call to fork(2), other threads may have locked mutexes that are visible in the user-space memory duplicated in the child. Such mutexes would never be unlocked, since the threads that placed the locks are not duplicated in the child. The intent of pthread_atfork() was to provide a mechanism whereby the application (or a library) could ensure that mutexes and other process and thread state would be restored to a consistent state. In practice, this task is generally too difficult to be practicable.

After a fork(2) in a multithreaded process returns in the child, the child should call only async-signal-safe functions (see signal-safety(7)) until such time as it calls execve(2) to execute a new program.
```

**Comment by pcanal** [comment]
So we do have a real problem but where I am confused is "if our failure case is due to unlocked locks in the child process" why is it seen only at tear down? I.e. would the very first use of the lock resources be already held back.

If using `_exit` is the workaround (solution?) then this means that no cleanup can be executed (even-though it might be needed).

> However, I'm not sure if we need to close TFiles because the workers don't open them

Do we have complete control over what the child process executes (i.e. no user code whatsoever?)

**Comment by hahnjo** [comment]
> So we do have a real problem but where I am confused is "if our failure case is due to unlocked locks in the child process" why is it seen only at tear down? I.e. would the very first use of the lock resources be already held back.

Yes, any of the libraries might block if called. And my understanding is (see below) that it's only their `atexit` handlers that get us into trouble, at least for sane code.

> If using `_exit` is the workaround (solution?) then this means that no cleanup can be executed (even-though it might be needed).
> 
> > However, I'm not sure if we need to close TFiles because the workers don't open them
> 
> Do we have complete control over what the child process executes (i.e. no user code whatsoever?)

We are executing user code, but only what was passed in for `Map`, `MapReduce`, and `Reduce` (as far as I understand). Now they could do nasty things in there like opening more files... That said, I can give `gSystem->Exit(0, kFALSE)` a try to shutdown ROOT cleanly and then call `_exit(0)`, but I don't see a way to run `atexit` handlers.

**Comment by pcanal** [comment]
What are I still trying to understand is whether it is really a property of the atexit (for that to be true it would need to be a lock that is specific to the atexit mechanism itself and/or of *only* the atexit callback used) or a more generic case that just happens to not happen *by chance* in our examples.

**Comment by pcanal** [comment]
With the example below, I see that the locking fails *also* if the lock is taken outside of the atexit.  The "deadlock" child is stuck at:
```
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0x55b728655040 <mutex>, private=0) at lowlevellock.c:52
#1  0x00007fe1a3a540a3 in __GI___pthread_mutex_lock (mutex=0x55b728655040 <mutex>) at ../nptl/pthread_mutex_lock.c:80
#2  0x000055b7286523ae in main () at fail02.cxx:41
```
with the source file
```
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

static pthread_mutex_t mutex;

void *thread_start(void *arg) {
  pthread_mutex_lock(&mutex);
  // work...
  sleep(2);
  pthread_mutex_unlock(&mutex);
  return NULL;
}

void shutdown() {
  pthread_mutex_lock(&mutex);
  // shutdown...
  pthread_mutex_unlock(&mutex);
}

int main() {
  pthread_mutex_init(&mutex, NULL);
  atexit(&shutdown);

  pthread_t thread;
  pthread_create(&thread, NULL, &thread_start, NULL);

  sleep(1);

  pid_t pid = fork();
  if (pid == -1) {
    fputs("could not fork!\n", stderr);
    exit(1);
  }

  if (pid == 0) {
    // child
    // Take the lock before doing anything
    pthread_mutex_lock(&mutex);
    // work...
    //sleep(2);
    pthread_mutex_unlock(&mutex);

    exit(0);
  } else {
    // parent
    waitpid(pid, NULL, 0);
  }

  pthread_join(thread, NULL);

  return 0;
}
```

**Comment by pcanal** [comment]
I.e. it seems that we can not fork if any thread is doing anything else (because that something else might be taking any fundamental locks (malloc, ROOT, dlopen, etc...)

**Comment by hahnjo** [comment]
> I.e. it seems that we can not fork if any thread is doing anything else (because that something else might be taking any fundamental locks (malloc, ROOT, dlopen, etc...)

Yep, which is why (as you quoted earlier):
> After a fork(2) in a multithreaded process returns in the child, the child should call only async-signal-safe functions (see signal-safety(7)) until such time as it calls execve(2) to execute a new program.

ie, no locks and things like that.

Now, we can guarantee for ROOT's own source code that we're not interacting with threads, in particular that the actions performed in the workers after `fork()` are safe, require no locks and don't result in calls to an external library. What we cannot guarantee is what libraries did before / during the `fork()` and what consequences this has for their `atexit` handlers.

**Comment by pcanal** [comment]
>  require no locks and 

For ROOT we can (try to) disable thread safety.

> , require no locks and don't result in calls to an external library. 

but that also technically (maybe) include malloc ... that one might be hard to avoid ...

And it also preclude executing any user code in the workers ....

> What we cannot guarantee ....

Yes and because of that it can not reliably work (unless there is no active thread when we fork).

**Comment by hahnjo** [comment]
> > , require no locks and don't result in calls to an external library.
> 
> but that also technically (maybe) include malloc ... that one might be hard to avoid ...

True, `malloc` is not async-signal-safe. I haven't been able to race calls of `malloc()` against `fork()`, but that doesn't mean anything.

> And it also preclude executing any user code in the workers ....
> 
> > What we cannot guarantee ....
> 
> Yes and because of that it can not reliably work (unless there is no active thread when we fork).

So to play it safe, we would need to remove `TProcessExecutor` or come up with a scheme that calls `exec`. However that one replaces the entire process image, including the input data and the user-provided function...

**Comment by eguiraud** [comment]
> we would need to remove TProcessExecutor

It has always been the case that forking from a multi-thread program is dangerous/broken.
Usage of `TProcessExecutor` is fine as long as the program is not multi-thread.
On Linux, that's totally fine, users are in charge of whether their program is multi-threaded or not.
I don't understand whether Mac makes your applications multi-thread with no warning or not.

**Comment by hahnjo** [comment]
> On Linux, that's totally fine, users are in charge of whether their program is multi-threaded or not.

Okay, then we should change the `tExecutor` test to make sure that all threads are joined before `fork`ing.

> I don't understand whether Mac makes your applications multi-thread with no warning or not.

My understanding is that yes, `com.apple.NSEventThread` is always started. Who's our Mac expert, @Axel-Naumann ? If that's the case, should we disable `TProcessExecutor` on Mac?

**Comment by Axel-Naumann** [comment]
Can we first try with joining? We only see multiproc failures on Macs since very recently - before disabling it altogether I'd prefer to give your fix a try.

**Comment by hahnjo** [comment]
> Can we first try with joining? We only see multiproc failures on Macs since very recently - before disabling it altogether I'd prefer to give your fix a try.

Ok, I'll prepare a PR for `roottest`. However, joining will only help for `tExecutor` which also fails on Linux (esp. `i386`, due to resource contention I suppose). `processExecutor` is failing since a longer time, https://github.com/root-project/root/pull/6800#issuecomment-726714882 is also on Mac.

**Comment by hahnjo** [comment]
> Ok, I'll prepare a PR for `roottest`.

No, doesn't work as I had hoped: When the global `RTaskArenaWrapper` gets destroyed, taking `fTBBArena` with it, the worker threads stay around. In the current implementation, there seems no way to go back to single-threaded after using `TThreadExecutor` once. It's possible that TBB has functions to join the threads, but I'm no expert here.

**Comment by eguiraud** [comment]
We can always split the test in two, one part that runs multiple threads, the other that runs multiple processes.
The issue remains with MacOS spawning threads on its own...

**Comment by hahnjo** [comment]
> We can always split the test in two, one part that runs multiple threads, the other that runs multiple processes.
> The issue remains with MacOS spawning threads on its own...

Sure, that solves the problem for our tests. But how likely is it that users will attempt something similar? If there's only the slightest chance, that's not a trap that we should leave around IMHO. The issue is too subtle, doesn't happen on every execution and this makes it very hard to debug...

**Comment by eguiraud** [comment]
Talking about Linux, where the OS doesn't make your application multi-threaded under your feet: `fork`ing a multi-thread program is bad, that's always been the case. We can and should warn users in the docs, but apart from that I'm not sure what we can do?

**Comment by hahnjo** [comment]
As discussed, this is still not enough to fully protect against all possible cases in multi-threaded programs.

**Pull request closed without merging**
