### PR TITLE
Jsmva issues

### PR DESCRIPTION
**Pull request by ellert**
The Fedora Packaging Guidelines some time ago added a section on packaging javascript files. This section says that minified scripts should be treated as compiled code. And like for programs written in other languages, pre-compiled code that is part of the sources must not be used in packaging, but must be regenerated from sources during the package build. I recently implemented these guidelines in the root package and found some issues.

This pull request has three commits.

1) The word "default" is a reserved word in the language, and when used as a key in a dictionary it must be quoted. The yuicompressor minifier complains about this:
```
$ yuicompressor etc/notebook/JsMVA/js/DecisionTree.js 
[ERROR] in etc/notebook/JsMVA/js/DecisionTree.js
  57:24:invalid property id
```
2. In one place (and one place only) in the script a construct from a very new version of the javascript standard is used for defining default values to function parameters. This unnecessarily makes the code incompatible with old browsers. It also makes it hard to run the minification during the package build as both yuicompressor and uglufyjs choke on it.
```
$ yuicompressor etc/notebook/JsMVA/js/NeuralNetwork.js 
[ERROR] in etc/notebook/JsMVA/js/NeuralNetwork.js
  509:75:missing ) after formal parameters
```
```
$ uglifyjs etc/notebook/JsMVA/js/NeuralNetwork.js  -c -m
Parse error at etc/notebook/JsMVA/js/NeuralNetwork.js:509,73
 = function (divid, netobj, oldStructure=false) {
                                        ^
SyntaxError: Unexpected token operator «=», expected punc «,»
```
3. The code has not been updated to reflect changes in jsroot. The code still tries to load d3.v3.min.js from jsroot. In the current version of jsroot the d3 script has been updated to version 4 and the file is now called d3.min.js. The pull request changes the name of the file in the two places where it is referenced, so it should now find the file. However this change is incomplete since the d3 API changes between the versions and some porting is needed.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by etejedor** [comment]
@ashlaban among the fixes of this PR, there is one related to the d3 issue in JsMVA you are currently fixing. Can you have a look? Perhaps you can also incorporate the other fixes.

**Comment by ashlaban** [comment]
For reference: Parts of these changes are included in PR#2353.

**Comment by ashlaban** [comment]
As @ellert points out, we need to port jsmva to d3 v4 that jsroot uses. Right now jsmva is basically unusable; Most of it's functionality depends on d3. Incorporating this PR will allow most of jsmva functionality to run, but a few things will be missing due to an api change.

I suggest to integrate this PR as is and provide the update to the rest of jsmva in a separate PR (unless you @ellert would volunteer to update this PR).

Details (and for future reference):
There are a few places of jsmva that should be updated to run under d3.v4. The swan example 
`https://cern.ch/swanserver/cgi-bin/go?projurl=https://raw.githubusercontent.com/iml-wg/tmvatutorials/master/TMVAinJupyter_FullTutorial.ipynb` shows what is broken.

The problems arise when calling:
- BookDNN (interactive design of DNN's; does not render)
- DrawNerualNetowork (visualising NN's; does not render)
- DrawDecisionTree (visualising BDT's; does not render)
- DrawCutEfficiencies (curves come up in grayscale, should be in color)

List of changes for 3 -> 4 can be found here: https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-40. Important ones to note are:
- d3.svg.line -> d3.line
- d3.svg.diagonal -> _removed_

**Comment by lmoneta** [comment]
I think then we can finally merge this now, and having further changes in a separate PR. 
Sorry for having missed this one

**Pull request merged**
