### PR TITLE
Fix in Cocoa. XSGui crashed on Mac M1

### PR DESCRIPTION
**Pull request by couet**
Patch proposed by Timur

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
This patch on a M1 machine is working.
The “periodic” example does not crash anymore.

**Review by linev — APPROVED** [review]
I hope, it works properly also on previous Mac versions

**Comment by couet** [comment]
Yes I tried also on Intel... it is fine too.

**Pull request merged**
