### PR TITLE
[RF] Don't support `proof` anymore in RooFit and RooStats

### PR DESCRIPTION
**Pull request by guitargeek**
The PROOF interface in RooFit/RooStats didn't work anymore for a long time (at least since ROOT 6.30.00 when the test statistic classes were made not serializable), so nobody will be suprised if this is removed.

### CODE REVIEW

**Comment by dpiparo** [comment]
Great simplification, which matches well the PROOF=OFF by default in master: thanks. This is not very important, but could users rely on some other sort of parallelism, e.g. T{Thread/Process}Executor?

**Comment by ferdymercury** [comment]
Thanks! Related: maybe it's good to remove also TProof and other deprecated features from the roofit tutorials. Right now, many are failing while building the docu, see:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/lastBuild/console

things like:
```
warning: 'createIterator' is deprecated: will be removed in ROOT v6.34: begin(), end() and range-based for loops. 
use of undeclared identifier 'TProofLite' because of inc/RooStats/ProofConfig.h:            int nMaxWorkers = gROOT->ProcessLineFast("TProofLite::GetNumberOfWorkers()");
Warning in <ROOT::Math::Fitter::CalculateHessErrors>: Error when calculating Hessian
 *** Break *** segmentation violation
```

**Comment by guitargeek** [comment]
Hi @ferdymercury, that's what I did in this PR. Or was there something I missed?

**Comment by ferdymercury** [comment]
Oh right, sorry!
I think the only thing missing would be to replace the deprecated createIterator functions in two or three files under tutorials.
grep -r createIterator tutorials/

**Comment by guitargeek** [comment]
> Oh right, sorry! I think the only thing missing would be to replace the deprecated createIterator functions in two or three files under tutorials. grep -r createIterator tutorials/

Thanks I get it now! I have opened a PR, feel free to review if you have time:
https://github.com/root-project/root/pull/15024

**Review by couet — APPROVED** [review]

**Pull request merged**
