### PR TITLE
Fix GCC10 / recursive AST reading (ROOT-10849)

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Backport (and adapt) llvm-svn 331428 plus required prerequisites.

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Could you also revert the custom fixes in that area?

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora32/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora32/cxx17

**Comment by Axel-Naumann** [comment]
Fedora32 has "unrelated" issues that become visible only after this PR.

The other builds failed to upload their (successful) test results to CDash, i.e. they really passed.

**Comment by pcanal** [comment]
@Axel-Naumann Should we expect all PR to now fail to run on Fedora32?

**Comment by Axel-Naumann** [comment]
Only if they ran on Fedora32 which they don't :-)

**Pull request merged**
