### PR TITLE
[TMVA][SOFIE] Support for Conv layer in PyTorch Parser

### PR DESCRIPTION
**Pull request by sanjibansg**
This PR adds support for parsing Convolution layers from PyTorch models into an RModel object.

Progress
- [x] Support for PyTorch Convolution Layers (Conv2D)
- [x] Tests

### CODE REVIEW

**Review by lmoneta — CHANGES_REQUESTED** [review]
2 python files have been deleted, 
tmva/pymva/test/generatePyTorchModelModule.py and tmva/pymva/test/generatePyTorchModelModule.py

You need to remove the corresponding  lines in tmva/pymva/test/CMakeLists.txt that copy teh files from the source to the binary directory using the `configure_file` command.

**Comment by lmoneta** [comment]
After fixing the CMake file, I am getting this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Model file PyTorchModelConvolution.pt not found!
Aborted (core dumped)
make[2]: *** [tmva/pymva/test/CMakeFiles/SofieCompileModels_PyTorch.dir/build.make:77: SofieCompileModels_PyTorch] Error 134
make[1]: *** [CMakeFiles/Makefile2:55168: tmva/pymva/test/CMakeFiles/SofieCompileModels_PyTorch.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
```

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default,  ROOT-ubuntu18.04/defaultwith flags -Dtmva-sofie=On

**Review by lmoneta — APPROVED** [review]
Looks fine to me!
Do you want maybe to squash some commits together for a better history ?
We can also squash all commits together in a single one

**Comment by sanjibansg** [comment]
> Looks fine to me! Do you want maybe to squash some commits together for a better history ? We can also squash all commits together in a single one

Yes it'd be good to squash the commits to have a better git history

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/defaultwith flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Pull request merged**
