### PR TITLE
[doxy] precompile libs script

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:

Precompiles C++ script to potentially speedup (slightly) documentation building

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by couet** [comment]
Yes it works. I am not sure if it really speed up the execution a lot. But why not doing it this may. Have you done some speed up measurement ? Note we also have more .C macros: `MakeRCanvasJS.C`, `MakeTCanvasJS.C` and `makeimage.C`

**Review by couet — APPROVED** [review]
It works. I merge. Potentially should it be done also for the other .C macros ?

**Comment by ferdymercury** [comment]
> Yes it works. I am not sure if it really speed up the execution a lot. But why not doing it this may. Have you done some speed up measurement ? Note we also have more .C macros: `MakeRCanvasJS.C`, `MakeTCanvasJS.C` and `makeimage.C`

Sorry, I didn't see this message. I did not do speed-up measurements.

Concerning makeimage and the others, I tried once and saw some problems when enabling multihreading, not sure why, so I did not look into it further.

**Comment by ferdymercury** [comment]
Related: https://github.com/root-project/root/commit/d8d71f4e92a2fb51ec6c2b2ac78d803ea7588569

**Pull request merged**
