### PR TITLE
DO NOT MERGE! Test PR builds for root7, this should trigger a warning.

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by linev** [comment]
@Axel-Naumann 
Actually, you create error.
But let see if error will be seen on any platform.

**Comment by linev** [comment]
Build on Mac is green!

**Comment by Axel-Naumann** [comment]
Mac has:
```
14:54:13 [7604/10184] Building CXX object gui/webdisplay/CMakeFiles/G__ROOTWebDisplay.dir/G__ROOTWebDisplay.cxx.o
14:54:13 In file included from gui/webdisplay/G__ROOTWebDisplay.cxx:42:
14:54:13 /build/jenkins/workspace/root-pullrequests-build/root/gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx:88:27: warning: unused parameter 'UNUSED' [-Wunused-parameter]
14:54:13    std::string GetUrl(int UNUSED) const { return fUrl; }
14:54:13                           ^
14:54:13 1 warning generated.
```
I need to fix the log parser.

**Comment by linev** [comment]
By chance, method is never used, therefore it is just a warning.

**Comment by linev** [comment]
We need one Mac, one Linux and one Windows platform where root7 always on.

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
> We need one Mac, one Linux and one Windows platform where root7 always on.

That's what we now have.

**Comment by Axel-Naumann** [comment]
OK, PRs are fixed.

**Pull request closed without merging**
