### PR TITLE
[PyROOT] Prevent construction of aggregate initializer for std::tuple

### PR DESCRIPTION
**Pull request by aaronj0**
Prevents failures induced by #16338 for python3.8

### CODE REVIEW

**Review by vepadulano — APPROVED** [review]
The change looks good to me, if the CI failures are understood/unrelated. Just for clarification, is there a way to test this specifically? Or it is easily visible but we don't have a Python 3.8 runner in the CI?

**Comment by aaronj0** [comment]
> The change looks good to me, if the CI failures are understood/unrelated. Just for clarification, is there a way to test this specifically? Or it is easily visible but we don't have a Python 3.8 runner in the CI?

Hi, @hahnjo was able to reproduce this on python3.8. It should be more visible if we had a python3.8 runner, but this does not error out on newer python versions.

The stack trace points to TCling not handling `void init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}` which is an incorrectly constructed aggregate initialization constructor. I would prefer if this could be tested before merging if @hahnjo can apply this commit on his platform and confirm that `roottest-python-basic-datatype` and `roottest-python-cpp-cpp11` start to pass

**Comment by hahnjo** [comment]
> > The change looks good to me, if the CI failures are understood/unrelated. Just for clarification, is there a way to test this specifically? Or it is easily visible but we don't have a Python 3.8 runner in the CI?
> 
> Hi, @hahnjo was able to reproduce this on python3.8. It should be more visible if we had a python3.8 runner, but this does not error out on newer python versions.

Actually I noticed on Friday that we have Python 3.8 in our `alma8` image. I don't know why it's not visible there...

> The stack trace points to TCling not handling `void init_tuple_string_unsigned_long_(tuple<string,unsigned long>*& self, const unsigned long& _1 = 0, const string& _0 = string{}` which is an incorrectly constructed aggregate initialization constructor. I would prefer if this could be tested before merging if @hahnjo can apply this commit on his platform and confirm that `roottest-python-basic-datatype` and `roottest-python-cpp-cpp11` start to pass

I re-checked that the two tests are still failing on `master` for my local configuration and can confirm that this PR fixes them, getting me back to a fully green test result :smiley:

**Comment by hahnjo** [comment]
@aaronj0 @guitargeek can we merge this PR?

**Pull request merged**
