### PR TITLE
THistPainter fixes, ROOT-9655

### PR DESCRIPTION
**Pull request by dajiaonao**
Hi,
I'm trying to add a patch to address the issue here: https://sft.its.cern.ch/jira/browse/ROOT-9655.
There are two features:
1) using the default option, TPaletteAxis will have the same range as the early histogram that the current histogram is normalized to, and thus the correct palette;
2) New options "SAME0" and "SAMES0" to allow opting out of the default normalization.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by couet** [comment]
I see in your PR comments that you implemented two new options in THistPainter. But in the code modifications you did I do not see any description of these new options in the help part. Can you also post an example showing these options in action ?

**Comment by dajiaonao** [comment]
Here is an example comparing the new options "SAME0" and "SAMES0" (on the right side) to the default one "SAME" and "SAMES" (on the left) [test1.C.txt](https://github.com/root-project/root/files/2680271/test1.C.txt), the options are printed on the plots.

And here is how they look from my locally complied version:
c1

Note that, even the "default" options, there is a fix applied to show the correct range in the palette axises.
Without this fix, i.e, in the root-6.14/08, they look this:
c2

I actually forgot to update the help document. Sorry...shall I add it in a new commit, or maybe you prefer to do it to make sure it's well integrated with other parts?

**Comment by couet** [comment]
You can continue to modify this PR and document this new option in the header of THistPainter. and include an example in the help.

**Comment by dajiaonao** [comment]
> I see in your PR comments that you implemented two new options in THistPainter. But in the code modifications you did I do not see any description of these new options in the help part. Can you also post an example showing these options in action ?

It's added. Please take a look if it's fine.

**Comment by couet** [comment]
Thanks for the update. I have still one question/worry. How the '0' of your new option SAME0 will work when combined with some other options allowing also 0 (like colz0)? Imagine the following option "SAME COLZ0"... COLZ0 is valid. That may be misunderstood with your new code ?

**Comment by dajiaonao** [comment]
> Thanks for the update. I have still one question/worry. How the '0' of your new option SAME0 will work when combined with some other options allowing also 0 (like colz0)? Imagine the following option "SAME COLZ0"... COLZ0 is valid. That may be misunderstood with your new code ?

I actually just followed the COL1 example in the existing code. If I understand correctly, the code will find the "SAME" first, and then check if there is a 0 immediately after it. The similar thing is done for the "COLZ" option. So it can distinguish "SAME0 COLZ" and "SAME COLZ0". This is also confirmed by a quick test of the code.

**Comment by couet** [comment]
Ok fine if you checked it works. I am in something else right now> I will come back to you code asap

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
Many thanks for this PR. It is now in place.
Cheers
Olivier

**Pull request merged**
