### PR TITLE
[RF] Fix streamer info warnings in RooFit

### PR DESCRIPTION
**Pull request by guitargeek**
This PR is to address GitHub issue https://github.com/root-project/root/issues/9353.

So far, it is only a revert of d91509e so I can see the failures in the CI (on my system, the RooFit tests are still passing even after reverting said commit).

### CODE REVIEW

**Review by lmoneta — APPROVED** [review]

**Comment by pcanal** [comment]
> projectroot.roofit.roofit.test.gtest_roofit_roofit_test_testRooExponential

```
C:\build\workspace\root-pullrequests-build\root\test\unit_testing_support\ROOTUnitTestSupport.cxx(70): error: Failed
Received unexpected diagnostic of severity 2000 at 'TStreamerInfo::CompareContent' reading 'The following data member of
the on-file layout version 1 of class 'RooSTLRefCountList<RooAbsArg>' differs from 
the in-memory layout version 1:
   vector<unsigned long> _refCount; //
vs
   vector<unsigned int> _refCount; //'.
```

The problem stems wrong:
```
std::vector<std::size_t> _refCount;
```
where ROOT does not (yet) make the std:*_t type opaque and thus sees different types on different platforms (and `long` is stored with 64 bits, `int` is stored with 32 bits, so here the 2 schema are indeed different).  

Using `unsigned long` instead of `std::size_t` should solve the problem.

**Comment by guitargeek** [comment]
Hi @pcanal, thanks a lot for commenting! Okay so I need to change the type. Just to make sure, do I still need to increase the class version too?

**Comment by pcanal** [comment]
You do need to increase the version number.  This is because, a priori, there is file written with both alternative of version 1 (when written from Windows or from Linux) and increasing the number would let the automatic schema evolution kick-in when reading file written with the 'wrong' alternative.

**Comment by guitargeek** [comment]
Alright @pcanal, then I know now that to do! Thanks again.

**Comment by pcanal** [comment]
[This may or may not apply here].  Remember to also increment the class version of any class derived from the 2 you changed here.

**Comment by guitargeek** [comment]
Fortunately there are no derived classes of these. Great, so then this PR is good to go!

**Pull request merged**
