### PR TITLE
Add diagnostics to debug broken initialization of TCling

### PR DESCRIPTION
**Pull request by amadio**
**Please do not merge this branch, it is for testing only!**

### CODE REVIEW

**Comment by amadio** [comment]
Stack trace when I have these changes in:
```
[ 67%] Generating G__MathCore.cxx, ../../lib/libMathCore_rdict.pcm, ../../lib/libMathCore.rootmap
ROOT::AddClass("") : N4ROOT6Detail10TTypedIterI10TBaseClassEE
ROOT::AddClass("") : N4ROOT8Internal34TCheckHashRecurveRemoveConsistencyE
ROOT::AddClass("") : N4ROOT6Detail10TTypedIterI13TEnumConstantEE
ROOT::AddClass("") : 19TViewPubDataMembers
ROOT::AddClass("") : 17TViewPubFunctions
ROOT::AddClass("") : N4ROOT11TRWMutexImpI6TMutexNS_8Internal13RecurseCountsEEE
ROOT::AddClass("") : N4ROOT11TRWMutexImpINS_10TSpinMutexENS_8Internal13RecurseCountsEEE
ROOT::AddClass("") : N4ROOT11TRWMutexImpI6TMutexNS_8Internal22UniqueLockRecurseCountEEE
ROOT::AddClass("") : N4ROOT11TRWMutexImpINS_10TSpinMutexENS_8Internal22UniqueLockRecurseCountEEE
ROOT::AddClass("") : N4ROOT6Detail10TTypedIterI10TBaseClassEE
ROOT::AddClass("") : N4ROOT8Internal34TCheckHashRecurveRemoveConsistencyE
Fatal in <TClassTable::Add>: Trying to add class with empty name to TClassTable
aborting
#0  0x00007fa7e57aacbe in __GI___waitpid (pid=32048, stat_loc=stat_loc
entry=0x7fffab271828, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007fa7e572138f in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007fa7e67b9c4f in TUnixSystem::StackTrace (this=0x7d30) at /home/amadio/src/root/core/unix/src/TUnixSystem.cxx:2412
#3  0x00007fa7e66900e8 in DefaultErrorHandler (level=32048, abort_bool=40, location=0x0, msg=0x7fa7e57aacbe <__GI___waitpid+46> "H=") at /home/amadio/src/root/core/base/src/TError.cxx:192
#4  0x00007fa7e668ff16 in ErrorHandler (level=32048, location=0x7fffab271828 "", fmt=0x0, ap=0x7fa7e57aacbe <__GI___waitpid+46>) at /home/amadio/src/root/core/base/src/TError.cxx:251
#5  0x00007fa7e668fb04 in Fatal (location=0x7d30 <error: Cannot access memory at address 0x7d30>, fmt=0x7fffab271828 "") at /home/amadio/src/root/core/base/src/TError.cxx:350
#6  0x00007fa7e67058b2 in TClassTable::Add (cname=0x7d30 <error: Cannot access memory at address 0x7d30>, id=6184, info=..., dict=0x7fa7e57aacbe <__GI___waitpid+46>, pragmabits=-441829952) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:350
#7  0x00007fa7e6704da5 in ROOT::AddClass (cname=0x7d30 <error: Cannot access memory at address 0x7d30>, id=6184, info=..., dict=0x7fa7e57aacbe <__GI___waitpid+46>, pragmabits=-441829952) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:761
#8  0x00007fa7e6704b94 in TClassTable::TClassTable (this=0x7d30) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:236
#9  0x00007fa7e6588e34 in TROOT::InitInterpreter (this=0x7d30) at /home/amadio/src/root/core/base/src/TROOT.cxx:2020
#10 0x00007fa7e6587ffc in ROOT::Internal::GetROOT2 () at /home/amadio/src/root/core/base/src/TROOT.cxx:385
#11 0x00007fa7e7f86986 in TCling__GetInterpreter () at /home/amadio/src/root/core/metacling/src/rootclingTCling.cxx:48
#12 0x00007fa7e7ea51d5 in RootClingMain (argc=98, argv=0x7fffab271828, isDeep=false, isGenreflex=190) at /home/amadio/src/root/core/dictgen/src/rootcling_impl.cxx:4333
#13 0x00007fa7e7e9dd43 in ROOT_rootcling_Driver (argc=32048, argv=0x7fffab271828, config=...) at /home/amadio/src/root/core/dictgen/src/rootcling_impl.cxx:6091
#14 0x00000000004027a8 in main (argc=32048, argv=0x7fffab271828) at /home/amadio/src/root/main/src/rootcling.cxx:44
Child aborted
gmake[2]: *** [math/mathcore/CMakeFiles/G__MathCore.dir/build.make:213: math/mathcore/G__MathCore.cxx] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:19283: math/mathcore/CMakeFiles/G__MathCore.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
```

**Comment by amadio** [comment]
Another stack trace:
```
Error in ROOT::AddClass(): adding class with no name when real name is N4ROOT8Internal34TCheckHashRecurveRemoveConsistencyE
Fatal in <TClassTable::Add>: Trying to add class with empty name to TClassTable
aborting
#0  0x00007f888f092cbe in __GI___waitpid (pid=32497, stat_loc=stat_loc
entry=0x7ffea63dbc28, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f888f00938f in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f88900a1c0f in TUnixSystem::StackTrace (this=0x7ef1) at /home/amadio/src/root/core/unix/src/TUnixSystem.cxx:2412
#3  0x00007f888ff780e8 in DefaultErrorHandler (level=32497, abort_bool=40, location=0x0, msg=0x7f888f092cbe <__GI___waitpid+46> "H=") at /home/amadio/src/root/core/base/src/TError.cxx:192
#4  0x00007f888ff77f16 in ErrorHandler (level=32497, location=0x7ffea63dbc28 "", fmt=0x0, ap=0x7f888f092cbe <__GI___waitpid+46>) at /home/amadio/src/root/core/base/src/TError.cxx:251
#5  0x00007f888ff77b04 in Fatal (location=0x7ef1 <error: Cannot access memory at address 0x7ef1>, fmt=0x7ffea63dbc28 "") at /home/amadio/src/root/core/base/src/TError.cxx:350
#6  0x00007f888ffed889 in TClassTable::Add (cname=0x7ef1 <error: Cannot access memory at address 0x7ef1>, id=-17368, info=..., dict=0x7f888f092cbe <__GI___waitpid+46>, pragmabits=-1892108864) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:347
#7  0x00007f888ffecd91 in ROOT::AddClass (cname=0x7ef1 <error: Cannot access memory at address 0x7ef1>, id=-17368, info=..., dict=0x7f888f092cbe <__GI___waitpid+46>, pragmabits=-1892108864) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:751
#8  0x00007f888ffecb94 in TClassTable::TClassTable (this=0x7ef1) at /home/amadio/src/root/core/cont/src/TClassTable.cxx:236
#9  0x00007f888fe70e34 in TROOT::InitInterpreter (this=0x7ef1) at /home/amadio/src/root/core/base/src/TROOT.cxx:2020
#10 0x00007f888fe6fffc in ROOT::Internal::GetROOT2 () at /home/amadio/src/root/core/base/src/TROOT.cxx:385
#11 0x00007f889186eab6 in TCling__GetInterpreter () at /home/amadio/src/root/core/metacling/src/rootclingTCling.cxx:48
#12 0x00007f889178d1d5 in RootClingMain (argc=27, argv=0x7ffea63dbc28, isDeep=false, isGenreflex=190) at /home/amadio/src/root/core/dictgen/src/rootcling_impl.cxx:4333
#13 0x00007f8891785d43 in ROOT_rootcling_Driver (argc=32497, argv=0x7ffea63dbc28, config=...) at /home/amadio/src/root/core/dictgen/src/rootcling_impl.cxx:6091
#14 0x00000000004027a8 in main (argc=32497, argv=0x7ffea63dbc28) at /home/amadio/src/root/main/src/rootcling.cxx:44
```

**Comment by pcanal** [comment]
the problem is likely to be either at
https://github.com/root-project/root/blob/2b690ee44992d58fcea38271fe689699ca6ea176/core/meta/src/TGenericClassInfo.cxx#L29
or
https://github.com/root-project/root/blob/5d451b1b6c28b77baf626583f891ed921dc23012/core/base/inc/Rtypes.h#L210

i.e the type name deduction/extraction.

**Comment by amadio** [comment]
> the problem is likely to be either at
> https://github.com/root-project/root/blob/2b690ee44992d58fcea38271fe689699ca6ea176/core/meta/src/TGenericClassInfo.cxx#L29

Seriously, what kind of error handling is that!?

Here is what I get now:
```
[ 67%] Generating G__MathCore.cxx, ../../lib/libMathCore_rdict.pcm, ../../lib/libMathCore.rootmap
Failed to deduce type for 'static std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ROOT::Internal::TTypeNameExtraction<T>::Get() [with T = ROOT::Detail::TTypedIter<TBaseClass>]'
Child aborted
gmake[2]: *** [math/mathcore/CMakeFiles/G__MathCore.dir/build.make:213: math/mathcore/G__MathCore.cxx] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:19283: math/mathcore/CMakeFiles/G__MathCore.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
```

**Comment by amadio** [comment]
And after I revert d8383fcb0a66e33ea7a8c8c78032d21f062e4f22, I get this:

```
[ 67%] Generating G__MathCore.cxx, ../../lib/libMathCore_rdict.pcm, ../../lib/libMathCore.rootmap
Failed to deduce type for 'static std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ROOT::Internal::TTypeNameExtraction<T>::Get() [with T = ROOT::Detail::TTypedIter<TBaseClass>]'
Deduced type is 'T'
Child aborted
gmake[2]: *** [math/mathcore/CMakeFiles/G__MathCore.dir/build.make:213: math/mathcore/G__MathCore.cxx] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:19283: math/mathcore/CMakeFiles/G__MathCore.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
```

**Comment by pcanal** [comment]
> And after I revert d8383fc, 

Why revert this commit?  Wouldn't that break the type extraction with gcc 7?

**Comment by pcanal** [comment]
> the problem is likely to be either at ...

To be clearer.  I suspect that __PRETTY_FUNCTION__ is returning for icc is different form that the one expected in TTypeNameExtractionBase::GetImpl and thus needs to be adjusted for it.

**Comment by pcanal** [comment]
From your output it look like the main difference is the end of the type information.`
gcc 7:
```
[with T = ROOT::Internal::TCheckHashRecurveRemoveConsistency; std::__cxx11::string = std::__cxx11::basic_string<char>]
```
while icc
```
[with T = ROOT::Detail::TTypedIter<TBaseClass>]
```
i.e. the trailing semi-colon is missing in icc and hence the line:
```
        const char* endWithT = strstr(startWithT, ";");
```
need to be enhanced to find the end either with semi-colon or bracket which ever comes first (or something 'better'/'more accurate'.

**Comment by amadio** [comment]
We need to stop relying on such hacks to deduce the types, because it will never work. If in the next version ICC decides to change the format of PRETTY_FUNCTION again, our code will become broken again. We need to use `typeid(T).name()` and then find a way to consistently demangle the name it returns, instead of trying to parse error messages.

**Comment by pcanal** [comment]
indeed.  I am not sure why this choice was made though.

Anyway, we even already have ```TClassEdit::DemangleTypeIdName(const std::type_info& ti, int& errorCode)``` that hides the platform dependence ... it might need to be moved though to be accessible from Rtypes.h

**Comment by amadio** [comment]
A fix for this is now part of #1393.

**Pull request closed without merging**
