### PR TITLE
[tmva] Fix new TMVA python tutorials

### PR DESCRIPTION
**Pull request by lmoneta**
This Pull request fixes two 2 Python tutorials introduced with #11069

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by sanjibansg — APPROVED** [review]
LGTM!

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
