### PR TITLE
[v6-30][skip-ci] Remove the deprecated `exceptions` option from the CI

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
Oh that's all we need? Thanks!

**Comment by bellenot** [comment]
> Oh that's all we need? Thanks!

What do you mean?

**Comment by guitargeek** [comment]
> > Oh that's all we need? Thanks!
> 
> What do you mean?

It's not all we need I think. The problem that `exceptions` is on by default, which triggers the warning everytime even if you don't set the flag yourself is still there:
https://github.com/root-project/root/blob/master/cmake/modules/RootBuildOptions.cmake#L130

I would suggest the following change:
```cmake
ROOT_BUILD_OPTION(exceptions IGNORE "Enable compiler exception handling (deprecated)")
```
instead of `ON`. As far as I can tell, the exceptions flag is actually ignored, so that would be accurate and evaluate to `false` in the deprecation check:
https://cmake.org/cmake/help/latest/command/if.html#basic-expressions

**Comment by bellenot** [comment]
Oh, OK, I see. Thanks @guitargeek ! I'll make a separate PR

**Pull request merged**
