### PR TITLE
[TMVA] RReader: allow spectators in xml file

### PR DESCRIPTION
**Pull request by goi42**
fixes bug reported in the forum [here](https://root-forum.cern.ch/t/rreader-and-spectator-variables/42844)

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build !

**Comment by pieterdavid** [comment]
I opened https://github.com/goi42/root/pull/2 with some fixes for this PR last week, but got no answer yet... shall I open a new PR directly here?

**Comment by goi42** [comment]
Hi @pieterdavid,
Sorry, somehow your request fell through the cracks. I’ve merged it now. Thanks for doing this—I hadn’t had time to come back to this myself.

**Review by lmoneta — COMMENTED** [review]
Hi, 
The PR looks good to me. Before merging, it would be nice to update also the tutorial or add a test for it

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
LGTM, thanks for adding support for the spectator variables!

@lmoneta already agreed with these changes, however his request to add documentation was not followed up. Still, it's worth it to also merge this development without this follow-up request, because spectator variables in the XML are quite common.

**Pull request merged**
