### PR TITLE
Remove unnecessary include in metacling

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by pcanal** [comment]
Thanks for looking into this.

How did you derive the list of things to be removed?  Our heuristic is to have the header for what the source use directly included rather than relying on the header being indirectly included.  So for example, this PR remove the include for std::string from TClingClassInfo.cxx which likely still works/compile but we still want to keep the #include <sring> as std::string is used (see like 59 or 60 for example).  

Cheers,
Philippe.

**Comment by yamaguchi1024** [comment]
Thanks for your comment!

https://github.com/root-project/root/pull/1748
Your question is related to this commit. I'm just invoking include-what-you-use command for each file, and only using part of its output. IWYU only looks at one file to determine if included header is needed or not.

**Comment by pcanal** [comment]
>  I'm just invoking include-what-you-use command for each file,

Fair-enough, that is a good way to go about it.   

However, I would like to understand why it recommends removing '#include <string>' when it is obviously use.  I.e. is it a deficiency in IWYU or is it a feature (in which case I am not quite sure what rules/heuristic it follows and would appreciate a clarification) or am I missing something?

**Comment by yamaguchi1024** [comment]
Hmm, now I understood what you meant. Actually I'm not sure what IWYU reducing policy is, so I'm trying to read this: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhatIsAUse.md

**Comment by yamaguchi1024** [comment]
Maybe this is too overzealous, closing

**Pull request closed without merging**
