### PR TITLE
Simplify memory regulation logic

### PR DESCRIPTION
**Pull request by vepadulano**
With *all* these changes, I do not see anymore failures in a local run with the ubuntu 24.10 CI image. let's see if the rest of the CI agrees. Note that one of the changes is equivalent to https://github.com/root-project/root/pull/16671

### CODE REVIEW

**Review by guitargeek — APPROVED** [review]
This is really great, and the CI also starts to be green! The failures are unrelated and caused by https://github.com/root-project/root/pull/16697. FYI, @ferdymercury.

**Comment by ferdymercury** [comment]
> The failures are unrelated and caused by #16697. FYI, @ferdymercury.

Yep, it's because the sibling roottest PR was overlooked. (Should have been merged simultaneously)

**Comment by vepadulano** [comment]
I have added more comments to the commit descriptions. Once the CI confirms these changes indeed work I will merge. Also, we can merge the CI for ubuntu24.10 directly with this PR.

**Comment by guitargeek** [comment]
Nice! And cool to see that it also works on Fedora 41 with Python 3.13

**Pull request merged**
