### PR TITLE
Rework creation of tasks in distributed mode

### PR DESCRIPTION
**Pull request by vepadulano**

### CODE REVIEW

**Review by etejedor — APPROVED** [review]
Reviewed together, great job!

**Comment by eguiraud** [comment]
I think we should have some unit tests for `get_clustered_range_from_percs` and `get_percentage_ranges`. E.g. tests that exercise that logic in case of many partitions per file, very few partitions per file and less partitions than the number of files.

**Comment by vepadulano** [comment]
The lgtm alert is for truncating division in case of integer arguments, which is only relevant for Python 2.

This is ready for final review. Maybe some comments that might help explain better the logic here and there? With final approval I will also add a commit message

**Comment by vepadulano** [comment]
@phsft-bot build

**Pull request merged**
