### PR TITLE
updated doxygen list

### PR DESCRIPTION
**Pull request by whit2333**
Fixed doxygen list here: https://root.cern.ch/doc/master/classROOT_1_1RDF_1_1RDataSource.html

### CODE REVIEW

**Comment by bluehood** [comment]
Hi @whit2333 , thank you for spotting _and_ fixing these!
Let me build the docs locally to double-check the formatting is right this time :smile:

**Comment by whit2333** [comment]
I might have some more small changes coming ...

**Comment by bluehood** [comment]
It certainly looks better than before. There is some inconsistency in the boldfacing of the numbers here:
image

Also we should either use the numbers to refer to the numbered list above or call the methods by name directly, probably not both. I don't have a strong preference though -- what do you think?

**Comment by bluehood** [comment]
> BTW can you define what a "Slot" is somewhere in the RDataFrame documentation? Sorry if I just missed it.

ctrl-f'ing it, it's said in a bunch of places but never "officially", we might want to fix that.
the best description is that slot is an integer that will take a different value, 0 to nThreads - 1, for each thread of execution. It is meant to be used as a helper to write thread-safe transformations and actions (e.g. you could write a `Foreach` function that hammers a different output variable per slot, making it inherently thread-safe).

**Comment by whit2333** [comment]
Thanks. I guess my question is more about the "slot concept", rather than the explicit definition (i.e. 0 to nthreads-1). I need to study this a bit more.

Regarding  the changes, I went with referencing by name.

**Comment by bluehood** [comment]
@whit2333 on the `RDataFrame` side, there is little more than that -- I guess you would like to understand slots on the `RDataSource` side of things then? Maybe we should continue this conversation on the ROOT forum, it might benefit many other people and might turn out useful to point people there in the future.
Feel free to post there if you need clarifications.

Regarding the PR: looks good to me (and thank you again).
Could you please squash together all commits and force-push to your PR branch? The final result is what we want to merge :smile:

**Comment by whit2333** [comment]
@dpiparo I have squashed the commits.

**Comment by bluehood** [comment]
@whit2333 sorry about the git confusion: it seems that you squashed all of your commits into Philippe's last commit.

We would like this PR to consist of one single commit of yours with all the changes to the doxygen docs. Once that's done, I will merge :smile:

**Comment by whit2333** [comment]
@bluehood Sorry about that. I should have been paying closer attention but I think I got it this time.

**Comment by bluehood** [comment]
@whit2333 perfect, thanks!

**Pull request merged**
