### PR TITLE
[RF] Fix several memory leaks in RooFit/RooStats

### PR DESCRIPTION
**Pull request by hageboeck**
[ROOT-10713][ROOT-7986] Several objects were leaking when being read from a file. This is because ownership was unclear, and because reading apparently wasn't tested.
Here
- Four leaks are fixed
- A reading test is added (which is reading the object that revealed all the leaks. This tests both for leaks in address sanitizer builds, but also ensures that the updated streamers still work.)
- A container overflow detected by address sanitizer is fixed.
- And the includes of RooRealVar are stripped down significantly. This is nice for RooFit, since almost everything includes RooRealVar.

### CODE REVIEW

**Comment by lmoneta** [comment]
Very nice to fix all these leaks !! LGTM

**Comment by ntadej** [comment]
@hageboeck, do you think this could be safely cherry-picked to the 6.20 branch? I would like to run a production fit and would rather use the stable version of ROOT?

I can build ROOT myself, but you can probably answer me quicker if lots of things changed in RooFit/RooStats in master.

**Comment by hageboeck** [comment]
@ntadej I tried to cherry-pick, but it only worked with three of the four fixes. Also, I only know that *merging* worked at the moment, but it's not clear whether it compiles or if tests work.
I will let it run and see, but to get the full fixes, you will have to wait for ROOT 6.22. The good new is that we will branch off the release candidate this week, so you could use the tag v6-22-00-rc1 or so when it's available.

**Comment by ntadej** [comment]
Managed to cherry-pick manually and it seems to compile. Will try to run, otherwise I'll wait for 6.22. Thanks for your help!

**Pull request merged**
