### PR TITLE
[TSpectrum] avoid recurrent questions on forum concerning legacy

### PR DESCRIPTION
**Pull request by ferdymercury**
There are monthly questions about TSpectrum being dis-recommended in the ROOT forum, and what alternatives there are.

For example: https://root-forum.cern.ch/t/which-package-or-class-supersede-the-tspectrum-for-searching-peaks/51459 and links there-in.

Normally, the answer is, there is no one to one development, you can still use it, it's just that it will no longer be maintained.

This PR makes the formulation of the 'warning' less alarming and potentially prevents further duplicate questions in the forum.

### CODE REVIEW

**Comment by couet** [comment]
I am not in favor to introduce yet a new keyword. The `legacy` keyword, seems to me, is the right one. Maybe the message should be improved a bit. Just a matter of taste. Let see...

The current message is:

_TSpectrum is a legacy interface: it is not recommended to use it in new code. There will be no bug fixes nor new developments._

The "key" word here is: "not recommended to use it in NEW code". reading between the lines it means: you can still use this class but it is not recommended to base new development on it.  That's exactly what it is.

You propose:

_TSpectrum is a legacy interface: you can use it, as there is no one-to-one replacement interface planned/known. There will be no bug fixes nor new developments._

You removed the fact we do not recommend using it in new code, I do not think it is a good idea, and you add the info that there is "no known replacement"... fine. But this can be said in the body of the doc. No need for the new keyword `unmaintained`. I am afraid a such new keyword will be used only for TSpectrum. That will add complexity for no real gain.

**Comment by ferdymercury** [comment]
I understand your point from the developer point of view. But from the user point of view:

There have been so many many users asking this question. When so many people ask this question, it means that the message is ambiguous. It's not a one-case.

https://root-forum.cern.ch/t/which-package-or-class-supersede-the-tspectrum-for-searching-peaks/51459
https://root-forum.cern.ch/t/if-tspectrum-class-is-legacy-code-another-code-for-tspectrum/50833
https://root-forum.cern.ch/t/question-about-tspectrum-alternatives/48447
https://root-forum.cern.ch/t/question-about-tspectrum-alternatives/48447
https://root-forum.cern.ch/t/alternative-for-tspectrum/49984

Also, saying that it is not recommended is a bit aggressive when there is no replacement for it, which is why in my opinion so many people ask the question. The result is that developers lose most time answering the questions in the forum. If one would say, do not use TTreeReaderArray, use RDataFrame, that would be fine.

In any case, I agree with your point of adding more info in the body doc, as you commented here: https://root-forum.cern.ch/t/alternative-for-tspectrum/49984/3?u=ferhue

Still, my opinion is that the wording could be fixed on the first place. If the label were just 'interface will not receive new bug fixes', instead of 'not recommended', it would be less ambiguous and no one would ask further questions in the forum.

**Comment by ferdymercury** [comment]
One idea: Maybe the 'legacy' alias could contain two arguments {1}{2}. 2 could be something like "There is no known replacement" or "" or "See RDataFrame for replacement".

**Comment by couet** [comment]
What about:

_TXXX is a legacy interface, there will be no bug fixes nor new developments, therefore it is not recommended to use it in new long-term production code. But depending on the context using TXXX might still be a valid solution._

?

**Comment by ferdymercury** [comment]
> What about:
> 
> _TXXX is a legacy interface, there will be no bug fixes nor new developments, therefore it is not recommended to use it in new long-term production code. But depending on the context using TXXX might still be a valid solution._
> 
> ?

sounds perfect :)

**Comment by ferdymercury** [comment]
> > Pointing to what alternatives there are, if any, either through the legacy alias, or in > the body doc, would be additionally helpful.
> 
> We cannot test the existence of an input variable in an alias therefore we cannot handle with the same alias the case where there is another solution and the case where there is not. I guess if there are possible alternatives they should be mentioned in the body of the class documentation.

I guess one could use:
`ALIASES                = "legacy{2}=\htmlonly<div class=\"legacybox\"><h2>Legacy Code</h2> \1 is a legacy interface: there will be no bug fixes nor new developments. But depending on the context using \1 might still be a valid solution. \2</div>\endhtmlonly"
`

and then:
`\legacy{TSpectrum}{Some parts of this class are superseded by RooFit.}`

or:
`\legacy{TTreeReader}{RDataFrame is recommended as replacement.}`

Second argument can be also left empty {}

**Comment by couet** [comment]
Yes, good point. I’ll try.

**Comment by ferdymercury** [comment]
Thanks! Another mechanism to know if there are one or two arguments would be overloading, but that requires repeating a bit of text when defining the aliases:

```
Note that you can overload an alias by a version with multiple arguments, for instance:
ALIASES += l{1}="\ref \1"
ALIASES += l{2}="\ref \1 \"\2\""
```

**Comment by couet** [comment]
I guess it is better if I do a new PR, Or would you like to modify this one to implement the new way?

**Comment by ferdymercury** [comment]
Sure, I will close this one :)

**Comment by couet** [comment]
TTreeReader does not have the `\legacy` banner right now.
https://root.cern/doc/master/classTTreeReader.html

**Comment by ferdymercury** [comment]
Yes, I just invented a 'silly' example for illustrating potential uses.

**Pull request closed without merging**
