### PR TITLE
JSON: Special handling of STL containers with len=1

### PR DESCRIPTION
**Pull request by linev**
It solves problem I recognize for the first time with ROOT7 webgui.
It was wrong representation for container like: std::vector<UserClass>
Patch for roottest will follow very soon.

### CODE REVIEW

**Comment by linev** [comment]
Hi Philippe @pcanal 

Should I apply clang-format for TBufferJSON?
It wants change mostly every line in the source code.

**Comment by pcanal** [comment]
You can restrict to just the line you modified in this PR.  You can, **if you want**, elect to apply it to the whole file if you are somewhat happy with the result.

**Comment by linev** [comment]
> You can restrict to just the line you modified in this PR.

But how I can do this? Is there special clang-format command for that?

> You can, if you want, elect to apply it to the whole file if you are somewhat happy with the result.

I don't care. But does it always produce correct result? I do not want to check manually all ~3600 lines of code.

**Comment by pcanal** [comment]
> I don't care. But does it always produce correct result? I do not want to check manually all ~3600 lines of code.

It is pretty good but not perfect (i.e. it does not always format the code is a way that is better).

The travis page has the information (both the command and the patch to be applied): https://travis-ci.org/root-project/root/jobs/240426093

The command is (in your case):

git-clang-format --commit 39af41d21cfe63141262dd7d03d21b5bad956aec --diff --binary /usr/local/clang-3.4/bin/clang-format

Cheers, Philippe.

**Comment by linev** [comment]
I submit separate PR for roottest.

**Pull request merged**
