### PR TITLE
Re-enable several default build options on Windows

### PR DESCRIPTION
**Pull request by bellenot**
Don't turn OFF builtin_tbb, dataframe, imt, roofit, and tmva by default on Windows

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
Congrats! LGTM! (ah I see windows build is still happening, lets wait then)

**Comment by oshadura** [comment]
@bellenot I am looking the logs for windows build and it looks like it stuck? (no changes from 10 morning?)

**Comment by bellenot** [comment]
> @bellenot I am looking the logs for windows build and it looks like it stuck? (no changes from 10 morning?)

Weird, checking...

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/cxx14

**Pull request merged**
