### PR TITLE
 [TreeProcMT] Fix ROOT-10227

### PR DESCRIPTION
**Pull request by bluehood**

### CODE REVIEW

**Comment by amadio** [comment]
Can you please add an explanation?

**Comment by bluehood** [comment]
@amadio basically I fixed a typo...added a little comment to the commit log.

**Comment by bluehood** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
I have cherry-picked 989d9158b6 into v6-18-00-patches as 62bde834ec.

**Comment by bluehood** [comment]
thank you @Axel-Naumann !

**Pull request merged**
