### PR TITLE
Revert D41416: "Do not deserialize all lazy template specializations when looking for one."

### PR DESCRIPTION
**Pull request by hahnjo**
The lazy loading approach may be faster, but it is continuously leading to problems with template instantiations and ODR violation checks in the most inconvenient places.

### CODE REVIEW

**Comment by pcanal** [comment]
For the record do we know how much 'slower' things are getting?

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On -Druntime_cxxmodules=OFF

**Review by vgvassilev — CHANGES_REQUESTED** [review]
We have been discussing this offline and I’d refrain from moving forward for the moment.

**Comment by hahnjo** [comment]
Sure, I only wanted to confirm my local observation that this revert happens to also solve https://github.com/root-project/root/issues/13058...

**Review by vgvassilev — COMMENTED** [review]
To summarize our discussion with @hahnjo. We agreed to do three things:
  * Enable the missing optimization for class template specializations that we lost due to merging process when adopting llvm13.
  * Adopt (a form of) [D153003](https://reviews.llvm.org/D153003) that would help us fix the template hashing issue;
  * Add a new `spec_begin` method such as `loaded_spec_begin` to allow the decl unloader avoid unloading yet-to-be-deserialized entities.

If we cannot make this work reasonably in a week we can revert it and immediately open a PR to reland it with a due date the next ROOT release. If this works, then we will make an effort to push `D41416` upstream.

**Comment by hahnjo** [comment]
We merged https://github.com/root-project/root/pull/13139

**Pull request closed without merging**
