### PR TITLE
Cling optimization option

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by vgvassilev** [comment]
It looks like we need some wider test coverage.

**Comment by Axel-Naumann** [comment]
Not for ROOT.

**Comment by vgvassilev** [comment]
I meant for cling as the feature seems to be in cling, too.

**Comment by Axel-Naumann** [comment]
Sure, but I'm testing ROOT here...

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Merged something similar to this.

**Pull request closed without merging**
