### PR TITLE
[CMake] Only build `clad` plugin if requested

### PR DESCRIPTION
**Pull request by guitargeek**
Building clad should not depend on the result of the connectivity check, but whether it is enabled.

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
LGTM.  The related error message and disabling is done (correctly in regard to this fix) on `CMakeLists.txt` line 99 to 106

**Comment by guitargeek** [comment]
> LGTM. The related error message and disabling is done (correctly in regard to this fix) on `CMakeLists.txt` line 99 to 106

That is correct! I should have maybe explained it in the PR description. Thank you very much for double-checking.

**Comment by ynikitenko** [comment]
I faced the following problem when compiling ROOT from source,

> [ 73%] Performing download step (git clone) for 'clad'

however, I was offline, and the whole build process interrupted.

I think that building from source assumes you have downloaded everything and you can safely compile in an isolated environment. At least it must be specified somewhere beforehand that one needs a connection or *those* modules.

Does your commit fix that in future versions?

**Comment by guitargeek** [comment]
Hi! The commit that fixes the problem you report is this one:
https://github.com/root-project/root/pull/15488

**Comment by ynikitenko** [comment]
Thank you. Not exactly: in my case I was online, and then went offline. The
build process for ROOT takes several hours on my laptop.

I wouldn't call that check reliable. Ideally, it could download the files
during that check or in the beginning of the build process.

**Pull request merged**
