### PR TITLE
[cmake] Randomize execution of gtests

### PR DESCRIPTION
**Pull request by stwunsch**
Does this make sense? Could increase our test coverage.

### CODE REVIEW

**Comment by amadio** [comment]
I don't think randomizing will increase test coverage. In any case, some tests depend on others, so running them in random order will cause them to fail. For example, in the TBufferMerger tests, one test writes in parallel to a file and a later test checks the data integrity of the file. If the second test is run before the first, it will fail, which is what happened above.

**Comment by stwunsch** [comment]
Shouldn't all unit-test be independent? If you see a failure in a test, shouldn't it be reproducible by itself? You could have hidden dependencies between the tests. That's at least the statement from the [gtest guys](https://groups.google.com/d/msg/googletestframework/A_Z_8Ctihmw/quG7RurEz_YJ).

But I agree that it does not increase the test coverage substantially.

**Comment by amadio** [comment]
The dependency is not hidden in this case, it's wanted. How could I check integrity of a file in a separate test than the one that creates the file otherwise? One needs to depend on the other. The other failed tests are probably similar. I think it's fine to add the randomization on a case-by-case basis. I don't think that just having tests that depend on one another is bad per se, only if the dependency is not intentional.

**Comment by Axel-Naumann** [comment]
Adding some clarification:
In the old days, CTest did not have the notion of "before running this test, build the following". So Pere resorted to "before running this test, run that test (which isn't actually a test but builds stuff but details)". Given that we haven't migrated to the new CTest pre-test commands we cannot run the tests in random order. Once we do this PR will be a great test that we did our job correctely!

**Comment by amadio** [comment]
The commit in this PR is only concerning Google test based tests, where you can pass an option to run the sub-tests that are part of the same binary in random order.

**Pull request closed without merging**
