### PR TITLE
[cling-cpt] Formatted code to be flake8 compliant [skip-ci]

### PR DESCRIPTION
**Pull request by saisoma123**
# This Pull request: Makes the code flake8 compliant

## Checklist:

- [X] tested changes locally
- [NA] updated the docs (if necessary)

This PR fixes the issue mentioned https://github.com/root-project/root/pull/406 in (https://github.com/root-project/cling/issues/406)

### CODE REVIEW

**Comment by vgvassilev** [comment]
I am worried about this change as it is very big. Did that formatting come from some automatic linter?

**Comment by saisoma123** [comment]
Sorry I first used yapf to format, then the remaining errors I fixed myself

**Comment by vgvassilev** [comment]
I am not sure I am qualified to review these changes. I prefer to have smaller and more understandable diffs.

**Comment by saisoma123** [comment]
Hi @vgvassilev, I think I could make it easier for you to review if I make smaller pull requests and each one corresponds to a certain flake8 error code.

**Pull request closed without merging**
