### PR TITLE
[PyROOT] Merge `libROOTPythonizations` and `libJupyROOT`

### PR DESCRIPTION
**Pull request by guitargeek**
Having only one CPython extension for PyROOT definitely makes things easier. The `libJupyROOT` was very small.

### CODE REVIEW

**Comment by pcanal** [comment]
What are the changes from a user point of view?

**Comment by guitargeek** [comment]
There is no change for the user, but for packaging it makes things easier. See also https://github.com/root-project/root/pull/15402.

Actually this is still a draft PR,I first wanted to see if all platforms are happy with the C++ changes. The next step is to move the `JupyROOT` submodule to `ROOT.JupyROOT`.

Also this will have no effect on the user, because the user never imports this module themselves: it is implicitly imported by `ROOT` in a notebook environment.

The overall goal of these PRs is to have a single pyroot module (`ROOT`) instead of the current 4 (ROOT, JsMVA, JupyROOT, and DistRDF). For packagers, and for Root as a Python package in general, that would make things clearer and easier: from installing root, you get the module `ROOT`.

**Review by vepadulano — APPROVED** [review]
Thanks! I believe this is the right way to go

**Comment by guitargeek** [comment]
Rebased on top of master. Failure on macos14 is because of the known xml2 issue.

**Pull request merged**
