### PR TITLE
[TMVA][ROOT-10734] Veto RNN and CNN tutorials if pymva not enabled

### PR DESCRIPTION
**Pull request by stwunsch**

### CODE REVIEW

**Comment by stwunsch** [comment]
Wouldn't it be easier to just remove the pymva part? I think an explicit library load in a tutorial is a little bit weird, from the users perspective. It does not convey the message of a clean tutorial for a stable feature.

**Comment by lmoneta** [comment]
HI, 
I think is nice to show in a tutorial that we can run different methods and TMVA and Keras at the same time. 
We could add a pre-processing macro for pymva, something like R__HAS_PYMVA
or even better fix the loading of the library using the ROOT plugin-manager.

I will see if I can provide a PR for one of these tomorrow

**Comment by oshadura** [comment]
@stwunsch @lmoneta is this still something we would like to be merged?

**Comment by lmoneta** [comment]
I think we can close this PR. It is not needed anymore

**Comment by oshadura** [comment]
@stwunsch I am sorry I closed PR but please reopen it if you feel it is something still needed :)

**Pull request closed without merging**
