### PR TITLE
Use FullName in TTree::GetLeaf.

### PR DESCRIPTION
**Pull request by pcanal**
Fixes ROOT-10942

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by Axel-Naumann — APPROVED** [review]

**Comment by eguiraud** [comment]
Those dataframe failures look real

**Comment by eguiraud** [comment]
This is messing with RDataFrame's logic to figure out what type a branch is. @pcanal I will debug what goes wrong exactly and let you know

**Comment by eguiraud** [comment]
At a fundamental level the problem is that `RDataFrame` has some homegrown logic to figure out the type of a branch/leaf that is sensible to changes in behavior of `TTree::GetBranch` or `TTree::GetLeaf`.

The problem RDataFrame has with this patch is that in the following repro, in which a `TClonesArray` branch is added to a `TTree`, behavior of `tree.GetLeaf("clonesarray")` has changed: before this patch, it would return a nullptr (while `tree.GetBranch("clonesarray")` would return the branch; after this patch `tree.GetLeaf("clonesarray")` returns a valid `TLeaf`, so RDataFrame thinks the type of the branch is `leaf->GetTypeName()`, which is `Int_t` for this branch containing `TClonesArray`.

I don't think this change in behavior is intentional given that the PR is supposed to fix retrieval of leaves by their full name, not change the behavior of retrieval of leaves with no dot in their names?

```cpp
#include <ROOT/RDataFrame.hxx>
#include <TTree.h>
#include <TClonesArray.h>
#include <TH1D.h>

int main()
{
   TClonesArray arr("TH1D", 3);
   for (int i = 0; i < 3; ++i) {
      auto *h = static_cast<TH1D *>(arr.ConstructedAt(i));
      h->SetBins(25, 0, 10);
      h->Fill(i);
   }
   TTree t("t", "t");
   t.Branch("arr", &arr);
   t.Fill();

   auto l = t.GetLeaf("arr");
   if (l == nullptr) {
      std::cout << "leaf is null" << std::endl; // this is what happens before this PR
      return 0;
   }

   // this prints "Int_t", and it is what happens with this PR
   std::cout << "leaf has type name " << l->GetTypeName() << std::endl;
   return 0;
}
```

**Review by eguiraud — CHANGES_REQUESTED** [review]
I took a second look. As far as I can tell, the change in behavior I describe above is unintentional/a bug.

**Comment by pcanal** [comment]
Thanks for double checking.  Yes it is unintentional.  This is due to the FullName of the "index" leaf of TClonesArray being misnamed.

**Comment by pcanal** [comment]
See https://github.com/root-project/roottest/pull/591 for additional tests.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@eguiraud readShip fails becuase the branch `MCTrack.fPdgCode` used to have the wrong name:
```
root [19] cbmsim->GetBranch("MCTrack.fPdgCode")->GetFullName()
(TString) "MCTrack.MCTrack.fPdgCode"
```
while it now properly returns:
```
root [19] cbmsim->GetBranch("MCTrack.fPdgCode")->GetFullName()
(TString) "MCTrack.fPdgCode"
```
and a consequence (I did not investigate the mechanics) is:
```
ERROR: expecting the type name Int_t for column MCTrack.fPdgCode and got 'ROOT::VecOps::RVec<Int_t>' instead!
```
Could you take a look?

Thanks.

**Comment by eguiraud** [comment]
Taking a look!

**Comment by eguiraud** [comment]
The test is wrong, and RDF has inferred the wrong type for columns like that since 6.18. https://github.com/root-project/roottest/pull/592 fixes the test (i.e. makes it red now, and green with this PR).

Do you plan to backport these changes to v6.18/20/22? If not, I'll have to fix the type inference in those versions in some other way.

**Review by eguiraud — APPROVED** [review]

**Comment by pcanal** [comment]
Yes, I will back-port to v6.20 and v6.22, is RDataFrame['s test] ready for it?
I will not back-port to v6.18 as we have not back-ported any of the GetFullName changes to it (yet?)

**Comment by eguiraud** [comment]
> is RDataFrame['s test] ready for it?

I have opened PRs that fix the test for master, 6.22 and 6.20

**Pull request merged**
