### PR TITLE
[tmva][pymva] Use .h5 file instead of .keras

### PR DESCRIPTION
**Pull request by lmoneta**
Go back to use .h5 files instead of .keras due to a problem in Keras loading .keras files on MacOS ARM 
(see https://github.com/keras-team/keras/issues/18278 )

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/deafult

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac12/default, ROOT-ubuntu2204/nortcxxmod

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default, ROOT-ubuntu2204/nortcxxmod

**Review by sanjibansg — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by lmoneta** [comment]
@phsft-bot build on mac13arm/default, mac13/default

**Pull request merged**
