### PR TITLE
Minuit2 fixes

### PR DESCRIPTION
**Pull request by HDembinski**
Hi, I am one of the iminuit developers (https://github.com/iminuit/iminuit).

We are glad that Minuit2 is still usable as a package separate from ROOT and thank the ROOT developers for that. It makes our life much easier.

The iminuit package is build by copying the Minuit2 code in ROOT and building a Cython wrapper around it. Because we compile and use the Minuit2 code outside of the ROOT build environment, we found and fixed some bugs, which we would like to merge upstream in ROOT as well. Each of the two commits in this PR fixes one issue.

The first is rather trivial, `MnPrint` is used unconditionally, even though the corresponding header `MnPrint.h` is only included if certain compiler flags are set.

The second one is a change in the interface of the `MinimumBuilder` base class. We run Minuit using the `MnMigrad` class. Without this change, there is no way to change the print level in a particular instance of MnMigrad. The change does not violate the logical constness of MinimumBuilder.

### CODE REVIEW

**Comment by henryiii** [comment]
You might take a look at #1680, that might make your life easier. (This patch is still looks like a good idea to me).

**Comment by cdeil** [comment]
@lmoneta - Could you please have a look at this?

It would be helpful for extern Minuit2 users like us in iminuit if it's simple to extract and update to the latest version.

**Comment by henryiii** [comment]
@cdeil , #1680 was merged; you should be able to extract Minuit trivially now (I don't think packages have been produced yet, though).

@lmoneta, @amadio do you think it would be a good idea to at least merge 2f320cd ? That's a logical error. The other change may be okay, but I'm not really sure you couldn't get around it with a const cast in user code, and making a non-mutex/atomic mutable doesn't seem to be safe to me.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by HDembinski** [comment]
Hi @henryiii, good to hear that your PR was accepted :) Congratulations!

**Comment by HDembinski** [comment]
@henryiii I guess I can work around this problem with a `const_cast`, but `const_casts` are evil and should not be necessary to access a basic feature of the public interface. In my understanding this is an interface bug. I agree that my solution is not optimal either, so if you want to take a deeper look please do.

In `iminuit`, we run MIGRAD with the class `MnMigrad`. If you look into `MnMigrad.h`, you will see that it only allows one to access the `ModularFunctionMinimizer` as a const reference. The `ModularFunctionMinimizer` allows us to access the `MinimumBuilder` as a const and non-const reference, but the latter is non available, because `ModularFunctionMinimizer` is already const. The only way to set the print level for `MnMigrad` that I can see is via
`MnMigrad.Minimizer().Builder().SetPrintLevel(...)`, and that only works when `SetPrintLevel(...)` is const.

As far as I can see, it makes sense that `MnMigrad` only hands out a const reference. Otherwise, it would also be a (possibly cleaner) solution if `MnApplication` and its children offer a `Minimizer()` method which returns a non-const reference.

**Comment by henryiii** [comment]
As you've seen and had to fix, this changes the interface (`const` is part of the signature of a function in C++), so that this could change for people overloading this method. And, if they don't add `overload` when overloading it, they might not even know that their code is broken. Also, I don't think anyone would expect a set method to be `const`.

Const casts are evil, but so is a non-atomic mutable. For the same reason. And at least with the const cast, you know what you are doing.

**Comment by henryiii** [comment]
PS: The underlying problem may be that both a const and non-const access to the reference should be available. I haven't looked into this particular problem as much as you have, I'm just warning you about the things that seem problematic to me with the current approach.

**Comment by HDembinski** [comment]
@henryiii I totally agree with you, as you can read from my previous comment. I can do a const_cast in my client code. That's ok to solve my problem, but then the root cause in Minuit is still there and remains unfixed.

**Comment by pcanal** [comment]
> The second one is a change in the interface of the MinimumBuilder base class. We run Minuit using > the MnMigrad class. Without this change, there is no way to change the print level in a particular
> instance of MnMigrad. The change does not violate the logical constness of MinimumBuilder.

When considering thread-safety, one of the conclusion is that in order to have a consistent system, const function *must* be thread-safe.  So indeed all mutable ought to be either protected by a lock or made atomic.

Independently, it is **very** odd to have a 'Setter' to be const.   What is the actual use case/code that is prevented by having this function non-const?

**Comment by HDembinski** [comment]
@pcanal I use the class `MnMigrad` to minimize a function and I want to set the PrintLevel for that class.

Quoting myself from two messages back:
We run MIGRAD with the class `MnMigrad`. If you look into `MnMigrad.h`, you will see that it only allows one to access the `ModularFunctionMinimizer` as a const reference. The `ModularFunctionMinimizer` allows us to access the `MinimumBuilder` as a const and non-const reference, but the latter is not available, because `ModularFunctionMinimizer` is already const. The only way to set the print level for `MnMigrad` that I can see is via
`MnMigrad.Minimizer().Builder().SetPrintLevel(...)`, and that only works when `SetPrintLevel(...)` is const.

**Comment by pcanal** [comment]
> If you look into MnMigrad.h, you will see that it only allows one to access the ModularFunctionMinimizer as a const reference.

@lmoneta @henryiii Is that limitation necessary?

**Comment by oshadura** [comment]
#

**Comment by oshadura** [comment]
#

**Comment by HDembinski** [comment]
I think we can close this pull request. The two patches have been separately addressed in PR's by @henryiii

**Comment by HDembinski** [comment]
Yes, it works.

**Comment by amadio** [comment]
Ok, closing this in favor of #1946.

**Pull request closed without merging**
