### PR TITLE
Rebase better to llvm13 to the FileEntryRef and FileEntry.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@andresailer reports
```
...
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for include/IOIMPL/TrackerPulseIOImpl.h
   requested to autoload type IOIMPL::TrackerPulseIOImpl
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for include/IOIMPL/TrackerRawDataIOImpl.h
   requested to autoload type IOIMPL::TrackerRawDataIOImpl
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for include/IOIMPL/VertexIOImpl.h
   requested to autoload type IOIMPL::VertexIOImpl
Error in <TInterpreter::AutoParse>: Error parsing payload code for class EVENT::LCEvent with content:

#line 1 "EVENT dictionary payload"
...
Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
```
and more, http://cdash.cern.ch/testDetails.php?test=16531307&build=211395 from  `Test: LCIO_pyLCIO_import_test (Passed)` (cough cough) - this might be pre-existing before the llvm13 upgrade

**Comment by vgvassilev** [comment]
> @andresailer reports
> 
> ```
> ...
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for include/IOIMPL/TrackerPulseIOImpl.h
>    requested to autoload type IOIMPL::TrackerPulseIOImpl
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for include/IOIMPL/TrackerRawDataIOImpl.h
>    requested to autoload type IOIMPL::TrackerRawDataIOImpl
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for include/IOIMPL/VertexIOImpl.h
>    requested to autoload type IOIMPL::VertexIOImpl
> Error in <TInterpreter::AutoParse>: Error parsing payload code for class EVENT::LCEvent with content:
> 
> #line 1 "EVENT dictionary payload"
> ...
> Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
> Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
> Error in <TClass::LoadClassInfo>: no interpreter information for class EVENT::LCEvent is available even though it has a TClass initialization routine.
> ```
> 
> and more, http://cdash.cern.ch/testDetails.php?test=16531307&build=211395 from `Test: LCIO_pyLCIO_import_test (Passed)` (cough cough) - this might be pre-existing before the llvm13 upgrade

Perhaps, the last fix I pushed will fix it...

**Comment by andresailer** [comment]
>  (cough cough) - this might be pre-existing before the llvm13 upgrade

Have some 💧 :) no "might" about this T_T
http://cdash.cern.ch/testDetails.php?test=14519774&build=210942

**Review by Axel-Naumann — APPROVED** [review]
LGTM!

**Comment by Axel-Naumann** [comment]
Thanks @andresailer - 2022-12-16 23:06:39 is before you saw the llvm upgrade?

**Comment by andresailer** [comment]
This is dev4, so ROOT 6.26-patches branch.

**Comment by Axel-Naumann** [comment]
> Perhaps, the last fix I pushed will fix it...

If pre-existing we won't need a fix: it's a symptom of not providing `ROOT_INCLUDE_PATH` to these headers, so ROOT cannot find them at runtime.

**Comment by vgvassilev** [comment]
> > Perhaps, the last fix I pushed will fix it...
> 
> If pre-existing we won't need a fix: it's a symptom of not providing `ROOT_INCLUDE_PATH` to these headers, so ROOT cannot find them at runtime.

I still think that’s better rebase if the original intent of the code and maybe it fixes it. I cannot merge it though…

**Pull request merged**
