### PR TITLE
[TMVA][SOFIE] Add GRU operator

### PR DESCRIPTION
**Pull request by lmoneta**
This Pull request replaces #8847 from @axmat   adding the GRU operator to TMVA SOFIE

In addition to the original code from Axmat it adds a full network test of a GRU  and fix some issues in the operator.

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Review by sitongan — APPROVED** [review]
lgtm!

**Pull request merged**
