### PR TITLE
Fix error handling in pyroot for python 3

### PR DESCRIPTION
**Pull request by MaxNoe**
This fixes pyroot for python 3.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks for your PR! Can you add a test or maybe just post a few lines of python code that are fixed by this PR, so we can add it to our python test suite ourselves?

**Comment by MaxNoe** [comment]
This is a back port for the 5-34-00 branch for this issue:
https://sft.its.cern.ch/jira/browse/ROOT-7640

**Comment by MaxNoe** [comment]
Without this patch, using python 3.6 in anaconda3:

```
>>> import ROOT
>>> h = ROOT.TH1D('test', 'test', 100, 0, 1)
AttributeError: type object 'TArray' has no attribute '__getitem__'

The above exception was the direct cause of the following exception:

SystemError: <built-in method mro of ROOT.PyRootType object at 0x17d57b8> returned a result with an error set
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxnoe/.local/root5/lib/ROOT.py", line 459, in __getattr1
    return getattr( self, name )
  File "/home/maxnoe/.local/root5/lib/ROOT.py", line 486, in __getattr2
    attr = _root.LookupRootEntity( name )
AttributeError: TH1D
```

**Comment by peremato** [comment]
We do not build ROOT 5.34 with Python 3.6 on our nightlies. We do not actively maintain this version anymore. So, I am going to merge the RP and cross the fingers.

**Comment by MaxNoe** [comment]
Thx

**Pull request merged**
