### PR TITLE
[RF] Make sure value servers of integrals are next direct value servers

### PR DESCRIPTION
**Pull request by guitargeek**
Integrals of derived PDFs have their client-server interface messed up,
and it's inconsistent with non-derived PDFs. Here is a reproducer:

```C++
void repro() {
    using namespace RooFit;
    RooRealVar x("x", "", 0, 1);

    RooRealVar par("par", "", -0.005, -5, 5);
    RooProduct parMod("par_mod", "", RooArgSet(par, RooConst(10)));

    RooGaussian gauss("gauss", "", x, parMod, RooConst(2.0));
    RooGenericPdf pdf("pdf", "gauss", gauss);

    std::unique_ptr<RooAbsReal> integ1{gauss.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
    integ1->Print("v");

    std::cout << std::endl;

    std::unique_ptr<RooAbsReal> integ2{pdf.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
    integ2->Print("v");
}
```

The integral of the Gaussian has the correct value (`V`) servers (the parameters of the Gaussian):
```
    (0x7ffc9b9bf798,-S) RooRealVar::x ""
    (0x7ffc9b9bf240,--) RooGaussian::gauss ""
    (0x7ffc9b9bff68,V-) RooProduct::par_mod ""
    (0x55ac531cd470,V-) RooConstVar::2 "2"
```

The integral of the `RooGenericPdf` should have the same value servers,
but it doesn't. Instead, it uses the leaves of the computation graph:
```
    (0x7ffc9b9bf798,-S) RooRealVar::x ""
    (0x7ffc9b9bec88,--) RooRealSumPdf::pdf ""
    (0x7ffc9b9bfb80,V-) RooRealVar::par ""
    (0x55ac51984c50,V-) RooConstVar::10 "10"
    (0x55ac531cd470,V-) RooConstVar::2 "2"
```

That means, the direct value server `par_mod` is **skipped** now,
misrepresenting the client-server relationship.

The new BatchMode makes strong use of the value-server interface for the
`RooFitDriver`, so it's very sensitive to `RooRealIntegrals` getting it
wrong.

That's why this commit suggests to change the logic in `RooRealIntegral`
to always add the next direct value servers that don't depend on the
integration variable, and not the leaves.

A unit test that verifies that the value servers of the integral are the
mathematically direct value servers and not the computation graph leaves
is also implemented.

Closes https://github.com/root-project/root/issues/11578.

The PR also fixes the same problem for the RooProjectedPdf, which is essentially a integral wrapper but it also got the server-client interface wrong. Now, it simply takes over the shape and value servers from the underlying integral, which is now implemented correctly.

### CODE REVIEW

**Comment by guitargeek** [comment]
To see where the crash happens exactly, as I didn't get it on my machine...

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you Jonas for this nice fix of a very difficult issue!

**Comment by elusian** [comment]
Thank you for the solution! Just a question, will this be backported to ROOT 6.26 or is it indeed too big of a change for a patch release?

**Comment by elusian** [comment]
Yes, I can try to switch to the dev3 LCG view, which should have ROOT master. I'll check in a few days, when the fix should be available in the builds

**Pull request merged**
