### PR TITLE
[RF] Bugfix in RooVDTHeaders.h.

### PR DESCRIPTION
**Pull request by manolismih**
Fix for https://github.com/root-project/root/issues/7240

### CODE REVIEW

**Comment by manolismih** [comment]
Tests don't test this part of code anyways.

**Comment by eguiraud** [comment]
> Tests don't test this part of code anyways.

should they?

**Review by eguiraud — APPROVED** [review]

**Comment by hageboeck** [comment]
@phsft-bot build with flags -Dvdt=OFF

**Comment by hageboeck** [comment]
> should they?

They should!

**Comment by eguiraud** [comment]
@hageboeck iow it would be nice to have at least one of the nightly builds with vdt=OFF (assuming we don't already)?

**Comment by manolismih** [comment]
@phsft-bot build with flags -Dvdt=OFF

**Comment by hageboeck** [comment]
Yes, I mentioned this a while ago, but somebody said that it would enlarge the build matrix. You can surely push this, though, because it's enough to just *convert* one of the builds.
Note, though, that `-Dvdt=OFF` doesn't work !!! You probably have to switch off `builtin_vdt` as well, because everything gets activated by default.

**Comment by hageboeck** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default with flags -Dvdt=OFF -Dbuiltin_vdt=OFF

**Comment by hageboeck** [comment]
Let's try on just one node for now ...

**Comment by hageboeck** [comment]
Ok, works.

**Comment by hageboeck** [comment]
@phsft-bot build with flags -Dvdt=OFF -Dbuiltin_vdt=OFF

**Pull request merged**
