### PR TITLE
Root 8563 fix out of bounds index

### PR DESCRIPTION
**Pull request by divserge**
fixed crash from the issue tracker ROOT-8563
"TMVA Multiclass example crash when running with argument "DNN""
The problem during logging the output from the last layer, due to the difference of sizes of testPattern and Output. Now the code takes into account the fact that there may be multiple outputs from the last layer of the Neural Net.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Can you remove the commented lines, please? No need to keep a commented version around, we have git to show us the previous version :-)

**Comment by divserge** [comment]
Yeah, sure. I just saw some commented lines there and figured i should leave it too) sorry)

**Comment by divserge** [comment]
in the last commit message it must be "+1" instead of "-1"

**Comment by vgvassilev** [comment]
@phsft-bot build!

@divserge could we add a regression test?

**Comment by divserge** [comment]
@vgvassilev Sure, I will add it.

**Comment by vgvassilev** [comment]
Thanks, please note you could add in-tree google tests if you need to.

**Comment by peremato** [comment]
@phsft-bot build

**Comment by lmoneta** [comment]
Thank you for this fix. It looks fine to me

**Pull request merged**
