### PR TITLE
V7 hist test fixes

### PR DESCRIPTION
**Pull request by claireguyot**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by HadrienG2** [comment]
@Axel-Naumann CI failure looks spurious too me.

**Comment by claireguyot** [comment]
Sorry, it's my fault @HadrienG2 , I didn't have a fork of roottest, so the build on Windows failed. I fixed it, so it should build now.

**Comment by HadrienG2** [comment]
I don't think I have an account on the Jenkins server, so let's go for the good old GitHub hack of restarting the CI by closing and reopening the PR ;)

**Comment by claireguyot** [comment]
Thanks!

**Pull request merged**
