### PR TITLE
Reduced ExcludeModules by one

### PR DESCRIPTION
**Pull request by arpi-r**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@arpi-r can you please fork https://github.com/root-project/roottest, windows build failed because it was not able to find your fork of roottest.git. Thanks!

**Comment by arpi-r** [comment]
@oshadura, I've created a fork of https://github.com/root-project/roottest

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
Unrelated CI failure `10:43:05 Build failed because: org.jenkinsci.plugins.workflow.job.WorkflowRun`

**Pull request merged**
