### PR TITLE
fix opening reference guide with .help Class

### PR DESCRIPTION
**Pull request by liginity**
As the current path for the reference guide would be "/doc/v624/...", there needs to be an extra "v" in the constructed path for the reference document.

### CODE REVIEW

**Review by jalopezg-r00t — CHANGES_REQUESTED** [review]
Thanks for your contribution, @liginity!  Could you make the requested changes before we can merge?

**Comment by liginity** [comment]
> Thanks for your contribution, @liginity! Could you make the requested changes before we can merge?

**Comment by liginity** [comment]
I am sorry that as I am not familiar with GitHub pull request, I just clicked the button closing the pull request.

I have added another commit thanks to your suggestion, @jalopezg-r00t .

**Review by jalopezg-r00t — APPROVED** [review]
LGTM.

**Comment by jalopezg-r00t** [comment]
@phsft-bot build

**Comment by jalopezg-r00t** [comment]
@phsft-bot build

**Comment by jalopezg-r00t** [comment]
@phsft-bot build

**Pull request merged**
