### PR TITLE
[RF] Implement `RooDataSet::addColumns` in terms of `addColumn`

### LINKED ISSUE #8787: [RF] RooDataSet columns added with addColumns method not copied correctly in reduce
Affects at least 6.22/08

Minimal reproducer:

```
{
    RooRealVar x("x","x",1);
    RooRealVar w("w","w",1);
    RooDataSet d("d","d",w,"w");

    d.addColumns(x);

    for(int i=0;i<10;i++) {
        x = i; d.add(x,0);
    }

    // d now has 10 entries with x values increasing
    for(int i=0;i<d.numEntries();i++) std::cout << d.get(i)->getRealValue("x") << ","; std::cout << std::endl;

    // now reduce the dataset and repeat:
    auto e = d.reduce("x>5");
    for(int i=0;i<e->numEntries();i++) std::cout << e->get(i)->getRealValue("x") << ","; std::cout << std::endl;
}
```

This outputs:

```
0,1,2,3,4,5,6,7,8,9,
9,9,9,9,
```

where it should really output:

```
0,1,2,3,4,5,6,7,8,9,
6,7,8,9,
```

If the "x" column was included when the dataset is constructed, the reduction works correctly.

### PR DESCRIPTION
**Pull request by guitargeek**
Re-implementing the column adding functionality for multiple columns at
once is not worth it. Adding the columns one after the other has little
overhead, and the current implementation of
`RooVectorDataStore::addColumns` is buggy anyway (see #8787).

Closes #8787.

### CODE REVIEW

**Review by lmoneta — COMMENTED** [review]
Is `addColumns` a public function ? Maybe we should add a deprecation message before removing it ?

**Comment by guitargeek** [comment]
> Is `addColumns` a public function ? Maybe we should add a deprecation message before removing it ?

Good point, I just have brought back `RooAbsDataStore::addColumns` in the same way as I did for the RooDataSet function: it is now implemented in terms of `RooAbsDataStore::addColumn`. LIke this, there is not public interface change at all and we don't need an entry in the release notes.

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by lmoneta — APPROVED** [review]
LGTM!

**Pull request merged**
