### PR TITLE
highlight mode for histogram or graph objects

### PR DESCRIPTION
**Pull request by musinsky**
Please see https://sft.its.cern.ch/jira/browse/ROOT-6792 or https://github.com/musinsky/ROOTHighlight

### CODE REVIEW

**Comment by couet** [comment]
Hello Jan. I think what is missing is the motivation/documentation of this new functionally. May be it can go in the THistPainter and TGraphPainter doc ? right now it is not easy to understand how to use it.

**Comment by couet** [comment]
Yes the best would be to add a section in: https://root.cern/doc/master/classTHistPainter.html
Look how it is done in THistPainter.cxx header.

**Comment by musinsky** [comment]
Added documentation. Relevant pages:
http://alice.saske.sk/rootdoc/html/classTHistPainter.html
http://alice.saske.sk/rootdoc/html/classTGraphPainter.html

**Comment by couet** [comment]
Hello Jan. Thanks for the doc but the html files are not what I am looking for. The doc is directly in THistPainter.cxx .. the html files are generated for them. Have the look at the header of THistPainter.cxx

**Comment by musinsky** [comment]
Hello Olivier, the doc was generated from sources files (THistPainter.cxx and TGraphPainter.cxx files) with doxygen. Sources files with doc was added to commit https://github.com/root-project/root/pull/1839/commits/5083799f3d89d76a8c4ac42f8bc5ebfcb487d2f6, sorry for confusing comment.

**Comment by couet** [comment]
Oh i see ! .. sorry that was my confusion ...

**Comment by couet** [comment]
Hello Jan. Sounds good and ready to be committed. We are now in the process of making ROOT 6.14
I think it is better if we commit your changes just after we do this new release. That will put less stress on us to polish this new feature.

**Comment by musinsky** [comment]
OK, after ROOT new release.

**Comment by couet** [comment]
Thanks for your patience :-)

**Comment by couet** [comment]
The first animated gif you added in http://alice.saske.sk/rootdoc/html/classTHistPainter.html#HP30 is a bit wide which forces the web bowser to adjust the display width, which later may creates weird layout of the subsequent pages one will browse . Would it be possible to have this animation such it does not force the web browser to adjust the display width? may be by putting the two canvas on top of each other and not side by side ?

**Comment by musinsky** [comment]
I can create a new animation (this is not a problem), which width is optimal (maximum) ?
[Original gif](https://raw.githubusercontent.com/musinsky/root/5083799f3d89d76a8c4ac42f8bc5ebfcb487d2f6/documentation/doxygen/images/hlHisto3.gif) has size 1200x530, [Half size gif](https://raw.githubusercontent.com/musinsky/ROOTHighlight/master/tmp/hlHisto3_half.gif) has 600x265.
Create animated gif with a width of around 800-900 ?

**Comment by couet** [comment]
I think that keeping the same size for the canvases but drawing them on top of each other should be fine.

**Comment by musinsky** [comment]
I have tried to make with two canvases (two gifs), but problem with "synchronization" in browser (gif1 "start animating" in different time as gif2, see on this temporary [site](http://alice.saske.sk/rootdoc2/html/classTHistPainter.html#HP30)), must be as one animated gif.

I think there are only two possibilities:
 * create a new animation with width for example 900
 * or set width in source ```\image html hlHisto3.gif "Highlight mode" width=900```

**Comment by couet** [comment]
Why don't you simply make one animated gif with the two canvases on top of each other ? it should be possible ? The tool you are using to make them does not allow this ?

**Comment by musinsky** [comment]
Now I've understood, sorry ... will be done, no problem

**Comment by musinsky** [comment]
Done (and regenerated html doc with doxygen)
http://alice.saske.sk/rootdoc/html/classTHistPainter.html#HP30

**Comment by couet** [comment]
much better ! Thanks !

**Pull request merged**
