### PR TITLE
[rootcling] Treat warnings coming from ROOT as errors.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The line
```
#pragma link C++ namespace FdUtil;
```
in roottest/root/meta/rootcling/classInLinkdef.h is indeed spurrious/unintended.

**Comment by oshadura** [comment]
@vgvassilev Nice!!!  Do you have matching PR in rooottest?

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@pcanal, those failures seem unrelated to me. What's your take?

**Pull request merged**
