### PR TITLE
WIP: Global RW lock

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@pcanal, could you please address the clang-format complaints?

I am building and testing locally, but before merging, I'd like the checks to be green.

**Comment by amadio** [comment]
`TBufferMerger` random number generation test on my machine (Core i7 6700).

Differences are not so visible below, but it's possible to notice that waits are slightly more costly (wider gaps), and the total runtime is longer. The wait count (due to the new locks on global containers) goes from ~1500 to about ~34300. These changes need to be checked on machines with higher core count and should probably be discussed with experiments too.

*before*
screenshot

*after*
screenshot

**Comment by pcanal** [comment]
The first large gap (just before 4s) seems longer in the 'after'.  Do we know where the other threads are stopped (and what the running thread does) both in the before and the after.

Do we know where (some of) the gaps are stopped in the main regime?

> TBufferMerger random number generation test on my machine (Core i7 6700).

Is that with or without the lock removed (both test are needed to get a clear view).

**Comment by amadio** [comment]
> The first large gap (just before 4s) seems longer in the 'after'. Do we know where the other threads are stopped (and what the running thread does) both in the before and the after.

Yes, that's the point at which `LoadClassInfo()` gets called. One thread works on that, while others are waiting for it to finish. That particular gap only happens once.

> Do we know where (some of) the gaps are stopped in the main regime?

These stops are on the global lock at several points of the code, it's not a single type of wait.

>> TBufferMerger random number generation test on my machine (Core i7 6700).
> Is that with or without the lock removed (both test are needed to get a clear view).

I wanted to test the impact of your changes, so that means this branch against master (i.e., no, the lock was not removed). I will test with the lock removed tomorrow.

**Comment by pcanal** [comment]
> Yes, that's the point at which LoadClassInfo() gets called. One thread works on that, while others are waiting for it to finish. That particular gap only happens once.

One thing I would to explore is why it is (or seems to be) larger in the new case and why there is additional waits 'just' right after.

**Comment by amadio** [comment]
This has been manually merged into master. Closing.

**Pull request closed without merging**
