### PR TITLE
Fix for Apple Silicon M1 - gfortran does not accept -m64

### PR DESCRIPTION
**Pull request by pzhristov**
This fixes an issue with the compilation of GEANT3 on M1. GEANT3 cmake includes ROOT_USE_FILE and updates CMAKE_Fortran_FLAGS, so -m64 was propagated to the compiler and not recognised.

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build just on mac11arm/cxx17

**Comment by pzhristov** [comment]
All the issues in CI have nothing to do with the PR.

**Review by oshadura — APPROVED** [review]
@pzhristov sadly I can't try your setup (root+geant3), so I trust you

**Pull request merged**
