### PR TITLE
[io] do not use single-file-merge shortcut if filters are specified

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:

Fixes https://github.com/root-project/root/issues/13359

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
LGTM.  Thanks. (since the result is wrong without this patch, we may want to add a test).

**Comment by ferdymercury** [comment]
> since the result is wrong without this patch, we may want to add a test

Added test, but it needs revision from your side as I am not fully sure whether it works.

**Comment by ferdymercury** [comment]
@bellenot Do you have any idea why the "result" is a nullptr in my test?

```
io/io/test/TFileMergerTests.cxx:99: Failure
result is nullptr
```

**Comment by bellenot** [comment]
@ferdymercury no idea. I can try to debug it if you have time to wait, or ask @pcanal who is our I/O expert...

**Comment by ferdymercury** [comment]
> @ferdymercury no idea. I can try to debug it if you have time to wait, or ask @pcanal who is our I/O expert...

Thanks! I think it's solved now.

**Review by pcanal — APPROVED** [review]
LGTM

**Pull request merged**
