### PR TITLE
[modules][cxxmodules] Switch back to umbrella.

### PR DESCRIPTION
**Pull request by vgvassilev**
…modules

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On -Druntime_cxxmodules=On -Dctest_test_exclude_none=Оn

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
Can we also add the warning then to ignore it `-Wno-incomplete-umbrella`?

**Comment by vgvassilev** [comment]
Sure, OTOH, it will be nop because the quoted issue was resolved on our side, too. The issue suggests that we have:
```
module M1 {
  umbrella "NonExistent" // expected-error here.
  module * { export * }
}

module M2 {
  umbrella "Existent"
  module * { export *}
}
```

We always create a folder GL, so AFAICT we are not hitting this warning.

Looks like the PR and the commit message were misnomers :( Fixing...

**Pull request merged**
