### PR TITLE
[math] Fix inconsistent behaviour of TFormula parameter functions

### LINKED ISSUE #7805: Inconsistent and unintuitive behaviour of TFormula::SetParNames and TFormula::SetParameters
### Explain what you would like to see improved

I would like functioning of both `TFormula::SetParNames()` and `TFormula::SetParameters()` to be more consistent and intuitive. 

#### Why `TFormula::SetParNames()` and `TFormula::SetParameters()` are inconsistent 
`TFormula::SetParNames()` sets the names of parameters in order (1st argument sets name of 1st parameter, 2nd argument sets name of 2nd parameter and so on), and it resets the name of remaining parameters to default value (which is, `p[i-1]` for `ith` parameter).

But, `TFormula::SetParNames()` only supports upto 11 arguments, and only resets upto 11th parameter. This lead to inconsistencies when number of parameters are above 11.

For example:

```c++
TFormula f("f", "x*[0]*[1]*[2]");
TFormula g("g", "x*[0]*[1]*[2]*[3]*[4]*[5]*[6]*[7]*[8]*[9]*[10]*[11]*[12]");

f.SetParNames("a", "b", "c", "d");  // works perfectly
g.SetParNames("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m"); // error
```

and also, if we assign names to all parameters using `TFormula::SetParName(Int_t, const char*)` and then call `TFormula::SetParNames()`, then it will only reset upto 11th parameter, parameters after that will have their assigned names.

Same issues exists with `TFormula::SetParameters()`

#### Why do I think `TFormula::SetParNames()` and `TFormula::SetParameters()` are unintuitive 

Consider this example:

```c++
TFormula f("f", "x*[0]*[1]*[2]*[3]");
f.SetParName(3, "lastParameter");
// Parameters names: p0, p1, p2, lastParameter
f.SetParNames("a", "b");
// Parameters names: a, b, p2, p3
```
User generally would not expect that `TFormula::SetParNames()` will change name of parameters that he/she did not specify, and will thus expect parameters names at the end of this snippet to be: `a, b, p2, lastParameter`.

Same issue exists with `TFormula::SetParameters()`.

Thus, I would like to modify `TFormula::SetParNames()` and `TFormula::SetParameters()` such that they do not reset the parameter names and values respectively. 

### Optional: share how it could be improved

Both `TFormula::SetParNames()` and `TFormula::SetParameters()` can be improved by replacing current implementation by variadic template function, this will remove the constraint of having fix number of arguments. It will also reduce the code duplication in both of these functions.

It is also trivial to disable the resetting of parameters to their default values and names using variadic template function.

### Setup

Root version: 6.25/01
Operating system: Ubuntu 20.04
How you obtained ROOT: built it from source

### PR DESCRIPTION
**Pull request by parth-07**
This PR aims to fix the problem of inconsistency in `TFormula::SetParNames()` and `TFormula::SetParameters()` functions as described in #7805.

I have added warning if more values are provided than the actual number of parameters of `TFormula` object, original behaviour of the function is maintained apart from the added warning.

Some test will fail due to the added warning, please tell if I should remove the warning or resolve the root cause of the warnings ( For instance, `TF1` using `TFormula::SetParameters()` and always passing 11 arguments is one cause of failing tests) 

I would also like to slightly modify behaviour of these functions such that value and names of only specified parameters should be changed, current behaviour is to reset the value and names of parameters which aren't specified, but this change may negatively impact programs using these functions. But still, I think this change will make these functions more intuitive. Please tell if I should add this change. 

This PR fixes #7805

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build

**Review by lmoneta — COMMENTED** [review]
Very nice improvements and I agree it is consistent now.
I think we should then fixes also `TF1::SetParNames` and `TF1::SetParameters` to be consistent and since TF1 is probably more used than TFormula itself

**Comment by parth-07** [comment]
> Very nice improvements and I agree it is consistent now.
> I think we should then fixes also `TF1::SetParNames` and `TF1::SetParameters` to be consistent and since TF1 is probably more used than TFormula itself

Yes agreed, I will make these changes in this PR.

**Comment by parth-07** [comment]
> I think we should then fixes also `TF1::SetParNames` and `TF1::SetParameters` to be consistent and since TF1 is probably more used than TFormula itself

`TF1::SetParNames` and `TF1::SetParameters` member functions are virtual, and C++ currently do not support virtual function templates. Can you suggest some other way to make these functions generic ? Normal variadic functions can be used, but they are not very easy to work with and maintain, and also do not provide static type checking.

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
Since I still think this is a nice improvement, I resurrected this PR by rebasing the changes on top of ROOT `master`. Let's see what the CI says now!

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
Hi @parth-07! I have resurrected this PR in order to close the underlying issue.

I simplified your implementation a bit, and also did the same treatment with the variadic template methods to the `TF1Parameters` class.

I didn't do this for the `TF1` though, because variadic templates would break the support for the context menu in the TBrowser.

But what is consistent now is that both `SetParNames` and `SetParameters` have default argument values that correspond to the parameters or names not changing. For the Parameters, this is encoded by `NaN`, and for the names it is encoded with empty strings.

**Comment by parth-07** [comment]
Hi @guitargeek, thank you for resurrecting the pull request.

**Pull request merged**
