### PR TITLE
Build built-in LZMA with O3 optimization level

### PR DESCRIPTION
**Pull request by eguiraud**
@bellenot I'm not sure what to do about windows, the configure command is empty there?

### CODE REVIEW

**Comment by eguiraud** [comment]
@oshadura yes, the following minimal reproducer runs in 13 seconds on my workstation with built-in LZMA, and in 6 with LZMA installed from system packages. 75% of the runtime is spent in `R__zipLZMA` in the slow case, 48% in the fast case.

This patch fixes that runtime difference.

```cpp
// write_lzma.cpp
#include <ROOT/RDataFrame.hxx>                                                                                          
#include <TStopwatch.h>                                                                                                 
#include <iostream>                                                                                                     
                                                                                                                        
int main() {                                                                                                            
   ROOT::RDF::RSnapshotOptions opts;                                                                                    
   opts.fCompressionAlgorithm =  ROOT::kLZMA;                                                                           
   opts.fCompressionLevel = 6;                                                                                          
   opts.fLazy = true;                                                                                                   
   auto trigger = ROOT::RDataFrame(50000000).Define("x", [] { return 42; }).Snapshot<int>("t", "f.root", {"x"}, opts);  
   TStopwatch s;                                                                                                        
   s.Start();                                                                                                           
   *trigger;                                                                                                            
   s.Stop();                                                                                                            
   std::cout << s.RealTime() << std::endl;                                                                              
   return 0;                                                                                                            
}
```

**Comment by eguiraud** [comment]
@oshadura now that I think of it, do you think other built-ins might have similar issues?

**Comment by oshadura** [comment]
ZSTD is OK, we added ```-03``` with @bbockelm  https://github.com/root-project/root/blob/560b27ab6ebeed6d7dc7c936ca76159b45193525/builtins/zstd/CMakeLists.txt#L89

ZLIB as well is fine: https://github.com/root-project/root/blob/560b27ab6ebeed6d7dc7c936ca76159b45193525/builtins/zlib/CMakeLists.txt#L119-L125

**Comment by oshadura** [comment]
> @oshadura yes, the following minimal reproducer runs in 13 seconds on my workstation with built-in LZMA, and in 6 with LZMA installed from system packages. 75% of the runtime is spent in `R__zipLZMA` in the slow case, 48% in the fast case.
> 
> This patch fixes that runtime difference.
> 
> (EDIT: plus from the [build log](https://github.com/root-project/root/files/5049830/LZMA-build-out.log) of built-in LZMA you can see no optimization flags are added at the moment)
> 
> ```c++
> // write_lzma.cpp
> #include <ROOT/RDataFrame.hxx>                                                                                          
> #include <TStopwatch.h>                                                                                                 
> #include <iostream>                                                                                                     
>                                                                                                                         
> int main() {                                                                                                            
>    ROOT::RDF::RSnapshotOptions opts;                                                                                    
>    opts.fCompressionAlgorithm =  ROOT::kLZMA;                                                                           
>    opts.fCompressionLevel = 6;                                                                                          
>    opts.fLazy = true;                                                                                                   
>    auto trigger = ROOT::RDataFrame(50000000).Define("x", [] { return 42; }).Snapshot<int>("t", "f.root", {"x"}, opts);  
>    TStopwatch s;                                                                                                        
>    s.Start();                                                                                                           
>    *trigger;                                                                                                            
>    s.Stop();                                                                                                            
>    std::cout << s.RealTime() << std::endl;                                                                              
>    return 0;                                                                                                            
> }
> ```

btw, nice benchmark!!! I vote to added it in rootbench.git :+1:

**Comment by eguiraud** [comment]
> I vote to add it in rootbench.git +1

I bet we will already see an improvement in the current benchmark?

**Comment by bellenot** [comment]
> @bellenot I'm not sure what to do about windows, the configure command is empty there?

liblzma.lib is shipped pre-build on Windows

**Comment by eguiraud** [comment]
Thanks Bertrand, we are good to go then as far as I can tell.

**Pull request merged**
