### PR TITLE
Require C++14 for ROOT, C++17 for ROOT7

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Review by bellenot — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Pull request merged**
