### PR TITLE
[Exp PyROOT] Make tutorials/pyroot/demo.py run also for Python3

### PR DESCRIPTION
**Pull request by maxgalli**
raw_input is simply input in Python 3

suggested in https://sft.its.cern.ch/jira/browse/ROOT-10721

### CODE REVIEW

**Comment by etejedor** [comment]
No need to wait for the builds (this tutorials does not even run because it is interactive), merging.

**Comment by akira-okumura** [comment]
Thank you. `gui_ex.py` and `parse_CSV_file_with_TTree_ReadStream.py` have Python-2-style`print`.

**Comment by etejedor** [comment]
Thanks @akira-okumura ! @maxgalli can you have a look and propose another PR ?

**Comment by maxgalli** [comment]
> parse_CSV_file_with_TTree_ReadStream

The print lines that I see in these two scripts are ```print('returning 0')``` and ```print("Usage: %s file_to_parse.dat" % sys.argv[0])```, both Python3 compatible, fixed by this commit: 
https://github.com/root-project/root/commit/dffafb93c8783448b3c98bcbad04cba266d80ff9#diff-bfad69ddd3dd134b48f95430a6008ae4
Am I correct?

On the other hand, @etejedor, ```guy_ex.py``` fails in pyroot_experimental due to a ```TPyDispatcher``` class that doesn't seem to have been ported yet.

**Pull request merged**
