### PR TITLE
Allow any RooAbsReal instead of just RooRealVar for params. 

### PR DESCRIPTION
**Pull request by will-cern**
Also make isBinnedDistribution depend on the vars rather than always return true.

## Changes or fixes:

Makes ParamHistFunc more flexible/powerful

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by will-cern** [comment]
Sorry, overlooked a dependency that needed changing ... should be fixed now

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
LGTM, thank you very much for the improvement!

**Comment by will-cern** [comment]
As always, any chance of it being pulled into the current release series (6.26) ?

**Comment by guitargeek** [comment]
Yes, it's a small change so I think a backport doesn't harm. I have added the PR to the list of things to backport so I won't forget it:
https://github.com/root-project/root/issues/10493

**Pull request merged**
