### PR TITLE
[CMake][PyROOT] Cache PyROOT variables needed by root-config --config

### PR DESCRIPTION
**Pull request by etejedor**
If we don't cache the PyROOT library, include dir and version variables, they will not be found by CMake in the loop over `CACHE_VARIABLES` which sets `ROOT_CONFIGARGS` in the main `CMakeLists.txt`, and therefore `root-config --config` will not show them. This affects master and 6.22.

This was reported by:
https://root-forum.cern.ch/t/python-in-root-6-22/39891

Note that `PYTHON_EXECUTABLE` is not cached, since caching it can interfere with the user setting of that same variable, when specifying that only one Python installation should be considered (if we cache it and reconfigure, CMake thinks it is the user who is setting it). This is not a problem, since `PYTHON_EXECUTABLE` was never offered in `root-config --config` in previous ROOT versions (the loop over `CACHE_VARIABLES` in the main `CMakeLists.txt` filters it out).

The alternative to this implementation, if we don't want to cache these PyROOT variables, would be to add them to `ROOT_CONFIGARGS` in the main `CMakeLists.txt`, independently of `CACHE_VARIABLES`.

### CODE REVIEW

**Comment by oshadura** [comment]
@etejedor thanks a lot for digging out this nice solution. We had similar solution before https://github.com/root-project/root/commit/ba383e2411d3be0d3cad0bec4f15902217179f41 except $PYTHON_EXECUTABLE was cached and causing other problem (@maxgalli fixed in commit I showed before). Do you know a reproducer that we can check that @maxgalli's  issue fixed by him is not back?

**Comment by oshadura** [comment]
updates drom @etejedor : PR was tested with/without  specifying ```PYTHON_EXECUTABLE```: it works!!! (it needed to be backported to 6.22 as well)

**Comment by etejedor** [comment]
@phsft-bot build just on mac1014/python3

**Comment by etejedor** [comment]
@phsft-bot build just on ROOT-debian10-i386/cxx14

**Comment by etejedor** [comment]
@phsft-bot build just on ROOT-debian10-i386/cxx14, mac1014/python3

**Pull request merged**
