### PR TITLE
Update ROOT and Cling to LLVM18

### PR DESCRIPTION
**Pull request by devajithvs**
# This Pull request:

### Rebase

A few relevant LLVM commits that were referenced for the rebase:

- https://github.com/llvm/llvm-project/commit/95dd17848383315050a5d64051bd695d0a653c51
- https://github.com/llvm/llvm-project/commit/8d67b9e2461d654c0a3657e511e2295006f23748
- https://github.com/llvm/llvm-project/commit/9478f661c26fbc22491218477917df5d8d73c51c
- https://github.com/llvm/llvm-project/commit/6a6994cc9bc0327aaf8b005c650ff5eb29d2bcce
- https://github.com/llvm/llvm-project/commit/8b1771bd9f304be39d4dcbdcccedb6d3bcd18200 

### Notes
- Cling and Root commits for the rebase are kept separate for now (can squash similar commits together later).
- Also added a temporary commit https://github.com/root-project/llvm-project/commit/4066693bd33bc93bdee33415b7f5773bda1d1f49 in LLVM to prevent building of mlgo-utils, which will not compile when all the test folders are removed. We can either keep it or add an exception to this file in the Root GitHub workflow to not remove the test folders under mlgo-utils.

#### TO DISCUSS/PROPERLY FIX
- [x] The commit 64f7cf6318ca9a4da766b02c45fc81aea7762f8e is memleaking; it is a temporary fix for now to prevent some failing tests, like `gtest-roofit-histfactory-test-testHistFactory`.
  - Fixed with: https://github.com/root-project/root/pull/16314
- [x] This commit: https://github.com/root-project/root/pull/15696/commits/de5d1413e07170e396ac51d982c0844e4f548f4b is a temporarily fix reintroducing a memory leak. 
  - Fixed with: https://github.com/root-project/root/pull/15696/commits/2c2d4dc2bf3ebe0f475b05a66a377c2467525d9d
- [x] This commit: d79963ecb74f957a332409ed91b106a0f53da10a fixes an issue with failing tests like `tutorial-hist-cumulative` when JITLink is turned on. This works for now, but will need to investigate further on why resource trackers were not destructed in the right order.
  - Not a critical issue: Can also look into this later after the merge.
- [x] Discussion on a proper solution for the macOS modulemap issue
  - Fixed with: https://github.com/root-project/root/pull/16315

## Checklist:
- [x] Fix mac13 build
- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by stephanlachnit** [comment]
I know this is totally not relevant for you, but I am still wondering: does this allow me to use system clang or are there still downstream patches required?

**Comment by hahnjo** [comment]
> I know this is totally not relevant for you, but I am still wondering: does this allow me to use system clang or are there still downstream patches required?

Hi Stephan, no we still require downstream patches. Their number gets reduced on every upgrade, you can track the status for LLVM 18 here: https://github.com/root-project/llvm-project/commits/ROOT-llvm18. More importantly, and not yet reflected in `ROOT-llvm18`, we will now also require a patch to the core LLVM JIT infrastructure (until upgrading past LLVM 19): https://github.com/llvm/llvm-project/pull/95532

**Comment by stephanlachnit** [comment]
Thanks for the update!

**Comment by hahnjo** [comment]
FWIW the current state compiles fine on RISC-V and is at least able to run `df103_NanoAODHiggsAnalysis.py` :wink:

**Comment by vgvassilev** [comment]
@smuzaffar, @devajithvs and @hahnjo have everything working reasonably with the llvm18 upgrade. Can you check this PR against cmssw?

**Comment by vgvassilev** [comment]
> @smuzaffar, @devajithvs and @hahnjo have everything working reasonably with the llvm18 upgrade. Can you check this PR against cmssw?

@iarspider, could you give us a hand?

**Comment by dpiparo** [comment]
> > @smuzaffar, @devajithvs and @hahnjo have everything working reasonably with the llvm18 upgrade. Can you check this PR against cmssw?
> 
> @iarspider, could you give us a hand?

I allow myself to add @aandvalenzuela to perhaps get some help.

**Comment by smuzaffar** [comment]
ROOT failed to build for aarch64, the build error is
```
Processing hsimple.C...
cling JIT session error: Failed to materialize symbols: { (<Process Symbols>, { DW.ref.__gxx_personality_v0 }) }
ninja: build stopped: subcommand failed.
error: Bad exit status from /data/cmsbld/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/tmp/rpm-tmp.3N7prC (%build)
```

See https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b2e919/41190/externals/root/6.33.01-1689b1f60f821828a7e2948d6cf5f908/log for detail root build log

**Comment by smuzaffar** [comment]
For x86_64, this change passed all cmssw [CI tests](https://github.com/cms-sw/root/pull/209#issuecomment-2316914821)

**Comment by vgvassilev** [comment]
> For x86_64, this change passed all cmssw [CI tests](https://github.com/cms-sw/root/pull/209#issuecomment-2316914821)

Does both have the same version of gcc? Does one have `libgcc_s.so` and the other `libgcc.a`? And which one?

**Comment by iarspider** [comment]
Yes, both builds used the same version of gcc (12.3.1), and both used `libgcc_s.so`

**Comment by smuzaffar** [comment]
@vgvassilev , gcc version is same (note that we use our own gcc and not from system). Both archs has `libgcc_s.so` in its lib64 path and `libgcc.a` in `lib/gcc/<arch>-redhat-linux-gnu/12.3.1/` directory [b]

[a]
- x86_64
```
Singularity> gcc --version
gcc (GCC) 12.3.1 20230527
```

- aarch64
```
Singularity> gcc --version
gcc (GCC) 12.3.1 20230527
```

[b]
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/libgcc.a
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/libgcc_eh.a
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libgcc_s.so
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libgcc_s.so.1
```

```
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02853/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/aarch64-redhat-linux-gnu/12.3.1/libgcc.a
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02853/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/aarch64-redhat-linux-gnu/12.3.1/libgcc_eh.a
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02853/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libgcc_s.so
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02853/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib64/libgcc_s.so.1
```

**Comment by vgvassilev** [comment]
@smuzaffar, can you rerun testing of this PR?

**Comment by smuzaffar** [comment]
@vgvassilev , @aandvalenzuela has already started the [tests for aarch64](https://github.com/cms-sw/root/pull/209#issuecomment-2331962555)

**Comment by smuzaffar** [comment]
FYI, CMSSW tests for both x86_64 and aarch64 passed now

**Comment by dpiparo** [comment]
Thanks a lot @smuzaffar for the support you and the core team provided to this endeavor.

**Review by vgvassilev — APPROVED** [review]
Thanks for all the work you've done! Please make sure you take a look at the commit history and if you like it, go ahead, LGTM!

**Pull request merged**
