### PR TITLE
Fix hist headers Doxygen syntax

### PR DESCRIPTION
**Pull request by couet**
Revisiting the hist/hist headers to make them doxygen compatible . Some data members were not commented properly (not the right format). So the comments do not appear on the ref guide, or worst, sometimes a wrong comment appear on a data member.

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Review by lmoneta — APPROVED** [review]
Thank you Olivier for these fixes requiring a big editing in all these files !! 
Looks great to me!

**Comment by couet** [comment]
I am a bit worrying about the fails... It does not looks like connected to this changes, but ....

**Comment by couet** [comment]
@phsft-bot build

**Pull request merged**
