### PR TITLE
[TMVA/BDT/IMT] Limit the size of TrainNodeInfo objects to ten times w…

### PR DESCRIPTION
**Pull request by pseyfert**
…hat the user asked for

Picking integer binning for the cut scan in node training otherwise
results in unreasonably large 2-D arrays, of which one needs at least
number_of_threads+2 (accumulate initialization, one per thread result,
one target)

This is the memory issue I mentioned in my previous PR.
Turns out I had an integer branch in my training data with a large difference between largest and smallest value, and the number of events in the sample was big enough to hit the if block in DecisionTree.cxx here:
```
   // #### When nbins is low compared to ndata this version of parallelization is faster, so use it 
   // #### Parallelize by chunking the data into the same number of sections as we have processors
   if(eventSample.size() >= cNvars*fNCuts*nPartitions*2)
```
which results in the instantiation of a few TrainNodeInfo objects (one per thread, on top of the target, and one for the initialization of std::accumulate, and i suspect the +operator adds temporary overhead. Each of which containing six 2dimensional arrays like:
```
   std::vector< std::vector<Double_t> > nSelS;
```
getting as size:
```
      nSelS            = std::vector< std::vector<Double_t> >(cNvars);
          nSelS[ivar]            = std::vector<Double_t>(nBins[ivar], 0);
```
i.e. number or training variables times [ nCuts, specified by the user (20 in the tutorials) **OR** difference between the largest int and smallest int in the tree, for integer variables ]. For me this was somewhere above 4GB. The else block works because on of these huge things is not a problem, but already with one thread the if version (given the +2 for the MapReduce) ran out of RAM.
```

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by ashlaban** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
HI Paul, 
Thank you very much for the fix. It looks fine to me. 
It would be just nice to have a test for this with integer variables with a large range

**Comment by pseyfert** [comment]
closing all my cern related PRs as won't-pursue-anymore w/o checking status

**Pull request closed without merging**
