### PR TITLE
[TMVA] Remove useless one-line scripts from PyKeras examples that cau…

### PR DESCRIPTION
**Pull request by stwunsch**
…sed errors in the incremental tests, update tutorials to Keras 2.x API

### CODE REVIEW

**Comment by stwunsch** [comment]
@dpiparo This fixes http://cdash.cern.ch/viewTest.php?onlyfailed&buildid=459248

**Comment by stwunsch** [comment]
Just realized that #1353 does the switch to the Keras 2.x interface (partially) in the tutorial. Please merge this first, then I'll rebase this PR.

**Comment by stwunsch** [comment]
@lmoneta Rebased with the current master!

**Comment by lmoneta** [comment]
@phsft-bot build

**Pull request merged**
