### PR TITLE
Significantly speed-up back-propagation

### PR DESCRIPTION
**Pull request by steremma**
This is achieved by parallelizing the weight update process.

This PR does not fix the code quality issues mentioned by @Axel-Naumann or the warnings, since these issues are handled by #2321

### CODE REVIEW

**Comment by steremma** [comment]
build!

**Comment by steremma** [comment]
@phsft-bot build!

**Comment by ashlaban** [comment]
@phsft-bot build!

**Comment by ashlaban** [comment]
Looks good to me!

**Comment by steremma** [comment]
I was not aware of this repo, thanks @vgvassilev 
I will discuss with @lmoneta and @ashlaban about the details and soon add a benchmark (it was already part of our goals for this summer)

**Pull request merged**
