### PR TITLE
[cxxmodules] Do not use rdict files.

### PR DESCRIPTION
**Pull request by vgvassilev**
We would like to get some performance evaluations from the cmssw side. This PR is a continuation from PR #3012 

@smuzaffar, @mrodozov, could you build ROOT's cxxmodule IB against this PR and see if there are performance difference with and without this PR?

### CODE REVIEW

**Comment by mrodozov** [comment]
In the branch we are using https://github.com/cms-sw/root/compare/cmscxx/master/610a87c0a2 
for building the modules IB
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/cxxmodule/root.spec#L6
this change is already there. 
https://github.com/cms-sw/root/blob/cmscxx/master/610a87c0a2/core/metacling/src/TCling.cxx#L1342
We can try running putting it in and out again but for this we have agree on some set of performance tests. 
Do you discussed anything like that with Shahzad or you have any suggestion ?

**Comment by mrodozov** [comment]
Also any suggestion for testing is probably better to go as PR against this base branch:
 https://github.com/cms-sw/root/compare/cmscxx/master/610a87c0a2
which I don't know what Shahzad used to branch from (I think its master if we follow our name convention for naming branches) and which is now long list of commits behind (and as it seems unmergable)
https://github.com/cms-sw/root/compare/cmscxx/master/610a87c0a2...vgvassilev:cmssw-no-rdicts?expand=1
A PR against this branch could be tested (for integration, not for performance) right away. 
This will make it easier to manual build with our tools and manually tested from there

**Comment by vgvassilev** [comment]
Ok, we will need to bump the cxxmodules branch and apply this PR. The rdict changes seem to have landed after 610a87c0a2

**Comment by mrodozov** [comment]
there are custom commits on that branch 
https://github.com/cms-sw/root/commits/cmscxx/master/610a87c0a2
which I'd guess up to here : https://github.com/cms-sw/root/commit/610a87c0a2d2339cbeea08dd8fc0daf29650ee18
are whats on master and after - fixes from Yuka and Oksana. 
Should I get whats on master and put those other commits on top ?

**Comment by oshadura** [comment]
@vgvassilev what do you want to measure? CMSSW performance? Unfortunately C++ modules IBs are broken, so it will require some time fixing them..

**Comment by vgvassilev** [comment]
@mrodozov, yes we will need to rebase it. 
@oshadura, yes, I want performance numbers. What’s broken ?

**Comment by oshadura** [comment]
Hi @vgvassilev @mrodozov, I have a PR here: https://github.com/cms-sw/root/pull/129

**Comment by vgvassilev** [comment]
Closing the PR now and we can reopen if needed.

**Pull request closed without merging**
