### PR TITLE
[Cling]Setup Github Actions CI for Linux and macOS

### PR DESCRIPTION
**Pull request by reikdas**
(Mirror of https://github.com/root-project/cling/pull/365)

### CODE REVIEW

**Review by Axel-Naumann — CHANGES_REQUESTED** [review]
Can you please dramatically reduce the set of builds? I don't think we can afford this within the free quota. Or am I miscalculating? Could you share with us an estimate of how many CPU GH Action hours this costs per month, and how this compares to the free quota?

**Comment by vgvassilev** [comment]
That's what's written here:

```
GitHub Actions usage is free for public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. By default, your account will have a spending limit of $0, which prevents additional usage of minutes or storage after you reach these limits. If you increase your spending limit above the default of $0, you will be billed for any minutes or storage beyond the limits, also called overages. GitHub charges usage to the account that owns the repository where the workflow is run. Any coupons on your account do not apply to GitHub Actions overages.
```

IIUC, there is no quota for public repos but the wording is very convoluted so maybe there is another interpretation.

**Comment by Axel-Naumann** [comment]
> **and self-hosted runners**

IIUC we have GH free with 2,000mins/month

**Comment by vgvassilev** [comment]
> OK I see - the assumption is that GH Free gives open source repos unlimited CPU hours for Actions. Fine. Then I'd still recommend we reduce the set of builds to 6 or so? What do you find a reasonable number?

They should be all run in parallel so there should not be a delays for PRs (and we are pretty slow in processing PRs anyway). Why do you want less build coverage?

**Comment by reikdas** [comment]
@Axel-Naumann  We reduced the testing matrix to 8 jobs.

**Comment by Axel-Naumann** [comment]
Great, thanks! My main concern - apart from resources usage, which we believe isn't an issue - is the near exponential explosion of the probability of failure due to random glitches. Eight builds should address that. Apologies for not mentioning the second reason for my hesitation for having many builds; we have fairly negative experiences with that from ROOT being tested on Jenkins...

**Review by Axel-Naumann — APPROVED** [review]

**Pull request merged**
