### PR TITLE
Fix Cocoa GUI for MacOS14 and Clang15

### PR DESCRIPTION
**Pull request by couet**
Fix Cocoa GUI for MacOS14 and Clang15. 

The following collection of patches was provided by Timur Pocheptsoff <tpochep@mail.ru>

- [x] Fix TBrowser "white window"
- [x] Fix TBrowser text editor (it does not echo text until the window is resized)
- [x] Fix the OpenGL viewer

Fixes https://github.com/root-project/root/issues/13834

### CODE REVIEW

**Comment by dpiparo** [comment]
I tried this code and it fixes part of the problem, as correctly described above. However, it seems that other problems are appearing. For example, if I try to use the command line prompt from the browser, a broken scrollbar appears
image

I would like to note that with PyROOT, everything works perfectly even without this fix, even if I cannot provide an explanation why.

**Comment by couet** [comment]
I do not have the same experience with python. On macphsft24 (M1, OSX14, Clang15) I disabled the web browser by putting `Browser.Name: TRootBrowser` in `$ROOTSYS/etc/system.rootrc` . Then I ran python and started TBrowser. It shows the faulty one.

**Comment by BethLong06** [comment]
I don't know if it's a problem with how I installed root, using homebrew, or if it's just that I'm not expert enough in this area, but I can't find the files specified to modify. Under `/usr/local/Cellar/root/6.28.06/` I find 
```INSTALL_RECEIPT.json LICENSE              README.md            bin                  etc                  include              lib                  share```, but no `src`.

**Comment by couet** [comment]
Ah ok, you are using a preinstalled version. Here we are speaking of the installation from the source. That's why ...

**Comment by BethLong06** [comment]
ok, that makes sense. For now I'm happy to use the web viewer as a workaround, but will this be fixed in new releases? I'd prefer to keep using a precompiled version rather than risk problems in compiling it myself

**Comment by couet** [comment]
Yes of course this will be fixed in the release.

**Review by bellenot — APPROVED** [review]
LGTM, if it doesn't break older versions of MacOS/clang

**Comment by couet** [comment]
I have installed these patches on macphsft18 which is running MacOS12 and Clang 14. So, old OS and Compiler. Good News: it is working.

**Pull request merged**
