### PR TITLE
New unfold plotting

### PR DESCRIPTION
**Pull request by rahulgrit**
Closed the previously opened MR as I had messed up something with the branch.

@cburgard's description of the changes:
The RooFit "plotOn" plotting engine is very useful to visualize RooFit objects.
However, there is currently a strict separation between "Data-like" objects (which can only really be drawn with points) and "Function-like" objects (which can only really be drawn as lines and areas).
However, in techniques like unfolding, "data" is often times corrected data, and hence might actually be a function-type object in RooFit.
With this PR, functionality is added to RooAbsReal::plotOn that allows to plot functions "data-like", with data points including error bars when using the draw option "P", which was previously unusable.

### CODE REVIEW

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
@rahulgrit we are ready to merge. Anything still missing?

**Comment by rahulgrit** [comment]
@hageboeck there's no more changes here, it's ready to merge.

**Pull request merged**
