### PR TITLE
Fix macOS 11 TCling::GetSharedLibs

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac10beta/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac10beta/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac1015/cxx17 mac10beta/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac10beta/cxx17

**Pull request merged**
