### PR TITLE
VDT Usage Fix, master branch (2022.12.06.)

### LINKED ISSUE #11797: Incorrect Dependency on VDT
- [x] Checked for duplicates

### Describe the bug

The `ROOTVecOps` library incorrectly declares a `PRIVATE` dependency on the VDT headers.

https://github.com/root-project/root/blob/master/math/vecops/CMakeLists.txt#L27

(To be correct, it declares its dependency on VDT in a very silly way that does not make any sense to me...)

Even though it clearly "publicly" depends on those headers.

https://github.com/root-project/root/blob/master/math/vecops/inc/ROOT/RVec.hxx#L54

### Expected behavior

When using the exported target `ROOT::ROOTVecOps`, I would expect to be able to use `RVec.hxx` just by linking my own target against `ROOT::ROOTVecOps`. Not having to care about the "internal" dependency of the ROOT code on VDT myself.

To fix, the following should happen:
  - VDT should be used in the ROOT CMake configuration through an imported target, not through `${VDT_INCLUDE_DIRS}` and `${VDT_LIBRARIES}`. (Since these make relocation very hard.)
  - Once `ROOTVecOps` depends on a library like `VDT::vdt`, `ROOTConfig.cmake.in` will need to include

```cmake
find_dependency(VDT)
```

somewhere around here: https://github.com/root-project/root/blob/master/cmake/scripts/ROOTConfig.cmake.in#L88-L99

In such a setup, as long as `builtin_vdt` is "correctly" installed alongside ROOT, the configuration should start becoming correct under all circumstances.

### To Reproduce

Don't really have a reproducer. But a CMake project like:

```cmake
cmake_minimum_required( VERSION 3.10 )
project( VecOpsTest )

find_package( ROOT REQUIRED )

add_executable( VecOpsTest VecOpsText.cpp )
target_link_libraries( VecOpsTest PRIVATE ROOT::ROOTVecOps )
```

, with a simple

```c++
#include <ROOT/RVec.hxx>

int main() { return 0; }
```

(as `VecOpsTest.cpp`) should be able to produce an error. As long as ROOT and VDT headers are not in the same location. Which is usually the case unfortunately...

### Setup

This is primarily an issue with "LCG builds" of ROOT. Where currently we have to manually take care of linking our code explicitly against VDT, even if we don't use those headers directly ourselves.

### Additional context

The report was triggered by an ATLAS analyser complaining about this issue, with their own analysis code.

### PR DESCRIPTION
**Pull request by krasznaa**
# This Pull request:

Simplified/fixed how VDT would be used. Did this by making `ROOTVecOps`, `RooBatchCompute` and `TMVA` link against `VDT::VDT` in all circumstances (as long as VDT is being used). Regardless of whether VDT is used as a "builtin" or as an "external". At the same time made `ROOTVecOps` and `RooBatchCompute` depend on `VDT::VDT` publicly, as they actually do.

## Changes or fixes:

  - Made sure that an imported `VDT::VDT` library would be set up when `builtin_vdt` is being used.
  - Simplified how `ROOTVecOps`, `RooBatchCompute` and `TMVA` would just (publicly) link against `VDT::VDT` if either `vdt` or `builtin_vdt` is `TRUE`. Instead of the spaghetti of options that it had before.
  - Made sure that all of those targets would explicitly depend on the `VDT` target if `builtin_vdt` is set to `TRUE`.
  - Made sure that VDT would be searched for when calling `find_package(ROOT)` in client code.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #11797.

### CODE REVIEW

**Comment by krasznaa** [comment]
@amadio you will need to help me out here. I have no idea what the error is about. What sort of build is it that is failing? It seems to me that it's attempting a build with `builtin_vdt=TRUE`. But that worked for me with these changes just fine. Also, how the heck is a generated `ROOTConfig.cmake` file being used during the configuration of ROOT itself? :confused:

**Comment by amadio** [comment]
It always works when you try on your own machine, and then fails when a different version of CMake or a different configuration is used. That's a lesson usually learned the hard way with CMake :-)

> Also, how the heck is a generated ROOTConfig.cmake file being used during the configuration of ROOT itself?

That's likely used by `roottest`, as it's actually a separate CMake project which builds against ROOT (and can also be built separately if needed).

The error you see happens because `find_dependency(Vdt)` tries to read a header for Vdt (to figure out its version) which should be in the build directory (builtin_vdt==True), but is not there yet, because the build/install of Vdt as a builtin happens only at build time, not configuration time.

**Comment by amadio** [comment]
BTW, the failure above is not your fault, but a problem with the current CI. You need to fork also `roottest` to make it go away.

**Comment by krasznaa** [comment]
I'm quite baffled every time I come in contact with it, how you guys manage to survive with such a testing infrastructure. :confused: I did have a fork of [roottest](https://github.com/root-project/roottest) from a long time ago.

https://github.com/krasznaa/roottest

What I didn't have was it being up to date with the main repository. Plus, did I see correctly in your copy-pasted error message that the CI complained about not finding a branch in my roottest fork with the same name as the branch that I opened this PR from? :confused: What the heck? Is it really expected that one would create a branch in both repositories to make a modification to ROOT?

After some deliberation I updated the PR as you can see. The setup that you guys have with `ROOTConfig.cmake` being generated twice, and one of them possibly being used already during the main configuration is... unique... (Just so that I stay PC...) I've seen similar configurations being used for header-only libraries in the past, but never for anything that needed an actual build before becoming usable.

In any case, making `ROOTConfig.cmake` skip `find_dependency(Vdt)` if `VDT::VDT` is already available as a target, was the most robust thing that I could come up with...

**Comment by krasznaa** [comment]
Somebody should give me a hint to how that `test_periodic_build` test is set up. Since I can't really fix a test for which I have no clue how it's being executed. (I tried to look for that name in the main repository, in `roottest` and `jenkins-pipelines`. But I now give up.)

But in general, if that test tries to use `ROOTConfig.cmake` out of the build directory **before** the ROOT build would've been done, then yes, that should fail. As that would be a bad test to have. :thinking:

**Comment by bellenot** [comment]
@krasznaa see https://github.com/root-project/root/blob/master/test/CMakeLists.txt#L409-L445

**Comment by krasznaa** [comment]
Let's see what the CI says now...

**Comment by krasznaa** [comment]
Silly me with the Windows build...

**Comment by bellenot** [comment]
I think the error is due to the fact there is no VDT on Windows. Did you try without VDT on other platforms?

**Comment by krasznaa** [comment]
> I think the error is due to the fact that there is no VDT on Windows. Did you try without VDT on other platforms?

I don't think it's that. :thinking: `ROOTConfig.cmake` will not look for VDT in this PR's setup if VDT was not used in the build.

I instead believe that I was just trying to set the `CMAKE_PREFIX_PATH` environment variable incorrectly in the Windows shell. Since Windows provides a few different shells, each of which comes with a slightly different formalism, in the end I reverted back to passing `CMAKE_PREFIX_PATH` as a cache variable to that test.

On Linux that works. Hopefully it will work on Windows too. I tried to set up a build on Windows on my laptop, but when after about 20 minutes it was still failing in one of the externals, I just gave up. :frowning:

**Comment by tmadlener** [comment]
After just having stumbled over this once again. What is the current status of this?

**Comment by dpiparo** [comment]
So I can see it built successfully on Ubuntu 22 and on a private test on macos 13 arm cherry-picking on top of master. Let's wait for all builds to complete and then we can discuss how to proceed.

**Comment by dpiparo** [comment]
Ubuntu22, centos8, Win10, macos11, macos12 M1 are successful. We are waiting for the last worker on ubuntu 20, but the changes look good to me.

**Comment by dpiparo** [comment]
Ok. Thanks to the prompt intervention of @andresailer (thanks!), we were even able to test this fix in the context of LCG builds, which are much more sophisticated than the ones of ROOT alone. This test was successful.

**Pull request merged**
