### PR TITLE
Fixed a compile error corresponding to the addition of the class TGraphMultiErrors

### PR DESCRIPTION
**Pull request by Triple-S**
Hello,

I'm sorry my new classed crashed root.
It seems to me that the error was due to the usauge of C-style variable length arrays that are only supported under g++ and not c++.
The changes I implemented should fix the bug.

All the best,
Simon Spies

### CODE REVIEW

**Comment by Triple-S** [comment]
@phsft-bot build

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by Triple-S** [comment]
I'm sorry, there was another place where I was using C-style programming only valid under g++ and not c++. Now I also fixed this one.

**Comment by Triple-S** [comment]
Actually I got to admit I have no idea why there are tests failing on ROOT-ubuntu16/nortcxxmod.
Acccording to the error message this seems to be related to the function TGraph::AllocateArrays which I did not touch at all, so this might be an unrealted issue.

**Comment by Triple-S** [comment]
Could an admin please trigger another build?

**Comment by vgvassilev** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
The failure is probably due to https://github.com/root-project/root/pull/4699

**Comment by lmoneta** [comment]
This PR looks fine. Thank you Simon for providing it !

**Comment by Triple-S** [comment]
Ok, everything seems fine now.
The two failed builds seem to be related to the error @vgvassilev mentioned.
I will keep watching whether further problems occur.

**Pull request merged**
