### PR TITLE
[RF][HS3] Non-uniform binnings for HistFactory HS3 and other improvements

### PR DESCRIPTION
**Pull request by cburgard**
# This Pull request:

Adds support for non-uniform binnings to HS3.

## Changes or fixes:
 
Adds an if/then/else everywhere RooRealVars are read or written to handle non-uniform binnings as well.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by cburgard** [comment]
Seeing how many places this code needed to be copied lets me thing it would be worthwhile to refactor the code to read and write axes in the HistFactory implementation to re-use the readBinnedData functionality from RooWSJSONFactoryTool via some to-be-defined interface.

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
> Seeing how many places this code needed to be copied lets me thing it would be worthwhile to refactor the code to read and write axes in the HistFactory implementation to re-use the readBinnedData functionality from RooWSJSONFactoryTool via some to-be-defined interface.
> 
> What do you think @guitargeek ?

I agree, the variable management is probably the most intricate part of the RooFit HS3 code right now, and we should see how to improve it in one of the next PRs! I can also discuss this together with @yashnator who noticed the same problems when working on the pythonizations.

For for this PR, let's merge it because it includes already quite a few developments. To your support of non-uniform binning, I added:

* merging `testHS3HistFactory` and `testHistFactory`, like this we test your non-uniform binning support for free
* correct global observables definition and import
* export all the HistFactory parameters (one of the things you noticed was not done and you told me on mattermost)
* some improvements of the HistFactoryJSONTool

**Review by guitargeek — APPROVED** [review]

**Pull request merged**
