### PR TITLE
[DF] Avoid heap allocation for column names

### PR DESCRIPTION
**Pull request by hahnjo**
Instead of passing a dynamically allocated array, pass an initializer list that the compiler can put on the stack. By removing the calls to new, this also helps the exploding compile times discussed in #9312.

### CODE REVIEW

**Comment by hahnjo** [comment]
@eguiraud this is another idea I had to work around the problem of long functions mixing `std::string_view` and `new`. In my preliminary tests, this improves performance in general (less heap allocations) so it might be worth it in addition to #9328. If that makes sense, I'd like to investigate `std::initializer_list` instead of arrays with a dummy element, but this seems to work for now.

**Comment by eguiraud** [comment]
thanks! my only doubt is whether the stack allocations can blow up and cause a stack smash, but i did not have time to think about it well, just a drive-by thought.

**Comment by hahnjo** [comment]
> thanks! my only doubt is whether the stack allocations can blow up and cause a stack smash, but i did not have time to think about it well, just a drive-by thought.

In principle, the compiler should be able to allocate stack that is large enough for the largest array of names that is ever needed because the memory is only passed to the call and can be reused afterwards. We should probably check if that's a potential problem at `-O0` (I cannot recall), but on the other hand this potential issues is reduced by #9328 compiling smaller functions...

**Comment by eguiraud** [comment]
As per our discussion, on my side we only need to confirm that everything works fine if the list of column names have, say, O(1k) sizes. And we also want to confirm that this is not a pessimization for the O0 case.

**Comment by hahnjo** [comment]
Okay, here's the version with `std::initializer_list`, which I find quite clean and neat but is slower than `master` (after #9342 with `-mllvm -optimize-regalloc=0`):

| | `master` | `std::initializer_list` |
| --- | --- | --- |
| `-O0` | 8.9s | 9.0s |
| `-O1` | 12.5s | 13.5s |

So not sure if the change is really worth it, and haven't checked stack usage either.

**Comment by hahnjo** [comment]
`perf diff` between current `master` and this PR:
```
               +0.63%  libCling.so               [.] (anonymous namespace)::OptimizeLEAPass::removeRedundantLEAs
               +0.62%  libCling.so               [.] std::__remove_if<llvm::AllocaInst**, __gnu_cxx::__ops::_Iter_pred<llvm::SetVector<llvm::AllocaInst*, llvm::SmallVector<llvm::AllocaInst*, 16u>, llvm::DenseSet<llvm::AllocaInst*, llvm::DenseMapInfo<llvm::AllocaInst*> > >::TestAndEraseFromSet<llvm::SROA::runImpl(llvm::Function&, llvm::DominatorTree&, llvm::AssumptionCache&)::{lambda(llvm::AllocaInst*)#1}> > >
     0.66%     +0.42%  [unknown]                 [k] 0xffffffff9f603885
     1.64%     -0.30%  libCling.so               [.] llvm::SmallPtrSetImplBase::FindBucketFor
               +0.26%  [JIT] tid 343249          [.] 0x00007f30bea1743e
     0.05%     +0.25%  libCling.so               [.] llvm::SROA::runImpl
     3.49%     -0.24%  libc-2.28.so              [.] __memcmp_avx2_movbe
     0.01%     +0.19%  libCling.so               [.] llvm::MachineRegisterInfo::defusechain_iterator<true, false, true, true, false, false>::defusechain_iterator
     0.34%     +0.18%  libCling.so               [.] llvm::Use::getImpliedUser
     0.97%     -0.17%  libCling.so               [.] llvm::SelectionDAG::Combine
     0.85%     -0.17%  libCling.so               [.] clang::Sema::isModuleVisible
     1.50%     +0.17%  libCling.so               [.] llvm::AttributeList::hasAttribute
     1.92%     -0.15%  libCling.so               [.] (anonymous namespace)::DAGCombiner::AddToWorklist
               +0.15%  libCling.so               [.] (anonymous namespace)::StackColoring::runOnMachineFunction
     0.49%     -0.15%  libCling.so               [.] llvm::StringMapImpl::LookupBucketFor
     0.45%     +0.15%  libc-2.28.so              [.] unlink_chunk.isra.2
     0.88%     -0.15%  libCling.so               [.] llvm::TargetLibraryInfoImpl::getLibFunc
     0.50%     +0.13%  libCling.so               [.] llvm::InstCombiner::run
     0.36%     +0.12%  libCling.so               [.] computeKnownBits
     0.39%     -0.12%  libCling.so               [.] (anonymous namespace)::RegAllocFast::runOnMachineFunction
     0.20%     +0.12%  libCling.so               [.] llvm::DataLayout::getAlignment
     0.01%     +0.12%  libCling.so               [.] llvm::Instruction::mayThrow
     0.33%     +0.12%  libCling.so               [.] llvm::removeUnreachableBlocks
     0.91%     -0.11%  libCling.so               [.] llvm::Value::getValueName
               +0.11%  libCling.so               [.] llvm::LiveRange::isLiveAtIndexes
     0.44%     -0.11%  libCling.so               [.] llvm::DAGTypeLegalizer::run
     0.49%     -0.11%  libCling.so               [.] (anonymous namespace)::DeadMachineInstructionElim::runOnMachineFunction
     0.19%     +0.11%  libCling.so               [.] llvm::PointerMayBeCaptured
     0.55%     +0.11%  libCling.so               [.] llvm::ConstantUniqueMap<llvm::ConstantExpr>::getOrCreate
     1.14%     +0.11%  libc-2.28.so              [.] _int_malloc
     0.48%     -0.10%  libCling.so               [.] llvm::SelectionDAG::AssignTopologicalOrder
     1.15%     -0.10%  libCling.so               [.] llvm::Attribute::hasAttribute
     0.12%     +0.10%  libCling.so               [.] llvm::wouldInstructionBeTriviallyDead
     1.06%     -0.10%  libCling.so               [.] clang::LookupResult::resolveKind
```

My interpretation is that optimizations are doing more, for little gain...

**Comment by hahnjo** [comment]
I can reproduce the numbers of https://github.com/root-project/root/pull/9329#issuecomment-984670318 with current `master`, so I'm closing this PR as it's not an improvement.

**Pull request closed without merging**
