### PR TITLE
Properly use `Copy(TObject &)` methods in `hist` classes

### LINKED ISSUE #10919: Histograms copy constructor has wrong implementation
While virtual `Copy(TObject &obj)` method is used in copy constructors, wrong cast may happen.
Simplest reproducer:
```
TProfile p;
TH1D h(p);
```
Causes fatal crash:
```
Fatal in <TProfile::Copy>: Cannot copy a TProfile in a TH1D
aborting
#0  0x00007f2293b0a83a in wait4 () from /lib64/libc.so.6
#1  0x00007f2293a7403b in do_system () from /lib64/libc.so.6
#2  0x00007f22942c5a3d in TUnixSystem::StackTrace() () from /home/linev/build/webgui/lib/libCore.so
#3  0x00007f229418294c in DefaultErrorHandler(int, bool, char const*, char const*) () from /home/linev/build/webgui/lib/libCore.so
#4  0x00007f22942497bd in ErrorHandler () from /home/linev/build/webgui/lib/libCore.so
#5  0x00007f22941988f4 in TObject::Fatal(char const*, char const*, ...) const () from /home/linev/build/webgui/lib/libCore.so
#6  0x00007f227d6fbde8 in TProfile::Copy(TObject&) const [clone .cold] () from /home/linev/build/webgui/lib/libHist.so
#7  0x00007f227d80aba7 in TH1D::TH1D(TH1D const&) () from /home/linev/build/webgui/lib/libHist.so
#8  0x00007f228c9dc028 in ?? ()
#9  0x00007f2293f83460 in ?? ()
#10 0x00007f228f062cfe in cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction&) () from /home/linev/build/webgui/lib/libCling.so
#11 0x00007f228efd6ea4 in cling::Interpreter::executeTransaction(cling::Transaction&) () from /home/linev/build/webgui/lib/libCling.so
#12 0x00007f228f07511c in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) () from /home/linev/build/webgui/lib/libCling.so
#13 0x00007f228f076c68 in cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) () from /home/linev/build/webgui/lib/libCling.so
#14 0x00007f228efd4bb8 in cling::Interpreter::EvaluateInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /home/linev/build/webgui/lib/libCling.so
#15 0x00007f228efd4f25 in cling::Interpreter::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::Value*, cling::Transaction**, bool) () from /home/linev/build/webgui/lib/libCling.so
#16 0x00007f228f0c6b17 in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /home/linev/build/webgui/lib/libCling.so
#17 0x00007f228eedaeac in HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#18 0x00007f228eefbbb8 in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) () from /home/linev/build/webgui/lib/libCling.so
#19 0x00007f2294550ab7 in TRint::ProcessLineNr(char const*, char const*, int*) () from /home/linev/build/webgui/lib/libRint.so
#20 0x00007f2294550e8d in TRint::HandleTermInput() () from /home/linev/build/webgui/lib/libRint.so
#21 0x00007f22942c2236 in TUnixSystem::CheckDescriptors() () from /home/linev/build/webgui/lib/libCore.so
#22 0x00007f22942c5198 in TUnixSystem::DispatchOneEvent(bool) () from /home/linev/build/webgui/lib/libCore.so
#23 0x00007f22941cd19c in TSystem::Run() () from /home/linev/build/webgui/lib/libCore.so
#24 0x00007f229415d293 in TApplication::Run(bool) () from /home/linev/build/webgui/lib/libCore.so
#25 0x00007f2294552843 in TRint::Run(bool) () from /home/linev/build/webgui/lib/libRint.so
#26 0x0000000000400e4d in main ()
```

Will be fixed by #10942

### PR DESCRIPTION
**Pull request by linev**
This is virtual method and can be overriden in derived classes.
Therefore when such method used in copy constructor or assignment
operator, one have to explicitly specify class which used.

Fixes #10919

### CODE REVIEW

**Review by lmoneta — COMMENTED** [review]
I am not sure if the use of non-virtual Copy in the copy constructor of the histogram class is correct. 
This PR will make a copy a TProfile to a TH1D possible which can have some side effects.
Example:
```
TProfile p("p","p",10,0,10);
TH1D & h1 = p;
TH1D h2 = h1;
```

I don't see then the benefits of not using the virtual Copy in the copy constructor and assignment operator.

**Comment by linev** [comment]
If one want to keep usage of virtual `Copy` methods, in each such method one should check if source object type match `this` object - using dynamic cast. Otherwise it may produce segmentation violation.

In my mind, current implementation of copy constructors with using of virtual `Copy` methods is wrong and error prone.

**Comment by lmoneta** [comment]
Are you referring about a check that the final type of the source is the same final type pf the target, i.e. in this code below: 
```
TH2D::TH2D(const TH2D &h2d) : TH2(), TArrayD()
 {
    ((TH2D&)h2d).Copy(*this);
 }
 ```
 if `this` and 'h2d` are actually the same final types (e.g. both TProfile histograms). 
 This check is performed in the `TProfile::Copy` function, see : 
 https://github.com/root-project/root/blob/master/hist/hist/src/TProfile.cxx#L422

**Comment by linev** [comment]
> This check is performed in theTProfile::Copy` function, 

Such check must be introduced in all Copy methods in all classes.
To avoid such checks, I propose directly call method of appropriate class and do not use `virtual` interface.

**Comment by lmoneta** [comment]
I agree if one is able to call copy constructors for the final classes and not for base ones. In the ROOT histogram design this is not the case since we have classes as TProfile deriving from TH1D and not TH1.

**Comment by linev** [comment]
When calling virtual `Copy` method in copy constructor - one never knows that exact happens. 
User can define derived class from TH1D and provide own `Copy` implementation.
In such case `TH1D th1 = user_th1;` will leads to wrong results. `TProfile` is just example of that with existing ROOT classes.

**Review by lmoneta — APPROVED** [review]
Thank you Sergei for the improvement and the change in TH1,2,3,D classes. 
It looks fine to me now. 
I think there is a reference file that needs to be update in the roottest repo for avoiding the failure seen in the CI, after the change to use `nullptr`.

**Comment by linev** [comment]
I already prepare PR for root-test:

https://github.com/root-project/roottest/pull/884

I will merge it shortly after merging this PR

**Pull request merged**
