### PR TITLE
[Math][ROOT-10131] Fix gcc9 warnings (-Wdeprecated-copy)

### PR DESCRIPTION
**Pull request by stwunsch**
PR against v6-18-00-patches

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
Rebuild to check whether the test failure above is reproducible.

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
And once again

**Comment by stwunsch** [comment]
@Axel-Naumann Should be fine for merging!

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
Was this part of PR https://github.com/root-project/root/pull/3972 ?

**Comment by Axel-Naumann** [comment]
Yes it was - closing. Thanks, @stwunsch !

**Pull request closed without merging**
