### PR TITLE
FindObject for rooabscollection

### PR DESCRIPTION
**Pull request by will-cern**
Another little change, this makes some nice features available in python such as ```"var" in collection```

### CODE REVIEW

**Comment by pcanal** [comment]
Can you rebase on  the tip of the master branch?  It seems some of the commit should already be there.  Thanks.

**Comment by will-cern** [comment]
> Can you rebase on the tip of the master branch? It seems some of the commit should already be there. Thanks.

done

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by will-cern** [comment]
I take it from the warnings that I might have to add the other FindObject method (that accepts a TObject pointer) to satisfy the builds? Please confirm and I can do this.

**Comment by pcanal** [comment]
You are correct.

**Comment by hageboeck** [comment]
> I take it from the warnings that I might have to add the other FindObject method (that accepts a TObject pointer) to satisfy the builds? Please confirm and I can do this.

Exactly. Something like `auto ptr = dynamic_cast<const RooAbsArg*>; return ptr ? find(*ptr) : nullptr;` should do it.

Could you include a one-line doxygen-readable comment (`///`) to avoid having two undocumented functions? Also note that `find(RooAbsArg&)` will find objects with the same name, not necessarily with the same pointer. You should decide with @guitargeek if that's actually desired when called from the Python side. In a second sentence, you should document whether that function will find objects with the same name (= equivalent objects as far as RooFit is concerned) or if it should only find the exact same object.

**Comment by will-cern** [comment]
> > I take it from the warnings that I might have to add the other FindObject method (that accepts a TObject pointer) to satisfy the builds? Please confirm and I can do this.
> 
> Exactly. Something like `auto ptr = dynamic_cast<const RooAbsArg*>; return ptr ? find(*ptr) : nullptr;` should do it.
> 
> Could you include a one-line doxygen-readable comment (`///`) to avoid having two undocumented functions? Also note that `find(RooAbsArg&)` will find objects with the same name, not necessarily with the same pointer. You should decide with @guitargeek if that's actually desired when called from the Python side. In a second sentence, you should document whether that function will find objects with the same name (= equivalent objects as far as RooFit is concerned) or if it should only find the exact same object.

Indeed I thought about having `auto arg = dynamic_cast<const RooAbsArg*>(obj); return (arg && containsInstance(*arg)) ? obj : nullptr;` but given the 'find' method matches by name I think for consistency the FindObject should behave the same for these classes, unless there is some additional benefit to FindObject(obj) returning obj??

**Review by guitargeek — APPROVED** [review]
Thank you Will! I also agree that the behavior should be consistent with `RooAbsCollection::find()`, because the `var in coll` pattern is basically a pythonization of `coll.find(var)`.

However, I think it's important to ensure this consistency in a pythonization unit test, but I'll take care of this.

**Comment by guitargeek** [comment]
Thanks again for the contributions! I implemented a unit test in this PR: https://github.com/root-project/root/pull/8179.

**Pull request merged**
