### PR TITLE
[Doc][RDF] New RDF tutorial with W boson analysis

### PR DESCRIPTION
**Pull request by stwunsch**
* Large scale analysis, about 30min runtime (2 cores, data read from EOS)
* Initial dataset has around 60 GB spread over 30 files
* Small fix to tutorial df104

~**Question: Since this is a rather long running tutorial, how should we handle this?**~

Fixed! Runs now in about 5 mins.

See here the resulting plot:

WBosonAnalysis

### CODE REVIEW

**Comment by stwunsch** [comment]
I put in a command line argument to parametrize the number of events used for the plot. Now the runtime is down to 5 minutes.

x

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@couet Could you have a look over the plotting code? I'm not sure whether the plotting could be simplified.

**Comment by stwunsch** [comment]
@couet Ping!

**Comment by stwunsch** [comment]
@couet Ping!

**Comment by oshadura** [comment]
@stwunsch I didn't see tutorials running in Jenkins logs, so I will start full build!

**Comment by oshadura** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
