### PR TITLE
Revert "Revert "[cxxmodules] Don't generate rootmap files with cxxmod…

### PR DESCRIPTION
**Pull request by yamaguchi1024**
…ules""

This reverts commit f409295be0ced782909c0b474c7142b657dc3c4d.

IIRC this destoryed ACLiC. Let's fix this and remove rootmap files.

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@yamaguchi1024 I think version of this already landed. I am closing this now but feel free to reopen if needed.

**Pull request closed without merging**
