### PR TITLE
Backport for no-linking against libpython

### PR DESCRIPTION
**Pull request by maxgalli**

### CODE REVIEW

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by etejedor** [comment]
There is a test failure in `python-regression-regression` that needs to be investigated, we can't merge this for now.

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by etejedor** [comment]
@phsft-bot build just on mac1014/python3 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by maxgalli** [comment]
@henryiii @chrisburr we merged this yesterday and the nightlies were fine, so it will make it to v6.22. I'm also closing the related ticket https://sft.its.cern.ch/jira/browse/ROOT-9950.

**Comment by chrisburr** [comment]
Wonderful! Thanks for the work on this, I'll retry the conda-forge build.

**Pull request merged**
