### PR TITLE
Update libc.modulemap

### PR DESCRIPTION
**Pull request by gargvaibhav64**

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@gargvaibhav64  can you please fork https://github.com/root-project/roottest, windows build failed because it was not able to find your fork of roottest.git. Thanks!

**Comment by gargvaibhav64** [comment]
> @gargvaibhav64 can you please fork https://github.com/root-project/roottest, windows build failed because it was not able to find your fork of roottest.git. Thanks!

Done right now.

**Comment by oshadura** [comment]
@phsft-bot build!

**Pull request closed without merging**
