### PR TITLE
[cling] Create non-empty source file

### PR DESCRIPTION
**Pull request by hahnjo**
LLVM currently has an issue that a completely empty source file is stored as a `nullptr`, but `DIFile::getSource()` does not correctly deal with this situation. A crash can be observed if just attempting to launch root.exe with `EXTRA_CLING_ARGS="-gdwarf-5 -gembed-source"`.

### CODE REVIEW

**Comment by hahnjo** [comment]
@amadio is what I describe in the first commit the correct reproducer? Your original commit had no ready-to-use example, so I had to guess...

**Comment by Axel-Naumann** [comment]
LGTM but I'd like to have @vgvassilev 's review.

**Review by vgvassilev — APPROVED** [review]
LGTM! I am wondering if we will have the same problem with clang-repl, because the compiler instance bootstrapping soon will be moved to what we have upstream.

**Comment by hahnjo** [comment]
> LGTM! I am wondering if we will have the same problem with clang-repl, because the compiler instance bootstrapping soon will be moved to what we have upstream.

Yes, I think the equivalent code is https://github.com/llvm/llvm-project/blob/main/clang/lib/Interpreter/Interpreter.cpp#L103-L104 (btw, the `<<< inputs >>>` should probably be a constant because it needs to agree with line 149). But it shouldn't be a real problem anymore after I landed https://reviews.llvm.org/D138658.

**Comment by vgvassilev** [comment]
> > LGTM! I am wondering if we will have the same problem with clang-repl, because the compiler instance bootstrapping soon will be moved to what we have upstream.
> 
> Yes, I think the equivalent code is https://github.com/llvm/llvm-project/blob/main/clang/lib/Interpreter/Interpreter.cpp#L103-L104 (btw, the `<<< inputs >>>` should probably be a constant because it needs to agree with line 149). But it shouldn't be a real problem anymore after I landed https://reviews.llvm.org/D138658.

Awesome!

**Pull request merged**
