### PR TITLE
[core] Prevent void return type from Map function

### PR DESCRIPTION
**Pull request by hahnjo**
Closes https://github.com/root-project/root/issues/7872

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]
Thanks for this nice update. Would it be perhaps possible to add a test?

**Comment by hahnjo** [comment]
> Thanks for this nice update. Would it be perhaps possible to add a test?

Not easily I think, because passing a `void` mapping function will still fail to compile, just with a nicer error message now...

**Comment by hahnjo** [comment]
@dpiparo good to merge then?

**Comment by dpiparo** [comment]
Yes please, go a head and merge. Thanks for this nice improvement!

**Pull request merged**
