### PR TITLE
[TMVA][SOFIE]Expand ONNX Operator implemented with the corresponding unit tests

### PR DESCRIPTION
**Pull request by Neel-Shah-29**
# This Pull request: Adds the Expand ONNX Operator in SOFIE

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by Neel-Shah-29** [comment]
image
Hello @lmoneta I implemented the expand operator but am facing issue with `RModelParser_ONNX.cxx` , can you help me with what can be the possible solution to resolve it?

**Review by axmat — CHANGES_REQUESTED** [review]

**Comment by axmat** [comment]
> image Hello @lmoneta I implemented the expand operator but am facing issue with `RModelParser_ONNX.cxx` , can you help me with what can be the possible solution to resolve it?

Hi @Neel-Shah-29, You need to add `ParseExpand.cxx` to the cmake file `root/tmva/sofie_parsers/CMakeLists.txt`.

**Review by axmat — APPROVED** [review]
Looks good, LGTM!
cc @lmoneta

**Comment by lmoneta** [comment]
@Neel-Shah-29 : thanks for the PR, before merging can you please fix these warnings reported by the CI above ? 
Thanks

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default, ROOT-ubuntu18.04/nortcxxmod

**Review by lmoneta — APPROVED** [review]
LGTM
Thank you Neel for the PR!

**Pull request merged**
