### PR TITLE
[v620] Spurious change to enable testing jenkins

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-fedora31/noimt with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-debian10-i386/cxx14

**Comment by hageboeck** [comment]
Converted to draft in order to be able to remove the `do not merge` label.

**Comment by guitargeek** [comment]
Duplicate of:
* https://github.com/root-project/root/pull/7906

**Pull request closed without merging**
