### PR TITLE
[tmva] Fix dependency of libTMVA from 

### PR DESCRIPTION
**Pull request by lmoneta**
This PR removes the dependency of libTMVA from libROOTDataFrame. 

The dependency is needed only for the test programs. 
This should fix the conflict seen when loading PyTorch models on some architectures. See https://github.com/root-project/root/pull/13674#issuecomment-1733208800 

In addition the PR veto some Keras tutorials which time-out on macOS due to need to keep eager execution on MacOS
(see https://github.com/root-project/root/pull/13634/commits/e1d2ed4a937e546d197a1c1c026c17f671a16bcc )

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build on ROOT-ubuntu2004-clang/default, ROOT-ubuntu2204/nortcxxmod, mac13arm/default  with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by sanjibansg — APPROVED** [review]
LGTM!

**Comment by lmoneta** [comment]
@phsft-bot build on ROOT-ubuntu2004-clang/default, ROOT-ubuntu2204/nortcxxmod, mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build on ROOT-ubuntu2004-clang/default, ROOT-ubuntu2204/nortcxxmod, mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by dpiparo** [comment]
For the CI this worked quite well. I would be in favour of merging this because the changes will avoid constant failures related to PyKeras on Mac builds.

**Review by dpiparo — APPROVED** [review]

**Pull request merged**
