### PR TITLE
[v628] Allocate TypesLoaded and DeclsLoaded lazily

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Updated to address the C++20ism and a few of the comments in #13000. In particular:

* Almost drop in replacement by exposing just an expand() method.
* Now also used in the SourceManager, for and additional gain of ~ 10 MB on the initial ROOT overhead (from 82 to 53MB in my synthetic test).

**Comment by hahnjo** [comment]
Please note that any change *must* land in `master` first and that we track changes to `interpreter/llvm-project` via https://github.com/root-project/llvm-project/. Ideally this should go via upstream first; for the topic if data structures please have a look at https://www.llvm.org/docs/ProgrammersManual.html#picking-the-right-data-structure-for-a-task

**Comment by ktf** [comment]
Thank you for your reminders, I will for sure follow the procedure once I am convinced this works fine for all ALICE usecases. Having a PR on the v6-28-00-patches branch merely simplifies sharing something which can be immediately used in the ALICE software stack.

Could you please advise regarding the data structure to use? I could not find one that fits the needed sparseness.

**Comment by ktf** [comment]
On a separate note, are the tests supposed to be green?

**Comment by hahnjo** [comment]
> Thank you for your reminders, I will for sure follow the procedure once I am convinced this works fine for all ALICE usecases. Having a PR on the v6-28-00-patches branch merely simplifies sharing something which can be immediately used in the ALICE software stack.

Yes understood :)

> Could you please advise regarding the data structure to use? I could not find one that fits the needed sparseness.

I'm not sure there is one already, but it has some comments to make about `std::vector` (because I saw you mentioning `std::pmr::vector`. If there is none yet (but I think Vassil mentioned one? maybe it's not listed in that document), it should likely be added to LLVM's ADT library first and then used in Clang.

> On a separate note, are the tests supposed to be green?

Yes, and from a quick look it seems ~all builds are failing with
```
Assertion `Index < TypesLoaded.size() && "Type index out-of-range"' failed.
```
which very much sounds like it is caused by the changes...

**Comment by ktf** [comment]
@phsft-bot build with flags -Dasan=ON

**Comment by ktf** [comment]
I managed to reproduce and fix the issue (mSize was not initialised) however I still get the assertions here. Could it be there is some incremental build issue? Do you build every time from scratch?

**Comment by ktf** [comment]
@phsft-bot build mac12arm/cxx20

**Comment by ktf** [comment]
@phsft-bot build with flags -DLLVM_BUILD_TYPE=RelWithDebInfo

**Comment by hahnjo** [comment]
@ktf can you please not debug in Jenkins? This should be investigated offline!

**Comment by hahnjo** [comment]
> > @ktf can you please not debug in Jenkins? This should be investigated offline!
> 
> Sorry, but I cannot replicate it offline, I have tried mac, ubuntu and centos with a number of combinations of the various `-D*ASSERT*=ON`, `-DCMAKE_BUILD_TYPE=*` I can possibly think of. If you have a failing environment could you provide me access to it?

I can quite easily reproduce it on EL8 with the exact `cmake` command from the Jenkins log. The important piece seems to be `-DCMAKE_CXX_STANDARD=14`.

**Comment by ktf** [comment]
ok, i will try that. indeed in alice we need to use c++17. I will try
without.

Ciao,
Giulio

**Comment by ktf** [comment]
Ok, I managed to reproduce and I think I know what is going on. I will provide an improved version in a bit.

**Comment by ktf** [comment]
Ok, I found out what was wrong and fixed it, taking advantage of some suggestion I got in the upstream LLVM review. The issue was missing pointer stability due to the fact the resizing of the backend store could have incurred in copies later than previously expected. The new code uses a BumpPtrAllocator to allocate the pages of items, rather than resizing an std::vector, so it's guaranteed that the elements don't move once they have been allocated (at the cost of the allocated memory not being necessarity contiguous anymore).

With such fix, I cannot reproduce the issue anymore when running standalone, with similar memory improvements when running my simple "open ALICE AOD file" test.

**Comment by ktf** [comment]
It looks like the builder disk is full:

```
04:17:46  /usr/bin/ar: interpreter/llvm/src/lib/libclangSema.a: No space left on device
```

**Comment by ktf** [comment]
So the upstream change has been merged. How can I ask for a proper backport? I have the impression building PRs to the v6-28-00-patches branch does not always work. Shall I try with master first? However, wouldn't doing that create troubles with the later integration of the LLVM upstream?

**Comment by vgvassilev** [comment]
> So the upstream change has been merged. How can I ask for a proper backport? I have the impression building PRs to the v6-28-00-patches branch does not always work. Shall I try with master first?

Yes, please open against the master.

> However, wouldn't doing that create troubles with the later integration of the LLVM upstream?

No, backports are fine for git to deal with during upgrades.

**Comment by hahnjo** [comment]
> > However, wouldn't doing that create troubles with the later integration of the LLVM upstream?
> 
> No, backports are fine for git to deal with during upgrades.

Well, they do need a bit of care to synchronize to our set of patches for newer LLVMs, but that's what we have to deal with.

**Comment by hahnjo** [comment]
FWIW the PR for `master` is https://github.com/root-project/root/pull/13808

**Comment by guitargeek** [comment]
As explained by @ktf (https://github.com/root-project/root/pull/13808#issuecomment-1905573235), this patch was required in 6.30, where it is already included.

Feel free to re-open if you should still need it in 6.28!

**Pull request closed without merging**
