### PR TITLE
Update TPad.cxx

### LINKED ISSUE #6447: MIssing initialization of TPad::fPrimitives
## Describe the bug
TPad::GetPrimitives() returns nullptr instead of an empty list, gets defererenced ... and so on.
```
[@test]$ ./pad4 

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
    gdb.printing.register_pretty_printer(gdb.current_objfile(),
#0  0x00007fc2c245846c in __libc_waitpid (pid=25123, stat_loc=stat_loc
entry=0x7ffefaecb520, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:31
#1  0x00007fc2c23d5f62 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007fc2c55d95dc in TUnixSystem::StackTrace (this=0xcf6980) at /usr/src/debug/root-6.22.02/core/unix/src/TUnixSystem.cxx:2408
#3  0x00007fc2c55dc06a in TUnixSystem::DispatchSignals (this=0xcf6980, sig=kSigSegmentationViolation) at /usr/src/debug/root-6.22.02/core/unix/src/TUnixSystem.cxx:3646
#4  <signal handler called>
#5  0x00007fc2c54dd41d in TObject::AppendPad (this=0x190c210, option=0x400c96 "") at /usr/src/debug/root-6.22.02/core/base/src/TObject.cxx:112
#6  0x0000000000400b76 in main (argc=<optimized out>, argv=<optimized out>) at test/pad4.cxx:13
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007fc2c54dd41d in TObject::AppendPad (this=0x190c210, option=0x400c96 "") at /usr/src/debug/root-6.22.02/core/base/src/TObject.cxx:112
#6  0x0000000000400b76 in main (argc=<optimized out>, argv=<optimized out>) at test/pad4.cxx:13
===========================================================



```

## Expected behavior
No crash

## To Reproduce
Code:

```
#include <TCanvas.h>
#include <TText.h>
#include <TPad.h>
#include <fenv.h>

int main(int argc, char **argv) {
    TCanvas* C= new TCanvas("canvas","canvas",1024,768);
    C->cd();
    TPad* c= new TPad();
    //c->cd(1);//works
    c->cd();//fails
    TText* t= new TText(0.5,0.5,"some text");
    t->Draw();
    delete t;
    delete c;
    delete C;
    return 0;
}

```
Compile

```
g++ pad4.cxx $(root-config --glibs --cflags --libs) -o pad4  -g
```

run

```
./pad4
```

## Setup
ROOT 6.22.02 gcc4.8.5 on CentOS7/EPEL

## Additional context
Possible fix:
Change 
```

TVirtualPad *TPad::cd(Int_t subpadnumber)
{
   if (!subpadnumber) {
      gPad = this;
      if (!gPad->IsBatch() && GetPainter()) GetPainter()->SelectDrawable(fPixmapID);
      return gPad;
   }
.....

```
to

```

TVirtualPad *TPad::cd(Int_t subpadnumber)
{
   if (!subpadnumber) {
      gPad = this;
      if (!gPad->IsBatch() && GetPainter()) GetPainter()->SelectDrawable(fPixmapID);
      if (!fPrimitives) fPrimitives = new TList;
      return gPad;
   }
.....

```

### PR DESCRIPTION
**Pull request by andriish**
Fixes #6447 
Tag @couet

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by couet** [comment]
This does not fix #6447

**Review by couet — APPROVED** [review]

**Comment by andriish** [comment]
Hi @couet  ,

>This does not fix #6447 the pad4.cxx program still crashes on ubuntu
yes, I see.

The error, however, appears in another place.

Will have a look.

Thank you!

Andrii

**Comment by couet** [comment]
I merged it ..... do not worry

**Pull request merged**
