### PR TITLE
Optimize includes in roofit

### PR DESCRIPTION
**Pull request by linev**
Extraction from #5535 to resolve conflicts in roofit

### CODE REVIEW

**Comment by linev** [comment]
@hageboeck Can you approve check this PR? 
Without it I cannot update #5535 - changes in core classes have side effects in roofit, which are fixed here

**Comment by hageboeck** [comment]
Hi,

sorry, cannot approve. I'm removing almost all uses of RooCatType in #5514 
If I approve this now, I cannot merge that. I can try to rebase your commit on top of #5514 and then remove all merge conflicts. Would that be an option?

**Comment by linev** [comment]
@hageboeck 
It is up to you now. I extract changes in roofit in separate PR. 
But would be nice to merge changes together soon, otherwise `dev` builds after #5535 will be corrupted

**Comment by hageboeck** [comment]
Ok, so I'll take the commit and rebase it.

**Comment by linev** [comment]
Close in favor of #5542

**Pull request closed without merging**
