### PR TITLE
Fix for Visual Studio 2019 v16.7.0

### PR DESCRIPTION
**Pull request by bellenot**
Silly workaround for rootcling not being able to parse the STL headers anymore after the update of Visual Studio to the version 16.7.0:
```
  Generating G__Core.cxx, ../bin/libCore.rootmap
  In file included from input_line_5:1:
  In file included from C:/Users/sftnight/build/release/include\Rtypes.h:191:
  In file included from C:/Users/sftnight/build/release/include/TGenericClassInfo.h:21:
  In file included from C:/Users/sftnight/build/release/include/TSchemaHelper.h:17:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.291  10\\include\string:11:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.291  10\\include\xstring:14:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.291  10\\include\xmemory:16:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.291  10\\include\xutility:15:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility(137,9): error G08EB1F86: expected member name or ';' after declaration specifiers [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
          !_Is_implicitly_default_constructible<_Uty1>::value || !_Is_implicitly_default_constructible<_Uty2>::value)
          ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility(137,9): error GC66A3811: expected ')' [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility:136:23: note: to match this '('
      constexpr explicit(
                        ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility(218,24): error G08EB1F86: expected member name or ';' after declaration specifiers [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
      constexpr explicit(!is_convertible_v<const _Other1&, _Ty1> || !is_convertible_v<const _Other2&, _Ty2>)
      ~~~~~~~~~~~~~~~~~~ ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility(218,24): error GC66A3811: expected ')' [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\utility:218:23: note: to match this '('
      constexpr explicit(!is_convertible_v<const _Other1&, _Ty1> || !is_convertible_v<const _Other2&, _Ty2>)
                        ^
  In file included from input_line_5:1:
  In file included from C:/Users/sftnight/build/release/include\Rtypes.h:191:
  In file included from C:/Users/sftnight/build/release/include/TGenericClassInfo.h:21:
  In file included from C:/Users/sftnight/build/release/include/TSchemaHelper.h:17:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\string:11:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\xstring:14:
  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\xmemory:16:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\xutility(63,31): error G959205E0: '_To' does not refer to a value [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
      return __builtin_bit_cast(_To, _Val);
                                ^
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\\include\xutility:51:17: note: declared here
  template <class _To, class _From,
                  ^
CUSTOMBUILD : error : Error loading the default header files. [C:\Users\sftnight\build\release\core\G__Core.vcxproj]
```
To be checked/removed after the upgrade of LLVM & Clang

### CODE REVIEW

**Comment by bellenot** [comment]
> Why don't you conditionally do that in the build system by adding `-D__CUDACC__` to the relevant rootcling invocations?

Right, that's another way... But then one has to tell users to do it as well in their scripts if they have any

**Comment by bellenot** [comment]
@vgvassilev so indeed, adding `-D__CUDACC__` to the rootcling invocations works as well, but that makes more changes and as I said, one has to tell users to add it in their scripts as well. Maybe @Axel-Naumann has an opinion on this?

**Comment by vgvassilev** [comment]
> > Why don't you conditionally do that in the build system by adding `-D__CUDACC__` to the relevant rootcling invocations?
> 
> Right, that's another way... But then one has to tell users to do it in their scripts as well, if they have any
> And I'm not sure what would happen when typing `#include <string>` in the ROOT prompt. I'll try

Then on the ROOT side like [here](https://github.com/root-project/root/blob/master/core/metacling/src/TCling.cxx#L1299) we can add the -D... Not sure what's best...

**Comment by bellenot** [comment]
> > > Why don't you conditionally do that in the build system by adding `-D__CUDACC__` to the relevant rootcling invocations?
> > 
> > 
> > Right, that's another way... But then one has to tell users to do it in their scripts as well, if they have any
> > And I'm not sure what would happen when typing `#include <string>` in the ROOT prompt. I'll try
> 
> Then on the ROOT side like [here](https://github.com/root-project/root/blob/master/core/metacling/src/TCling.cxx#L1299) we can add the -D... Not sure what's best...

You mean adding `-D__CUDACC__` in `RegisterPreIncludedHeaders`? It's a bit confusing...  And BTW, what's the issue with my patch?

**Comment by bellenot** [comment]
@vgvassilev I'm now trying to add `-D__CUDACC__` in `rootcling_impl.cxx`

**Comment by bellenot** [comment]
@vgvassilev please check now

**Comment by Axel-Naumann** [comment]
I would certainly recommend not to force this on users: the CUDA define is a workaround until cling can parse MSVC stdlib / llvm upgrade. Because of that we should make it widely available but hide it.

**Pull request merged**
