### PR TITLE
[hist] Reduce relative tolerance in an assert in test_tprofile2poly.cxx

### PR DESCRIPTION
**Pull request by guitargeek**
This follows up on 46642ca1c40, reducing the relative tolerance in one case to make the test pass again on macOS ARM.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
This PR still causes macOS 14 ARM test failures. I have [reverted](https://github.com/root-project/root/commit/ab6cdd5ddaf2294f55793d409508ec93dfcffc25) the commit that caused this; please feel free to come up with a "good compromise"!

**Comment by guitargeek** [comment]
> This PR still causes macOS 14 ARM test failures. I have [reverted](https://github.com/root-project/root/commit/ab6cdd5ddaf2294f55793d409508ec93dfcffc25) the commit that caused this; please feel free to come up with a "good compromise"!

It should be fixed now. I was only missing the increased tolerance in the check of the overflow bin, which was not done in the loop where I have already increased the tolerance already

**Review by lmoneta — APPROVED** [review]
LGTM!
A relative error of 1.E-12 should be large enough to take into account some numerical differences.
It is, however, unexpected that the test fails since the code to compute the bin error of the TProfile2Poly and the TProfile2D do the same operations.

**Comment by guitargeek** [comment]
Thanks. I have taken you comment and also added it to the test.

**Pull request merged**
