### PR TITLE
[cling] Backport jitlink ppc64

### PR DESCRIPTION
**Pull request by bzEq**
# This Pull request:

## Changes or fixes:
Backport jitlink ppc64 backend

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This is based on https://github.com/hahnjo/root/tree/llvm16, however I didn't find the base repository in the list when I was creating this PR.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@smuzaffar can you trigger a build on the ppc64 infrastructure for cmssw?

**Comment by bzEq** [comment]
Build failures are due to calling `empty` in assert, fixing it.

**Comment by bzEq** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by smuzaffar** [comment]
> @smuzaffar can you trigger a build on the ppc64 infrastructure for cmssw?

CMS tests started via https://github.com/cms-sw/root/pull/188

**Comment by hahnjo** [comment]
Merging this depends on https://github.com/root-project/root/pull/13273, so marking as draft.

FWIW the roottest failures are because some references need updates (https://github.com/root-project/roottest/pull/992), but not needed for testing here.

**Comment by vgvassilev** [comment]
@smuzaffar, I see the tests were rejected on the cmssw side but can you help us understand if something was missing on the ppc64 backend side?

**Comment by smuzaffar** [comment]
@vgvassilev , CMS tests [passed](https://github.com/cms-sw/root/pull/188#issuecomment-1782229736) this time. CMSSW build step was failing as `rootcling` failed to build dictionary[a] for one of our package ( which boost headers). Anyway, [patching boost](https://github.com/cms-externals/boost/pull/6) fixed the build issue. 

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0e3c07/35428/build-logs/CondFormats/RunInfo/log.html
```
>> Building LCG reflex dict from header file src/CondFormats/RunInfo/src/classes.h
In file included from input_line_7:57:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_ROOT6_X_2023-10-25-2300/src/CondFormats/RunInfo/src/headers.h:1:
In file included from cmssw/src/CondFormats/RunInfo/interface/RunNumber.h:4:
In file included from cmssw/src/CondFormats/Serialization/interface/Serializable.h:18:
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/external/boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/vector.hpp:26:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/nvp.hpp:35:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/split_free.hpp:22:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/serialization.hpp:14:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/strong_typedef.hpp:28:
  .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/type_traits/has_nothrow_assign.hpp:65:7: warning: builtin __has_nothrow_assign is deprecated; use __is_nothrow_assignable instead [-Wdeprecated-builtins]
       BOOST_HAS_NOTHROW_ASSIGN(T)
....
....
In file included from input_line_7:57:
In file included from cmssw/src/CondFormats/RunInfo/src/headers.h:1:
In file included from cmssw/src/CondFormats/RunInfo/interface/RunNumber.h:4:
In file included from cmssw/src/CondFormats/Serialization/interface/Serializable.h:17:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/string.hpp:23:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/serialization/level.hpp:30:
In file included from .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/mpl/integral_c.hpp:32:
  .../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion]
     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
                              ^
.../boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
#   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
```

**Comment by hahnjo** [comment]
We merged https://github.com/root-project/root/pull/13273 this morning. In order to move forward, we need to
 * [ ] rebase on current `master`
 * [ ] get a list of exact upstream commit hashes that we can apply to https://github.com/root-project/llvm-project/
 * [ ] get a CMSSW test on PowerPC64 (the above test is for `x86`!)

**Comment by bzEq** [comment]
>  rebase on current master
Sure.

> get a list of exact upstream commit hashes that we can apply to https://github.com/root-project/llvm-project/
Will do. Must be noted, some commits are not cherry-picked cleanly.

> get a CMSSW test on PowerPC64 (the above test is for x86!)
Can you elaborate?

**Comment by hahnjo** [comment]
> > get a list of exact upstream commit hashes that we can apply to https://github.com/root-project/llvm-project/
> 
> Will do. Must be noted, some commits are not cherry-picked cleanly.

Ok, is this because of other changes? Ideally, we really want to apply upstream commits so that they automatically rebase out during the next upgrade.

> > get a CMSSW test on PowerPC64 (the above test is for x86!)
> 
> Can you elaborate?

https://github.com/root-project/root/pull/13850#issuecomment-1782483745 notes that CMS tests passed, however that is for the `amd64` architecture, *not* for `ppc64le`!

**Comment by bzEq** [comment]
> Ok, is this because of other changes?

Yes. When started to develop, JITLink for ppc64 was based on LLVM-17. There are misc changes between 16.x and 17.x in APIs and code structures.

**Comment by hahnjo** [comment]
Right. If there are other infrastructure changes to backport to make things easier, we can also do that.

**Comment by hahnjo** [comment]
@bzEq can you please prepare the list of upstream commit hashes that you are backporting here?

**Comment by bzEq** [comment]
> @bzEq can you please prepare the list of upstream commit hashes that you are backporting here?

They are
```
18dc8dcd768f [PowerPC][JITLink] Support R_PPC64_GOT_TLSGD_PCREL34 (#68660)
a712244f3b76 [PowerPC][JITLink] Support R_PPC64_GOT_PCREL34 (#68658)
1dae4dd0d80f [JITLink][PowerPC] Fix incorrect assertion of addend for R_PPC64_REL24
94239712eb17 Fix typos in comments of ExecutionEngine (NFC)
b6e2eac2930e [JITLink][PowerPC] Add relocations included in rtdyld but missing from jitlink
d6791fb77402 [JITLink][PowerPC] Fix relocations in stubs for ppc64 big-endian target
9c38a178d3a6 [JITLink][PowerPC] Add basic TLS support for ppc64
5cb2a78ac2fe [Orc][PowerPC] Enable ELFNixPlatform support for ppc64le
ca6d86f6bf12 [JITLink][PowerPC] Support R_PPC64_PCREL34
11a02de7829a [JITLink][PowerPC] Change method to check if a symbol is external to current object
7bf9c5bbb7d1 [JITLink] ppc64.h - fix MSVC "not all control paths return a value" warning. NFC.
995f199f0a76 [JITLink][PowerPC] Correct handling of R_PPC64_REL24_NOTOC
74f2a76904d7 [JITLink] Rename TableManager::appendEntry, add comment.
79786c4d23f1 [JITLink][PowerPC] Fixed unused variable warning. NFC.
61358d4fbeb3 [JITLink][PowerPC] Add TOC and relocations for ppc64
52b88457baf8 [JITLink] Use SubtargetFeatures to store features in LinkGraph
846bde483d63 Silence switch statement contains 'default' but no 'case' labels warning; NFC
8313507a7c3f [JITLink][ELF][ppc64] Add skeleton ppc64 support and ELF/ppc64 JITLink backend.
```
`52b88457baf8` can't be cherry-pick'ed cleanly.

**Comment by bzEq** [comment]
I'm not familiar with root's llvm merging strategy, how to fix above llvm-diff errors?

**Comment by hahnjo** [comment]
> I'm not familiar with root's llvm merging strategy, how to fix above llvm-diff errors?

We need to have a tag in https://github.com/root-project/llvm-project/. I will take care of this, that's why I asked for the commit hashes :wink: 

In the mean time, it would be great to get CMS testing on `ppc64le`. @smuzaffar can you help with that? Now that the LLVM upgrade is merged, I guess this should be a bit easier...

**Comment by smuzaffar** [comment]
@hahnjo , I have opened https://github.com/cms-sw/root/pull/192 and will start testing it once ppc64le Integration Build (IB) based on ROOT master is available ( hopefully tomorrow morning)

**Comment by smuzaffar** [comment]
cms tests passed for production arch (el8_amd64_gcc12) and powerpc

**Comment by hahnjo** [comment]
> cms tests passed for production arch (el8_amd64_gcc12) and powerpc

Thanks! And I understand correctly it solves some problems that were there on ppc64le before?

**Comment by smuzaffar** [comment]
> > cms tests passed for production arch (el8_amd64_gcc12) and powerpc
> 
> Thanks! And I understand correctly it solves some problems that were there on ppc64le before?

@hahnjo , most of ppc64le issues (e.g. https://github.com/cms-sw/cmssw/issues/41658) were already fixed when we moved to ROOT 6.30 ( LLVM 13). In order to test this jitlink ppc64 change we need to test it for ROOT 6.26 e.g. CMSSW_13_3_X IBs where we still get errors (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_13_3/2023-12-19-2300?selectedArchs=el8_ppc64le_gcc12&selectedFlavors=X&selectedStatus=failed ). If you can open a PR for root 6.26 patches branch then I can test it

**Comment by hahnjo** [comment]
> > > cms tests passed for production arch (el8_amd64_gcc12) and powerpc
> > 
> > Thanks! And I understand correctly it solves some problems that were there on ppc64le before?
> 
> @hahnjo , most of ppc64le issues (e.g. [cms-sw/cmssw#41658](https://github.com/cms-sw/cmssw/issues/41658)) were already fixed when we moved to ROOT 6.30 ( LLVM 13).

Ah ok, so it wasn't the JIT linker infrastructure after all. That's good to hear, I hope things are still equally fine in `ROOT6` now with LLVM 16. But then does this JITLink backport actually still solve some issues on top of that?

> In order to test this jitlink ppc64 change we need to test it for ROOT 6.26 e.g. CMSSW_13_3_X IBs where we still get errors (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_13_3/2023-12-19-2300?selectedArchs=el8_ppc64le_gcc12&selectedFlavors=X&selectedStatus=failed ). If you can open a PR for root 6.26 patches branch then I can test it

ROOT 6.26 had LLVM 9, it would be very hard to backport these JITLink changes there. And also, if the upgrade to LLVM 13 already solved most issues, it seems questionable to me that it would improve anything, or am I missing something?

**Comment by vgvassilev** [comment]
The dust is mostly settled from the llvm16 upgrade. This PR becomes important for cmssw and we should probably include it in the next release. Let's move forward here.

**Comment by hahnjo** [comment]
> The dust is mostly settled from the llvm16 upgrade. This PR becomes important for cmssw and we should probably include it in the next release. Let's move forward here.

To be fair, what I heard from CMS is that most things already work with ROOT 6.30... But yes, we need to synchronize the commits into https://github.com/root-project/llvm-project/; that's on me, I was hoping that I can replace three patches by proper backports before though...

**Comment by vgvassilev** [comment]
I was wondering if we have an ETA for this since this is still biting cms...

**Comment by hahnjo** [comment]
To be honest, my interpretation of https://github.com/root-project/root/pull/13850#issuecomment-1867519153 is that most failures are solved by the upgrade to ROOT 6.30 / LLVM 13. We will not be backporting to ROOT 6.26 / LLVM 9 and I haven't see confirmation that this fixes anything on top of LLVM 13 or LLVM 16, so it's not on the top of my priority list.

**Comment by vgvassilev** [comment]
I'd like to move forward with this in the current master as soon as possible. This is a general improvement in terms of stability and maintenance and we probably should not wait until bugs start showing up to justify getting this in. Is there anything else that's required before merging it?

**Comment by vgvassilev** [comment]
@bzEq, could you rebase?

**Comment by bzEq** [comment]
Rebased.

**Comment by vgvassilev** [comment]
@hahnjo, @smuzaffar let me know if you have any objections in moving forward here.

@hahnjo, can you give us a link to what we should follow to update the llvm monorepo with these changes to make the `Diff LLVM and Clang against fork of monorepo` happy?

**Comment by hahnjo** [comment]
> I'd like to move forward with this in the current master as soon as possible. This is a general improvement in terms of stability and maintenance and we probably should not wait until bugs start showing up to justify getting this in. Is there anything else that's required before merging it?

Okay, that's a totally different motivation. The previous argument was that this is "changing the world" for CMS, which is not the case in my current understanding and we should therefore stop claiming.

> @hahnjo, @smuzaffar let me know if you have any objections in moving forward here.

I have mixed feelings about backporting that many commits for an architecture where we don't have immediate bug reports at the moment that would be solved by the changes. ROOT currently relies on LLVM 16 and that has a certain number of features and supported platforms; in my understanding these changes come in anyway with the next upgrade, right?

**Comment by smuzaffar** [comment]
We have moved to ROOT 6.30 for our latest production release. So this is not an issue any more for latest CMSSW releases.
For CMSSW release cycle e.g. for following release cycles which use root 6.26 we still have 25 relvals failing with error [a]
- 13.3.X https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_13_3_X (based on root commit 9583d15fbe80462d1ed555b6664aa679e4633216)
- 13.2.X https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_13_2_X (based on root commit 65c222e5118e03035be81a458ac97ce868b82478)

Although CMSSW_13_0_X, CMSSW_13_1_X also are based on root 6.26 patches branches but we do not get such failures for these releases. The root differences between 13.1.X and 13.2.X are https://github.com/root-project/root/compare/38994b6a72...a25c523160 .

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_ppc64le_gcc11/CMSSW_13_2_X_2024-02-11-2300/pyRelValMatrixLogs/run/20034.0_TTbar_14TeV+2026D86/step2_TTbar_14TeV+2026D86.log
```
#15 0x000010080ba32c48 in cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction&) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#16 0x000010080b998394 in cling::Interpreter::executeTransaction(cling::Transaction&) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#17 0x000010080ba4a354 in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#18 0x000010080ba4bb50 in cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#19 0x000010080b993b08 in cling::Interpreter::parseForModule(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#20 0x000010080b8897bc in ExecAutoParse(char const*, bool, cling::Interpreter*) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#21 0x000010080b89a058 in TCling::AutoParseImplRecurse(char const*, bool) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#22 0x000010080b89fda4 in TCling::AutoParse(char const*) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#23 0x000010080b86e918 in TClingLookupHelper__AutoParse(char const*) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
#24 0x000010080b7ac95c in ROOT::TMetaUtils::TClingLookupHelper::GetPartiallyDesugaredNameWithScopeHandling(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) () from /cvmfs/cms-ib.cern.ch/sw/ppc64le/week0/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_2_X_2024-02-11-2300/external/el8_ppc64le_gcc11/lib/libCling.so
```

**Comment by smuzaffar** [comment]
if it is easy to backport this to root 6.26 then I can test it.

**Comment by vgvassilev** [comment]
> if it is easy to backport this to root 6.26 then I can test it.

How difficult is to move to 6.30?

**Comment by vgvassilev** [comment]
> > I'd like to move forward with this in the current master as soon as possible. This is a general improvement in terms of stability and maintenance and we probably should not wait until bugs start showing up to justify getting this in. Is there anything else that's required before merging it?
> 
> Okay, that's a totally different motivation. The previous argument was that this is "changing the world" for CMS, which is not the case in my current understanding and we should therefore stop claiming.

This is still changing the world for CMSSW in long run. The fact that we do not observe bugs for unclear to me reasons does not change that fact. JitLink allows debugging jit'd code along with native support for ppc. Last 10 years RuntimeDyld was a nightmare to maintain and work with. Now that's gone for good.

> 
> > @hahnjo, @smuzaffar let me know if you have any objections in moving forward here.
> 
> I have mixed feelings about backporting that many commits for an architecture where we don't have immediate bug reports at the moment that would be solved by the changes. ROOT currently relies on LLVM 16 and that has a certain number of features and supported platforms; in my understanding these changes come in anyway with the next upgrade, right?

That's correct, since there are multiple entities and workplans included here, there is no reason to wait for the next upgrade which is not planned yet. That leaves out the option to ask for additional bugfixes/features.

**Comment by smuzaffar** [comment]
> > if it is easy to backport this to root 6.26 then I can test it.
> 
> How difficult is to move to 6.30?

change root in production releases is not an easy task. We need to redo the physics  validation which we do not recommend for production cmssw releases.

**Comment by vgvassilev** [comment]
@smuzaffar whats the expected lifetime for 6.26 in cmssw? Is it worth trying to backport eventual fixes for ppc in runtimedyld or entertain the idea of porting back the jitlink backend to llvm9?

@bzEq do you have an idea if there were ppc related fixes in RuntimeDyld between llvm9 and llvm16? If so maybe backporting them can help. If not I can talk with the jitlink maintainers if it is even feasible to backport jitlink ppc to llvm9

**Comment by smuzaffar** [comment]
> @smuzaffar whats the expected lifetime for 6.26 in cmssw? Is it worth trying to backport eventual fixes for ppc in runtimedyld or entertain the idea of porting back the jitlink backend to llvm9?

 looking at the releases where we use root 6.26 [a] and ppc64le has issues, lifetime could be indefinite ( specially if these are used for analysis). As  user mostly use `x86_64` for analysis, so I think we can survive without backporting this to 6.26

[a]
```
Cycle [CMSSW_13_3_0](https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_13_3_0) General Software updates aiming for 2024. Nano v13 and possibly Mini v4. Last release to include major changes from Simulation
Cycle [CMSSW_13_2_0](https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_13_2_0) Release for HI data taking in 2023
```

**Review by hahnjo — APPROVED** [review]

**Pull request merged**
