### PR TITLE
[skip-ci][NFC][ntuple] specifications.md --> BinaryFormatSpecification.md

### PR DESCRIPTION
**Pull request by jblomer**

### CODE REVIEW

**Comment by pcanal** [comment]
Since we changing the name of the file, this is a good time to ask whether it should be more specific.  For example a variation on `BinaryFormatSpecification.md` to distinguish it from any API/C++ level specification.

**Comment by silverweed** [comment]
I'm personally fine with `specification`, as I wouldn't consider our API a "specification" in any sense of the term: just a particular implementation of the binary specs.

**Comment by jblomer** [comment]
Here is a suggestion with `BinaryFormatSpecification.md` and, for consistency, `Architecture.md` (capitalized).

**Comment by hahnjo** [comment]
I don't have a strong opinion how the files should be named...

**Pull request merged**
