### PR TITLE
Do not look for clad* libs if clad is off.

### PR DESCRIPTION
**Pull request by vgvassilev**
Fixes ROOT-9575.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by amadio** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dccache=Off

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

The reported problems seem to be unrelated but let’s retrigger.

**Pull request merged**
