### PR TITLE
[Do not merge] Test clad master before release.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
> Build failed on windows10/cxx14. Running on null:C:\build\workspace\root-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/151667/console).
> ### Errors:
> 
>     * [2022-08-10T11:41:30.438Z] C:\build\workspace\root-pullrequests-build\build\bin\libCling.dll : fatal error LNK1120: 3 unresolved externals [C:\build\workspace\root-pullrequests-build\build\core\metacling\src\Cling.vcxproj]

```
14:41:28    RIO.vcxproj -> C:\build\workspace\root-pullrequests-build\build\bin\libRIO.dll
14:41:28    Building Custom Rule C:/build/workspace/root-pullrequests-build/root/core/metacling/src/CMakeLists.txt
14:41:28    Auto build dll exports
14:41:30       Creating library C:/build/workspace/root-pullrequests-build/build/lib/libCling.lib and object C:/build/workspace/root-pullrequests-build/build/lib/libCling.exp
14:41:30  cladPlugin.lib(ClangPlugin.obj) : error LNK2019: unresolved external symbol "public: struct clad::DerivativeAndOverload __thiscall clad::DerivativeBuilder::Derive(class clad::DiffRequest const &)" (?Derive@DerivativeBuilder@clad@@QAE?AUDerivativeAndOverload@2@ABVDiffRequest@2@@Z) referenced in function "public: class clang::FunctionDecl * __thiscall clad::plugin::CladPlugin::ProcessDiffRequest(struct clad::DiffRequest &)" (?ProcessDiffRequest@CladPlugin@plugin@clad@@QAEPAVFunctionDecl@clang@@AAUDiffRequest@3@@Z) [C:\build\workspace\root-pullrequests-build\build\core\metacling\src\Cling.vcxproj]
14:41:30  cladDifferentiator.lib(ReverseModeVisitor.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall clad::MultiplexExternalRMVSource::ActAfterParsingDiffArgs(struct clad::DiffRequest const &,class llvm::SmallVector<class clang::ValueDecl const *,16> &)" (?ActAfterParsingDiffArgs@MultiplexExternalRMVSource@clad@@UAEXABUDiffRequest@2@AAV?$SmallVector@PBVValueDecl@clang@@$0BA@@llvm@@@Z) [C:\build\workspace\root-pullrequests-build\build\core\metacling\src\Cling.vcxproj]
14:41:30  cladDifferentiator.lib(ReverseModeVisitor.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall clad::MultiplexExternalRMVSource::ActOnStartOfDerivedFnBody(struct clad::DiffRequest const &)" (?ActOnStartOfDerivedFnBody@MultiplexExternalRMVSource@clad@@UAEXABUDiffRequest@2@@Z) [C:\build\workspace\root-pullrequests-build\build\core\metacling\src\Cling.vcxproj]
14:41:30  C:\build\workspace\root-pullrequests-build\build\bin\libCling.dll : fatal error LNK1120: 3 unresolved externals [C:\build\workspace\root-pullrequests-build\build\core\metacling\src\Cling.vcxproj]
14:41:30  Command exited with the value: 1
```

Hi @bellenot, do you have an idea what needs to be fixed here? Is it that I need to add something to the list of the libCling exports?

**Comment by bellenot** [comment]
> Hi @bellenot, do you have an idea what needs to be fixed here? Is it that I need to add something to the list of the libCling exports?

I don't think so. Make sure the unresolved symbols are not inline functions

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
> > Hi @bellenot, do you have an idea what needs to be fixed here? Is it that I need to add something to the list of the libCling exports?
> 
> I don't think so. Make sure the unresolved symbols are not inline functions

I am not sure I can follow. Should I not have inline functions?

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
Seems like we are good for a release. Thanks again @bellenot for the windows patch!

**Pull request closed without merging**
