### PR TITLE
[cxxmodules] Refactor LoadCoreModules.

### PR DESCRIPTION
**Pull request by Teemperor**
Refactored LoadCoreModules that it now prints a warning if a module isn't found. Also fixes some nullptr-derefs from the old code where we accessed pointers before checking if they're null.

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
Uff, clang format doesn't like the RegisterModule way of doing things...

**Comment by Teemperor** [comment]
@phsft-bot build with flags -Druntime_cxxmodules=Off -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
@Axel-Naumann @pcanal Can you review commit ecbc8935771a77e32cf6cf570e563b3d3d7948a0 ?
@vgvassilev Can you review commit 97fbd59a087459e83569a8b37e6b42512776623d ?
@amadio Can you review commit ba0bb14ca75f99fa77af607e06db51af4c365bfd ?

**Comment by Teemperor** [comment]
Additional runtime modules failures are because of the (legitimate) warning that we can't find modules sometimes.

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=Off -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
@phsft-bot build just on centos7/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
@phsft-bot build just on centos7/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on -Droofit=Off

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on -Droofit=Off

**Comment by amadio** [comment]
What is the status here? Should this be updated and merged, or closed?

**Comment by Teemperor** [comment]
Well, it mostly just exposes a bug more visible (the lack of codegen when loading code with `LoadModule`) which causes more tests to fail. And fixing codegen problems isn't very straightforward :)

**Comment by vgvassilev** [comment]
@Teemperor can you rebase or shall I?

**Comment by vgvassilev** [comment]
That's PR #1665.

**Pull request closed without merging**
