### PR TITLE
[cxxmodules] Enable a few modules for Windows. Now we can run hsimple.C.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/cxx14 with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build!

@bellenot let's merge this PR, it does not affect the status of the regular builds and slightly improve the status of modules support on Windows.

**Review by bellenot — APPROVED** [review]
OK, I agree, let's merge, so I can then make PRs against the master. Thanks Vassil!

**Pull request merged**
