### PR TITLE
Adjust reference for Aarch64

### PR DESCRIPTION
**Pull request by ellert**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks, Mattias!

We're running and passing on AArch64: http://cdash.cern.ch/viewTest.php?onlypassed&buildid=515508

What's different about yours?

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by couet** [comment]
Hi Matthias, sorry for the late reply. I have recently changed the stressgraphics ref file. Can you take the new one and verify it on your machine ? I guess you will need to submit a new version of the ref file in this PR.

**Comment by ellert** [comment]
Since this PR was submitted there has been 1 commit to the stressGraphics.ref file in master. That commit changed the numbers for test number 27. This PR changes the results for test number 32, 33, 38 and 40. This is sufficiently far away from 27 that the PR can still be merged without conflicts, so there is no need to rebase. The PR was created to address issues found when building root 6.12, but the same results apply also for root 6.14.

**Comment by couet** [comment]
@phsft-bot build

**Pull request merged**
