### PR TITLE
Add initializer_list constructor to TVectorT.

### PR DESCRIPTION
**Pull request by hageboeck**
Initially, this was to try out the suggestion [in #7151](https://github.com/root-project/root/issues/7151#issuecomment-1047822177), to enable code like
```c++
TGraph gr({1, 2, 3}, {1, 2, 3});
```

This doesn't work, unfortunately, because overload resolution cannot disambiguate between the `TVectorF` and `TVectorD` constructors of TGraph.

What this enables, however, is this:
```c++
TVectorD{1., 2., 3.}
```
or for the TGraph case:
```c++
TGraph gr(TVectorD{1., 2., 3.}, {1., 2., 3.});
```

I think it's a nice shortcut to have.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Could we have a tiny, little test?

**Comment by Axel-Naumann** [comment]
Totally, if that's a test? :-) Thank you!

**Comment by ferdymercury** [comment]
> disambiguate between the `TVectorF` and `TVectorD` constructors of TGraph.

Does it work if you use:
`TGraph gr({1.d, 2.d, 3.d}, {1, 2, 3});`
?

**Comment by hageboeck** [comment]
> > disambiguate between the `TVectorF` and `TVectorD` constructors of TGraph.
> 
> Does it work if you use: `TGraph gr({1.d, 2.d, 3.d}, {1, 2, 3});` ?

No, `.d` doesn't exist in C++. See the section on "suffix" [here](https://en.cppreference.com/w/cpp/language/floating_literal).

**Comment by ferdymercury** [comment]
Ohh, I see. And with the decimal point but no "d", why does it still thinks it's ambiguous although you are explicitly forcing it to be double?
`
TGraph gr({1., 2., 3.}, {1, 2, 3});`

**Comment by dpiparo** [comment]
@lmoneta the reason why this is not merged is not clear to me: could you clarify?

**Comment by guitargeek** [comment]
I think there were failing tests because suddenly, some overload resolutions became ambiguous. For example when a function has an overload for `TVector` and `std:vector`, this is now ambiguous because both can be implicitly constructed via initializer list.

**Comment by guitargeek** [comment]
> @lmoneta the reason why this is not merged is not clear to me: could you clarify?

Ah, now I remember!

This would be a backwards incompatible change, because it changes the meaning of

```c++
TVectorD{5};
```
Before, this created a vector with 5 zero elements. With this PR, it will create a vector with a single 5!

This is way to backwards incompatible to be merged. @hageboeck maybe came to the same conclusion, and for that reason decided to not continue working on this PR anymore. Making it work in a backwards compatible way is probably not worth the effort for a legacy pre-STL class like `TVector`.

I would instead suggest to change the interfaces of for example TGraph so that they can take initializer lists directly without going over the `TVectorT`.

We can also wait for C++23, which will introduce a `std::span` constructor from initializer list. Then we also have the option to use `std::span` in the interfaces to cover this usecase without losing generality: a TVectorT can probably be converted to a `std::span` too.

**Comment by lmoneta** [comment]
I agree with you @guitargeek , TVectorT is a legacy class and I would not change its interface. It is better to add the constructor from the initialiser list directly in the TGraph

**Comment by guitargeek** [comment]
Ok! Let's close this PR then

**Pull request closed without merging**
