### PR TITLE
Added methods GetInfo and GetClassName to TestStatistics likelihood classes

### PR DESCRIPTION
**Pull request by Zeff020**
# This Pull request:

Added some instrospection methods to TestStatistics Likelihood classes and also added corresponding tests. In particular added GetName() and GetInfo(). GetName() follows the same interface as the other RooFit classes in order to stay consistent. GetInfo() returns an std::string which allows for the added flexibility of concatenating more information about the class.

Also added getComponents() to RooSumL in order to retrieve the vector of components from the sum likelihood.

Note I am not completely happy about the implementation of the naming, in particular with the fact that the name needs to be supplied to the constructor of the RooAbsL class. Another option would be to override the GetName() and GetInfo() functions in each of the child classes explicitly with the same implementation, in which case we could have a unique name_ variable in each of the child classes and no need for the modification to the constructors. Let me know if this is preferred.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Review by guitargeek — CHANGES_REQUESTED** [review]
Hi Zef, thanks for opening the PR!

Ok I see now what you want to achieve! So the name that you want to add to the likelihood classes is not like usual for RooFit objects a name that is different for each instance, but it's a name that is not per instance but per class.

I'd suggest therefore to change the interface to make that difference clear. What about adding a new function to `RooAbsL` like `getClassName`?
```C++
const char * GetClassName() = 0;
```
And then you override this function in each likelihood implementation to return it's name? Then in `GetName` and `GetInfo`, you can call this function to build the instance name and info string how you like.

The thing is it's not so nice to have an extra string member for RooAbsL that is actually static. And as you probably already noticed, it makes the RooAbsL constructors also a bit messier because you have to account now for these different ways of constructing it with different combination of keyword arguments.

How does that sound like to you?

**Comment by Zeff020** [comment]
Hi @guitargeek, yeah that does sound like a good idea. The reason why I kept the GetName() just as the class name for now is that I wanted to avoid building the full name as a char* to not have to deal with messy c-string concatenation in a very simple function.

**Comment by guitargeek** [comment]
Yes, right, it's better to use `std::string` whenever necessary

**Comment by Zeff020** [comment]
Hi @guitargeek, I think this is probably how you intended it. I've reverted the earlier commit and made a new one with your suggestion but feel free to squash them into a single commit when merging, there are not that many changes in this PR anyway. I've mostly avoided touching GetName as the current implementation is probably already pretty similar to how it works in the rest of RooFit.

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by Zeff020** [comment]
Hi @guitargeek, I believe the changes are addressed and the builds are passing, is there any reason not to merge for now? I am happy to address more changes if required.

**Review by guitargeek — APPROVED** [review]
Hi Zef! Yes you're right, thanks for the reminder.

* LGTM, new functionality described in the PR description was implemented with some unit tests and the PR comments were addressed.

**Pull request merged**
