### PR TITLE
[Core] Allow for whitespace between quotes and outer braces

### LINKED ISSUE #14462: Parser for I/O customization rule is too strict.
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

A rule like:
```
#pragma read sourceClass="userClass" targetClass="userClass" source="" target="transientMember" version="[1-]" code="{ transientMember = true; } "
```
fails because of the trailing space in code.  Instead:
```
code="{ transientMember = true; }"
```
works.

### Reproducer

With class:
```
class userClass
{
   bool transientMember;
};
```

### ROOT version

master

### Installation method

any

### Operating system

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gemmeren**
# This Pull request:

## Changes or fixes:
Fixes #14462

## Checklist:

- [x] tested changes locally
- [n/a] updated the docs (if necessary)

This PR fixes 
Removes additional whitespace between quotes and braces. @pcanal

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build

**Comment by gemmeren** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
@phsft-bot build

**Comment by gemmeren** [comment]
Ok, I need to rethink this, since the current change looses command elements after code key. Part of the problem is code fragment can include either curly braces or quotes, so finding the end of the key isn't quite as trivial.

**Comment by gemmeren** [comment]
I'll close this and open a new PR when I find a better solution.

**Pull request closed without merging**
