### PR TITLE
handle NaN EDM better

### PR DESCRIPTION
**Pull request by HDembinski**
When the EDM value in Migrad is NaN, it nevertheless reports convergence, because failure to converge is detected with the condition (edm > edmval) which fails (wrongly) if edm is NaN.

The added code aborts the minimization at the earliest point if edm is NaN.

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build!

**Review by lmoneta — APPROVED** [review]
Looks good to me ! Thank you Hans for this useful fix!

**Comment by HDembinski** [comment]
> Looks good to me !

Thanks! The CI jobs fail because I need to use `std::isnan` instead of `isnan`. I will fix that.

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
@phsft-bot  build

**Comment by lmoneta** [comment]
Retrying to build this PR. Seems the builds did not work before

**Pull request merged**
