### PR TITLE
[CI] Add a first arm run.

### PR DESCRIPTION
**Pull request by hageboeck**
- Add a new step running on self-hosted arm machines.
- Add a machine tag to S3 URL to not clash with x86 builds.

### CODE REVIEW

**Comment by dpiparo** [comment]
This is really good stuff. ARM nodes are appearing on WLCG and testing on that platform will automatically improve the sw stacks of LHC experiments. The test failure needs some thinking but it does not seem a complex issue. If I may suggest this, I would also make sure that a clear indicator of the platform appears in the label of the build ("ARM", "Aarch"...)

**Comment by hahnjo** [comment]
Is there a reason we need `-march=native` on AArch64? I think a more "standard" configuration might be better for the start...

**Comment by hageboeck** [comment]
> Is there a reason we need `-march=native` on AArch64? I think a more "standard" configuration might be better for the start...

No particular reason. I just copied the config from the build above.

**Review by dpiparo — APPROVED** [review]
LGTM!

**Pull request merged**
