### PR TITLE
Update RootMacros.cmake

### PR DESCRIPTION
**Pull request by rlalik**
Fix root-project/root#6777

* includes COMPILE_FEATURES for compiling dictionary files

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Review by oshadura — APPROVED** [review]
For me this PR looks reasonable, but I will invite @vgvassilev to recheck

**Comment by vgvassilev** [comment]
Indeed, LGTM!

**Comment by oshadura** [comment]
@rlalik could you please backport into 6.22-patches branch please?

**Comment by rlalik** [comment]
> @rlalik could you please backport into 6.22-patches branch please?

You mean I should made PR into 6.22-patches instead of master, right?

**Comment by oshadura** [comment]
@rlalik ah no, I just wanted to say that your fix will be available only in the next ROOT release 6.24, otherwise you could _as well_ open PR to https://github.com/root-project/root/tree/v6-22-00-patches so it could be available in next patch 6.22 release - 6.22.08 (I am not sure if it  is planned)

**Pull request merged**
