### PR TITLE
[cmake] Some improvements related to feature detection

### PR DESCRIPTION
**Pull request by guitargeek**
More detail in the commit descriptions.

### CODE REVIEW

**Review by bellenot — COMMENTED** [review]
I'll let @linev review this part

**Review by bellenot — APPROVED** [review]
LGTM, but let's wait for the review of @linev

**Comment by linev** [comment]
I need to check it while here two different Qt versions may be tested in one cmake file.

**Comment by guitargeek** [comment]
Thank you! Are you checking it yourself, or is there something I can do to help?

**Comment by linev** [comment]
> Are you checking it yourself, or is there something I can do to help?

I checking on my desktop machine where both Qt5 and Qt6 are installed and I always compiling both libs.

**Review by linev — CHANGES_REQUESTED** [review]
Qt5 and Qt6 conflict with each other when used from same cmake file.
If interesting, here error output:
```
-- Looking for TBB
-- Looking for BLAS for optional parts of TMVA
-- PyROOT: development package found. Building for version 3.11.7
CMake Error at /usr/lib64/cmake/Qt6Qml/Qt6QmlMacros.cmake:2415 (message):
  qt_generate_foreign_qml_types() is only available in Qt 6.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Qml/Qt6QmlConfig.cmake:132 (include)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  /usr/lib64/cmake/Qt6Quick/Qt6QuickDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  /usr/lib64/cmake/Qt6Quick/Qt6QuickConfig.cmake:50 (include)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake:50 (include)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  /usr/lib64/cmake/Qt6/Qt6Config.cmake:166 (find_package)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:2026 (find_package)
  CMakeLists.txt:298 (include)


CMake Warning at cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6Quick/Qt6QuickConfig.cmake

  but it set Qt6Quick_FOUND to FALSE so package "Qt6Quick" is considered to
  be NOT FOUND.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake:50 (include)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  /usr/lib64/cmake/Qt6/Qt6Config.cmake:166 (find_package)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:2026 (find_package)
  CMakeLists.txt:298 (include)


CMake Warning at cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake

  but it set Qt6WebEngineCore_FOUND to FALSE so package "Qt6WebEngineCore" is
  considered to be NOT FOUND.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6/Qt6Config.cmake:166 (find_package)
  cmake/modules/SearchInstalledSoftware.cmake:18 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:2026 (find_package)
  CMakeLists.txt:298 (include)
```

**Comment by guitargeek** [comment]
Ok, thanks for checking @linev! In that case, I'll remove the commit with the `Qt` detection from this PR. It was not so important for me anyway, the main motivation for this PR was that ROOT doesn't silently disable CUDA.

Are you okay with how the PR is now, @linev?

**Review by linev — APPROVED** [review]
Now it works for me.

Seems to be policy is no longer required.
I using cmake `3.28.1`

**Pull request merged**
