### PR TITLE
Use `std::stringstream` instead of `TString` and `char[]`

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by bellenot** [comment]
@phsft-bot build with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by linev** [comment]
Bertrand
Now Jenkins too smart - once failed, it will not start new compiling jobs. 
One need to add more commits and exclude `ROOT-performance-centos7-multicore/default`, which has problem with configuring cmake for LLVM

**Comment by linev** [comment]
>    * warning: format string is not a string literal (potentially insecure) [-Wformat-security]

I will fix warnings with next PR - they didn't appears when I was submitting my last PR

**Comment by bellenot** [comment]
@phsft-bot build just on fedora27/noimt fedora29/python3 ubuntu16/rtcxxmod mac1014/cxx17 windows10/default with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by bellenot** [comment]
@phsft-bot build just on ROOT-fedora27/noimt ROOT-fedora29/python3 ROOT-ubuntu16/rtcxxmod  windows10/default with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by linev** [comment]
@phsft-bot  build just on ROOT-fedora27/noimt, ROOT-fedora29/python3,  ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags  -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by linev** [comment]
@bellenot Jenkins is going crazy. I use last command with other PR #3477 and it works properly. Now it does not :-(

**Comment by linev** [comment]
And one need to push some more commits, otherwise Jenkins will do nothing

**Comment by bellenot** [comment]
I'm fed-up with this crappy infrastructure :angry:

**Comment by bellenot** [comment]
@phsft-bot build just on ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Pull request merged**
