### PR TITLE
TH1 KolmogorovTest infinite loop

### PR DESCRIPTION
**Pull request by ashlaban**
[EDIT]: 2017-07-20 dropped commit (6953483).

See the commit messages for detailed descriptions of the changes. In essence, when comparing some data with the KolmogorovTest an infinite loop was triggered.

(bba95dd) We want to get an approximate solution to the test despite there being some bins with neg. content
(06024c8) To prevent the infinite loop in other cases, calling FillRandom with a histogram with negative content is now an error.
(6953483) The caching inside GetRandom can violate an invariant of the function. (Always return NaN when there is a bin with neg. content in the source histogram). [EDIT] Removed after discussion with Lorenzo. The recomputation of the integral here was deemed too expensive as the function is intended to be called in tight loops.

Since these changes might have far reaching effects I am up for discussion whether any commits should be dropped.

A reproducer in can be found [here](https://gist.github.com/ashlaban/05552ab5f5a7aa05e9c9b73229b2dba4).

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build

**Comment by Teemperor** [comment]
@phsft-bot build

and stop spamming

**Comment by gganis** [comment]
Hi, including the patch in my build I have failed to reproduce the problem on the same machine where it occurred (mac1012/native).
Maybe a glitch or some other strange effect.
This said, the developer taking care of TH1 is back next week and I think we need his advise on this change.

**Comment by ashlaban** [comment]
Sounds good, thanks for looking into it!

**Comment by ashlaban** [comment]
Hi, who is the TH1 developer? I think it is time to check in with him :)

**Comment by ashlaban** [comment]
Ping @lmoneta. Updated according to our discussion.

**Pull request merged**
