### PR TITLE
Reset function sections before JITting

### PR DESCRIPTION
**Pull request by hahnjo**
This makes all functions end up in the same text section, which is important for TCling on macOS to catch exceptions from constructors: Stack unwinding requires information about program addresses to find out which objects to destroy and what code should be called to handle the exception. These addresses are relocated against a single __text section when loading the produced MachO binary, which breaks if the call sites of global constructors end up in a separate init section.

Fixes ROOT-10703 and ROOT-10962

(cherry picked from commit 028fcca0fa76111877751df876cf13968be602f9)

### CODE REVIEW

**Comment by hahnjo** [comment]
I actually added a test as part of https://github.com/root-project/root/pull/7100 two years ago, but this part was removed during the llvm13 upgrade and nobody noticed because we only ran the Cling test suite on Linux :cry: Note that `check-cling` actually very red on macOS, but most of that seems to come from `-lSystem`? @Axel-Naumann

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/nortcxxmod, mac11/cxx14, mac12/noimt

**Comment by hahnjo** [comment]
ping @Axel-Naumann, I think this would also be good to have in 6.28/00 (I will prepare a backport shortly, but the fix should be merged into `master` first)

**Review by Axel-Naumann — APPROVED** [review]
Thanks, looks good to me (but I'm certainly not an expert). Any chance of exposing this upstream?

**Comment by hahnjo** [comment]
See https://github.com/root-project/root/pull/7100#issuecomment-767654480 for my answer on this from two years ago.

**Comment by Axel-Naumann** [comment]
> See https://github.com/root-project/root/pull/7100#issuecomment-767654480 for my answer on this from two years ago.

😂 Wow you are amazing! Thanks! And 💯 for revisiting our clang/llvm branch sync!

**Pull request merged**
