### PR TITLE
[CMake][Exp PyROOT] Build pyunittests for all the python versions - solution 2

### PR DESCRIPTION
**Pull request by maxgalli**

### CODE REVIEW

**Comment by maxgalli** [comment]
@phsft-bot build

**Comment by oshadura** [comment]
We will need once to discuss this PR and https://github.com/root-project/root/pull/5249 . Do you have preferred solution? :)

**Comment by maxgalli** [comment]
> We will need once to discuss this PR and #5249 . Do you have preferred solution? :)

Personally I find more clear #5249, but I get the point of @etejedor who prefers this, so I'm working mainly on this one.

**Comment by etejedor** [comment]
We can perhaps have a meeting to discuss the pros and cons of one and the other? Let's continue on mattermost.

**Comment by maxgalli** [comment]
closed for now, might be revisited later

**Pull request closed without merging**
