### PR TITLE
Do not draw error bars when they are smaller than the marker.

### PR DESCRIPTION
**Pull request by couet**
In TGrpahErrors TGraphAsymmErrors and TGraphBentErrors, the error bars were drawn inside the marker when the marker was bigger than the error bars. This was reported in this forum post: https://root-forum.cern.ch/t/error-bars-inside-markers-with-draw-same/60631

### CODE REVIEW

**Review by linev — APPROVED** [review]

**Comment by couet** [comment]
Failing tests on Mac:
```
1575:roottest-graphics-AtlasExample_o << do not see any difference compared to the previous version .....
1716:roottest-graphics-graphreverse_o  << understood, more investigations needed
1824:roottest-graphics-ratioplot1_o.       << do not see any difference compared to the previous version .....
```

**Comment by dpiparo** [comment]
@linev @couet how is the process to fix those tests?

**Comment by couet** [comment]
I am on it

**Comment by couet** [comment]
I am looking at AtlasExample.C. For some reason I do not understand yet it seems the error bars are drawn up->down, unlike the other plots. That's why it does not pass. I am investigating.

**Comment by couet** [comment]
The failure of AtlasExample.C is understood. I have changed the solid circle marker to a hollow one.  Here is what I get. On the right the current master on the left the version with this fix applied. One can clearly see extra lines (inward error bars) on the right one because the marker is larger than the error bars. Of course that generates extra lines and the size of the SVG file changes. I guess the reference file will need to be regenerated.
Screenshot 2024-09-06 at 13 30 58
I will check ratioplot1.C now, I bet it is the same kind of thing.

**Comment by dpiparo** [comment]
The reference needs to be regenerated if we want to merge this PR.

**Comment by dpiparo** [comment]
@couet see and take ownership of https://github.com/root-project/roottest/pull/1183

**Review by dpiparo — APPROVED** [review]

**Comment by dpiparo** [comment]
I'd like to note that the same testing strategy used for this PR could be applied for https://github.com/root-project/root/pull/16348 in order to move it forward.

**Pull request merged**
