### PR TITLE
Dot help v2

### PR DESCRIPTION
**Pull request by couet**
New PR for .help

### CODE REVIEW

**Comment by couet** [comment]
@Axel-Naumann:  This looks good to merge seems to me. The static analyser error about the missing include file TApplicationCommandLineOptionsHelp.h is because this include is generated at build time and of course not visible when the static analyser ran.

**Comment by pcanal** [comment]
Can we reduce the number of commits, especially the ones with the same commit logs?

**Comment by couet** [comment]
I plan to do "Squash and merge" ... I guess it is fine ?

**Comment by pcanal** [comment]
If I remember correctly this would collate the commits log (i.e. ends up with many repeates)

**Comment by couet** [comment]
Yes ... It will do that. But I have no other suggestions. Moreover I guess we would like to keep Desislava commits history.

**Comment by Axel-Naumann** [comment]
We can combine some of the commits, we can update the author - there are many things we can do :-) I can show you tomorrow. Else e.g. Javier or Stephan might be able to show.

**Pull request merged**
