### PR TITLE
[RF] Several improvements to the RooFit build configuration

### PR DESCRIPTION
**Pull request by guitargeek**
Some improvements in the RooFit build configuration to avoid that information that is only necessary for RooFit at build time is leaking into the public user interface.

In particular, it is not necessary to define these `R__HAS_<*>` flags in the public ROOT config only to use them in the private `.cxx` sources. This should be avoided and instead be done with defines in the build configuration.

* Move stressRooFit and stressRooStats to `roofit` directory
* Remove `R__HAS_ROOFIT_MULTIPROCESS` from ROOT configuration
* No need to check `R__HAS_MATHMORE` in roofitmore sources
* Avoid need for `R__HAS_CUDA`

More detail in the commit descriptions.

### CODE REVIEW

**Comment by guitargeek** [comment]
Surprisingly, adding `./stressRooStats -b cpu -minim Minuit2` to the test matrix resulted in failures only on `mac12arm`.

I'm trying to replace the custom minimization code in the RooStats LikelihoodInterval with some more idiomatic RooFit code. Maybe it avoids the problem.

**Comment by guitargeek** [comment]
I removed the added `./stressRooStats -b cpu -minim Minuit2` that I attempted to introduce with this PR.

It seems that this test would hit some ununderstood Minuit2 Minos error that needs to be dealt with in a separate PR.

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you Jonas for these improvements in the configuration

**Comment by guitargeek** [comment]
Rebasing after merging this other PR:
* https://github.com/root-project/root/pull/13925

**Pull request merged**
