### PR TITLE
Added the possibility to specify a line width for marker symbols

### PR DESCRIPTION
**Pull request by Triple-S**
Hello,

this patch adds the possibility to specify a line width to be used when markers are drawn. Recently I stumbled upon this and searched for an already existing solution, but I could only find other people looking for something like this, so I decided to implement it.

Before I start to describe the changes, let me mention the most important point first: I only tested the feature under Linux, since I have neigther a ROOT installation under Windows nor a Mac. Since the feature also changes files associated with drawing under Windows and MacOS, I consider it absolutly mandatory to test the feature under those systems before merging this pull request.

Now back to the actual feature. Since an image says more than 1000 words here an image of the outcome using the implemented feature which is also part of the feature description in the class TAttMarker:
c

**The attribute fMarkerLineWidth**
The storing of the parameter is done by the attribute fMarkerLineWidth of the TAttMarker class. I checked all daughter classes of TAttMarker for the need of changes due to this addition. Furthermore, I added a line width dropdown field to the TAttMarkerEditor which works the same way as in the TAttLineEditor.

Obviosly the line width only makes sense for marker styles that consist of lines and not areas. To check whether the currently set marker style is influenced by the marker line width I added the function HasMarkerLineWidth to TAttMarker.

**Marker size and draw method**
Since the calculation of the size of the marker assumed ultimatly thin lines up to now, the bounding box of the marker would have increased when setting a larger marker line width. To counter that, I decreased the marker size by the amount it would have increased due to the line width. However, note that this only works with round line caps and round line joins, since for example with miter joins the bounding box becomes infinitly large for infinitly small angles.

This is also the reason why I decided to used round caps and round joins when drawing the marker lines in a TPad. However for the vector graphic export classes the line join method is set by gStyle->GetJoinLinePS(). Since there was no corresponding implementation for the line cap, I added it to TStyle. Furthermore, the line join method setting was ignored by the SVG export until now, so I decided to add it there as well.

**Further changes**
Another thing I noted is that the markers 3 and 5 (and 31) were looking different depending on whether they were drawn by a class based on TVirtualPadPainter or based on TVirtualPS. Furthermore the behaviour for marker styles 9-19 were different between the implementations. (You can see the differences when you compare the canvas created by `TMarker::DisplayMarkerTypes()` with the marker style example picture in the class reference of TAttMarker.)
I thought that the marker style definition used by classes based on TVirtualPadPainter seems better than the one by classes based on TVirtualPS. However, if you think that the definition of classes based on TVirtualPS is more correct, I can change this quickly but would then propose to also change definition in the TVirtualPadPainter classes since the markers should look the same everywhere.

If you have any further recommendations please let me know.
Thanks and all the best,
Simon Spies

### CODE REVIEW

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by Triple-S** [comment]
OK, I forgot to change the ROOT7 implementations.
The build on Mac seems to fail cause the expressions for line join and line cap method I found on the internet are invalid. I changed them, but unfortunatly cannot test it locally cause I dont own a Mac.
About the failing tests I assume that this is due to the additional attribute which slightly changes filesizes. What would be the best way to resolve this? I would assume that the values in roottest need to be updated.

**Comment by linev** [comment]
General comment - you have to preserve old functionality as much as possible.

In your particular case - when adding new argument to the constructor (like TAttMarker), you have to provide default value for it that existing user code still can be compiled. 

Also you redefines some virtual methods (adding extra arguments) - means if any user code relies on that API, it will be "silently" broken. Probably here one should not modify existing virtual methods, but add extra ones for new marker attributes

**Comment by Triple-S** [comment]
Thanks for the comment @linev 

I clearly see your point and I got to admit I was not thinking much about compatibility when I wrote this feature although this is a crucial point for a toolkit like ROOT.

About the default value for the constructor everything is totally fine.
About the redefined virtual functions, I am not 100% sure what is the best way to resolve the problem. Probably providing a default value for the new parameter like I did for TAttMarker::SaveMarkerAttributes will not be enough.
I was asking myself whether it is better to overload the virtual function with the additional parameter or to define a complete new function with a different name.

Maybe you can give me an advice on how to resolve this problem since am not fully familiar with the concept of virtual functions and the consequences of a particular implementation.

All the best,
Simon Spies

**Comment by linev** [comment]
> Maybe you can give me an advice on how to resolve this problem since am not fully familiar with the concept of virtual functions and the consequences of a particular implementation.

In my mind - one should introduce new methods to configure extra marker attributes.
In that case old API remains, only new is introduced.
But we should wait for @couet - that he is thinking about it

**Comment by Triple-S** [comment]
Could an admin please start another build? I would like to know whether at least the compile errors are fixed now.

**Comment by Triple-S** [comment]
I have another question: Several changes of this PR require an adjustment of the reference values of some tests. What is the correct way to get new reference values? Can I just run the test macros and take the results as new reference values or do they need to be calculated on a specific system with specific configurations?

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
> Can I just run the test macros and take the results as new reference values or do they need to be calculated on a specific system with specific configurations?

You should be able to run it on almost any system. If the results changed across systems, we would constantly see a lot of failures.

**Comment by Triple-S** [comment]
OK, it seems to me this project is getting out of control, since I was not aware of how much is connected to it. However, I still think the feature is something to keep in mind, because I think it would be a very nice and valueble addition for ROOT.
Furthermore, I think the implemenataion of TStyle::SetLineCapPS is something we should habe in ROOT, since I see no reason why we should have TStyle::SetLineJoinPS, but not TStyle::SetLineCapPS.
Maybe it would be better to divide this PR into serveral smaller ones that can be tested more easily.
What do you think about it?

**Comment by linev** [comment]
In my mind, best way to go - introduce new methods and do not touch old ones.

**Comment by couet** [comment]
Sorry for this late comment. I had some other urgent matters to deal with.
My general comment is that the line width is not part of of the marker attributes. Seems to me markers attributes should remain simple. Some markers are also filled polygon. Would you like to apply the fill style to them ? I guess not. I guess the best way to implement what you need is to define new marker types. We are not limited in number. If you want a star with bigger line width we can ad a new marker type. Any way the useful line width is limited and surely smaller than 10.

**Comment by Triple-S** [comment]
Thanks for you reply @couet, I see your point that it's not ideal to define an attribute that is only used by approximatly half of all available styles.

The main reason I wanted to have this feature is that I realized that lines with a width of 1 can become badly visible in presentations or on posters which is why I prefer to use line width 2 as default everywhere.

For the implementation via the marker styles as you propose I see basically 2 ways to implement this:
1. At the moment we have marker styles up to 49. One could just start to redefine all existing marker styles where a linewidth makes sense from 50 upwards with a linewidth of 1, 2, 3 ...
However, I think this might become confusing if further styles are added in the future, because then there will be no logic behind the numbers and the corresponding markers, although there is not much logic behind the style numbers right now too.
2. One could define it in a way that adding 100 to the marker style corresponds to an increase of the linewidth of 1. As an example the regular + marker with linewidth 1 would be 2, with linewidth 2 it would be 102, with linewidth 3 202 ...
I know this would be rather equal to defining a standalone linewidth attribute, but it would allow us to add up to 50 additional marker styles in the future without breaking the logic and I doubt we will have more than 100 different marker styles one day.

Since you are the responsible coordinator for the graphics part of ROOT, I think this decision should be up to you.

----------------------------------------------------------------------------------------------------

Could you also comment on the differences in the drawing of markers 3, 5 (and 31) between classes inheriting from TVirtualX and classes inheriting from TVirtualPS? The following picture shows the difference for marker style 3:
temp
I think the different implementations should be unified so that markers look the same everywhere. From my point of view the implementation of TVirtualX classes seems better, but I would like to have your opinion on this.

**Comment by couet** [comment]
@Triple-S 
 I see your points about posters. One simple way to bypass this issue is or course to use filled markers with seems to me are better any way. But I can understand you need hollow markers. As you may need only a few line widths may be 2, 3 and 4 simply adding new makers makes sense. Given the usually small size of markers, having any possible line widths does not make sense (you will  rapidly get big "blobs" not understandable). So I am not sure a coding convention is necessary.

The different look of the maker 3 should be fixed.

**Comment by Triple-S** [comment]
Alright, then I know how to go on.
I will close this PR here and split it into 3 PRs each dedicated to one feature:
1. Unify drawing of markers 3, 5 (and 31)
2. Implementation of TStyle::SetLineCapPS
3. Additional markers with thicker lines

**Pull request closed without merging**
