### PR TITLE
Avoid Snapshot errors when updating directories

### PR DESCRIPTION
**Pull request by goi42**
If one tries to update a directory inside an existing file, Snapshot complains:
`Error in <TFile::mkdir>: An object with name hi exists already`

This fixes the problem by using the `returnExistingDirectory` option in `mkdir`.

First mentioned in the forum [here](https://root-forum.cern.ch/t/snapshot-complains-when-updating-existing-directory/37935). Similar to [PR4649](https://github.com/root-project/root/pull/4649).

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by goi42** [comment]
@bluehood [PR4649](https://github.com/root-project/root/pull/4649) already incorporates similar changes for `SnapshotHelperMT`. In that case, it calls `fOutputFiles[slot]->mkdir(fDirName.c_str(), "", true)` regardless of the File Open option since each thread can write to the same directory; thus, no additional adjustment is needed.

**Comment by bluehood** [comment]
Uhm so half of this fix is in the other PR? :sweat_smile:

**Comment by goi42** [comment]
@bluehood no, they address different problems. PR4649 is already merged and prevents errors being raised due to multiple threads writing to the same directory. This PR addresses the case of writing to an existing directory using the "update" option; no fix is required for MT.

**Comment by goi42** [comment]
@bluehood It probably would have made sense if I had fixed this in PR4649, but I was trying to solve a different problem in that case and didn't notice/think about this one 🤷🏼‍♂️

**Comment by bluehood** [comment]
@goi42 ah #4649 was merged some time ago, I see! I got it confused with #4965, sorry!

So this can go in, but I would like to have a test for the fixed usecase. I don't know how to check that `TFile` printed an Error, do you by chance? I'll ask around :D

**Comment by bluehood** [comment]
Or maybe the Error caused some visible difference in the output file?

**Comment by goi42** [comment]
@bluehood Ah, okay, no problem. I'm currently adding a test to check that both trees get written, but no, I don't know how to check printed errors. Is a test necessary for such a case? A quick check indicates that this PR only affects the printed error statement, not the saved output.

**Pull request merged**
