### PR TITLE
Add minimal example for TMVA binary Classification

### PR DESCRIPTION
**Pull request by ashlaban**

### CODE REVIEW

**Comment by ashlaban** [comment]
Sound like a good idea. I’ll have a look at it.

Cheers,
  Kim

**Comment by ashlaban** [comment]
Updated the file as per your suggestion Danilo, removing the doxygen style of comments. Left the formulation mostly intact, just a few small improvements.

**Comment by ashlaban** [comment]
Any update on reviewing this?

**Comment by etejedor** [comment]
@dpiparo anything else to add? Can we merge?

**Pull request merged**
