### PR TITLE
Add a class to perform compensate summation

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by karies** [comment]
Missing `#include <vector>` in `TMath.h`. And do we really need that in `TMath.h`? :-/ That file gets included pretty much everywhere...

**Comment by xvallspl** [comment]
Hi Axel,

I understood wrong. Fixing it.

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by martinmine** [comment]
@phsft-bot build!

**Pull request merged**
