### PR TITLE
Bulk I/O - v3 revision PR

### PR DESCRIPTION
**Pull request by zzxuanyuan**
@pcanal @bbockelm 

This PR is about Bulk API after revision of previous PR #2519

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by zzxuanyuan** [comment]
Hi, @pcanal @bbockelm 

Could you look at these two errors https://travis-ci.org/root-project/root/jobs/513121824.

The first one says TTreeReaderFast calls Error (virtual function) in its constructor, which is what TTreeReader exactly did.

The second one claims "SillyStruct" class does not have a fUniqueID. What should be the correct way to compile and create SillyStruct in order to make it generate fUniqueID automatically?

**Comment by pcanal** [comment]
> The second one claims "SillyStruct" class does not have a fUniqueID. What should be the correct way to compile and create SillyStruct in order to make it generate fUniqueID automatically?

The error is spurrious.  Indeed the code pattern is unusual and **intentionally** look at (sometime) uninitialized memory).  You can ignore this error.

> The first one says TTreeReaderFast calls Error (virtual function) in its constructor, which is what TTreeReader exactly did.

This is also cumbersome but valid (because we don't overload Error here).  You can also replace it with
```
   ::Error("TTreeReaderFast::TTreeReaderFast", "TTree is NULL!");
```

**Comment by zzxuanyuan** [comment]
@pcanal I changed the Error functions in constructors to ::Error and ignore the second error for now.

**Comment by pcanal** [comment]
I updated the branch to simplify a bit the history.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The friend.make problem is likely due to a missing dependency in ctest (root-tree-friend-make depends and root-io-event)
The windows failure is due to missing M_PI declaration.

**Pull request merged**
