### PR TITLE
[cmake] Re-add python stl_set tests

### PR DESCRIPTION
**Pull request by dpiparo**
This PR adds a test for #14710

### CODE REVIEW

**Review by bellenot — APPROVED** [review]
Thanks Danilo!

**Comment by dpiparo** [comment]
I hope we'll see the same behaviour as in our private tests 🤞

**Comment by bellenot** [comment]
> I hope we'll see the same behaviour as in our private tests 🤞

Like this? 😉 
```
C:\root-dev\build\x64\release>ctest -C Release -R pyroot-pyz-stl-set
Test project C:/root-dev/build/x64/release
    Start 7: pyunittests-bindings-pyroot-pythonizations-pyroot-pyz-stl-set
1/1 Test #7: pyunittests-bindings-pyroot-pythonizations-pyroot-pyz-stl-set ...   Passed    1.44 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.91 sec
```

**Comment by dpiparo** [comment]
> > I hope we'll see the same behaviour as in our private tests 🤞
> 
> Like this? 😉
> 
> ```
> C:\root-dev\build\x64\release>ctest -C Release -R pyroot-pyz-stl-set
> Test project C:/root-dev/build/x64/release
>     Start 7: pyunittests-bindings-pyroot-pythonizations-pyroot-pyz-stl-set
> 1/1 Test #7: pyunittests-bindings-pyroot-pythonizations-pyroot-pyz-stl-set ...   Passed    1.44 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Total Test time (real) =   1.91 sec
> ```

Yes, but on both flavours ;-)

**Pull request merged**
