### PR TITLE
Fix hard error when checking if non-common_range is printable

### PR DESCRIPTION
**Pull request by lackhole**
# This Pull request:

## Changes or fixes:
Fix hard error when checking if non-[common_range](https://en.cppreference.com/w/cpp/ranges/common_range) is printable. I.e., [std::ranges::enumerate_view](https://en.cppreference.com/w/cpp/ranges/enumerate_view).
Although root does not support C++20 currently, a range that returns different type for `begin()` and `end()` is still legal in other C++ versions.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

Fixes https://github.com/root-project/root/issues/14966

### CODE REVIEW

**Comment by dpiparo** [comment]
Thanks for this code.
Could you also provide a test that highlights the problem being solved?

**Comment by vepadulano** [comment]
> Although root does not support C++20 currently

Sorry for the passing by question, but how did you come to this conclusion? ROOT does support C++20 since a while. Maybe you are not encountering a specific feature for your use case that makes things confusing?

**Comment by vgvassilev** [comment]
This seems reasonable to me. Is there any chance on adding a test in `interpreter/cling/test`?

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Review by ferdymercury — APPROVED** [review]

**Review by dpiparo — APPROVED** [review]
LGTM if the tests, which I restarted, succeed.

**Pull request merged**
