### PR TITLE
[cxxmodules] Also load TreePlayer to fix TDataFrame tests.

### PR DESCRIPTION
**Pull request by Teemperor**
Depends on: #1317, adds only one other commit:

    It seems automatically loading TreePlayer when TDataFrame is used
    without the appropriate include never worked. This was previously
    fixed by just adding TreePlayer (which contains TDF) to the PCH.
    
    As always, let's recreate this hack with modules to make restore
    the old behavior with modules turned on.

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build with flags -Druntime_cxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=On

**Comment by Teemperor** [comment]
We first need to fix the dependencies that TreePlayer is built before we try to load it.

**Comment by vgvassilev** [comment]
That would require building quite a lot of root...

**Pull request closed without merging**
