### PR TITLE
[RF] Make extended fit default of RooAbsPdf::fitChi2() same as in fitTo

### PR DESCRIPTION
**Pull request by guitargeek**
It is confusing to the users that the chi2 fit is by default not extended, even if the pdf is extended. Because this is what happens in normal likelihood fits.

This commit makes that behavior consistent and explains it in the release notes.

Also, a new error message is added for the case you forcing a non extended fit on a pdf that must be extended, because this is guaranteed to give wrong results.

This change addresses the confusion on the forum:
https://root-forum.cern.ch/t/failing-chi2-fit/56309

### CODE REVIEW

**Comment by AntoniMarcinek** [comment]
I looked into doxygen for the chi2FitTo() 
https://root.cern/doc/master/classRooAbsPdf.html#a77be869c84f102f1fce246c6f01b5b7d
and it doesn't mention `Extended()` at all. So I think this should be added with proper explanation of the behaviour.

Furthermore doxygen for fitTo()
https://root.cern/doc/master/classRooAbsPdf.html#a52c4a5926a161bcb72eab46890b0590e
specifies that `Extended()` is off by default, while it should rather say that it is on if pdf is extended and off if it is not.

**Comment by guitargeek** [comment]
> I looked into doxygen for the chi2FitTo() https://root.cern/doc/master/classRooAbsPdf.html#a77be869c84f102f1fce246c6f01b5b7d and it doesn't mention `Extended()` at all. So I think this should be added with proper explanation of the behaviour.
> 
> Furthermore doxygen for fitTo() https://root.cern/doc/master/classRooAbsPdf.html#a52c4a5926a161bcb72eab46890b0590e specifies that `Extended()` is off by default, while it should rather say that it is on if pdf is extended and off if it is not.

That's a good point! In the final commit of this PR, I improved the documentation of the `Extended()` command argument.

I have also added three more commits:
* some refactor to avoid code duplication in RooAbsReal and RooAbsPdf
* don't recommend the use of `RooChi2Var` directly in RooPlot documentation
* a commit that just fixes typos

**Comment by AntoniMarcinek** [comment]
Looking at the docs of  `createChi2` I see that it points to `RooChi2Var` ctor. Is it ok given that you are now discouraging usage of `RooChi2Var`? Furthermore, in https://root-forum.cern.ch/t/failing-chi2-fit/56309/8 you say that `createChi2` supports more options.

**Comment by AntoniMarcinek** [comment]
Oh yes, this sounds very reasonable!

**Review by lmoneta — APPROVED** [review]
LGTM

**Pull request merged**
