### PR TITLE
Backport: Dynamic Path: ROOT_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
This is a backport of #7031 to the 6-24-00-patches branch.

I cherry-picked two of the three commits.
I left the test suite out, as it finally should go to roottest.git, as far as I understood it.

This is basically to get the thing started.

cc:  @pcanal, @dennisklein

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by ChristianTackeGSI** [comment]
@bellenot can you help with the windows build error?

**Comment by pcanal** [comment]
The windows error is unrelated.  It seems that a build area used for the older Cling version (using llvm v5) is being reused.

**Comment by pcanal** [comment]
The macos failure is an infrasture issue:
```
Plugin dlopen(libXrdSecgsi-4.so, 256): image not found sec.protocol libXrdSecgsi-4.so
```

**Pull request merged**
