### PR TITLE
Fix lazy template loading for macOS with C++17

### PR DESCRIPTION
**Pull request by hahnjo**
Fixes https://github.com/root-project/root/issues/12003

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
👏

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11/cxx17, mac12/cxx17, mac13/cxx17, mac11arm/cxx17, mac12arm/cxx17, mac13arm/cxx17

**Comment by hahnjo** [comment]
Oh come on, do I now also need to solve https://github.com/root-project/root/issues/10291 :cry:

**Comment by hahnjo** [comment]
<details>
<summary>Here's a stack trace from a full Debug build</summary>

```
#0  0x00007ffff5af6acf in raise () from /lib64/libc.so.6
#1  0x00007ffff5ac9ea5 in abort () from /lib64/libc.so.6
#2  0x00007ffff5ac9d79 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ffff5aef426 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff242b51a in clang::FunctionDecl::getODRHash (this=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/Decl.cpp:4120
#5  0x00007ffff2716558 in (anonymous namespace)::ODRDeclVisitor::VisitFunctionDecl (this=0x7fffffff37e0, D=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/ODRHash.cpp:340
#6  0x00007ffff271732d in clang::declvisitor::Base<llvm::make_const_ptr, (anonymous namespace)::ODRDeclVisitor, void>::VisitCXXMethodDecl (this=0x7fffffff37e0, D=0x20dce40) at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:431
#7  0x00007ffff27165cd in (anonymous namespace)::ODRDeclVisitor::VisitCXXMethodDecl (this=0x7fffffff37e0, D=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/ODRHash.cpp:348
#8  0x00007ffff271563d in clang::declvisitor::Base<llvm::make_const_ptr, (anonymous namespace)::ODRDeclVisitor, void>::Visit (this=0x7fffffff37e0, D=0x20dce40) at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:431
#9  0x00007ffff27141b0 in (anonymous namespace)::ODRDeclVisitor::Visit (this=0x7fffffff37e0, D=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/ODRHash.cpp:281
#10 0x00007ffff2713eaa in clang::ODRHash::AddSubDecl (this=0x7fffffff6b58, D=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/ODRHash.cpp:471
#11 0x00007fffeeb7c733 in clang::ASTReader::diagnoseOdrViolations()::$_37::operator()(clang::Decl const*) const (this=0x7fffffff6b40, D=0x20dce40) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:9616
#12 0x00007fffeeb79a26 in clang::ASTReader::diagnoseOdrViolations()::$_17::operator()(llvm::SmallVector<std::pair<clang::Decl*, unsigned int>, 4u>&, clang::RecordDecl*, clang::DeclContext const*) const (this=0x7fffffff6aa8, Hashes=..., Record=0x1bde148, DC=0x1bde188) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:9981
#13 0x00007fffeeb717e6 in clang::ASTReader::diagnoseOdrViolations (this=0xea4670) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:10404
#14 0x00007fffeeb7d033 in clang::ASTReader::FinishedDeserializing (this=0xea4670) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:11674
#15 0x00007fffeeb8ab2c in clang::ExternalASTSource::Deserializing::~Deserializing (this=0x7fffffff7930) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/AST/ExternalASTSource.h:86
#16 0x00007fffeec4347b in clang::ASTReader::ReadDeclRecord (this=0xea4670, ID=402293) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReaderDecl.cpp:4155
#17 0x00007fffeeb60800 in clang::ASTReader::GetDecl (this=0xea4670, ID=402293) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:7531
#18 0x00007fffeeb665bb in clang::ASTReader::GetExternalDecl (this=0xea4670, ID=402293) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp:7240
#19 0x00007fffedb6c480 in cling::ExternalASTSourceWrapper::GetExternalDecl (this=0xe70300, ID=402293) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp:115
#20 0x00007fffeed8d884 in clang::MultiplexExternalSemaSource::GetExternalDecl (this=0x7370d0, ID=402293) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/MultiplexExternalSemaSource.cpp:45
#21 0x00007ffff2481278 in clang::RedeclarableTemplateDecl::loadLazySpecializationImpl (this=0x1c08370, LazySpecInfo=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:310
#22 0x00007ffff2481364 in clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl (this=0x1c08370, Args=..., TPL=0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:323
#23 0x00007ffff2486ad6 in clang::RedeclarableTemplateDecl::findSpecializationImpl<clang::FunctionTemplateSpecializationInfo, llvm::ArrayRef<clang::TemplateArgument>&> (this=0x1c08370, Specs=..., InsertPos=@0x7fffffff8488: 0x0, ProfileArgs=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:335
#24 0x00007ffff2481792 in clang::FunctionTemplateDecl::findSpecialization (this=0x1c08370, Args=..., InsertPos=@0x7fffffff8488: 0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/DeclTemplate.cpp:416
#25 0x00007fffefe57c77 in clang::TemplateDeclInstantiator::VisitFunctionDecl (this=0x7fffffff86b0, D=0x1c08448, TemplateParams=0x0, FunctionRewriteKind=clang::TemplateDeclInstantiator::RewriteKind::None) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:1947
#26 0x00007fffefe60113 in clang::TemplateDeclInstantiator::VisitFunctionDecl (this=0x7fffffff86b0, D=0x1c08448) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:3580
#27 0x00007fffefe3eb49 in clang::declvisitor::Base<std::add_pointer, clang::TemplateDeclInstantiator, clang::Decl*>::Visit (this=0x7fffffff86b0, D=0x1c08448) at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:421
#28 0x00007fffefeaf9d4 in clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0::operator()() const (this=0x7fffffff8670) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:3862
#29 0x00007fffefeaf9a5 in llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) (callable=140737488324208) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:177
#30 0x00007fffeea46a79 in llvm::function_ref<void ()>::operator()() const (this=0x7fffffff85d0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:200
#31 0x00007fffeedfc48d in clang::runWithSufficientStackSpace(llvm::function_ref<void ()>, llvm::function_ref<void ()>) (Diag=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/Basic/Stack.h:46
#32 0x00007fffeedebc10 in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (this=0x733920, Loc=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/Sema.cpp:482
#33 0x00007fffefe61537 in clang::Sema::SubstDecl (this=0x733920, D=0x1c08448, Owner=0x1bc5100, TemplateArgs=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:3861
#34 0x00007fffefcfc825 in clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (this=0x733920, FunctionTemplate=0x1c08370, 
    Deduced=..., NumExplicitlySpecified=0, Specialization=@0x7fffffff9470: 0x0, Info=..., OriginalCallArgs=0x0, PartialOverloading=false, CheckNonDependent=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateDeduction.cpp:3611
#35 0x00007fffefdd64f4 in clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, clang::QualType, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool)::$_6::operator()() const (this=0x7fffffff8e48) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateDeduction.cpp:4362
#36 0x00007fffefdd6445 in llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, clang::QualType, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool)::$_6>(long) (callable=140737488326216) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:177
#37 0x00007fffeea46a79 in llvm::function_ref<void ()>::operator()() const (this=0x7fffffff8d00) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:200
#38 0x00007fffeedfc48d in clang::runWithSufficientStackSpace(llvm::function_ref<void ()>, llvm::function_ref<void ()>) (Diag=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/Basic/Stack.h:46
#39 0x00007fffeedebc10 in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (this=0x733920, Loc=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/Sema.cpp:482
#40 0x00007fffefcff998 in clang::Sema::DeduceTemplateArguments (this=0x733920, FunctionTemplate=0x1c08370, ExplicitTemplateArgs=0x7fffffff9690, ArgFunctionType=..., Specialization=@0x7fffffff9470: 0x0, Info=..., IsAddressOfFunction=false) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateDeduction.cpp:4361
#41 0x00007fffefbd7fca in clang::Sema::CheckFunctionTemplateSpecialization (this=0x733920, FD=0x23541f0, ExplicitTemplateArgs=0x7fffffffa960, Previous=..., QualifiedFriend=false) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplate.cpp:9086
#42 0x00007fffefe58e81 in clang::TemplateDeclInstantiator::VisitFunctionDecl (this=0x7fffffffb428, D=0x1c081b8, TemplateParams=0x0, FunctionRewriteKind=clang::TemplateDeclInstantiator::RewriteKind::None) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:2166
#43 0x00007fffefe60113 in clang::TemplateDeclInstantiator::VisitFunctionDecl (this=0x7fffffffb428, D=0x1c081b8) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:3580
#44 0x00007fffefe3eb49 in clang::declvisitor::Base<std::add_pointer, clang::TemplateDeclInstantiator, clang::Decl*>::Visit (this=0x7fffffffb428, D=0x1c081b8) at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:421
#45 0x00007fffefe526f6 in clang::TemplateDeclInstantiator::VisitFriendDecl (this=0x7fffffffb428, D=0x1c08118) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:1323
#46 0x00007fffefe3e781 in clang::declvisitor::Base<std::add_pointer, clang::TemplateDeclInstantiator, clang::Decl*>::Visit (this=0x7fffffffb428, D=0x1c08118) at interpreter/llvm/src/tools/clang/include/clang/AST/DeclNodes.inc:71
#47 0x00007fffefdee4e5 in clang::Sema::InstantiateClass (this=0x733920, PointOfInstantiation=..., Instantiation=0x1bde148, Pattern=0x1bc5e60, TemplateArgs=..., TSK=clang::TSK_ImplicitInstantiation, Complain=true) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2735
#48 0x00007fffefdefa71 in clang::Sema::InstantiateClassTemplateSpecialization (this=0x733920, PointOfInstantiation=..., ClassTemplateSpec=0x1bde148, TSK=clang::TSK_ImplicitInstantiation, Complain=true) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:3219
#49 0x00007fffeff67178 in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3::operator()() const (this=0x7fffffffbab0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaType.cpp:8673
#50 0x00007fffeff67125 in llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) (callable=140737488337584) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:177
#51 0x00007fffeea46a79 in llvm::function_ref<void ()>::operator()() const (this=0x7fffffffb8a0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/ADT/STLExtras.h:200
#52 0x00007fffeedfc48d in clang::runWithSufficientStackSpace(llvm::function_ref<void ()>, llvm::function_ref<void ()>) (Diag=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/Basic/Stack.h:46
#53 0x00007fffeedebc10 in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (this=0x733920, Loc=..., Fn=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/Sema.cpp:482
#54 0x00007fffeff4c3fa in clang::Sema::RequireCompleteTypeImpl (this=0x733920, Loc=..., T=..., Kind=clang::Sema::CompleteTypeKind::AcceptSizeless, Diagnoser=0x7fffffffbcd0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaType.cpp:8672
#55 0x00007fffeff4bcf3 in clang::Sema::RequireCompleteType (this=0x733920, Loc=..., T=..., Kind=clang::Sema::CompleteTypeKind::AcceptSizeless, Diagnoser=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaType.cpp:8418
#56 0x00007fffeeecf69e in clang::Sema::RequireCompleteType (this=0x733920, Loc=..., T=..., Diagnoser=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/Sema/Sema.h:2332
#57 0x00007fffeeece244 in clang::Sema::RequireCompleteType<clang::SourceRange> (this=0x733920, Loc=..., T=..., DiagID=3138, Args=...) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/Sema/Sema.h:2342
#58 0x00007fffeeec9c59 in clang::Sema::RequireCompleteDeclContext (this=0x733920, SS=..., DC=@0x7fffffffc1b8: 0x1bde188) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/Sema/SemaCXXScopeSpec.cpp:235
#59 0x00007fffedb730e6 in cling::LookupHelper::findScope (this=0x68d8a0, className=..., diagOnOff=cling::LookupHelper::NoDiagnostics, resultType=0x7fffffffc600, instantiateTemplate=true) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/LookupHelper.cpp:705
#60 0x00007fffed80efde in TClingClassInfo::TClingClassInfo (this=0x1babf10, interp=0x6c8990, name=0x1bc1dd0 "ROOT::Experimental::RHist<1,double,ROOT::Experimental::RHistStatContent,ROOT::Experimental::RHistStatUncertainty>", intantiateTemplate=true) at /home/jhahnfel/ROOT/src/core/metacling/src/TClingClassInfo.cxx:88
#61 0x00007fffed60498c in TCling::SetClassInfo (this=0x6c7f40, cl=0x1e612e0, reload=false) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:4034
#62 0x00007ffff6c3a9da in TClass::LoadClassInfo (this=0x1e612e0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:5828
#63 0x00007ffff6c392fc in TClass::GetListOfBases (this=0x1e612e0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:3641
#64 0x00007ffff6c3cb46 in TClass::GetBaseClass (this=0x1e612e0, cl=0x160c7d0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:2681
#65 0x00007ffff6c43eb2 in TClass::InheritsFrom (this=0x1e612e0, cl=0x160c7d0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:4894
#66 0x00007ffff6c47ba7 in TClass::Property (this=0x1e612e0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:6100
#67 0x00007ffff6c46dc7 in TClass::IsForeign (this=0x1e612e0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:5938
#68 0x00007ffff6c46e68 in TClass::PostLoadCheck (this=0x1e612e0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:5955
#69 0x00007ffff6c3e928 in TClass::GetClass (typeinfo=..., load=true, hint_pair_offset=0, hint_pair_size=0) at /home/jhahnfel/ROOT/src/core/meta/src/TClass.cxx:3284
#70 0x000000000058b9d1 in ROOT::Internal::TClassGetClassHelper<ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty> >::GetClass (load=true, silent=false) at /home/jhahnfel/ROOT/src/core/meta/inc/TClass.h:628
#71 0x000000000058b97f in ROOT::Internal::GetClassHelper<ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty> > (load=true, silent=false) at /home/jhahnfel/ROOT/src/core/meta/inc/TClass.h:644
#72 0x000000000058b93f in TClass::GetClass<ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty> > (load=true, silent=false) at /home/jhahnfel/ROOT/src/core/meta/inc/TClass.h:654
#73 0x000000000058a8e8 in TDirectory::WriteObject<ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty> > (this=0x7fffffffcfc8, obj=0x7fffffffd398, name=0x41b846 "h1", option=0x41f9ae "", bufsize=0) at /home/jhahnfel/ROOT/src/core/base/inc/TDirectory.h:284
#74 0x00000000005878fc in IOTest_OneD_Test::TestBody (this=0x69e1f0) at /home/jhahnfel/ROOT/src/hist/histdrawv7/test/io.cxx:20
#75 0x00000000005dd396 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#76 0x00000000005c2438 in testing::Test::Run() ()
#77 0x00000000005c3881 in testing::TestInfo::Run() ()
#78 0x00000000005c429f in testing::TestSuite::Run() ()
#79 0x00000000005d4e1c in testing::internal::UnitTestImpl::RunAllTests() ()
#80 0x00000000005de156 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#81 0x00000000005d468c in testing::UnitTest::Run() ()
#82 0x00000000005e8dc7 in main ()
```
</details>

This is my current understanding of what is happening:
1. The test wants to write a `RH1D` into a `TMemFile` (frame 74) so Cling has to load the `TClassInfo` (frame 60) and calls `RequireCompleteDeclContext` (frame 58).
2. This ends up in `RequireCompleteType` looking for `RHist<1, double, RHistStatContent, RHistStatUncertainty>` (frames 56-59).
3. Because it's not yet complete, Clang starts `InstantiateClassTemplateSpecialization` (frame 48), which visits the `friend` declaration for `HistFromImpl<1, double, RHistStatContent, RHistStatUncertainty>` (around frame 45).
4. Clang does some magic for deducing the template arguments and eventually decides to ask `FunctionTemplateDecl::findSpecialization` (frame 24), that in turn begins to `loadLazySpecializationsImpl` (frame 22). *Note* that this is the place where this PR "fixes" lazy loading / deserialization!
5. The `ASTReader` kicks in with `ReadDeclRecord` (frame 16).
6. After deserlization, the `ASTReader` performs the `diagnoseOdrViolations` (frame 13), which eventually trys to `getODRHash` of `RHist::GetNDim`.

Do I interpret this correctly that we are instantiating `RHist` and then later on find it in a module while deserializing `HistFromImpl`? How can this be? @vgvassilev

**Comment by vgvassilev** [comment]
That looks correct diagnosis. Can we extend the lifetime of `clang::ExternalASTSource::Deserializing::~Deserializing` eg register a deserialization upon say `findScope` and then delay the odr hash checks after things were fully deserialized?

**Comment by hahnjo** [comment]
> That looks correct diagnosis. Can we extend the lifetime of `clang::ExternalASTSource::Deserializing::~Deserializing` eg register a deserialization upon say `findScope` and then delay the odr hash checks after things were fully deserialized?

Very creative idea :sweat_smile: what we can do is create our own `Deserializing` RAII in `findScope` because `ASTReader::FinishedDeserializing` will only do ODR violation checking on the last matching call. However, this also skips a number of other actions. As a result, I end up with an assertion for a cast of `FunctionDecl` - probably because some internal state is not correctly updated.

In general, this approach sounds like treating the symptoms instead of the underlying cause, no? If I look at the backtrace for https://github.com/root-project/root/issues/10291, `findScope` is not involved there... (but a `friend` decl is :thinking:)

**Comment by vgvassilev** [comment]
Yes, it is treating the symptoms but I think that’s what I can think of at the moment.

**Comment by vgvassilev** [comment]
> Some further debugging (but really just dumping notes from some experiments):
> 
>     * The problem of `histhistdrawv7testUnit` can be simplified, in some approximation, to:
> 
> 
> ```
> root [0] TClass::GetClass("ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty>")
> root.exe: /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/Decl.cpp:4120: unsigned int clang::FunctionDecl::getODRHash() const: Assertion `hasODRHash()' failed.
> ```
> 
>     * Even simpler, just trying to create an object of that template instantiation fails:
> 
> 
> ```
> root [0] ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty> h;
> root.exe: /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/lib/AST/Decl.cpp:4120: unsigned int clang::FunctionDecl::getODRHash() const: Assertion `hasODRHash()' failed.
> ```
> 
>     * Funnily enough, the `using RH1D = RHist<1, double, RHistStatContent, RHistStatUncertainty>` works just fine; same if I remove the second `STAT` template and only leave `RHistStatContent`.

I've been stumbling upon these before: this is not simple as it has some template parameter pack expansion as part of the class inheritance chain...

**Comment by hahnjo** [comment]
Only a rebase, checking that the failure in `gtest-hist-histdrawv7-test-histhistdrawv7testUnit` is still there for all platforms. Also there seems to be a new failure in `roottest-root-meta-tuple-exec_configtype_unload-auto`, let's see how many platforms that affects...

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11/cxx17, mac11arm/cxx17, mac12/cxx17, mac12arm/cxx17, mac13/cxx17, mac13arm/cxx17

**Comment by hahnjo** [comment]
The failure of `roottest_root_meta_tuple_exec_configtype_unload_auto` is an interesting one: It is a deserialization triggered by the `DeclUnloader`, which in turn makes the `DeclCollector` (rightfully) complain about the "missing transaction during deserialization". The reason for the deserialization is that `DeclUnloader` calls `spec_begin` requiring to load all specializations. I'm more and more eying to completely revert the lazy loading, as proposed in https://github.com/root-project/root/pull/12238 so that a situation like that can never happen...

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/cxx17

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11/cxx17, mac11arm/cxx17, mac12/cxx17, mac12arm/cxx17, mac13/cxx17, mac13arm/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by hahnjo** [comment]
https://github.com/root-project/root/pull/13046 fixed https://github.com/root-project/root/issues/12003 so I'm closing this for now. I'm not done yet with the topic since the application of D41416 is still wrong, but I first want to land https://github.com/root-project/root/pull/13049 and then re-evaluate.

**Pull request closed without merging**
