### PR TITLE
Add diagnostic counts, suuuper nice for tests!

### PR DESCRIPTION
**Pull request by Axel-Naumann**
"And make sure we didn't see any errors or warnings."

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @Axel-Naumann , how does this class behave in a MT environment?

**Comment by Axel-Naumann** [comment]
As well as std::cerr...

I plan to replace the underlying stream by the upcoming buffered, thread-safe iostream. But I can definitely make the counts atomic already before! Thanks for pointing that out!

**Comment by dpiparo** [comment]
it depends on the timescales/cost of the change, right?

**Comment by pcanal** [comment]
> As well as std::cerr...

Well it does not have to ... 

On a side note, this logger needs (before any experiment can use v7) to have a way for the user to customize/redirect the output.

**Pull request merged**
