### PR TITLE
make DrawClone method the right way on tutorial

### PR DESCRIPTION
**Pull request by cxwx**
on fitsio tutorial

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@couet why is this needed - isn't `DrawClone` supposed to draw on the currently selected pad, and doesn't `cd` select a pad?

**Comment by couet** [comment]
DrawClone draws in in the SelectedPad see https://root.cern/doc/master/classTObject.html#a7cd0f76ae1791c469f9472a9d4c8d6f9
It was initially meant to be used interactively to draw an object from a pad to the selected one.
The question is more: Why do we need DrawClone in these examples (a simple Draw should be fine) ? I do not have FITS installed right now. I will need to make a new ROOT install with it to try.

**Comment by cxwx** [comment]
> DrawClone draws in in the SelectedPad see https://root.cern/doc/master/classTObject.html#a7cd0f76ae1791c469f9472a9d4c8d6f9
> It was initially meant to be used interactively to draw an object from a pad to the selected one.
> The question is more: Why do we need DrawClone in these examples (a simple Draw should be fine) ? I do not have FITS installed right now. I will need to make a new ROOT install with it to try.

The problem is described at link

**Comment by couet** [comment]
the link you posted is broken

**Comment by cxwx** [comment]
> the link you posted is broken

sorry, I rewrite the links

**Comment by couet** [comment]
Yes that's what is said in the DrawClone documentation. But what about using simply Draw instead of DrawClone in these examples ?

**Comment by cxwx** [comment]
> Yes that's what is said in the DrawClone documentation. But what about using simply Draw instead of DrawClone in these examples ?
In fact, the older version is using simple Draw without std::unique_ptr
the latest version is using std::unique_ptr instead of simple pointer, this would deconstruct at the end of program. so DrawClone must be used

**Comment by cxwx** [comment]
> What about DrawCopy instead of DrawClone (keeping the simple cd) ?

DrawCopy could only used with TH1::
The TImage and TGraph do not have member function of DrawCopy

**Comment by couet** [comment]
One last think to try might be:
```  
img->Clone() ; img->Draw()
```

**Comment by cxwx** [comment]
> One last think to try might be:
> 
> ```
> img->Clone() ; img->Draw()
> ```

```
TImage * img2 = (TImage *)im->Clone("test2");
img2->Draw();
```
should be OK, but it create another TImage Object.
Do you think it's better?

**Comment by couet** [comment]
DrawClone also create a new object object see line 225 [here](https://root.cern/doc/master/TObject_8cxx_source.html#l00219) . The problem with DrawClone is that it will go in the SelectedPad, not in the Pad define by cd()... They may coincide sometime but not always. So, I think it is better to make it clear a Clone is needed to avoir deletion. Then this object is drawn ... but the primary thing is to avoid deletion.

**Comment by cxwx** [comment]
> So, I think it is better to make it clear a Clone is needed to avoir deletion. Then this object is drawn ... but the primary thing is to avoid deletion.

OK, then I think, the std::unique_ptr should not be used at least in this tutorial, I would close this pr and try another one

**Comment by couet** [comment]
ok

**Pull request closed without merging**
