### PR TITLE
Size types should use %z

### PR DESCRIPTION
**Pull request by ellert**

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by linev** [comment]
@bellenot Does `%z` qualifier works on Windows?

**Comment by bellenot** [comment]
> @bellenot Does `%z` qualifier works on Windows?

@linev I don't think so. What type is it supposed to be?

**Comment by bellenot** [comment]
> @bellenot Does `%z` qualifier works on Windows?

Apparently yes, according to [this page](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2015#size-prefixes-for-printf-and-wprintf-format-type-specifiers)

**Comment by eguiraud** [comment]
Look good to me, thanks a lot @ellert !

**Pull request merged**
