### PR TITLE
[clad] Fix corrupt patch file (missing space in context).

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Fixes Windows patch error.

### CODE REVIEW

**Review by bellenot — APPROVED** [review]
Thanks Axel! (weirdly enough I don't see this issue on any of my build machines...)

**Comment by grimmmyshini** [comment]
Thanks for working on this! I only now realise how sensitive patch files are to these errors. Thanks again!

**Comment by Axel-Naumann** [comment]
Next issue:
```
13:42:12    clad_local_array.patch:50: trailing whitespace.
13:42:12          m_arr[i] = arr ? arr[i] : 0;
13:42:12    fatal: corrupt patch at line 61
```
I'll check later

**Comment by hahnjo** [comment]
maybe re-generate the patch entirely (assuming we have a way to apply the current one, but it seems Linux is not affected)?

**Comment by Axel-Naumann** [comment]
> maybe re-generate the patch entirely (assuming we have a way to apply the current one, but it seems Linux is not affected)?

@grimmmyshini knows how to do that - I will hot fix this here but it's up to her to do this properly. (FYI @vgvassilev )

**Comment by vgvassilev** [comment]
Can you open an issue we need a new clad release. I don’t think we should drag these patches along for too long.

**Comment by hahnjo** [comment]
> I just meant to apply the semi-broken patches locally and get fresh patches by running `diff`...

... or just download https://github.com/vgvassilev/clad/commit/4baee3583b36259809b361935df8b7d414a88898.patch and https://github.com/vgvassilev/clad/commit/262025e0dc6485700ea938dd3ee873e34a9ebe62.patch (GitHub is nice)

**Comment by Axel-Naumann** [comment]
Current state:
```
18:10:43    Performing patch step for 'clad'
18:10:43    clad_array_size_type.patch:25: trailing whitespace.
18:10:43      CUDA_HOST_DEVICE T& operator[](std::ptrdiff_t i) { return m_arr[i]; }
18:10:43    clad_local_array.patch:50: trailing whitespace.
18:10:43          m_arr[i] = arr ? arr[i] : 0;
18:10:43    clad_local_array.patch:62: trailing whitespace.
18:10:43    double func6(double seed) {
18:10:43    clad_local_array.patch:63: trailing whitespace.
18:10:43      double sum = 0;
18:10:43    clad_local_array.patch:64: trailing whitespace.
18:10:43      for (int i = 0; i < 3; i++) {
18:10:43    fatal: corrupt patch at line 149
```

**Comment by hahnjo** [comment]
Apparently not fully fixed: https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/175439/console reports `fatal: corrupt patch at line 181` :confused:

**Comment by hahnjo** [comment]
please see https://github.com/root-project/root/pull/12892

**Pull request closed without merging**
