### PR TITLE
[DOCS][skip-ci] Switch doxygen link from Jira to GitHub issues

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Review by couet — APPROVED** [review]
May be change the order as suggested  by @ynikitenko.

**Comment by eguiraud** [comment]
In what order should the links be?

**Comment by couet** [comment]
Not sure it is relevant but he said:

_Rearrange "Provide your feedback"
I think github issues should go before the Forum in the list of options (if there are really two ways), because one can see closed and open issues (on the Forum I found several complaints about the links, but it's not clear whether they are open or closed without opening them)._

**Comment by ynikitenko** [comment]
It's your decision about how you organize your work, but maybe it would be better to simply suggest to users to

- submit bugs to github
- ask questions on the forum.

Why I wrote that github is better for "feedback", is because its issues are integrated with push and pull releases, and they won't be lost (as forum reports can be), they will stay open until closed or fixed. 

Maybe you can invent a better wording for that paragraph.

**Comment by eguiraud** [comment]
Closing as duplicate of https://github.com/root-project/root/pull/7307 (had missed that one :smile: ).

**Pull request closed without merging**
