### PR TITLE
[TCling] Exclude deleted functions from iteration.

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by vgvassilev** [comment]
Can you add a test to the TClingTests.cxx?

**Comment by vepadulano** [comment]
I'm not sure so I ask, would this go towards solving [ROOT-10800](https://sft.its.cern.ch/jira/browse/ROOT-10800)?

**Comment by Axel-Naumann** [comment]
Tests are in roottest.

**Comment by vgvassilev** [comment]
> Tests are in roottest.

Not the reproducer which gives the semantic reason why we skip deleted functions.

**Pull request merged**
