### PR TITLE
Testing less_includes features

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Dless_includes=ON

**Comment by pcanal** [comment]
How does this relate to https://github.com/root-project/root/pull/5123 ?

**Comment by linev** [comment]
Yes, these are continuation with conseuent usse of `R__LESS_INCLUDES` macro

**Comment by linev** [comment]
Too many changes were done, new PR will be created soon

**Pull request closed without merging**
