### PR TITLE
Cling 157

### PR DESCRIPTION
**Pull request by Axel-Naumann**
ROOT version of https://github.com/root-project/cling/pull/157

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-ubuntu16/nortcxxmod

**Review by vgvassilev — APPROVED** [review]

**Comment by vgvassilev** [comment]
@Axel-Naumann does the clingtest pass? Could you add it to roottest as we discussed before merging this PR?

**Comment by Axel-Naumann** [comment]
As discussed offline, I can enable cling-test in ROOT's ctest once the call to `sudo` is gone (e.g. by disabling the clang-unloading test) and once the two XFAIL tests are addressed that actually work with ROOT-patches (and thus ROOT).

**Comment by Axel-Naumann** [comment]
> does the clingtest pass?

Yes.

**Pull request merged**
