### PR TITLE
[DF] Avoid memory-heavy histogram entry buffering in single-thread

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by pcanal** [comment]
As a side note, it appears that `dataframe_simple` printouts:
```
[ RUN      ] MT/RDFSimpleTests.WritingToFundamentalType/0
input_line_164:2:41: error: cannot assign to variable 'var0' with const-qualified type 'const int'
auto func22(const int var0){return var0 = 42
                                   ~~~~ ^
input_line_164:2:23: note: variable 'var0' declared const here
auto func22(const int var0){return var0 = 42
            ~~~~~~~~~~^~~~
[       OK ] MT/RDFSimpleTests.WritingToFundamentalType/0 (1 ms)
```
but it does not make that sub-test fails.  Is that intentional?

**Comment by eguiraud** [comment]
> Is that intentional?

@pcanal yes, that's an `EXPECT_THROW` in the test code

**Comment by eguiraud** [comment]
This will fail again (sorry for the mails @pcanal ). I need to double-check what RDF's behavior is with scalar values and vector weights for histogram fillings with/without histo models and with/without multi-threading. It looks like we have an inconsistency in how Histo1D with/without models treats that case (the former allows it, the latter does not).

**Comment by eguiraud** [comment]
The only relevant change is the one in the last commit, but it depends on the other changes from https://github.com/root-project/root/pull/12972 to work correctly, so it's rebased on top of those for now.

**Comment by eguiraud** [comment]
@vepadulano this small change is finally ready for review :grimacing:

**Review by vepadulano — APPROVED** [review]
Yep, nice thanks!

**Pull request merged**
