### PR TITLE
[RF] Update RooFitResult.cxx - use printValue for constPars 

### PR DESCRIPTION
**Pull request by will-cern**
in some user cases there are things in the constPar list that aren't a RooRealVar, so make this printout more flexible by using the printValue method.

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by will-cern** [comment]
sorry, had a typo!

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
Thanks will for generalizing the function like this!

I have just changed your commit to fix the warnings in the CI, and added another code cleaning commit.

**Comment by will-cern** [comment]
thanks for merging. Any chance we can pull into 6.28, since technically it is a bug fix against assumption that the constPars are all RooRealVars?

**Pull request merged**
