### PR TITLE
[v6-24] Compiling on Debian 12 (bookworm)

### PR DESCRIPTION
**Pull request by umbertozappi**
Patches for compile on Debian 12 with Python 3.11 libraries

# This Pull request:

## Changes or fixes:
Permit to compile with Python's libraries 3.11, too
I've tested locally on Debian 12 (bookworm)

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by hahnjo** [comment]
Hi @umbertozappi, thanks for testing! Is this a backport from `master`? We usually try to avoid commits that are on release branches only (except documentation and release notes). Also I think there were some more fix to Python 3.11 support in the mean time; if we want ROOT 6.24 to fully support Python 3.11, we will also need to backport them...

**Comment by umbertozappi** [comment]
Hi @hahnjo
No, this fix isn't a backport of master.

**Comment by hahnjo** [comment]
We should really try to stay similar with `master`. For the change in this PR, that's https://github.com/root-project/root/commit/484deb056dacf768aba4954073b41105c431bffc but https://github.com/root-project/root/pull/10734 has some more changes which should all be backported...

May I ask what is the motivation to use 6.24 with Python 3.11 and not a more recent version of ROOT (we're about to release 6.30)?

**Comment by guitargeek** [comment]
Closed in favor of an actual backport:
* https://github.com/root-project/root/pull/13990

It's always good to have better compatibility of the old branches. It's quite useful also for devs that want to build old releases for debugging.

**Pull request closed without merging**
