### PR TITLE
Fix ROOT-7182 TFile record full pathname in fRealName

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by Axel-Naumann — APPROVED** [review]

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by jblomer — APPROVED** [review]

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The failure on macos is pre-existing (missing python module)

**Pull request merged**
