### PR TITLE
Fix boundary check for VecOps::Take

### PR DESCRIPTION
**Pull request by arizzi**
fixing issue

# This Pull request:

## Changes or fixes:
https://github.com/root-project/root/issues/14914

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by dpiparo** [comment]
@arizzi Thanks for this patch!
Could you also add a test for this here https://github.com/root-project/root/blob/master/math/vecops/test/vecops_rvec.cxx ?

**Comment by arizzi** [comment]
the unit test was already there but the bug was passing that particular version of the test by chance.

it can be modified this way to detect the bug
https://github.com/root-project/root/compare/master...arizzi:root:patch-2

**Comment by arizzi** [comment]
done

**Comment by dpiparo** [comment]
Thanks. Tests started!

**Review by dpiparo — APPROVED** [review]
LGTM. Thanks a lot, @arizzi !

**Pull request merged**
