### PR TITLE
TMVA::DataSetInfo incorrectly handles reading of array of variables

### PR DESCRIPTION
**Pull request by petrstepanov**
# Problem Outline:
Precondition. On the **training (classification)** stage user adds array of variables to the `TMVA::DataLoader` object with a new method introduced in ROOT 6.20:
```
TMVA::DataLoader *loader = new TMVA::DataLoader(...)
loader->AddVariablesArray("vars", nBins);
```

On the next stage - **classification application** user creates `TMVA::Reader` object and adds an array of variables to it:
```
TMVA::Reader* reader = new TMVA::Reader(...);
std::vector<float> fValues(nBins);
reader->DataInfo().AddVariablesArray("vars", nBins, "", "", 0, 0, 'F', kFALSE, &fValues[0]);
```

Pointer to the first element of the `&fValues[0]` passed to the `TMVA::DataSetInfo::AddVariablesArray(..., void *external)` function. Inside `AddVariablesArray()` pointer is **not incremented** in the loop where variables are defined. This provides faulty `reader->EvaluateMVA` output.

# This Pull Request:
Modifies `TMVA::DataSetInfo::AddVariablesArray(..., void *external)` function. Depending on the variable type `char varType`, `void * external` pointer is incremented in the loop. This provides correct TMVA evaluation.

## Changes or fixes:
Please refer to the commit details.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by lmoneta** [comment]
Thank you for the contribution, looks good to me. I will try to include also a test for this

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by petrstepanov** [comment]
@lmoneta no rush. I added a workaround in my program code. So no need to patch 6.26

**Comment by lmoneta** [comment]
@petrstepanov : Thank you for the contribution that now is merged!
I forgot to mention you that next time it would be better to merge together simple commits and have more meaningful commit log messages. 
Thanks again!

**Pull request merged**
