### PR TITLE
[tmva][sofie] Some fixes for 6.34

### PR DESCRIPTION
**Pull request by lmoneta**
This PR provides some fixes and optimization to some operators as Reduce 
See commit messages for details

### CODE REVIEW

**Comment by dpiparo** [comment]
Could tests be written for these fixes?

**Comment by lmoneta** [comment]
Two new tests have been added for these operators. It should be ready now to be merged

**Comment by lmoneta** [comment]
@dpiparo can this be merged? The current code in 6.34 is broken for the ReduceSum operator

**Review by dpiparo — APPROVED** [review]
LGTM, thanks. Also good to backport.

**Review by sanjibansg — APPROVED** [review]
LGTM! Thanks for this.

**Pull request merged**
