### PR TITLE
v6-24-00-patches nonull backport

### PR DESCRIPTION
**Pull request by kgizdov**
Backport for #9271 to v6-24-00-patches

### CODE REVIEW

**Comment by jalopezg-r00t** [comment]
@phsft-bot build

**Comment by kgizdov** [comment]
fixes backported - could someone trigger a rebuild?

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by kgizdov** [comment]
I don't get it, this branch is rebased on `v6-24-00-patches`. Why would it fail with:
```
11:04:06  -- Rebasing kgizdov-v6-24-00-patches-nonull-backport against v6-24-00-patches: [Executing COMMAND;C:/Program Files/Git/cmd/git.exe;-c;user.name=sftnight;-c;user.email=sftnight@cern.ch;rebase;-f;-v;v6-24-00-patches;kgizdov-v6-24-00-patches-nonull-backport;WORKING_DIRECTORY;C:/build/workspace/root-pullrequests-build/root;TIMEOUT;300]
11:04:07  stdout: 
11:04:07  stderr: 
11:04:07  It seems that there is already a rebase-apply directory, and
11:04:07  I wonder if you are in the middle of another rebase.  If that is the
11:04:07  case, please try
11:04:07  	git rebase (--continue | --abort | --skip)
11:04:07  If that is not the case, please
11:04:07  	rm -fr "C:/build/workspace/root-pullrequests-build/root/.git/rebase-apply"
11:04:07  and run me again.  I am stopping in case you still have something
11:04:07  valuable there.
```

**Pull request closed without merging**
