### PR TITLE
[TDF] Datasource fixes

### PR DESCRIPTION
**Pull request by bluehood**
* fix interaction of data-source columns and user-defined columns  
* add tests

### CODE REVIEW

**Comment by dpiparo** [comment]
@bluehood , thanks for the actions you took so quickly.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
Node has the disk full... Please try again later, as disk space is being cleared now.

**Comment by bluehood** [comment]
@phsft-bot build please

**Comment by bluehood** [comment]
@phsft-bot build ?

**Comment by bluehood** [comment]
Alright the bot is not helping, travis is green, I tested locally and everything works as expected, and the changes are small.

I will go ahead and merge and keep a close eye on the incrementals for any issue that might arise on platforms different than my own.

**Pull request merged**
