### PR TITLE
Make fit chunking dependent on IMT pool size

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by dpiparo** [comment]
@xvallspl I wonder if a test can be adequate here.

**Comment by dpiparo** [comment]
just my 2 cents: perhaps we can have the code that they are running?

**Comment by pcanal** [comment]
Original context: https://github.com/cms-sw/cmssw/issues/23105

**Comment by xvallspl** [comment]
Hmmm... From what I understood we can just run a simple fit twice and check that the result is the same. Or maybe even add another test for the evaluation of the objective function, as the reduction is done sequentially and should not create any problem.

**Comment by pcanal** [comment]
Not quite.  The issues was seen as result differing on two different machine but being always the same on the same machine.  The two machines have different number of core and thus the chunking was different even in the case where the user requested only a single core to be used on both machine.

The related issue is, of course, the question of *why* the end result depends on the chunking and whether this indicates a severe flaw in the algorithm used or is 'simply' case of visible but 'normal' numerical error/uncertainty being propagated.

**Comment by pcanal** [comment]
This addresses https://sft.its.cern.ch/jira/browse/ROOT-9421

**Comment by pcanal** [comment]
See also https://sft.its.cern.ch/jira/browse/ROOT-9422 which is not addressed here (instability of the fitting when the number of thread used changes).

**Comment by xvallspl** [comment]
Thanks for merging this, Philippe. I will add the test as soon as I come back from vacation.

The chunking introduces partial reduction of the results (one per chunk). The propagated error in these partial results will differ with the number of data elements processed per chunk. As a consequence, the final reduction step will be carried out with differing implicit errors when specifying different numbers of chunks. This is normal and expected.

Would you have it otherwise? I could see to apply the reduction step with a compensated sum if so.

**Pull request merged**
