### PR TITLE
[cxxmodules] Add a module for experimental/string_view

### PR DESCRIPTION
**Pull request by vgvassilev**
That should fix a recent nightly failure with gcc11

### CODE REVIEW

**Review by pcanal — CHANGES_REQUESTED** [review]
Could enhance the commit log by copy/pasting/summarizing the error that it fixes?  The log will be long gone when we next look at that commit log.  Thanks.

**Comment by vgvassilev** [comment]
The commit message seems pretty clear to me. Can you suggest something?

**Comment by Axel-Naumann** [comment]
@pcanal proposes to add the literal diagnostic, which helps understand "recent failure" in two years, and which allows to search if we run into this again, e.g. in 6-26:

```
[ 70%] Generating G__Core.cxx, ../lib/Core.pcm

/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:491:10: error: module 'std.bits/ranges_base.h' requires feature 'cplusplus20'
  module "bits/ranges_base.h" {
         ^
/usr/include/c++/12/experimental/string_view:43:10: note: submodule of top-level module 'std' implicitly imported here
#include <bits/ranges_base.h> // enable_borrowed_range, enable_view
         ^
In file included from input_line_3:2:

/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/include/Rtypes.h:195:10: fatal error: could not build module 'ROOT_Foundation_Stage1_NoRTTI'
#include "TIsAProxy.h"
 ~~~~~~~~^~~~~~~~~~~~~

Error: Error loading the default rootcling header files.
gmake[2]: *** [core/CMakeFiles/G__Core.dir/build.make:474: core/G__Core.cxx] Error 1
```

**Comment by Axel-Naumann** [comment]
(And btw it's GCC 12, I'm not remembering seeing this issue with GCC 11 as the commit log says?)

**Comment by vgvassilev** [comment]
> (And btw it's GCC 12, I'm not remembering seeing this issue with GCC 11 as the commit log says?)

Nope, the problem being fixed is seen for gcc11 as the commit message points out: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=ROOT-centos9,SPEC=noimt,V=master/3429/console

**Comment by vgvassilev** [comment]
> @pcanal proposes to add the literal diagnostic, which helps understand "recent failure" in two years, and which allows to search if we run into this again, e.g. in 6-26:
> 
> ```
> [ 70%] Generating G__Core.cxx, ../lib/Core.pcm
> 
> /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:491:10: error: module 'std.bits/ranges_base.h' requires feature 'cplusplus20'
>   module "bits/ranges_base.h" {
>          ^
> /usr/include/c++/12/experimental/string_view:43:10: note: submodule of top-level module 'std' implicitly imported here
> #include <bits/ranges_base.h> // enable_borrowed_range, enable_view
>          ^
> In file included from input_line_3:2:
> 
> /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/include/Rtypes.h:195:10: fatal error: could not build module 'ROOT_Foundation_Stage1_NoRTTI'
> #include "TIsAProxy.h"
>  ~~~~~~~~^~~~~~~~~~~~~
> 
> Error: Error loading the default rootcling header files.
> gmake[2]: *** [core/CMakeFiles/G__Core.dir/build.make:474: core/G__Core.cxx] Error 1
> ```

The commit message says exactly that. I don't think I want to paste the error to say actually the same thing as the commit message says.

**Comment by vgvassilev** [comment]
> > @pcanal proposes to add the literal diagnostic, which helps understand "recent failure" in two years, and which allows to search if we run into this again, e.g. in 6-26:
> > ```
> > [ 70%] Generating G__Core.cxx, ../lib/Core.pcm
> > 
> > /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:491:10: error: module 'std.bits/ranges_base.h' requires feature 'cplusplus20'
> >   module "bits/ranges_base.h" {
> >          ^
> > /usr/include/c++/12/experimental/string_view:43:10: note: submodule of top-level module 'std' implicitly imported here
> > #include <bits/ranges_base.h> // enable_borrowed_range, enable_view
> >          ^
> > In file included from input_line_3:2:
> > 
> > /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/include/Rtypes.h:195:10: fatal error: could not build module 'ROOT_Foundation_Stage1_NoRTTI'
> > #include "TIsAProxy.h"
> >  ~~~~~~~~^~~~~~~~~~~~~
> > 
> > Error: Error loading the default rootcling header files.
> > gmake[2]: *** [core/CMakeFiles/G__Core.dir/build.make:474: core/G__Core.cxx] Error 1
> > ```
> 
> The commit message says exactly that. I don't think I want to paste the error to say actually the same thing as the commit message says.

I think I see where the confusion comes from, now. I added the PR title in the commit message.

**Comment by Axel-Naumann** [comment]
Yes, better than the "That should fix a recent nightly failure with gcc11" that Philippe commented on, thanks for improving it!

Compared to just including the actual diagnostic (something Philippe and I generally try to do these days, something that has proven super helpful several times), your current log:
```
That should fix a recent nightly failure with gcc11 avoiding to require
module "bits/ranges_base.h" in C++20 context.
```

does not call out
- that it's during dictionary generation
- that the modulemap requires feature module 'cplusplus20' (your log seems to suggest that the error surfaces when compiled in C++20 mode)
- that the issue is with GCC12 headers (your message seems to suggest that it's with GCC11 headers)
- the "stack trace", i.e. `/usr/include/c++/12/experimental/string_view:43:10: note: submodule of top-level module 'std' implicitly imported here` and then `/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/include/Rtypes.h:195:10: fatal error: could not build module 'ROOT_Foundation_Stage1_NoRTTI'` and then `#include "TIsAProxy.h"`

In general we tell our users (+/- always) "can we please see the actual diagnostic", and for the same reasons it's super helpful to include them here. The time we discussed this is waaay larger than the time it would have taken you to update the log to what Philippe proposes, rather than updating it to something that tries to address the issues (but seemingly fails?)

But it's Philippe's review, I let him comment / deal with this if you still prefer to keep your current commit log. I simply wanted to add an explanation why Philippe suggests the inclusion of the actual diagnostic (and why I found it convincing and do it ever since he propose it to me).

**Comment by vgvassilev** [comment]
> Yes, better than the "That should fix a recent nightly failure with gcc11" that Philippe commented on, thanks for improving it!
> 
> Compared to just including the actual diagnostic (something Philippe and I generally try to do these days, something that has proven super helpful several times), your current log:
> 
> ```
> That should fix a recent nightly failure with gcc11 avoiding to require
> module "bits/ranges_base.h" in C++20 context.
> ```
> 
> does not call out
> 
>     * that it's during dictionary generation
> 
>     * that the modulemap requires the module feature 'cplusplus20' (your log seems to suggest that the error surfaces when compiled in C++20 mode, while this error shows up when compiling in C++14 or 17)
> 
>     * that the issue is also with GCC12 headers (your message seems to suggest that it's only with GCC11 headers)
> 
>     * the "stack trace", i.e. `/usr/include/c++/12/experimental/string_view:43:10: note: submodule of top-level module 'std' implicitly imported here` and then `/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/include/Rtypes.h:195:10: fatal error: could not build module 'ROOT_Foundation_Stage1_NoRTTI'` and then `#include "TIsAProxy.h"`
> 
> 
> In general we tell our users (+/- always) "can we please see the actual diagnostic", and for the same reasons it's super helpful to include them here. The time we discussed this is waaay larger than the time it would have taken you to update the log to what Philippe proposes, rather than updating it to something that tries to address the issues (but seemingly fails?)
> 
> But it's Philippe's review, I let him comment / deal with this if you still prefer to keep your current commit log. I simply wanted to add an explanation why Philippe suggests the inclusion of the actual diagnostic (and why I found it convincing and do it ever since he propose it to me).

This issue exists on gcc11 and gcc12 (and I guess any gcc that made changes to libstdc++ and the experimental/string_view header file). I am not sure if pasting a diagnostic from a random system makes this clearer in any form. I agree with you this should have be 1 min review fixing an important failure that we introduced with the c++20 support and some of the new releases of maybe libstdc++.

@pcanal I find pasting errors in the logs a bad practice, especially when it obfuscates the real fix. Can you suggest a commit message which adds enough information which makes me happy as well?

In general it is a bit unfortunate how the whole review went for this PR. This should been just a simple "approve" as I thought we needed a quick fix which I developed in between travels and a business trip... I suspect this would help me define urgent/important in similar circumstances in future...

**Comment by pcanal** [comment]
@vgvassilev Let me clarify the disconnect.

The title says "Add **a** module for experimental/string_view"
The commit says:

That should fix a recent nightly failure with gcc11 avoiding to require
module "bits/ranges_base.h" in C++20 context.

The code says:
```
 module "experimental/string_view" {
    export *
    header "experimental/algorithm"
 }
 ```
 
The commit content as-is seems completely unrelated to the commit log as far as I could tell (without doing research on the relationship between `range_base`, `string_view` and `algorithm`.
 
So I pondered whether the fix was the right fix for a problem I did not know anything about  ... 
 
The right thing to do would have probably be have been to request a complete explanation of what the original problem was, what was the mechanism leading to the error and why this solution was the best solution.

This was obviously much more than this seemingly simple fix required.

So instead I thought to ask for a very low cost, straight forward solution: simply copy/pasting the error with no additional effort to explain in detail.

> Can you suggest a commit message which adds enough information which makes me happy as well?

That requires to paraphrase the error and add a few more details.

```
That should fix a recent nightly failure with gcc11.

The failure presented during dictionary generation in a C++14 and C++17 build and incorrectly complained about needing   the 'cplusplus20' feature for the 'std.bits/ranges_base.h' module.  The issue was triggered by an inclusion of `<bits/ranges_base.h>`  from `string_view`.

This issue exists on gcc11 and gcc12 (and I guess any gcc that made changes to libstdc++ and the experimental/string_view header file). 

It seems the issue is solved by exporting `algorithm` as part of the `string_view` module.
```

Actually, I still don't know why adding `algorithm` fixes a problem with `range_base.h`, so I can't add that to the commit ... maybe it is something like "... by avoiding to use the module maps provided by the standard library in those case"?

**Comment by vgvassilev** [comment]
> Actually, I still don't know why adding `algorithm` fixes a problem with `range_base.h`, so I can't add that to the commit ... maybe it is something like "... by avoiding to use the module maps provided by the standard library in those case"?

Now that’s something I was looking for! Thank you! I think that’s a mistake in this PR. I failed to update the relevant header as well. The problem is more subtle probably as since some update of gcc it started picking up experimental/string_view which in turn somehow uses the headers only available in c++14 onwards. So perhaps we should re-export string_view… I can look at that tomorrow.

**Comment by vgvassilev** [comment]
@pcanal, please check the commit log, I think that's good to go.

**Review by pcanal — APPROVED** [review]
Looks sufficient even-though the wording still leaves me a bit confused. 

> it needs to include "bits/ranges_base.h" which is a c++14 header 
 
Then why is the error message talking about require C++20 context?

> breaks the compilation in case of c++11.

Didn't Axel report that it failed in C++14 and C++17?

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
The failures seem unrelated. Let's merge this PR.

**Pull request merged**
