### PR TITLE
[skip-ci] df105 nbconvert fix

### PR DESCRIPTION
**Pull request by couet**
Make sure nbconvert work on this script.
See: https://github.com/root-project/root/issues/10430

Thanks to @etejedor and @eguiraud

### CODE REVIEW

**Comment by etejedor** [comment]
The `args=[]` has to be passed only if you are in the notebook, see my comment: https://github.com/root-project/root/issues/10430#issuecomment-1106238384

**Comment by etejedor** [comment]
Something like:
```python
import sys
if 'df105_WBosonAnalysis.py' in sys.argv[0]:
    # Script
    parser.parse_args()
else:
    # Notebook
    parser.parse_args(args=[])
```

**Comment by couet** [comment]
> The args=[] has to be passed only if you are in the notebook, see my comment: https://github.com/root-project/root/issues/10430#issuecomment-1106238384

I saw your comment but what I said is that `parser.parse_args(args=[])` seems to work for both cases. I was wondering why in that case doing two different approaches ?

Anyway I just tried your suggestion. I get:

```
sftnight@root-ubuntu-2004-3:~/couet/root/documentation/doxygen$ python3 ../../tutorials/dataframe/df105_WBosonAnalysis.py
Traceback (most recent call last):
  File "../../tutorials/dataframe/df105_WBosonAnalysis.py", line 44, in <module>
    if args.b: ROOT.gROOT.SetBatch(True)
NameError: name 'args' is not defined
sftnight@root-ubuntu-2004-3:~/couet/root/documentation/doxygen$ 
```

**Comment by etejedor** [comment]
import sys
if 'df105_WBosonAnalysis.py' in sys.argv[0]:
    # Script
    args = parser.parse_args()
else:
    # Notebook
    args =parser.parse_args(args=[])

**Comment by couet** [comment]
Ok. But the code you suggested does not work.

**Comment by etejedor** [comment]
The last version I pasted is different, does that not work either?

**Comment by couet** [comment]
oops , yes it is ok, I did not see it was different. (I pushed it)

**Review by etejedor — APPROVED** [review]

**Pull request merged**
