### PR TITLE
[metacling]Refactor Property into base class by passing reference

### PR DESCRIPTION
**Pull request by reikdas**
@vgvassilev

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by reikdas** [comment]
In https://github.com/root-project/root/pull/5283/files#diff-731544d47414211363492c1443589e15L132 is there any reason why there is no `property |= kIsArray;` ? (It is there in similar blocks like in TClingDataMemberInfo.cxx of this PR - https://github.com/root-project/root/pull/5283/files#diff-cb40dcc7a52ad261ee66558b009a961cL446 and also in the files I refactored in PR #5243 ). 

If I add that line to the block, then I get a checksum mismatch on a streamer (if I am interpreting the roottest error logs correctly) - 
```
--- Using ROOT from /home/reik/root/root-build
--- root/io/double32/template32.ref	2019-12-28 12:45:09.779147688 +0530
+++ root/io/double32/template32.clog	2020-04-03 10:44:03.968974661 +0530
@@ -32,7 +32,7 @@
  OBJ: TRealData	v2.regdouble	Description of persistent data members : 0 at: [deleted from log]
 The following should be a Double32_t: Double32_t
 
-StreamerInfo for class: m02<Double32_t>, checksum=0x8610c861
+StreamerInfo for class: m02<Double32_t>, checksum=0x4dcf66a2
   map2<Double32_t,Double32_t,alloc<pair<Double32_t,Double32_t> > > BASE            offset= [deleted from log] type= 0                     
   int            fN              offset= [deleted from log] type= 6                     
   vector<Double32_t> ff1             offset= [deleted from log] type=300 ,stl=1, ctype=9,                     
make[1]: *** [Makefile:84: template32] Error 1
At least 1 tests have failed:
--- FAILING TEST: make -C . template32
make: *** [/home/reik/root/roottest//scripts/Rules.mk:15: summary] Error 1
```
Maybe the error logs can be fixed by changing the reference file here - https://github.com/root-project/roottest/blob/master/root/io/double32/template32.ref 

But I think since the checksum is not matching, the streamers are also changing and perhaps that is not behaviour we want. 

@pcanal Can you help please?

**Comment by pcanal** [comment]
The checksum should apriori not be changing as a consequence of refactoring (so the refactoring and the behavior change (if it is warranted) should be separate commits.  

If/when the checksum changes,  we need to understand **exactly** why and verify that this is because the information in more precise/better than before (and not because of a bug .. eg.  in the failing example I don't see (looking superficially) any array being involved).

Note that a checksum change is a big deal and means that one would also need to update TStreamerInfo to allow a class with the same version number with 2 different checksums.  Otherwise the users would need to upgrade all the version numbers of their classes (that are affected).

**Comment by reikdas** [comment]
Thanks so much @pcanal !

It was an error in my code. I fixed it :)

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
