### PR TITLE
Deep Learning Module

### PR DESCRIPTION
**Pull request by IlievskiV**
Integration of all different layers in one Deep Learning module.

### CODE REVIEW

**Comment by amadio** [comment]
It looks like you need to rebase this branch since there are conflicts with the current master.

**Comment by omazapa** [comment]
Hi Akshay,
merge commits is not allowed you need to do  a rebase and may solve the conflicts.

**Comment by vgvassilev** [comment]
@IlievskiV, it is not realistic for this 13K lines modifications to be properly reviewed. Could you split this into smaller atomic PRs?

**Comment by xvallspl** [comment]
Hi, @IlievskiV, @sshekh.

Could you rebase and resolve conflicts? I'm assigning this PR to @lmoneta

**Comment by omazapa** [comment]
Hi Guys,

I am getting errors in this branch compiling with cuda  support, I am using cuda 8.


/home/ozapatam/Projects/GSoC/rootdnn/compile/include/TMVA/DNN/Architectures/Cuda.h(396): error: identifier "AReal" is undefined
/home/ozapatam/Projects/GSoC/rootdnn/compile/include/TMVA/DNN/Architectures/Cuda.h(396): error: identifier "AReal" is undefined
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu(143): error: declaration is incompatible with "void TMVA::DNN::TCuda<AFloat>::Im2col(TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)"
/home/ozapatam/Projects/GSoC/rootdnn/compile/include/TMVA/DNN/Architectures/Cuda.h(287): here
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu(254): error: declaration is incompatible with "void TMVA::DNN::TCuda<AFloat>::Downsample(TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, int, int, int, int, int, int)"
/home/ozapatam/Projects/GSoC/rootdnn/compile/include/TMVA/DNN/Architectures/Cuda.h(357): here
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu(267): error: expected a declaration
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu(333): warning: parsing restarts here after previous syntax error
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/RecurrentPropagation.cu(29): error: "auto" function requires a trailing return type
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/RecurrentPropagation.cu(29): error: declaration is incompatible with "TMVA::DNN::TCuda<AFloat>::Matrix_t &TMVA::DNN::TCuda<AFloat>::RecurrentLayerBackward(TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, const TMVA::DNN::TCudaMatrix<AFloat> &, TMVA::DNN::TCudaMatrix<AFloat> &)"
/home/ozapatam/Projects/GSoC/rootdnn/compile/include/TMVA/DNN/Architectures/Cuda.h(92): here
/home/ozapatam/Projects/GSoC/rootdnn/tmva/tmva/src/DNN/Architectures/Cuda/RecurrentPropagation.cu(39): error: expected a declaration

**Pull request closed without merging**
