### PR TITLE
fix for 2nd part of ROOT-10528 

### PR DESCRIPTION
**Pull request by pcanal**
Mainly fix TClass::GetClass behavior when AutoLoading is disabled.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
Could you split the rename from the actual fix?

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
The test failure is due to #4988 which was a hotfix for 09934e9d6a2a55248efca3ad9659e684850b2426

**Pull request merged**
