### PR TITLE
[Doc][NFC] Add initial tutorials for DF and RVec linking to doxygen

### LINKED ISSUE #7700: [DF] Add df000 tutorial and link to the doxygen documentation
To catch people starting looking at RDF from the tutorials!

### LINKED ISSUE #7701: [VecOps] Add vecops000 tutorial linking to the doxygen documentation
To catch people start looking at VecOps and RVec from the tutorials.

### PR DESCRIPTION
**Pull request by stwunsch**
The idea is to catch people looking at DF or VecOps/RVec and remember
them of the exhaustive documentation on doxygen.

Fixes #7700
Fixes #7701

### CODE REVIEW

**Comment by stwunsch** [comment]
Note to myself: We want to keep a `vecops000_introduction.*` version, but the `df001_introduction.*` is already fine as it is.

**Comment by eguiraud** [comment]
(+ the text you get at the top of https://root.cern.ch/doc/master/group__tutorial__vecops.html should be expanded a bit and at least link to the docs)

**Review by couet — APPROVED** [review]

**Review by eguiraud — DISMISSED** [review]
As per comments above

**Review by guitargeek — APPROVED** [review]
Following the PR discussion, I changed this PR to expand the introduction in the vecops tutorials instaead of introducing a new "introduction" tutorial. This mirrors what also RDataFrame has done in the meantime, and then this stale PR can be closed by merging.

**Pull request merged**
