### PR TITLE
Revert "Implementation of REveText, addition of GL overlay support (p…

### PR DESCRIPTION
**Pull request by jblomer**
…rototype)."

This reverts commit 3b9ed05df2f1209c715deb4a500206f5458b20ba.

There are some case of errors like

```
[512/1065] Building CXX object graf2d/asimage/CMakeFiles/ASImage.dir/src/TASPngWriter.cxx.o
FAILED: graf2d/asimage/CMakeFiles/ASImage.dir/src/TASPngWriter.cxx.o 
<snip>
src/graf2d/asimage/src/TASPngWriter.cxx:3:10: fatal error: afterrootpngwrite.h: No such file or directory
    3 | #include <afterrootpngwrite.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

```
C:\root-dev\git\master\graf2d\asimage\src\TASPngWriter.cxx(3,10): error C1083: Cannot open include file: 'afterrootpngwrite.h': No such file or directory [C:\root-dev\build\x64\release\graf2d\asimage
\ASImage.vcxproj]
```

I suggest to revert until this is sorted out.

### CODE REVIEW

**Review by dpiparo — APPROVED** [review]
Please go ahead.

**Comment by linev** [comment]
Is it appears in incremental builds?
Source is this PR: https://github.com/root-project/root/pull/15812

**Comment by jblomer** [comment]
@linev I just checked out your branch but this fix unfortunately still doesn't work for me

**Comment by linev** [comment]
@jblomer Are you using incremental build?

**Comment by jblomer** [comment]
Yes, this is an incremental build

**Comment by linev** [comment]
For me it works only after fresh rebuild

**Comment by jblomer** [comment]
Ok, didn't try this yet. I would prefer if we found a solution that works with incremental builds.

**Comment by linev** [comment]
ROOT CI was showing green on all platforms for the PR #15812, my PR probably just cosmetics

**Comment by osschar** [comment]
The original PR had `clean build` tag ... @dpiparo told me to use this when it turned out libAfterImage is not re-built without it. And the PR adds files in there.

**Comment by linev** [comment]
>  I would prefer if we found a solution that works with incremental builds.

It is affects `ExternalProject_Add` command in cmake - one have to rebuild libAfterImage. 
I see no easy way to add dependency there

**Comment by osschar** [comment]
Sorry about giving you extra work on Monday morning :( I'm going to bed now ... if I wake up with hiccups I'll know it's you guys extending your vocabulary on my account :)

Vincenzo told me libAfterImage is now never taken as an external ... so it doesn't really need to be built as such. But this would require an even bigger surgery, doing all the low-level image format library resolution in our cmake stuffez.

**Comment by linev** [comment]
Not trivial solution will be fully integrate building of libAfterImage into ROOT cmake.
But this is too much work.

**Comment by jblomer** [comment]
@linev I'm trying rebuilding from scratch now. I'm afraid I don't have enough battery, so I can't give feedback until some time after my current meeting. 
@dpiparo I'm assigning you to this PR, if you don't mind. Please feel free to decide whether to close or merge.

**Comment by hahnjo** [comment]
FWIW you can resurrect your local incremental builds with `rm -rf AFTERIMAGE-prefix/` and then `cmake .`. The failure is related to our `ExternalProject_Add` that does `cmake -E copy_directory` without properly tracking dependencies.

**Pull request closed without merging**
