### PR TITLE
[DF] Fix compilation of Foreach with mutable lambdas 

### LINKED ISSUE #8317: [DF] Compilation failure when a mutable lambda is passed to Foreach
### To Reproduce

```cpp
#include <ROOT/RDataFrame.hxx>

int main() {
   int i = 0;
   ROOT::RDataFrame(10).Foreach([&](ULong64_t e) mutable { ++i; }, {"rdfentry_"});
   return i;
}
```

Currently this fails to compile because the helper type `AddSlotParameter` expects a const functor.

### PR DESCRIPTION
**Pull request by eguiraud**
This fixes #8317.

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
But see comment. I'd really like to tun on IMT by default on Windows and macOS and with X11 outside the grid and batch systems, and this might trigger failures?

**Comment by eguiraud** [comment]
> and this might trigger failures?

yes, and not just here. i don't know how much of our code (and users') relies on the default being single-thread execution, but it's probably a fair amount. having to always think about thread-safety even when doing these sort of quick debugging printouts is not a 100% transparent change.

**Comment by Axel-Naumann** [comment]
And for this test you can be certain that no other code in the same test binary turns on IMT?

**Comment by eguiraud** [comment]
Yes, the only place that turns on (and then off) IMT in this executable is https://github.com/root-project/root/blob/941025d4e9ecb486419afe7e2be250bd02bd5169/tree/dataframe/test/dataframe_interface.cxx#L356-L364

**Comment by eguiraud** [comment]
Merging this. If we want code to be able to never assume implicit MT is off we need a big pass over most RDF code anyway.

**Pull request merged**
