### PR TITLE
Remove Thread tutorials

### PR DESCRIPTION
**Pull request by dpiparo**
Moved to roottest, see https://github.com/root-project/roottest/pull/126

### CODE REVIEW

**Comment by pcanal** [comment]
Do we have replacement for threadsh1.C and threadsh2.C which shows how to handle TCanvas from multiple threads?

**Comment by dpiparo** [comment]
@pcanal , we have this JIRA item about thread safety of canvases: https://sft.its.cern.ch/jira/browse/ROOT-9177
Perhaps @couet wants to give a try to these tutorials?

**Comment by dpiparo** [comment]
... I claim nobody looked at these tutorials in a very long time. The programming model as well as the description are somehow indicators.

**Comment by pcanal** [comment]
> ... I claim nobody looked at these tutorials in a very long time. The programming model as well as the description are somehow indicators.

Yes, they need to be updated/replaced.

> we have this JIRA item about thread safety of canvases: https://sft.its.cern.ch/jira/browse/ROOT-9177

These 2 tutorials are not about construction/destruction but about access pattern and insuring that the canvas are refreshed.

Thanks.
Philippe.

**Comment by dpiparo** [comment]
sure. Shall I open another ticket about utilisation side by side the one about construction?

**Comment by dpiparo** [comment]
Jokes apart, redoing the tutorial is easy. As a matter of fact, I'll add soon to the PR. Thanks @pcanal for the feedback!

**Comment by pcanal** [comment]
> Jokes apart, redoing the tutorial is easy. As a matter of fact, I'll add soon to the PR.

Great thanks.   Could you also translate threadsh2.C?  Thanks.

PS.
```
(*gThreadXAR)("METH", 4, arr, NULL);
```
means, please execute the given function call as part of the main threads 'ProcessEvents' loop.

**Comment by dpiparo** [comment]
I am not sure of the value of translating the tutorial. It's not well written and it's not clear to me the information useful for the end users which is carried by it, especially since we already have threadsh1 already.

**Comment by pcanal** [comment]
The test h2 shows how to generated animated gif from snapshots of the canvas without taking a lock (but by using the gThreadXAR mechanism ... which we probably need to (eventually) 'replace').

If there is no easy and/or clear translation of this example, I recommend we keep it until such a time where we have a clear replacement.

Thanks,
Philippe.

**Comment by Axel-Naumann** [comment]
ok to close?

**Pull request closed without merging**
