### PR TITLE
[CMAKE] Make CXX_FLAGS on Mac cache variables.

### PR DESCRIPTION
**Pull request by hageboeck**
On linux, the compiler flags are cache variables, i.e. they can be
overridden by the user. On Mac, that wasn't the case.

### CODE REVIEW

**Comment by hageboeck** [comment]
You mean you want `-O3` etc? I don't know why that was only changed for unix.

**Comment by hageboeck** [comment]
@Axel-Naumann Do you know why Mac has `-O2` and Unix `-O3`?

**Comment by oshadura** [comment]
my personal opinion from CMake point of view this PR is ready to go and and fix discrepancy between Mac and Unix Debug setup. @Axel-Naumann can you please confirm that Mac should have `-O2` and nor `-O3`?

**Comment by Axel-Naumann** [comment]
I don't remember why Mac had O2 not O3, sorry. I do remember we looked at it once.

**Comment by oshadura** [comment]
@Axel-Naumann agree, sorry for noise and I will merge PR.

**Pull request merged**
