### PR TITLE
[Exp PyROOT] Use VERSION_GREATER_EQUAL for Python version in dotted s…

### PR DESCRIPTION
**Pull request by etejedor**
…tring

### CODE REVIEW

**Comment by oshadura** [comment]
@maxgalli I was asking you to talk with Enric yesterday about https://github.com/root-project/root/pull/5158 before merging PR.

**Comment by etejedor** [comment]
@oshadura I reviewed #5158 and decided to keep this warning disabling. This PR just fixes an issue with the comparison of the version.

**Comment by oshadura** [comment]
Ok, please go ahead! I am looking forward to https://github.com/root-project/root/pull/5158 PR, which fix warning for me in pyroot

**Comment by oshadura** [comment]
Ah, I just realized that this "_" is everywhere....I think there is no way to keep it.

**Comment by etejedor** [comment]
IIRC @maxgalli needed this `_` version of the python major.minor to construct the PyROOT library names, which, since some of them are Python extension modules, can't contain a dot in the name.

What he can do is just not set the `_` version to the CMake variable and leave it intact, but still have his own variable with the underscore to generate the PyROOT library names.

@maxgalli can you take care of this? You can start from this PR or I close and you start from a new one, as you prefer.

**Pull request closed without merging**
