### PR TITLE
[cxxmodules] Preload more modules

### PR DESCRIPTION
**Pull request by vgvassilev**
Rebase PR #1396.

Original PR comment:
"ROOT can't autoparse classes inside namespaces with the rootmap
system (as the loading callbacks don't correctly land where
they are supposed to land with our injected namespaces). As this
turns out to be a feature of some kind, let's preload
TMVA/TreePlayer/Graf to fix all failing tests that are related
to this feature/bug with modules enabled.

This commit can be dropped if we solve on of those problems:

    figure out how to fix this bug in the rootmap-based loading
    without regressin in performance.

    replace the rootmap system with something else like attaching
    all C++ modules on startup.

Note that we already do something like this in normal ROOT by
including these packages into the PCH which also makes those
decls available in the normal clang lookup."

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by pcanal** [comment]
> let's preload TMVA/TreePlayer/Graf to fix all failing tests that are related to this feature/bug with modules enabled.
> ... This commit can be dropped if we solve on of those problems:

Obviously the removal of this preload is a necessary precursor to making the use of module the default.  Do we have a mechanism to 'not' forget to remove it?

**Comment by vgvassilev** [comment]
@pcanal, can you elaborate a little because I cannot understand both sentences ;)

**Comment by pcanal** [comment]
>> Obviously the removal of this preload is a necessary precursor to making the use of module the 
>> default. Do we have a mechanism to 'not' forget to remove it?

> @pcanal, can you elaborate a little because I cannot understand both sentences ;)

@vgvassilev I was apparently mistakenly talking about 'preloading the library' rather than what you seem to have meant ('preloading the module').   Since it is 'only' the module and that we already do this pre-loading of the AST node via the PCH, removing this 'pre-attaching of the AST nodes via preloading the module' is indeed not a pre-requisite to making the use of module the default mechanism.  [It is rather a question of optimization and/or implementation of the replacement for the rootmap forward declaration].

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
I think we can close this as it's out of date and we have a new patch for loading all the modules. Loading more modules have the negative effect on performance, so we're not going to this direction for now.

**Comment by vgvassilev** [comment]
Which is the new patch you have in mind?

**Comment by yamaguchi1024** [comment]
https://gist.github.com/yamaguchi1024/56cc7a18638c9f581817e682b729e880
^ This one

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -DROOT_PARALLEL_LINK_JOBS=2  -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -DROOT_PARALLEL_LINK_JOBS=2 -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@Teemperor, I'd like to close this PR but the change to the clang::SourceManager seems still relevant. Could you open a phab review for it?

**Comment by vgvassilev** [comment]
This is implemented in a different way in the master.

**Pull request closed without merging**
