### PR TITLE
[RF] Added offsetting to `RooAbsPdf::fitTo`

### PR DESCRIPTION
**Pull request by Zeff020**
# This Pull request:

## Changes or fixes:

Adds offsetting named argument to `RooAbsPdf::fitTo()` as requested in #11856. I have decided to use the naming convention for the named argument options that was already present in `RooAbsPdf::CreateNLL()` to avoid confusion and for the potential case that the other named argument options in the latter will also be added to `RooAbsPdf::fitTo()`

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — CHANGES_REQUESTED** [review]
Hi @Zeff020, thanks for opening PR!

Have you tested this change? If I try out the code now with the basic Gaussian NLL from the `rf101` example (as always), if always errors out:

```
gauss.fitTo(*data, ModularL(true), Offset(true), Parallelize(true));
```
Gives:
```
[#0] ERROR:InputArguments -- RooAbsPdf::createNLL(gauss) ERROR: argument ModularL not allowed in this context
[#0] ERROR:InputArguments -- RooAbsPdf::createNLL(gauss) ERROR: argument ModularL not allowed in this context
[#0] ERROR:InputArguments -- RooAbsPdf::createNLL(gauss) ERROR: illegal combination of arguments and/or missing arguments
terminate called after throwing an instance of 'std::logic_error'
  what():  In RooMinimizer constructor: Selected likelihood evaluation but a non-modular likelihood was given. Please supply ModularL(true) as an argument to createNLL for modular likelihoods to use likelihood or gradient parallelization.
```

And when I don't use `Parallelize(true)`, I even get a segfault.

Do you also see this behavior? If yest, can you fix it please?

**Comment by Zeff020** [comment]
Hi @guitargeek, my most recent commit should fix the issue that you encountered, at least it does for me locally.

**Comment by guitargeek** [comment]
Cool, thanks! Okay I'll try it

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
Hi @Zeff020! There are some tests failing now. Can you check what's going on there? Let me know on Mattermost if you need help

**Comment by Zeff020** [comment]
Hi @guitargeek, I've amended my most recent commit, could you try the build and tests again? All problems should be resolved now.

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
LGTM, thanks for the fix! I tried out the fit in the first RooFit tutorial now:
```
gauss.fitTo(*data, PrintLevel(-1), Save(), ModularL(true), Offset(true), Parallelize(false))->Print();
```
And I put some printouts in the RooMinimizer to see if the offsetting option is correctly propagated. And it is.

**Pull request merged**
