### PR TITLE
Fix move-only types support in TExecutor::Map

### PR DESCRIPTION
**Pull request by anerokhi**

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @anerokhi , thanks for the PR. Could you add a test for this feature? It could be located in a file https://github.com/root-project/root/tree/master/core/base/test here called "ExecutorsTests.cxx".

**Comment by anerokhi** [comment]
So where should I add the test? BTW, it is more than primitive.
```c++
auto v = ROOT::TThreadExecutor{}.Map([](int) { return make_unique<TList>(); }, { 1, 2, 3 });
```
shall compile.

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by bellenot** [comment]
The `windows10/default` build fails because of roottest not being found in your GitHub (i.e. you didn't clone roottest)

**Comment by anerokhi** [comment]
@bellenot fixed

**Comment by dpiparo** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Thanks, @anerokhi !

**Pull request merged**
