### PR TITLE
[physics] Add conversion to ROOT::Math::XYZTVector

### PR DESCRIPTION
**Pull request by Axel-Naumann**
As a wonderful side-effect, this adds support for construction from a TLorentzVector.

See https://root-forum.cern.ch/t/problem-initializing-a-4-vector/50789

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
That overload doesn't work, back to drawing board.

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you for the nice improvement!

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you Axel for adding this conversion!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Pull request merged**
