### PR TITLE
Fix in complex_quartic  problem reported in issue #6900 and add test

### LINKED ISSUE #6900: mathmore: invalid roots for a quartic polynomial
trying to find the roots of the following polynomial:
```
  a x^4 + b x^3 + c x^2 + d x + e = 0

a = 2.2206846808021337
b = 7.643281053997895
c = 8.831759446092846 
d = 3.880673545129404
e = 0.5724551380144077
```

I get the following roots:
```python
>>> import ROOT
>>> list(ROOT.Math.Polynomial(
2.2206846808021337, 7.643281053997895,
8.831759446092846, 3.880673545129404,
0.5724551380144077).FindRoots())

[(-0.8609914206605772+0j),
 (-0.8609285681365977+0j),
 (-0.8599689425356434-3.142626022335893e-05j),
 (-0.8599689425356434+3.142626022335893e-05j)]
```

plotting that polynomial, we can easily notice the roots are incorrect:
foo

using `numpy.roots` (which is using a companion matrix):
```python
>>> import numpy as np
>>> np.roots([
2.2206846808021337, 7.643281053997895,
8.831759446092846, 3.880673545129404,
0.5724551380144077])

array([-1.34283005+0.00000000e+00j, -1.34282804+0.00000000e+00j,
       -0.37809989+1.00708006e-06j, -0.37809989-1.00708006e-06j])
```
we do get saner values.

### PR DESCRIPTION
**Pull request by lmoneta**
Uncomment some different code that is used to compute the discriminat of the
resolvent cubic equation used to find the roots of a quartic equation. 
This different code seems to be better numerically. 

This fixes #6900

Add tests for quartic equations to validate code.

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build  just on ROOT-debian10-i386/cxx14 with flags -Dmathmore=On

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build with flags -Dmathmore=On

**Review by guitargeek — APPROVED** [review]
This is a nice improvement! Maybe we can still merge it, and also close the associated issue?

**Comment by hahnjo** [comment]
@guitargeek @lmoneta before merging such old PR, it would have been in order to rebase and run this through the new CI: It broke Windows builds (fixed by @bellenot in https://github.com/root-project/root/pull/14274) and causes a CMake warning (to be addressed by https://github.com/root-project/root/pull/14280)...

**Comment by hahnjo** [comment]
The new test also seems to fail on mac14arm in the new CI, can you please have a look asap? @guitargeek @lmoneta

**Pull request merged**
