### PR TITLE
[v624][PyROOT] Fixes for Python 3.11

### PR DESCRIPTION
**Pull request by guitargeek**
Backport of the Python 3.11 compatibility PRs:
* https://github.com/root-project/root/pull/10734
* https://github.com/root-project/root/pull/10047
* https://github.com/root-project/root/pull/11457
* https://github.com/root-project/root/pull/12857

### CODE REVIEW

**Comment by hahnjo** [comment]
There are even more fixes for Python 3.11 compatibility, this was exactly my point; I found at least
 * https://github.com/root-project/root/pull/11457
 * https://github.com/root-project/root/pull/12857

Again, the question is why we need to support new versions of Python with a (legacy) release of ROOT...

**Comment by guitargeek** [comment]
Ah, thanks! I though you meant the other commit from the same PR

**Comment by hahnjo** [comment]
Yes, the other commits from the same PR were the obvious candidates. I'm neither claiming that the above list is the full set of fixes for Python 3.11 - hence my question towards the purpose. IMHO just making it compile but crash at runtime isn't exactly the best state for a future bug fix release...

**Comment by hahnjo** [comment]
I mean crashes with Python 3.11 - we don't have this in the Jenkins nodes. Claiming support without testing isn't ideal.

**Comment by guitargeek** [comment]
Well, we are not claiming Python 3.11 support. It's just a courtesy to the user who wanted to make these changes to the 6.24 branch.

**Comment by umbertozappi** [comment]
I want to thank you for your time and I promise that next time I will try to open PR on the master branch.

**Pull request merged**
