### PR TITLE
[TMVA][SOFIE]Selu and Sigmoid activation functions for PyTorch Parser

### PR DESCRIPTION
**Pull request by tong-qiu**
Add support for Selu activation function for pytorch parser.

### CODE REVIEW

**Comment by tong-qiu** [comment]
Sigmoid activation function is also added.

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Review by lmoneta — CHANGES_REQUESTED** [review]
Hi 
The PR looks good. There is only a conflict caused by another merge we did in the mean time in the TMVA/Sofie repository, probably the addition for supporting the RNN operator. 
Can you please rebase, fix the conflict and update the PR so we can merge it ?

Thank you !

Lorenzo

**Comment by tong-qiu** [comment]
The merge conflict has been resolved. Please rerun build.

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
Thank you for updating the PR. I will check if it rebuilds and if it will be fine, I will merge it

**Comment by tong-qiu** [comment]
@phsft-bot  build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by tong-qiu** [comment]
The pipeline failed because of a merged conflict. This time I tried rebase instead of merged. Could you try rebuild again?

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
Thanks for rebasing. Now it should be fine

**Comment by tong-qiu** [comment]
Sorry a merge conflict was not handled properly. Now it should be fine.

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by tong-qiu** [comment]
It needs another rebuild. The problematic file was somehow ignored when I compile it locally. Sorry about this. :cold_sweat:

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Review by lmoneta — APPROVED** [review]
Looks good now ! Thank you for the contribution!

**Pull request merged**
