### PR TITLE
LZ4 upgrade to latest recommended version (multiple bug fixes)

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by pcanal** [comment]
Could you augment the commit to include the new version number and maybe even a link to the LZ4 release notes?  Thanks.

**Comment by oshadura** [comment]
@pcanal shoudl I apply clang-format and fix clang-tidy errors in LZ4 codebase?

**Comment by amadio** [comment]
@oshadura, no, we should not use clang-format on code we do not own, otherwise it's hard to know what's different with upstream. That's valid for all builtins.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
