### PR TITLE
Fix in TGeoMCGeometry::Mixture(Int_t& kmat, const char* name, Float_t…

### PR DESCRIPTION
**Pull request by agheata**
Cherry-picked from Ivana's commit f245cb4
Ivana needs this also in v6-18-00-patches

### CODE REVIEW

**Comment by agheata** [comment]
Cherry-picked also the previous commit that Ivana wanted

**Comment by agheata** [comment]
@ihrivnac can you check that these are the right commits to be ported to 6-18?

**Comment by ihrivnac** [comment]
Thank you, @agheata . I checked, and confirm.

**Comment by agheata** [comment]
The build on ROOT-fedora30/cxx14 fails for no reason, all test have passed but the build is declared UNSTABLE for some unknown reason. @Axel-Naumann any idea? I've seen this message on other builds in the past.

**Comment by agheata** [comment]
All test passing, failure is due to UNSTABLE. @Axel-Naumann this is ready to merge

**Pull request merged**
