### PR TITLE
Fix memory leak in TTreeCacheUnzip

### PR DESCRIPTION
**Pull request by linev**
Discovered by clang-tidy #7429 
Plus few minor fixes tree sources

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
The travis-ci/pr result (clang-tidy) seems relevant (point to potential problem).

**Comment by linev** [comment]
Should I port it to 6.24?

**Comment by linev** [comment]
> The travis-ci/pr result (clang-tidy) seems relevant (point to potential pre-existing problem).

@Axel-Naumann @pcanal 

80-90% of messages from clang-tidy are false positives or not very important (like unused variables). And in case of `travis-ci/pr` it only reports about lines which are changed in PRs. Therefore it useless now. Probably, one should enable only really important errors from clang-tidy (like memory leak or wrong delete operator), but make them more prominent in PRs - send message in the thread like Jenkins does.

**Comment by pcanal** [comment]
> Should I port it to 6.24?

Yes, please :)

**Pull request merged**
