### PR TITLE
Adjust all THttpServer source with travis 

### PR DESCRIPTION
**Pull request by linev**
Plus minimal change in websocket id - use UInt_t instead of void*

### CODE REVIEW

**Comment by linev** [comment]
Seems to be, my configuration for clang-format does not really match with the travis CI.

**Comment by linev** [comment]
Please ignore it - it has one line of code from webgui prototype.
I need to remove it.

**Comment by linev** [comment]
I will try to fix compilation problem.
Tomorrow I will update my "http_travis" branch.
After such update it should be possible to merge request.

But another problem with clangFormat will remain.
Formatting rules here https://root.cern.ch/coding-conventions does not correspond to Travis CI checker.

**Comment by bellenot** [comment]
You should just be using the .clang-format in the repository directly

**Comment by linev** [comment]
From my side I am done.
At least Travis CI is now happy :)

**Comment by bellenot** [comment]
Thanks Sergey!

**Pull request merged**
