### PR TITLE
Revert "[To be reverted] Disable df026 because it requires pandas."

### PR DESCRIPTION
**Pull request by stwunsch**
PR to check the status of the build nodes wrt to pandas.

Related to the ticket https://sft.its.cern.ch/jira/browse/ROOT-10921

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@cernphsft build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by oshadura** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
