### PR TITLE
[backport] Revert "[cxxmodules] Allow submodules to contain headers which may be…

### PR DESCRIPTION
**Pull request by vgvassilev**
… missing."

This reverts commit f4ea5ad76c74671ebbdfb64fdaeffb986811420d.

We do not need to support gcc 4.8 anymore.

### CODE REVIEW

**Comment by vgvassilev** [comment]
This should help with cms-sw/cmssw#39735

**Comment by vgvassilev** [comment]
This failure seems unrelated to this PR.

**Comment by hahnjo** [comment]
I'm not sure about this: Commit 0d6d2ff902bee4b6485aae19dba9d346c2138f69 requiring C++14 only landed for 6.26. Before that (including 6.24), ROOT only required C++11 and should build fine with GCC 4.8.5 from CentOS 7. Breaking this in a patch release may not be a good idea... @Axel-Naumann

**Comment by Axel-Naumann** [comment]
@hahnjo where do we require C++14 here? Sorry, I'm not seeing that (but I also forgot the meaning of `require !header_existence`).

**Comment by Axel-Naumann** [comment]
Found it: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-v6-24-00-patches/LABEL=ROOT-ubuntu16,SPEC=cxx14,V=6-24/175/console is now failing (since this PR) with
```
00:22:07 /mnt/build/night/LABEL/ROOT-ubuntu16/SPEC/cxx14/V/6-24/build/etc/cling/std.modulemap:313:20: error: header 'string_view' not found
00:22:07     textual header "string_view"
00:22:07                    ^
00:22:07 input_line_1:1:10: note: submodule of top-level module 'std' implicitly imported here
00:22:07 #include <new>
00:22:07          ^
``` 

@vgvassilev please consider reverting this.

**Comment by hahnjo** [comment]
This change in itself doesn't require C++14, but I understand "We do not need to support gcc 4.8 anymore." that you cannot build with that version of GCC anymore, which should have worked fine before with 6.24...

**Comment by hahnjo** [comment]
> I don’t have access to a laptop right now. @hahnjo can you revert?

https://github.com/root-project/root/pull/11582

**Pull request merged**
