### PR TITLE
Fix for copying title to cloned volumes and nodes [6-22]

### PR DESCRIPTION
**Pull request by mrodozov**
Porting it from master

### CODE REVIEW

**Comment by jalopezg-uc3m** [comment]
@phsft-bot build

**Comment by civanch** [comment]
@couet , @agheata , we need the patch urgently - it is blocking for this year CMS plans.

**Comment by bellenot** [comment]
@mrodozov please fork also [roottest](https://github.com/root-project/roottest) to avoid build failure on `windows10/cxx14`

**Comment by mrodozov** [comment]
alright I'll change it

**Comment by mrodozov** [comment]
I forked it

**Review by pcanal — APPROVED** [review]

**Pull request merged**
