### PR TITLE
Eve-7: Handle exception in table content streaming 

### PR DESCRIPTION
**Pull request by alja**
* Try/catch exceptions in steaming of table
* Stream REveLog message conent in the the end-change content form server
* Add support for different projections than RPhi RhoZ in REveJetCone

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check changes for master branch.

**Comment by linev** [comment]
@phsft-bot build

**Comment by alja** [comment]
@linev I can't see the exact reason for clang-format error which is reported above.

**Comment by linev** [comment]
> I can't see the exact reason for clang-format error which is reported above.

It simply fails for all PRs. No idea why

**Review by linev — APPROVED** [review]
Looks ok

**Comment by linev** [comment]
@alja Should one back-port these changes to 6.26? As I understand, 6.24 get these changes?

**Comment by alja** [comment]
@linev I have made a backport of this PR to 6.26 in #9643.
The 6.24 get this changes except  error handling in table representation of REveDataCollection. This one as I know is used only by CMS event display.

**Pull request merged**
