### PR TITLE
[GSoC] Add ZSTD compression algorithm to ROOT I/O 

### PR DESCRIPTION
**Pull request by oshadura**
Open as a replacement of https://github.com/root-project/root/pull/3947

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build with flags -Dbuiltin_zstd=ON

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build with flags -Dbuiltin_zstd=ON

**Comment by oshadura** [comment]
@Axel-Naumann, @pcanal, actual Jenkins build is green, "red" is coming from clang-format warnings for ZSTD builtins...

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -Dbuiltin_zstd=ON -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by oshadura** [comment]
@phsft-bot build with flags -Dbuiltin_zstd=ON -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by oshadura** [comment]
@Axel-Naumann do you know what means next on ROOT-fedora27/noimt:
`09:35:57 From https://github.com/oshadura/root
09:35:57  * [new branch]            alfonso-zst-final -> oshadura-alfonso-zst-final
09:35:57 Auto packing the repository in background for optimum performance.
09:35:57 See "git help gc" for manual housekeeping.
09:35:57 error: The last gc run reported the following. Please correct the root cause
09:35:57 and remove .git/gc.log.
09:35:57 Automatic cleanup will not be performed until the file is removed.
09:35:57 
09:35:57 warning: There are too many unreachable loose objects; run 'git prune' to remove them.`

**Comment by Axel-Naumann** [comment]
> do you know what means next on ROOT-fedora27/noimt:

Fixed!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@pcanal did you mean `@phsft-bot build with flags -Dbuiltin_zstd=ON -DCTEST_TEST_EXCLUDE_NONE=On`?

**Comment by pcanal** [comment]
The errors contains:
```
03:51:11 -- Looking for ZSTD
03:51:11 CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
03:51:11   Could NOT find ZSTD (missing: ZSTD_LIBRARIES ZSTD_INCLUDE_DIR)
```

**Comment by pcanal** [comment]
@pcanal did you mean @phsft-bot build with flags -Dbuiltin_zstd=ON -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
> @pcanal did you mean  ...  -Dbuiltin_zstd=ON 

Well ... that is one test to run ... but also since without it does not "work" , we can't merge ....

**Comment by pcanal** [comment]
@phsft-bot build with flags -Dbuiltin_zstd=ON -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@Axel-Naumann @oshadura What are we missing for the PR to succeed without -Dbuiltin_zstd=ON ?

**Comment by oshadura** [comment]
Hi Philippe! About zstd, it is using classical fail-on-missing strategy, which is enabled by default in PRs. Axel will help me to install zstd on PR nodes, so we can test it without builtin_zstd. I tested builds without builtin_zstd and fail-on-missing strategy, it works just fine..

**Comment by oshadura** [comment]
@ph build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@pcanal failure of projectroot.tree.dataframe.test.gtest_tree_dataframe_test_dataframe_snapshot  is unrelated comparing to my changes

**Comment by pcanal** [comment]
The failure of projectroot.tree.dataframe.test.gtest_tree_dataframe_test_dataframe_snapshot on ROOT-ubuntu16/rtcxxmod does not appear to be related **but** it also succeed consistently with just the master, so we need to understand a bit more why it fails here before merging.

**Comment by oshadura** [comment]
@phsft-bot build only on ROOT-ubuntu16/rtcxxmod with flags -DKEEP_PR_BUILDS_FOR_A_DAY=On

**Comment by oshadura** [comment]
@phsft-bot build with flags -DKEEP_PR_BUILDS_FOR_A_DAY=On

**Comment by oshadura** [comment]
> Ah no, we can't do this, because failing node is used for releasing ROOT (on Ubuntu 16), so we can't install our own binaries directly there. @Axel-Naumann I think we can do exception here?

Axel told me that we can build zstd as a builtin in this case.

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The failure is 'lost connection' to worker so we don't know the actual result.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by fylux** [comment]
A small update about compressing dictionaries in ZSTD (TL;DR: Improvement when compressing large files with small dictionary)
https://github.com/facebook/zstd/issues/1694#issuecomment-545216804

**Comment by pcanal** [comment]
Good news!  Thanks.

**Pull request merged**
