### PR TITLE
[tree] raise error instead of crash when trying to access null GetTree

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:

Fixes https://its.cern.ch/jira/browse/ROOT-10390

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
Thanks.

**Comment by dpiparo** [comment]
Rerunning all builds on linux given the unfortunate crashes, not related to this work, but hopefully fixed. Thanks a lot for this PR @ferdymercury !!

**Review by dpiparo — APPROVED** [review]
LGTM too, provided that the Linux builds succeed.

**Comment by ferdymercury** [comment]
> LGTM too, provided that the Linux builds succeed.

Thanks! Looking green now.

**Comment by pcanal** [comment]
The errors are unrelated.

**Pull request merged**
