### PR TITLE
Integration of Qt5Web and CEF Web Displays for ROOT 7

### PR DESCRIPTION
**Pull request by amadio**
This supercedes #1623.

### CODE REVIEW

**Comment by amadio** [comment]
Thanks, @linev! My changes were just to make Qt4 and Qt5 work together.

**Comment by amadio** [comment]
Looks like there is a problem with the installation of Qt4 in the LCG externals...

**Comment by amadio** [comment]
I can reproduce the failures, something about Qt3Support. I will try to fix it and push again.

**Comment by amadio** [comment]
Haven't merged this yet since I still need to iron out a couple of issues I found during testing. Will merge when I manage to fix everything.

**Comment by linev** [comment]
@amadio 

Hi Guilherme.

Is it ready now? I already have two more PRs, which are waiting for this.

**Comment by amadio** [comment]
@linev I wanted to test the changes I made to QtGSI, but I will merge this now and port the examples later. I don't think that there is any problem with the code. Sorry for taking this long.

**Comment by amadio** [comment]
Just for future reference, Jenkins passed, but I rebased before pushing, so builds below will fail since they will not find the branch to build.

**Pull request merged**
