### PR TITLE
[DF] Fix crash in lazy jitted Snapshots

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by eguiraud** [comment]
Weird coincidence that the only test failure is in a test that uses TBufferMerger, but it should be completely unrelated to my changes.

**Comment by eguiraud** [comment]
@phsft-bot build

**Review by Axel-Naumann — APPROVED** [review]
NB and mostly unrelated, the ABI issue (and the need to do the alloc+dealloc outside the JIT) might have been fixed in llvm9, if we are lucky?

**Comment by eguiraud** [comment]
> the ABI issue (and the need to do the alloc+dealloc outside the JIT) might have been fixed in llvm9, if we are lucky?

This shared_ptr-on-heap trick we use is not to work around ABI issues but to resolve a lifetime issue: we need objects created by compiled code to stay alive at least until jitting time (which in RDF happens lazily), so we keep them around in heap-allocated shared_ptrs and when both compiled code and jitted code is done with them they are destructed.

It would be more elegant to guarantee that lifetimes are consistent "by design" if possible, but I could not think of a way.

**Pull request merged**
