### PR TITLE
Improve arrow support

### PR DESCRIPTION
**Pull request by ktf**
Fix a number of brown paperbag bugs and add initial support for nested types, starting from List<T>, which gets mapped to RVec<T>.

### CODE REVIEW

**Comment by ktf** [comment]
Please let me know how you want to proceed, in particular:

* One PR / Three PR
* Start integration from bug fix branch / Start integration from master branch
* It would also be nice to bump arrow to 0.11.1

**Comment by dpiparo** [comment]
@ktf @amadio this is on hold until we get back Arrow on our nodes as at the moment we do not have the required coverage.

**Comment by ktf** [comment]
If there is anything I can do to help, let me know.

**Comment by amadio** [comment]
Well, it seems `build just on X` doesn't work after labels have changed names... I think it's time for a full overhaul of the Jenkins PR infrastructure.

**Comment by dpiparo** [comment]
@phsft-bot build  with flags -Dall=ON

**Comment by ktf** [comment]
Are the errors my fault?

**Comment by amadio** [comment]
> Are the errors my fault?

I don't think so. Let's get master clean before rerunning here. Maybe we need just `-Darrow=ON` on the right node instead of `-Dall=ON`, which might be showing some of the errors above.

**Comment by amadio** [comment]
@phsft-bot build with flags -Dall=ON

**Comment by amadio** [comment]
Let's see if this will be enough. If not I will add arrow in rootspi.

**Comment by dpiparo** [comment]
@ktf I notice you want to put these changes on top of 6.14. Can we try those in master before?

**Comment by dpiparo** [comment]
let's start with the master version of the PR.

**Comment by ktf** [comment]
#3277 is rebased on master.

**Comment by dpiparo** [comment]
@phsft-bot build with flags -Dall=ON

**Comment by amadio** [comment]
@phsft-bot build with flags -Darrow=ON -Dfail-on-missing=OFF

**Comment by dpiparo** [comment]
@phsft-bot build with flags -Darrow=ON -Dfail-on-missing=OFF

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -Darrow=ON -Dfail-on-missing=OFF

**Comment by amadio** [comment]
@Axel-Naumann @ktf maybe it's best to close this PR? PR #3277 is the same thing for master, and has been merged already.

**Comment by ktf** [comment]
Fine with me.

**Pull request closed without merging**
