### PR TITLE
[ntuple] Add missing RField signed char specialization

### LINKED ISSUE #16135: [ntuple] Cannot create RFieldBase for signed char
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Since last Friday's dev3LCG nightly (i.e. from 26/7) we cannot create a field for `signed char`. This used to work fine w/ the LCG dev3 nightly from 25/7.

Here is the error message:

```
Error in <TRint::HandleTermInput()>: ROOT::Experimental::RException caught: unknown type: signed char (unchecked RResult access!)
At:
  ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&, const std::string&, bool)::<lambda(const std::string&)> [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:629]
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&, const std::string&, bool) [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:852]
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::RFieldBase> > ROOT::Experimental::RFieldBase::Create(const std::string&, const std::string&) [/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx:592]

```

### Reproducer

To setup ROOT:
```
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
lsetup "asetup Athena,main--dev3LCG,latest"; # any version after r26 (inclusive)
```

To reproduce the error:
```
root [0] using namespace ROOT::Experimental;
root [1] auto field = RFieldBase::Create("foo", "signed char").Unwrap();
```

### ROOT version

dev3/Fri/ROOT/HEAD (from 26/7)

### Installation method

LCG dev3 nightly build

### Operating system

AlmaLinux release 9.4 (Shamrock Pampas Cat)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #16135

### CODE REVIEW

**Review by jblomer — APPROVED** [review]
LGTM. As a follow-up, we should check if other `signed <>` types need special treatment, too. At least when passed as a string.

**Review by hahnjo — CHANGES_REQUESTED** [review]
This is wrong, `signed char` is the same as `char`. All comments related to `RField<char>` apply.

**Comment by jblomer** [comment]
Is this true? According to https://en.cppreference.com/w/cpp/language/types: 
```
char — type for character representation which can be most efficiently processed on the target system (has the same representation and alignment as either signed char or unsigned char, but is always a distinct type). 
```

**Review by hahnjo — APPROVED** [review]
> Is this true? According to https://en.cppreference.com/w/cpp/language/types:
> 
> ```
> char — type for character representation which can be most efficiently processed on the target system (has the same representation and alignment as either signed char or unsigned char, but is always a distinct type). 
> ```

Oh ok... Can we have a comment next to `RIntegralTypeMap<signed char>` about this?

> As a follow-up, we should check if other `signed <>` types need special treatment, too. At least when passed as a string.

Before https://github.com/root-project/root/commit/4a2fca87c5d95b07d412617f4af641054398db4e `signed char` was the only type that was normalized to `char`. So as far as I understand now, this was wrong because https://en.cppreference.com/w/cpp/language/types goes on:
> The signedness of char depends on the compiler and the target platform: the defaults for ARM and PowerPC are typically unsigned, the defaults for x86 and x64 are typically signed.

**Comment by jblomer** [comment]
Ouch. Good point! So now it is the column representation we want. Should we add `kChar` to the list of deserialization types, at least temporarily?

**Comment by hahnjo** [comment]
Ah right, it's not only for writing but also for reading existing ntuples... Maybe we can check with ATLAS if it's a problem for them?

**Comment by jblomer** [comment]
@amete Can you comment? As is, files written before the patch cannot be read with a ROOT after the patch. Do we need to fix this?

**Comment by jblomer** [comment]
Maybe we anyway should enable reading into `signed char` from a `kChar` column, if only for automatic schema evolution. Users should be able to change a member from `char` to `signed char`, and it may be the simplest to enable this through the column representations rather than a field translation.

**Comment by amete** [comment]
Thanks a lot everyone!

Let me comment on the ATLAS question anyways. At this point we do all our reading/writing tests within consistent ROOT versions. So, breaking backward/forward compatibility wouldn't be an issue for us just yet (i.e. until we start writing official data, which is some ways ahead).

**Pull request merged**
