### PR TITLE
Eve-7 Add server status info (No.2)

### PR DESCRIPTION
**Pull request by alja**
## This Pull request:
* Add server status info
* Corrections in accessing table expression for derived classes
* Enable navigation to Lego view

It is a correction  to #9005

### CODE REVIEW

**Comment by alja** [comment]
@linev I made this PR without 2 unnecessary commits in #9005

**Comment by linev** [comment]
@phsft-bot build

**Comment by alja** [comment]
@linev I saw osx11  errors from the previous PR.  std::timespec is not defined there. An option is to use defines for Big Sur.

**Comment by linev** [comment]
Or you just missing some include?

**Comment by alja** [comment]
@linev Required includes are there. std::timespec is part of C++17. It should work on osx11. For the moment I used std::time for non linux systems.

**Comment by linev** [comment]
@phsft-bot build

**Comment by alja** [comment]
@linev I think the build errors are not related to this change.

**Review by linev — APPROVED** [review]

**Pull request merged**
