### PR TITLE
[RF] Update RooFit AD to support ATLAS and CMS Higgs combinations

### PR DESCRIPTION
**Pull request by guitargeek**
Update RooFit AD to support ATLAS and CMS Higgs combinations.

### CODE REVIEW

**Comment by guitargeek** [comment]
Reopened the PR with the "clean build" flag. This should hopefully fix the test failures on macOS.

I had this Idea because by chance I saw the same test failures on my own Arch Linux desktop when I did an incremental build where I updated the clad tag from 1.5 to master in between. It seems the re-build of clad didn't get triggered, which might have also happened on the CI.

**Comment by vgvassilev** [comment]
Are these changes not working with clad v1.5?

**Comment by guitargeek** [comment]
> Are these changes not working with clad v1.5?

Some of them. I have created a new PR that factors out the changes that work with v1.5, so that we can already merge these developments.

**Review by vgvassilev — APPROVED** [review]
LGTM! Perhaps we can improve a little the history of commits.

**Pull request merged**
