### PR TITLE
[GSoC][TMVA][SOFIE] Add GRU operator

### PR DESCRIPTION
**Pull request by axmat**
## This Pull request:
Development of the Gated Recurrent Unit operator for the Google Summer of Code project [Inference Code Generation for Recurrent Neural Networks](https://summerofcode.withgoogle.com/projects/#5885532631990272).
Depends on #8800 and #8881.

## Checklist:

- [ x] tested changes locally

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Review by lmoneta — APPROVED** [review]
Thank you Ahmat for adding the tests. 
The code looks good to me. If it is fine for the CI I will merge it !

**Comment by lmoneta** [comment]
@axmat The test is still failing. It works fine on my machine, so maybe it is due to an old protobuf version installed on that machine. I will investigate it.

**Comment by axmat** [comment]
Nice! Thank you Lorenzo.

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default,  ROOT-ubuntu18.04/default  with flags -Dtmva-sofie=On

**Review by lmoneta — CHANGES_REQUESTED** [review]
Hi @axmat 
I have found a couple of issues when testing the GRU with a PyTOrch generated model. 
Here is the patch fixing this:
https://github.com/lmoneta/root/commit/83e380a7201b06b3f8971384ad91ec9c6f93d2f3

Can you please apply it on top of your changes. 

There is also a warning in the generated code when also linear before reset is true. It is caused by this:
```
/home/moneta/rootgit/root-build/tmva/sofie/test/GRUBatchwise_FromROOT.hxx:86:11: warning: declaration of ‘previous_offset’ shadows a previous local [-Wshadow]
   86 |    size_t previous_offset = (seq - 1) * 18;
      |           ^~~~~~~~~~~~~~~
/home/moneta/rootgit/root-build/tmva/sofie/test/GRUBatchwise_FromROOT.hxx:71:10: note: shadowed declaration is here
   71 |   size_t previous_offset = (seq - 1) * 18;
```
If you have time, can you also please fix this one. If not I can apply these changes in a new PR on top of your commits. Please let me know
Thank you !

**Comment by axmat** [comment]
Hi @lmoneta,
Unfortunately, I will not be able to fix this issue soon. You can open a new PR on top of this one.
Thanks!

**Comment by lmoneta** [comment]
This PR is now included in #9930

**Pull request closed without merging**
