### PR TITLE
REve - Show only item idx in the first column of REveTable controller

### PR DESCRIPTION
**Pull request by alja**
# This Pull request:
Minor change in a table controller

## Changes or fixes:
Possible error on reloads of a page when elements are highlighted.

This PR fixes #

### CODE REVIEW

**Comment by alja** [comment]
@linev This PR has a minor change. Please check.

**Comment by linev** [comment]
Hi @alja, please check LGTM warning.
There is some typo in the code.

**Review by linev — CHANGES_REQUESTED** [review]
Something wrong here:

     for (let xri = 0; xri < xr.length; xri++) {
               let nv = parseFloat(xr[i]);
               if (!isNaN(nv)) {
                  rowData[r][ri] = nv;
               }
            }

Please check indicies usage

**Comment by alja** [comment]
@linev I have removed the oboslete part. That was a useful report. There was no runtime error because xr.length was undefined. Thanks!

**Review by linev — APPROVED** [review]

**Pull request merged**
