### PR TITLE
[cmake] Introduce build option -Dasserts

### LINKED ISSUE #6448: Disable NDEBUG for PR builds
I think we agree that we don't want the `NDEBUG` flag in PR builds but haven't decided on a solution to remove the flag.

### PR DESCRIPTION
**Pull request by stwunsch**
The flag is enabled by default for CMAKE_BUILD_TYPE=Debug and dev=ON and
has the effect that the -DNDEBUG flag is **not** attached to the
CMAKE_C_FLAGS and CMAKE_CXX_FLAGS.

Fixes #6448

I'll also add a sentence to the release notes before merging something. However, note that the default behaviour of ROOT has only changed for the `dev=ON` option, which has now asserts enabled. Do we like this or shall I remove it from the dev mode?

I can also take care of the infrastructure (aka rootspi) so that we actually define that flag for all interesting builds.

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
Perfect solution! LGTM!

**Comment by stwunsch** [comment]
@oshadura Now we've actually thought about using a proper `RootBuildOption` called `-Dasserts` to implement the same thing. What do you think? Build option or plain cmake variable (like the `ROOT_ENABLE_ASSERTS` above)?

**Comment by oshadura** [comment]
What do you think actually to merge it in a dev option? or you would like to have a separate one for builds and etc?

**Comment by stwunsch** [comment]
I would enable it with `-Ddev=ON` but I think we also want a separate handle, e.g., for benchmarking reasons.

**Comment by oshadura** [comment]
It could be added as a plain option (e.g. `asan` https://github.com/root-project/root/blob/master/cmake/modules/RootBuildOptions.cmake#L193), but if you will be OK to have it as a part of `dev`, I think it would be easier then to maintain one more option :) It is up to you!

**Comment by stwunsch** [comment]
Then I vote for the explicit option :) Another reason we want an option is that we can have defaults, which are always overwritten if the build option is set explicitely. This allows you to have a debug build without asserts, if you like.

**Review by Axel-Naumann — APPROVED** [review]

**Comment by stwunsch** [comment]
@phsft-bot build with `-Dasserts=ON`

**Comment by stwunsch** [comment]
@phsft-bot build with flags -Dasserts=ON

**Comment by stwunsch** [comment]
Such as discussed on mattermost: I've switched to a plain cmake option so that the flag does not get exposed as feature by `root-config`. However, this has the downside that (without additional boilerplate logic) the asserts are always on for `CMAKE_BUILD_TYPE=Debug` and `dev=ON`, no matter what you specify for `asserts`.

**Review by oshadura — APPROVED** [review]

**Pull request merged**
