### PR TITLE
Support PCRE2

### LINKED ISSUE #11395: Migrate to pcre2
### Explain what you would like to see improved

root uses pcre (8.45), while upstream no longer maintains or supports it. Fedora is in the process of actively removing pcre and moving to pcre2 (10.40). It would be extremely helpful if root could migrate to pcre2.

### PR DESCRIPTION
**Pull request by ellert**
# This Pull request:

Makes it possible to use PCRE2 as an alternative to PCRE

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #11395

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
What we (you, the ROOT team, the users) need to discuss is whether we can deprecate TPRegex altogether, given that std::regex is now (since C++17 is required, as a side effect of kicking out old compilers) guaranteed to be available. Or reimplement it using std:: regex.

Thoughts?

**Comment by ellert** [comment]
Some background:
https://fedoraproject.org/wiki/Changes/PcreDeprecation
https://bugzilla.redhat.com/show_bug.cgi?id=2128369

**Comment by andresailer** [comment]
pcre2 10.40 (as mentioned in #11395) already comes with a pcre2-config.cmake (https://github.com/PCRE2Project/pcre2/blob/pcre2-10.40/cmake/pcre2-config.cmake.in) file. Can that be used instead of adding FindPCRE2.cmake ?

**Comment by ellert** [comment]
> pcre2 10.40 (as mentioned in #11395) already comes with a pcre2-config.cmake (https://github.com/PCRE2Project/pcre2/blob/pcre2-10.40/cmake/pcre2-config.cmake.in) file. Can that be used instead of adding FindPCRE2.cmake ?

The packaged pcre2 in Fedora and RHEL/CentOS/Rocky/Alma does not ship the cmake files. They are only create/installed if pcre2 is built using cmake. The RPM for Fedora and RHEL are built using autotools, and therefore do not contain the cmake files.

**Comment by guitargeek** [comment]
Not adding this to the 6.32 milestone, since even Fedora rawhide still has the old pcre for now.

**Comment by guitargeek** [comment]
> What we (you, the ROOT team, the users) need to discuss is whether we can deprecate TPRegex altogether, given that std::regex is now (since C++17 is required, as a side effect of kicking out old compilers) guaranteed to be available. Or reimplement it using std:: regex.
> 
> Thoughts?

I wouldn't go into this direction yet. We have a couple of problems with `std::regexp`, like these symbol clashes with other Python libraries:
https://github.com/root-project/root/issues/15309

Therefore, provided that it's tested, I'm in favor of merging this PR. I'm adding pcre2 to the CI images, so that we can test it:
https://github.com/root-project/root-ci-images/pull/31

**Review by guitargeek — APPROVED** [review]
Amazing! We can see in the CI that it works:
```txt
  -- Looking for PCRE
  -- Found PCRE2: /usr/include (found version "10.32") 
```

**Pull request merged**
