### PR TITLE
[cppyy] [from upstream] implicit conversion from a tuple of arguments

### PR DESCRIPTION
**Pull request by ianna**
# This Pull request:

back port to allow `__cast_cpp__ `to return tuple for an implicit temporary if a temporary can be accepted by C++

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by jalopezg-git** [comment]
@ianna, it seems that there's merge conflicts and CI cannot proceed.  I see that this is WIP, so disregard if you are aware/working on it.

**Comment by ianna** [comment]
@wlav, @vgvassilev, @jpivarski - FYI

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
Hi @ianna ,

Thanks a lot for the PR, and very much sorry for taking so long in giving the first reply!

Just to give a bit more context, other than the direct goal of the commit, what is the usecase this serves? If it is a backport, can you maybe point at the commit you are bringing from upstream in the commit description?

**Comment by ianna** [comment]
> Hi @ianna ,
> 
> Thanks a lot for the PR, and very much sorry for taking so long in giving the first reply!
> 
> Just to give a bit more context, other than the direct goal of the commit, what is the usecase this serves? If it is a backport, can you maybe point at the commit you are bringing from upstream in the commit description?

Hi @vepadulano,
This is a commit cherry-picked from upstream. A user would be able to do similar to the following (e.g. map a C++ type to a Python type):
```python
array = ak.Array(
  [
    [{"x": 1, "y": [1.1]}, {"x": 2, "y": [2.2, 0.2]}],
    [],
    [{"x": 3, "y": [3.0, 0.3, 3.3]}],
  ]
)

source_code_cpp = """
template<typename T>
double go_fast_cpp(T& awkward_array) {
 double out = 0.0;
 
 for (auto list : awkward_array) {
   for (auto record : list) {
     for (auto item : record.y()) {
       out += item;
     }
   }
 }

 return out;
}
"""
cppyy.cppdef(source_code_cpp)

out = cppyy.gbl.go_fast_cpp[array.cpp_type](array)
```

**Comment by Axel-Naumann** [comment]
@vepadulano objections against merging?

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
I went and searched for this commit upstream, it is https://github.com/wlav/CPyCppyy/commit/eec92e53af6e8eb0c89fe27332cdc23179059bb7 . It seems that this commit alone would break our fork, as the CI also reports, since some things are missing. For example, the `ISCONST` template parameter of the class `InstancePtrConverter` is not present on our side https://github.com/root-project/root/blob/1d65f2ecf42f9fc38e300515e8bcf1593f0068ff/bindings/pyroot/cppyy/CPyCppyy/src/Converters.h#L51 whereas it is present upstream https://github.com/wlav/CPyCppyy/blob/1a2589fdccd31fac875b6d6bf5adb71e3bef8a4b/src/Converters.h#L54 .

This means that I have to dig into upstream and understand how many commits are necessary to land this one in our side. It may take a while, not sure.

**Comment by vepadulano** [comment]
After a first search, this is a non exhaustive list of commits that are needed *before* the commit of this PR could be applied to our fork:

1.  https://github.com/wlav/CPyCppyy/commit/23a397f464bb1b706f5ef87a4c439a7fb6e3a301 : changes in `Converters.cxx:SelectInstanceCnv`
2. https://github.com/wlav/CPyCppyy/commit/3d263f5f0d8617d1c21ad6bc3d76242e6e994a9a : changes in `Converters.cxx:SelectInstanceCnv`
3. https://github.com/wlav/CPyCppyy/commit/b9dbb2057a9249f770d6f5bab2d095882bd3b755 : changes in `Converters.h` (template argument `ISCONST` of the class `InstancePtrConverter`),  changes in `Converters.cxx` (implementations of the methods of `InstancePtrConverter` class and changes in `SelectInstanceCnv` function)

And these are definitely not enough to reach synchronisation with the chain of commits that would bring our fork to the correct state for introducing the commit of this PR.

@ianna I'll let you decide if you want to trace back all the commits needed to apply the one in this PR and then we could revisit it again.

Otherwise, this will have to wait for a full rebase on upstream

**Comment by ianna** [comment]
> After a first search, this is a non exhaustive list of commits that are needed _before_ the commit of this PR could be applied to our fork:
> 
> 1. [wlav/CPyCppyy@23a397f](https://github.com/wlav/CPyCppyy/commit/23a397f464bb1b706f5ef87a4c439a7fb6e3a301) : changes in `Converters.cxx:SelectInstanceCnv`
> 2. [wlav/CPyCppyy@3d263f5](https://github.com/wlav/CPyCppyy/commit/3d263f5f0d8617d1c21ad6bc3d76242e6e994a9a) : changes in `Converters.cxx:SelectInstanceCnv`
> 3. [wlav/CPyCppyy@b9dbb20](https://github.com/wlav/CPyCppyy/commit/b9dbb2057a9249f770d6f5bab2d095882bd3b755) : changes in `Converters.h` (template argument `ISCONST` of the class `InstancePtrConverter`),  changes in `Converters.cxx` (implementations of the methods of `InstancePtrConverter` class and changes in `SelectInstanceCnv` function)
> 
> And these are definitely not enough to reach synchronisation with the chain of commits that would bring our fork to the correct state for introducing the commit of this PR.
> 
> @ianna I'll let you decide if you want to trace back all the commits needed to apply the one in this PR and then we could revisit it again.
> 
> Otherwise, this will have to wait for a full rebase on upstream

Thanks, @vepadulano ! I'll check how much work it is to synchronise it.

**Comment by Axel-Naumann** [comment]
Does this mean the corresponding commit(s) to master should be reverted until this is solved? I'm a bit lost - do we have a feature test that works in master thanks to the corresponding PR but didn't work before? How is this PR here so different?

**Comment by Axel-Naumann** [comment]
We use the term "backport" when merging something from master to release branches, that confused me a couple of times here :-) I renamed the PR to "[from upstream]" to confuse me less, sorry about that!

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
As a PR that cherry picks commits from CPyCppyy, this is superseeded by:
https://github.com/root-project/root/pull/14507

**Pull request closed without merging**
