### PR TITLE
Revert another LLVM patch

### PR DESCRIPTION
**Pull request by hahnjo**
Replace it by two proper backports of https://reviews.llvm.org/D142352 and https://reviews.llvm.org/D142443.

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by hahnjo** [comment]
Alright, I think I managed to hunt down and fix the underlying issues that required removing the `assert` and disabling the IR verifier: https://reviews.llvm.org/D142352 and https://reviews.llvm.org/D142443 Assuming these go through upstream, we could either revert the "hacky" LLVM patch (and replace it by two backports for LLVM 13), or just wait for the next LLVM upgrade (and close this PR). What do you think @Axel-Naumann @vgvassilev?

**Comment by vgvassilev** [comment]
> Alright, I think I managed to hunt down and fix the underlying issues that required removing the `assert` and disabling the IR verifier: https://reviews.llvm.org/D142352 and https://reviews.llvm.org/D142443 Assuming these go through upstream, we could either revert the "hacky" LLVM patch (and replace it by two backports for LLVM 13), or just wait for the next LLVM upgrade (and close this PR). What do you think @Axel-Naumann @vgvassilev?

I'd prefer to replace the hacky patch with the backports as they are now. This way we have at least one more source to track what happened to the particular issue. If they end up closed there will be a reason or an alternative which will make it easier to get rid of the non-merged backport patch.

**Comment by hahnjo** [comment]
> I'd prefer to replace the hacky patch with the backports as they are now. This way we have at least one more source to track what happened to the particular issue. If they end up closed there will be a reason or an alternative which will make it easier to get rid of the non-merged backport patch.

Ok, noted. I propose I go ahead with the migration of the patches to a fork of the monorepo and we do this afterwards.

**Comment by vgvassilev** [comment]
> > I'd prefer to replace the hacky patch with the backports as they are now. This way we have at least one more source to track what happened to the particular issue. If they end up closed there will be a reason or an alternative which will make it easier to get rid of the non-merged backport patch.
> 
> Ok, noted. I propose I go ahead with the migration of the patches to a fork of the monorepo and we do this afterwards.

Sure, that's over to you. My only suggestion would be to write down the exact procedure once we are done so that we can follow it more consistently.

**Review by vgvassilev — APPROVED** [review]

**Comment by hahnjo** [comment]
Ok, all platforms seem to be working fine (in particular Windows) - the failure on Ubuntu 20.04 looks unrelated. I will wait for https://github.com/root-project/root/pull/12117 to be approved and merged, then rebase this PR and update the tag referencing the monorepo.

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3.

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-ubuntu2004/python3

**Comment by hahnjo** [comment]
Now ZeroMQ has a hash mismatch. This is getting annoying, I'm merging this without passing Ubuntu 20.04.

**Pull request merged**
