### PR TITLE
Ref guide version changer

### PR DESCRIPTION
**Pull request by couet**
Reference guide version changer. first try. Needs more test and tuning.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
> Needs more test and tuning.

Like what?

**Comment by couet** [comment]
To include the version changer the only file to be modified is htmlheader.html. I included there the code you sent me. When I install the doc locally on my machine, with this modified header, I get the following picture:

Screenshot 2020-06-22 at 13 04 35

Two issues:
   1. the layout is ugly
   2. the "version changing" does not work.

**Comment by Axel-Naumann** [comment]
Better now, @couet ? Are we ready with this?

**Comment by couet** [comment]
I will put the new button's look in that PR.

**Comment by couet** [comment]
The look is fine. I think, if you approve, we can push it.

**Pull request merged**
