### PR TITLE
WebGui: implementation of ROOT6 TCanvas painter with RWebWindow/JSROOT

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON -Dcxx14=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by dpiparo** [comment]
Hi @linev: that was fast, congrats. For this code, @couet is of course the best reviewer. Nevertheless I wonder if:
- Doxygen doc can be embedded from the start (it is in some places and it is not in others). In addition this is *the* opportunity to comment a backend properly.
- The code can be clang-formatted
- The copyright statemets can be made uniform
- The 70 commits are the right granularity (is the code compiling for each one of them?)
- The guards such as https://github.com/root-project/root/pull/2780/files#diff-6865e4d715d527b6e139711e517617baR22 can be removed since we concluded they are useless
- ClassDef and ClassImp are needed
- The globbing of headers in the CMakeLists can be replaced by the explicit list (https://github.com/root-project/root/pull/2780/files#diff-9e914a256e005f48875c44e6aa1938faR5)
- We need all these dictionaries and with streamers: https://github.com/root-project/root/pull/2780/files#diff-7ddd3257f2c65c9447eeb3aa2a14bcb5R1
- The code needs yet another read (https://github.com/root-project/root/pull/2780/files#diff-7f91457bd372590be2853b22673fd59dR169 , https://github.com/root-project/root/pull/2780/files#diff-7f91457bd372590be2853b22673fd59dR216)

With my comments above, I absolutely do not want to slow you down but perhaps try and reduce the future maintenance code with a minimal investment today.

**Comment by linev** [comment]
@dpiparo 

> Doxygen doc can be embedded from the start (it is in some places and it is not in others). 
> In addition this is the opportunity to comment a backend properly.

Yes. Some of code was copy-pasted before Olivier redo doxygen formatting.
Now we need to do the same with that code

> The code can be clang-formatted

If it really needed - I can do this.  I prefer to use it only for new commits.

> The copyright statemets can be made uniform

That is best example? In ROOT sources there are many variants.

> The guards ... are useless

Ok. This can be removed

> ClassDef and ClassImp are needed

I have them for TObject-derived classes. Do we need them for others?

> The 70 commits are the right granularity (is the code compiling for each one of them?)

Yes, all commits can be compiled - when rallback to appropriate date all other used ROOT classes.

> We need all these dictionaries and with streamers:

Yes, these are objects exchanged between server and clients. I uses JSON conversion for them

> The globbing of headers in the CMakeLists can be replaced by the explicit list 

Ok. I will check which headers are really needed.

> The code ... needs yet another read 

This is wrapper for TVirtualX - some objects painters (including TCanvas) doing sometime direct X11 calls. Some of them I block, another map into SVG

> I absolutely do not want to slow you down but perhaps try and reduce the future maintenance cost with a minimal investment today.

Most of the comments can be resolved by Olivier @couet We will discuss tomorrow how to proceed 

> that was fast

It is result of approx 18 months of work

**Comment by linev** [comment]
@dpiparo 

> Doxygen doc can be embedded from the start (it is in some places and it is not in others). 
> In addition this is the opportunity to comment a backend properly.

Yes. Some of code was copy-pasted before Olivier redo doxygen formatting.
Now we need to do the same with that code

> The code can be clang-formatted

If it really needed - I can do this.  I prefer to use it only for new commits.

> The copyright statemets can be made uniform

That is best example? In ROOT sources there are many variants.

> The guards ... are useless

Ok. This can be removed

> ClassDef and ClassImp are needed

I have them for TObject-derived classes. Do we need them for others?

> The 70 commits are the right granularity (is the code compiling for each one of them?)

Yes, all commits can be compiled - when rallback to appropriate date all other used ROOT classes.

> We need all these dictionaries and with streamers:

Yes, these are objects exchanged between server and clients. I uses JSON conversion for them

> The globbing of headers in the CMakeLists can be replaced by the explicit list 

Ok. I will check which headers are really needed.

> The code ... needs yet another read 

This is wrapper for TVirtualX - some objects painters (including TCanvas) doing sometime direct X11 calls. Some of them I block, another map into SVG

> I absolutely do not want to slow you down but perhaps try and reduce the future maintenance cost with a minimal investment today.

Most of the comments can be resolved by Olivier @couet We will discuss tomorrow how to proceed 

> that was fast

It is result of approx 18 months of work

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build just on windows10/vc15  with flags -Droot7=ON

**Pull request merged**
