### PR TITLE
Windows: Fix pointer formatting in Eve7

### PR DESCRIPTION
**Pull request by bellenot**
Make sure hexadecimal pointer values have the correct '0x' prefix (not automatic on Windows)

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Can we please use a `stringstream` instead?

**Comment by bellenot** [comment]
> Can we please use a `stringstream` instead?

Done, thanks for the suggestion

**Comment by linev** [comment]
@bellenot 
Bertrand, would be ok if we apply #3466 first? Then we need to rebase this PR.

**Comment by bellenot** [comment]
> @bellenot
> Bertrand, would be ok if we apply #3466 first? Then we need to rebase this PR.

@linev No problem!

**Comment by linev** [comment]
@bellenot I finish refactoring of eve7 code. Now one can apply your Windows patch - after rebasing it

**Comment by bellenot** [comment]
I got conflicts, so I close this PR and will open a new one

**Pull request closed without merging**
