### PR TITLE
Moved TMath's fundamental constants to TMathBase

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by vgvassilev** [comment]
It seems most of the inlines could turn into constexprs.

**Comment by xvallspl** [comment]
Yes, I didn't want to touch that much.

No problem in doing it, If you agree.

**Comment by vgvassilev** [comment]
This looks good to me, modulo the clang-format unhappiness.

**Comment by lmoneta** [comment]
I don;t agree with this PR. 
 I think Math constants should remain in Math.h and stays in Mathcore. TMathBase should be minimal and not contain those math constants. 

I see this is done only for a use of TMath::Pi in TTimeStamp.  I would just hardcoded there and avoid this PR

 Lorenzo

**Comment by xvallspl** [comment]
This won't be applied

**Pull request closed without merging**
