### PR TITLE
[DF] Add tests for RNTupleDS + RVecs

### PR DESCRIPTION
**Pull request by eguiraud**
These tests are expected to fail at the moment. RNTupleDS needs a little tweak to use RRVecField instead of RVectorField to read collections.

Re-test and merge after #10623 is in.

### CODE REVIEW

**Review by jblomer — APPROVED** [review]

**Comment by eguiraud** [comment]
@phsft-bot build

**Comment by eguiraud** [comment]
@phsft-bot build please

**Comment by jblomer** [comment]
@phsft-bot build

**Comment by eguiraud** [comment]
@jblomer the failure at https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/145821/testReport/projectroot.tree.dataframe/test/gtest_tree_dataframe_test_datasource_ntuple/ seems real -- we get a different type name for mac 11..?

**Comment by jblomer** [comment]
> @jblomer the failure at https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/145821/testReport/projectroot.tree.dataframe/test/gtest_tree_dataframe_test_datasource_ntuple/ seems real -- we get a different type name for mac 11..?

Looking into it.

**Comment by jblomer** [comment]
@eguiraud Looks like an issue with the test. The expected typename is the normalized one, `ROOT::VecOps::RVec<std::int32_t>`. Could you adjust the test and rebase?

**Comment by eguiraud** [comment]
oooh all PR builds except mac11 are C++14!

**Comment by eguiraud** [comment]
Done!

**Pull request merged**
