### PR TITLE
[DF] Rename the members of REntryRange

### PR DESCRIPTION
**Pull request by ikabadzhov**

### CODE REVIEW

**Comment by eguiraud** [comment]
The struct is called REntryRange so the members can just be fBegin and fEnd can they not?

**Comment by vepadulano** [comment]
I agree with Enrico, also check whether there's any usage of `start entry` or similar in the docs

**Comment by ikabadzhov** [comment]
> The struct is called REntryRange so the members can just be fBegin and fEnd can they not?

I just changed the members inside of the struct. Then RLoopManager has `fBeginEntry` and `fEndEntry`.

**Review by vepadulano — APPROVED** [review]
Thank you!

**Pull request merged**
