### PR TITLE
[TMVA][SOFIE] Add batch normalization operator

### PR DESCRIPTION
**Pull request by lmoneta**
Add the new operator developed by Aaradhya Saxena.

This PR extends #8882 and updates to the new Session class of Sofie. 
It includes also the test for Batch normalization operator

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Review by sitongan — APPROVED** [review]

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by hahnjo** [comment]
@lmoneta for future commits, can you please leave an empty line between the subject (first line) and the commit description (starting in line 3)? Having text in the second line makes `git log --oneline` horrible to read because git thinks that the entire commit message is the subject...

**Comment by lmoneta** [comment]
You are right ! Sorry for this, I have never used `git log --oneline`.

**Pull request merged**
