### PR TITLE
Update masses of Omega_c0 and Xi_cc++ according to PDG 2022

### PR DESCRIPTION
**Pull request by vkucera**
See:

- https://pdg.lbl.gov/2022/listings/rpp2022-list-omegac-zero.pdf
- https://pdg.lbl.gov/2022/listings/rpp2022-list-xicc-plus-plus.pdf

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks - I bet there are many other missing and outdated particle properties. Do you have a suggestion how to fix "everything"?

**Comment by vkucera** [comment]
> Thanks - I bet there are many other missing and outdated particle properties. Do you have a suggestion how to fix "everything"?

Hi @Axel-Naumann , One can parse the file `https://pdg.lbl.gov/2023/mcdata/mass_width_2023.txt` to update masses of some particles in a more automated way, but it does not cover other particle properties nor all particle masses (e.g. Xi_cc++ is missing).

The page https://pdg.lbl.gov/2023/html/computer_read.html also mentions available APIs and SQLite files for accessing the full database. This could be the best way to systematically compare the two databases and update everything. This kind of access is provided for testing only though so might require manual check of the found differences.

**Comment by Axel-Naumann** [comment]
Thanks for digging up that info!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by vkucera** [comment]
> Thanks for digging up that info!

No problem. I would leave that task to someone more competent though. Are you fine with merging this PR for now?

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
Thanks for your contribution, code and "PDG research" :-)

**Pull request merged**
