### PR TITLE
Added recursive print depth meta command.

### PR DESCRIPTION
**Pull request by perovic**
Implemented corresponding print behavior.
Maybe revise this meta command's behavior in the case of a missing argument (print out the current value, instead of toggling between two defaults), if it turns out to be more intuitive.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Not sure about the rationale here but could you rebase and add a test case for this functionality?

**Comment by vgvassilev** [comment]
@Axel-Naumann, shall we close this due to inactivity?

**Comment by etejedor** [comment]
@Axel-Naumann what should we do with this one?

**Comment by etejedor** [comment]
@Axel-Naumann should we close this one?

**Comment by etejedor** [comment]
At the risk of being repetitive :grin:  @Axel-Naumann can we close this one?

**Comment by Axel-Naumann** [comment]
Let's close - we keep the code in this PR, but for now there has not been a lot of demand for the feature :-)

**Pull request closed without merging**
