### PR TITLE
[DOC] Update release notes for RDF+TTreeProcessorMT

### PR DESCRIPTION
**Pull request by bluehood**
Should we mention @stwunsch 's nanoaod tutorials? Are we missing anything else?

### CODE REVIEW

**Comment by bluehood** [comment]
(is there a way to stop the PR build? :smile: )

**Comment by Axel-Naumann** [comment]
Log in to Jenkins, hit the ❌ next to the progress bar for that build. Done that!

**Comment by bluehood** [comment]
@stwunsch should I add a line about the nice nanoAOD tutorials?

**Comment by bluehood** [comment]
@dpiparo I think we can merge this?

**Pull request merged**
