### PR TITLE
[ntuple] Split `RField.hxx` header

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Comment by jblomer** [comment]
I like the splitting! We should line up this PR with the follow-up of on-disk support for multi column representations. The follow-up makes some larger changes to the RField classes.

**Comment by silverweed** [comment]
For ease of searching, I suggest renaming files like `RField/Fundamental.hxx` -> `RField/RFieldFundamental.hxx`

**Comment by hahnjo** [comment]
> For ease of searching, I suggest renaming files like `RField/Fundamental.hxx` -> `RField/RFieldFundamental.hxx`

Done. For now we keep the invariant that the split headers may only be included via `RField.hxx`, with the exception of `RFieldBase.hxx`.

**Review by jblomer — APPROVED** [review]
LGTM. The remaining clang-format errors should probably be fixed.
Do we want to leave the left-over stuff in RField.hxx or eventually move it do a different header, too?

**Review by jblomer — COMMENTED** [review]
One thing I overlooked: the new headers need to become part of the CMakeLists.txt, I think

**Comment by hahnjo** [comment]
> LGTM. The remaining clang-format errors should probably be fixed.

Ok, it seems to be a difference between my local `clang-format` version and what we have in the GitHub action...

> Do we want to leave the left-over stuff in RField.hxx or eventually move it do a different header, too?

I'm not sure yet. Ideally it would be cool if `RField.hxx` only only had a base `template <typename T> RField` and then a couple of `#include`. However that will be difficult because of the base case of `RClassField`... To be seen in the future.

> One thing I overlooked: the new headers need to become part of the CMakeLists.txt, I think

I tried this initially, but it didn't work: I think all headers listed in `CMakeLists.txt` are treated as top-level header for the module. We don't want this for the split `RField` headers...

**Pull request merged**
