### PR TITLE
[cppyy] [backport] support __cast_cpp__ to implicitly convert python objects to proxies

### LINKED ISSUE #12579: [backport] support __cast_cpp__ to implicitly convert python objects to proxies
- [x] Checked for duplicates

### Describe the bug

`ROOT` and latest` cppyy 3.0.1` cannot be used in the same virtual environment.

### Expected behavior

Please, consider back porting the feature needed from `cppyy 3.0.1`:
https://github.com/wlav/CPyCppyy/commit/6c7ca2547347b7bea8e49c7f2337fa9fb0455186

### PR DESCRIPTION
**Pull request by ianna**
# This Pull request:

back-ports support __cast_cpp__ to implicitly convert python objects to proxies

## Changes or fixes:

cherry-picked https://github.com/wlav/CPyCppyy/commit/6c7ca2547347b7bea8e49c7f2337fa9fb0455186

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #12579

### CODE REVIEW

**Comment by ianna** [comment]
@wlav and @jpivarski - FYI

**Review by Axel-Naumann — CHANGES_REQUESTED** [review]
Thanks, @ianna !

- Could you please rewrite the history to combine the two commits?
- I don't see `gAnnotations` and `gCType` being read anywhere. I suspect that they are not needed and artifacts of a failed merge?

**Comment by ianna** [comment]
> Thanks, @ianna !
> 
> * Could you please rewrite the history to combine the two commits?

Thanks, @Axel-Naumann. I'll do that.

> * I don't see `gAnnotations` and `gCType` being read anywhere. I suspect that they are not needed and artifacts of a failed merge?

No, I think, these are the new features from @wlav's master branch. I think, they are harmless :-)
but I'll leave it to @wlav to comment.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by ianna** [comment]
Ok, I see the patch needs `PyObject_CallMethodNoArgs` that is new in version 3.9. Which one is the minimum Python requirement for ROOT?

**Comment by wlav** [comment]
See [here](https://github.com/wlav/CPyCppyy/blob/master/src/CPyCppyy.h#L361) for the compatibility code.

**Review by ianna — COMMENTED** [review]
@Axel-Naumann - a Python version check is added and extra variables removed as suggested by @wlav. Please, let me know if you'd like me to squash the commits. Thanks!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by wlav** [comment]
@ianna, this is the implicit conversion from a tuple of arguments: https://github.com/wlav/CPyCppyy/commit/eec92e53af6e8eb0c89fe27332cdc23179059bb7

It is only accepted for C++ functions that are temporaries (const ref, by value, move), whereas returning a proxy object directly works in all cases except moves. In principle I could make both work in all cases, but this seems to be more logical, especially since methods could be overloaded.

**Comment by ianna** [comment]
> @ianna, this is the implicit conversion from a tuple of arguments: [wlav/CPyCppyy@eec92e5](https://github.com/wlav/CPyCppyy/commit/eec92e53af6e8eb0c89fe27332cdc23179059bb7)
> 
> It is only accepted for C++ functions that are temporaries (const ref, by value, move), whereas returning a proxy object directly works in all cases except moves. In principle I could make both work in all cases, but this seems to be more logical, especially since methods could be overloaded.

Fantastic! Thanks, @wlav!

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
Thanks, @ianna and @wlav !

**Pull request merged**
