### PR TITLE
[metacling] Switch default cling optimization for ROOT to -O1.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
# This Pull request:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Review by eguiraud — APPROVED** [review]
LGTM

**Comment by Axel-Naumann** [comment]
@vgvassilev 

User CPU time, 2nd run of all tests:

test | opt | non-opt
-----|-----|--------
stressGeometry.cxx | 20.10 | 19.36
stressHistogram.cxx | 16.52 | 15.89
stressGraphics.cxx | 57.68 | 16.13

stressGraphics generates code that's full of virtual function calls. This used to explode; a factor 4 is still terrible but given that this is on the "awkward" side of our legacy code likely a price we need to pay.

**Comment by vgvassilev** [comment]
> @vgvassilev
> 
> User CPU time, 2nd run of all tests:
> test 	opt 	non-opt
> stressGeometry.cxx 	20.10 	19.36
> stressHistogram.cxx 	16.52 	15.89
> stressGraphics.cxx 	57.68 	16.13
> 
> stressGraphics generates code that's full of virtual function calls. This used to explode; a factor 4 is still terrible but given that this is on the "awkward" side of our legacy code likely a price we need to pay.

The question is how many tutorials and code such as stressGraphics.cxx we have, and more importantly how much of the experiments/users use that style of coding/interfaces.

**Comment by Axel-Naumann** [comment]
I know the question, but I don't think anyone knows the answer. The code that gets slowed down is vtable-heavy code (at least I think that's the symptom), i.e. "legacy" code. We need to motivate people to migrate to today's code, so that's what we should be optimize for. We are not making legacy code impossible, but we are indeed pessimizing it. I'd be happy :-) to have someone with `opt` knowledge figure out which pass it is that blows up. Maybe @hahnjo could give us a hand?

**Comment by Axel-Naumann** [comment]
@vgvassilev do you object to me merging? I'd want to see this exposed to users earlier rather than later, to hear feedback before we tag v6.26. I have opened an issue https://github.com/root-project/root/issues/9312 to keep track.

**Comment by vgvassilev** [comment]
> @vgvassilev do you object to me merging? I'd want to see this exposed to users earlier rather than later, to hear feedback before we tag v6.26. I have opened an issue #9312 to keep track.

No objections. What I'd like to understand is how much code regressed. But also, is the performance benefit significant outside of RDF. Both probably require more field testing...

I suspect that for many cases we will be okay. There will be a number of regressed cases. What is unclear is how many are going to be the significantly improved cases. I believe for RDF we control the environment and compile even with -O2.

**Pull request merged**
