### PR TITLE
Test PR for R__COMPLETE_MEM_TERMINATION

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION"

**Comment by Teemperor** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by Teemperor** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

And please don't die before you submit the CDash report...

**Comment by martinmine** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by Teemperor** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by Teemperor** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build with flags -DCMAKE_CXX_FLAGS="-DR__COMPLETE_MEM_TERMINATION" -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build just on slc6/gcc49 with flags -Dvc=OFF -Dimt=ON -Dccache=OFF

**Comment by martinmine** [comment]
@phsft-bot build just on slc6/gcc49 with flags -Dvc=OFF -Dimt=ON -Dccache=OFF

**Pull request closed without merging**
