### PR TITLE
[ntuple] Enforce valid naming upon field creation

### LINKED ISSUE #16834: `RFieldBase::Create` does not enforce valid field names
### Check duplicate issues.

- [X] Checked for duplicates

### Description

`RFieldBase::Create` doesn't check whether the provided name of the created field is valid, this only happens in `RNTupleModel::[Add|Make]Field. This means that currently, it is possible to create field names containing dots in this way.

### Reproducer

```cpp
auto field = RFieldBase::Create("x.y", "float").Unwrap();
std::cout << field->GetFieldName() << std::endl;
```

### ROOT version

any

### Installation method

any

### Operating system

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by enirolf**
Before, field name checking only took place in `RNTupleModel`. This PR performs the check upon construction of the `RFieldBase`. To still allow for special cases where fields can have an empty name, e.g. the zero field, this specific check has been moved out of `RFieldBase::EnsureValidFieldName` and to the places where this should actually be enforced.

Fixes #16834

### CODE REVIEW

**Review by vepadulano — APPROVED** [review]
Thank you!

**Review by jblomer — APPROVED** [review]
Thanks! Looks in principle good to me. We can still clone though to the empty name, I think?

**Comment by enirolf** [comment]
> We can still clone though to the empty name, I think? Probably that's ok. 

Yes, that's correct. In fact, that is necessary for (among others) `RNTupleDS` to work properly.

> The precise rule is that field names must not be empty _on disk_ but can be empty in memory.

Exactly, this responsibility is now moved to `RFieldDescriptorBuilder`.

**Comment by vepadulano** [comment]
> The precise rule is that field names must not be empty on disk but can be empty in memory. 

I will add this to https://github.com/root-project/root/pull/16813

**Pull request merged**
