### PR TITLE
[rdrawable] add destructor for HistDrawable

### PR DESCRIPTION
**Pull request by linev**
Not sure, but may help on Windows

### CODE REVIEW

**Comment by linev** [comment]
Bertrand, you have to try code on your machine. I am not sure if I con convince `Jenkins` to build with root7.

**Comment by linev** [comment]
@phsft-bot build with flags -DCMAKE_CXX_STANDARD=14 -Droot7=ON

**Comment by bellenot** [comment]
Still the same error...

**Comment by bellenot** [comment]
See the [PR #4457](https://github.com/root-project/root/pull/4457)

**Pull request closed without merging**
