### PR TITLE
Refactor of test/stressMathCore.cxx to use Google Test

### PR DESCRIPTION
**Pull request by martinmine**
Basic refactoring of test/stressMathCore.cxx to be smaller, more manageable files, and to use Google Test. The functionality is the same, but is now using Google Test for assertions instead of doing logical operations on an integer as the test result.

Ping @lmoneta

### CODE REVIEW

**Comment by vgvassilev** [comment]
It seems there are a few clang-format and clang-tidy issues. Could you address them, too?

**Comment by martinmine** [comment]
@vgvassilev Fixed in commit https://github.com/root-project/root/pull/594/commits/6cf326d88a82ae3af9067e7a9f6aa5e4a61a1180, thanks.

**Comment by vgvassilev** [comment]
What about the clang-tidy issue?

**Comment by martinmine** [comment]
@vgvassilev Sorry, I thought it was fixed as the build passed so I didn't dive into the console logs of it. Anyhow, as far as I understand, the only issue it complains about is that `root/math/mathcore/test/stress/TestHelper.cxx:33:20` is never reached, which I find unreasonable. Do you think this could be a false flag, or something I should look more into?

**Comment by vgvassilev** [comment]
It comes from an 'alpha' checker and think it is a false positive.

**Pull request merged**
