### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by amadio** [comment]
Why reverting the previous fix?

**Comment by vgvassilev** [comment]
It didn't work, at least for recent clang.

**Comment by amadio** [comment]
Yes, but there is not need to revert at least the `extern C` stuff, don't you agree?

**Comment by vgvassilev** [comment]
Well, including headers in extern "C" is considered as a bad practice. Such inclusion becomes a warning/error for modules builds. I'd rather reduce such cases (esp when they are no op) than keep piling them up.

**Comment by amadio** [comment]
> Well, including headers in extern "C" is considered as a bad practice.

Even for C headers? In any case, if it's problematic for the modules builds, then reverting is the best solution.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
