### PR TITLE
add missing GL includes in FTGL, v6.18  [ROOT-10631]

### PR DESCRIPTION
**Pull request by linev**
Backport to v6.18

### CODE REVIEW

**Comment by oshadura** [comment]
One more update from forum:

` 98%] Linking CXX shared library …/…/lib/libRGL.so

ld: library not found for -lGLEW

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [lib/libRGL.so] Error 1

make[1]: *** [graf3d/gl/CMakeFiles/RGL.dir/all] Error 2

make: *** [all] Error 2`

**Comment by oshadura** [comment]
Can you add please dependency on ${OPENGL_LIBRARIES}?

**Comment by linev** [comment]
> Can you add please dependency on ${OPENGL_LIBRARIES}?

Seems to be, I need add `GLEW` as dependency - but only when it `builtin_glew`

**Comment by linev** [comment]
If this is a case - we need to add same dependency in 6.20 branch

**Comment by linev** [comment]
@oshadura That does it mean - build unstable?

**Comment by linev** [comment]
@oshadura Can you approve PRs - this and #5210

**Pull request merged**
