### PR TITLE
[cling] Make parts of the cling codebase similar to upstream `clang-repl`

### PR DESCRIPTION
**Pull request by devajithvs**
# This Pull request:
Makes non-breaking changes to the existing code to make cling similar to upstream clang-repl. The idea is to make more changes in a similar fashion and completely swap out certain functions when they are similar enough.
## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Thanks for taking up this challenge. This is awesome!

**Comment by vgvassilev** [comment]
@smuzaffar, we will probably start moving towards more upstream llvm parts in Cling. These PRs need to be tested on cmssw because of relocation and pcms. Can you test this PR?

**Comment by smuzaffar** [comment]
> @smuzaffar, we will probably start moving towards more upstream llvm parts in Cling. These PRs need to be tested on cmssw because of relocation and pcms. Can you test this PR?

CMSSW tests started via  cms-sw/root#206

**Comment by smuzaffar** [comment]
@vgvassilev , cmssw [tests looks good](https://github.com/cms-sw/root/pull/206#issuecomment-2083540349). A unit test failure is not related to this PR.

**Comment by vgvassilev** [comment]
@smuzaffar, thank you!

`ROOT CI / mac14 ARM64 LLVM_ENABLE_ASSERTIONS=On` seems to be broken at cmake configuration and I do not see how this could be caused by this PR. Let's move forward here.

**Pull request merged**
