### PR TITLE
Fix running ROOT with -Dclingtest=On

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On

**Comment by amadio** [comment]
Hi Vassil, you probably need to rebase for the tests to stop failing.

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On -Dccache=Off

**Pull request closed without merging**
