### PR TITLE
[DF] Update Arrow datasource to the version in v6.20

### PR DESCRIPTION
**Pull request by eguiraud**
The RArrowDS in v6.16 did not support recent arrow versions.
This commits syncs it with v6.18, v6.20 and master.

This should fix [these](http://cdash.cern.ch/viewBuildError.php?buildid=865186) compilation failures in 6.16.

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by eguiraud** [comment]
The unit test also needed updating, now done.

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by oshadura** [comment]
@eguiraud there is something else needed to be backported to fix missing tests?

**Comment by eguiraud** [comment]
Hi Oksana, I was hoping to get @ktf or at least @Axel-Naumann to sign this off, since there seems to be breaking changes included in the backport (see the failures in `projectroot.tree.dataframe.test.gtest_tree_dataframe_test_datasource_arrow` above, before I also backported changes in that test).

**Comment by eguiraud** [comment]
@Axel-Naumann turned off arrow for ROOT <6.18, so we don't need the backports anymore

**Pull request closed without merging**
