### PR TITLE
Avoid virtual function call in Fill() if buffer map not needed

### PR DESCRIPTION
**Pull request by jblomer**
According to my benchmarks, speeds up filling into a ramdisk without compression by 5% - 10%.

### CODE REVIEW

**Comment by pcanal** [comment]
Can you use rebase rather merge (Merge commits are mostly disallowed).

**Comment by pcanal** [comment]
thanks

**Comment by jblomer** [comment]
Yup, sure, I'll open a another, clean pull request.

**Comment by jblomer** [comment]
@vgvassilev here it is: https://github.com/jblomer/forest/blob/master/fillbench.cxx

**Comment by jblomer** [comment]
Without merge commits in #2146

**Pull request closed without merging**
