### PR TITLE
Fix constructor for pointer to functor

### PR DESCRIPTION
**Pull request by xvallspl**
Bug found in the forum: https://root-forum.cern.ch/t/tf1-constructor-with-custom-class-broken-with-xcode-9-0/26422/9

### CODE REVIEW

**Comment by amadio** [comment]
Hi @xvallspl. It's probably worth adding tests for each acceptable type to check that the constructors are working as expected. This is not the first time a fix is needed for it, probably make sure it's not broken by future changes.

**Comment by xvallspl** [comment]
I was on it :)

**Comment by xvallspl** [comment]
I'm actually going to add it in gtest instead of roottest, so changing to WIP

**Comment by amadio** [comment]
Yeah, a gtest is best. No need to mark as WIP, I'm not merging without the test :-)

**Comment by xvallspl** [comment]
I run clang-format before pushing! maybe in the wrong terminal/directory? 😩

**Pull request merged**
