### PR TITLE
Return pointer to XXX object in DrawXXX methods.

### PR DESCRIPTION
**Pull request by couet**
This was not uniform as explain in this issue:
https://github.com/root-project/root/issues/6966

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Review by linev — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@couet rerunning PR tests because they will now pick up your new roottest branch making everything pass, ideally!

**Comment by couet** [comment]
@phsft-bot build

**Pull request merged**
