### PR TITLE
[Experimental PyROOT] Add numpy array interface to STL vector and RVec

### PR DESCRIPTION
**Pull request by stwunsch**
Reimplemented the numpy array interface for the experimental pyroot. I've pushed the setup mostly to python, which makes the code much nicer compared to the implementation in the "standard" pyroot.

This PR sits on top of #2467 (and therefore blocked by #2449).

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
Needs to be checked on python3 as there's no PR build for this (?)

**Comment by amadio** [comment]
The Fedora 28 build uses Python3

**Comment by stwunsch** [comment]
@phsft-bot build

**Pull request merged**
