### PR TITLE
Final changes to py2help

### PR DESCRIPTION
**Pull request by ElieKhairallah**

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build just on windows10/vc15

**Comment by amadio** [comment]
This pull request contains a merge commit, please rebase it instead. It cannot be merged as it is. Thanks.

**Pull request closed without merging**
