### PR TITLE
V6 08 00 patches

### PR DESCRIPTION
**Pull request by chissg**
Per conversion with Philippe, this pull request includes cherry-picked fixes for #ROOT-8714 and #ROOT-8222 from the master branch, which applied clean.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by chissg** [comment]
I'm confused: are these CI build errors something I should be worried about and trying to fix? They look pretty systemic to me. I can tell you I had a successful build on my own machine with GCC 6.3.0, but I understand the need for things to be verified independently. I just don't know how to interpret what might need to be done, here.

**Comment by Axel-Naumann** [comment]
Don't spend your time on this, Chris - this looks like infrastructural breakage...

**Comment by peremato** [comment]
It is running the v6-08-00-patches branch **root** on the master of **roottest**. This is something we need to fix in the Jenkins bot.

**Comment by peremato** [comment]
@phsft-bot build!

**Comment by peremato** [comment]
@phsft-bot build

**Pull request merged**
