### PR TITLE
Remove header copying in core/clingutils

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Standalone cling doesn't use modules; does it work even without copying headers, in a relocatable way? We might be able to turn this off for ROOT though.

**Comment by hahnjo** [comment]
> Standalone cling doesn't use modules; does it work even without copying headers, in a relocatable way? We might be able to turn this off for ROOT though.

Unless I'm missing something obvious here, this isn't used for Cling standalone at all - `core/clingutils/CMakeLists.txt` is a ROOT thing, no?

**Comment by Axel-Naumann** [comment]
🤦

**Comment by Axel-Naumann** [comment]
You should also test with `-Druntime_cxxmodules=Off`, please.

**Comment by hahnjo** [comment]
@phsft-bot build with flags -Druntime_cxxmodules=Off -DCTEST_TEST_EXCLUDE_NONE=On

**Review by vgvassilev — APPROVED** [review]
That looks reasonable to me.

**Pull request merged**
