### PR TITLE
v620 Fix ROOT-10942: Use FullName in TTree::GetLeaf

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by pcanal** [comment]
@eguiraud Is the issues in projectroot.tree.dataframe.test.gtest_tree_dataframe_test_dataframe_interface pre-existing?

**Comment by eguiraud** [comment]
@pcanal I think you backported too much? the test case that fails in dataframe_interface is a regression test introduced in later versions

**Comment by pcanal** [comment]
or too little.  In order to do the backport I need https://github.com/root-project/root/pull/6342/commits/9422eec329b9fe3b672e87a9617c67cf3762fdfa which indeed contains the failing test: RDataFrameInterface.UnusedJittedNodes.

@eguiraud Should I remove the tests or should we backport more?

**Comment by eguiraud** [comment]
@pcanal I assume the addition of those 3 new gtests in tree/dataframe/test/dataframe_interface.cxx is the result of a conflict resolution when backporting. The correct resolution is to leave the tests out (and therefore also the patch to one of the tests that the backported commit would add).

**Pull request merged**
