### PR TITLE
[TEve] Add XZ projection type.

### PR DESCRIPTION
**Pull request by osschar**
See discussion leading up to this:
https://root-forum.cern.ch/t/axes-dont-show-up-in-the-projection-of-a-imported-gdml-geometry-in-eve/40484/

### CODE REVIEW

**Review by linev — APPROVED** [review]
Looks ok

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@osschar, I guess you want to merge PR yourself?

**Comment by osschar** [comment]
@linev please do it, I don't have the karma oomph, it seems.

**Comment by linev** [comment]
Then I will do squash

**Comment by osschar** [comment]
thanks!

**Pull request merged**
