### PR TITLE
Simplify the platform-dependent part of a couple of add_custom_command

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Awesome!

**Comment by bellenot** [comment]
> Awesome!

Thanks! But it's not good enough yet...

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@bellenot, this seems to work very well! Can the commits be squashed and merged?

**Comment by bellenot** [comment]
> @bellenot, this seems to work very well! I was just triggering a CI rerun (the Windows 64 bit failures are unrelated and also seen in other PRs).
> 
> Can the commits be squashed and merged?

Thanks Jonas! I'll cross-check and squash and merge

**Review by guitargeek — APPROVED** [review]

**Pull request merged**
