### PR TITLE
[RF] Change types of persistent `unsigned long` and `std::size_t` data members in RooFit classes to platform independent definitions

### PR DESCRIPTION
**Pull request by guitargeek**
This is a follow up to https://github.com/root-project/root/pull/9475. See the commit messages for more info.

### CODE REVIEW

**Comment by pcanal** [comment]
> is now used instead (see also adc78fa).

Avoid using commit hash in commit log (*) (especially since we use rebase) as they are not stable, in particular if/when the commit is back ported.  At the very least, I recommend adding (or using instead) the title of the commit in question.

**Comment by guitargeek** [comment]
Hi @pcanal, happy New Year! Sorry I missed your comment just before the holiday break. I have updated the last commit message to not only include the commit hash in `master`, but also the commit title. Is that okay now?

**Review by lmoneta — APPROVED** [review]
LGTM!

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
Thanks.

**Pull request merged**
