### PR TITLE
[jsroot] dev 26/06/2024 with `THStack` and `TMultiGraph` fixes

### PR DESCRIPTION
**Pull request by linev**
1. TProfile and TProfile2D projections https://github.com/root-project/root/issues/15851
2. Draw total histogram from TEfficiency when draw option starts with 'b'
3. Let redraw TEfficiency, THStack and TMultiGraph with different draw options via hist context menu
4. Support 'pads' draw options for TMultiGraph, support context menu for it
5. Internals - do not select pad (aka gPad) for objects drawing, always use assigned pad painter
6. Fix - properly save zoomed ranges in drawingJSON()
7. Fix - properly redraw TMultuGraph

Resolves many issues with `THStack` and `TMultiGraph` handling.

For instance, macro `tutorials/legacy/mlp/mlpRegression.C` with multi-graph works properly with web graphics.

Also y scale range selection for THStack is much closer to original ROOT

### CODE REVIEW

**Comment by dpiparo** [comment]
Thanks for this effort. Are tests included in the forthcoming json/svg testing battery?

**Comment by linev** [comment]
Tests not yet included. 
I create separate PR for fixing `THStack` functionality. And will add several tests there.
For graphics testing we need to activate Adrian testsuite

**Review by dpiparo — APPROVED** [review]
LGTM

**Comment by linev** [comment]
Failures unrelated to PR

**Pull request merged**
