### PR TITLE
v7: rename TDirectory -> RDirectory (ROOT-10126)

### PR DESCRIPTION
**Pull request by linev**
Also v7 TFit, TFile, TLogger, TIndexIter

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
Hove no idea that is with Jenkins :(

**Comment by linev** [comment]
Seems to be, only mac is doing something

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON -DCMAKE_CXX_STANDARD=14

**Comment by linev** [comment]
I hope, after https://github.com/root-project/roottest/pull/325 also testing with c++17 will work

**Comment by amadio** [comment]
Not all nodes support C++14 and 17... (some use GCC 4.8 to build).

**Comment by linev** [comment]
@amadio Seems to be, when nothing else specified, mac nodes try to use c++17 and fails with several roottest (deprecated auto_ptr)

**Comment by linev** [comment]
@amadio  
As idea: 
Can we provide build option which enables maximal-available c++ standard and root7 when at least c++14 is there? Or simply enable root7 an all platforms where it make sense? 
Otherwise it always a chalenge to test root7 features on Jenkins

**Comment by Axel-Naumann** [comment]
@linev could you resolve the conflict, please?

**Pull request closed without merging**
