### PR TITLE
[TMVA] Add new RTensor constructor

### PR DESCRIPTION
**Pull request by axmat**
This PR should add a new constructor for the RTensor class.

### CODE REVIEW

**Comment by stwunsch** [comment]
Hey, thanks for your PR! I'm a little bit confused, aren't the strides set by the memory layout and the shape of the tensor? In which configuration you would want to set custom strides? Also I'm not too sure whether then the transformations are still valid. Can you confirm this?

**Comment by axmat** [comment]
Hi @stwunsch,

I think that the strides are set by the memory layout (row-major or column-major), the memory format (CHWN, NCHW, ...) and the shape of the tensor.

CHWN is the format supported by RTensor.So when computing the strides, the function Internal::ComputeStridesFromShape assumes that the memory format is CHWN.

NCHW is the only format supported by ONNX (Open Neural Network Exchange). That’s why I need to set custom strides to comply to the ONNX standards and to inference ONNX models.

A better approach would be to support these two formats like in CuDNN:
```{c++}
enum class MemoryFormat{
   CHWN = 0;
   NCHW = 1
};

```

I have checked and Reshape is not valid. it calls the function Internal::ComputeStridesFromShape which computes the strides in the CHWN format.

**Comment by stwunsch** [comment]
Hi!

Could you explain further how `CHWN` vs `NCHW` matters for `RTensor`? I understand this as the "channel-first" or "batch-first" ordering of tensors in TensorFlow, ONNX, cuDNN, ... . However, this does not matter, since it's just how you interpret the indices of a 4D `RTensor` and not related to the actual memory layout. Is this correct?

**Comment by axmat** [comment]
Thanks, it doesn't really matter for RTensor.
I had to set custom strides to access the elements of the tensor in NCHW format. But permuting the indices or reshaping the data does the trick, I think you can close this PR.

**Comment by stwunsch** [comment]
Alright :) Thanks for the discussion!

**Pull request closed without merging**
