### PR TITLE
[PyROOT] Do `__getattr__` pythonization of TTree in Python

### PR DESCRIPTION
**Pull request by guitargeek**
There is no need to do this on the C++ size.

### CODE REVIEW

**Comment by pcanal** [comment]
@smuzaffar Could you check if this break any CMSSW code?

**Comment by guitargeek** [comment]
> @smuzaffar Could you check if this break any CMSSW code? Actually more interesting is: #14444

It doesn't matter which one you test, they both contain the commit with the `GetAddress()` and `GetObject()` return type

**Comment by smuzaffar** [comment]
> @smuzaffar Could you check if this break any CMSSW code? Actually more interesting is: #14444

@pcanal , cmssw tests are running via https://github.com/cms-sw/root/pull/196

**Comment by smuzaffar** [comment]
mostly looks good for cmssw. Only one unit test failed with error [a]

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ce122a/37051/unitTests/src/DQMServices/Demo/test/TestDQMServicesDemo/testing.log
```
++ /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_ROOT6_X_2024-01-25-2300/src/DQMServices/Demo/test/dqmiodumpentries.py alltypes.root -r 1 --summary
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_ROOT6_X_2024-01-25-2300/src/DQMServices/Demo/test/dqmiodumpentries.py", line 54, in <module>
    value = metree.Value
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.31.01-29afad78d0e3ad51f539f0164a6c7494/lib/ROOT/_pythonization/_ttree.py", line 266, in _TTree__getattr__
    proxy = bind_branch_to_proxy(self, name, branch)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc12/lcg/root/6.31.01-29afad78d0e3ad51f539f0164a6c7494/lib/ROOT/_pythonization/_ttree.py", line 212, in bind_branch_to_proxy
    return cppyy.bind_object(branch.GetAddress()[0], branch.GetClassName())
TypeError: 'nullptr_t' object is not subscriptable
+ '[' '0: 1, 0.0: 1, 1: 11, 100: 33, 200: 11, 5: 16, 5.0: 5' = '' ']'

---> test TestDQMServicesDemo had ERRORS
```

**Comment by guitargeek** [comment]
Thank you very much for catching these errors, @smuzaffar. It appears our CI doesn't cover all code branches...

Anyway, given that the pythonization implemented in C++ still works fine even after the CPyCppyy upgrade in my other PR, this translation to Python is not necessary at this moment, and I will close this PR.

**Pull request closed without merging**
