### PR TITLE
[cxxmodules] Add LD_LIBRARY_PATH to the list of prebuilt module caches.

### PR DESCRIPTION
**Pull request by vgvassilev**
We rely on rootcling to put reflection/IO information and building pcms
on demand does not make sense.

EDIT: We cannot really disable building implicit pcms as we are missing infrastructure. We currently rely on building libc, stl and _Builtin_intrinsics modules on demand while running rootcling.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Droofit=Off -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
Looks like the system goes out of memory due to the multiple concurrent modules built by rootcling.

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug -Druntime_cxxmodules=On -Droofit=Off -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
When I do `bin/root.exe -q -l` with this patch in release build, unsetting LD_LIBRARY_PATH and DYLD_LIBRARY_PATH, I get this error:
```
[yuka@yuka-arch module-release]$ rm -rf /tmp/*
[yuka@yuka-arch module-release]$ source bin/thisroot.sh
[yuka@yuka-arch module-release]$ bin/root.exe -q -l
 
[yuka@yuka-arch module-release]$ unset DYLD_LIBRARY_PATH
[yuka@yuka-arch module-release]$ unset LD_LIBRARY_PATH
[yuka@yuka-arch module-release]$ bin/root.exe -q -l
input_line_1:1:10: remark: building module 'stl' as '/tmp/org.llvm.clang.yuka/ModuleCache/stl.pcm' [-Rmodule-build]
#include <new>
         ^
input_line_1:1:10: remark: finished building module 'stl' [-Rmodule-build]
/home/yuka/module-release/include/libc.modulemap:1:8: fatal error: module 'libc' is defined in both '/tmp/org.llvm.clang.yuka/ModuleCache/libc.pcm' and '/home/yuka/module-release/lib/libc.pcm'
module "libc" [system] {
       ^
Error in <TCling::LoadModule>: Module libc failed to load
Error in <TCling::LoadModule>: Module libc not found!
Error in <TCling::LoadModule>: Module ROOT_Foundation_C failed to load
Error in <TCling::LoadModule>: Module ROOT_Foundation_C not found!
Error in <TCling::LoadModule>: Module ROOT_Config failed to load
Error in <TCling::LoadModule>: Module ROOT_Config not found!
Error in <TCling::LoadModule>: Module ROOT_Foundation_Stage1_NoRTTI failed to load
Error in <TCling::LoadModule>: Module ROOT_Foundation_Stage1_NoRTTI not found!
terminate called after throwing an instance of 'std::runtime_error'
  what():  >>> Interpreter compilation error:
Unexpected end of file
Aborted (core dumped)
```
As shown, Clang is still trying to generate implicit modules in `/tmp/org.llvm.clang.yuka/ModuleCache/`.

This patch is adding `/home/yuka/module-release/lib:.:/home/yuka/module-release/lib:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib` to TCling path, so I guess the expected result is implicitly loading modules in `/home/yuka/module-release/lib` (even when LD_LIBRARY_PATH is unset) but somehow it doesn't work because currently Clang is trying to generate implicit modules.

Stack trace of WriteAST(Runtime, with LD_LIBRARY_PATH and DYLD_LIBRAYR_PATH unset):
```
(gdb) b WriteAST
Function "WriteAST" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (WriteAST) pending.
(gdb) r -q -l
Starting program: /home/yuka/module-relwithdeb/bin/root.exe -q -l
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
input_line_1:1:10: remark: building module 'stl' as '/tmp/org.llvm.clang.yuka/ModuleCache/stl.pcm' [-Rmodule-build]
#include <new>
         ^
[New Thread 0x7ffff0b8c700 (LWP 21631)]
[New Thread 0x7fffebfff700 (LWP 21632)]
[New Thread 0x7fffeb7fe700 (LWP 21633)]
[Switching to Thread 0x7fffeb7fe700 (LWP 21633)]

Thread 4 "root.exe" hit Breakpoint 1, clang::ASTWriter::WriteAST (this=this@entry=0x7fffdc023c70, SemaRef=..., OutputFile="/tmp/org.llvm.clang.yuka/ModuleCache/sys_types.h.pcm", WritingModule=0x7fffdc018480, 
    isysroot=..., hasErrors=false) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Serialization/ASTWriter.cpp:4470
4470                                         bool hasErrors) {
(gdb) bt
#0  clang::ASTWriter::WriteAST (this=this@entry=0x7fffdc023c70, SemaRef=..., OutputFile="/tmp/org.llvm.clang.yuka/ModuleCache/sys_types.h.pcm", WritingModule=0x7fffdc018480, isysroot=..., hasErrors=false)
    at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Serialization/ASTWriter.cpp:4470
#1  0x00007ffff1fd2e6a in clang::PCHGenerator::HandleTranslationUnit (this=0x7fffdc023ba0, Ctx=...) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Serialization/GeneratePCH.cpp:61
#2  0x00007ffff1d96a58 in clang::MultiplexConsumer::HandleTranslationUnit (this=<optimized out>, Ctx=...) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Frontend/MultiplexConsumer.cpp:305
#3  0x00007ffff37bc16a in clang::ParseAST (S=..., PrintStats=<optimized out>, SkipFunctionBodies=<optimized out>) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Parse/ParseAST.cpp:159
#4  0x00007ffff1d67996 in clang::FrontendAction::Execute (this=this@entry=0x7fffeb7f9c00) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Frontend/FrontendAction.cpp:896
#5  0x00007ffff1d302f4 in clang::CompilerInstance::ExecuteAction (this=0x7fffebff7ed0, Act=...) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Frontend/CompilerInstance.cpp:984
#6  0x00007ffff1d309af in <lambda()>::operator() (__closure=0x7fffebff7db0) at /home/yuka/root/interpreter/llvm/src/tools/clang/lib/Frontend/CompilerInstance.cpp:1154
#7  llvm::function_ref<void()>::callback_fn<compileModuleImpl(clang::CompilerInstance&, clang::SourceLocation, llvm::StringRef, clang::FrontendInputFile, llvm::StringRef, llvm::StringRef, llvm::function_ref<void(clang::CompilerInstance&)>, llvm::function_ref<void(clang::CompilerInstance&)>)::<lambda()> >(intptr_t) (callable=140737152777648) at /usr/include/llvm/ADT/STLExtras.h:98
#8  0x00007ffff43bffb3 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) () from /home/yuka/module-relwithdeb/lib/libCling.so
#9  0x00007ffff43c00a5 in RunSafelyOnThread_Dispatch(void*) () from /home/yuka/module-relwithdeb/lib/libCling.so
#10 0x00007ffff44360ad in ExecuteOnThread_Dispatch(void*) () from /home/yuka/module-relwithdeb/lib/libCling.so
#11 0x00007ffff6e3d08c in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007ffff6b74e7f in clone () from /usr/lib/libc.so.6
```
My point is
1. In user's machine, I think it is unlikely that LD_LIBRARY_PATH and DYLD_LIBRARY_PATH is unset because if ROOT is successfully installed in the machine, they should be set. Thus I'm not 100% sure that we should add DynamicPath to search because it causes overhead in the lookup.
2. Instead, I think we can change Clang code to abort when it generates implicit modules on-demand and emit error messages.

What do you think?

**Comment by vgvassilev** [comment]
I changed the description of the PR to describe what's the final intent here.

**Comment by yamaguchi1024** [comment]
What is the point of adding the compile time LD_LIBRARY_PATH to the runtime prebuild module cache?

**Comment by vgvassilev** [comment]
We have similar functionality in the [CIFactory.cpp](https://github.com/root-project/root/blob/master/interpreter/cling/lib/Interpreter/CIFactory.cpp#L1085-L1090) already. However, I can't really decide which is the better approach here. Maybe this one is still preferable because this feature seems ROOT-specific.

**Comment by lmoneta** [comment]
@vgvassilev , @yamaguchi1024   Is this PR still relevant ? Should we fix the failures and merge ?

**Comment by yamaguchi1024** [comment]
I think this is not relevant anymore.

**Comment by vgvassilev** [comment]
There is different version of this code in the codebase already.

**Pull request closed without merging**
