### PR TITLE
[DF] Shorten RDF unit tests

### PR DESCRIPTION
**Pull request by dpiparo**
Reduce duration of DF unit tests, eliminating jitting in favor of compilation where possible and optimizing obvious parameters, all without loosing any coverage.

# This Pull request:

## Changes or fixes:
The df battery of unit tests now runs a few minutes faster than before.

## Checklist:

- [v] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by eguiraud** [comment]
@martamaja10 sounds reasonable to me, what do you think?

**Comment by dpiparo** [comment]
doing unrelated work, I noticed that other df tests could be optimized and that more could be done for the "helpers" tests.

**Comment by martamaja10** [comment]
> @martamaja10 sounds reasonable to me, what do you think?

Looks good to me as well.

**Comment by dpiparo** [comment]
Thanks @martamaja10 . The issue I am looking at is why the code does not build on linux. It seems kind of odd that this include does not work ```#include <Math/Vector4D.h>```...

**Review by pcanal — COMMENTED** [review]
LGTM.  Thanks.

**Review by pcanal — APPROVED** [review]

**Review by vepadulano — APPROVED** [review]
Thank you Danilo!

**Review by martamaja10 — APPROVED** [review]
Looks good from my side too, thank you!

**Pull request merged**
