### PR TITLE
[cling] Fix remaining test failures

### LINKED ISSUE #12455: Failing Cling tests with multiple interpreters
Since the upgrade to LLVM 13, at least two tests are failing because of broken interactions with multiple interpreters:
 * `CodeUnloading/AtExit.C` does not find the symbol `gChild`.
 * `MultipleInterpreters/MultipleInterpreters.C` cannot find the symbol `_ZN5cling7runtime6gClingE` / `cling::runtime::gCling` during `ChildInterp.echo()` (the first usage to construct `cling::Interpreter ChildInterp(*gCling, 1, argV);` seems fine).

Based on this, one might theorize that the child interpreter doesn't have access to symbols declared in its parent (not sure how this worked before).

### PR DESCRIPTION
**Pull request by jalopezg-git**
This pull request fixes the remaining failing cling tests.  See below for the concrete changes.

@vgvassilev After the changes proposed in this PR, _all_ the cling tests are passing.

## Changes or fixes:
- Restore symbol lookup in child interpreters: prior to the upgrade to LLVM13, child interpreters used to also lookup symbols
in their parent.  This PR introduces a `DefinitionGenerator` that allows for symbol lookup across different `IncrementalJIT` instances, which restores the old behavior.
This change fixes the following tests: CodeUnloading/AtExit.C, MultipleInterpreters/MultipleInterpreters.C.
- `cling::DeclExtractor::EnforceInitOrder`: do not use `ActOnReturnStmt()`, given that the scope returned by `m_Sema->getCurScope()` might be == m_Sema->TUScope which obviously is not a function scope; use `BuildReturnStmt()` instead.
This fixes the following crash:
```
1:  https://github.com/root-project/root/pull/3 0x0000556b6a50389e clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) (/home/jalopezg/CERN/repos/root/_build/interpreter/llvm/src/bin/cling+0x225389e)
1:  https://github.com/root-project/root/pull/4 0x0000556b69215c56 cling::DeclExtractor::EnforceInitOrder(llvm::SmallVector<clang::Stmt*>&) (/home/jalopezg/CERN/repos/root/_build/interpreter/llvm/src/bin/cling+0xf65c56)
1:  https://github.com/root-project/root/pull/5 0x0000556b69216788 cling::DeclExtractor::ExtractDecl(clang::FunctionDecl*) (/home/jalopezg/CERN/repos/root/_build/interpreter/llvm/src/bin/cling+0xf66788)
1:  https://github.com/root-project/root/pull/6 0x0000556b69216a75 cling::DeclExtractor::Transform(clang::Decl*) (/home/jalopezg/CERN/repos/root/_build/interpreter/llvm/src/bin/cling+0xf66a75)
```

## Checklist:
- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #12455.

### CODE REVIEW

**Review by hahnjo — COMMENTED** [review]
Thanks, I now realize I rendered `m_externalIncrementalExecutor` unused in commit 9b2041e3000a1d86bbad0595b2bc8e2deb8e247a...

Instead of our own `DelegateGenerator`, did you try using the available `ReexportsGenerator` with `Jit->getMainJITDylib()`?

**Comment by jalopezg-git** [comment]
> Thanks, I now realize I rendered `m_externalIncrementalExecutor` unused in commit [9b2041e](https://github.com/root-project/root/commit/9b2041e3000a1d86bbad0595b2bc8e2deb8e247a)...
> 
> Instead of our own `DelegateGenerator`, did you try using the available `ReexportsGenerator` with `Jit->getMainJITDylib()`?

Yes, indeed my first try at this was
```c++
  return std::make_unique<ReexportsGenerator>(Jit->getMainJITDylib(), JITDylibLookupFlags::MatchAllSymbols);
```
but it didn't seem to work.

I think this might be related to the issue described [here](https://stackoverflow.com/questions/74405679/cannot-resolve-symbols-by-reexportsgenerator-in-llvm-orc-jit), and as far as I could see without diving too deep, is that it may have something to do with linker-mangled name vs. IR symbol name.  Thus, if `ReexportsGenerator` cannot be used _directly_, I propose this fix instead.

**Review by hahnjo — APPROVED** [review]
> it may have something to do with linker-mangled name vs. IR symbol name

Ih right, that topic again. Fair enough, let's work with what we have right now :smiley:

**Review by vgvassilev — APPROVED** [review]
This is awesome. LGTM!

I have pinged @lhames about the generator question.

**Pull request merged**
