### PR TITLE
[cling] Extracted decls should be unconditionally moved to the parent DeclContext

### PR DESCRIPTION
**Pull request by jalopezg-r00t**
Declarations extracted by DeclExtractor, regardless of their type, should be moved to the parent declaration context (be it the `TranslationUnitDecl` or a `NamespaceDecl` if DefinitionShadower is enabled).

This prevents the following situation (i.e., the CXXRecordDecl becomes a child of the TranslationUnitDecl instead of the internal namespace used by the definition shadower):
```c++
root [] struct X {} foo
(struct X &) @0x7f545a5ff018
root [] .stats asttree
|-NamespaceDecl 0x5647ecc93780 <<invalid sloc>> <invalid sloc> __cling_N50 inline
| |-VarDecl 0x5647ecc89f10 <ROOT_prompt_0:1:1, col:13> col:13 used foo 'struct X':'X' callinit
| | `-CXXConstructExpr 0x5647ecc8a420 <col:13> 'struct X':'X' 'void () noexcept'
| `-FunctionDecl 0x5647ecc89bc8 <input_line_8:1:1, ROOT_prompt_0:3:1> input_line_8:1:6 __cling_Un1Qu30 'void (void *)'
...
|-CXXRecordDecl 0x5647ecc89c98 <line:1:1, col:11> col:8 struct X definition
```

Sibling PR in roottest: https://github.com/root-project/roottest/pull/819.

## Checklist:
- [X] tested changes locally

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Lgtm! Any chance for a test to capture this?

**Comment by Axel-Naumann** [comment]
@pcanal I'd be okay with adjusting [roottest/root/meta/tclass/execState.C](https://github.com/root-project/roottest/blob/master/root/meta/tclass/execState.C) as follows:
```diff
 int execState() {
    int result = 0;
 
-    gROOT->ProcessLine("class Event;");
+    gROOT->Declare("class Event;");
    TClass *c = TClass::GetClass("Event"); 
    if (TClass::kForwardDeclared != c->GetState()) {
       Error("execState","State is %d instead of %d (TClass::kForwardDeclared)",
```
which should "fix" the test failure. What do you think?

**Comment by pcanal** [comment]
I think it is fine to change the test as the new code fit better the intent.  However, it also hides a real issue:
```
root [0] class ABC;
root [1] void func(ABC*) {}
root [2] class ABC { int a; }
root [3] ABC a
(ABC &) @0x10ad87068
root [4] func(&a)
IncrementalExecutor::executeFunction: symbol '_ZN11__cling_N514funcEPN11__cling_N523ABCE' unresolved while linking [cling interface function]!
You are probably missing the definition of __cling_N51::func(__cling_N52::ABC*)
Maybe you need to load the corresponding shared library?
```

**Comment by jalopezg-r00t** [comment]
> ```
> root [4] func(&a)
> IncrementalExecutor::executeFunction: symbol '_ZN11__cling_N514funcEPN11__cling_N523ABCE' unresolved while linking [cling interface function]!
> You are probably missing the definition of __cling_N51::func(__cling_N52::ABC*)
> Maybe you need to load the corresponding shared library?
> ```
This pull request improves the situation; cling now emits a diagnostic
```c++
ROOT_prompt_4:1:1: error: no matching function for call to 'func'
func(&a)
^~~~
ROOT_prompt_1:1:6: note: candidate function not viable: no known conversion from '__cling_N52::ABC *' to '__cling_N50::ABC *' for 1st argument
void func(ABC*) {}
     ^
```
meaning: function `func()` takes a different version of `class ABC` (for which you provided a different definition in a following step).

Despite the sequence you described being valid C++, if definition shadowing is enabled (as per the current implementation), you need to also redefine the function so that the type of the first argument is that of the latest definition of `class ABC`:
```c++
root [5] void func(ABC*) {}
root [6] func(&a)
```

**Pull request merged**
