### PR TITLE
[VecOps] Deprecate RVec::AsVector

### PR DESCRIPTION
**Pull request by eguiraud**
It returns the `std::vector<T, RAdoptAllocator<T>>` data member by
reference, but in the near future we want to remove the data member
(in the context of adding a small buffer optimization to RVec).

### CODE REVIEW

**Review by pcanal — APPROVED** [review]

**Comment by eguiraud** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by eguiraud** [comment]
@bellenot "no space left on device" :confused:

**Comment by bellenot** [comment]
> @bellenot "no space left on device" 😕

Should be fixed now. Just let Jenkins update the node status...

**Comment by bellenot** [comment]
@eguiraud the node is available now

**Comment by eguiraud** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by eguiraud** [comment]
Thank you Bertrand!

**Pull request merged**
