### PR TITLE
Fix PR builds on Mac for v6.20

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
LGTM!

**Comment by oshadura** [comment]
looks like it is something wrong with nodes?

**Comment by hahnjo** [comment]
> looks like it is something wrong with nodes?

I think the failures are real, we're missing a number of patch to make macOS 11 work with v6.20. I had hoped that the few would do, but looks like I need to debug this on a node instead of spamming Jenkins...

**Comment by Axel-Naumann** [comment]
I took macphsft20 offline; macphsft23 should jump in.

**Comment by Axel-Naumann** [comment]
> I think the failures are real, we're missing a number of patch to make macOS 11 work with v6.20.

It's a combination. But we don't *need* to make v6.20 work on macOS11. But I guess we currently have a version independent set of PR platforms... That'll auto-fix with root.git having the CI pipeline "inside", in the future... For now we will likely have to ignore macOS11 for v6.20 :-/

**Comment by Axel-Naumann** [comment]
OTOH I really don't understand the 10.14 failure - the node has numpy installed just fine at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy.

**Comment by hahnjo** [comment]
> OTOH I really don't understand the 10.14 failure - the node has numpy installed just fine at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy.

AFAICT it's not using the Frameworks Python, but `/usr/local/bin/python3`. Does this mean we need https://github.com/root-project/root/pull/6849/commits/6a7b54854118125258f0384c0478f1b4a4fb20a0? I'm going to test this directly on the node when I have time.

**Comment by Axel-Naumann** [comment]
IIRC `/usr/local/bin/python3` is a symlink to the Framework python. 10.14 - things are really different there. :-)

**Comment by hahnjo** [comment]
> I took macphsft20 offline; macphsft23 should jump in.

@Axel-Naumann hmm, `macphsft23` is even worse: `xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun` What do I have to do to get `macphsft20` back? :sweat_smile: I think I found enough commits to get most of the tests pass

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11.0/cxx17

**Comment by Axel-Naumann** [comment]
@couet this might mean that you need to run clang one through the remote display, to sign the license and download what's missing. Just running `clang --help` in a terminal should be enough. Can you do it?

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11.0/cxx17

**Pull request merged**
