### PR TITLE
Fix execution policy error when IMT is OFF

### PR DESCRIPTION
**Pull request by agarciamontoro**
If IMT is disabled, force the execution policy to be `ROOT::Fit::ExecutionPolicy::kSerial`, warning the user that a change in the execution policy has been made.

This should fix the errors in the tests built without IMT.

When the support for `kMultitProcess` is finished, maybe we should change this and force the execution policy to be `kMultitProcess`.

### CODE REVIEW

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
@phsft-bot build with flags -Dimt=OFF -Dbuiltin_tbb=OFF

**Comment by lmoneta** [comment]
@phsft-bot build with flags -Dimt=OFF -Dbuiltin_tbb=OFF

**Pull request merged**
