### PR TITLE
H comb merge new

### PR DESCRIPTION
**Pull request by cburgard**
Wouter Verkerke has added some fixes to RooFit for usage in the Higgs Combination working group in ATLAS. These fixes include additions of new classes as well as genuine bugfixes. This is a minimal collection of these fixes that successfully compiles and passes all the tests on an SLC6 machine. @egpbos

[rebased version of this pull request: [https://github.com/root-project/root/pull/776](url)]

### CODE REVIEW

**Comment by bluehood** [comment]
Hi,
first of all thank you for your contribution. I am in no position to actually review the content of the pull request, but it seems you are adding two commits with unclear descriptions that change 37 files and 4000+ lines -- making it a hard PR to review. If you have time and it sounds reasonable to you, it might be desirable to split the PR in commits containing small self-contained logical changes (with a descriptive commit message).

Perhaps more importantly, it seems some rebasing artifacts like
```
+<<<<<<< HEAD
```
were left in the code.

Cheers,
Enrico

**Comment by martinmine** [comment]
Hi, not a reviewer either but just offering my two cents to make the PR review more smooth:
- Make sure your PR can actually compile. As @bluehood mentioned, there are many rebasing artifacts throughout the code. Also make sure your code passes clang-format.
- What bugs/issues does this PR actually solve? You mentioned in the previous PR #776 that they "fixes include additions of new classes as well as genuine bugfixes.", could you elaborate what bugfixes these are? (This would be nice to have in your commit messages)
- Some test for whatever you are trying to fix would be great, this PR adds >4600 LOC without one single test.

**Comment by Teemperor** [comment]
@phsft-bot build

do your best, you can do it

**Comment by cburgard** [comment]
I now (hopefully) removed all of the rebasing artefacts by undoing and redoing the cherry-picking. Unfortunately it seems that Jenkins still complains, although I can't seem to find the reason - my local version seems to compile... any suggestions?

**Comment by martinmine** [comment]
@phsft-bot build.

@cburgard this is because the build by Jenkins was triggered by @Teemperor before you submitted the additional commits. Once Jenkins is triggered, it will take the last commit that you made upon the time it gets triggered. I have re-triggered a build of your PR as of this comment.

**Comment by cburgard** [comment]
Ok apparently I understand CMake way less than I thought I did.

Let's see...
@phsft-bot build.

**Comment by Teemperor** [comment]
@phsft-bot build

**Comment by cburgard** [comment]
I refactored things a bit. Now all tests should succeed. Could anyone trigger a new build test?

**Comment by egpbos** [comment]
@phsft-bot build

**Comment by bluehood** [comment]
@phsft-bot build please

**Comment by cburgard** [comment]
I'm a bit confused by the output of Jenkins here... 
As far as I can see, the build claims to have failed, but the only failed tests that I can see are related to TFormula, whereas the changes only affect RooFit...
Any idea what might be going on here?

**Comment by bluehood** [comment]
hi, well the PR is built on top of master, and master currently has a few failing tests. so it's really not your fault :)

**Comment by cburgard** [comment]
Good! Anything else to be done on my side for the pull request to be merged, then?

**Comment by bluehood** [comment]
Yep, your PR should be reviewed, approved and merged by the main developer responsible for this part of the code. I believe in this case it is @lmoneta.

Cheers,
Enrico

**Comment by cburgard** [comment]
Let me know if there is anything that needs to be done by me. Otherwise, I hope someone (@lmoneta ?) will take care of the merging as soon as there is some free capacity.

**Comment by martinmine** [comment]
@cburgard many of the new file this PR introduces contains headers containing
` This code was autogenerated by RooClassFactory       `
Any reason why?

**Comment by cburgard** [comment]
I cannot really comment on the specifics of the code, as I am not the original author. That would be Wouter Verkerke, who has asked me to propagate these fixes and additions upstream for him. I assume that if you have specific questions about individual code segments, it's probably easiest if you ask him directly.

**Comment by Axel-Naumann** [comment]
While the final review indeed needs @lmoneta here are preliminary comments:
 
- There is almost no documentation, this must be fixed before merging. Note that ROOT has changes its syntax since a couple of years, we now use doxygen.
- We need a couple of tests
- We need a tutorial
- We need a diff for the release notes.

Assuming that @lmoneta accepts this PR design-wise, these issues must be addressed before we can merge.

**Comment by lmoneta** [comment]
@phsft-bot  build

**Comment by cburgard** [comment]
adding @wverkerke

**Comment by lmoneta** [comment]
All the code of this PR has been merged, by opening another one and fixing the conflicts

**Pull request closed without merging**
