### PR TITLE
[cxxmodules] Load modulemap in current directory

### PR DESCRIPTION
**Pull request by yamaguchi1024**
This is related to the fix of includeInLinkdef. Load
"./module.modulemap" if it exists. User can cd to different directory
and LoadModule loads the new modulemap.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
Maybe we should do this only when LoadModule fails with default include path?

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by yamaguchi1024** [comment]
Trees are also failing in nightlies, https://epsft-jenkins.cern.ch/view/ROOT/job/root-nightly-runtime-cxxmodules/lastBuild/BUILDTYPE=Debug,COMPILER=gcc62,LABEL=slc6/testReport/
so these I think is unrelated

**Comment by yamaguchi1024** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Pull request merged**
