### PR TITLE
Add a chunking interface to TProcessExecutor

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by gganis** [comment]
Looking at this.
Why do you need to control the number of chunks?
That should be controlled internally; either to the number of workers or a multiple of that.

**Comment by xvallspl** [comment]
We decided to pursue this in a way it's not exposed to the user. Another PR to come soon.

**Pull request closed without merging**
