### PR TITLE
fix a line in PyMethodBase.cxx which make it fail to build

### PR DESCRIPTION
**Pull request by ACA4DFA4**
fixed a bug in tmva/pymva/src/PyMethodBase.cxx

### CODE REVIEW

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
Good catch @ACA4DFA4 ! I wonder why we don't see the build failure in our CI. Can you tell us your configuration and how you got the error during the build ?

**Comment by lmoneta** [comment]
I think the code before is valid C++, since you can convert `const char * ` to std::string and you can do:
```
std::string s = " this  " + std::string("works ");
```

**Comment by vepadulano** [comment]
But the code before was doing 
```cpp
"Key "+key+" does not exist in the dictionary."
```
Which is `const char *` + `const char *` + `const char *`, which do not implement `operator+`. Or am I missing something?

**Review by lmoneta — APPROVED** [review]
This is correct @vepadulano. The code before compiles because we are building only with Python3 and it is compiled only in Python2 builds. 
In the CI we don't have anymore Python2 only builds.

**Comment by vepadulano** [comment]
Ok I understand. I would wait for @ACA4DFA4 to tell us more about their configuration, including why do they need to build with Python2.

**Comment by vepadulano** [comment]
@ACA4DFA4 the Python executable chosen should be whatever `python3` points to, which probably will be `python3.8`. In the output you pasted, `python3.8` is actually found, what is not found is `missing: Python3_INCLUDE_DIRS Python3_LIBRARIES Python3_NumPy_INCLUDE_DIRS...`. It might be enough to just install `numpy` with `python3`, but that's beside the point of this PR. In your case PyROOT will build directly with Python2 since there are some missing components for 3, hence the error you found. Thanks for the fix! This PR can be merged.

**Pull request merged**
