### PR TITLE
WebEve: Add interface for custom GUI in REveManger

### PR DESCRIPTION
**Pull request by alja**
Here is an example of setting custom openui5 client GUI:

 auto eveMng = REX::REveManager::Create();
 eveMng->AddLocation("mydir/", "/home/alja/root-dev/EveWebApp/ui5");
 eveMng->SetDefaultHtmlPage("file:mydir/xxx.html");
 
Here is test repository:
https://github.com/alja/EveWebApp

### CODE REVIEW

**Comment by linev** [comment]
@alja, can you use `const std::string &` instead of `std::string` as methods arguments.

**Comment by alja** [comment]
@linev OK, will make this change.

**Comment by alja** [comment]
What about const char* for arguments?

The usage will be like this:
   eveMng = REX::REveManager::Create();
   eveMng->AddLocation("mydir/", "/home/alja/root-dev/EveWebApp/ui5");
   eveMng->SetDefaultHtmlPage("file:mydir/test.html");

**Comment by linev** [comment]
> What about const char* for arguments?

No, please use `const std::string &`.

**Comment by linev** [comment]
@alja I asked `const std::string &`. If you use `std::string &`, you have to declare extra variable before calling such method.

**Comment by alja** [comment]
@linev please check if that is OK.

**Comment by linev** [comment]
Now is ok - I merging it

**Pull request merged**
