### PR TITLE
libpng 1.6.40

### PR DESCRIPTION
**Pull request by couet**
This Pull request incorporates the latest `libpng` as requested here:
https://github.com/root-project/root/issues/13825
The new version is 1.6.40.

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
Ok. I need to understand whats wrong with that.

**Comment by couet** [comment]
@phsft-bot build

**Review by bellenot — APPROVED** [review]
LGTM

**Comment by couet** [comment]
@phsft-bot build

**Pull request merged**
