### PR TITLE
webgui: correct close of canvas

### PR DESCRIPTION
**Pull request by linev**
1. Implement Canvas::Hide(). It send "CLOSE" command to all connected clients. 
Normally this causes closing of browser window. Works with CEF, Qt5 and web browsers

2. Handle correctly situation when user closes canvas window himself. At this moment JS client sends websocket::close() command to the server, that CanvasPainter can correctly cleanup connection. 
Requires special handling with Qt5WebView widget, which typically closed too fast by Qt. 

3. Small bug fix with civetweb websocket handler - sometime it calls handler with empty data. Such calls should be just ignored.

### CODE REVIEW

**Comment by couet** [comment]
It looks fine with me. I will pull it today.

**Comment by bellenot** [comment]
While you're looking at it, could you fix the warnings reported there:
http://cdash.cern.ch/viewBuildError.php?type=1&buildid=379054
http://cdash.cern.ch/viewBuildError.php?type=1&buildid=379157

**Comment by linev** [comment]
> While you're looking at it, @linev could you fix the warnings reported there:

First warning is fixed, second warning is strange - for me is everything OK.

**Comment by bellenot** [comment]
It is on CentOS7, gcc62 and c++14 flag:
```
/.../root/gui/canvaspainter/v7/src/TCanvasPainter.cxx:697:32: warning: offset outside bounds of constant string
        conn->fGetMenu = cdata + 8;
```
Maybe one has to check the size of the string...

**Comment by linev** [comment]
conn->fGetMenu = cdata + 8;

> Maybe one has to check the size of the string...

One line before there is expression:

    strncmp(cdata, "GETMENU:", 8) == 0)

Means string has at least 8 characters. And in worse case `cdata+8` will be point on 0. I see no problem here.

**Comment by bellenot** [comment]
Well, all I can say is that this causes a warning, and it's the only one in our builds which is not green...

**Comment by linev** [comment]
Hi @couet @Axel-Naumann 

That about this PR?
Should I push new commits here?

**Comment by couet** [comment]
Hi Sergey. 
Bertand assigned this PR to me to check if the C++ part was correct. For me it is. Then he cam back to me saying I should wait to accept it because you need to fix some warning before. As soon as you think it is ok I can commit it.

**Comment by linev** [comment]
Hi Oliver,

There is "false-positive" warning in CentOS (see our discussion before)
It is about pointer arithmetic with `const char*`
I will change code in the future to avoid it.

Regards,
Sergey

**Comment by couet** [comment]
So what should I do ? I wait your green light to commit

**Comment by linev** [comment]
I suggest that you merge this PR.

With the next bunch of commits (later today or tomorrow) I also will try to solve problem with the warnings.

**Comment by couet** [comment]
OK I wait you next bunch of commits later today to merge it. Let me know.

**Comment by linev** [comment]
> OK I wait you next bunch of commits later today to merge it

You do not understand.
I will create separate pull request.
It is about usage of OpenUI5 library to build canvas interface.
And in that new PR I will add few modifications in CanvasPainter.cxx to solve warnings.

**Comment by couet** [comment]
Ah ok .. so I merge that one( #819 ) now ? ... Sorry I thought you wanted to add something to #819

**Pull request merged**
