### PR TITLE
[jsmva] fix operator precedence [skip-ci]

### PR DESCRIPTION
**Pull request by linev**
Also update minified file
Discovered with DeepCode

### CODE REVIEW

**Comment by linev** [comment]
@Axel-Naumann Can you approve it?

**Comment by Axel-Naumann** [comment]
What about https://github.com/root-project/root/pull/7691#issuecomment-806837596 ?

**Comment by Axel-Naumann** [comment]
ARGH me and reading :-)

**Review by Axel-Naumann — APPROVED** [review]

**Comment by linev** [comment]
> What about #7691 (comment) ?

Yes, found by LGTM code analyzers

**Pull request merged**
