### PR TITLE
[TDF] Comments and text fixes

### PR DESCRIPTION
**Pull request by bluehood**
`clang-format` will not be happy with the very long lines in the user guide, but on the other hand markdown only accepts table rows on a single line, so I think this case calls for an exception.

### CODE REVIEW

**Comment by bluehood** [comment]
travis complains about the long lines in the markdown tables as expected.
jenkins seems to have failed a build on mac1011 due to his own issues.

**Comment by peremato** [comment]
@bluehood why you run it with -Dimt=OFF?

**Comment by bluehood** [comment]
@peremato it's not me, now the jenkins bot is more verbose and specifies the options and platforms it builds with. those are the defaults.

**Comment by dpiparo** [comment]
Hi @peremato, the mixture of the imt and non-imt builds was not changed. Before proceeding to make the non-imt build a special case we decided at the PPP meeting to wait to have all tests green.

**Pull request merged**
