### PR TITLE
Revert "Temporary hack to survive (unnecessary) codegening of deseria…

### PR DESCRIPTION
**Pull request by vgvassilev**
…lized decls"

clang.git patch id: ffc388b

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Pull request merged**
