### PR TITLE
Remove make_unique and integer sequence STL backports

### PR DESCRIPTION
**Pull request by eguiraud**
Now that we require C++14 we can be sure the STL provides it.

### CODE REVIEW

**Review by guitargeek — APPROVED** [review]
Great, thanks! That surely works for RooFit.

**Comment by eguiraud** [comment]
The errors in VectorisedPDF are fixed by https://github.com/root-project/roottest/pull/730

**Review by etejedor — APPROVED** [review]

**Comment by eguiraud** [comment]
Let's see if the build is green now that `VectorisedPDF` does not include `RMakeUnique.hxx` anymore.

**Comment by eguiraud** [comment]
@phsft-bot build please

**Comment by eguiraud** [comment]
@phsft-bot build

**Pull request merged**
