### PR TITLE
[DF] In jitted lambdas, pass fundamental types by const value

### PR DESCRIPTION
**Pull request by eguiraud**
Rather than non-const reference. This has two advantages:
- passing fundamental types by value is slightly more efficient
- passing by const value helps avoiding typos such as `if (x = 0)`

This fixes ROOT-11009.

Reviewers, what do you think? Can this break any currently valid code?

- [x] add test

### CODE REVIEW

**Comment by stwunsch** [comment]
That's great! Out of curiousity: How does the error message look like for `Filter('x = 0')`?

**Review by stwunsch — APPROVED** [review]
LGTM, I like it!

**Review by hageboeck — APPROVED** [review]
The code looks like it's doing what it should be doing.

Regarding whether it's OK to do that:
- As discussed, we think it's alright, because power users can write their own lambdas that take by reference.
[ ] An entry in the release notes would be nice.
[ ] Maybe also a test.

**Comment by hageboeck** [comment]
> That's great! Out of curiousity: How does the error message look like for `Filter('x = 0')`?
> And I don't think that this breaks any existing code. Writing back to the input arguments is clearly a super weird thing in RDF and would rely on implementation details that are not visible to the user.

Very similar to this:
```
root [0] auto func = [](const double doub) {
 doub += 1.;
}
ROOT_prompt_1:1:6: error: cannot assign to variable 'doub' with const-qualified type 'const double'
doub += 1.;
~~~~ ^
ROOT_prompt_0:1:29: note: variable 'doub' declared const here
auto func = [](const double doub) {
               ~~~~~~~~~~~~~^~~~
```

**Comment by eguiraud** [comment]
Correct, more precisely:

```cpp
ROOT::RDataFrame(1).Define("x", "42").Filter("x = 42").Count().GetValue()
```
```
input_line_15:2:47: error: cannot assign to variable 'var0' with const-qualified type 'const int'
auto lambda1 = [](const int var0){return var0 = 42
                                         ~~~~ ^
input_line_15:2:29: note: variable 'var0' declared const here
auto lambda1 = [](const int var0){return var0 = 42
                  ~~~~~~~~~~^~~~
Error in <TRint::HandleTermInput()>: std::runtime_error caught: 
RDataFrame: An error occurred during just-in-time compilation. The lines above might indicate the cause of the crash
 All RDF objects that have not run an event loop yet should be considered in an invalid state.
```

**Comment by eguiraud** [comment]
Release notes are updated at https://github.com/root-project/root/pull/6530

**Comment by eguiraud** [comment]
All done, will merge if green

**Pull request merged**
