### PR TITLE
[core] Fix random crashes on Windows

### PR DESCRIPTION
**Pull request by bellenot**
Fix random crashes of the `imt101_parTreeProcessing` tutorial on Windows

### CODE REVIEW

**Review by hahnjo — APPROVED** [review]
All green - fantastic! Maybe give @pcanal a chance to take a quick look.

**Comment by bellenot** [comment]
> All green - fantastic! Maybe give @pcanal a chance to take a quick look.

I already asked him...

**Comment by pcanal** [comment]
Excellent fix!!

To reduce the number of lock being taken in the case of function with multiple arguments, can you check if using this patch *instead* also works:
```
diff --git a/core/base/inc/TPluginManager.h b/core/base/inc/TPluginManager.h
index 129ad1b078..0e44c803ed 100644
--- a/core/base/inc/TPluginManager.h
+++ b/core/base/inc/TPluginManager.h
@@ -169,6 +169,8 @@ private:
       auto name = typeid(std::tuple<T...>).name();
       if (!fArgTupleTypeInfo[nargs - 1].empty())
          return name == fArgTupleTypeInfo[nargs - 1];
+
+      R__LOCKGUARD(gInterpreterMutex);
       if (!CheckExactMatch<T...>(0, params...))
          return false;
       fArgTupleTypeInfo[nargs - 1] = name;
```

**Comment by bellenot** [comment]
@pcanal Done, it works as well. Thanks!

**Review by pcanal — APPROVED** [review]
LGTM.  Thanks.

**Pull request merged**
