### PR TITLE
Remove unused Python modules from PyROOT/cppyy tests by backporting commit from cppyy

### PR DESCRIPTION
**Pull request by pitkajuh**
# This Pull request:

This pull request removes unused Python modules (sys, os, py) from PyROOT/cppyy tests. The modules were imported in certain files, but they were not actually referenced in the code.

## Changes or fixes:

Changes PyROOT/cppyy test files by removing unused Python modules.

## Checklist:
[CTestCostData.txt](https://github.com/root-project/root/files/13743203/CTestCostData.txt)

- [X] tested changes locally
- [ ] updated the docs (if necessary)
[LastTest.log.gz](https://github.com/root-project/root/files/13743200/LastTest.log.gz)

### CODE REVIEW

**Comment by pitkajuh** [comment]
> Can you propose these changes upstream in https://github.com/wlav/cppyy and backport the commit here. That would enable us to upgrade to the upstream version easier.

Hello. Yes, I will do as you suggested.

**Comment by pitkajuh** [comment]
> Can you propose these changes upstream in https://github.com/wlav/cppyy and backport the commit here. That would enable us to upgrade to the upstream version easier.

Okay, so I created a pull request https://github.com/wlav/cppyy/pull/207 as you suggested. But I am not sure how to backport the commit here. Would you be able to guide me how to do it?

**Comment by vgvassilev** [comment]
> > Can you propose these changes upstream in https://github.com/wlav/cppyy and backport the commit here. That would enable us to upgrade to the upstream version easier.
> 
> Okay, so I created a pull request [wlav/cppyy#207](https://github.com/wlav/cppyy/pull/207) as you suggested. But I am not sure how to backport the commit here. Would you be able to guide me how to do it?

Once you get a review upstream then we can merge the same commit here.

**Comment by pitkajuh** [comment]
Dear All. Pull request https://github.com/wlav/cppyy/pull/207 has been merged.

**Review by vepadulano — APPROVED** [review]
Dear @pitkajuh , thank you so much! Before merging, can you squash the commit history to only show the one commit with the changes?

**Comment by pitkajuh** [comment]
> ou squ

I'm sorry I don't know what happened. Yesterday I tried to squash the commits, but I messed up something and I accidentally closed the PR. I have no idea how that happened. Nevertheless, the commits are now squashed. Is it possible to reopen the PR? I apologize for any inconvenience.

**Comment by vgvassilev** [comment]
Please remove the merge commits.

**Comment by guitargeek** [comment]
@phsft-bot build

**Pull request merged**
