### PR TITLE
Pair offset

### LINKED ISSUE #6840: TClass for pair sometimes have the wrong offset/size
Recent updated had made TClass::GetClass always returns an instance for std::pair even if there is no dictionary for the pair or it has not been instanced yet in the interpreter (step that can lead to autoparsing).
However, the offset and size calculations (guesses) in those cases is inadequate and sometimes leads to incorrect use (read/write) of the content of collection.  See for example: https://github.com/cms-sw/cmssw/issues/30359#issuecomment-728121661

### PR DESCRIPTION
**Pull request by pcanal**
Fix #6840. i.e Improve handling for std::pair without a dictionary.

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/defaul with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
Ready to merge.

**Review by Axel-Naumann — APPROVED** [review]

**Pull request merged**
