### PR TITLE
[cxxmodules] Load the dependent modules for both rootcling and rootcling_stage1

### PR DESCRIPTION
**Pull request by vgvassilev**
cc: @oshadura, @davidlange6, @smuzaffar

### CODE REVIEW

**Comment by vgvassilev** [comment]
@Axel-Naumann, weren't these failures in the master and then fixed?

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
I'm not aware of them being fixed. We have a report that might be related, https://sft.its.cern.ch/jira/browse/ROOT-10629

**Comment by vgvassilev** [comment]
Should we proceed with this PR and then fix the failures as we will have a reproducer?

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on ROOT-fedora30/cxx14 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug

I fail to reproduce this issue locally. Let's try to debug it at the bot.

**Comment by vgvassilev** [comment]
@phsft-bot build just on ROOT-fedora30/cxx14 with flags -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_BUILD_TYPE=RelWithDebInfo

**Comment by vgvassilev** [comment]
```cpp
cat repro.C 
#include <vector>
template <typename T>
struct Template {
   Template() {}
private:
   T m[12];
};

struct S {
   std::vector<Template<float> > use;
};

template class Template<std::vector<float> >;

void repro() {}

```

This reproduces the problem. It is seen only on `ROOT-fedora30/cxx14` with build config:

```
cmake  -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_FLAGS="-UNDEBUG" -DCMAKE_CXX_STANDARD="14" -DCMAKE_INSTALL_PREFIX="../install" -DLLVM_BUILD_TYPE="RelWithDebInfo" -Dalien="Off" -Darrow="Off" -Dasimage="On" -Dbuiltin_afterimage="On" -Dbuiltin_cfitsio="Off" -Dbuiltin_davix="On" -Dbuiltin_fftw3="Off" -Dbuiltin_freetype="Off" -Dbuiltin_ftgl="On" -Dbuiltin_gl2ps="On" -Dbuiltin_glew="On" -Dbuiltin_gsl="Off" -Dbuiltin_lz4="On" -Dbuiltin_lzma="On" -Dbuiltin_openssl="Off" -Dbuiltin_pcre="On" -Dbuiltin_tbb="On" -Dbuiltin_unuran="On" -Dbuiltin_vc="On" -Dbuiltin_vdt="On" -Dbuiltin_veccore="On" -Dbuiltin_xrootd="On" -Dbuiltin_xxhash="On" -Dbuiltin_zlib="On" -Dbuiltin_zstd="Off" -Dccache="ON" -Dcefweb="Off" -Dclad="On" -Dcocoa="Off" -Dcuda="Off" -Dcudnn="Off" -Ddataframe="On" -Ddavix="On" -Ddcache="Off" -Ddev="Off" -Dfail-on-missing="On" -Dfcgi="Off" -Dfftw3="On" -Dfitsio="On" -Dfortran="On" -Dgdml="On" -Dgfal="Off" -Dgsl_shared="Off" -Dgviz="Off" -Dhttp="On" -Dimt="On" -Dlibcxx="Off" -Dmathmore="On" -Dmemstat="Off" -Dminuit2="On" -Dmlp="On" -Dmonalisa="Off" -Dmpi="Off" -Dmysql="On" -Dodbc="Off" -Dopengl="On" -Doracle="Off" -Dpgsql="On" -Dpyroot="On" -Dpythia6="Off" -Dpythia6_nolink="Off" -Dpythia8="On" -Dqt5web="Off" -Dr="Off" -Droofit="On" -Droottest="ON" -Dshadowpw="On" -Dsoversion="On" -Dspectrum="On" -Dsqlite="On" -Dssl="On" -Dtesting="ON" -Dtmva="On" -Dtmva-cpu="On" -Dtmva-gpu="Off" -Dtmva-pymva="On" -Dtmva-rmva="Off" -Dunuran="On" -Dvc="On" -Dvdt="On" -Dveccore="On" -Dvecgeom="Off" -Dvmc="On" -Dwin_broken_tests="Off" -Dx11="On" -Dxml="On" -Dxrootd="On" ../root -G Ninjacmake  -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_CXX_FLAGS="-UNDEBUG" -DCMAKE_CXX_STANDARD="14" -DCMAKE_INSTALL_PREFIX="../install" -DLLVM_BUILD_TYPE="RelWithDebInfo" -Dalien="Off" -Darrow="Off" -Dasimage="On" -Dbuiltin_afterimage="On" -Dbuiltin_cfitsio="Off" -Dbuiltin_davix="On" -Dbuiltin_fftw3="Off" -Dbuiltin_freetype="Off" -Dbuiltin_ftgl="On" -Dbuiltin_gl2ps="On" -Dbuiltin_glew="On" -Dbuiltin_gsl="Off" -Dbuiltin_lz4="On" -Dbuiltin_lzma="On" -Dbuiltin_openssl="Off" -Dbuiltin_pcre="On" -Dbuiltin_tbb="On" -Dbuiltin_unuran="On" -Dbuiltin_vc="On" -Dbuiltin_vdt="On" -Dbuiltin_veccore="On" -Dbuiltin_xrootd="On" -Dbuiltin_xxhash="On" -Dbuiltin_zlib="On" -Dbuiltin_zstd="Off" -Dccache="ON" -Dcefweb="Off" -Dclad="On" -Dcocoa="Off" -Dcuda="Off" -Dcudnn="Off" -Ddataframe="On" -Ddavix="On" -Ddcache="Off" -Ddev="Off" -Dfail-on-missing="On" -Dfcgi="Off" -Dfftw3="On" -Dfitsio="On" -Dfortran="On" -Dgdml="On" -Dgfal="Off" -Dgsl_shared="Off" -Dgviz="Off" -Dhttp="On" -Dimt="On" -Dlibcxx="Off" -Dmathmore="On" -Dmemstat="Off" -Dminuit2="On" -Dmlp="On" -Dmonalisa="Off" -Dmpi="Off" -Dmysql="On" -Dodbc="Off" -Dopengl="On" -Doracle="Off" -Dpgsql="On" -Dpyroot="On" -Dpythia6="Off" -Dpythia6_nolink="Off" -Dpythia8="On" -Dqt5web="Off" -Dr="Off" -Droofit="On" -Droottest="ON" -Dshadowpw="On" -Dsoversion="On" -Dspectrum="On" -Dsqlite="On" -Dssl="On" -Dtesting="ON" -Dtmva="On" -Dtmva-cpu="On" -Dtmva-gpu="Off" -Dtmva-pymva="On" -Dtmva-rmva="Off" -Dunuran="On" -Dvc="On" -Dvdt="On" -Dveccore="On" -Dvecgeom="Off" -Dvmc="On" -Dwin_broken_tests="Off" -Dx11="On" -Dxml="On" -Dxrootd="On" ../root -G Ninja
```

**Comment by oshadura** [comment]
@vgvassilev I think most dependent PRs are merged, so this PR could be simplified...

**Comment by vgvassilev** [comment]
> Build failed on mac1015/cxx17.
> Running on macphsft18.dyndns.cern.ch:/Users/sftnight/build/jenkins/workspace/root-pullrequests-build
> [See cdash](http://cdash.cern.ch/index.php?project=ROOT&filtercount=1&field1=buildname/string&compare1=65&value1=PR-5443-mac1015-cxx17&date=2020-04-29).
> [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/console).
> ### Failing tests:
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_importROOT_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_importROOT_notebook/)
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_simpleCppMagic_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_simpleCppMagic_notebook/)
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_thread_local_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_thread_local_notebook/)
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_ROOT_kernel_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_ROOT_kernel_notebook/)
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_tpython_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79301/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_tpython_notebook/)

Fail with `sh: ipython3: command not found`



> Build failed on ROOT-fedora29/python3.
> Running on root-fedora29-3.cern.ch:/build/workspace/root-pullrequests-build
> [See cdash](http://cdash.cern.ch/index.php?project=ROOT&filtercount=1&field1=buildname/string&compare1=65&value1=PR-5443-ROOT-fedora29-python3&date=2020-04-29).
> [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79297/console).
> ### Failing tests:
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_simpleCppMagic_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79297/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_simpleCppMagic_notebook/)
> 
>     * [projectroot.roottest.python.JupyROOT.roottest_python_JupyROOT_importROOT_notebook](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/79297/testReport/projectroot.roottest.python/JupyROOT/roottest_python_JupyROOT_importROOT_notebook/)

Fail with `Parent appears to have exited, shutting down.`

Both seem unrelated to this PR.

**Comment by oshadura** [comment]
Fedora failures are not unrelated...

**Comment by smuzaffar** [comment]
@oshadura , https://github.com/cms-sw/cmsdist/pull/5791 should include this root change in cmssw. Hopefully in tonight's 23h IB

**Comment by vgvassilev** [comment]
@davidlange6 may want his change to be integrated tonight first and maybe the next round?

**Pull request merged**
