### PR TITLE
[ntuple] Add explicit EnableMT methods to RNTupleReader, Writer

### PR DESCRIPTION
**Pull request by mxxo**
Allow users to request multithreaded (de)compression even if IMT is not enabled globally with `ROOT::EnableImplicitMT()`. This required a change to `TTaskGroup` to avoid checking if IMT was enabled -- as I understand it, we can use TBB even if IMT isn't turned on because we don't use `RTaskArena`.

### CODE REVIEW

**Comment by jblomer** [comment]
Many thanks!  To me this looks fine.  As far as I can see, RNTuple is the only user of TTaskScheduler.  @Axel-Naumann @pcanal @eguiraud any objections to the `TTaskScheduler` change?

**Comment by jblomer** [comment]
Many thanks, to me this looks fine. @Axel-Naumann @pcanal @eguiraud any objections to the change in `TTaskGroup`?

**Comment by eguiraud** [comment]
Hi, some comments/questions:

1. I guess the behavior of `TTaskGroup` should mimic what `TThreadExecutor` does, e.g. it should use the task arena if it exists, and it should construct one if it doesn't. What's the rationale for doing things independently of ROOT's task arena? Does this mean users might see more cores used than they expect in some cases?
2. Are you ok with silently do nothing if R__IMT is undefined? Would it be better to print a warning?
3. Can we also have a way to disable RNTuple's multi-threading even if implicit MT is enabled, like TTree has?

**Comment by mxxo** [comment]
Hi Enrico, thank you very much for taking a look.

> 1. I guess the behavior of TTaskGroup should mimic what TThreadExecutor does, e.g. it should use the task arena if it exists, and it should construct one if it doesn't. What's the rationale for doing things independently of ROOT's task arena? Does this mean users might see more cores used than they expect in some cases?

I believe this change only removes an unnecessary restriction on when `TTaskGroup` can be used (i.e. after looking through the implementation, I don't think having IMT globally enabled is a precondition for the use of `TTaskGroup` and test benchmarks using this implementation seem to perform the same).

> 2. Are you ok with silently do nothing if R__IMT is undefined? Would it be better to print a warning?

Thank you, yes, a warning would probably be better.

> 3. Can we also have a way to disable RNTuple's multi-threading even if implicit MT is enabled, like TTree has?

Yes, this makes sense to me. It will probably need a big warning in the docs about when to call it and/or some graceful shutdown logic. Even if this PR doesn't make it that method might be valuable by itself.

> the rationale behind my question is that we should not have N different multi-threading behaviors for N components

I completely agree, it is very nice to be able to say "if you want multithreading, call `EnableImplicitMT` and you're done".

> and we should play well with the TBB settings of frameworks such as CMSSW, but it's not clear to me how we do that now, actually

For the RNTuple NanoAOD project, we were hoping to plug in the CMSSW tbb instance with `RPageStorage::SetTaskScheduler` (for both page sink and source): https://github.com/root-project/root/blob/a9c61d56afd70b74425779f330a4ec2cc581bb0b/tree/ntuple/v7/inc/ROOT/RPageStorage.hxx#L136

by implementing a derived `RTaskScheduler` on the CMSSW side so they have control over task isolation etc. 
https://github.com/root-project/root/blob/4118c0cb6db03998ae77f56f57cc372ac150c9df/tree/ntuple/v7/inc/ROOT/RPageStorage.hxx#L66-L76

**Comment by eguiraud** [comment]
> For the RNTuple NanoAOD project, we were hoping to plug in the CMSSW tbb instance with RPageStorage::SetTaskScheduler (for both page sink and source)

IIRC the current design is meant to play well with experiment frameworks' TBB thread pools, i.e. we should just use that if it exists. Is that not the case for RNTuple?

**Comment by mxxo** [comment]
There is some anecdata that ROOT's IMT is sometimes turned off because it has been said to interfere with the CMSSW tbb.

**Comment by eguiraud** [comment]
Might be, but the opposite of our intent :smile: we design for ROOT to work well with TBB-based frameworks (and afaik CMSSW does run with ROOT's IMT on), and we fix these sort of issues when they come up, e.g. https://sft.its.cern.ch/jira/browse/ROOT-11014 , https://sft.its.cern.ch/jira/browse/ROOT-10078

**Comment by jblomer** [comment]
I think it's a good point not to have too many nobs for turning on and off parallelism.  How about we expose the `SetTaskScheduler()` interface from `RNTupleReader` and `RNTupleWriter`.  So you'd either use all of IMT, or you explicitly diverge in RNTuple by providing your own task scheduler.

**Comment by eguiraud** [comment]
We probably have to discuss this for ROOT at large. `TTree` has a per-object IMT setting. Fitting has no knobs, only the global IMT settings. RDataFrame _for now_ has no knobs, but we were discussing with @Axel-Naumann that it might be useful if it did. RNTuple is thinking of using the scheduler itself as a customization point.

**Comment by jblomer** [comment]
In the context of RNTuple, this has concluded in #14831, #14807, #15724

Basically: fixing the use of the TBB task arena and adding IMT opt-out for RNTuple.

**Pull request closed without merging**
