### PR TITLE
[TMVA] Add API Support for RMSProp Optimizer:

### PR DESCRIPTION
**Pull request by ravikiran0606**
* Implement RMSProp Optimizer.
* Add Unit tests and MethodDL tests.

Reference Implementation: [Tensorflow RMSProp Optimizer](https://www.tensorflow.org/api_docs/python/tf/train/RMSPropOptimizer)

### CODE REVIEW

**Comment by ravikiran0606** [comment]
@lmoneta  @stwunsch  Can you please review? And for RMSProp the meanAbsoluteError is of the order of 1e-2. So I would like to discuss on the threshold value for testing the optimizer.

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by ravikiran0606** [comment]
@stwunsch @lmoneta  I updated the PR. Can you now review and trigger the build?

**Comment by lmoneta** [comment]
@phsft-bot build !

**Comment by stwunsch** [comment]
@build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by ravikiran0606** [comment]
@lmoneta  @stwunsch  I guess we are good to merge this :smile:

**Pull request merged**
