### PR TITLE
[webgui] add ping.cxx to tests

### PR DESCRIPTION
**Pull request by linev**
Let test webgui integrity
- if THttpServer work properly
- if JSROOT loads on client side
- if communication runs between server and clients

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@phsft-bot build

**Review by oshadura — APPROVED** [review]
LGTM! (failures are unrelated) and thanks a lot for moving tests in test directory!

**Comment by oshadura** [comment]
Example of failure:``` ava.lang.IllegalArgumentException: Could not instantiate {delegate={$class=XUnitBuilder, testTimeMargin=3000, thresholdMode=1, thresholds=[{$class=FailedThreshold, failureNewThreshold=0, failureThreshold=0, unstableNewThreshold=0, unstableThreshold=0}, {$class=SkippedThreshold, failureNewThreshold=, failureThreshold=, unstableNewThreshold=, unstableThreshold=}], tools=[{$class=CTestType, deleteOutputFiles=true, failIfNotNew=false, pattern=build/Testing/*/Test.xml, skipNoTestFiles=false, stopProcessingIfError=true}]}} for org.jenkinsci.plugins.workflow.steps.CoreStep: java.lang.UnsupportedOperationException: no known implementation of interface jenkins.tasks.SimpleBuildStep is named XUnitBuilder ```

**Comment by linev** [comment]
@oshadura 

There are also [real failures](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/116051/console) produced by new `root-webgui-ping` test, but I do not see any error output :(

**Comment by oshadura** [comment]
> @oshadura
> 
> There are also [real failures](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/116051/console) produced by new `root-webgui-ping` test, but I do not see any error output :(

ahhhhh.... I didn't notice, sorry!

**Comment by linev** [comment]
@phsft-bot build

**Pull request merged**
