### PR TITLE
Pass emit argument to TGNumberEntry::SetNumber

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Adds capability of not emitting a signal when calling SetNumber from user-code, in analogy with SetText.

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Review by bellenot — APPROVED** [review]
LGTM, thanks!

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by ferdymercury** [comment]
I think test fails because of https://github.com/root-project/root/commit/f68ed04667d7c2a4c99ecd44aea1f37252004f82
Maybe the cmake version can be change to the one from Ubuntu snap?

**Comment by bellenot** [comment]
@ferdymercury we are aware of the issue, thanks 🙂

**Pull request merged**
