### PR TITLE
Let ImplicitMT influence on THN::Fit() execution policy

### PR DESCRIPTION
**Pull request by xvallspl**
...so we don't need to write "MULTITHREAD" as fit option. Update the test.

### CODE REVIEW

**Comment by xvallspl** [comment]
For some reason I had problems making this work on gcc > 4.9.2, but It may be my configuration. This PR will test that too.

**Comment by xvallspl** [comment]
Passes the builds without vectorization.

Boh, I guess it was my problem 🤷‍♂️

**Comment by xvallspl** [comment]
@phsft-bot build with flags -Dbultin_veccore=ON -Dbuiltin_vc=ON

**Comment by xvallspl** [comment]
Applied formatting changes

**Comment by dpiparo** [comment]
Good that now this is streamlined.
Small note: this pr introduces warnings: http://cdash.cern.ch/viewBuildError.php?type=1&buildid=397963
Perhaps it would be good to address them before merging.

**Comment by xvallspl** [comment]
@dpiparo They are Vc warnings. The first one jumps in test-veccore, which I didn't touch, so I'm not sure I can do anything there... @amadio?

**Comment by dpiparo** [comment]
well, certainly you are able to do something...

**Comment by xvallspl** [comment]
With that I meant that these look like the Vc warnings we know we get on Mac, which people with way better knowledge than me on this area have tackled several times and, from last time I heard, not succeeded.

But I may also be mistaken, maybe that's not the cause or maybe there's some workaround in place until Vc is fixed.  Of course, I plan to discuss it, check it and confirm it. I can tag this as "do not merge" until then.

**Comment by amadio** [comment]
This is strange indeed, maybe that particular kind of warning is not suppressed in the headers. In any case, the warnings are not due to Xavi's code, but due to Vc. If the tests passed, I'd say the warnings are not a blocker and this can be merged.

**Comment by amadio** [comment]
That is, I will fix the warnings if they show up in the nightlies.

**Pull request merged**
