### PR TITLE
Pin the Roofit batch computation library to be used.

### PR DESCRIPTION
**Pull request by manolismih**
When RooFit starts for the first time it automatically loads the most optimal batch computation library. In response to issue #7361 I introduce an environment variable that permits the user to explicitly select the library to be used.

### CODE REVIEW

**Comment by manolismih** [comment]
In regards to ROOT builds with specific architectures: I believe that the users explicitly setting "-march=avx" or downloading a binary tagged as "avx" would assume that the code they are running is always avx. So it might surprise them negatively that the default runtime option I introduced is "find the most optimal computation library". On the other hand, it would also be a negative surprise if users get throttled down if their hardware supports a faster library than what they specified. The solution discussed in the Monday meeting was issuing a warning for that possible mismatch in CMake, in case the users have specified themselves a specific architecture. BUT, if we provide binaries, it's just us that will get the warning, so it's completely useless. What do you think?

**Comment by Axel-Naumann** [comment]
We should always give the most performant version to users (even those who pick up a ROOT build with `-march=...`). For experts we need to have a way to select a certain computational library, but I'm convinced that this should not be at configure time - again, to ensure that users get exposed to the most performant version.

**Review by Axel-Naumann — APPROVED** [review]

**Comment by manolismih** [comment]
> Looks good to me ! I agree with the implemented logic.
> 
> Maybe I have missed, and it is already there, but I think we should have an INFO message (also with gDebug=0), telling which type of library is loaded.

If you set gDebug to 0 you will get the message from SystemLoad().

**Comment by manolismih** [comment]
> We should always give the most performant version to users (even those who pick up a ROOT build with `-march=...`). For experts we need to have a way to select a certain computational library, but I'm convinced that this should not be at configure time - again, to ensure that users get exposed to the most performant version.

We have this, if they set `RooFit.ComputationLibraryArch=<arch>` in .rootrc they will get what they ask for.

**Comment by lmoneta** [comment]
This fixes #7361

**Pull request merged**
