### PR TITLE
Add detailed error message if RNTupleWriter::Write() fails

### LINKED ISSUE #14487: Assert when trying to write RNTuple to full disk
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Calling `ROOT::Experimental::RNTupleWriter::Recreate` with a path to a full disk results in an assert in RMiniFile.cxx about `fileStream` being bad.

A more useful error message would be appreciated.

### Reproducer

Should happen anytime you write to a full disk.

### ROOT version

------------------------------------------------------------------
  | Welcome to ROOT 6.31/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 21 2024, 23:43:23                 |
  | From heads/master@tags/v6-31-01                                  |
  | With g++ (GCC) 12.3.1 20230527                                   |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

### Installation method

CMSSW release

### Operating system

Linux alma 8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Nowakus**
# This Pull request:

## Changes or fixes:
Replaced somewhat cryptic 'assert failed' message with the actual I/O error message explaining what went wrong in RNTupleWriter::RFileSimple::Write()

## Checklist:

- [X] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #14487

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build

**Review by jblomer — COMMENTED** [review]
Very nice!  We may want to throw an `RException` instead, and I think we also want the better error message in `RFileProper`.

**Comment by Nowakus** [comment]
Switched to RException

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by Nowakus** [comment]
I suspect the tests may need to be updated

**Comment by Nowakus** [comment]
This PR should be good now

**Comment by dpiparo** [comment]
Hi @Nowakus I started the tests but leave all comments to @jblomer . One thing I can say already now is that a random file seems to be part of the changes at the moment and should perhaps be removed.

**Review by jblomer — CHANGES_REQUESTED** [review]
Thank you very much!

LGTM, but there is a `.asetup.save` file mistakenly part of the PR. Could you remove and rebase?

**Comment by Nowakus** [comment]
Random file removed

**Review by jblomer — APPROVED** [review]

**Comment by jblomer** [comment]
Replaced by #15007

**Pull request closed without merging**
