### PR TITLE
[modulemap] bits/chrono.h exists already with C++11:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
It is needed for C++11 support of #include <chrono>. Failures:
```
Processing /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C...
In file included from input_line_10:1:
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C:55:51: error: no member named 'duration' in namespace 'std::chrono'
         std::this_thread::sleep_for(std::chrono::duration<double, std::nano>(500));
                                     ~~~~~~~~~~~~~^
```

and

```
root [11] #include <bits/chrono.h>
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:432:10: error: module 'std.bits/chrono.h' requires feature 'cplusplus17'
  module "bits/chrono.h" [optional] {
         ^
ROOT_prompt_11:1:10: note: submodule of top-level module 'std' implicitly imported here
         ^
```

### CODE REVIEW

**Review by guitargeek — APPROVED** [review]
Thank you for the fix! Indeed, `duration` is C++11:
https://en.cppreference.com/w/cpp/chrono/duration

**Comment by vgvassilev** [comment]
Are we sure we are not picking this header from folder experimental?

**Comment by Axel-Naumann** [comment]
Yes.

**Comment by Axel-Naumann** [comment]
The mac13 llvm assert (module source Loc overflow?) is a real issue that we probably need to address before merging.

**Comment by Axel-Naumann** [comment]
@vgvassilev the same crash (overrun of Loc-IDs?) [happens in master](https://github.com/root-project/root/actions/runs/4738766741/jobs/8412967445),

```
2023-04-19T02:14:18.1147930Z Assertion failed: ((Val & ~(~0U >> (32-NumBits))) == 0 && "High bits set!"), function Emit, file BitstreamWriter.h, line 205.
2023-04-19T02:14:18.1150000Z Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
2023-04-19T02:14:18.1302820Z 0  rootcling_stage1         0x00000001079ce99c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
2023-04-19T02:14:18.1307960Z 1  rootcling_stage1         0x00000001079cd6c8 llvm::sys::RunSignalHandlers() + 64
2023-04-19T02:14:18.1311600Z 2  rootcling_stage1         0x00000001079cf06c SignalHandler(int) + 344
2023-04-19T02:14:18.1311820Z 3  libsystem_platform.dylib 0x000000018a46ea84 _sigtramp + 56
2023-04-19T02:14:18.1312270Z 4  libsystem_pthread.dylib  0x000000018a43fc28 pthread_kill + 288
2023-04-19T02:14:18.1312500Z 5  libsystem_c.dylib        0x000000018a34dae8 abort + 180
2023-04-19T02:14:18.1312650Z 6  libsystem_c.dylib        0x000000018a34ce44 err + 0
2023-04-19T02:14:18.1316460Z 7  rootcling_stage1         0x0000000107c022f4 clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) (.cold.1) + 0
2023-04-19T02:14:18.1319720Z 8  rootcling_stage1         0x00000001052efcac llvm::BitstreamWriter::Emit(unsigned int, unsigned int) + 228
2023-04-19T02:14:18.1322880Z 9  rootcling_stage1         0x0000000105307ebc void llvm::BitstreamWriter::EmitRecordWithAbbrevImpl<unsigned long long>(unsigned int, llvm::ArrayRef<unsigned long long>, llvm::StringRef, llvm::Optional<unsigned int>) + 676
2023-04-19T02:14:18.1325880Z 10 rootcling_stage1         0x00000001052e4f8c clang::ASTRecordWriter::Emit(unsigned int, unsigned int) + 228
2023-04-19T02:14:18.1328900Z 11 rootcling_stage1         0x000000010532fde4 clang::ASTWriter::WriteDecl(clang::ASTContext&, clang::Decl*) + 416
2023-04-19T02:14:18.1332000Z 12 rootcling_stage1         0x00000001052f2b10 clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) + 11872
2023-04-19T02:14:18.1335020Z 13 rootcling_stage1         0x00000001052efb14 clang::ASTWriter::WriteAST(clang::Sema&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*, llvm::StringRef, bool, bool) + 196
2023-04-19T02:14:18.1337980Z 14 rootcling_stage1         0x000000010534689c clang::PCHGenerator::HandleTranslationUnit(clang::ASTContext&) + 260
2023-04-19T02:14:18.1341040Z 15 rootcling_stage1         0x0000000104ff3ef0 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 52
2023-04-19T02:14:18.1344070Z 16 rootcling_stage1         0x0000000105159a84 clang::ParseAST(clang::Sema&, bool, bool) + 504
2023-04-19T02:14:18.1347070Z 17 rootcling_stage1         0x0000000104fb70b4 clang::FrontendAction::Execute() + 112
2023-04-19T02:14:18.1350270Z 18 rootcling_stage1         0x0000000104f3e7c0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 828
2023-04-19T02:14:18.1353270Z 19 rootcling_stage1         0x0000000104f4ba84 void llvm::function_ref<void ()>::callback_fn<compileModuleImpl(clang::CompilerInstance&, clang::SourceLocation, llvm::StringRef, clang::FrontendInputFile, llvm::StringRef, llvm::StringRef, llvm::function_ref<void (clang::CompilerInstance&)>, llvm::function_ref<void (clang::CompilerInstance&)>)::$_4>(long) + 56
2023-04-19T02:14:18.1356440Z 20 rootcling_stage1         0x0000000107910410 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 212
2023-04-19T02:14:18.1359590Z 21 rootcling_stage1         0x0000000104f44bf4 compileModuleImpl(clang::CompilerInstance&, clang::SourceLocation, llvm::StringRef, clang::FrontendInputFile, llvm::StringRef, llvm::StringRef, llvm::function_ref<void (clang::CompilerInstance&)>, llvm::function_ref<void (clang::CompilerInstance&)>) + 3096
2023-04-19T02:14:18.1362510Z 22 rootcling_stage1         0x0000000104f414d8 compileModuleAndReadAST(clang::CompilerInstance&, clang::SourceLocation, clang::SourceLocation, clang::Module*, llvm::StringRef) + 1820
2023-04-19T02:14:18.1365490Z 23 rootcling_stage1         0x0000000104f40984 clang::CompilerInstance::findOrCompileModuleAndReadAST(llvm::StringRef, clang::SourceLocation, clang::SourceLocation, bool) + 2456
2023-04-19T02:14:18.1368510Z 24 rootcling_stage1         0x0000000104f4355c clang::CompilerInstance::loadModule(clang::SourceLocation, llvm::ArrayRef<std::__1::pair<clang::IdentifierInfo*, clang::SourceLocation> >, clang::Module::NameVisibilityKind, bool) + 7272
2023-04-19T02:14:18.1371800Z 25 rootcling_stage1         0x00000001075f35d0 clang::Preprocessor::HandleHeaderIncludeOrImport(clang::SourceLocation, clang::Token&, clang::Token&, clang::SourceLocation, clang::DirectoryLookup const*, clang::FileEntry const*) + 4744
2023-04-19T02:14:18.1375060Z 26 rootcling_stage1         0x00000001075ed5d4 clang::Preprocessor::HandleIncludeDirective(clang::SourceLocation, clang::Token&, clang::DirectoryLookup const*, clang::FileEntry const*) + 180
2023-04-19T02:14:18.1378280Z 27 rootcling_stage1         0x00000001075eded0 clang::Preprocessor::HandleDirective(clang::Token&) + 1844
2023-04-19T02:14:18.1381530Z 28 rootcling_stage1         0x00000001075c4740 clang::Lexer::LexTokenInternal(clang::Token&, bool) + 5768
2023-04-19T02:14:18.1384800Z 29 rootcling_stage1         0x00000001075c21b8 clang::Lexer::Lex(clang::Token&) + 96
2023-04-19T02:14:18.1388090Z 30 rootcling_stage1         0x00000001076264d0 clang::Preprocessor::Lex(clang::Token&) + 104
2023-04-19T02:14:18.1391130Z 31 rootcling_stage1         0x00000001052037bc clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) + 96
2023-04-19T02:14:18.1394070Z 32 rootcling_stage1         0x0000000104b404c8 cling::IncrementalParser::ParseInternal(llvm::StringRef) + 1344
2023-04-19T02:14:18.1397290Z 33 rootcling_stage1         0x0000000104b3f85c cling::IncrementalParser::Initialize(llvm::SmallVectorImpl<llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > > >&, bool) + 628
```

As it's unrelated to this PR I will merge this.

**Pull request merged**
