### PR TITLE
[rootcling] Deprecate -r flag

### PR DESCRIPTION
**Pull request by reikdas**
@vgvassilev

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

@reikdas could you describe this in the release notes here: https://github.com/root-project/root/blob/master/README/ReleaseNotes/v620/index.md#deprecation-and-removal

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
why are we removing/deprecating the -r option "now", isn't that too soon (i.e. are the rootmap file deprecated this release?)

**Comment by vgvassilev** [comment]
That's a good question. I did not see a practical use case for this in first place. It seems it has been introduced quite long ago in root-project/root@64e9dbe5c72c0ccc8a942e8cec19fbdfe81200bd However, it did not have any documentation (besides the commit message) and I doubt it was picked up by the users.

The rootmaps are not deprecated by the release in the usual meaning of deprecation. From this release onward the rootmap files should be considered a legacy feature. We should limit their use because we have a superior system.

I do not think the deprecation is premature. It will give us a better understanding if we need this option. If we do we should have something similar with modules, if we don't it would reduce the complexity of rootcling.

**Comment by Axel-Naumann** [comment]
We can deprecate rootmap files as soon as we can deprecate use of ROOT with rootmap files. Almost all experiments will be unable to do so for years to come, and there is Windows. As is, we cannot deprecate rootmap files.

**Comment by vgvassilev** [comment]
Agreed. We are not talking about deprecating the rootmap files at all in this PR or outside.

**Comment by vgvassilev** [comment]
This seems to have a valid use case. Given the release time frame, I'd feel much more comfortable in reverting this until we figure out the corner cases.

**Pull request merged**
