### PR TITLE
[TDF] Split TDataFrame.hxx into multiple files

### PR DESCRIPTION
**Pull request by bluehood**
This PR is a work-in-progress. Submitting mainly to get feedback and test on all platforms (it compiles and tests run on my machines).

`TDataFrame.hxx` neared the 2000 lines, so I decided to bite the bullet and disentangle it in logically separated parts. `TDataFrame`'s functionality is now divided as follows:

- `TDataFrame.{hxx,cxx}`: class `TDataFrame`
- `TDataFrameInterface.{hxx,cxx}`: class `TDataFrameInterface`
- `TDFNodes.{hxx,cxx}`: class `TDataFrameImpl`, `TDataFrameAction{,Base}`, `TDataFrameBranch{,Base}`, `TDataFrameFilter{,Base}`
- `TActionResultProxy.hxx`: class `TActionResultProxy`
- `TDFOperations.{hxx,cxx}`: all `*Operation` classes
- `TDFTraitsUtils.hxx` -> `TDFUtils.{hxx,cxx}`: all helper functions and meta-helpers

I also ran `clang-format` and `include-what-you-use` on these files to improve coding style and useless/misplaced includes. I plan to squash all commits into just two/three (one for splitting, one for formatting, one for the includes) if/when the changes will be green-lit.

**Open issues**
- [ ] `TActionResultProxy::TriggerRun` is still in `TDataFrame.hxx` because it depends on TDataFrameImpl. Moving it into `TActionResultProxy.hxx` would cause a circular include dependency
- [ ] `ColumnName2ColumnTypeName` is in `TDataFrameInterface.{hxx,cxx}`, but being an helper function it should actually be in `TDFUtils.hxx`. This would cause a circular include dependency with `TDFNodes.hxx` due to `TDataFrameImpl`
- [ ] same for `CallCreateAction`, but the circular dependency is with `TActionResultProxy`. This function is much less general than the former though, so maybe it could stay in `TDataFrameInterface.{hxx,cxx}`
- [ ] `TSlotStack` is now declared and defined at namespace scope in `TDFNodes.cxx`. Declaration and definitions should be split, the class itself should probably be nested inside `TDataFrameImpl`

### CODE REVIEW

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by bluehood** [comment]
Alright, so the only test failing is `roottest/dataframe/test_glob.C`. It is not clear to me why the interpreter does not find methods like `TDataFrameImpl::Book`. Changing roottest to pass `test_glob.C+` rather than `test_glob.C` solves the problem on my machines. That is actually how the other macros are processed in `roottest/root/dataframe`.

I am not sure whether this is expected behavior, so I am not sure how to proceed.

**Comment by dpiparo** [comment]
Thanks for this fine refactoring. Merged.

**Comment by bluehood** [comment]
Thanks!

N.B.
each of the open issues described in my original has a relevant `TODO` comment in the source

**Pull request closed without merging**
