### PR TITLE
[doxy] Enable compilation of macros

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Allows macros to be compiled when building docu, as suggested by couet in https://github.com/root-project/root/pull/10004#pullrequestreview-916874733

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by couet** [comment]
In https://github.com/root-project/root/pull/10004#pullrequestreview-916874733 I met the other .C macro in the doxygen/folder, this used to make the doc. Not all the tutorials.

**Comment by ferdymercury** [comment]
> In [#10004 (review)](https://github.com/root-project/root/pull/10004#pullrequestreview-916874733) I mean the other .C macros in the doxygen/folder, this used to make the doc. Not all the tutorials.

Oh, I see. But those macros in the doxygen folder call themselves another macros, so I was just updating the ones that are being called (not all tutorials explicitly) because otherwise it gives an error when trying to compile them. Should I revert those changes?

**Comment by Axel-Naumann** [comment]
We intentionally keep macros "illegal C++": we have a C++ interpreter and we should benefit from this, removing parts of C++ not needed for interactive use, *especially* for tutorials. We find this simplifies the tutorials. We have exceptions for tutorials where we believe many uses will be compiled.  

Being able to compile the tutorials isn't a benefit in and by itself. This PR here came out of https://github.com/root-project/root/pull/10004 which claims "Precompiles C++ script to potentially speedup (slightly) documentation building". If that's indeed correct then that's a bug in cling. cling must be as fast as compiled code (if using the same optimizer, the same clang version as cling links against etc). So I'd like to better understand the motivation of this?

**Comment by ferdymercury** [comment]
The main motivation concerning speedup is that currently, the documentation takes between 5 and 7 hours to build, which makes it hard to debug and improve.

The 'slow part' happens in 'filter.cxx' (which does some parsing that slows down doxygen), as well as when the tutorials are run.

That being said, I did not benchmark if pre-compiling makes things considerably faster, so maybe this PR is not worth it, I agree...

**Comment by ferdymercury** [comment]
On the other hand, I have prepared a rehauled-version that is thread-safe so that doxygen can run in parallel: https://github.com/root-project/root/pull/9966#issuecomment-1055977012

(Here I did check that things were faster.)

**Pull request closed without merging**
