### PR TITLE
Fix bias in RANLUX++

### PR DESCRIPTION
**Pull request by hahnjo**
From a high-level perspective, this PR does two things:
 * It converts the LCG state back to RANLUX numbers to avoid a bias in the generated numbers as reported by Martin Lüscher. This comes from the fact that the modulus `m = 2 ** 576 - 2 ** 240 + 1` is not a power of 2, so just treating the LCG state as a pool of entropy means that the  upper `576 - 240 = 336` bits have a higher probability of being 0 than 1.
 * Extract only 48 bits instead of 52 bits per random number. This restores the connection to the theoretical properties derived from understanding the original subtract-with-borrow recursion as a dynamical system.

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
Excellent work! I'm a bit worried about the dir name `RANLUX++`, whether all file systems will happily do that. Maybe `ranluxpp`? `ranluxxx` looks... easily inappropriate :-)

**Review by lmoneta — APPROVED** [review]
Looks very  good !!
Thank you Jonas for this great improvement !

**Comment by hahnjo** [comment]
> I'm a bit worried about the dir name `RANLUX++`, whether all file systems will happily do that. Maybe `ranluxpp`? `ranluxxx` looks... easily inappropriate :-)

Yes, I'll go with `ranluxpp` as we're already using this in `RanluxppEngine` and the corresponding file names :+1:

**Comment by hahnjo** [comment]
Passed multiple runs with `TestU01` using different seeds (the default seed leads to one warning with p-value being exactly the threshold `0.9990`) and the "compatibility engines" I wrote some weeks ago (will submit after cleaning up the code) still produce the values that I extracted from GSL and `std::ranlux{24,48}`. Will merge tomorrow morning, unless there are further comments.

**Pull request merged**
