### PR TITLE
http: use proper arguments of pthread_setname_np on OS X

### PR DESCRIPTION
**Pull request by linev**
This is alternative to #2581 
Lets check if it compiles better

### CODE REVIEW

**Comment by linev** [comment]
This patch was applied to civetweb repository: https://github.com/civetweb/civetweb/pull/652

**Comment by vgvassilev** [comment]
@phdft-bot build just on slc6/clang_gcc62

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On

**Comment by linev** [comment]
@phsft-bot build

**Pull request merged**
