### PR TITLE
[mathmore] Remove license-incompatible KelvinFunctions.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Part of ROOT-10992

### CODE REVIEW

**Comment by pcanal** [comment]
Is moving it to `MathMore` an option?

**Comment by Axel-Naumann** [comment]
It is already in mathmore. The license is simply not FOSS (read it carefully if you care).

**Comment by Axel-Naumann** [comment]
```
// *** THIS SOFTWARE CAN NOT BE USED FOR COMMERCIAL GAIN. ***
```

**Comment by guitargeek** [comment]
Also, check this out:
https://codecogs.com/library/maths/special/bessel/kelvin.php
> Source code is available when you buy a [Commercial](https://codecogs.com/pages/licences/com.php) licence.

And then in the commercial license it says:
> You **cannot** distribute source code behind the CodeCogs Software.

By the way, other components of codecogs have different license options, for example [this one](https://www.codecogs.com/library/engineering/fluid_mechanics/waves/dispersion.php):
> Source code is available when you agree to a [GP Licence](https://www.codecogs.com/pages/licences/gpl.php) or buy a [Commercial Licence](https://www.codecogs.com/pages/licences/com.php).

Maybe the Kelvin functions were also possible to be used with the GPL, but at least now this doesn't seem to be possible, as only the commercial license gives you access to the source code.

With this, I would also come to the conclusion that that the code needs to be removed ASAP.

**Comment by pcanal** [comment]
Thanks for clarifying.

**Review by pcanal — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
Failures seem unrelated.

**Pull request merged**
