### PR TITLE
[TDF] Add TDF::Not helper and relevant gtest

### PR DESCRIPTION
**Pull request by bluehood**

### CODE REVIEW

**Comment by dpiparo** [comment]
Very nice PR. The negation functionality will be a clear upgrade of the present infrastructure. For what concerns Filter and Map, I am in favour of keeping them but *maybe* it could be discussed what is their interplay with the ones provided by VecOps for TVecs (#1613). I am of course ready to revise the implementations in #1613.

**Comment by bluehood** [comment]
@phsft-bot build

**Comment by bluehood** [comment]
since #1613 now implements equivalents of `TDF::Map` and `TDF::Filter` as part of the VecOps, the only helper left here is `TDF::Not`. I'm sure more will come in the future :)

**Comment by bluehood** [comment]
@Axel-Naumann does v7 have these kind of v7 utilities? if yes how is the header that contains them called?

For now TDF users do `#include <ROOT/TDataFrame.hxx>` and this PR would add an optional `#include <ROOT/TDFHelpers.hxx>`, but I was wondering if there's a convention there.

**Comment by bluehood** [comment]
@phsft-bot build

**Pull request merged**
