### PR TITLE
Fix root-config now that 'thread' option is always enabled

### PR DESCRIPTION
**Pull request by amadio**
See commit message for more details.

### CODE REVIEW

**Comment by vgvassilev** [comment]
What would be the way to enable debug for llvm?

**Comment by amadio** [comment]
With `-DLLVM_BUILD_TYPE=Debug`.

**Comment by amadio** [comment]
I think the fixes for threads need more work, I will exclude some commits and re-test. Only the fix to root-config should be strictly required for now.

**Comment by Axel-Naumann** [comment]
@amadio can you please split the llvm debug commit into a separate PR? We need to get this in ASAP to get our windows nodes stable again, and the other changes are a distraction from that. While certainly useful (not preempting Philippe's review), they live on a different timescale than the llvm debug commit. Thanks!

**Comment by amadio** [comment]
@Axel-Naumann Done, it's now in pull request #4348.

**Comment by amadio** [comment]
Looks like the mac build just got aborted. I will remove the LLVM change, since it's in a separate PR and re-run Jenkins.

**Pull request merged**
