### PR TITLE
Add builtin_cfitsio option for Windows

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build with flags -Dbuiltin_cfitsio=ON -Dccache=ON

**Comment by bellenot** [comment]
@phsft-bot build with flags -Dbuiltin_cfitsio=ON -Dccache=ON

**Comment by bellenot** [comment]
@amadio Can you review this PR, please? Thanks!

**Comment by amadio** [comment]
Sorry, I've seen it before, but forgot to add the review. Cheers,

**Comment by bellenot** [comment]
> Sorry, I've seen it before, but forgot to add the review. Cheers,

No problem, thanks!

**Pull request merged**
