### PR TITLE
protect fIsRunning from TThread, and fix typo

### PR DESCRIPTION
**Pull request by ferdymercury**
Addresses one of the issues on https://github.com/root-project/root/issues/8365

Namely, TThread::Printf() causing a data race with TApplication::Run()

```
TApplication::IsRunning() const (TApplication.h:148)
TThread::XARequest(char const*, int, void**, int*) (TThread.cxx:1029)
This conflicts with a previous write of size 1 by thread #1
TApplication::Run(bool) (TApplication.cxx:1622)
```

After this fix, the error disappears from helgrind.

### CODE REVIEW

**Comment by pcanal** [comment]
Would an alternate solution be:
```
   std::atomic<Bool_t>             fIsRunning;       //True when in event loop (Run() has been called)
```
?

**Comment by ferdymercury** [comment]
I had tried that too, but Helgrind gave an error on the 'atomic' library, not sure why. Thus I switched to the gROOTMutex.

**Comment by pcanal** [comment]
I am not sure why it complains about "that" (new) atomic in particular, we used atomics quite a bit in the rest of the code.

**Comment by ferdymercury** [comment]
Amended.

I am seeing a similar issue with TSystem.h, `TSeqCollection  *fTimers{nullptr};           //List of timers`

There are data races when adding and removing timers from the list. Should I change it there also to atomic? (In this PR or in a separate one?)

**Comment by pcanal** [comment]
> I am seeing a similar issue with TSystem.h, TSeqCollection *fTimers{nullptr}; //List of timers

I think we should tackle this in a separate PR.  The simplest solution though is to always create the fTimers (i.e. move its creation to the constructor or init routine) and to mark it as a 'thread safe' collection:
```
fTimers->UseRWLock();
```
thanks.

**Comment by pcanal** [comment]
>  Maybe defining a gTimersMutex would do the job

Adding case specific mutex requires to make '100% sure' that the code in the critical section can *\*never\** take/request the ROOT global lock [An example innocuous looking case is the calls to TObject::Error which will interrogate the related TClass object and thus sometimes request the global lock].  Failure to insure this lack of global lock taking will (inevitably) lead to dead locks.

**Comment by pcanal** [comment]
>  The simplest solution though is to always create the fTimers 

Also I noted that TOrdCollection (the type of fTimes at the moment) has not been upgraded yet to support ```UseRWLock()``` (it will silently ignore it), so we will need to also change the type to ```TList```

**Comment by pcanal** [comment]
> Maybe atomic_base has to be added to the suppression file? 

Yep, you are right :)

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
The roofit error on ROOT-ubuntu16/nortcxxmod are pre-existing (see https://github.com/root-project/root/pull/3760#issuecomment-858157849)

**Comment by pcanal** [comment]
Thanks!

**Pull request merged**
