### PR TITLE
[RDF] Fix ROOT-9898

### PR DESCRIPTION
**Pull request by bluehood**
Backport #3248 to v6.16

### CODE REVIEW

**Comment by bluehood** [comment]
@phsft-bot build please

**Comment by dpiparo** [comment]
@phsft-bot build please

**Comment by bluehood** [comment]
This PR now also includes #3257 (second part of the fix)

**Comment by bluehood** [comment]
@phsft-bot build

**Comment by bluehood** [comment]
@dpiparo @Axel-Naumann this PR fixes the use after delete reported in [ROOT-9898](https://sft.its.cern.ch/jira/browse/ROOT-9898).

The last build passed, I started another one _just to be sure_.

I assigned the PR to you because I don't have permission to merge in v6.16 and I don't know if you want it in or not before the release.

**Comment by bluehood** [comment]
@phsft-bot build

**Pull request merged**
