### PR TITLE
[clang] Fix crash with constexpr destructor [v6.28]

### PR DESCRIPTION
**Pull request by hahnjo**
Fixes https://github.com/root-project/root/issues/13851
See also https://github.com/llvm/llvm-project/issues/68702

(cherry picked from commit 0919a5359eefda0fc9e56a3198da21596114d62f)

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build just on windows10/default

**Comment by hahnjo** [comment]
Hi @bellenot, can you help me understand the issue on Windows? I see the same happened in https://github.com/root-project/root/pull/13793, is this something to worry about?

**Comment by bellenot** [comment]
I cleaned that machine. Let's try again...

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/default

**Comment by hahnjo** [comment]
Thanks @bellenot!

**Pull request merged**
