### PR TITLE
Add support for distributed RDataFrame constructed from RDatasetSpec

### PR DESCRIPTION
**Pull request by gwmyers**
# This Pull request:
Add support for experimental distributed RDataframe when the RDataframe is constructed from an RDatasetSpec object. See https://root-forum.cern.ch/t/using-rdataframe-with-dask-and-rdatasetspec/58230

## Changes or fixes:
 - Add a class to [HeadNode.py](bindings/experimental/distrdf/python/DistRDF/HeadNode.py) to handle the case where the RDataframe with distributed backend is constructed from an RDatasetSpec object
 - Use the above class when constructing the appropriate RDataframe instance

## Checklist:

- [x] tested changes locally
- [x] updated the docs (N/A)

This PR fixes #

### CODE REVIEW

**Review by vepadulano — COMMENTED** [review]
@gwmyers Thank you so much for your contribution! You are pretty much spot on! I have added a couple of tests and now the CI is running, if all looks good afterwards I'd say we could already merge this PR

**Comment by gwmyers** [comment]
Hi @vepadulano , Great! Thanks! Please let me know if I can help with anything!

**Review by vepadulano — APPROVED** [review]
Very nice, thanks! I think this is good to go for a first step, I will take care of adding more complicated tests in roottest to check the integration with dask/spark.

**Comment by vepadulano** [comment]
@phsft-bot build

**Pull request merged**
