### PR TITLE
TThread Printf fix memleak

### PR DESCRIPTION
**Pull request by ferdymercury**
see https://github.com/root-project/root/issues/8297
(This leak seems to be there since https://github.com/root-project/root/commit/656be4df3a8ccbf8cb749bd862d71f1690fbd2c5)

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
Yikes thanks!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by ferdymercury** [comment]
Thanks so much for the merge :)
Do you think the other valgrind leaks are real ones or just need to be suppressed? https://github.com/root-project/root/issues/8297

**Comment by Axel-Naumann** [comment]
*You* did all the work here! Thank you, Ferdy!

I'll reply in the issue.

**Pull request merged**
