### PR TITLE
[WIP][TDF] Add a column by default which carries the entry number

### PR DESCRIPTION
**Pull request by dpiparo**
the column is called __TDF_iEvent__ and is of type ULong64_t.

This is how it works:
```
root [0] ROOT::Experimental::TDataFrame d(10)
(ROOT::Experimental::TDataFrame &) A data frame that will create 10 entries

root [1] d.Foreach([](ULong64_t e){cout << e << endl;}, {"__TDF_iEvent__"})
0
1
2
3
4
5
6
7
8
9
```

### CODE REVIEW

**Comment by bluehood** [comment]
Cool and useful! It's nice how this feature became easy to implement thanks to recent unrelated improvements.

I think we should use a name that's easier to remember for users, and we should document very well what this number corresponds to in the various cases (e.g. when running on a TChain).

Also as a personal preference I would move down the setup of the column to `TLoopManager`'s constructor, as this is "not `TInterface`'s business" in a sense. What do you think?

**Comment by bluehood** [comment]
The test failures related to `Report` are because of the check [here](https://github.com/dpiparo/root/blob/a298979465295915a17b2ef1b7e82afa81d51660/tree/treeplayer/inc/ROOT/TDFInterface.hxx#L1403-L1404).

It's not true anymore that if `!fValidColumns.empty()` then the node is the result of a `TLoopManager` + at least one `Define`. Now the condition is `fValidColumns.size() > 1`. I wonder whether we could do something better there.

**Comment by dpiparo** [comment]
1) I agree that the name is less than optimal. As a matter of fact, I wonder if this should be always by default or something the user can decide to have.
2) For defining the column in the TLoopManager, good idea.
3) The test failures are ~expected. Nothing was done to prevent those yet, this PR was submitted to kick off discussion (and succeded)
4) For the doc, that's, as always, understood that the documentation should be high quality.

**Comment by pcanal** [comment]
Why do we need an actual column (taking memory)?  Isn't the entry number (at least the one hereby defined) always passed to the function(s) directly and/or indirectly?

**Comment by dpiparo** [comment]
The issue needs to be looked at from the C++ and PyROOT perspective with a programming model in mind. But let me start from the technical answers, which are easier:
1) The memory taken by the "entry number custom column" is one 64 bit integer per slot, so negligible
2) Correct: Both slot and entry number are available at the TDF level, the difficulty is to percolate them in the actual function in the define/filter

Focussing only on C++, one could think about a "TDF::EntryNumber" type. We could detect it if used as first argument of the function passed and pass the entry. Such type will be transparently convertible to a 64-bits integer. As a side note, also the slot could be treated similarly. The issue will be in PyROOT, with filters and defines expressed as strings which are then jitted: these types make sense only if present in the signature of the function.

If we go for the custom column solution, we know exactly what to do, we tested heavily all the components involved but we have to choose a name: "__TDF_iEntry", "__Entry", "__iEntry" .
Certainly starting with a "__slot" and "__entry" could be very attractive since it will provide 
a. The slot and the entry if needed
b. The steps needed for the implementation are already well understood
c. There is very little overhead - custom columns' lambdas are invoked only if the column is actually used
d. Would seamlessly work in PyROOT

**Pull request merged**
