### PR TITLE
Print instructive error message if builtin_llvm=off

### PR DESCRIPTION
**Pull request by wiene**
Fixes bug [ROOT-9186](https://sft.its.cern.ch/jira/browse/ROOT-9186).

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks, @wiene ! Indeed - we have upstreamed llvm patches but not yet all of those on clang.

@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by wiene** [comment]
@Axel-Naumann, looking at the build logs, it seems to me that there is a problem with the CI system: "No space left on device". Could you have a look at it?

**Comment by Axel-Naumann** [comment]
Yes we're aware and working on a fix.

**Comment by vgvassilev** [comment]
LLVM is technically patch free. We can teach our build system to try to find LLVM 5.0 and use it. The tricky part is that we still need to build clang (we should probably set the `LLVM_EXTERNAL_CLANG_SOURCE_DIR`).

**Pull request merged**
