### PR TITLE
[MT][ROOT-9901] Replace usage of strtok in core and hist

### PR DESCRIPTION
**Pull request by dpiparo**
and protect the TUrl class from races.

### CODE REVIEW

**Comment by dpiparo** [comment]
@phsft-bot build just on windows10/default

**Comment by dpiparo** [comment]
@phsft-bot build just on windows10/default

**Comment by dpiparo** [comment]
thanks bot.

**Comment by dpiparo** [comment]
@bellenot : I could use some help with the errors :) http://cdash.cern.ch/viewBuildError.php?buildid=616819
Can you see what went wrong?

**Comment by dpiparo** [comment]
I pushed a workaround. Hopefully it works.

**Comment by bellenot** [comment]
@dpiparo BTW, the [c++ standard](https://en.cppreference.com/w/c/string/byte/strtok) mention `strtok_s`, not `strtok_r`

**Comment by dpiparo** [comment]
It's C standard but *nice*.

**Pull request merged**
