### PR TITLE
[tmva][sofie] Fix Gather and Squeeze operators and some memory issues in ConvTranspose

### PR DESCRIPTION
**Pull request by lmoneta**
This Pull request fixes some issues fond with valgrind in the ConvTranspose operator
and fixes the Gather and Reshap operators

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/cxx17, ROOT-ubuntu2004/default

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
v6-28: 186fb50dedbfe70a2273108c276c4fb7649eaeb4 + a953141e1f4928765da758cc96ec633d1521fb68

**Pull request merged**
