### PR TITLE
Added make uninstall

### PR DESCRIPTION
**Pull request by reikdas**
This is in reference to this forum post - https://root-forum.cern.ch/t/feature-request-make-uninstall/32663

This is but a naive implementation of make uninstall (https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake). This feature does have some issues.. quoting from the forum post - "One of the problems could be the removal of files that were installed independently of ROOT. "

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by reikdas** [comment]
> Build failed on windows10/default.
> [See console output](https://epsft-jenkins.cern.ch/job/root-pullrequests-build/53471/console).

Could someone show me the error logs when building on Windows? (I do not have the relevant permission)

**Comment by oshadura** [comment]
Hi Pratyush, 

I am not sure what happened here, maybe @bellenot can help you here?
`22:02:36 fatal: could not read Username for 'https://github.com': Invalid argument
22:02:36 SetCTestConfiguration:SourceDirectory:C:/build/workspace/root-pullrequests-build/root
22:02:36 SetCTestConfiguration:BuildDirectory:C:/build/workspace/root-pullrequests-build/build
22:02:36 Run dashboard with model Pullrequests
22:02:36    Source directory: C:/build/workspace/root-pullrequests-build/root
22:02:36    Build directory: C:/build/workspace/root-pullrequests-build/build
22:02:36    Track: Pullrequests
22:02:36    First perform the initial checkout: C:/Program Files/CMake/bin/cmake.exe -E chdir C:/build/workspace/root-pullrequests-build/root C:/Program Files/Git/cmd/git.exe checkout -f 
22:02:36    Perform checkout in directory: C:/build/workspace/root-pullrequests-build
22:02:36 Initial checkout failed!
22:02:36 CMake Error at C:/build/workspace/root-pullrequests-build/rootspi/jenkins/root-build.cmake:803 (ctest_start):
22:02:36   ctest_start unknown error. `

**Comment by amadio** [comment]
I think you need to fork roottest as well.

**Comment by reikdas** [comment]
> I think you need to fork roottest as well.

I forked it. 
Do I need to clone it inside the root/ directory of the pull request branch?

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
No, the build bot looks for a fork of roottest in your account to possibly take a matching branch and use for the pull request, but it errors out if you don't have roottest forked. @vgvassilev you may want to have a look at this when you have time. Cheer,s

**Comment by reikdas** [comment]
Would this feature require a test checking if ROOT was uninstalled successfully? (I am not sure if it is even possible - the only way that comes to mind is checking if trying to locate all the files in install_manifest.txt individually returns an error, or the more naive checking if thisroot.sh exists outside of the build directory)

**Comment by Axel-Naumann** [comment]
Could you please leave a note where you copied / adapted this code from?

**Comment by reikdas** [comment]
The CMake FAQ - https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Comment by Axel-Naumann** [comment]
Yes please add the link say to `cmake_uninstall.cmake.in` - one of them is good enough. Thanks!

**Comment by amadio** [comment]
We could also tell people this (which is shown in the FAQ as well):

> Instead of creating an "uninstall" target, Unix users could enter this command in the shell:
```sh
xargs rm < install_manifest.txt
```

I think that having the uninstall target makes us liable if users end up deleting important files with `make uninstall`. For example, you may build ROOT with the default prefix `/usr/local`, and then inadvertently call only `make uninstall`, which may irreparably break, e.g., on Mac OS a ROOT that has been installed with Homebrew. @Axel-Naumann, what do you think?

**Comment by reikdas** [comment]
Wouldn't there be issues anyway if the user installed ROOT system wide using both brew and by building it from source using CMake? Quoting the forum post where I spoke about this pull request - 

> I faced an issue where I installed a build with pyroot_experimental enabled. Then I installed a build with pyroot_experimental disabled. I sourced the thisroot.sh in my /usr/local/ (where ROOT is installed by default for a system wide installation) and pyroot_experimental features were enabled. (Ofcourse this issue could be worked around with sourcing the thisroot.sh in my build directory)

And, perhaps even then a simple uninstall followed by an install of ROOT (using brew following your example) might fix the broken installation?

**Comment by amadio** [comment]
I recommend not sourcing `thisroot.sh` multiple times in the same shell. That will mess up your environment. This is not related to install/uninstall. If you install ROOT somewhere with `make install`, just add `<prefix>/bin` to your `$PATH` and `<prefix>/lib` to your `$PYTHONPATH` and you should never need to `source thisroot.sh`. Also, if you install your own multiple versions of ROOT with `make install`, I recommend installing into an empty directory, not `/usr/local` where Homebrew may have installed it. Then you can just `rm -rf` if needed to uninstall. If you install into `/usr/local` with a package manager, just use the package manager to uninstall. Installing with `make install` a custom ROOT that overwrites another installation with a package manager is going to get you into trouble and `make uninstall` will not help much. With the uninstall target, if you change configuration before uninstalling, you may have half-uninstalled ROOT left over (e.g by enabling/disabling `pyroot_experimental` between make install/make uninstall), or may remove important files from other packages depending on what builtins you had enabled when you built ROOT. CMake has this disabled by default for this reason, and I'm reluctant to provide this uninstall target in ROOT for the same reason.

**Comment by Axel-Naumann** [comment]
...plus "many of us" recommend to simply not do `make install`, but use ROOT right where it was built, or better yet grab a binary build from https://root.cern/download/nightly/ and untar it. As Guilherme says: if you want to get rid of that, just `rm -rf`, done!

**Comment by reikdas** [comment]
Would it possible to mention on the https://root.cern.ch/building-root page that the preferred method is to not do `make install` but to use it from the build directory? And also that `xargs rm < install_manifest.txt` is the way to remove the files if someone does decide to do `make install` ?

**Pull request closed without merging**
