### PR TITLE
fix doxygen typo

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Some doxygen warnings

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by ferdymercury** [comment]
There is also this warning, but I am not sure where it comes from. Maybe from the double asterisks ?

`geom/geom/src/TGeoCone.cxx:53: warning: end of comment block while expecting command </tt>`

**Review by couet — APPROVED** [review]
LGTM

**Comment by ferdymercury** [comment]
> There is also this warning, but I am not sure where it comes from. Maybe from the double asterisks ?
> 
> `geom/geom/src/TGeoCone.cxx:53: warning: end of comment block while expecting command </tt>`

This one is maybe due to **`TGeoCone`** or `phi.` but not sure...

**Comment by ferdymercury** [comment]
Yes, I'll try

**Pull request merged**
