### PR TITLE
Move to `TStyle` static members from `TGaxis`

### PR DESCRIPTION
**Pull request by linev**
Redirect calls to:
* TGaxis::SetMaxDigits()
* TGaxis::GetMaxDigits()
* TGaxis::SetExponentOffset()

Let use these configurations also in TWebCanvas, which has access to
gStyle object

Small adjustment in TStyle class

Implement all these attributes in JSROOT

### CODE REVIEW

**Review by couet — COMMENTED** [review]
Don't you need to increment:
```
ClassDefOverride(TGaxis,6)
```
?

**Review by couet — APPROVED** [review]

**Comment by lmoneta** [comment]
@linev  This commit breaks the TGAxis drawing from the TMVAGui. It causes an infinite loop 
at https://github.com/root-project/root/blob/master/graf2d/graf/src/TGaxis.cxx#L1891

this is caused by a large negative value for maxdigits. 
For some reasons to be understood, `gAxis->GetAxisMaxDigits` returns a large negative number

**Comment by lmoneta** [comment]
Here is the code reproducing the problem
```
auto s  = new TStyle(*gROOT->GetStyle("Plain"));
 s->SetName("TMVA");
 gROOT->GetListOfStyles()->Add(s);
gROOT->SetStyle("TMVA");
cout << gStyle->GetAxisMaxDigits() << endl;
```

and the result is `-1717986919`

**Comment by linev** [comment]
Here is it: https://github.com/root-project/root/pull/12583

**Pull request merged**
