### PR TITLE
Add initial support for RISC-V

### PR DESCRIPTION
**Pull request by hahnjo**
This pull request contains the changes to add initial support for RISC-V. It was developed during the past months on a StarFive VisionFive v1 that was kindly provided to me as part of the [RISC-V Developer Boards Program](https://riscv.org/risc-v-developer-boards/). More details about the challenges are available in the form of a [blog post on my website](https://www.hahnjo.de/blog/2023/01/28/riscv-higgs.html), a [presentation at the CaaS meeting in January](https://compiler-research.org/meetings/#caas_12Jan2023), and a [recording of that talk](https://youtu.be/3PWeLGrF41g).

Please note that this PR only contains the necessary changes to the build system and ROOT's configuration files and utilities. Making the interpreter actually functional requires a number of backports to ROOT's copy of LLVM 13, that are available separately in a branch (https://github.com/hahnjo/root/tree/riscv-backports).

### CODE REVIEW

**Comment by hahnjo** [comment]
The required backports in LLVM are available here: https://github.com/hahnjo/root/tree/riscv-backports

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by hahnjo** [comment]
@Axel-Naumann @pcanal I would appreciate one of you looking over the core config part

**Comment by hahnjo** [comment]
@phsft-bot build

**Review by Axel-Naumann — APPROVED** [review]
Congratulations, @hahnjo !

**Pull request merged**
