### PR TITLE
Fix problems due to copying headers to build directory

### PR DESCRIPTION
**Pull request by amadio**
This turned out to be quite a bit harder to fix than I anticipated, but now almost all headers should be picked from the source directory, and many missing dependencies were added. After I also fix `ROOT_GENERATE_EXECUTABLE()` to use headers from the source directory, then generate headers out of `${CMAKE_BINARY_DIR}/include` and add them to their respective owning targets, we should be able to move the headers to the build directory only at the very end of the build in order to make ROOT usable from the build directory. However, in order to catch missing includes and other dependencies at build time, we need to keep using headers from the source directory only during the build.

### CODE REVIEW

**Comment by vgvassilev** [comment]
I think it may be a better approach if we expand the transitive dependencies. Eg. if we have `Core<-RIO<-Blah` and you specify only `RIO`, the system should automatically expand `Core`.

Then we can choose if we want to enforce our cmake to enumerate all dependencies explicitly (because we will be able to issue a proper diagnostic).

Expansion of transitive dependencies will free the non-expert users of our macros of enumerating all libraries and their dependencies (which they might not be aware of). And more importantly, it will free our cmake lists of:
```
set deps()
if (option)
  deps(libOpt1)
endif(option)

...
DEPENDENCIES ${deps}
...

**Comment by amadio** [comment]
Hi Vassil,

> I think it may be a better approach if we expand the transitive dependencies. Eg. if we have Core<-RIO<-Blah and you specify only RIO, the system should automatically expand Core.

The dependencies I am adding in this pull request are not transitive, they are *direct* dependencies created because a library header or source includes a header from the other library. Each commit should have in its message the reason why the dependency is necessary, and I will amend those that don't later. Expanding all dependencies and linking them explicitly probably won't help here, it will just create a lot of unnecessary overlinking. The same is true for optional dependencies, I don't see how expanding all dependencies can help, since the optional dependency is the "RIO" from your example, i.e., a direct dependency, even if optional.

**Comment by amadio** [comment]
Mac has a strange failure:
```
14:37:56 CMake Error at interpreter/llvm/src/tools/clang/tools/driver/CMakeLists.txt:120 (file):
14:37:56   file failed to open for reading (No such file or directory):
14:37:56 
14:37:56     /build/jenkins/workspace/root-pullrequests-build/build/interpreter/llvm/src/tools/clang/clang.order
```

**Comment by amadio** [comment]
CMake strikes again, it seems CMP0076 and on are only available with CMake 3.12 and above...

**Comment by amadio** [comment]
I'm leaving out the commits that rely on a newer version of CMake to be reviewed later.

**Comment by amadio** [comment]
A change depending on CMake 3.12 slipped through, I removed it.

**Comment by amadio** [comment]
Failed because Windows node seems to be out of space... In any case, this will be addressed in another PR, closing.

**Pull request closed without merging**
