### PR TITLE
Implementing Range overload with recommended changes

### PR DESCRIPTION
**Pull request by edfink234**
# This Pull request:

## Changes or fixes:

This is the new PR I mentioned here: https://github.com/root-project/root/pull/13408 
## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by edfink234** [comment]
The link above didn't work, I meant [here](https://github.com/root-project/root/pull/13408)

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@phsft-bot build

**Review by vepadulano — APPROVED** [review]
Thank you @edfink234 , the changes look good!

**Comment by edfink234** [comment]
🥳

**Pull request merged**
