### PR TITLE
Do not evaluate dependent immediate invocations

### PR DESCRIPTION
**Pull request by hahnjo**
We deferred the evaluation of dependent immediate invocations in https://reviews.llvm.org/D119375 until instantiation. We should also not consider them referenced from a non-consteval context.

Fixes: https://github.com/llvm/llvm-project/issues/55601

```
template<typename T>
class Bar {
  consteval static T x() { return 5; }
 public:
  Bar() : a(x()) {}

 private:
  int a;
};

Bar<int> g();
```
Is now accepted by clang. Previously it errored with: `cannot take address of consteval function 'x' outside of an immediate invocation  Bar() : a(x()) {}`

Differential Revision: https://reviews.llvm.org/D132031

---

Fixes https://github.com/root-project/root/issues/13698, a problem with the new C++ headers from the new macOS SDK.

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build also on mac13/cxx20, mac13arm/cxx20

**Comment by hahnjo** [comment]
@phsft-bot build also on mac13/cxx20, mac13arm/cxx20

**Review by vgvassilev — APPROVED** [review]

**Review by dpiparo — APPROVED** [review]
Thanks for this very nice PR prepared so quickly.

**Comment by dpiparo** [comment]
The numerous failures are fixed by this PR https://github.com/root-project/root/pull/13696

**Comment by Axel-Naumann** [comment]
Unbelievable @hahnjo - congratulations!

**Comment by hahnjo** [comment]
FWIW there were build problems in the incremental GitHub Actions CI (because I forgot to set the right label); they are gone in a clean build triggered by the merge to `master` and we are left with the test failures. Let's see how the nightlies go and then I will backport tomorrow.

**Pull request merged**
