### PR TITLE
[ntuple] `RNTupleFillContext`: Wait for all tasks before destructing model

### PR DESCRIPTION
**Pull request by hahnjo**
Re-enable the `SmallClusters` test.

### CODE REVIEW

**Review by jalopezg-git — COMMENTED** [review]
Awesome :smiley:!  Does this finally fix the crashes in some build configurations?

**Comment by hahnjo** [comment]
> Awesome 😃! Does this finally fix the crashes in some build configurations?

Yes. But we're not entirely happy with the solution because it breaks some of the layering (IMHO `RNTupleWriter` should not need to know that the sink has to wait for all its tasks). We're still discussing how to best solve this...

**Comment by hahnjo** [comment]
https://github.com/root-project/root/pull/16164 nicely solved the problem with freeing pages, but the `RNTupleModel` problem persists because the tasks created in `RPageSinkBuf` hold onto the `RColumnElement`...

**Comment by hahnjo** [comment]
This isn't needed anymore, https://github.com/root-project/root/pull/16350 removed the small clusters write option.

**Pull request closed without merging**
