### PR TITLE
Minuit2 CMake Update

### PR DESCRIPTION
**Pull request by amadio**
This updates Minuit2 build options and uses proper configuration for OpenMP and MPI.

### CODE REVIEW

**Comment by amadio** [comment]
@phsft-bot build with flags -Dminuit=ON -Dminuit2=ON -Dminuit2_omp=ON -Dminuit2_mpi=ON

**Comment by amadio** [comment]
Note, there is a test that fails with MPI=ON, which will need to be fixed (already fails before changes in this PR).

**Comment by amadio** [comment]
@phsft-bot build with flags -Dminuit=ON -Dminuit2=ON -Dminuit2_omp=ON -Dminuit2_mpi=ON

**Comment by amadio** [comment]
Tested locally with CMake 3.8 and 3.10, since there is no MPI in the externals, and no OpenMP on Macs.

**Comment by pcanal** [comment]
Note: this was merged directly into the master.

**Comment by amadio** [comment]
Yes, I had to test myself, as we do not have MPI to test with the CI. After testing, I made a couple of minor changes before merging (to fix the configuration with CMake <= 3.9), that's why this shows as closed and not merged.

**Pull request closed without merging**
