### PR TITLE
Update libc.modulemap

### PR DESCRIPTION
**Pull request by gargvaibhav64**

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build on ROOT-ubuntu16 with flags -Dcxxmodules=On

**Comment by vgvassilev** [comment]
@phsft-bot build on ROOT-ubuntu16/default with flags -Dcxxmodules=On

**Comment by oshadura** [comment]
@vgvassilev cxxmodules build will be broken, since clang HEAD was not build last few days (I am working on it)

**Comment by gargvaibhav64** [comment]
Hi @oshadura @yamaguchi1024 ,

Can I do something to get this merged?

**Comment by oshadura** [comment]
@phsft-bot build on ROOT-ubuntu16/default with flags -Dcxxmodules=On

**Comment by oshadura** [comment]
@phsft-bot build on ROOT-ubuntu1804-clangHEAD/default with flags -Dcxxmodules=On

**Comment by oshadura** [comment]
Merging since the build is actually green, but there is no way to check cxxmodules builds in Jenkins [no node with clang compiler setup].

**Pull request merged**
