### PR TITLE
Revert D153003 "[clang] Fix ODR hashing of template template parameters"

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@hahnjo, looks like the test failures in #13139 that were fixed by this commit are gone. Any idea why?

@smuzaffar, can we test this PR for cmssw?

**Comment by hahnjo** [comment]
> @hahnjo, looks like the test failures in #13139 that were fixed by this commit are gone. Any idea why?

It's possible that D153003 isn't needed anymore with LLVM 16. We should try reverting in ROOT 6.30 with LLVM 13...

**Comment by hahnjo** [comment]
@vgvassilev I pushed https://github.com/root-project/llvm-project/releases/tag/ROOT-llvm16-20240223-01 for you to put into `interpreter/llvm-project/llvm-project.tag`. Also can you please make the commit a proper revert of the *ROOT* commit b90bab03ac5fb72448ae95b37bd5b1b7aec0256c, not one of the various versions in https://github.com/root-project/llvm-project/?

**Comment by vgvassilev** [comment]
> [-20240223-01](https://github.com/root-project/llvm-project/releases/tag/ROOT-llvm16-20240223-01)

I've put that in a separate commit...

**Comment by hahnjo** [comment]
To make the `llvm-diff` workflow fully happy, you need to add one more `case TemplateName::UsingTemplate:` to the `switch` statement - this was added with LLVM 16 and is therefore not present by a plain revert.

**Review by hahnjo — APPROVED** [review]
Great, thanks!

**Pull request merged**
