### PR TITLE
Deprecation and option removal for v6.30

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Remove build options already deprecated for 6.28 and deprecate what https://github.com/root-project/root/issues/9114 asks for.

A subsequent PR will remove the corresponding code.

### CODE REVIEW

**Comment by pcanal** [comment]
< Deprecation and option removal for v6.30

Do you mean 6.32?

**Review by pcanal — APPROVED** [review]

**Review by pcanal — CHANGES_REQUESTED** [review]
The failures in [pyunittests_dataframe_cache](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/187156/testReport/projectroot.tree.dataframe/test/pyunittests_dataframe_cache/) are related.

**Review by dpiparo — APPROVED** [review]
Thanks for this PR @Axel-Naumann . Once all tests are passing, for me it's ready to merge.

**Comment by Axel-Naumann** [comment]
> Do you mean 6.30 or 6.32?

6.30. I hope we can still make it :-) @bellenot might you be able to fix this while I'm gone? We can remove the actual code of the modules in a second, unrelated step - what's needed now is the CMake build option part. I.e. what's left is the error in [pyunittests_dataframe_cache](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/187156/testReport/projectroot.tree.dataframe/test/pyunittests_dataframe_cache/).

**Review by bellenot — CHANGES_REQUESTED** [review]
To fix the failing tests, I propose to change these lines:
https://github.com/root-project/root/blob/6ef7c98b7cfecd00c24d696007981827072eea0e/tree/dataframe/test/CMakeLists.txt#L119-L120
into:
```
 ROOT_ADD_PYUNITTEST(dataframe_cache dataframe_cache.py ENVIRONMENT LEGACY_PYROOT="off") 
 ROOT_ADD_PYUNITTEST(dataframe_datasetspec dataframe_datasetspec.py ENVIRONMENT LEGACY_PYROOT="off") 
 ```
The relevant part of the code can be removed later on in the `dataframe_cache.py` and `dataframe_datasetspec.py` files

**Comment by dpiparo** [comment]
I tried the solution proposed by @bellenot . It works very well also on macos (even if I had to update cmake from version 3.26 to version 3.27 to reproduce the problem it was solving).
I am in favour of merging his changes.
I can provide a subsequent PR cleaning the dataframe tests (and also other places) from legacy pyroot.

**Comment by linev** [comment]
Deprecation of `oracle` is fine for me - I am not aware of any active user.
Last questions on forum about Oracle plugin was in 2017.

**Review by linev — APPROVED** [review]

**Comment by dpiparo** [comment]
It seems we are good from the CI point of view. @pcanal @bellenot @linev, are we ready to merge in your opinion?

**Comment by bellenot** [comment]
> It seems we are good from the CI point of view. @pcanal @bellenot @linev, are we ready to merge in your opinion?

Fine with me

**Review by bellenot — APPROVED** [review]

**Review by pcanal — APPROVED** [review]
LGTM

**Pull request merged**
