### PR TITLE
[interpreter] Enable `LLVM_ENABLE_ABI_BREAKING_CHECKS`

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
Nice, lgtm!

**Comment by hahnjo** [comment]
Except it doesn't work yet, as now also shown by a clean build in the CI; there are some issues left to be fixed

**Comment by vgvassilev** [comment]
> Except it doesn't work yet, as now also shown by a clean build in the CI; there are some issues left to be fixed

Annoying... llvm does not allow people to get away easily :)

**Comment by hahnjo** [comment]
It seems I found all places that needed proper error handling (https://github.com/root-project/root/pull/17160 fixed one instance in parallel that I also had locally) and this works now. @vgvassilev I saw there were ideas of releasing Cling 1.2 - we probably want this in before.

**Review by vgvassilev — APPROVED** [review]
LGTM^2.

**Pull request merged**
