### PR TITLE
[sofie] fix compiler override warnings

### PR DESCRIPTION
**Pull request by linev**
Like seen here: https://github.com/root-project/root/pull/11561#issuecomment-1278788221

### CODE REVIEW

**Review by lmoneta — COMMENTED** [review]
Is the `override` keyword really needed ?
These are implementations of  abstract method, we will get an error anyway if they are not implemented.  If this is needed, we need to do it for all the ROperator_XXX classes implementing the ROperator interface

**Comment by linev** [comment]
> Is the `override` keyword really needed ?

Once it is used for any method - it has to be used for all other overriden virtual methods.

**Comment by linev** [comment]
It appeared with `std::string GenerateInitCode() override`

**Review by lmoneta — APPROVED** [review]
Thank you Sergei. I understand it now why is needed in this case. 
It is then OK to merge. We might want to add the keyword to the other operators later

**Pull request merged**
