### PR TITLE
[ROOT-10472] Fix building clingutils tests with builtin_clang=OFF

### PR DESCRIPTION
**Pull request by chrisburr**
See [this comment](https://sft.its.cern.ch/jira/browse/ROOT-10472?focusedCommentId=106666&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-106666) on JIRA for an explanation.

Closes #4702.
Closes #4749.

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by chrisburr** [comment]
> I am in favor of this PR but it will require more thorough testing...@vgvassilev was asking if it works with -Dclingtest=ON

I agree that this one is cleaned and the build works with `clingtest=ON`. (I didn't try running anything beyond my usual test commands.)

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On

**Comment by vgvassilev** [comment]
The failures actually mean this PR is ok. The changes introduced by this PR should have had impact on how we configure. The failing tests show that we went past this phase and fail in the testing phase which is something that we probably broke long ago.

LGTM!

**Comment by oshadura** [comment]
LGTM, as well! I checked Windows failure (unrelated TBB failure), so @Axel-Naumann what do you think?Can we merge it?

**Comment by oshadura** [comment]
@Axel-Naumann I think it will be better, considering comment of @amadio in https://sft.its.cern.ch/jira/browse/ROOT-10472 I to use instead of this, the PR #4749 (I reopened it). @chrisburr After LLVM upgrade, I will be happy to try your patch again!

**Comment by Axel-Naumann** [comment]
I see no argument why the cling tests are preexisting? Could someone please verify, eg. using the PR builds testing PR? The failures look suspiciously connected to a change of the build system in how we link llvm into cling.

**Comment by oshadura** [comment]
I opened https://github.com/root-project/root/pull/4843

**Pull request closed without merging**
