### PR TITLE
[cmake] Generation of RGitCommit.h depends on nothing.

### PR DESCRIPTION
**Pull request by vgvassilev**
Remove the redundant dependencies from the target. This fixes a cxxmodules
nightly builds.

### CODE REVIEW

**Comment by amadio** [comment]
You know better than me what's going on here, feel free to merge.

**Comment by Axel-Naumann** [comment]
Please consider reverting this:

RGitCommit.h triggers recompilation of TROOT.cxx triggers relinking of libCore triggers regeneration of all dictionaries triggers relinking of all libraries.

And with this PR merged, RGitCommit.h will get regenerated when?

**Comment by vgvassilev** [comment]
Go ahead and revert it if that's urgent. I can only look at it tomorrow.

**Comment by vgvassilev** [comment]
The `gitcommit` target is build before `BaseTROOT` [here](https://github.com/root-project/root/pull/1741/files#diff-5f4a237561b8048385b3ba09ef74fc96L97).

**Pull request merged**
