### PR TITLE
[cxxmodules] CIFactory now uses MultiplexConsumer

### PR DESCRIPTION
**Pull request by Teemperor**
This is a preparation for C++ modules as they will require that
we attach multiple consumers to the CI.

### CODE REVIEW

**Comment by Teemperor** [comment]
I moved this into an extra PR because it somehow the CIFactory patch from #930 fails a certain test. If this also fails this test, then I at least know it's related to this ASTConsumer (as everything else should be behind a `if(modules)`).

**Comment by Teemperor** [comment]
@phsft-bot build

**Comment by Teemperor** [comment]
@vgvassilev @Axel-Naumann any clue why this is failing this test? The only outside visible change should be that you now no longer can `do getASTConsumer()` and then cast it to the custom consumer type, but I don't see any point where we do this.

**Comment by Axel-Naumann** [comment]
No clues from me. But I hear gdb calling...

**Comment by Teemperor** [comment]
Closing this, it's already part of the #930 PR

**Pull request closed without merging**
