### PR TITLE
Implement option CJUST (color justified labels) to TPaletteAxis

### PR DESCRIPTION
**Pull request by oschaile**
As indicated in the root forum I implemented the alignment of labels and ticks in TPaletteAxis
at colour boundaries = contourlevels instead of the algorithm provided by TGAxis 
Please check carefully since I am a novice as git producer

### CODE REVIEW

**Comment by couet** [comment]
Hi Otto,
I see you have modified only the file TPaletteAxis.cxx. But I guess this option will pass trough THistPainter::MakeChopt also... Is there any danger that it my trigger some other option in THistPainter ? For instance "C" is a valid option.. Just wondering...
Olivier

**Comment by couet** [comment]
Hi Otto,
Have you some comments on my last message ?
Cheers,
Olivier

**Comment by oschaile** [comment]
Apropos option "CJUST" vs. "C":
you are right THistPainter::MakeChopt  sees this also.
I didnt feel competent to mess around there since I wouldnt
know how to transmit the option to TPaletteAxis without major changes.

However "C" applies only for 1D and "CJUST" for 2D so they should be 
mutually exclusive.
As a protection one could put in THistPainter.cxx:4269
(strstr(chopt,"C") && !strstr(chopt,"CJUST")) ...

Btw: "CJUST" is just a proposal, it could be named differently
       I thought it might be mnemonic
Otto

**Comment by couet** [comment]
Hi Otto,
Sounds good one can deal with "CJUST" in Makechopt... What about an example showing the usage of this option ? 

here:
https://root.cern/doc/master/classTPaletteAxis.html
or here:
https://root.cern/doc/master/classTHistPainter.html#HP22

Cheers,
Olivier

**Comment by oschaile** [comment]
ok, I will provide one
Otto

**Comment by couet** [comment]
Hi Otto,
I think you have modified Doxyfile by mistake.
Cheers,
Olivier

**Comment by oschaile** [comment]
Hi Olivier,
oh sorry, mea culpa. I tried to generate the full docu in in doxygen directory,
this somehow failed (traceback ) 
Then I reduced the "Input section" to THistPainter + PaletteAxisin in Doxyfile
this worked.
Yesterday I added this by mistake to the commits.
How can I fix that: Replace Doxyfile by the 6.18.00 version and commit again??
Cheers
Otto

**Comment by couet** [comment]
Yes I do this mistake too from time to time :-) (reducing the number of input files in Doxyfile and forget to restore te right version before committing). You simply need to change Doxyfile to the correct version and push it again to this PR.

**Comment by couet** [comment]
Hi Otto, Your new puss restores the variable INPUT, but also modified EXCLUDE_SYMBOLS and EXLUDE_PATTERNS... do you really want to do that ?
Cheers,
Olivier

**Comment by oschaile** [comment]
no, not  really,
I took the file from root version 6.18.00, obviosly wrong one
I dont know how to get exactly the one I started with when
modifying INPUT,
I have a backup from 2019-09-10:
[Doxyfile.2019-09-10-000000.txt](https://github.com/root-project/root/files/3620872/Doxyfile.2019-09-10-000000.txt)

**Comment by couet** [comment]
You should take the Doxyfile from master

**Comment by oschaile** [comment]
PR is  in a not clean state since Doxyfile was modified  by mistake 
will restart from current master

**Pull request closed without merging**
