### PR TITLE
Use GetNmethods instead of GetListOfMethods(kTRUE)

### PR DESCRIPTION
**Pull request by yamaguchi1024**
We don't want ot use GetListOfMethods, because it invokes header
parsing.

### CODE REVIEW

**Comment by dpiparo** [comment]
Nice: this parsing was useless! Do you know where it is useful to know how many methods a class has but not which they are in PyROOT? Putting @etejedor  in  the loop.

**Comment by pcanal** [comment]
Removing the loading the list of function changes the semantic of the return value and indeed as Danilo points we need to understand *how* this routine (Cppyy::GetNumMethods) is used before knowing whether this is the best improvement.

**Comment by pcanal** [comment]
humm .. actually since GetNmethods calls GetListOfMethods with the default value for the parameters, it loads of the functions anyway.  So I was wrong there is no semantic change :)

**Comment by yamaguchi1024** [comment]
Yeah GetNmethods calls GetListOfMethods :) It'll be nice if we don't have to make a list of methods just because we want to get the number..

**Comment by vgvassilev** [comment]
I think we can avoid requiring the method count. I will discuss with Yuka offline and we will let you know.

**Comment by pcanal** [comment]
> Yeah GetNmethods calls GetListOfMethods :) It would be nice if we don't have to make a list of methods just because we want to get the number..

Strictly speaking this is not the case.   This routine is used twice in the code and both time it is used as the barrier in a for loop over the method.   So indeed, those two loop might be better off being rewritten to use iterators instead of index, however lifting the need for the iteration through the method is another thing entirely.

**Comment by yamaguchi1024** [comment]
Do you mean the case GetNmethods is used in graf2d/gpad/src/TPad.cxx? True it looks these loop can be rewritten to iterators.

**Comment by yamaguchi1024** [comment]
So what we want to do is *Remove using GetListOfMethods(kTRUE), because it involves iterations*. Currently GetNmethods is calling GetListOfMethods internally, but we would like to change the implementation of GetNmethods not to use GetListOfMethods soonish.

**Comment by pcanal** [comment]
> So what we want to do is Remove using GetListOfMethods(kTRUE), because it involves iterations. Currently GetNmethods is calling GetListOfMethods internally, but we would like to change the implementation of GetNmethods not to use GetListOfMethods soonish.

But given that GetNmethod is (almost) always use by code that iterate through the list, I do not see the gain (i.e. shouldn't we first look if the iteration (that uses GetNmethods) can (semantically) be removed?).

**Comment by yamaguchi1024** [comment]
https://gist.github.com/yamaguchi1024/aa0e4c9d4f73c62d3c7edd8a73f34266
 
I feel this is super wrong but we can't do something like this?

**Comment by pcanal** [comment]
How is it better/different?

**Comment by yamaguchi1024** [comment]
```
core/meta/inc/TClass.h
   std::atomic<TListOfFunctions*> fMethod;   //linked list for methods                                                                                                                    

   TViewPubDataMembers*fAllPubData;     //all public data members (including from base classes)
   TViewPubFunctions *fAllPubMethod;    //all public methods (including from base classes)
   mutable TList     *fClassMenuList;   //list of class menu items
...
```
I guessed it means fMethod already has list for methods

**Comment by pcanal** [comment]
> I guessed it means fMethod already has list for methods

That is its purpose but the content is brought it only on demand (i.e. if the user ask for the list to be loaded).

**Comment by yamaguchi1024** [comment]
https://gist.github.com/yamaguchi1024/cab4db2ec5f479837ddde54943ea0ec3

We can do something like this and try not to invoke this with true, but it doesn't solve any  problems. Ideally we want to remove all methods like this (GetNmethods, GetListOfMethods, GetListOf... ) so we don't have to worry about iterations. However there are many codes in ROOT which are relying onto these methods, so I'm looking for somewhere middle...

**Comment by pcanal** [comment]
> We can do something like this and try not to invoke this with true, but it doesn't solve any problems. 

I agree that it does not solve the problem as the user that invokes this function is likely to want to be informed about **all** methods and so would call it always with "load==true".

> Ideally we want to remove all methods like this (GetNmethods, GetListOfMethods, GetListOf... ) 

I disagree that we should.  Those are valid operations that are have no possible replacement; for example when wanting to print to the screen the list of all methods.

What we need to do is to look at their **usage** and see if they can be replaced by something else (for example when an iteration through the methods can be replaced by a lookup).  Note that in the case of the code in binding/pyroot, you would first discuss with @etejedor as this code may soon be replaced by a new version/implementation that has different characteristics.

**Comment by etejedor** [comment]
I've checked the code of `Cppyy::GetNumMethods` in Wim's Cppyy and it is equivalent to what we have now in PyROOT. Although it is true that we might merge with Cppyy in the end, it seems that both Cppyy and PyROOT can benefit from the kind of optimization that is proposed in this PR. Ideally, Wim should be aware of these optimizations and incorporate them also in Cppyy, so that we don't lose them if the merge happens.

**Comment by yamaguchi1024** [comment]
https://gist.github.com/yamaguchi1024/95f332222e74f2168df0d452cb2b463f

How about remembering the number of methods in TClassRef? I don't know if this will solve the performance problem but at least we don't have to iterate on same classes.

**Comment by pcanal** [comment]
> How about remembering the number of methods in TClassRef? I don't know if this will solve the performance problem but at least we don't have to iterate on same classes.

I am a bit lost .... What performance problem are we addressing here?  [i.e. as far as I can tell most time the number of methods is accessed this is followed by an iteration over all methods].   Can you be more specific on which (part of which) benchmark you are optimizing and how much this change would improve the run-time of this benchmark?

**Comment by yamaguchi1024** [comment]
I do agree that iterations have no replacement: it is very strong. Thus it must be a last last decision to use it because it's very expensive as well.

**Comment by yamaguchi1024** [comment]
I thought it's unavoidable to iterate over methods at first, so it might be a little help to remember the number of methods in TClassRef. I'm trying to optimize memory (and also cpu time) by removing iterations as possible, and I thought remembering the method number help reduce calling GetListOfMethods(true)

**Comment by pcanal** [comment]
>  to remember the number of methods in TClassRef. I'm trying to optimize memory 

TClassRef is supposed to be a light weight object (a smart pointer) which might be duplicated many times.  Increasing the size of this object would unnecessarily increased the memory consumption by a little bit in many places.   I also do not see the point of caching the value there since it is *already* cached in the list itself (i.e. doing GetListOfMethods(kFALSE)->GetEntries() would cost 'only' the cost of the two functions calls to retrieve whatever was the 'previous' value of the number of methods).

**Comment by yamaguchi1024** [comment]
I profiled pyroot few days ago and found `LookupCppEntity` is a hot function, and this is calling `CreateScopeProxy`, which is calling `Cppyy::GetNumMethods`. So I thought optimizing this part of code really make sense. What do you think?

**Comment by Axel-Naumann** [comment]
This conversation makes no sense to me :-) You're discussing

```
auto GetAllMethods() {
  vector<...> ret;
  for (method: methods())
    ret.emplace_back(method);
  return ret;
}
```

That's because PyROOT and cppyy do "overload resolution" by choosing the best out of a pre-existing collection of functions.

If we want to have any effect in the profile we need to change the way that PyROOT and cppyy find the function to call. This cannot happen by changing either the loop style nor the loop itself, it needs to be fixed by changing the way PyROOT and cppyy do "overload resolution".

If this makes to you no sense then please:
- do not post a reply here
- wait until I'm back at CERN
- I invite everyone to a coffee and we chat.

I recommend we either close this or wait until this chat has happened.

**Pull request closed without merging**
