### PR TITLE
update xrootd hash

### PR DESCRIPTION
**Pull request by lmoneta**

### CODE REVIEW

**Review by bellenot — APPROVED** [review]

**Comment by pcanal** [comment]
Why did the hash of the file in lcgpackage change?

**Comment by bellenot** [comment]
> Why did the hash of the file in lcgpackage change even-though the xrootd version did not change? (i.e. Didn't we migrate away from downloading from github to avoid exactly this kind of problem?)

That's a good question! I asked some people here, we'll see...

**Comment by bellenot** [comment]
OK, problem understood. The person who did the change came to my office, that should never happen again (hopefully).

**Comment by pcanal** [comment]
Thanks.

**Pull request merged**
