### PR TITLE
added 'nproc' for the processing units.

### PR DESCRIPTION
**Pull request by codetronaut**
Added 'nproc' for the processing units available, needed during the build process.

### CODE REVIEW

**Comment by codetronaut** [comment]
@Axel-Naumann , which shell are you currently using, and **nproc** is a GNU core utility which is available default in every Linux distro and shell. If it's not running on your shell I assume you are using a non-Linux machine. Because in mac it's alternative is **sysctl -n hw.logicalcpu** , you can try with it and let me know if it's working or not.

**Comment by codetronaut** [comment]
>  Do you want to update your PR accordingly?
what updates I should add?

**Comment by Axel-Naumann** [comment]
`sysctl -n hw.logicalcpu` works. I still think that a simple "`-j8` where "8" is the number of cores you have" is easier to access for our readers. I don't think it's the readme's job to explain how to find one's number of cores. "`-j8` where "8" is the number of cores you have" is the change I suggested you to do. Would you agree to do that?

**Comment by codetronaut** [comment]
> `sysctl -n hw.logicalcpu` works. I still think that a simple "`-j8` where "8" is the number of cores you have" is easier to access for our readers. I don't think it's the readme's job to explain how to find one's number of cores. "`-j8` where "8" is the number of cores you have" is the change I suggested you to do. Would you agree to do that?

Yes and

**Comment by codetronaut** [comment]
Updated, please check.

**Comment by Axel-Naumann** [comment]
OK, let me be more explicit:
```
 cmake ../root
    $ make -j8
In `-j8`, "8" is the number of processor cores you have.
```
seems to be enough. I don't think the `-jN` case adds much, I believe people will understand that themselves?

**Comment by codetronaut** [comment]
what about this?
```
$make -jN
In -jN, "N" is the number of processor cores you have.
eg. -j8
```
otherwise, change you suggested is also fine.

**Comment by Axel-Naumann** [comment]
I know our users:

> In https://... you say `$make -jN` but that's broken: "make: the '-j' option requires a positive integer argument". Please fix!

So yeah, I would indeed give the example "-j8" and explain that it's just an example... What do you think?

**Comment by codetronaut** [comment]
yes, you are right, I also think -jN may not add much, if they face any problem then they can google it or create an issue.

commit updated please check.

**Comment by codetronaut** [comment]
@Axel-Naumann , Did you found time to look into this?

**Comment by oshadura** [comment]
@codetronaut the same story here, 4 commits to change 1 line of documentation? I don't think it is reasonable.

Things to read: https://chris.beams.io/posts/git-commit/ and please google "why we need to squash commits".

Usually contributors come to ROOT with ready PRs that just require a small review process.

I am sorry but I will need to close this PR, since it is not a playground, please reopen PR later when it will be ready.

**Comment by codetronaut** [comment]
@oshadura, I am sorry for this and will make appropriate changes soon.

**Pull request closed without merging**
