### PR TITLE
[cling-cpt] Reducing global variable mutaiton [skip-ci]

### PR DESCRIPTION
**Pull request by saisoma123**
# This Pull request: Reduces global variable mutation, and is now easier to debug.

## Checklist:

- [NA] tested changes locally
- [X] updated the docs (if necessary)

This PR fixes issue mentioned in the meta-issue list #406 (https://github.com/root-project/cling/issues/406).

### CODE REVIEW

**Comment by vgvassilev** [comment]
I think this PR is not going in the direction of resolving the underlying issue. The idea in the issue, iiuc, is that we have variables (on the global scope) which were mutated by a lot of functions. Moving these variables to become class variables does not solve the mutation problems.

I think a viable way forward is to teach functions not use global variables but to pass these global variables as parameters. This way we will know which function requires what state. Then we can think how to refactor it further.

**Comment by saisoma123** [comment]
Thank you I'll work on it

**Comment by saisoma123** [comment]
I'll close this pull request and make a new one with the parameter passing style you mentioned @vgvassilev

**Comment by saisoma123** [comment]
@vgvassilev

**Pull request closed without merging**
