### PR TITLE
Revert "Change default value for builtin_gtest option to ON"

### PR DESCRIPTION
**Pull request by stephanlachnit**
This reverts commit 8e355c2c565af555f75209ea0f1c2ce255f85cc6 from #10301.

/cc @ellert @bellenot 

# This Pull request:

## Changes or fixes:

Sets `builtin_gtest` to `OFF` by default. It  is already the case that `builtin_gtest` will be enabled automatically if `GTest` is not found.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Comment by stephanlachnit** [comment]
@bellenot friendly ping :)

**Comment by bellenot** [comment]
Fine with me, but I first have to check our CI to make sure we explicitly set it to `ON`

**Review by bellenot — APPROVED** [review]
Fine with me

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by stephanlachnit** [comment]
> This is fine with me, but I first have to check our CI to make sure we explicitly set it to `ON`.

Should not matter, as it falls back to builtin automatically (same as for the other builtin things)

**Comment by hahnjo** [comment]
Well not quite, it broke clean builds on the `master` branch on basically all platforms... Not clear why, investigating.

**Comment by bellenot** [comment]
> Well not quite, it broke clean builds on the `master` branch on basically all platforms... Not clear why, investigating.

Where did you see that?

**Comment by hahnjo** [comment]
In the new CI (should have probably mentioned): https://github.com/root-project/root/actions/runs/5735591722/job/15543575826

**Comment by hahnjo** [comment]
> > In the new CI (should have probably mentioned): https://github.com/root-project/root/actions/runs/5735591722/job/15543575826 (and siblings)
> 
> Interesting... it does set `builtin_gtest` correctly though...

Yes, but there was a side effect of looking for an installed version of GTest; fixed in https://github.com/root-project/root/pull/13375

**Pull request merged**
