### PR TITLE
[PyROOT][CMake] Remove pyroot_experimental flag, create pyroot_legacy

### PR DESCRIPTION
**Pull request by etejedor**
With 6.22, the new PyROOT will not be experimental anymore and become the default.

This PR proposes to get rid of the `pyroot_experimental` CMake flag and create a new one to request to build with the old PyROOT (`pyroot_legacy`).

### CODE REVIEW

**Comment by etejedor** [comment]
>  if someone will still try use pyroot_experimental => CMake should help user to switch to pyroot option? 

Do you think this is really necessary? Isn't it enough to say clearly in the release notes that `pyroot_experimental` does not exist anymore, and that `pyroot_legacy` has been added? It seems to me that otherwise we are carrying old options that we do not use anymore. But I don't know what has been the policy for deprecated CMake options in the past.

> As well do we need to provide message that if user uses pyroot option, CMake should notify that it is ex pyroot_experimental?

But PyROOT experimental will cease to exist as such, we will have PyROOT (which will be a new one) and then the legacy. Again I think that release notes can help explain this.

**Comment by oshadura** [comment]
@etejedor I think it will be helpful (i will not rely everyone reading release notes as well as people who just get used to use `pyroot_experimental` flag over long time) @Axel-Naumann can you please give your opinion?

**Comment by etejedor** [comment]
Just pushed a fix for the `dataframe-cache` test failure, let's wait for the builds.

**Comment by Axel-Naumann** [comment]
IMO it's okay to remove `pyroot_experimental` without deprecation for 6.22: it was experimental until 6.22. It would certainly help users to check whether `pyroot_experimental` is set, and if so, issue an error message. A simple `if(pyroot_experimental) message(FATAL_ERROR "pyroot_experimental is now called pyroot! Please reconfigure with -Dpyroot=On")` will do.

**Comment by etejedor** [comment]
Added a commit for @Axel-Naumann's comment, if the builds are ok I will merge today in master, so we can check the nightlies and merge tomorrow in 6.22.

**Pull request merged**
