### PR TITLE
Cling PR 284

### PR DESCRIPTION
**Pull request by SimeonEhrig**
See root-project/cling#284
The original pull request was: https://github.com/root-project/root/pull/4616/commits

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by SimeonEhrig** [comment]
@Axel-Naumann Now, it should build it.

**Comment by bellenot** [comment]
@SimeonEhrig please fork also roottest to fix the `windows10/cxx14` build

**Comment by SimeonEhrig** [comment]
@bellenot I forked the `roottest` repository. Is that enough or do I have to do additional things?

**Comment by bellenot** [comment]
> @bellenot I forked the `roottest` repository. Is that enough or do I have to do additional things?

That should be enough, thanks!

**Comment by Axel-Naumann** [comment]
**Congratulations**, @SimeonEhrig !

**Comment by pcanal** [comment]
The incremental, for example: https://epsft-jenkins.cern.ch/job/root-incremental-master/LABEL=ROOT-performance-centos7-multicore,SPEC=default/8204/console
fails with:
```
CMake Error at interpreter/cling/CMakeLists.txt:178 (message):
  NVPTX backend is not activated

  Please enable it via -DLLVM_TARGETS_TO_BUILD="host;NVPTX"


-- Configuring incomplete, errors occurred!
See also "/data/sftnight/wsincrmaster/LABEL/ROOT-performance-centos7-multicore/SPEC/default/build/CMakeFiles/CMakeOutput.log".
See also "/data/sftnight/wsincrmaster/LABEL/ROOT-performance-centos7-multicore/SPEC/default/build/CMakeFiles/CMakeError.log".
gmake: *** [cmake_check_build_system] Error 1
Command exited with the value: 2
```
What is the best solution?

**Comment by Axel-Naumann** [comment]
Rebuild from scratch. Doing that as we speak.

**Comment by SimeonEhrig** [comment]
Thank you for merging. Now I can start implementing the nice features :-)

**Comment by ax3l** [comment]
Congrats on the merge, glad to read this! :)

**Pull request merged**
