### PR TITLE
Rename Cling's flag -modulemap_overlay to -includedir-loc

### PR DESCRIPTION
**Pull request by gargvaibhav64**

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
`448>Done Building Project "C:\build\workspace\root-pullrequests-build\build\core\clingutils\dequeDict.vcxproj" (default targets) -- FAILED.
16:05:34    483>CustomBuild:
16:05:34          <SeparateClass Prefixes:["--"] Name:"metastr">
16:05:34          <JoinedClass Prefixes:["-"] Name:"includedir_loc=">
16:05:34          Options are not in order!
16:05:34          UNREACHABLE executed at C:\build\workspace\root-pullrequests-build\root\interpreter\llvm\src\lib\Option\OptTable.cpp:134!
16:05:34          Exit code 0xc0000409`

**Comment by gargvaibhav64** [comment]
Hi @oshadura ,
Is there something that I can do to get the builds successful and get this PR merged?

**Comment by oshadura** [comment]
@gargvaibhav64, yes, build was broken for the windows, now it also has conflicts, so you need to rebase on master and check how to fix windows build :)

**Comment by yamaguchi1024** [comment]
@gargvaibhav64 Could you rebase?

**Comment by gargvaibhav64** [comment]
> @gargvaibhav64 Could you rebase?

I did the rebase, please check now.

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by yamaguchi1024** [comment]
@gargvaibhav64 Please check the failing tests.

**Comment by gargvaibhav64** [comment]
@yamaguchi1024 I think it should work now.

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
Travis build failure is not connected with changes, I will merge this PR.

**Pull request merged**
