### PR TITLE
Avoid pad creation with W<=0 or H<=0

### PR DESCRIPTION
**Pull request by couet**
Fix https://github.com/root-project/root/issues/6374

### CODE REVIEW

**Review by linev — APPROVED** [review]

**Comment by andriish** [comment]
Hi @couet ,

this will not fix the #6374 , but rather mask it.

While the creation of pad with zero width will be forbidden, one still could resize the pad to zero width and have a crash.
This fix will just make the reproduction of bug much more complicated.

Best regards,

Andrii

**Comment by couet** [comment]
I disagree. It should be protected at this level and we should not allow the creation of a 0 sized pad. It should be stopped at this level. Now if it shows elsewhere it has to be protected also. I will try to find if there is other ways to resize to zero. At least it is not possible interactively (I just checked). Now this PR prevent to create a pad with width 0.

**Comment by linev** [comment]
Probably, we can protect `SetPad` method as well - just to prevent that somebody assign negative size from C++ code

**Comment by couet** [comment]
Yes, `SetPad` is the other way to change pad position. I will make a reproducer based on that.

**Comment by andriish** [comment]
I my opinion that should be ok to create a pad with zero dimensions.
 One could do that, resize the pad and then draw. So such fixes should be done in codes for the resiye and/or draw.

Best regards,

Andrii

**Comment by couet** [comment]
In my opinion it is not ok to create a pad with 0 dimension.

**Comment by andriish** [comment]
That is another  point of view (completely fine, as for me). But then the implicit dimensions should never be zero, but some minimal value. That is harder to implement. And if not implememted,
The codes that now have no explicit dimensions (implicit 0)  will fail.

**Comment by couet** [comment]
I do not understand what you mean by "implicit dimensions" ... you mean the dimensions when you do: 
```
auto p = new TPad();
```
?

**Comment by andriish** [comment]
Yes, this and alike.

**Comment by couet** [comment]
@phsft-bot build

**Pull request merged**
