### PR TITLE
Extra patches used by ALICE

### PR DESCRIPTION
**Pull request by ktf**
This is the complete set of patches used by ALICE on top of v6-20-02. AFAICT they are all in master already. Any chance we can get them included in the next v6-20-XX tag?

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@ktf I cant find next commit in the master: "Fix issues in THistPainter and TFileMerger". Other commits are in place. Can you please open a separate PR for it both in master and 6.20?

**Comment by ktf** [comment]
@oshadura done in #5410 and #5411.

**Comment by oshadura** [comment]
Lets remove this commit from here, so you will continue discussion in new PRs and then it is ready to go!

**Comment by ktf** [comment]
Done.

**Pull request merged**
