### PR TITLE
[llvm-project] Introduce paged vector [v6.30]

### PR DESCRIPTION
**Pull request by hahnjo**
The goal of the class is to be an (almost) drop in replacement for SmallVector and std::vector when those are presized and filled later, as it happens in SourceManager and ASTReader.

By doing so, sparsely accessed PagedVector can profit from reduced memory footprint.

Co-authored-by: Jonas Hahnfeld <jonas.hahnfeld@cern.ch>

(cherry picked from commit 9c7bac05ea52cea6757f083fec8e2b794f8b79d6, backport of https://github.com/root-project/root/pull/13808)

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by dpiparo** [comment]
Thanks @hahnjo . On Windows, we see an issue with lexing, but I guess this is caused by https://github.com/root-project/root/pull/14374, right @bellenot ?

**Review by dpiparo — APPROVED** [review]
Thanks for the changes. For me the PR is ready to be merged if it is confirmed that the failure on Windows is unrelated.

**Comment by hahnjo** [comment]
> On Windows, we see an issue with lexing, but I guess this is caused by #14374, right @bellenot ?

Yes, very likely the same as https://github.com/root-project/root/pull/14200#issuecomment-1903602682 on `master`...

**Pull request merged**
