### PR TITLE
[cmake xrd] From Guilherme: disable -Werror which breaks GCC9:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
See https://github.com/xrootd/xrootd/issues/993
In a subsequent commit (not part of v6.18) we will only build the Xrd client!

### CODE REVIEW

**Comment by amadio** [comment]
I would like to suggest to drop the "From Guilherme:" part from the commit message (I don't like my name in it like that), and add a [`Suggested-by: `](https://git.wiki.kernel.org/index.php/CommitMessageConventions) tag instead, or just drop it entirely, it's just a minor change.

**Comment by amadio** [comment]
BTW, do any of the builds in Jenkins actually use the builtin xrootd? I guess yes, but just to make sure.

**Comment by Axel-Naumann** [comment]
E.g. ubu16 uses it. I like to attribute who wrote the patch. Learned that from llvm, still like it :-)

**Comment by amadio** [comment]
You can attribute things without putting the name on the first line. I don't like my name being put like that, so please don't do it again. Let me write the commit, or put my name after the second line of the commit message.

**Comment by Axel-Naumann** [comment]
OK understood.

**Pull request merged**
