### PR TITLE
[REve] Update to RenderCore release from github, deploy it as builtin tarball

### PR DESCRIPTION
**Pull request by osschar**
- Move some RenderCore specific classes and all shaders into RenderCore source tree.

- Implement all existing Three.js functionality with RenderCore.

- In RenderCore, further improve on existing functionality:
  - Textured points - arbitrary size and shape.
  - Mesh lines - arbitrary thickness.
  - Object and sub-object picking through color buffer with fragment depth detection.
  - Camera handling like in TEve, with ability to pick rotation center.

- The development branch has been squashed to hide redundant changes. Full history is available in PR osschar/root#41.

## C++ / Server Changes

- REveManager: Make RenderCore the default rendering engine.

- Stream interpreter errors and show them in client log

- Add flag fIsRCore to REveManager.

- Make REvePointSet secondary-selectable.

- Add parameter for projection depth in REveDataCollection

## JS / Client Changes

- Remove error MessageBox popup during client updates.

- EveManager.js: Check change bits in ImportSceneBinary when scene changes are streamed.

- EveScene.js: Optimize visibility changes.

- EveScene.js: pass eve_element instead of object3d in cases where it simplifies the code.

- EveScene.js, GlViewer classes: Cleamup highlite/selection management so it can be abstracted for RCore.

- Separate viewer-side selection processing for Three / RCore.

## Tutorials / Demos Changes

- event_demo.C: secondary select points, jet title include pT.

- Tune marker sizes, colors, visual parameters.

### CODE REVIEW

**Review by linev — APPROVED** [review]
Looks ok.

I test several tutorials - all them work.

**Comment by Axel-Naumann** [comment]
Can we please have [the warning](https://github.com/root-project/root/pull/11936#issuecomment-1358960607) fixed?

**Comment by linev** [comment]
@Axel-Naumann   Warning should be fixed now by my commit

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on windows10/cxx14

**Pull request merged**
