### PR TITLE
Fix mem leak in TQCommand

### PR DESCRIPTION
**Pull request by linev**
Wrong delete operator was used

### CODE REVIEW

**Comment by linev** [comment]
Trivial fix, code is no longer used anyway. 
Can be moved out of libCore (in libGui, for instance)

**Comment by bellenot** [comment]
> Trivial fix, code is no longer used anyway.
> Can be moved out of libCore (in libGui, for instance)

Not sure... See:
```
class TApplication : public TObject, public TQObject
```

**Comment by linev** [comment]
> Not sure... See:

I mean TQCommand is not used in ROOT code at all. 
Most probably, it can be in some very old GUI-based applications. 
Therefore TQCommand can me moved in  libGui

**Comment by bellenot** [comment]
Oh, OK, I see. Sorry for the noise

**Comment by linev** [comment]
I found example of TQCommand usage in ROOT4. 
Seems to be, it was eliminated when moving to ROOT5

**Pull request merged**
