### PR TITLE
[cxxmodules] Add bits/unique_ptr to the modulemap to untie module dependency

### PR DESCRIPTION
**Pull request by vgvassilev**
The std.condition_variable module can be exported via the std.condition_variable
module or std.memory. On some platforms (gcc10) that causes definition mismatch
problems of kind:

In module 'std' imported from input_line_1:1:
  c++/10.3.0/bits/unique_ptr.h:208:12: error: 'std::__uniq_ptr_data<std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >, std::default_delete<std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > > >, true, true>' has different definitions in different modules; definition in module 'std.condition_variable' is here
     struct __uniq_ptr_data : __uniq_ptr_impl<_Tp, _Dp>
           ^
/c++/10.3.0/bits/unique_ptr.h:208:12: note: definition in module 'std.condition_variable' is here

Try fixing cms-sw/cmssw#36700

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
This change is only for unix, I do not see how this PR can fail on Win...

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by hahnjo** [comment]
Is this still relevant? We had quite some changes to `std.modulemap` to support a very wide range of newer versions of GCC / libstdc++, so maybe this is already fine?

**Comment by vgvassilev** [comment]
> Is this still relevant? We had quite some changes to `std.modulemap` to support a very wide range of newer versions of GCC / libstdc++, so maybe this is already fine?

I believe so, cmssw modules ib might be failing due to this.

**Comment by vgvassilev** [comment]
Let's close this for now. We can revisit the topic if needed.

**Pull request closed without merging**
