### PR TITLE
Evaluate https://reviews.llvm.org/D33529

### PR DESCRIPTION
**Pull request by vgvassilev**
This is to test a potential fix to a recent regression in llvm wrt exposing symbols to the JIT from dlopened with RTLD_LOCAL libraries.

This regression forced ROOT to revert this patch, adding one more patch to the list of llvm patches. We want to check if D33529 fixes our issue and make sure it goes in the next llvm release (coming soon).

@marsupial, I failed to apply D33657 on top and D33658. They are marked as dependencies but it looks like they do not apply cleanly.

### CODE REVIEW

**Comment by marsupial** [comment]
D33658 had a conflict but is resolved now.
Also you'll have to set the ordering for the behavior you want, I believe that is SO_LoadedFirst.

**Comment by vgvassilev** [comment]
Ok, I will give it a try. I got the impression that we decided it should be the default?

**Comment by marsupial** [comment]
I think the default should be not to overwrite all symbols when a library is loaded, the best example of why is that would mean loading **libX.dylib** could insert it's `operator new` into the JIT for and whether it did so or not is entirely dependent on whether  `operator new` was used prior to loading **libX.dylib** or not.

**Comment by vgvassilev** [comment]
@marsupial it looks like neither patch fixes the issue.

**Comment by marsupial** [comment]
Specificity would help...this is reporting Jenkins CI build passed and the majority of tests pass here as well (I've never successfully had them all pass).
Perhaps you are not picking up the full history of changes (as you said there were conflicts)?
Maybe apply the changes to LLVM and then overwrite the ROOT versions?

**Comment by vgvassilev** [comment]
@marsupial Jenkins reports around 500 failures. Don't worry I am working on a fix and I will take care of all that.

**Comment by marsupial** [comment]
To be honest I am worried. Predominately because you've mentioned your desire to revert https://reviews.llvm.org/D30107 about 4 times and are starting to do so on threads that have nothing to do with this issue.  To me it seems you may not be particularly interested in working toward a solution that helps other parties (as ROOT's desired/default behavior is 100% incorrect for us).

I've tried to be helpful and understand where you are coming from, but I've asked for a concrete example of breakage that https://reviews.llvm.org/D33529 does not resolve twice and it is not provided.

Perhaps you can elucidate on what you are planning, or give an example that is not fixed by D33529?

Thank you.

**Comment by vgvassilev** [comment]
I am looking for a hotfix for the upcoming llvm release. The patch would be in the [area](https://github.com/llvm-mirror/llvm/blob/master/lib/Support/DynamicLibrary.cpp#L76-L92):
  * I plan to remove the NDEBUG assert
  * Make the `std::vector<void*>` a `std::vector<llvm::PointerIntPair<void*, 1, bool>`
  * Add a default flag to `addPermanentLibrary` saying if it was opened with RTLD_GLOBAL
  * I will change the search order to search for those first.

A real solution I've discussed with Lang privately is that we should figure out a way how to pass the dlopened handle to the cling interpreter (before any parsing happens) and have a call to dlsym before calling the DynamicLibrary [here](https://github.com/root-project/cling/blob/master/lib/Interpreter/IncrementalJIT.cpp#L320). This would only happen after the next release of LLVM.

I appreciate your proposed solutions but I do not really have a lot of bandwidth nowadays to investigate why they do not work for us. You will probably see what's going wrong if you build this PR locally.

One of the issues is that it is not clear to me is what exactly is your use case and this is why there are misunderstandings. I feel fairly strongly running cling (and ROOT) with a patch-free LLVM and clang. I would appreciate if we can coordinate next time such breaking changes before asking for a llvm review and land patches in these particularly sensitive areas.

**Comment by marsupial** [comment]
> I appreciate your proposed solutions but I do not really have a lot of bandwidth nowadays to investigate why they do not work for us. You will probably see what's going wrong if you build this PR locally.

I have built locally and don't see the issue (I don't even know what I'm looking for).  Both you and @pcanal asked me to fix this and I spent actual time trying to figure out what you guys were after and implementing a solution that has little cost for both of us.  I too suffer from lack time, so asking me to do work then walking away without even giving a single example of what is broken seems a bit rude....

Seriously, can I get one test that still fails with https://reviews.llvm.org/D33529 ?

If that cannot be done could @pcanal or @Axel-Naumann at least verify that after applying D33529 and setting `DynamicLibrary::SearchOrder = SO_LoadedFirst; // or SO_LoadedLast (don't know the problem)` 500+ tests are broken?

> I would appreciate if we can coordinate next time such breaking changes before asking for a llvm review and land patches in these particularly sensitive areas.

I explicitly added you to the list of reviewers for the original patch, there is little more I can do than that.  And more coordination is exactly what I am trying to do now. If we cannot reach a conclusion may I at least be added to review whatever your solution looks like?


> 1. I plan to remove the NDEBUG assert

Already done in D33529

> 2. Make the std::vector<void*> a std::vector<llvm::PointerIntPair<void*, 1, bool>>

How can you guarantee that the platform will deliver a pointer with proper alignment for that?

> 3. I will change the search order to search for first the one that are not marked RTLD_GLOBAL.

So any other client that wants to open thing's with RTLD_LOCAL will then expose what they thought were private symbols to the JIT as a whole?


> One of the issues is that it is not clear to me is what exactly is your use case and this is why there are misunderstandings.

I also don't understand why there are mis-understandings, but have explained the use case a few times now and **3** will explicitly break that as well as provide bizarre default behavior:

> libc++.so, libA.so
> libA.so defines an overload for global operator new/delete
> 
> ```
> DynamicLibrary::getPermanentLibrary(NULL)
> // Other code
> DynamicLibrary::getPermanentLibrary("libA.so")
> ```
> In your scheme the JIT can pull operator new/delete from libA.so, and worse is that whether it pulls operator new/delete from libA.so is dependent on whether operator new/delete has been resolved in **// Other code** before libA.so has been loaded.
> 

The example can be expanded to RTTI information, exceptions, and a host of other problems.
And even worse than that is that in your scheme there is no way of hiding symbols from the global scope, in fact it promotes everything that the user reasonably expected to be private (via RTLD_LOCAL) to take dominance over anything else.

**Comment by vgvassilev** [comment]
On 07/07/17 23:36, marsupial wrote:
>
>     I appreciate your proposed solutions but I do not really have a
>     lot of bandwidth nowadays to investigate why they do not work for
>     us. You will probably see what's going wrong if you build this PR
>     locally.
>
> I have built locally and don't see the issue (I don't even know what 
> I'm looking for). Both you and @pcanal <https://github.com/pcanal> 
> asked me to fix this and I spent actual time trying to figure out what 
> you guys were after and implementing a solution that has little cost 
> for both of us. I too suffer from lack time, so asking me to do work 
> then walking away without even giving a single example of what is 
> broken seems a bit rude....
>
Hm, for me the issue was obvious, sorry. You need to build ROOT, start 
it and type `int i`.
>
> Seriously, can I get one test that still fails with 
> https://reviews.llvm.org/D33529 ?
>
> If that cannot be done could @pcanal <https://github.com/pcanal> or 
> @Axel-Naumann <https://github.com/axel-naumann> at least verify that 
> after applying D33529 and setting |DynamicLibrary::SearchOrder = 
> SO_LoadedFirst; // or SO_LoadedLast (don't know the problem)| 500+ 
> tests are broken?
>
Now trying with SO_LoadedLast.
>
>     I would appreciate if we can coordinate next time such breaking
>     changes before asking for a llvm review and land patches in these
>     particularly sensitive areas.
>
> I explicitly added you to the list of reviewers for the original 
> patch, there is little more I can do than that. And more coordination 
> is exactly what I am trying to do now. If we cannot reach a conclusion 
> may I at least be added to review whatever your solution looks like?
>
>      1. I plan to remove the NDEBUG assert
>
> Already done in D33529
>
>      2. Make the std::vector<void*> a
>         std::vector<llvm::PointerIntPair<void*, 1, bool>>
>
> How can you guarantee that the platform will deliver a pointer with 
> proper alignment for that?
>
>      3. I will change the search order to search for first the one
>         that are not marked RTLD_GLOBAL.
>
> So any other client that wants to open thing's with RTLD_LOCAL will 
> then expose what they thought were private symbols to the JIT as a whole?
>
>     One of the issues is that it is not clear to me is what exactly is
>     your use case and this is why there are misunderstandings.
>
> I also don't understand why there are mis-understandings, but have 
> explained the use case a few times now and *3* will explicitly break 
> that as well as provide bizarre default behavior:
>
>     libc++.so, libA.so
>     libA.so defines an overload for global operator new/delete
>
>     |DynamicLibrary::getPermanentLibrary(NULL) // Other code
>     DynamicLibrary::getPermanentLibrary("libA.so") |
>
>     In your scheme the JIT can pull operator new/delete from libA.so,
>     and worse is that whether it pulls operator new/delete from
>     libA.so is dependent on whether operator new/delete has been
>     resolved in *// Other code* before libA.so has been loaded.
>
> The example can be expanded to RTTI information, exceptions, and a 
> host of other problems.
>
   No, this would not break the case you mentioned. The case that will 
have a special behavior is if you called 
`DynamicLibrary::getPermanentLibrary(handle)`. So you should be safe there.
>
> And even worse than that is that in your scheme there is no way of 
> hiding symbols from the global scope, in fact it promotes everything 
> that the user reasonably expected to be private (via RTLD_LOCAL) to 
> take dominance over anything else.
>
   I understand that and I am totally fine for fixing this the right way 
after the llvm release.

**Comment by vgvassilev** [comment]
@marsupial using `SO_LoadedLast` (which is somewhat counter-intuitive to our use case) seems to work. I've greenlit D33529 but give Lang couple of hours/days to give feedback.

**Comment by marsupial** [comment]
> Hm, for me the issue was obvious, sorry. You need to build ROOT, start
it and type `int i`.

Yes and before D33529 I see a problem, after I do not.

Is there a chance the patch you are using is outdated or got borked in conflict resolution?

This is what I have (all applied cleanly except for the unit-test which ROOT seems to drop), and you really only need the first 3 commits.

https://github.com/marsupial/root/tree/PR/1

> No, this would not break the case you mentioned. The case that will
> have a special behavior is if you called
> `DynamicLibrary::getPermanentLibrary(handle)`. So you should be safe there.

So if one calls DynamicLibrary::addPermanentLibrary the behavior will differ? That seems extremely hackie, (and would likely cause conflicts with everything I'm trying to get into DynamicLibrary)

**Comment by marsupial** [comment]
> using SO_LoadedLast (which is somewhat counter-intuitive to our use case) seems to work.

I agree `SO_LoadedLast`  shouldn't be what your after especially if it works with `SO_LoadedFirst` here.
Diff-ing my PR1 vs your JITRTLD_LOCAL shows something went screwy, in particular:
DynamicLibrary.h@91 should be:
```
    enum SearchOrdering {
      /// SO_Linker - Search as a call to dlsym(dlopen(NULL)) would when
      /// DynamicLibrary::getPermanentLibrary(NULL) has been called or
      /// search the list of explcitly loaded symbols if not.
      SO_Linker,
      /// SO_LoadedFirst - Search all loaded libraries, then as SO_Linker would.
      SO_LoadedFirst,
      /// SO_LoadedLast - Search as SO_Linker would, then loaded libraries.
      /// Only useful to search if libraries with RTLD_LOCAL have been added.
      SO_LoadedLast,
      /// SO_LoadOrder - Or this in to search libraries in the ordered loaded.
      /// The default bahaviour is to search loaded libraries in reverse.
      SO_LoadOrder = 4
    };
```

> Thanks for helping me out to sort this out!

No problem, but lets sort if it can be accomplished with `SO_LoadedFirst`.


> My personal opinion is that it should be the default, being close to the old behavior.

I understand that but do my examples or the fact the old behavior completely breaks down on Windows give you no pause?

**Comment by vgvassilev** [comment]
The patch landed in llvm proper. Closing this testing PR.

**Pull request closed without merging**
