### PR TITLE
[cmake][ci] Improve selection of a candidate `roottest` branch to checkout

### PR DESCRIPTION
**Pull request by jalopezg-git**
The search for a candidate repository and branch for `roottest` now works as follows: 
- If the current head is a well-known branch, e.g. `master` or `v6-28-00-patches`, use the matching branch upstream as the forked repository may be out-of-sync.
- Otherwise, try a branch that matches the name of the current head in the forked repository, if it exists; else try using the closest upstream head/tag below `HEAD`'s parent commit.
- As a last resort, if there is no preferred candidate, checkout the remote's default head.

This patchset also adds some minor changes to the new CI in order to forward additional information about pull requests.

## Checklist:
- [x] tested changes locally

### CODE REVIEW

**Comment by jalopezg-git** [comment]
> **NOTE:** however, there's still a caveat: in the last step, we `ls-remote` and `clone` the remote https://github.com/root-project/roottest.git. For the CI, I think this should be the URL of the forked (user's) repository instead.

I guess that for this, we could actually take the URL for the `origin` remote of root.git, and just `s/root.git/roottest.git/` (?)

**Comment by eguiraud** [comment]
Hi, AFAIK rootbench does not have branches for different releases or tags, the only guarantee is that current tip of trunk from rootbench compiles against current tip of trunk from root.

Does it still make sense to apply the same logic that we use for roottest to rootbench?

**Review by Axel-Naumann — APPROVED** [review]
Great thanks! I agree with @eguiraud - we should remove the use of `${GIT_BRANCH}` in rootbench, and always checkout master instead. Other than that: awesome thank you!

**Comment by jalopezg-git** [comment]
> Great thanks! I agree with @eguiraud - we should remove the use of `${GIT_BRANCH}` in rootbench, and always checkout master instead. Other than that: awesome thank you!

The previous incarnation was wrong anyways though.  I have updated the PR with the new patch set :slightly_smiling_face: .  Please review.

**Review by Axel-Naumann — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
