### PR TITLE
[ROOT-9707][DF] Defer declaration of type aliases to the interpreter until right before the event loop

### PR DESCRIPTION
**Pull request by bluehood**
~~This PR should turn green when [ROOT-9790](https://sft.its.cern.ch/jira/browse/ROOT-9790) is resolved.~~ A temporary workaround for greedy jitting of `Cache` and `Snapshot` has been added.

### CODE REVIEW

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by bluehood** [comment]
Most test failures are due to https://sft.its.cern.ch/jira/browse/ROOT-10062

**Comment by bluehood** [comment]
@dpiparo I _think_ this is it, let's see if jenkins agrees :smile:

**Comment by bluehood** [comment]
The windows failure seems unrelated

**Comment by bluehood** [comment]
As far as I can tell it's due to a recent RVec PR that uses M_PI but windows can't find it

**Comment by dpiparo** [comment]
@phsft-bot build , just to check the win build.

**Comment by bluehood** [comment]
@Axel-Naumann @bellenot do you have any idea why I get these windows failures about an error that, as far as I can tell, has been fixed in master?

**Comment by Axel-Naumann** [comment]
I guess it's simply that they are not fixed in master, right?

**Comment by bluehood** [comment]
@Axel-Naumann yes sorry, for some reason I thought they were

**Comment by bluehood** [comment]
@phsft-bot build please

**Pull request merged**
