### PR TITLE
Remove pq2, proofd, rootd

### PR DESCRIPTION
**Pull request by gganis**
Such code was deprecated in 6.14

### CODE REVIEW

**Comment by gganis** [comment]
Weird errors, pretty much unrelated with the changes. I do not have them on my installation.
I'll try re-running.

**Comment by gganis** [comment]
@phsft-bot build just on ROOT-centos7/python3, ROOT-fedora27/noimt

**Comment by amadio** [comment]
@gganis These are known, at least the statusbitcheck and xrootd plugin. Fixes for them are already on the way.

**Comment by Axel-Naumann** [comment]
None of these errors are related to your change; they're all in the works!

**Comment by Axel-Naumann** [comment]
I'd say so: https://github.com/root-project/root/blob/master/man/man1/setup-pq2.1

**Pull request merged**
