### PR TITLE
Add ApplyX function to TGraphErrors

### PR DESCRIPTION
**Pull request by Andres-Briones**
Add ApplyX line 409

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Thanks, @RockAndres !

**Comment by RockAndres** [comment]
Need to add void  virtual void ApplyX(TF1 *f); to the TGrpahErrors.h file

**Comment by RockAndres** [comment]
This is the first time I have contributed to a project and used GitHub, sorry for the errors

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
@Andres-Briones please fork also roottest to fix the build error on Windows

**Comment by linev** [comment]
@phsft-bot build!

**Comment by linev** [comment]
@phsft-bot build!

**Comment by linev** [comment]
@phsft-bot build!

**Comment by linev** [comment]
@couet Can you check PR?

**Comment by couet** [comment]
@phsft-bot build!

**Comment by bellenot** [comment]
@Andres-Briones please fork also [roottest](https://github.com/root-project/roottest) in order to fix the build error on Windows

**Comment by couet** [comment]
@phsft-bot build!

**Comment by pamputt** [comment]
@couet, what is the status of this PR?

**Comment by couet** [comment]
@phsft-bot build!

**Pull request merged**
