### PR TITLE
Fixed gSystem->GetMemInfo bug

### PR DESCRIPTION
**Pull request by AdvaitDhingra**
I (tried) to fix [this](https://github.com/root-project/root/issues/7196) issue.

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build

**Comment by AdvaitDhingra** [comment]
I forgot to define fMemAvialable. Should work now

**Comment by AdvaitDhingra** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
@AdvaitDhingra please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks

**Comment by AdvaitDhingra** [comment]
> @AdvaitDhingra please fork also [roottest](https://github.com/root-project/roottest) to prevent failures (timeout) on Windows nodes. Thanks

Okay, I forked it. How can I test my changes?

**Comment by pcanal** [comment]
The linux version looks good.  The MacOS and Windows (@bellenot  might be able to help with that version) needs to be updated too.  In particular in this PR `MemInfo_t::fMemAvailalble` is not initialized (as a random value) on those 2 platforms.

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
> The linux version looks good. The MacOS and Windows (@bellenot might be able to help with that version) needs to be updated too. In particular in this PR `MemInfo_t::fMemAvailalble` is not initialized (as a random value) on those 2 platforms.

I think `MemInfo_t::fMemAvailalble` should be initialized in `TSystem.cxx`, since it is declared in `TSystem.h`. My question is: Is it needed at all on Windows? We don't calculate the memory status the same in `TWinNTSystem`

**Comment by bellenot** [comment]
So let's do it that way, in TWinNTSystem.cxx, in `static void GetWinNTMemInfo(MemInfo_t *meminfo)`:
Add this line:
```
   meminfo->fMemAvailable = meminfo->fMemFree;
```
below this line:
```
   meminfo->fMemFree   = (Int_t) (free >> 20);
```

**Comment by AdvaitDhingra** [comment]
> So let's do it that way, in TWinNTSystem.cxx, in `static void GetWinNTMemInfo(MemInfo_t *meminfo)`:
> Add this line:
> 
> ```
>    meminfo->fMemAvailable = meminfo->fMemFree;
> ```
> 
> below this line:
> 
> ```
>    meminfo->fMemFree   = (Int_t) (free >> 20);
> ```

Okay

**Comment by pcanal** [comment]
> BTW, what is the difference between fMemFree and fMemAvailable ?

The "free" is the memory avaialble minus the memory temporarily used by the OS/kernel and easily freed, for example used for file caching.

**Comment by bellenot** [comment]
> > BTW, what is the difference between fMemFree and fMemAvailable ?
> 
> The "free" is the memory avaialble minus the memory temporarily used by the OS/kernel and easily freed, for example used for file caching.

OK, thanks for the info @pcanal !

**Comment by AdvaitDhingra** [comment]
I have roottest working now. Which tests do I need to run? There are 2000.

**Comment by ferdymercury** [comment]
> I have roottest working now. Which tests do I need to run? There are 2000.

I think you do not need to run it explicitly, just have a fork on GitHub, so that the automatic CI tests pass well.

**Comment by AdvaitDhingra** [comment]
So what else needs to be dine now?

**Comment by pcanal** [comment]
We still to (find somebody who can) implement the MacOS version.

**Pull request closed without merging**
