### PR TITLE
Jupyter: provide extra args to rootnb executable

### PR DESCRIPTION
**Pull request by linev**
Use these args to re-assign IP address where server should be bind.
Now one can use:
```
root --notebook --localhost
root --notebook --ip=myhostname
```
Potentially, all optional args can be forwarded to jupyter-notebook

### CODE REVIEW

**Comment by linev** [comment]
This solves problem on my desktop, where config like:
```
c.NotebookApp.ip = '*'
```
Leads to error when starting notebook.

**Comment by etejedor** [comment]
Thanks for the PR, I believe it would be better to make this more generic and just forward any argument after `root --notebook` to jupyter, not only `--ip` or `localhost`. I guess that if we just forward the arguments to Jupyter, then it will take into account our argument over what is specified in the Jupyter configuration file (although I am not 100% sure).

**Comment by linev** [comment]
> I guess that if we just forward the arguments to Jupyter, then it will take into account our argument
 > over what is specified in the Jupyter configuration file (although I am not 100% sure).

Yes, this also works. Now I just forward all args to jupyter executable.
For me it still works when starting:
```
root --notebook --ip=hostname
```

**Comment by etejedor** [comment]
I agree, since this PR makes it possible to override options, the user has the possibility to set the ip themselves. That would also alleviate issues of people using the Jupyter versions with the bug that prevents parsing the option.

**Comment by linev** [comment]
Ok, I remove it from default options and add few more comments into release notes

**Pull request merged**
