### PR TITLE
Implement rapidity-based DeltaR calculations in TLorentzVector

### PR DESCRIPTION
**Pull request by mattleblanc**
Hello,

At the moment, the `ROOT::TLorentzVector` class uses a pseudorapidity-based calculation for the commonly-used DeltaR distance between vectors. For massive objects, such as jets, the rapidity should often be used instead. I have implemented a small switch within the `TLorentzVector::DeltaR` function to allow users to make this calculation with the vector's rapidity, instead of pseudorapidity. This has a default value of `kFALSE`, which means that the current behaviour will be the default one.

I have cross-checked this new functionality with the `fastjet::pseudojet::delta_R` implementation and an internal ATLAS one, which all give the same results when performing the rapidity-based calculation.

Please let me know if I have violated any contribution guidelines, and I will update this PR accordingly!

🍻 Matt

### CODE REVIEW

**Comment by mattleblanc** [comment]
Hi, I guess this should also be implemented in VectorUtil -- this is a work-in-progress until I push another commit. Sorry for not sending it all at once!

MLB

**Comment by lmoneta** [comment]
Hi Matt

 Than you for your contribution!

If you have time, it would be nice to add also this also for the Genvector package for the `ROOT::Math::LorentzVector` classes. This can be added as a new function in the VectorUtil file, something like `DeltaRapidityPhi`. 
I am not sure if it is better just having just the new function, `DeltaRapidityPhi` instead of `DeltaR` with a boolean parameter.

Cheers

Lorenzo

**Comment by mattleblanc** [comment]
I've added this functionality now also to ROOT::Math::GenVector, it gives the same results as the other implementation and fastjet::pseudojet. I'm not sure if this is exactly how you wanted it implemented, so please let me know if you have further comments -- I've tried to keep everything as consistent as possible between the two sets of changes.

**Comment by mattleblanc** [comment]
Hi @lmoneta, this is just a ping in case you didn't see the other message -- there is obviously no rush, though.

**Comment by oshadura** [comment]
@phsft-bot build!

**Review by lmoneta — APPROVED** [review]

**Review by lmoneta — CHANGES_REQUESTED** [review]
In the case of VectorUtil we need two different functions: 
DeltaR( v1,v2) for Eta
DeltaRapidityPhi (v1,v2) for Rapidity. 

The reason is that we can call DeltaR also for 3D objects and if it is implemented in term of rapidity , it will not compile. You can see this from the failing error from the integration builds.

Can you please add this change ? 

Thank you for this contribution !
Lorenzo

**Comment by mattleblanc** [comment]
Hi @lmoneta, that makes sense -- I have just pushed some more changes. Thanks for the review!

MLB

**Comment by lmoneta** [comment]
Thank you for the changes. They look good now. 
It would be nice to add also a test for the new DeltaRapidityPhi function, for example adding few lines of code in 
https://github.com/root-project/root/blob/master/tutorials/math/mathcoreGenVector.C#L424

If you don't have time doing this, I can do it later, after merging this PR.

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by mattleblanc** [comment]
Hi @lmoneta, I don't have time to implement this test at the moment, but I will add it to my list to revisit in the future, in case I get there before you do. Thanks once again for reviewing this PR!

**Review by lmoneta — APPROVED** [review]
A test will then be added as a separate PR. Thank you @mattleblanc for this contribution!

**Pull request merged**
