### PR TITLE
fix crash when SetSupportGL is enabled but gGLManager is nullptr

### PR DESCRIPTION
**Pull request by ferdymercury**
otherwise I encounter a crash due to a gGLManager=nullptr being accessed in line 1147

### CODE REVIEW

**Review by couet — COMMENTED** [review]
Given the title of your PR I would have thought you test `gGLManager` being null or not instead of `fGLDevice == -1`

**Comment by ferdymercury** [comment]
thanks, I added the gGL check also. But checking fGLDevice is also potentially useful, right?

**Comment by couet** [comment]
> thanks, I added the gGL check also. But checking fGLDevice is also potentially useful, right?

Well I am not sure. If you have a use case for that di you test it ?

**Comment by ferdymercury** [comment]
Yes, just checking fGLDevice != -1 solved the crash for me. probably because fGLDevice is always -1 when gGLManager is null.

**Comment by couet** [comment]
and testing only gGLManager ? does it fix it ?

**Comment by ferdymercury** [comment]
Yes, that fixes it, too.

However I was taking a look at the example here:
https://github.com/root-project/root/blob/146772b95e4a33918b71f9a965dc31736c5092e8/graf2d/gpad/src/TCanvas.cxx#L2617

and thought it was better to check for fGLDevice also.

**Comment by ferdymercury** [comment]
See also this part in the constructor:
```

if (fGLDevice == -1)
         fUseGL = kFALSE;
```

SetSupportGL(true) overwrites fUseGL to true even if fGLDevice is -1.

**Comment by couet** [comment]
Ah ok ... fair enough... if it is already done that way elsewhere do it by testing fGLDevice only ... so your first implementation was correct. Sorry for the noise.

**Review by couet — APPROVED** [review]

**Comment by ferdymercury** [comment]
sure, no worries

**Review by couet — APPROVED** [review]

**Pull request merged**
