### PR TITLE
[RF] Remove usage of RooNameSet and use helper functions instead

### PR DESCRIPTION
**Pull request by guitargeek**
The RooNameSet class is too complicated considering that it fulfills a
rather simple purpose, which is to serialize the names of objects in a
RooArgSet to a string that can be used to select objects from other
RooArgSets.

This commit proposes to replace the RooNameSet class by new functions in
the RooHelpers namespace: `getColonSeparatedNameString` and
`selectFromArgSet`. These functions make use of `std::string` to be much
less verbose than the original RooNameSet class.

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
👍 for not using this, any more. You might, however, break user code out there in the world. Consider moving it into [`RooFitLegacy`](https://github.com/root-project/root/tree/master/roofit/roofitcore/inc/RooFitLegacy) or add a description for how to modernise.

An in-between solution is to move it now and use 
https://github.com/root-project/root/blob/d59c871f161716cbf2b707d36d062eee7d4b0189/core/foundation/inc/ROOT/RConfig.hxx#L514-L527
to trigger deprecation warnings. In e.g. 6.28 you can remove it, then.

**Comment by guitargeek** [comment]
Hi @hageboeck, thanks for your comments! I have implemented them by removing the second commit where I removed the RooNameSet class.

Instead, there is now a new commit where I move it to RooFitLegacy.

**Comment by guitargeek** [comment]
By the way, I changed my other PR https://github.com/root-project/root/pull/8078 to deprecate the RooHashTable in the same way that Stephan suggested here for the RooNameSet.

**Review by lmoneta — APPROVED** [review]
LGTM! 
Thanks for making this change!

**Pull request merged**
