### PR TITLE
[reve] Rename function ExportToCINT to ExportToInterpreter

### PR DESCRIPTION
**Pull request by alja**
This PR:
* Removes CINT from function name
* Minor improvement in error ellipsoid example

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check.

**Review by dpiparo — APPROVED** [review]
LGTM, Thanks.

**Comment by dpiparo** [comment]
@alja there are conflicts in your changes.

**Comment by alja** [comment]
@dpiparo I made a mistake with rebase. I will redo the PR with another branch.

**Pull request closed without merging**
