### PR TITLE
[cmake] Allow C++20, fwiw given llvm9.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Suggested by LHCb.

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]

**Review by oshadura — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora34/default with flags -DCMAKE_CXX_STANDARD=20

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora34/default with flags -DCMAKE_CXX_STANDARD=20

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora34/default with flags -DCMAKE_CXX_STANDARD=20

**Comment by Axel-Naumann** [comment]
llvm9 is missing functionality required to parse GCC11's libstdc++ in C++20 mode. Given that it seems unnecessary to merge this into v6.24/02.

**Pull request merged**
