### PR TITLE
[ci] Add Fedora 41 builds

### PR DESCRIPTION
**Pull request by dpiparo**

### CODE REVIEW

**Comment by guitargeek** [comment]
Related: https://github.com/root-project/root/pull/16749

**Comment by dpiparo** [comment]
rebased and restarted

**Comment by guitargeek** [comment]
This is not looking good, I can reproduce all these failures also on Arch Linux with Python 3.13...

**Comment by wlav** [comment]
Typically, disparate errors that are all kinda the same mean an error was set prior by some other operation and not cleared. What then happens is that the next (any) Python operation fails, setting its own error.

This is something that's new:
```
+Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
```
and may help narrow it down.

**Comment by guitargeek** [comment]
I have investigated one of the failures a bit more, and here is my status:
https://github.com/wlav/cppyy/issues/272

I'll have to stop working on this for today, but I wanted to leave it there just in case you have an idea.

**Comment by guitargeek** [comment]
After the recent updates to ROOT master, only these test failures remain:
```txt
 384:test-stressgraphics-chrome
1403:tutorial-roofit-rf617_simulation_based_inference_multidimensional-py
1404:tutorial-roofit-rf618_mixture_models-py
1634:roottest-python-cling-class
1726:roottest-python-numba-numba
1731:roottest-python-regression-regression
```

**Comment by guitargeek** [comment]
Superseded by #16851.

**Pull request closed without merging**
