### PR TITLE
CMake build option with recommended developer settings

### PR DESCRIPTION
**Pull request by Axel-Naumann**
- `-Werror`
- fastest linker around
- split DWARF (to accelerate link times)
- use gdb-index to accelerate starting ROOT in a debugger

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -Ddev=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
> Super nice!!! Can we add somewhere README for developers?

@oshadura like this https://github.com/root-project/root/pull/5085/commits/8a02e9f6a3702d5c05ab059730afdc6eda74027c ?

**Comment by oshadura** [comment]
I think it is ready to go, but why Jenkins is red? (I can't open this particular log)

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-fedora29/python3

**Pull request merged**
