### PR TITLE
Label longtest for tests running over 1 minute

### PR DESCRIPTION
**Pull request by martinmine**
Tests are labeled `longtest` if they run longer than 1 minute, based on this build: http://cdash.cern.ch/viewTest.php?onlypassed&buildid=329399
This is to be able to skip tests that runs for longer time, when for example during building of PRs when extensive testing may not be needed.

Will make another PR in https://github.com/root-project/roottest as well that has the other tests labeled.

### CODE REVIEW

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by dpiparo** [comment]
Hi @martinmine ,

do you think we can also try and reduce the runtime of some tests and tutorial so that we gain coverage *and* time ?

**Comment by martinmine** [comment]
@dpiparo while I think this may be possible, it goes beyond the scope of this PR.

I have implemented the more verbose way of labeling as suggested by @peremato in commit https://github.com/root-project/root/pull/408/commits/92416250aac7d542f0846e58cfd4d2f85c29694c

**Comment by dpiparo** [comment]
Hi @martinmine ,
sure you are right! I was just looking a bit ahead thinking of a way to 
1) Adiabatically re-add the long tests after making them quicker
2) Make the time needed to run all tests on ci and developers machines faster 
Cheers

**Comment by peremato** [comment]
Merged

**Comment by martinmine** [comment]
@dpiparo That makes sense. Most of the tests that are running for a long time are stress tests, or tests that tests some function under an extensive amount of configurations. Generating or setting up some example case is also a big performance hog on the tests. I think the trade-off for reducing the test time would be to reduce the comprehensiveness of some tests.

**Pull request closed without merging**
