### PR TITLE
Update FindArrow.cmake 

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by oshadura** [comment]
@eguiraud build green, can you edit please commit message and it is ready to go :)

**Comment by eguiraud** [comment]
Thanks for taking a look Oksana, commit message updated!

**Comment by eguiraud** [comment]
Thanks for taking a look Oksana, commit message updated!

**Comment by eguiraud** [comment]
Can't press the merge button because "WIP" is not reporting its status, will try again tomorrow

**Comment by Axel-Naumann** [comment]
Editing the title helped. Might be related to https://github.com/wip/app/issues/216 - i.e. let's give this some more weeks to see whether we get stuck again.

**Pull request merged**
