### PR TITLE
Eve7 Handle RFileDialog response 

### PR DESCRIPTION
**Pull request by alja**
Change Log:
- Enable RFileDialog through REveManager
- Add checks for validity of table and filter expressions
- Clear unnecessary REveManager printouts

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check

**Comment by linev** [comment]
@phsft-bot build

**Review by linev — APPROVED** [review]

**Comment by linev** [comment]
@alja There are no changes in ui5 part concerning FileDialog - do you forget it?

**Comment by alja** [comment]
@linev 
I have made a test example in https://github.com/alja/EveWebApp running macro collection_proxies_test.C.

The file dialog will be used in FireworksWeb to open a data file and save/reload the configuration file.

**Pull request merged**
