### PR TITLE
New 4-vector with Polar3D-mass construction.

### PR DESCRIPTION
**Pull request by whit2333**
Added new four-vector class `PThetaPhiM` for constructing a Lorentz  vector from a 3D polar vector and a mass. This addition class makes use of `Polar3D` for the spatial coordinates.

### CODE REVIEW

**Comment by whit2333** [comment]
Hi @lmoneta,

The Jenkins failed for some odd reason. I cannot login to see the details.

**Comment by whit2333** [comment]
Did any human look into this?

**Comment by lmoneta** [comment]
I thin this PR could be merged. Could you maybe uncomment the test, so we have it running ?

**Comment by lmoneta** [comment]
I close now this PR
If the author wants to merge this, we can re-open, but we need to fix conflict and add the test.

**Pull request closed without merging**
