### PR TITLE
webgui: CEF + batch mode improvments

### PR DESCRIPTION
**Pull request by linev**
Many  improvements in CEF:
- support POST requests, let transfer arbitrary data from client to server
- replace text-based cefQuery messaging by longpoll, required for binary transfer
- assign X11 error handler to avoid application abort in case of minor X11 warnings
- use single-process mode in batch to reduce number of running processes

Provide special handling of batch mode for Chrome and Firefox:
- both support `--headless` mode completely without X 
- very simple workaround to stop browser after 30 s with `timeout 30 chromium ...` command
- let configure custom shell commands via `.rootrc` parameters

Changes in http and webgui libraries:
- "hide" TCivetweb, TFastCgi, THttpWSEngine classes from end-user (@Axel-Naumann)
- remove some comments from civetweb.c  (@amadio)
- use std::copy() instead of memcpy() for std::string (@Axel-Naumann)
- introduce simple key identification of clients, let recognize which client starts by TWebWindow::Show()
- simplify cmake files, separate v7 code in FitPanel

### CODE REVIEW

**Comment by couet** [comment]
looks fine to me .. let see if it passes the tests.

**Comment by amadio** [comment]
Master is broken after this merge. There is a header missing in git.
```
[ 65%] Built target XMLIO
gmake[2]: *** No rule to make target '/home/amadio/src/root/net/http/inc/TCivetweb.h', needed by 'net/http/G__RHTTP.cxx'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:16748: net/http/CMakeFiles/RHTTP.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

```

**Comment by linev** [comment]
> Master is broken after this merge. There is a header missing in git.

No, you need to build from scratch or just delete:

     [shell] rm -rf net/http

**Comment by amadio** [comment]
Ah, I re-ran CMake, but did not remove the directory... Thanks! This sort of problem will go away when we start listing all files in the build system. It's a really annoying problem.

**Pull request merged**
