### PR TITLE
[cling] Fix test MultipleInterpreters.C

### PR DESCRIPTION
**Pull request by hahnjo**
The return type of `foo(int)` is `void`, which causes an assertion failure in `lib/Interpreter/Value.cpp:163`: "Type not supported".

### CODE REVIEW

**Comment by hahnjo** [comment]
In principle this should be caught by `if (C.hasSameType(QT, C.VoidTy))` that was added in the same PR: https://github.com/root-project/root/pull/11252

**Comment by vgvassilev** [comment]
I agree that the test should probably not use `echo` for that but we should probably fix the interface, too. Is `Value::isVoid` not being checked in the `echo` interface? I am not sure I understand how it worked before and how the PR you mentioned broke it..

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Review by jalopezg-git — APPROVED** [review]
LGTM! (ouch, this came across unnoticed for me in the past)

**Pull request merged**
