### PR TITLE
[Doc] Add PyMVA introduction and Keras documentation to TMVA Users Guide

### PR DESCRIPTION
**Pull request by stwunsch**
- Add PyMVA introduction and Keras documentation to TMVA Users Guide.
- Set default options for PyKeras method correctly.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Stefan,

thanks for the PR: looks like great documentation. Usually we write documentation in markdown: is there a reason why you went for latex? Was a strategy to generate this doc every night discussed somewhere?

**Comment by stwunsch** [comment]
We decided in a TMVA meeting that we want to update the TMVA User's Guide, e.g., such as Simon did recently for the new DNN method. That's the reason for the latex code. As far as I know (and are able to use grep), there's not yet a pandoc integration for the TMVA User's guide such as done for the other docs.

**Comment by dpiparo** [comment]
I see. I'd like to see this automatically generated and linked from here https://root.cern.ch/root-user-guides-and-manuals .
Would it be a problem to convert all this to markdown (pandoc -s example4.tex -o example5.text)?  @couet @lmoneta what do you think?

**Comment by stwunsch** [comment]
I doubt that it's easily portable. E.g., as far as I know latex references are not directly portable to html (via markdown) and there are quite a lot of custom functions such as the option tables or the code examples. Still, I like the idea to have it in markdown so it can be ported via pandoc easily to other formats. Though, this would probably need a major refactoring of the document.

**Comment by dpiparo** [comment]
Hi,
as I said, we do not generate any documentation from latex and leave it in source format is not as useful as providing it on the ROOT website as pdf, html and various other formats. I let @lmoneta and @couet comment further about this though.

**Comment by couet** [comment]
I can help with the conversion to markdown if we decide to do it.

**Pull request merged**
