### PR TITLE
[RDF] Fix a dependency issue for an RDF test.

### PR DESCRIPTION
**Pull request by hageboeck**
splitcoll-arrayview needs a dictionary to run. This creates a depedency
between dictionary generation and test target to fix a build-system race
condition.

### CODE REVIEW

**Comment by eguiraud** [comment]
Thanks a lot @hageboeck !

**Comment by hageboeck** [comment]
Fixed a typo in the commit message ..

**Comment by hageboeck** [comment]
> Thanks a lot @hageboeck !

Sure, NP.

**Comment by oshadura** [comment]
@hageboeck @eguiraud  sorry for delay! :)))

**Pull request merged**
