### PR TITLE
Conv branch

### PR DESCRIPTION
**Pull request by arthur-tsang**
This pull request integrates the `TF1Convolution` object into `TF1` so that one can directly create a `TF1` with a convolution in it. The syntax to construct such a convolution is:
`new TF1("f", "CONV(f1, f2)")`
Note that convolutions can be nested with each other and `NSUM`s.

Also, if you are helping me merge, please note that this pull request contains within it the `TF1NormSum` code from PR #799.

### CODE REVIEW

**Comment by martinmine** [comment]
@arthur-tsang thanks for your contribution, perhaps you want to re-base to resolve the conflicts and we can test your PR?

**Comment by arthur-tsang** [comment]
Ok, I will rebase it this evening

**Comment by pcanal** [comment]
> > Ok, I will rebase it this evening
>  merge with current master

Note that 'merge commit' to catch up with the master are **not** allowed.  Please use rebase instead.

**Comment by arthur-tsang** [comment]
@pcanal thanks for the clarification (I've never done a rebase before); I went back and did the merge using `git rebase` this time.

**Comment by martinmine** [comment]
@arthur-tsang your history seems to be duplicated after rebasing. If you want to, I can come help you out with rebasing. Where is your office?

**Comment by arthur-tsang** [comment]
@martinmine yes, please. My office is 2-0-25.

**Comment by martinmine** [comment]
@arthur-tsang I'll drop by after lunch :)

**Pull request closed without merging**
