### PR TITLE
[clad] Bump clad version to v1.4.

### PR DESCRIPTION
**Pull request by vgvassilev**
This new release includes several fixes helping to simplify RooFit AD backend.

See more at: https://github.com/vgvassilev/clad/releases/tag/v1.4

### CODE REVIEW

**Comment by vgvassilev** [comment]
> Build failed on windows10/default. Running on null:C:\build\workspace\root-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/196397/console).

Hi @bellenot, do you have a clue if that failure is related to this particular PR?

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/default

**Comment by vgvassilev** [comment]
These failures seem unrelated to this PR.

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/default

**Comment by vgvassilev** [comment]
Another set of unrelated failures. @guitargeek can we move forward here?

**Review by guitargeek — APPROVED** [review]
Thanks! Yes, the failures are unrelated. I look forward to this getting merged, so I can merge the other PR that built on Garimas work to make the generated code faster to compile!

**Pull request merged**
