### PR TITLE
[webgui] adjust code for use on Windows

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by linev** [comment]
I hit a fancy problem with civetweb on Windows. It does not work properly if I running ROOT from the path which contains symbolic link. I will provide a fast fix, but problem has to be resolved on civetweb side later.

**Comment by bellenot** [comment]
> I hit a fancy problem with civetweb on Windows. It does not work properly if I running ROOT from the path which contains symbolic link. I will provide a fast fix, but problem has to be resolved on civetweb side later.

There is no symbolic link on Windows...

**Comment by linev** [comment]
> There is no symbolic link on Windows...

Yes, they are. 
On German Windows there is folder "C:\Programme", which is just symbolic link to "C:\Program Files". And I try to use ROOTSYS as "C:\Programme\root", avoiding spaces in the path.

**Comment by bellenot** [comment]
Oh! OK, I see (they are called `shortcuts` on Windows...) :wink:

**Comment by linev** [comment]
> they are called shortcuts on Windows...

API function called CreateSymbolicLink

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka?redirectedfrom=MSDN

**Pull request merged**
