### PR TITLE
[IO] Deprecate TStreamerElement::ESTLtype in favor of ROOT::ESTLType

### PR DESCRIPTION
**Pull request by eguiraud**
I don't know if this is desirable or not, but I figured I would raise the issue. `TStreamerElement::ESTLtype` duplicates `ROOT::ESTLType` exactly, but with a lower-case `t` in `type`. It confused me when I found this out (and it turns out that I forgot to update `TStreamerElement::ESTLtype` when I updated `ROOT::ESTLType`).

I could not find any usage of `TStreamerElement::ESTLType` in ROOT, and ROOT compiles just fine without the enum, but just in case someone out there is using it, I'm proposing to deprecate it in 6.24 and remove it in 6.26.

Feel free to close this PR if you don't think this makes sense.

UPDATE:

after discussion with @pcanal we decided that deprecation/removal is the right thing to do, and I extended the patch to `TDictionary` and `TClassEdit`. `TBufferJSON` had some usage of `TClassEdit::ESTLType` which has now been substituted with `ROOT::ESTLType`.

UPDATE 2:

Since gcc 5 (the system compiler on Ubuntu 16) [does not support deprecation of enumerators](https://godbolt.org/z/1TEo5M), I'm proposing to disable `R__DEPRECATED` for that gcc version (it was already disabled for gcc 5.1 and 5.2 due to a different issue).

### CODE REVIEW

**Comment by eguiraud** [comment]
What the heck ubuntu16 :expressionless:

**Comment by eguiraud** [comment]
gcc 5.3, used in Ubuntu 16, does not support `__attribute__((deprecated))` in that position: https://godbolt.org/z/jz1ove

**Comment by eguiraud** [comment]
Mmmmh ok I have to figure out where `std::is_same<unsigned int, std::underlying_type<TDictionary::ESTLType>::type>::value;` comes from in PyROOT.

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
I have updated the PR by rebasing on master, refreshing the version in the deprecation macros, and dropping the GCC 5 workaround because the minimum supported version is GCC 8 anyway:
https://root.cern/install/dependencies/

**Comment by eguiraud** [comment]
:heart:

**Comment by pcanal** [comment]
It looks like we need a companion `roottest` PR.

**Comment by guitargeek** [comment]
Replaced by #15487.

**Pull request closed without merging**
