### PR TITLE
Keep read-only functionality in TWebCanvas for ROOT6

### PR DESCRIPTION
**Pull request by linev**
Now TWebCanvas only able to serve data for the web clients, but not allowed to change data in the TCanvas. This means:
- no new objects
- no context menu
- no range update
- no any attributes updates
- no any command execution

Full-functional implementation, based on TWebCanvas, will be maintained outside ROOT here:
https://github.com/linev/go4/tree/master/webgui6

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build just on ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags -Droot7=ON

**Comment by linev** [comment]
@phsft-bot build just on ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags -Droot7=ON

**Comment by Axel-Naumann** [comment]
For the record, `RCanvas` provides an interactive WebGUI canvas for ROOT.

**Pull request merged**
