### PR TITLE
Build core/macosx only when cocoa=ON

### LINKED ISSUE #12527: MacOS build fails if configured without cocoa
On macOS, `-Dcocoa=Off` will cause the build to fail with
```
[ 77%] Linking CXX shared library ../lib/libCore.so
Undefined symbols for architecture arm64:
  "TMacOSXSystem::TMacOSXSystem()", referenced from:
      ROOT::new_TMacOSXSystem(void*) in G__Core.cxx.o
      ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
  "TMacOSXSystem::~TMacOSXSystem()", referenced from:
      ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
      ROOT::deleteArray_TMacOSXSystem(void*) in G__Core.cxx.o
  "typeinfo for TMacOSXSystem", referenced from:
      ROOT::GenerateInitInstanceLocal(TMacOSXSystem const*) in G__Core.cxx.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libCore.so] Error 1
make[1]: *** [core/CMakeFiles/Core.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by amadio**
Fixes #12527.

### CODE REVIEW

**Comment by amadio** [comment]
@phsft-bot build just on mac12/cxx14 with flags -Dcocoa=Off

**Comment by Axel-Naumann** [comment]
We don't have XQuartz installed on our Macs, so testing cannot really succeed :-/ We are discussing whether we should just force cocoa for macOS and "deprecate" x11 on macOS (given that it might not build anymore since years...) We'll leave this open until we decide.

**Comment by amadio** [comment]
The CI pages are hanging when I try to check what went wrong, @Axel-Naumann are the errors seen above expected? I don't think my change is causing them.

**Comment by Axel-Naumann** [comment]
Before going there we need to decide on https://github.com/root-project/root/pull/12528#issuecomment-1483209784

**Comment by pcanal** [comment]
This PR is actually independent on the decision on X11.  Merging this PR is necessary to build without Cocoa AND without X11 (in addition to with X11).

**Review by pcanal — APPROVED** [review]
Thanks.

**Comment by pcanal** [comment]
However this PR is not sufficient, we also need: https://github.com/root-project/root/pull/14387

**Pull request merged**
