### PR TITLE
Add checksum support to LZ4 compression

### PR DESCRIPTION
**Pull request by bbockelm**
This is a backport of #907, cherry-picked from 1776869fbb8d45b1bd4fc5e06194493dc45d5e25.

### CODE REVIEW

**Comment by amadio** [comment]
@bbockelm Before we can merge this, we need to test with both builtin and external lz4, since ROOT is currently broken with the latter.

**Comment by oshadura** [comment]
Updated PR: https://github.com/root-project/root/pull/1012

**Comment by amadio** [comment]
Should we just close this PR then and use the newer one?

**Comment by amadio** [comment]
This has been merged via other means. Closing.

**Pull request closed without merging**
