### PR TITLE
Fix an error when generating the Unuran dictionary on Windows

### PR DESCRIPTION
**Pull request by bellenot**
This fixes the following (potentially erroneous) error:
Error in <CloseStreamerInfoROOTFile>: Unique pointer unique_ptr<TUnuranBaseDist,default_delete<TUnuranBaseDist > > has zero data members.

### CODE REVIEW

**Comment by pcanal** [comment]
What does the declaration of unique_ptr looks like on Windows?  What does .class unique_ptr<something> say?

**Comment by bellenot** [comment]
> What does the declaration of unique_ptr looks like on Windows?

	// CLASS TEMPLATE _Unique_ptr_base
template<class _Ty,
	class _Dx>
	class _Unique_ptr_base
	{	// stores pointer and deleter
public:
	typedef remove_reference_t<_Dx> _Dx_noref;
	typedef typename _Get_deleter_pointer_type<_Ty, _Dx_noref>::type pointer;

	template<class _Ptr2,
		class _Dx2>
		_Unique_ptr_base(_Ptr2 _Ptr, _Dx2&& _Dt)
		: _Mypair(_One_then_variadic_args_t(), _STD forward<_Dx2>(_Dt), _Ptr)
		{	// construct with compatible pointer and deleter
		}

	template<class _Ptr2>
		constexpr _Unique_ptr_base(_Ptr2 _Ptr)
		: _Mypair(_Zero_then_variadic_args_t(), _Ptr)
		{	// construct with compatible pointer
		}

	_NODISCARD _Dx& get_deleter() _NOEXCEPT
		{	// return reference to deleter
		return (_Mypair._Get_first());
		}

	_NODISCARD const _Dx& get_deleter() const _NOEXCEPT
		{	// return const reference to deleter
		return (_Mypair._Get_first());
		}

	pointer& _Myptr() _NOEXCEPT
		{	// return reference to pointer
		return (_Mypair._Get_second());
		}

	const pointer& _Myptr() const _NOEXCEPT
		{	// return const reference to pointer
		return (_Mypair._Get_second());
		}

	_Compressed_pair<_Dx, pointer> _Mypair;
	};

	// CLASS TEMPLATE unique_ptr SCALAR
template<class _Ty,
	class _Dx>	// = default_delete<_Ty>
	class unique_ptr
		: public _Unique_ptr_base<_Ty, _Dx>
	{	// non-copyable pointer to an object
public:
	typedef _Unique_ptr_base<_Ty, _Dx> _Mybase;
	typedef typename _Mybase::pointer pointer;
	typedef _Ty element_type;
	typedef _Dx deleter_type;

	using _Mybase::get_deleter;

	template<class _Dx2 = _Dx,
		_Unique_ptr_enable_default_t<_Dx2> = 0>
		constexpr unique_ptr() _NOEXCEPT
			: _Mybase(pointer())
		{	// default construct
		}

	template<class _Dx2 = _Dx,
		_Unique_ptr_enable_default_t<_Dx2> = 0>
		constexpr unique_ptr(nullptr_t) _NOEXCEPT
			: _Mybase(pointer())
		{	// null pointer construct
		}

	unique_ptr& operator=(nullptr_t) _NOEXCEPT
		{	// assign a null pointer
		reset();
		return (*this);
		}

	template<class _Dx2 = _Dx,
		_Unique_ptr_enable_default_t<_Dx2> = 0>
		explicit unique_ptr(pointer _Ptr) _NOEXCEPT
			: _Mybase(_Ptr)
		{	// construct with pointer
		}

	template<class _Dx2 = _Dx,
		enable_if_t<is_constructible_v<_Dx2, const _Dx2&>, int> = 0>
		unique_ptr(pointer _Ptr, const _Dx& _Dt) _NOEXCEPT
			: _Mybase(_Ptr, _Dt)
		{	// construct with pointer and (maybe const) deleter&
		}

	template<class _Dx2 = _Dx,
		enable_if_t<conjunction_v<negation<is_reference<_Dx2>>,
			is_constructible<_Dx2, _Dx2>>, int> = 0>
		unique_ptr(pointer _Ptr, _Dx&& _Dt) _NOEXCEPT
			: _Mybase(_Ptr, _STD move(_Dt))
		{	// construct by moving deleter
		}

	template<class _Dx2 = _Dx,
		enable_if_t<conjunction_v<is_reference<_Dx2>,
			is_constructible<_Dx2, remove_reference_t<_Dx2>>>, int> = 0>
		unique_ptr(pointer, remove_reference_t<_Dx>&&) = delete;

	unique_ptr(unique_ptr&& _Right) _NOEXCEPT
		: _Mybase(_Right.release(),
			_STD forward<_Dx>(_Right.get_deleter()))
		{	// construct by moving _Right
		}

	template<class _Ty2,
		class _Dx2,
		enable_if_t<conjunction_v<negation<is_array<_Ty2>>,
			is_convertible<typename unique_ptr<_Ty2, _Dx2>::pointer, pointer>,
			conditional_t<is_reference_v<_Dx>, is_same<_Dx2, _Dx>, is_convertible<_Dx2, _Dx>>
		>, int> = 0>
		unique_ptr(unique_ptr<_Ty2, _Dx2>&& _Right) _NOEXCEPT
			: _Mybase(_Right.release(),
				_STD forward<_Dx2>(_Right.get_deleter()))
		{	// construct by moving _Right
		}

 #if _HAS_AUTO_PTR_ETC
	template<class _Ty2,
		enable_if_t<conjunction_v<is_convertible<_Ty2 *, _Ty *>,
			is_same<_Dx, default_delete<_Ty>>>, int> = 0>
		unique_ptr(auto_ptr<_Ty2>&& _Right) _NOEXCEPT
			: _Mybase(_Right.release())
		{	// construct by moving _Right
		}
 #endif /* _HAS_AUTO_PTR_ETC */

	template<class _Ty2,
		class _Dx2,
		enable_if_t<conjunction_v<negation<is_array<_Ty2>>,
			is_assignable<_Dx&, _Dx2>,
			is_convertible<typename unique_ptr<_Ty2, _Dx2>::pointer, pointer>
		>, int> = 0>
		unique_ptr& operator=(unique_ptr<_Ty2, _Dx2>&& _Right) _NOEXCEPT
		{	// assign by moving _Right
		reset(_Right.release());
		this->get_deleter() = _STD forward<_Dx2>(_Right.get_deleter());
		return (*this);
		}

	unique_ptr& operator=(unique_ptr&& _Right) _NOEXCEPT
		{	// assign by moving _Right
		if (this != _STD addressof(_Right))
			{	// different, do the move
			reset(_Right.release());
			this->get_deleter() = _STD forward<_Dx>(_Right.get_deleter());
			}
		return (*this);
		}

	void swap(unique_ptr& _Right) _NOEXCEPT
		{	// swap elements
		_Swap_adl(this->_Myptr(), _Right._Myptr());
		_Swap_adl(this->get_deleter(), _Right.get_deleter());
		}

	~unique_ptr() _NOEXCEPT
		{	// destroy the object
		if (get() != pointer())
			{
			this->get_deleter()(get());
			}
		}

	_NODISCARD add_lvalue_reference_t<_Ty> operator*() const
		{	// return reference to object
		return (*get());
		}

	_NODISCARD pointer operator->() const _NOEXCEPT
		{	// return pointer to class object
		return (this->_Myptr());
		}

	_NODISCARD pointer get() const _NOEXCEPT
		{	// return pointer to object
		return (this->_Myptr());
		}

	explicit operator bool() const _NOEXCEPT
		{	// test for non-null pointer
		return (get() != pointer());
		}

	pointer release() _NOEXCEPT
		{	// yield ownership of pointer
		pointer _Ans = get();
		this->_Myptr() = pointer();
		return (_Ans);
		}

	void reset(pointer _Ptr = pointer()) _NOEXCEPT
		{	// establish new pointer
		pointer _Old = get();
		this->_Myptr() = _Ptr;
		if (_Old != pointer())
			{
			this->get_deleter()(_Old);
			}
		}

	unique_ptr(const unique_ptr&) = delete;
	unique_ptr& operator=(const unique_ptr&) = delete;
	};

> What does .class unique_ptr say?
root [0] .class unique_ptr
Class unique_ptr not found
root [1]

**Comment by pcanal** [comment]
What about 
```
.class unique_ptr<TObject>
```
:)

**Comment by bellenot** [comment]
> What about
> 
> ```
> .class unique_ptr<TObject>
> ```
> :)
```
root [1] .class unique_ptr<TObject>
===========================================================================
class std::unique_ptr<class TObject, struct std::default_delete<class TObject> >
SIZE: 4 FILE: memory LINE: -1
Base classes: --------------------------------------------------------
0x0        public std::_Unique_ptr_base<class TObject, struct std::default_delete<class TObject> >
List of member variables --------------------------------------------------
List of member functions :---------------------------------------------------
filename     line:size busy function type and name
(compiled)     (NA):(NA) 0 public: unique_ptr(std::unique_ptr<TObject, std::default_delete<TObject> > &&_Right);
(compiled)     (NA):(NA) 0 public: unique_ptr(const std::unique_ptr<TObject, std::default_delete<TObject> > &);
(compiled)     (NA):(NA) 0 public: class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &operator=(std::nullptr_t) noexcept;
(compiled)     (NA):(NA) 0 public: class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &operator=(class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &&_Right) noexcept;
(compiled)     (NA):(NA) 0 public: void swap(class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &_Right) noexcept;
(compiled)     (NA):(NA) 0 public: ~unique_ptr<TObject, default_delete<TObject> >() noexcept;
(compiled)     (NA):(NA) 0 public: add_lvalue_reference_t<class TObject> operator*() const;
(compiled)     (NA):(NA) 0 public: std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer operator->() const noexcept;
(compiled)     (NA):(NA) 0 public: std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer get() const noexcept;
(compiled)     (NA):(NA) 0 public: explicit operator bool() const noexcept;
(compiled)     (NA):(NA) 0 public: std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer release() noexcept;
(compiled)     (NA):(NA) 0 public: void reset(std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer _Ptr) noexcept;
(compiled)     (NA):(NA) 0 public: class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &operator=(const class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &) = delete;
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, _Unique_ptr_enable_default_t<_Dx2> = 0> constexpr unique_ptr() noexcept unique_ptr();
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, _Unique_ptr_enable_default_t<_Dx2> = 0> constexpr unique_ptr(std::nullptr_t) noexcept unique_ptr(std::nullptr_t);
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, _Unique_ptr_enable_default_t<_Dx2> = 0> explicit unique_ptr(std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer _Ptr) noexcept explicit unique_ptr(std::unique_ptr<TObject, std::default_delete<TObject> >::pointer _Ptr);
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, enable_if_t<is_constructible_v<_Dx2, const _Dx2 &>, int> = 0> unique_ptr(std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer _Ptr, const struct std::default_delete<class TObject> &_Dt) noexcept unique_ptr(std::unique_ptr<TObject, std::default_delete<TObject> >::pointer _Ptr, const std::default_delete<TObject> &_Dt);
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, enable_if_t<conjunction_v<negation<is_reference<_Dx2> >, is_constructible<_Dx2, _Dx2> >, int> = 0> unique_ptr(std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer _Ptr, struct std::default_delete<class TObject> &&_Dt) noexcept unique_ptr(std::unique_ptr<TObject, std::default_delete<TObject> >::pointer _Ptr, std::default_delete<TObject> &&_Dt);
(compiled)     (NA):(NA) 0 public: template <class _Dx2 = struct std::default_delete<class TObject>, enable_if_t<conjunction_v<is_reference<_Dx2>, is_constructible<_Dx2, remove_reference_t<_Dx2> > >, int> = 0> unique_ptr(std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer, remove_reference_t<struct std::default_delete<class TObject> > &&) = delete unique_ptr(std::unique_ptr<TObject, std::default_delete<TObject> >::pointer, remove_reference_t<std::default_delete<TObject> > &&);
(compiled)     (NA):(NA) 0 public: template <class _Ty2, class _Dx2, enable_if_t<conjunction_v<negation<is_array<_Ty2> >, is_convertible<typename unique_ptr<_Ty2, _Dx2>::pointer, std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer>, conditional_t<is_reference_v<struct std::default_delete<class TObject> >, is_same<_Dx2, struct std::default_delete<class TObject> >, is_convertible<_Dx2, struct std::default_delete<class TObject> > > >, int> = 0> unique_ptr(unique_ptr<_Ty2, _Dx2> &&_Right) noexcept unique_ptr(unique_ptr<_Ty2, _Dx2> &&_Right);
(compiled)     (NA):(NA) 0 public: template <class _Ty2, enable_if_t<conjunction_v<is_convertible<_Ty2 *, class TObject *>, is_same<struct std::default_delete<class TObject>, default_delete<class TObject> > >, int> = 0> unique_ptr(auto_ptr<_Ty2> &&_Right) noexcept unique_ptr(auto_ptr<_Ty2> &&_Right);
(compiled)     (NA):(NA) 0 public: template <class _Ty2, class _Dx2, enable_if_t<conjunction_v<negation<is_array<_Ty2> >, is_assignable<struct std::default_delete<class TObject> &, _Dx2>, is_convertible<typename unique_ptr<_Ty2, _Dx2>::pointer, std::unique_ptr<class TObject, struct std::default_delete<class TObject> >::pointer> >, int> = 0> class std::unique_ptr<class TObject, struct std::default_delete<class TObject> > &operator=(unique_ptr<_Ty2, _Dx2> &&_Right) noexcept;
root [2]

```

**Comment by bellenot** [comment]
@pcanal so?

**Comment by pcanal** [comment]
The problem is that the data member are in a base class rather than a direct class.  Rather than specialized for Windows you could replace :
```
auto upDms = clm->GetListOfDataMembers();
```
with 
```
auto upDms = clm->GetListOfRealData();
```
Cheers,
Philippe.

**Comment by bellenot** [comment]
@pcanal Well, OK, fine, I'll try. But what is the purpose of this check anyway? (seriously)

**Comment by pcanal** [comment]
It is a first order test that unique_ptr is vaguely as expected .... (See @dpiparo for more details).

**Comment by bellenot** [comment]
We looked at the code together, and the proposed solution was good enough for him... @dpiparo, do you want to comment?

**Comment by bellenot** [comment]
> auto upDms = clm->GetListOfRealData();

doesn't work...

**Comment by bellenot** [comment]
> you probably need to call
> 
> ```
> clm->BuildRealData();
> ```
> before hand.

OK, that seems to work on Windows. I will discuss with Danilo on Monday what is the best option, but IMHO, we already spent too much time on this (potentially useless) piece of code...

**Comment by bellenot** [comment]
Let's try if it works everywhere, and @pcanal, please let me know if it's ok with you to merge this PR once all platforms are green

**Pull request merged**
