### PR TITLE
[CMake] Start migrating strong dependencies outside SearchInstalledSoftware and deprecate 'python' option

### PR DESCRIPTION
**Pull request by maxgalli**
In order to:
- make the build system less entangled and more maintainable 
- give a solution to the bug mentioned in https://github.com/root-project/root/pull/4939
we move the search for Python installation in a new script called SearchRootCoreDeps, where also the search for main Root dependencies will happen at some point.

The misleading 'python' option, which was basically enabling pyroot, is deprecated.

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot  build with flags -Dpyroot_experimental=ON

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DKEEP_PR_BUILDS_FOR_A_DAY=ON -Dpyroot_experimental=OFF

**Comment by maxgalli** [comment]
@phsft-bot build with flags -DKEEP_PR_BUILDS_FOR_A_DAY=ON -Dpyroot_experimental=ON

**Comment by maxgalli** [comment]
@phsft-bot build with flags -Dpyroot_experimental=ON

**Comment by oshadura** [comment]
@maxgalli @etejedor  any ideas on how we can make progress with this PR? Do we need to change configuration of node mac1014/cxx17?

Windows build seems to be "green":
```
Error(s) when building project
   0 Compiler errors
   51 or more Compiler warnings
```

**Comment by maxgalli** [comment]
> @maxgalli @etejedor any ideas on how we can make progress with this PR? Do we need to change configuration of node mac1014/cxx17?
> 
> Windows build seems to be "green":
> 
> ```
> Error(s) when building project
>    0 Compiler errors
>    51 or more Compiler warnings
> ```

If I remember correctly, this happens every time we build with PyROOT Experimental on this machine, due to some incompatibility between c++17 and Python2.7 (@etejedor can for sure explain better than me). So yes, I guess the only way to make it green is change the configuration of the node itself (maybe install and build with Python3 or disable the node completely?).

**Comment by etejedor** [comment]
> If I remember correctly, this happens every time we build with PyROOT Experimental on this machine, due to some incompatibility between c++17 and Python2.7 
Yes, this is not related to this PR. When compiling PyROOT with C++17, the compiler complains because Python2.7, in some of its headers, uses the register keyword which is not allowed anymore in C++17.

**Pull request merged**
