### PR TITLE
Formul params3

### PR DESCRIPTION
**Pull request by arthur-tsang**
This pull request allows one to use user-defined (and some predefined) functions with different variables and/or parameters from what was given in the original definition. For example, a function originally defined on variable `x` with parameter `[0]` can now easily be applied to variable `y` with parameter `[alpha]` as part of another function definition. The syntax for the `TFormula` is as follows:
* `f(var0, var1, var2, ..., param0, param1, param2, ...)`

Furthermore, this PR introduces a few shortcuts:
* The syntax `[n..m]` for ranges of numbered parameters (for example, `[1..3]` expands to `[1],[2],[3]`)
* To simply replace/rename parameters, the variables may be omitted
* Otherwise, if redefining variables, the parameters may be omitted (except, of course, if substituting them all for parameters if the numbers of parameters and variables are equal)

This PR supports the nesting of functions (but still not recursive definitions!).

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by arthur-tsang** [comment]
Sorry, I thought I already took care of the clang-format. I will go and do that.

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by lmoneta** [comment]
@phsft-bot build

**Pull request merged**
