### PR TITLE
Resolve error: call to virtual function in destructor

### PR DESCRIPTION
**Pull request by Ask149**
The following files had a destructor making a call to a virtual function. Thus, implicitly the function corresponding to the base class was getting called. In correspondence to the above issue, I would like to suggest explicitly calling the corresponding class function in the destructor, which will resolve the issue keeping the purpose constant.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@lmoneta objections? Else I'll merge.

**Comment by Axel-Naumann** [comment]
Thanks @Ask149 for your contribution, that's a good change! Out of curiosity, how did you detect this?

**Comment by Ask149** [comment]
> Thanks @Ask149 for your contribution, that's a good change! Out of curiosity, how did you detect this?

@Axel-Naumann I encountered a Travis clang build error specifying 'Call to a virtual function in destructor' in my previous pull request #4164, so, while resolving the same, I found the above issue.

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Pull request merged**
