### PR TITLE
Update LinkDef3.h

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi, is this just indentation?

**Comment by Teemperor** [comment]
@dpiparo He added the second template arguments.

**Comment by dpiparo** [comment]
great, thanks! Given that there is no IO for these classes I do not see any issue with the PR.

**Comment by Teemperor** [comment]
This fixed the warnings for me and passes on all systems, but it seems we didn't get a build slot on centos7 yet. As it will most likely also pass there, can we get this merged @dpiparo  that I can test #759 ?

**Comment by vgvassilev** [comment]
The build seems stuck on centos due to probably infrastructure. The rest of the builds seem fine.

**Pull request merged**
