### PR TITLE
[RF] Fix `xroofit` bugs in breakdown,impact,and error on histograms of RooRealSumPdf

### PR DESCRIPTION
**Pull request by will-cern**
This fix will be needed for 6.30 too.

Opening this PR now so that you know it is needed, but I will be continuing to run some tests today and may push some more changes if I find more bugs!

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by will-cern** [comment]
With latest commits this PR is ready to go, I think

**Comment by Axel-Naumann** [comment]
Adding to 6.30 milestone as per @will-cern 's request

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]

**Pull request merged**
