### PR TITLE
Added a search range to TH*::FindFirst(Last)Bin.

### PR DESCRIPTION
**Pull request by ksmith0**
The additional firstBin and lastBin arguments limit the axis being
searched for the bin above or threshold. If the firstBin term is less
than 1 it is set to 1. If the lastBin term is less than 0 or greater than
the number of bins the value is set to the number of bins for that axis.

### CODE REVIEW

**Comment by pamputt** [comment]
I checked manually the patch and it works fine for TH1 and TH2 (x and y axis). I did not test it on TH3

**Comment by lmoneta** [comment]
The PR looks fine to me. However, looking at the code, is it really needed to have 6 functions (2 for each dimensions) doing basically the same thing ? 
I think it would be a good occasion to re-factor the code and have a single functions for all the 3 types of histograms. What do you think ? 

Lorenzo

**Comment by etejedor** [comment]
@pamputt can you provide an answer to @lmoneta?

**Comment by lmoneta** [comment]
I think this PR provide some useful functionality. @ksmith0 if you don't have time to re-factor the code, I can do it

**Comment by ksmith0** [comment]
@lmoneta at this point I think it would be wise for you to finish it off. I clearly have other priorities as this has been open for a year. Thanks for offering to refactor it.

**Comment by lmoneta** [comment]
@ksmith0  thank you for your quick reply. I will try to do it in the next day. I will close then this PR when I will open a new one based on this one

**Comment by lmoneta** [comment]
This PR is now replaces by # 3399. Actually this one contained a bug in TH3::FindFirstBin that is fixed now in the new PR.

**Pull request closed without merging**
