### PR TITLE
Use relative RPATH on Linux and macOS by default

### PR DESCRIPTION
**Pull request by amadio**
This allows our binary releases to be used without needing to `source thisroot.sh` by default on Linux as well as on macOS.

The only setup required will be to `export PYTHONPATH=$(root-config --libdir)` with the `root-config` from the binary release, so that python knows where to get ROOT when the user tries to `import ROOT`.

### CODE REVIEW

**Review by Axel-Naumann — COMMENTED** [review]
Thanks! LGTM but I'd like @bellenot to sign off

**Review by bellenot — APPROVED** [review]
I have no idea what side effects that changes might bring, but I trust you, thanks :-)

**Comment by amadio** [comment]
No side effects, just enables RPATH by default and uses relative paths for them, so they always work, no matter where you extract the binary release tarballs. Thanks for approving!

**Comment by amadio** [comment]
The failing test is not related to my changes. Merging.

**Pull request merged**
