### PR TITLE
[tmva] Fix the dependency of TMVA tutorials and PyMVA tests 

### PR DESCRIPTION
**Pull request by lmoneta**
This Pull request fixes the correct dependency of some TMVA tutorial and PyMVA tests to avoid that the input data files are written at the same time.

The PR contains also a fix for th TMVA_SOFIE_RSofieReader tutorial to handle correctly the  model output vector

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, on ROOT-ubuntu2204/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu2204/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Review by bellenot — APPROVED** [review]
Can you correct the indent in the CMake files (within the `if()` `endif()` pairs)? Otherwise, if you are sure about the dependencies, this is fine with me (for the CMake part).

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu2204/cxx17

**Pull request merged**
