### PR TITLE
[ntuple] Updated formatting for ROOTv7 revised climate tutorial

### PR DESCRIPTION
**Pull request by JohnYoon13**

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@JohnYoon13, thank for working on this. Maybe the PR accidentally deleted files from `interpreter/llvm`?

**Comment by JohnYoon13** [comment]
> @JohnYoon13, thank for working on this. Maybe the PR accidentally deleted files from `interpreter/llvm`?

@vgvassilev I resubmitted a new PR 7306 that includes the llvm files, but still seem to come across build issues.

**Comment by couet** [comment]
It look like you are mixing two things in this PR ? isn't it ?
May be it would be better to make two separated  PRs.

**Pull request closed without merging**
