### PR TITLE
ROOTR fixed event loop

### PR DESCRIPTION
**Pull request by omazapa**
Hi Guys,

* Added support to check if R interface is running in the thread of event loop, to avoid segfault in scientific linux running tests.
* Fixed some datatypes according to coding conventions.

Cheers,
Omar.

### CODE REVIEW

**Comment by omazapa** [comment]
@phsft-bot build!

but something is wrong with travis ci,  can I merge it anyway?

**Comment by vgvassilev** [comment]
@omazapa, it seems you are not following ROOT's coding conventions and this is why travis is unhappy. I'd strongly recommend fixing it first.

**Comment by bluehood** [comment]
@omazapa the quickest fix is copy-pasting the diff from the output of the travis bot to a new file in your local root repo, and running a `git apply` on it. You can also run clang-format yourself. I think you will need at least v3.8, and the bot suggests the following commands:
```
git checkout master
git-clang-format --commit 1230f79df89e95687659859cad39c9fd2e48f4eb --diff --binary clang-format
```

**Comment by vgvassilev** [comment]
`git-clang-format --commit 1230f79df89e95687659859cad39c9fd2e48f4eb --binary clang-format` even applies it automatically.

**Comment by vgvassilev** [comment]
Perhaps you will need to rebase this PR because we changed a little the clang-format policy today.

**Comment by omazapa** [comment]
Thanks @vgvassilev  and @bluehood
Sure, I will to update code.

My bests!

**Pull request merged**
