### PR TITLE
Py2help v2

### PR DESCRIPTION
**Pull request by ElieKhairallah**
Added the necessary commands to generate root command line options and manual page.

### CODE REVIEW

**Comment by couet** [comment]
@phsft-bot build

**Comment by ElieKhairallah** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
Alright, now the infrastructure should be normalized. We just need to submit branches that are up to date with current master. Hopefully the build will pass this time.

**Comment by couet** [comment]
Still did not build. Should we re-submit ?

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by ElieKhairallah** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ubuntu16/native

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by ElieKhairallah** [comment]
@phsft-bot build just on windows10/vc15

**Comment by couet** [comment]
@phsft-bot build just on windows10/vc15

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build just on windows10/vc15

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by couet** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native, slc6-i686/gcc49

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native and slc6-i686/gcc49

**Comment by couet** [comment]
@phsft-bot build

**Comment by couet** [comment]
@phsft-bot build just on mac1013/native

**Comment by couet** [comment]
@phsft-bot build just on mac1013/native

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1013/native, slc6-i686/gcc49

**Comment by vgvassilev** [comment]
@phsft-bot build on mac1013/native, slc6-i686/gcc49

**Comment by couet** [comment]
mac is ok. let's try on windows.

**Comment by couet** [comment]
@phsft-bot build just on mac1013/native

**Comment by vgvassilev** [comment]
This requires rebase on the user side. Closing and we will reopen a new, properly-rebased PR.

**Pull request closed without merging**
