### PR TITLE
[cling] Only set result type if result type is known for auto-injection

### LINKED ISSUE #13965: [Cling] Assertion fails with wrong but innocent code
### Check duplicate issues.

- [X] Checked for duplicates

### Description

There is a very simple way to cause an assertion in cling through wrong but innocent C++ code

### Reproducer

```cpp
root [0] g=TF1("gaus")
Assertion failed: ((D->NextInContextAndBits.getPointer() || D == LastDecl) && "decl is not in decls list"), function removeDecl, file DeclBase.cpp, line 1477.
```

### ROOT version

master, MacOS 14

### Installation method

built from sources, debug (clang in release mode)

### Operating system

MacOS 14

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devajithvs**
fixes #13965

# This Pull request:

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #13965

### CODE REVIEW

**Comment by devajithvs** [comment]
Still need to create the LLVM tag. Failing llvm-diff can be rerun once llvm tag is created.

**Comment by vgvassilev** [comment]
We should probably have a test for this change.

**Review by dpiparo — APPROVED** [review]
Thanks a lot for this change, very elegant. I approve it but pending the judgement of the compiler experts. 
A doubt: is the test really testing the example provided in https://github.com/root-project/root/issues/13965 ?

**Comment by devajithvs** [comment]
> A doubt: is the test really testing the example provided in #13965 ?

In #13965, the issue was that when we try to call a TF1 constructor with wrong arguments in root, it segfaults. We were trying to use the type information we didn't have, and that was causing the segfault. 

This is similar to calling a function with wrong arguments and is a standalone test case. I can try to use TF1 in the test case too.

**Comment by hahnjo** [comment]
> A doubt: is the test really testing the example provided in #13965 ?

To add to Dev's reply, the crash message for the code provided in that issue changed after the upgrade to LLVM 16. I agree it's the same underlying problem, ie calling a function / constructor with the wrong number of arguments so that the `auto` deduction doesn't work.

**Review by hahnjo — APPROVED** [review]
LGTM; I think a test with mismatched arguments to a constructor (as in https://github.com/root-project/root/issues/13965) is not mandatory, in the end it comes down to the same result of Clang not being able to determine the auto `auto` type.

**Review by vgvassilev — APPROVED** [review]
We should deprecate this feature by issuing a warning if somebody uses it.

**Comment by devajithvs** [comment]
> We should deprecate this feature by issuing a warning if somebody uses it.

Just to clarify, do you mean we should issue a warning saying `Declarations without the 'auto' keyword will be deprecated in the future` or something similar?

I can open a new PR for that, I had a quick chat with @dpiparo and maybe we should discuss this more. ping: @hahnjo

**Comment by vgvassilev** [comment]
> > We should deprecate this feature by issuing a warning if somebody uses it.
> 
> Just to clarify, do you mean we should issue a warning saying `Declarations without the 'auto' keyword will be deprecated in the future` or something similar?

Yes.

> 
> I can open a new PR for that, I had a quick chat with @dpiparo and maybe we should discuss this more. ping: @hahnjo

Sure.

**Comment by hahnjo** [comment]
> > We should deprecate this feature by issuing a warning if somebody uses it.
> 
> Just to clarify, do you mean we should issue a warning saying `Declarations without the 'auto' keyword will be deprecated in the future` or something similar?
> 
> I can open a new PR for that

I would guess you'll probably have to fix a number of instances in roottest... But that's indeed for a future PR.

**Pull request merged**
