### PR TITLE
v7attr: move line/box/marker/text attributes to gpadv7

### PR DESCRIPTION
**Pull request by linev**
Base classes for attributes defined in gpad, but also some classes like
RPad uses line or fill attributes. Later attributes can be extracted
into separate library.

Should resolve circular dependency error, detected only on Windows

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by bellenot** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by bellenot** [comment]
@phsft-bot build on ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, mac1014/cxx17, windows10/default with flags -Droot7=ON

**Comment by linev** [comment]
@bellenot Should I push "dummy" commit? Without new commits Jenkins very often ignore our tries to build ROOT with root7 flags - it just abort building.

**Comment by bellenot** [comment]
@linev you can try, but I think Jenkins has some problems anyway...

**Comment by linev** [comment]
It was build on two platforms (MacOS and fedora27), all other are hanging now.

**Comment by linev** [comment]
@phsft-bot build on windows10/default with flags -Droot7=ON

**Comment by linev** [comment]
@bellenot 
I trying to trigger windows - all other platforms are OK

**Comment by bellenot** [comment]
@linev the Windows nodes are offline...

**Comment by bellenot** [comment]
@linev BTW, `Should resolve circular dependency error, detected only on Windows` is not true, it was detected only on `-ubuntu16/rtcxxmod`

**Comment by linev** [comment]
In this case - just merge it. Logically circular dependency is resolved

**Pull request merged**
