### PR TITLE
[RF] Small fixes to debug printout in RooRealIntegral and RooEffGenContext

### PR DESCRIPTION
**Pull request by elusian**
# This Pull request:
Fixes some small issues with debug printout during integration or generation

## Changes or fixes:
The first commit changes the debug printout in `RooRealIntegral::evaluate`. `_mode` here is the analytical integral code, `_intOperMode` is the variable that can be `Hybrid`, `Analytic` or `PassThrough` (like in the switch-case above).

The second commit adds `printMultiline` to `RooEffGenContext`. This is used when requesting verbose printout during dataset generation, which is supposed to recursively print all gen contexts. Before this change, having a `RooEffProd` inside the model stopped the recursive printout.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by elusian** [comment]
Apologies, I copied the function from another gen context and did not notice that `RooEffGenContext` was already in the 3 spaces convention. Should I fix this?

**Comment by guitargeek** [comment]
Hi, thanks for the PR first of all!

Yes, it would be nice to fix that, I see now that the `RooEffGenContext` header and source almost correctly follow the ROOT clang-format style correctly:
https://github.com/root-project/root/blob/master/.clang-format

(well, the header not really, but it also doesn't have that many lines)

I think your PR is a good opportunity to correctly format them for good! Could you add an initial commit to this PR where you `clang-format` these files first? You can write in the commit message something like "this reformatting is done now because the files will be changed in the following commit, and the differences to the ROOT code style were already minor".

And then, on top of the reformatting commit, you could make the commit with your actual new function (and code format again).

Does that sound good to you?

**Comment by elusian** [comment]
Hello, I can do that. Just to be clear, that applies only to RooEffGenContex.h and cxx, right? Not RooRealIntegral.cxx, which would change a lot with the ROOT format

**Comment by guitargeek** [comment]
Yes, exactly. I'd prefer not to re-format the older more complicated sources, because that makes it harder to understand where things are coming from via `git blame`.

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by guitargeek — APPROVED** [review]
LGTM, thanks a lot for these fixes!

**Pull request merged**
