### PR TITLE
[tmva][sofie] Move parser definition for operators in implementation

### PR DESCRIPTION
**Pull request by lmoneta**
Move definition of free function defining the parser operator functions in the implementation, since these are only for internal use

This should fix some of the issues seen when using PCH

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default, ROOT-ubuntu18.04/nortcxxmod with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default

**Review by Axel-Naumann — APPROVED** [review]
Great thanks!

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default, ROOT-ubuntu18.04/nortcxxmod

**Pull request merged**
