### PR TITLE
Readjust the representation of CallFunc arguments to match the callee signature

### LINKED ISSUE #14405: Arguments of functions passed to TTree::Draw/Scan always take the default values
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Dear experts,
since ROOT 6.30 I have encountered an issue when calling simple functions inside a `TTree::Scan`. For example, if I consider a function whose prototype is 
`int func(int a)`
and call it in a `TTree::Scan`
`t->Scan("func(myBranch)")`

it will always be called with 0 as argument. This happens also when passing a constant argument (`t->Scan("func(2)")`). This issue doesn't appear in root 6.28.

Cheers,
Marino

### Reproducer

To reproduce the bug just call the `test()` function in the following piece of code
```
root[] .L filename.C
root[] test()
```

If this macro is run with root 6.28, the `cout` in `testfunc` will correctly print the values of the branches and `testfunc` column in the Scan will show the correct output of the formula `a+b*c`. When run with ROOT 6.30, the `cout` will print `0 0 0` and the `testfunc` column will always be 0.

```
#include <iostream>
#include <string>
#include <TFile.h>
#include <TTree.h>

using namespace std;

float testfunc(int a, int b, float c)
{
    cout << a << " " << b << " " << c << endl;
    return a + b * c;
}

void createTree(const string &filename)
{
    cout << "Creating tree in file " << filename << endl;
    TFile *f = TFile::Open(filename.c_str(), "RECREATE");
    TTree *t = new TTree("t", "t");
    int a;
    int b;
    float c;
    t->Branch("a", &a, "a/I");
    t->Branch("b", &b, "b/I");
    t->Branch("c", &c, "c/F");
    for (int i = 0; i < 10; ++i)
    {
        a = i;
        b = i + 1;
        c = i + 2;
        t->Fill();
    }
    t->Write();
    f->Close();
    cout << "Tree created" << endl;
}

void runExampleScan(const string &filename)
{
    cout << "Running example scan" << endl;
    TFile *f = TFile::Open(filename.c_str());
    TTree *t = (TTree *)f->Get("t");
    t->Scan("a:b:c:testfunc(a,b,c)", "", "colsize=20");
    delete t;
    delete f;
}

void runExampleDraw(const string &filename)
{
    gROOT->SetBatch();
    TCanvas *c = new TCanvas("c", "c", 800, 600);
    cout << "Running example draw" << endl;
    TFile *f = TFile::Open(filename.c_str());
    TTree *t = (TTree *)f->Get("t");
    t->Draw("testfunc(a,b,c)", "");
    delete t;
    delete f;
    c->SaveAs("test.png");
}

int test()
{
    string filename = "test.root";
    createTree(filename);
    runExampleScan(filename);
    runExampleDraw(filename);
    return 0;
}

```

### ROOT version

```
ROOT v6.30/02
Built for linuxx8664gcc on Dec 20 2023, 18:59:44
From heads/master@tags/v6-30-02
With g++ (GCC) 13.1.0
Binary directory: /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.30.02-fb5be/x86_64-el9-gcc13-opt/bin
```

### Installation method

Pre-built binary

### Operating system

Red Hat Enterprise Linux 9.3 (tested also on Centos7)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vgvassilev**
TClingCallFunc provides an interface between compiled and interpreted code. That is, we can create at compile time a function to be called by the interpreter and get back its result into compiled code. To do that we require connecting to a function declaration available in the interpreter and calling it by setting input arguments. However, the input arguments are set with the SetArg which can resolve to a type and argument representation different from the signature of the interpreter function we will call. This is practically not a problem integral types because their representation is mostly the same. The problem becomes visible when we call SetArg with a `double` and the function signature expects a `float`. That works out of the box when the compiler can see both ends and insert proper representation casts. Unfortunately, when crossing the compiler/interpreter boundary we use `void*` and that information is lost.

This patch adds some representation adjustments so that the compiled code (SetArg) and the interpreted code (CallFunc) can agree on the memory representation before calling.

Fixes #14405

### CODE REVIEW

**Comment by dpiparo** [comment]
Thanks for your work @vgvassilev ! Do you think it's possible to add a high level test of the code to check the original report of Alice is addressed?

**Comment by ktf** [comment]
Thanks! We are testing it in our own tag. Since it applies easily there and we have other changes in any case, no need to speedtrack the backport, if it works.

**Comment by vgvassilev** [comment]
> Thanks for your work @vgvassilev ! Do you think it's possible to add a high level test of the code to check the original report of Alice is addressed?

The test I have is the minimal reproducer from this issue's test.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on windows10/default

**Review by dpiparo — APPROVED** [review]
Thanks @vgvassilev for these nice changes. ALICE confirmed ROOT now works for them. I propose to merge the PR and backport it to 6.30 as soon as @pcanal is also happy.

**Comment by vgvassilev** [comment]
Github decided to close this PR. I've reopened it here: #14888

**Pull request closed without merging**
