### PR TITLE
[ntuple] Remove stub serialization of meta-data envelope

### PR DESCRIPTION
**Pull request by jblomer**
The meta-data envelope will not be part of the v1.0 specification. It will likely come later as a minor format update.

Note that this change breaks forward compatibility.

### CODE REVIEW

**Comment by jblomer** [comment]
> Given that this breaks forward compatibility, should the major version number be bumped?

Actually the minor version (RC), since we are still in epoch 0.

**Comment by hahnjo** [comment]
> Note that this change breaks forward compatibility.

Will we still be able to read "old" rc2 files?

**Comment by jblomer** [comment]
> > Note that this change breaks forward compatibility.
> 
> Will we still be able to read "old" rc2 files?

Yes, also tested e.g. in the ntpl004 tutorial that reads a pre-PR file.

**Review by hahnjo — APPROVED** [review]
LGTM then; I guess the usual robustness principle applies: "be conservative in what you do, be liberal in what you accept from others"

**Pull request merged**
