### PR TITLE
[clang] Fix crash with constexpr destructor

### PR DESCRIPTION
**Pull request by hahnjo**
Fixes https://github.com/root-project/root/issues/13851
See also https://github.com/llvm/llvm-project/issues/68702

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
Amazing, it works!

**Comment by vgvassilev** [comment]
Let’s wait for this to land upstream.

**Comment by hahnjo** [comment]
> Let’s wait for this to land upstream.

Is this a requirement? This is finally fixing test crashes with the most recent GCC and C++20, I'd rather have this in...

**Comment by vgvassilev** [comment]
> > Let’s wait for this to land upstream.
> 
> Is this a requirement? This is finally fixing test crashes with the most recent GCC and C++20, I'd rather have this in...

Do we have a open PR against the llvm mainstream at least?

**Comment by hahnjo** [comment]
> > > Let’s wait for this to land upstream.
> > 
> > 
> > Is this a requirement? This is finally fixing test crashes with the most recent GCC and C++20, I'd rather have this in...
> 
> Do we have a open PR against the llvm mainstream at least?

Yes, https://github.com/llvm/llvm-project/pull/69076, as linked from the LLVM issue

**Comment by vgvassilev** [comment]
Ok, I missed that.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Pull request merged**
