### PR TITLE
[PyROOT] Remove PyROOT legacy code

### PR DESCRIPTION
**Pull request by guitargeek**
The legacy PyROOT was deprecated in 6.30 and will be removed for ROOT 6.32.

### CODE REVIEW

**Review by vepadulano — APPROVED** [review]
Amazing!!! It's just missing a line in the release notes to signal the removal. Feel free to add it in this PR or another

**Comment by vepadulano** [comment]
Is there any sibling PR for roottest to be made?

**Comment by guitargeek** [comment]
> Amazing!!! It's just missing a line in the release notes to signal the removal. Feel free to add it in this PR or another

Thanks for the approval! The release notes got a bit out of sync with the build options at this point, not only because of `pyroot_legacy`. I'll make a separate PR to fix it.

**Comment by guitargeek** [comment]
> Is there any sibling PR for roottest to be made?

Yes, I will also do that, but it was not necessary to do so at the same time. The changes are independent this time.

**Pull request merged**
