### PR TITLE
 Allow to use root as dependency using FetchContent

### LINKED ISSUE #8923: Allow to use root as dependency using `FetchContent`
### Explain what you would like to see improved
Allow to use root as dependency using `FetchContent`

### To Reproduce
```cmake
cmake_minimum_required(VERSION 3.16)

project(Test)

include(FetchContent)

FetchContent_Declare(
  root
  GIT_REPOSITORY https://github.com/root-project/root.git
  GIT_TAG        latest-stable
)

FetchContent_MakeAvailable(root)
```
### Setup
ROOT version :  latest-stable
Operating system : Linux
How you obtained ROOT : github

### PR DESCRIPTION
**Pull request by flagarde**
# This Pull request:

This pull request allows to root as a sub-project using `FetchContent` 

## Changes or fixes:
It's mainly a change of cmake variable CMAKE_SOURCE_DIR to PROJECT_SOURCE_DIR etc..

## Checklist:

- [X ] tested changes locally 
Was compiling both in "standard" and "FetchContent "
- [ X] updated the docs (if necessary) 
- (not needed I think ?)

This PR fixes #8923

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@flagarde apologies for not making progress with this in a reasonable time. Would you be able to address the conflict by rebasing? We will then re-run the tests to see what the CMake error is. It might just be a CMake too old; we have bumped the required CMake version to 3.16 in the meantime, so that might have fixed itself.

**Comment by flagarde** [comment]
@Axel-Naumann no problems. I'm working on it. I was using my branch on a personnal project. It seems to work but some hacking is needed to generate dictionnaries (STAGE1) :

```cmake
  root_generate_dictionary(G__Channel "include/Channel.hpp" LINKDEF "include/ChannelLinkDef.hpp" ${STAGE1})
  add_library(Channel OBJECT "src/Channel.cpp" G__Channel.cxx)
  target_include_directories(Channel PUBLIC "${YAODAQ_INCLUDE}" PUBLIC "include")
  target_link_libraries(Channel PUBLIC ROOT::Core)
  set_target_properties(Channel PROPERTIES PUBLIC_HEADER "include/Channel.hpp")
  #install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libChannel_rdict.pcm TYPE BIN)
  install(TARGETS Channel)
```

More changes are needed on the cmake/modules/RootMacros.cmake for an easier integration.

**Comment by flagarde** [comment]
Sorry for the mess. you can find a cleaner pull request on #9516

**Comment by Axel-Naumann** [comment]
Thanks for this! Closing this in favor of the new version.

**Pull request closed without merging**
