### PR TITLE
Remove duplicate include of subdirectory builtins/glew

### PR DESCRIPTION
**Pull request by gargvaibhav64**
This commit fixes a duplicate include error which occurs on configuring Cmake options.
This happens because the directory is included again in a few lines later.
@vgvassilev 

```
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:538 (add_subdirectory):
  The binary directory

    E:/root-build/builtins/glew

  is already used to build a source directory.  It cannot be used to build
  source directory

    E:/root/builtins/glew

  Specify a unique binary directory name.
```

### CODE REVIEW

**Comment by oshadura** [comment]
Hi @gargvaibhav64, thanks for taking a look! Correct fix could be https://github.com/root-project/root/pull/5526 because we want check both cases with we have opengl, but not glew and just separately enabled builtin_glew.

**Comment by gargvaibhav64** [comment]
@oshadura, I think both cases would get covered with these changes also as [this](https://github.com/root-project/root/blob/3e646ff121d003774df2d884b16db0f05b3f0b53/cmake/modules/SearchInstalledSoftware.cmake#L529) line sets builtin_glew which will later be detected on this [line](https://github.com/root-project/root/blob/726a49d24fe0a67200b064853f5522db9609fb8f/cmake/modules/SearchInstalledSoftware.cmake#L534). 

Anyways, #5526 also fixes the issue. So no worries.

**Comment by oshadura** [comment]
Actually, I think your fix it better because it similiar to all other builtins in cmake. I will test it and merge after!Thank you!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by mrodozov** [comment]
with this change the GL directory in include disappeared and now it fails to find glew.h:
https://github.com/cms-sw/cmsdist/pull/5800
we are using -Dbuiltin_glew=ON which should be enough during install time (I guess)
I can see the end of the config saying 
`-- Enabled support for:  asimage builtin_afterimage builtin_clang builtin_ftgl builtin_gl2ps builtin_glew ...`
and the builtins dir contains this: `davix  glew  lz4  openssl  pcre  xxhash  zlib  zstd`
There is a build log on cmadev25,  in 
`/build/mrodozov/root/build_root/BUILD/slc7_amd64_gcc820/lcg/root/6.21.01-cms/log`
could you help me whats wrong ?

**Comment by pcanal** [comment]
@alja ?

**Pull request merged**
