### PR TITLE
Cling fixes after the LLVM upgrade

### PR DESCRIPTION
**Pull request by vgvassilev**
Patches by @marsupial

### CODE REVIEW

**Comment by marsupial** [comment]
This one too https://github.com/marsupial/cling/commit/21edb1619fdff9e63aec8667ac9c2133bd2c95e1

**Comment by marsupial** [comment]
And one more: https://github.com/marsupial/cling/commit/03d2edd21c3651840200d91df1e1a7fc950fca67

**Comment by vgvassilev** [comment]
@phsft-bot build with CMake flags -Dclingtest=On -Dvc=OFF -Dimt=ON -Dccache=ON

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclingtest=On -Dvc=OFF -Dimt=ON -Dccache=ON

**Pull request merged**
