### PR TITLE
Fix tests RArrowDS tests

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@eguiraud this should solve the issue with the tests.

**Comment by eguiraud** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Darrow=ON

**Comment by eguiraud** [comment]
thanks _a lot_ @ktf !

**Comment by eguiraud** [comment]
build is waiting for the node [here](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/77465/console)

**Pull request merged**
