### PR TITLE
Add lock in TCling::UnloadFile

### PR DESCRIPTION
**Pull request by vepadulano**
It modifies the interpreter state, thus needs locking.

UPDATE:

As suggested by @hahnjo I tried to write a small unit test to see the data race in action. In fact it was pretty easy, and it also highlighted another data race in `TCling::LoadFile`. In the latest commits I take care both of adding the lock to the other method and adding the test.

### CODE REVIEW

**Comment by vepadulano** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by hahnjo** [comment]
Thanks @vepadulano! My only worry is that all threads are loading and unloading the same shared library. Does the problem also happen when the threads are working on their own library?

**Comment by vepadulano** [comment]
> Does the problem also happen when the threads are working on their own library?

Yes indeed. Letting each thread create its own library via `CompileMacro` highlights other types of data races, that I think might be better treated in a separate PR. Just to give an example, these are 2 thread stacktraces in a modified test (see at the bottom)

```
(gdb) t 3
(gdb) bt
#7  0x00007ffff75b7ed0 in ROOT::TReadLockGuard::TReadLockGuard (this=0x7fffcfff7e70, mutex=0x277a800)
    at /home/vpadulan/Programs/rootproject/rootsrc/core/base/inc/TVirtualRWMutex.h:123
#8  0x00007ffff75f4aae in TSystem::FindHelper (this=0x45fa10, 
    path=0x7fffc8034040 "/home/vpadulan/Projects/rootcode/lock-tcling-unloadfile/load_unload_helpers_1_cpp_ACLiC_dict.h", dirptr=0x0)
    at /home/vpadulan/Programs/rootproject/rootsrc/core/base/src/TSystem.cxx:737
#9  0x00007ffff7705827 in TUnixSystem::Unlink (this=0x45fa10, 
    name=0x7fffc8034040 "/home/vpadulan/Projects/rootcode/lock-tcling-unloadfile/load_unload_helpers_1_cpp_ACLiC_dict.h")
    at /home/vpadulan/Programs/rootproject/rootsrc/core/unix/src/TUnixSystem.cxx:1674
#10 0x00007ffff7600b75 in TSystem::CompileMacro (this=0x45fa10, filename=0x7fffc8000ba0 "load_unload_helpers_1.cpp", opt=0x40909c "g", 
    library_specified=0x40909b "", build_dir=0x40909b "", dirmode=0)
```
```
(gdb) t 6
(gdb) bt
#12 0x00007ffff6e88301 in TFile::TFile (this=0x7fffce7f3370, 
    fname1=0x7fffb8003ee0 "/home/vpadulan/Projects/rootcode/lock-tcling-unloadfile/load_unload_helpers_4_cpp_ACLiC_dict_rdict.pcm", 
    option=0x7ffff120efbb "READ", ftitle=0x7ffff1209b59 "", compress=101) at /home/vpadulan/Programs/rootproject/rootsrc/io/io/src/TFile.cxx:380
#13 0x00007fffed25be48 in TCling::LoadPCM (this=0x54c9c0, 
    pcmFileNameFullPath="/home/vpadulan/Projects/rootcode/lock-tcling-unloadfile/load_unload_helpers_4_cpp_ACLiC_dict_rdict.pcm")
    at /home/vpadulan/Programs/rootproject/rootsrc/core/metacling/src/TCling.cxx:1879
#14 0x00007fffed25db4e in TCling::RegisterModule (this=0x54c9c0, modulename=0x7ffff463b5a0 "load_unload_helpers_4_cpp_ACLiC_dict", 
    headers=0x7ffff463d100 <(anonymous namespace)::TriggerDictionaryInitialization_load_unload_helpers_4_cpp_ACLiC_dict_Impl()::headers>, 
    includePaths=0x7ffff463d120 <(anonymous namespace)::TriggerDictionaryInitialization_load_unload_helpers_4_cpp_ACLiC_dict_Impl()::includePaths>, 
    payloadCode=0x7ffff463b498 "\n#line 1 \"load_unload_helpers_4_cpp_ACLiC_dict dictionary payload\"\n\n#ifndef __ACLIC__\n  #define __ACLIC__ 1\n#endif\n\n#define _BACKWARD_BACKWARD_WARNING_H\n// Inline headers\n#include \"load_unload_helpers"..., 
    fwdDeclsCode=0x7ffff463b370 "\n#line 1 \"load_unload_helpers_4_cpp_ACLiC_dict dictionary forward declarations' payload\"\n#pragma clang diagnostic ignored \"-Wkeyword-compat\"\n#pragma clang diagnostic ignored \"-Wignored-attributes\"\n#pr"..., 
    triggerFunc=0x7ffff463a2d7 <(anonymous namespace)::TriggerDictionaryInitialization_load_unload_helpers_4_cpp_ACLiC_dict_Impl()>, 
    fwdDeclsArgToSkip=std::vector of length 0, capacity 0, 
--Type <RET> for more, q to quit, c to continue without paging--
    classesHeaders=0x7ffff463d180 <(anonymous namespace)::TriggerDictionaryInitialization_load_unload_helpers_4_cpp_ACLiC_dict_Impl()::classesHeaders>, lateRegistration=false, hasCxxModule=false) at /home/vpadulan/Programs/rootproject/rootsrc/core/metacling/src/TCling.cxx:2307
#15 0x00007ffff75d53ca in TROOT::RegisterModule (modulename=0x7ffff463b5a0 "load_unload_helpers_4_cpp_ACLiC_dict", 
```

Which might hint to a missing lock in `TCling::LoadPCM`. This is the modified test
```cpp
#include <thread>
#include <vector>
#include <string>
#include <fstream>

#include <TInterpreter.h>
#include <TROOT.h>
#include <TSystem.h>

const static std::string code{R"(
#ifndef ROOT_MY_HELPER_FUN
#define ROOT_MY_HELPER_FUN
bool my_helper_fun(double x, double val)
{
    return x > val;
}
#endif
)"};

void write_helpers(unsigned int n)
{
   for (unsigned int i = 0; i < n; i++)
   {
      std::string library_file{"load_unload_helpers_" + std::to_string(i) + ".cpp"};
      std::ofstream myfile;
      myfile.open(library_file);
      myfile << code;
   }
}

void load_unload(unsigned int n)
{
   std::string library_basename{"load_unload_helpers_" + std::to_string(n)};
   std::string library_file{"load_unload_helpers_" + std::to_string(n) + ".cpp"};
   std::string library_so{"load_unload_helpers_" + std::to_string(n) + "_cpp.so"};

   gSystem->CompileMacro(library_file.c_str(), "g");

   for (int i = 0; i < 10; i++)
   {
      gInterpreter->LoadFile(library_so.c_str());
      gInterpreter->UnloadFile(library_so.c_str());
   }
}

int main()
{
   ROOT::EnableThreadSafety();
   std::vector<std::thread> threads;

   unsigned int n_libraries = 5;
   write_helpers(n_libraries);

   for (unsigned int i = 0; i < n_libraries; i++)
   {
      threads.emplace_back(load_unload, i);
   }

   for (auto &thread : threads)
   {
      thread.join();
   }
}
```

**Comment by vepadulano** [comment]
One addition w.r.t. to the previous comment that may also be relevant. If I try the modified example where each thread calls `CompileMacro` on a separate library without the patch of this PR, I still get this kind of stacktrace
```
#14 0x00007fb2d4d9322f in cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) () from /home/vpadulan/programs/rootproject/rootinstall/add-locks-testing/lib/libCling.so
#15 0x00007fb2d4d7b230 in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /home/vpadulan/programs/rootproject/rootinstall/add-locks-testing/lib/libCling.so
#16 0x00007fb2d4a6d17a in HandleInterpreterException (metaProcessor=0x2929eb0, input_line=0x7fb2b8019840 ".L load_unload_helpers_0_cpp.so", compRes=
0x7fb2bd9f975c: cling::Interpreter::kSuccess, result=0x0) at /home/vpadulan/programs/rootproject/rootsrc/core/metacling/src/TCling.cxx:2436
#17 0x00007fb2d4a814c6 in TCling::LoadFile (this=0x1afbf90, path=0x7fb2b8000bd0 "load_unload_helpers_0_cpp.so") at /home/vpadulan/programs/rootproject/rootsrc/core/metacling/src/TCling.cxx:7432
#18 0x0000000000406686 in load_unload (n=0) at repro_onelibperthread.cpp:41
```

That shows the data race in `TCling::LoadFile`, so that is always present even when each thread works on its library.

**Review by hahnjo — APPROVED** [review]
Ok great, so we have another race in `CompileMacro`... Would it be possible to create the libraries from the main thread only, before starting the "worker" threads?

Just to elaborate: I'm not sure how `LoadFile` and `UnloadFile` are supposed to behave if the same library has already been loaded / unloaded concurrently. But maybe that's just fine and we should go with the current test...

P.S.: Currently all libraries have the same function - is that fine?

**Comment by vepadulano** [comment]
>  Would it be possible to create the libraries from the main thread only, before starting the "worker" threads?
> P.S.: Currently all libraries have the same function - is that fine?

Sure, I added another test that creates one shared library per thread before starting execution. Each shared library contains different code (same function body but the function name is changed). Each thread then `Load`s/`Unload`s its own different library.

**Review by hahnjo — APPROVED** [review]
Perfect, good idea to have both tests!

**Pull request merged**
