### PR TITLE
[TDF+IMT] Fix nested parallelism

### PR DESCRIPTION
**Pull request by bluehood**
This PR includes the commits of
* PR #833 
* a fix (dependent on #833) for task-unsafety in TDataFrame's TColumnValue
* PR #828 
* a patch for task-unsafety in TDataFrame's thread-slot distribution by @dpiparo (commit 2787af2)

If we want to push these commits little by little, PR #833 and PR #828 should be merged first, then I can open a third PR with the second (and fourth?) fix.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @bluehood ,
I'd wait for the master to be green again and then merge. Since the PR is done and #833 and #828 are reviewed and my patch is very simple, I'd go for this "summary PR" and close the afore mentioned ones.

Great that now we can seamlessly handle nested parallelism with ROOT. This is yet another milestone for the efficient usage of extreme architectures such as KNL.
In addition this work allows the upgrade of TTreeProcessorMT with the the "locality patch" of @etejedor.

**Comment by bluehood** [comment]
@dpiparo I have closed the two PRs that are included in this one and added the default labels instead of "do not merge". I will fix the `clang-format` issues and that would make this PR ready for merging on my part (the `roottest_root_multicore_tthrobj_ttreeview_regression_build` failures are expected and are fixed by [PR 63](https://github.com/root-project/roottest/pull/63) in root-project/roottest).

**Comment by bluehood** [comment]
@vgvassilev I think clang-format is having some issues (maybe because of the change in ubuntu distro used by travis?): when I run clang-format locally I definitely do not get as many corrections as highlighted by the bot.

**Comment by vgvassilev** [comment]
@bluehood, that's weird. I think it is because we have broken clang-format file (according to clang-format-3.9 on the bot). I am thinking to follow up renaming of one of the configs from 'SplitEmptyFunctionBody' to 'SplitEmptyFunction'. Could you locally do it and let me know if your clang-format would be happy with the shorthand 'SplitEmptyFunction'?

**Comment by bluehood** [comment]
Hi @vgvassilev ,
clang 4.0 (compiled on my machine a few months ago) is not happy with `SplitEmptyFunction` (does not know the keyword).

**Pull request merged**
