### PR TITLE
[cmake] Update builtin tbb to 2021.9.0.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Factor out the URL - it's unconventional to have two URLs, and it's reasonable to just update the version number as part of the URL.

Remove patches.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on windows10/cxx14

**Review by bellenot — APPROVED** [review]
LGTM. Thanks Axel!

**Comment by Axel-Naumann** [comment]
Once merged I will verify perf numbers with grafana.

**Comment by hahnjo** [comment]
just for my curiosity: Why the separate revert of `gcc13.patch`? Both existing patches are removed, which is the normal expectation for version updates...

**Comment by Axel-Naumann** [comment]
>Why the separate revert 
Because I had it at hand and the revert applied cleanly. No underlying reason. (Sorry, I didn't mean to offend by reverting.)

**Pull request merged**
