### PR TITLE
[cxxmodules] Exclude tree-temperature test from runtime_cxxmodules

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Note that this is failing in master as well, @couet is notified.

**Comment by yamaguchi1024** [comment]
I think `veto` is used when you want to exclude tutorials

**Comment by vgvassilev** [comment]
Looks like the failure is not modules-related. Shall we close that PR?

**Pull request closed without merging**
