### PR TITLE
RBatchGenerator: Added support for multiple target columns

### PR DESCRIPTION
**Pull request by DanteNiewenhuis**
RBatchGenerator now supports multiple target columns. The target should be given as a list of strings and the data will be returned in the same order. The user can still provide a string when using a single target

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
Hi @DanteNiewenhuis and @lmoneta, what is the status of this PR?

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
Thank you! This was added as part of #16650

**Pull request closed without merging**
