### PR TITLE
[cxxmodules] Rework the loading of the modulemap in the working dir.

### PR DESCRIPTION
**Pull request by vgvassilev**
This patch actually loads the modulemap as previously it wrongly detected
it was already loaded.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build just on ROOT-ubuntu16/rtcxxmod with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@pcanal, it looks like projectroot.roottest.cling.typedef_global.roottest_cling_typedef_global_scopeTest* failures actually bring the old behavior as described in https://github.com/root-project/roottest/blob/master/cling/typedef_global/output.ref-5. How do make this check conditional for modules vs non-modules?

**Comment by vgvassilev** [comment]
@phsft-bot build just on ROOT-ubuntu16/rtcxxmod with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build on ROOT-performance-centos7-multicore/default, ROOT-fedora27/noimt, ROOT-fedora29/python3, ROOT-ubuntu16/rtcxxmod, ROOT-ubuntu18.04-i386/cxx14, mac1014/cxx17, windows10/default with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build on mac1014/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
