### PR TITLE
[skip-ci] [io] Collapse data format details of TFile class

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:

Supersedes https://github.com/root-project/root/pull/9616

## Checklist:

- [ ] tested changes locally
- [x] updated the docs (if necessary)

### CODE REVIEW

**Comment by vepadulano** [comment]
I believe the changes go in the right direction as discussed in the related PR, thanks a lot @ferdymercury ! Probably we need an explicit approval by @couet that the <details> tag is doing what we expect

**Comment by couet** [comment]
Hi @vepadulano , I just built the corresponding documentation of this new TFile version.  It uses the tag `<details>` which is not used in ROOT except in a few places in `interpreter/llvm-project/clang/www/`. This tag allows to hide a part of the doc and make it visible only when clicking on the text given in `<summary>`. The other new bits are the two `\sa` which seem fine too.

**Review by vepadulano — APPROVED** [review]
Thank you @couet for checking and @ferdymercury for the contribution! I believe this looks good

**Comment by ferdymercury** [comment]
@pcanal how do you like it ?

**Review by pcanal — APPROVED** [review]

**Comment by ferdymercury** [comment]
@couet can you merge? Thanks!

**Comment by ferdymercury** [comment]
@couet It seems the root-makedoc-master bot is dead, as these changes are not yet visible in the Web? Or does it only rebuild weekly? thanks!

**Comment by couet** [comment]
@ferdymercury looking at it

**Comment by couet** [comment]
relaunched

**Pull request merged**
