### PR TITLE
Move old release notes into README/ReleaseNotes/

### PR DESCRIPTION
**Pull request by amadio**
I think these files are fine to remove, but maybe even removing only the ROOT 5 ones would be already enough (they can be recovered from the older version tarballs in any case).

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Why should we remove old release notes?

**Comment by amadio** [comment]
Well, I just wanted to start a discussion. Many of those files are empty or only have a single line header. I don't think there's much value in them. Also, the old versions themselves will still contain those files. In any case, if not to remove, it might make sense to at least move these directories all under `README/ReleaseNotes/old/`. I am looking to remove old/deprecated stuff and `git grep` always gets cluttered with stuff from those files, making it more time consuming to find the real code that needs to be removed.

**Comment by amadio** [comment]
@couet Ok, I will move them all into `README/ReleaseNotes/old` then. At least I will be able to add `grep -v README` when working on removing other deprecated/obsolete stuff.

**Comment by amadio** [comment]
@Axel-Naumann @couet Turned the removals into moving into `README/ReleaseNotes/*`. Please let me know if any of the paths is not good.

**Comment by amadio** [comment]
I need to adjust minuit, as apparently the docs are used by the standalone build.

**Comment by amadio** [comment]
Alright, should be ok now. I moved `math/minuit2/doc` back in place for the standalone build to work.

**Comment by amadio** [comment]
I need to redo the moves, I will take comments into consideration and start a new pull request some other time. For now, I'm closing this.

**Pull request closed without merging**
