### PR TITLE
[gradients] Re-enable test.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@bellenot could you help us with the Win regex of that test. I do not understand why it fails, the output across platforms should be the same...

**Comment by bellenot** [comment]
> @bellenot could you help us with the Win regex of that test. I do not understand why it fails, the output across platforms should be the same...

No idea, I don't even understand the error message... But I'll check on my own llvm 9.0 build and let you knoe

**Comment by vgvassilev** [comment]
That's not related to the llvm9 upgrade. Here we want to print, and compare against the expected, the generated gradient function.

**Comment by bellenot** [comment]
> That's not related to the llvm9 upgrade. Here we want to print, and compare against the expected, the generated gradient function.

Oh, OK, sorry I overlooked the PR. I'll take a look beginning of next year (ping me if I forget)

**Review by lmoneta — APPROVED** [review]

**Pull request merged**
