### PR TITLE
Fix for ROOT-10123

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Comment by amadio** [comment]
> That seems strange. RForest has no headers?

It does, but they are all in `v7/inc`. Now they moved the `LinkDef.h` file into `inc/`, which works around the issue, but we still need to fix this. I think it should be possible to have headers in `include/` rather than `inc/`, or just in `v7/inc/`, like it was the case for `RForest`.

**Comment by Axel-Naumann** [comment]
> have headers in include/ rather than inc/

I don't understand the rationale for `include/`. For `inc/` the rationale is "that's where ROOT has its headers". But what if my package has them in `myPackage/`?

And given that, why would `ROOT_STANDARD_PACKAGE` then be the right function to use? Shouldn't that be tailored just for ROOT, and work only for ROOT, and if it doesn't work for "my package" then people should use the function that generates dictionary and use plain CMake for the rest?

**Comment by amadio** [comment]
> I don't understand the rationale for include/

That's for external users calling `ROOT_GENERATE_DICTIONARY()`, for example, or `ROOT_INSTALL_HEADERS()`, or something that calls one of these two.

**Comment by Axel-Naumann** [comment]
I don't see how your reply addresses my concerns.

**Comment by amadio** [comment]
https://github.com/search?q=ROOT_STANDARD_LIBRARY_PACKAGE&type=Code

**Comment by Axel-Naumann** [comment]
...most of which is ROOT itself.

OK, so even if we assume that this macro is used by users, why would we want to also search `include/` if we didn't do it before? Why not leave it untouched if it works for ROOT - and seemingly also for those users that decided to use it?

**Comment by amadio** [comment]
> ...most of which is ROOT itself.

most ≠ all. If you click through the next pages, you'll see many examples that are not in ROOT itself.

> even if we assume that this macro is used by users, why would we want to also search include/ if we didn't do it before?

We do not assume, it *is* used by our users. I didn't change it to search in `include/`, just to not add `inc/` and `v7/inc` if they don't exist. However, if headers are only in `include/`, checking for headers only in `inc/` and `v7/inc/` will come up empty, therefore we cannot check that the list is not empty. That's why I removed the check in the other commit. It fails even in ROOT without that, because `ROOT_GENERATE_DICTIONARY()` is called from `core/CMakeLists.txt` and neither `core/inc/` nor `core/v7/inc/` exist.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
Asking to build again, since Jenkins was down during last build and got stuck

**Comment by amadio** [comment]
Errors are about `std::auto_ptr`, so not a problem of this PR. Please merge when you are ready.

Note that after this, we are testing creation of the tarballs:
https://epsft-jenkins.cern.ch/job/root-pullrequests-build/59420/testReport/(root)/projectroot/package/
https://epsft-jenkins.cern.ch/job/root-pullrequests-build/59419/testReport/(root)/projectroot/package/

**Comment by amadio** [comment]
@phsft-bot build

**Pull request merged**
