### PR TITLE
TDataSource upgrade

### PR DESCRIPTION
**Pull request by bluehood**
It is sometimes not possible for a TDataSource to know the full range of entries upfront. To cope with these cases, we need TDataSource to somehow communicate to TDataFrame when it can finish looping -- dynamically, as we go, we are done when we are done.

The solution proposed in this PR is that TDataFrame will call `TDataSource::GetEntryRanges` repeatedly instead of just once: after processing a batch of entry ranges, TDF will ask for another one, then another one, until the TDataSource replies with an empty vector, which signals the end of the event-loop.

The current TDataSources required small modification to make sure that the second time `GetEntryRanges` is invoked it returns an empty vector.

Furthermore, as TDataFrame might use the same TDataSource for multiple event-loops, the TDataSource must setup `fEntryRanges` at the beginning of each event-loop. This is the rationale for the introduction of the `TDataSource::Init` and `TDataSource::Finalise` methods, that can optionally be implemented by the concrete data-source classes to deal with per-event-loop initialization and clean-up operations.
I think the addition of `Init` might be a good thing overall because currently we high-jack `SetNSlots` to perform initialization operations -- `Init` seems like a more proper place. `Finalise` is introduced for symmetry.

### CODE REVIEW

**Comment by dpiparo** [comment]
great development. It will be necessary at some point and also useful for a csv ds 2.0 which does not cache in memory the entire file.
I would go to Initialise instead of Init to be coherent with Finalise and other popular frameworks such as Gaudi.

**Comment by bluehood** [comment]
Sorry for the mail spam, it took me a while to get the docs right :)

**Comment by etejedor** [comment]
Hi Enrico, great work! I understand it will be up to the DS to decide on the size of the portion of the source file that it reads each time and stores in memory? And then the partial ranges will be computed with that portion size plus the number of slots.

We could even make the portion size configurable by the user (to control the memory usage of the DS), which at the same time allows to control the granularity of the computations. My only doubt is: if we allow to read a source little by little, does this mean that after each of these reads (and the corresponding processing of the read entries) there will be a synchronization barrier, after which the next portion will be read and the tasks for that portion will be spawned?

**Comment by bluehood** [comment]
Hi @etejedor,
> will be up to the DS to decide on the size of the portion of the source file that it reads each time and stores in memory?

TDataFrame is completely agnostic regarding file reading, entry chunking etc. The only thing TDF sees are the batches of entry ranges that `TDataSource::GetEntryRanges` returns -- one task is spawned for each of the range. So basically every decision in this regard is in the hands of `TDataSource`.

> does this mean that after each of these reads there will be a synchronization barrier?

Yes. I didn't feel like implementing a one-producer-many-consumers thread-safe queue 😅 but it can always be done later if we want/need it.

**Pull request merged**
