### PR TITLE
[RF] Enable again the RooJSONFactoryWSTool Python tests on Mac

### PR DESCRIPTION
**Pull request by guitargeek**
More details in the commit descriptions.

### CODE REVIEW

**Comment by pcanal** [comment]
@guitargeek Do we know why `Add const to std::map key types` would actually `fixes the occasional crashes`?  I.e. do we know it is not "just" moving things around and making it rare enough that it is not noticed?

**Review by lmoneta — APPROVED** [review]
Thank you Jonas for this fix!

**Comment by guitargeek** [comment]
Hi @pcanal, I don't understand what you mean by "moving things around here". The way I tested it was to run a Python script with just `ROOT.RooJSONFactoryWSTool.pdfImportExpressions()` many times on `macphsft23` (with macos 11).

Before adding the `const`, the script crashed on average about 1 in 5 times. Afterwards, it never did.

**Comment by pcanal** [comment]
If we don't understand "why" it crashes, the cause could be  a memory error (reading deleted memory, reading past the end of array, reading uninitialized memory; because of llvm block alloc, valgrind often can't see those).  Changing the text compiled could result in change in the size of the array, in the order of the allocations and deallocations, etc. that result in the error becoming rare (1 out 1000 instead of 1 out 5).  

And essentially I am asking if you "arbitrarily" tried to add the const and observed an improvement or if you knew that the lack of const lead llvm/clang to take a code path with a (known?) deficiency or unsupported features or some other problems.

**Comment by guitargeek** [comment]
Ah I see what you mean now, thanks for clarifying!

No, I didn't have any idea how the lack of `const` could have been a problem. I just added it in an act of desperation, hoping that I would somehow get up in a code path that is not broken.

So you think there is still a small chance that it crashes then? Then I'll quickly make another study to give you the exact number of crashes out of 1000 trials or so.

**Comment by guitargeek** [comment]
So before this PR, it's hard to tell how often you get the crash because even if I call the python interpreter in a loop, the crash stops everything...

Here is how I try it:
```Python
import subprocess

cmd = ["python", "-c", "import ROOT; ROOT.RooJSONFactoryWSTool.pdfImportExpressions()"]

n_iterations = 1000

for i in range(n_iterations):
   print(i)
   out = subprocess.check_output(cmd).strip().decode("utf-8")

   print(out)
```

With this PR (in fact **just** with the `const std::string` change), the 1000 iterations are finished without any crash.

Of course I can't exclude that the crashes are even rarer, it's like searching for new physics here, haha! But are you okay with merging the PR @pcanal?

**Comment by pcanal** [comment]
I am indeed fine with merging this.  I would ask that you consider open an issue essentially stating "reverting this PR should not lead to a crash but it does and we don't know why" :)   Thanks.

**Comment by guitargeek** [comment]
Ok, alright! I will open an issue then, and also backport this PR to the 6.26 branch.

**Comment by guitargeek** [comment]
There you go, the issue is open: https://github.com/root-project/root/issues/9847

**Pull request merged**
