### PR TITLE
ROOT-9071

### PR DESCRIPTION
**Pull request by peremato**
Simplification of building builtin LZ4 and fixing ROOT-9071

### CODE REVIEW

**Comment by peremato** [comment]
@phsft-bot build

**Comment by peremato** [comment]
@phsft-bot build just on windows10/vc15

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/vc15

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by bellenot** [comment]
@phsft-bot build just on windows10/vc15

**Comment by peremato** [comment]
Could not test on windows/vc15. It does not work in the pullrequest yet. Watching the incrementals...

**Pull request merged**
