### PR TITLE
[ci] Add test summary to pull requests

### PR DESCRIPTION
**Pull request by olemorud**
# This Pull request:
- (https://github.com/root-project/root/issues/12186) Adds test summaries to builds. Writes comments on pull-requests: [example](https://github.com/olemorud/root/pull/9)
- Adds the `--rm` flag to containers as a temporary fix for the disk space problem (puppet fix coming soon)

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

[skip-ci]

### CODE REVIEW

**Comment by vgvassilev** [comment]
Awesome! Can we also add `codecov` to measure given PR test coverage? You can take a look at https://github.com/vgvassilev/clad/blob/57345cfae9fd3c1ad2fc1f5a4e2e95e0ee4a68ac/.github/workflows/ci.yml#L737-L741

**Comment by Axel-Naumann** [comment]
> Awesome! Can we also add codecov to measure given PR test coverage? You can take a look at [vgvassilev/clad@57345cf/.github/workflows/ci.yml#L737-L741](https://github.com/vgvassilev/clad/blob/57345cfae9fd3c1ad2fc1f5a4e2e95e0ee4a68ac/.github/workflows/ci.yml#L737-L741)

Certainly (I think we have an issue up for this, please check, @vgvassilev or open one). Codecov shouldn't be part of this PR though :-)

**Comment by vgvassilev** [comment]
> > Awesome! Can we also add codecov to measure given PR test coverage? You can take a look at [vgvassilev/clad@57345cf/.github/workflows/ci.yml#L737-L741](https://github.com/vgvassilev/clad/blob/57345cfae9fd3c1ad2fc1f5a4e2e95e0ee4a68ac/.github/workflows/ci.yml#L737-L741)
> 
> Certainly (I think we have an issue up for this, please check, @vgvassilev or open one). Codecov shouldn't be part of this PR though :-)

I did not intend to ask about it in the context of this PR. It was more towards being a very similar feature that's easy to reach.

**Review by Axel-Naumann — APPROVED** [review]
Sweet!

**Pull request merged**
