### PR TITLE
[RCanvas] new way to produce images in batch mode

### PR DESCRIPTION
**Pull request by linev**
Use headless Chrome browser, running from file system.
No any HTTP server required.
Following formats are supported: png, pdf, svg, jpeg, webp
Requires that chrome is installed on all test machines
Tested on Linux, Mac and Windows
Exactly same code used with TWebCanvas

### CODE REVIEW

**Comment by linev** [comment]
Exactly same routine can be applied for TWebCanvas, but this requires small modifications in TCanvasImp interface

**Comment by Axel-Naumann** [comment]
>  Requires that chrome is installed on all test machines

I don't want to *require* Chrome for ROOT, so the test (and ROOT) must survive also without. Would that be possible? Or is it already the case and I just misread your statement?

**Comment by linev** [comment]
> I don't want to require Chrome for ROOT, so the test (and ROOT) must survive also without. Would that be possible? Or is it already the case and I just misread your statement?

Without chrome browser any kind of batch root7 graphics generation will fail

**Comment by linev** [comment]
I just checked - also Mac version works as designed

**Pull request merged**
