### PR TITLE
[PyROOT exp] Enable string_view backport

### PR DESCRIPTION
**Pull request by stwunsch**
Enable `std::string_view` backport in experimental PyROOT.

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build with `-Dpyroot_experimental=ON`

**Comment by stwunsch** [comment]
@amadio Could you have a look whether the cmake changes make sense?

**Comment by etejedor** [comment]
Issue on JIRA:
https://sft.its.cern.ch/jira/browse/ROOT-9954

**Comment by etejedor** [comment]
I think we can go for the PR to Cppyy and see what is the opinion of Wim on this issue. The tricky point is the dependency we introduce between CPyCppyy and ROOT, although only if a macro is defined.

**Comment by stwunsch** [comment]
[Here](https://bitbucket.org/wlav/cpycppyy/pull-requests/15) is the PR to CPyCppyy.

**Comment by stwunsch** [comment]
@etejedor I've removed the preproc variable and put in a patch file. Should we put it in like this?

**Comment by etejedor** [comment]
Let's try to find some time to look at it together with @amadio

**Comment by amadio** [comment]
Why add a patch file? We can easily check what changes have been made to Cppyy with git.
Removing the preprocessor macro will probably not please Wim, since that turns an optional into a hard dependency on ROOT. Other than that, the changes look OK.

**Pull request merged**
