### PR TITLE
[TMVA] Add operations needed for performing optimizer updates:

### PR DESCRIPTION
**Pull request by ravikiran0606**
* Implement ConstAdd, ConstMult, ReciprocalElementWise, SquareElementWise, SqrtElementWise in CPU, GPU and Reference architectures.

* Add Unit Tests for them in CPU, GPU architecture.

* Add ROOT Style docs and clang format the code.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Please rebase onto master (rewriting this branch's history) instead of creating merge commits.

**Comment by ravikiran0606** [comment]
@Axel-Naumann   Yeah I was trying to do that! I'll rebase into master and update this PR.

**Comment by ravikiran0606** [comment]
I have rebased into master and updated the PR. @lmoneta  @stwunsch  Can you please review this?

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
Looking carefully at the code, I see that we need to have a GPU implementations for these functions.
As a first attempt we could try by doing in term of TMatrixT  using the conversions TCudaMatrix -> Matrix functions and then we check if it is really needed to have something specific for GPU's

**Comment by lmoneta** [comment]
@phsft-bot build!

**Comment by ravikiran0606** [comment]
@lmoneta @stwunsch  I ll add the GPU implementation for those Operations soon and update this PR. We can merge then !

**Comment by ravikiran0606** [comment]
@stwunsch @lmoneta  I added the GPU implementation for those operations and both the CPU and GPU tests are passing. Can you review and trigger the build?

**Comment by stwunsch** [comment]
@phsft-bot build

**Pull request merged**
