### PR TITLE
 Allow to populate ROOT at configure time using FetchContent (part1)

### LINKED ISSUE #8923: Allow to use root as dependency using `FetchContent`
### Explain what you would like to see improved
Allow to use root as dependency using `FetchContent`

### To Reproduce
```cmake
cmake_minimum_required(VERSION 3.16)

project(Test)

include(FetchContent)

FetchContent_Declare(
  root
  GIT_REPOSITORY https://github.com/root-project/root.git
  GIT_TAG        latest-stable
)

FetchContent_MakeAvailable(root)
```
### Setup
ROOT version :  latest-stable
Operating system : Linux
How you obtained ROOT : github

### PR DESCRIPTION
**Pull request by flagarde**
# This Pull request:

This pull request allows to root as a sub-project using `FetchContent`.
It a cleaner Pull request than (#8941)

## Changes or fixes:
It's mainly a change of cmake variable CMAKE_SOURCE_DIR to PROJECT_SOURCE_DIR etc..

## Checklist:

- [X ] tested changes locally 
Was compiling both in "standard" and "FetchContent "
- [ X] updated the docs (if necessary) 
- (not needed I think ?)

This PR fixes #8923

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by flagarde** [comment]
Hope the test will pass for now

**Comment by Axel-Naumann** [comment]
I think that's a good PR to follow up on, @bellenot what do you think? Shall we reopen and bring it to mergable state?

**Comment by bellenot** [comment]
> I think that's a good PR to follow up on, @bellenot what do you think? Shall we reopen and bring it to mergable state?

Well, that would be an idea, but the repo has already been deleted (i.e. I cannot re-open this PR)

**Comment by flagarde** [comment]
Yes, I did some cleaning on my repos. I didn't know this would close the PR. If still interested I could give a eye again on it and resubmit a PR

**Comment by bellenot** [comment]
@flagarde yes, please

**Pull request closed without merging**
