### PR TITLE
[core] Clean code command in rule parsing

### PR DESCRIPTION
**Pull request by vepadulano**
To avoid having to use regex to parse trailing curly brackets with/without trailing whitespaces, the code command string is cleaned with the following strategy:
- Trim whitespaces at the borders
- Get the inner command (i.e. the part between quotes)
- Trim whitespaces again
- Stitch back together

This should fix the unforeseen PyTorch failures brought by PyTorch's snafu (as described and https://github.com/pytorch/pytorch/issues/49460#issuecomment-911365091) and triggered by the use of std::regex introduced in https://github.com/root-project/root/pull/14716 

This replaces https://github.com/root-project/root/pull/14716 to fix https://github.com/root-project/root/issues/14462

### CODE REVIEW

**Review by pcanal — CHANGES_REQUESTED** [review]
The change looks good.  However we should add a test for this probably in `roottest`

**Comment by vepadulano** [comment]
Test at https://github.com/root-project/roottest/pull/1066

**Review by pcanal — APPROVED** [review]
LGTM. Thanks,

**Comment by hahnjo** [comment]
This appears to have broken Windows builds, as signaled by both Jenkins and the new CI... Unfortunately I cannot see a real error message. FYI @bellenot

**Pull request merged**
