### PR TITLE
cling PR 284

### PR DESCRIPTION
**Pull request by Axel-Naumann**
See https://github.com/root-project/cling/pull/284

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@SimeonEhrig you said (in https://github.com/root-project/cling/pull/284#issuecomment-545871201 )

> I have removed the part of the code that requires changes to the clang base.

Yet the errors above seem to come from a missing llvm patch. Could you clarify?

**Comment by SimeonEhrig** [comment]
> @SimeonEhrig you said (in [root-project/cling#284 (comment)](https://github.com/root-project/cling/pull/284#issuecomment-545871201) )
> 
> > I have removed the part of the code that requires changes to the clang base.
> 
> Yet the errors above seem to come from a missing llvm patch. Could you clarify?

I've removed any part that requires changes to the Clang base. The error occurs because the nvptx is not enabled. I'm not familiar with the root build process, so I need a little time to check it.

**Comment by SimeonEhrig** [comment]
I see there is a mistake at the PR. The commit fe126794f5e5cd5f1cd9d55f9a419b9d10a292f9 is no longer needed.

**Comment by SimeonEhrig** [comment]
I have developed a solution to enable the NVPTX backend in Root by default. I have also implemented a check in the CMakeLists.txt of Cling that throw an error if the NVPTX backend is not enabled. Unfortunately, I don't know how to push commits to this PR, so I forked your repo and modified the PR-284 branch: https://github.com/SimeonEhrig/root/tree/PR-284

**Attention:** I have removed the last commit of your branch.

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Superseded by #4618

**Pull request closed without merging**
