### PR TITLE
[core] Remove some `mm*.c` in core/clib

### PR DESCRIPTION
**Pull request by guitargeek**
These files are unused and can be removed.

This should fix this warning in the ROOT nightlies on the mac13 node:

```
core/clib/src/mmtrace.c:32:14: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
extern char *getenv ();
```

https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=mac13,SPEC=cxx20,V=master/lastBuild/parsed_console/

### CODE REVIEW

**Comment by hahnjo** [comment]
Why not just remove? (FYI the previous treatment of this code was in commit 0cd36a959859ab55c78a4a03dbf9a85ee3623622)

**Comment by guitargeek** [comment]
You're right, everything in this file is commented out anyway

**Comment by hahnjo** [comment]
Ok, not exactly what I had in mind :sweat_smile: I only meant to suggest to just remove the declaration. The file still defines `mmtrace`, even if empty. I guess Axel or Philippe need to comment what the `core/clib` is still used for...

**Comment by guitargeek** [comment]
Haha! Well okay, maybe @Axel-Naumann can comment if this file is still needed before I change the PR again :)

**Comment by Axel-Naumann** [comment]
We only need very few functions for `TMapFile`. In principle, reducing the `clib/*/mm*` sources to just that should do.

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
Those looks indeed unused.  There is likely more than could be removed.

**Comment by guitargeek** [comment]
Thanks Phillipe! As Axel suggested, I have also removed the other `mm*.c` files that are not used inside the ROOT internals.

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
The error is unrelated (resource contention on Windows).

**Comment by pcanal** [comment]
Thanks.

**Pull request merged**
