### PR TITLE
Changing default compression algorithm for 6-14-patches to zlib

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by pcanal** [comment]
Is there a corresponding PR for roottest?

**Comment by oshadura** [comment]
@pcanal working on it! I will assign to you as soon it  will be ready (I put label don't review yet ;D)

**Comment by amadio** [comment]
@Axel-Naumann @pcanal I believe that there are too many places that need to be changed when changing the default compression. We should have a single source of truth for the default, and use its value everywhere else. So, instead of using `1` and `4` directly, it would be much better to use `ROOT::DefaultCompressionAlgorithm` or something similar to that. One good reason for this is that it's really hard to find which `4`s mean `LZ4` and which are just a regular `4`. It also seems that `R__HAS_DEFAULT_LZMA` isn't used anywhere, so it would be quite hard to set the default to that at the moment. Finally, when a user sets the default on his/her config file to something else, it will not affect any of these places where `1` and `4` are used directly in ROOT. That's made even worse by the fact that setting `-Dcompression_default=lzma` at CMake configuration time will not change any of these as well, which will definitely make users very confused.

**Comment by pcanal** [comment]
@amadio I completely agree with your statements.  This type of update is planned but was not yet made.  So better or worse, given the lack of time before the release, the easiest way to go back to zlib as the default is doing commit revert.

**Pull request merged**
