### PR TITLE
[DF] Run test in IMT mode too

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by ikabadzhov** [comment]
On some other place IMT could be used as well:

```diff
diff --git a/tree/dataframe/test/dataframe_vary.cxx b/tree/dataframe/test/dataframe_vary.cxx
index 92ac2c8c67..12451030af 100644
--- a/tree/dataframe/test/dataframe_vary.cxx
+++ b/tree/dataframe/test/dataframe_vary.cxx
@@ -31,7 +31,7 @@ auto SimpleVariation()
    return ROOT::RVecI{-1, 2};
 }
 
-TEST(RDFVary, RequireExistingColumn)
+TEST_P(RDFVary, RequireExistingColumn)
 {
    ROOT::RDataFrame df(10);
    EXPECT_THROW(
@@ -45,7 +45,7 @@ TEST(RDFVary, RequireExistingColumn)
       std::runtime_error);
 }
 
-TEST(RDFVary, VaryTwiceTheSameColumn)
+TEST_P(RDFVary, VaryTwiceTheSameColumn)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1; });
    EXPECT_THROW(
@@ -75,7 +75,7 @@ TEST(RDFVary, VaryTwiceTheSameColumn)
       std::logic_error);
 }
 
-TEST(RDFVary, RequireVariationsHaveConsistentType)
+TEST_P(RDFVary, RequireVariationsHaveConsistentType)
 {
    auto df1 = ROOT::RDataFrame(10).Define("x", [] { return 1.f; });
    // x is float, variation expression cannot return RVec<int>, must be RVec<float>
@@ -125,7 +125,7 @@ TEST(RDFVary, RequireVariationsHaveConsistentType)
 // throwing exceptions from jitted code cause problems on windows and MacOS+M1
 #if !defined(_MSC_VER) || defined(R__ENABLE_BROKEN_WIN_TESTS)
 #if !(defined(R__MACOSX) && defined(__arm64__))
-TEST(RDFVary, RequireVariationsHaveConsistentTypeJitted)
+TEST_P(RDFVary, RequireVariationsHaveConsistentTypeJitted)
 {
    // non-jitted Define, jitted Vary with incompatible type
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1.f; });
@@ -196,7 +196,7 @@ TEST(RDFVary, RequireVariationsHaveConsistentTypeJitted)
 #endif
 #endif
 
-TEST(RDFVary, RequireReturnTypeIsRVec)
+TEST_P(RDFVary, RequireReturnTypeIsRVec)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1; });
    EXPECT_THROW(
@@ -209,7 +209,7 @@ TEST(RDFVary, RequireReturnTypeIsRVec)
       std::runtime_error);
 }
 
-TEST(RDFVary, RequireNVariationsIsConsistent)
+TEST_P(RDFVary, RequireNVariationsIsConsistent)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1; });
    auto s = df.Vary("x", SimpleVariation, {}, /*wrong=*/3).Sum<int>("x");
@@ -231,10 +231,14 @@ TEST(RDFVary, RequireNVariationsIsConsistent)
       std::runtime_error);
 
    std::cerr.rdbuf(oldCerrStreamBuf);
-   EXPECT_EQ(strCerr.str(), "RDataFrame::Run: event loop was interrupted\n");
+   std::string msg;
+   const auto nRepetitions = GetParam() ? std::min(4u, std::thread::hardware_concurrency()) : 1u;
+   for (auto i = 0u; i < nRepetitions; ++i)
+      msg += "RDataFrame::Run: event loop was interrupted\n";
+   EXPECT_EQ(strCerr.str(), msg);
 }
 
-TEST(RDFVary, VariationsForDoesNotTriggerRun)
+TEST_P(RDFVary, VariationsForDoesNotTriggerRun)
 {
    ROOT::RDataFrame df(10);
    auto h = df.Define("x", [] { return 1; }).Histo1D<int>("x");
@@ -242,7 +246,7 @@ TEST(RDFVary, VariationsForDoesNotTriggerRun)
    EXPECT_EQ(df.GetNRuns(), 0);
 }
 
-TEST(RDFVary, VariationsForWithNoVariations)
+TEST_P(RDFVary, VariationsForWithNoVariations)
 {
    ROOT::RDataFrame df(10);
    auto h = df.Define("x", [] { return 1; }).Histo1D<int>("x");
@@ -250,7 +254,7 @@ TEST(RDFVary, VariationsForWithNoVariations)
    EXPECT_EQ(hs.GetKeys(), std::vector<std::string>{"nominal"});
 }
 
-TEST(RDFVary, GetVariations)
+TEST_P(RDFVary, GetVariations)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 0; }).Define("y", [] { return 10; });
    auto df2 = df.Vary("x", SimpleVariation, {}, 2)
@@ -269,7 +273,7 @@ TEST(RDFVary, GetVariations)
                   "Variations {x:0, x:1} affect column x\nVariations {xy:0, xy:1} affect columns {x, y}\n");
 }
 
-TEST(RDataFrameInterface, VaryFriend)
+TEST(RDFVary, VaryFriend)
 {
    int x = 0;
    TTree main("main", "main");
@@ -295,7 +299,7 @@ TEST(RDataFrameInterface, VaryFriend)
    EXPECT_EQ(sum2vars["var:0"], 43);
 }
 
-TEST(RDFVary, ResultMapIteration)
+TEST_P(RDFVary, ResultMapIteration)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 0; }).Vary("x", SimpleVariation, {}, 2);
    auto s = df.Sum<int>("x");
@@ -327,7 +331,7 @@ TEST_P(RDFVary, VaryDefinePerSample)
    EXPECT_EQ(ss["x:1"], 2 * 10);
 }
 
-TEST(RDFVary, SaveGraph)
+TEST_P(RDFVary, SaveGraph)
 {
    ROOT::RDataFrame df(1);
    auto c = df.Define("x", [] { return 0; })
@@ -622,7 +626,7 @@ TEST_P(RDFVary, DefineDependingOnVariations)
    EXPECT_EQ(sums["yshift:low"], 410);
 }
 
-TEST(RDFVary, VaryAndAlias)
+TEST_P(RDFVary, VaryAndAlias)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1; }).Alias("y", "x").Vary("x", SimpleVariation, {}, 2);
    auto s1 = df.Sum<int>("y");
@@ -1000,7 +1004,7 @@ struct MyCounter : public ROOT::Detail::RDF::RActionImpl<MyCounter> {
    }
 };
 
-TEST(RDFVary, VaryBook)
+TEST_P(RDFVary, VaryBook)
 {
    auto d = ROOT::RDataFrame(10)
                .Define("x", [](ULong64_t e) { return int(e); }, {"rdfentry_"})
@@ -1385,7 +1389,7 @@ TEST_P(RDFVary, VaryProfiles)
    EXPECT_DOUBLE_EQ(h2s["x:1"].GetMean(), 4.5);
 }
 
-TEST(RDFVary, VaryReduce)
+TEST_P(RDFVary, VaryReduce)
 {
    auto h = ROOT::RDataFrame(10)
                .Define("x", [](ULong64_t e) { return int(e); }, {"rdfentry_"})
```

**Comment by eguiraud** [comment]
I think the only tests where the MT version would actually exercise different code paths are VaryBook and VaryReduce -- I added those. For all others I don't think it makes a difference?

**Comment by ikabadzhov** [comment]
Maybe this one as well:
```diff
-TEST(RDFVary, RequireNVariationsIsConsistent)
+TEST_P(RDFVary, RequireNVariationsIsConsistent)
 {
    auto df = ROOT::RDataFrame(10).Define("x", [] { return 1; });
    auto s = df.Vary("x", SimpleVariation, {}, /*wrong=*/3).Sum<int>("x");
@@ -231,10 +231,14 @@ TEST(RDFVary, RequireNVariationsIsConsistent)
       std::runtime_error);
 
    std::cerr.rdbuf(oldCerrStreamBuf);
-   EXPECT_EQ(strCerr.str(), "RDataFrame::Run: event loop was interrupted\n");
+   std::string msg;
+   const auto nRepetitions = GetParam() ? std::min(4u, std::thread::hardware_concurrency()) : 1u;
+   for (auto i = 0u; i < nRepetitions; ++i)
+      msg += "RDataFrame::Run: event loop was interrupted\n";
+   EXPECT_EQ(strCerr.str(), msg);
 }
```
For the others I agree

**Review by ikabadzhov — APPROVED** [review]
nice, thanks. the other test is up to you - my reasoning was to check that each single thread throws

**Comment by eguiraud** [comment]
The `Require*` tests are testing that we correctly check for error conditions -- that should not depend on ST vs MT (but as you saw it might happen that if we check in each thread we get the error message printed N times)

**Pull request merged**
