### PR TITLE
Eve-7 Broaden use REveDataCollections

### PR DESCRIPTION
**Pull request by alja**
This change is redesign of REveDataCollection to visualize heavy events using DigitSets  or REveCaloData elements.
This change also makes online tooltips in calorimeters possible.
Note: In macro collection_proxies.C is an example of REveDigitSet using REveDataCollection. The demo has calorimeters included, but are not yet integrated in collections, e.g. individual towers can't be queried in table view.
caloyellow

### CODE REVIEW

**Comment by alja** [comment]
@linev Please review. I have tested macro event_demo.C, boxset.C, lineset.C together with collection_proxies.C

**Review by linev — APPROVED** [review]

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
Failure on `mac1015/cxx17` has nothing to do with the code.

**Comment by linev** [comment]
@alja, can you provide fix for warning about 'REveDataItem'? 
Strange, but I did not saw it before.

**Comment by alja** [comment]
@linev Ok, will do that soon.

**Pull request merged**
