### PR TITLE
Add google benchmark

### PR DESCRIPTION
**Pull request by vgvassilev**
This enables us to write performance benchmarks for specific ROOT functional points. Some of the advantages:
  * We can split performance tests from unit tests;
  * We can configure the benchmarks in a uniform way, specifying classes of benchmarks along with their running parameters (such as iterations);
  * We can calculate asymptotic complexity (Big O) of the benchmarked items;
  * Multithreading is a first class citizen;
  * We can fine tune optimization levels (preventing some code to be optimized away);
  * Rich reporting options;
  * Possibility for calculating statistical performance deviations;
  * More can be found [here](https://github.com/google/benchmark).

This would enable finer grained benchmarking of vectorized code.

### CODE REVIEW

**Comment by vgvassilev** [comment]
This is what I get with this. Please note that the code is still very dependent of -Dbuiltin_vc=On.
image

**Comment by bbockelm** [comment]
[Help with RooFit GBenchmark](https://trello.com/c/x1HfNaSf/16-help-with-roofit-gbenchmark)

**Comment by bbockelm** [comment]
[Help with RooFit GBenchmark](https://trello.com/c/x1HfNaSf/16-help-with-roofit-gbenchmark)

**Comment by pcanal** [comment]
>  Help with RooFit GBenchmark

Card not found.

This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.

**Comment by vgvassilev** [comment]
@pcanal, this is some weird GH trello integration which should be ignored.

**Comment by vgvassilev** [comment]
Looks like jenkins cannot propagate the return results back to the PR. We have all green except for gcc4.9 on centos7 which I had to cancel because of the huge backlog of jobs it currently has.

**Pull request merged**
