### PR TITLE
[clingutils] Modernize C++ casting in generated dictionaries to avoid potential warnings in derived applications

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
Improves cast safety by using static_cast instead of old C-style cast.

## Checklist:

- [x] tested changes locally

This PR fixes # 

## Additional context
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/1992/WG21%201992/X3J16_92-0122%20WG21_N0199.pdf

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
Thanks.  As a side note, since the input here are either nullptr or a void*, there is no practical difference beside the (potential) increased readability.

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by ferdymercury** [comment]
> Build failed on ROOT-performance-centos8-multicore/default. Running on olbdw-01.cern.ch:/data/sftnight/workspace/root-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/136652/console).
> ### Failing tests:
> 
>     * [projectroot.tmva.tmva.test.crossvalidation.gtest_tmva_tmva_test_crossvalidation_testCrossValidationIntVar](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/136652/testReport/projectroot.tmva.tmva.test/crossvalidation/gtest_tmva_tmva_test_crossvalidation_testCrossValidationIntVar/)

Is the failing test related to this PR ?

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by ferdymercury** [comment]
> Thanks. As a side note, since the input here are either nullptr or a void*, there is no practical difference beside the (potential) increased readability.

The main reason I proposed this is that in my own applications, I use -Wold-style-cast, and I get hundreds of warnings of ROOT-related classes / dictionaries, that mask my 'own' mistakes. Even if there is no practical difference, indeed for readability of external compilations it would be quite helpful.

**Comment by Axel-Naumann** [comment]
Failure seems unrelated.

**Pull request merged**
