### PR TITLE
[RF] Remove RooFormula code for gcc <= 4.8

### PR DESCRIPTION
**Pull request by guitargeek**
The code behind `#ifndef ROOFORMULA_HAVE_STD_REGEX` in `RooFormula.cxx` can be removed, because gcc 4.8 is effectively not supported anymore since the switch to switch to C++14 as the minimum standard to build ROOT. At this point, `std::regex` probably also works with visual studio, so the `#ifndef _MSC_VER` check can probably be removed in the same go.

Not having separate codes for different compilers means there is less room for bugs, like #11992.

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
@phsft-bot build

**Comment by guitargeek** [comment]
(to see if the `REMOVE_THIS_NOW` warnings are really gone now)

**Review by lmoneta — APPROVED** [review]
LGTM!

**Pull request merged**
