### PR TITLE
[cling] Simplify symbol overrides and `addOrReplaceDefinition`

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Review by devajithvs — APPROVED** [review]

**Comment by vgvassilev** [comment]
What does git blame says about the code we remove? Was that added separately to address some specific problem?

**Comment by hahnjo** [comment]
> What does git blame says about the code we remove? Was that added separately to address some specific problem?

Regarding forcing symbol emission, this was added all the way back in 2016 / 2017 by commits https://github.com/root-project/root/commit/189025d7682ad27614f32dd00cabf221046b71ea and https://github.com/root-project/root/commit/1c19e0ab4a039c83821d10169c5f0c1877c89ba4. You tried to reduce this during the upgrade to LLVM 9 (https://github.com/root-project/root/commit/696d5428d7a8863e72f4ad12b32c43fa1110eabd#diff-6e2f3604a761eaec5f5cda89a7dda68ab5a46e4369278267764daff49efaff74), Axel added back the full loop for Windows: https://github.com/root-project/root/commit/2c4a756d38d9b5f0348f645a116b3014159f03d6 The CI is green on Windows, and I believe it's not needed anymore with the current lookup mechanisms in ORCv2.

The lookup in `addOrReplaceDefinition` was added during the upgrade to LLVM 13 and the rewrite to ORCv2: https://github.com/root-project/root/commit/5c8451557d6eb578468a48acd87ba51e8d17304b#diff-6f538c4c81f9684d6b725af96572958f38a55ddbf11226ac5404a35b8caca965 I don't think this was ever necessary, as argued in the commit message: "Calling `getSymbolAddress` will force symbol emission, which is not needed if the intent is to replace it."

**Comment by vgvassilev** [comment]
Okay. Let’s move forward and see what happens!

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Pull request merged**
