### PR TITLE
Fix problems in hist painter (TF3)

### PR DESCRIPTION
**Pull request by linev**
1. Memory leak - when "pie" draw option is used, created TPie object is not destroyed
2. When tf3 draw option provided to histogram, it crashes `h3->Draw("tf3")` 
3. "TF3" and "ISO" strings does not correctly suppressed from options when decoded
4. TF3 pointer remains in global variable and not cleared when TF3 is deleted

### CODE REVIEW

**Comment by linev** [comment]
Here two macros showing the problem:

[bad.C.txt](https://github.com/root-project/root/files/4164562/bad.C.txt)
[cone3dfull.C.txt](https://github.com/root-project/root/files/4164563/cone3dfull.C.txt)

**Comment by couet** [comment]
Looks fine. I will check your example.

**Comment by linev** [comment]
> Looks fine. I will check your examples.

I slightly change method signature `TPainter3dAlgorithms::ImplicitFunction`.
Do you think anybody uses this class directly?
We could just make it "invisible" - do not show in `$ROOTSYS/includes`

**Comment by linev** [comment]
Actually, one should change two other static methods in `TPainter3dAlgorithms` - one can move them to THistPainter class

**Comment by linev** [comment]
In principle, `TPainter3dAlgorithms` class one could keep as is, moving all changes into `THisPainter`. Main problem - static variable keep invalid pointer and accidentally it can be used again. If we do not care about API in  `TPainter3dAlgorithms` - just let remove it from public includes. And complete changes, that non of static methods used for TF3 painting

**Comment by linev** [comment]
@couet That about idea of "hiding" TPainter3dAlgorithms class? Or keep it on the same place as before?

**Pull request merged**
