### PR TITLE
[ci-config] Turn on all Math packages on GitHub runners

### PR DESCRIPTION
**Pull request by lmoneta**
# This Pull request:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
By putting it into `buildconfig/`, it will also appear in the releases. Is that what we want, given GPL licensed dependencies?

**Comment by hahnjo** [comment]
> Yes absolutely, we need to put it back these packages that the physics user needs. Commercial users they can build themself a non-GPL release

Ok, that's a decision that deviates from what was implemented in the past, I don't think this should just be done in a PR. Also it will be hugely confusing if the math packages only appear in alma9. If the new decision is to include them, that must be a global switch IMHO.

**Comment by dpiparo** [comment]
The testing should happen indeed on all platforms. We can also have 1 build/released platform which is fully GPL.

**Comment by dpiparo** [comment]
Also, it's not really math, but SOFIE is not built nor tested via GH actions, on any platform.

**Comment by lmoneta** [comment]
> > Yes absolutely, we need to put it back these packages that the physics user needs. Commercial users they can build themself a non-GPL release
> 
> Ok, that's a decision that deviates from what was implemented in the past, I don't think this should just be done in a PR. Also it will be hugely confusing if the math packages only appear in alma9. If the new decision is to include them, that must be a global switch IMHO.

In the past (prior to 6.30) we have always distributed the GPL Math packages in the binaries. They have been distributed as separated shared libraries, so it was the responsibility of the users to what to link

**Comment by dpiparo** [comment]
Merging for the Fixathon, the discussion will have to continue afterwards.

**Comment by hahnjo** [comment]
If we decide to go this way, it should be properly implemented: Options for all platforms should go into `.github/workflows/root-ci-config/buildconfig/global.txt`, the files touched right now are reserved for platform specific overrides.

**Comment by guitargeek** [comment]
Superseeded by https://github.com/root-project/root/pull/15158, which also removed the removal of GPL options.

**Pull request closed without merging**
