### PR TITLE
[tmva standalone reader codegen] replace vectors by arrays

### PR DESCRIPTION
**Pull request by pseyfert**
The static vectors look like a thread safety issue in our tests.
std::array avoid memory allocation on every execution in the same way
the static vector does.

NB: `#include <array>` is already present in the codegen from `MethodBase.cxx`

WIP: local building and testing

### CODE REVIEW

**Comment by pseyfert** [comment]
good from my side now.

**Comment by lmoneta** [comment]
The PR looks good to me. It would be nice however to have a test that the code result is correct.

**Comment by ashlaban** [comment]
@lmoneta, what tests would be required before merging is ok?

**Comment by pseyfert** [comment]
closing all my cern related PRs as won't-pursue-anymore w/o checking status

**Pull request closed without merging**
