### PR TITLE
Fix linking warnings due to visibility=hidden being set for the tests.

### PR DESCRIPTION
**Pull request by Teemperor**
Currently if we compile this test we get ld warning messages like this:

```
ld: direct access in function ... to global weak symbol. This was likely
caused by different translation units being compiled with different
visibility settings.
```

This seems to be caused by the fact that visibility=hidden is spreading
from the parent directory to the test directory, even though it should
only land in the src/ directory. As CMAKE_CXX_FLAGS is working on a
per subdirectory basis, we just move the code for handling the source
code to the src/ folder, which should contain the visibility=hidden.

### CODE REVIEW

**Comment by Teemperor** [comment]
Just making a PR to test this on OS X for now.

**Comment by Axel-Naumann** [comment]
Can you attach the `diff -u` of the two files? You moving the file *and* changing it in the same commit makes it impossible for me to figure out what has changed in the content...

**Comment by Axel-Naumann** [comment]
The diff was personally brought to my office - it's empty. Will merge once Jenkins reports happiness.

**Comment by Axel-Naumann** [comment]
The same failure exists without this PR. Merging!

**Pull request merged**
