### PR TITLE
[cont] Fix TArray?::AddAt() to actually add. Thanks, Jan Fiete!

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Review by lmoneta — APPROVED** [review]
LGTM !

**Review by lmoneta — COMMENTED** [review]
Actually, we should update also the documentation as well, see the doc for TArrayD::AddTo. 
In addition this is maybe a behaviour change, some users maybe expect something else, but I think it is still good to fix this. They can use the assignment operator for this

**Comment by Axel-Naumann** [comment]
Ouch - that's terrible (and I remember now having stepped into this pitfall before). It's "simulating" `TCollection::AddAt(idx, val)`.

We need to choose between breaking backward compatibility and fixing interface expectation :-/ I really don't know what to do here. I'd even argue that we should remove the function altogether, as the cleanest solution. I will close this in favor of removal.

**Comment by lmoneta** [comment]
I agree, remove the function is probably the best solution !

**Comment by jgrosseo** [comment]
What we actually need - for optimal performance - would be an Add function without out of bounds check. Let me know how you decide, and we adapt.

**Comment by jgrosseo** [comment]
Adding @ktf to this

**Pull request closed without merging**
