### PR TITLE
Adding RooFit/ RooStat libraries

### PR DESCRIPTION
**Pull request by guiguem**
Test if root install has roofit, if yes add the roofit and other libraries to rootlibs

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Thanks for your PR, @guiguem !

After a discussion within the team we decided not to apply it for the following reasons:
- RooFit is not even enabled by default. If we reconsider that ROOT should really be built with RooFit then we will revisit your PR (or something similar).
- it is fairly trivial to add `RooFit` to CMake's `find_package` https://root.cern.ch/how/integrate-root-my-project-cmake / to add a `-lRooFit` behind `root-config --libs`, so adding this to our build system doesn't appear to be a huge simplification for users.

I hope this explanation reduces  a bit the frustration that our decision might cause - we do appreciate your suggestion especially as it's a PR!

**Comment by guiguem** [comment]
Thank you for considering this PR and for your answer, @Axel-Naumann 

The way the modification was designed accounts for the case when RooFit is not enabled (by not adding the library), so I don't understand your first reason.

Also I thought this findROOT.cmake was supposed to be used generically by people willing to find the root libs via cmake.
Even if I agree this is possible, it is not obvious from the documentation and the page you just mention, which is the reason I modified the findROOT.cmake in the first place.
Maybe I think adding some documentation would then be helpful if this PR is not applied.

**Comment by Axel-Naumann** [comment]
Dear Mathieu @guiguem - excellent point on the doc, thanks! I have created https://sft.its.cern.ch/jira/browse/ROOT-9009 for it.

The first reason is about RooFit being a crucial part or not. If it is, we should include it in the (crucial) libraries that `find_package` sets; but then we should also build it by default (because it's crucial). As long as we don't build it by default we mark it as "not crucial for ROOT". This might well change in the near future, given the relevance of RooFit - at which point we'll add it to `find_package`, too!

**Comment by guiguem** [comment]
I see!
Thank you for these explanations and opening an issue.

**Pull request closed without merging**
