### PR TITLE
Remove many includes duplication in ROOT sources

### PR DESCRIPTION
**Pull request by linev**
Also in some places use `TVirtualPad.h` instead of `TPad.h`

### CODE REVIEW

**Comment by linev** [comment]
> Now you just have to find all includes that could also be handled with a forward declaration. ;-)

I do not intend to touch such cases. There are many good reasons to have them as is.
But I just looked through the code (with Eclipse help)  and tried to exclude heavy includes like `TMath.h` or `TVirtualX.h` there they simply not used

**Comment by linev** [comment]
@Axel-Naumann  @bellenot   Something wrong with Jenkins link https://epsft-jenkins.cern.ch/job/root-pullrequests-handler/12463/console - it shows building of previous PR?

**Comment by bellenot** [comment]
What do you mean? The log says:
`GitHub pull request #5080 of commit 8e61ce5abe749d76c2ec091933487c5f7a3616f4, no merge conflicts.`

**Comment by linev** [comment]
If I click on jenkins link, and then on mac or windows build, I see list of changes from previous PR.
But yes, few lines later it says something about merging PR #5080 - somehow misleading. False alarm.

**Pull request merged**
