### PR TITLE
[cxxmodules] Use the API to load top level system modules.

### PR DESCRIPTION
**Pull request by vgvassilev**
This will allow us to uniformly load all modules tagged as `[system]`. This way we avoid explicitly mentioning the module names (helpful for OSX).

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Druntime_cxxmodules=Off

**Comment by Teemperor** [comment]
`HeaderSearch::loadTopLevelSystemModules` is a misnomer: It only loads the modulemap files in the system paths but it doesn't actually load the C++ modules behind them into the lookup. It's however a good idea to actually call this *in addition* to our code because it ensures that clang's module lookup is up to date.

Can you remove the deletions in this patch, the rest is good to go.

(For example this test fails now: https://epsft-jenkins.cern.ch/job/root-pullrequests-build/12169/testReport/projectroot.roottest.root.tree/addresses/roottest_root_tree_addresses_make/ )

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
PR #1350 supersedes this one. Closing.

**Pull request closed without merging**
