### PR TITLE
[RDF][Doc] Save figures in the Python tutorials also to disk

### PR DESCRIPTION
**Pull request by stwunsch**
* In Python script mode the canvases dont stay on screen, therefore
  the figures are saved and an according notification is printed.
* Fixes ROOT-10960

### CODE REVIEW

**Comment by stwunsch** [comment]
I don't like the future thingy if it's not absolutely necessary to prevent the code from breaking since py2 is dead (or let's say zombie ;))

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
I thought some [info statement](https://github.com/root-project/root/blob/master/graf2d/gpad/src/TPad.cxx#L4927) was printed when saving the image :thinking:

**Comment by stwunsch** [comment]
It depends on the log level of root and i think other factors (i don't see it always). however, i've put it also in the code to make it very explicit that there's a file at the end :)

**Comment by eguiraud** [comment]
it also makes things clearer when reading the tutorial code

**Comment by vepadulano** [comment]
That's fair, very well!

**Pull request merged**
