### PR TITLE
[graf2d] Apply `clang-tidy` suggestions

### PR DESCRIPTION
**Pull request by guitargeek**
This is applying most of the suggestions from the CMSSW clang-tidy configuration:
https://github.com/cms-sw/cmssw/blob/master/.clang-tidy

Two checks are excluded though, because they can make wrong suggestions about replacing copies with const references:

  * `performance-for-range-copy`

  * `performance-unnecessary-copy-initialization`

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by couet — APPROVED** [review]
lgtm

**Comment by guitargeek** [comment]
@phsft-bot to see if the Windows failures go away

**Comment by guitargeek** [comment]
@phsft-bot build

**Pull request merged**
