### PR TITLE
Update Vc to version 1.3.0 in CMake externals

### PR DESCRIPTION
**Pull request by amadio**
- Update Vc to version 1.3.0
- Download from LCG at CERN (Vc-1.3.0 not yet available at service-spi.web.cern.ch)
- Use same compiler options and installation prefix as ROOT
- Configure and install Vc into CMake binary directory
- Install at the end with the rest of ROOT

### CODE REVIEW

**Comment by karies** [comment]
@phsft-bot build!

**Comment by amadio** [comment]
Following a comment by @dpiparo, I've updated the branch to pull Vc from LCG rather than GitHub and rebased.

**Comment by amadio** [comment]
This is what I see on Jenkins:
```
Caused by: hudson.plugins.git.GitException:
Command "git fetch --tags --progress https://github.com/root-project/root.git
     +refs/pull/*:refs/remotes/origin/pr/*" returned status code 143:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
	... 12 more
ERROR: null
```
Could it be because I opened the merge request before the migration to root-project?

**Comment by dpiparo** [comment]
Thanks, merged!

**Pull request closed without merging**
