### PR TITLE
[CMake] Update TBB version

### PR DESCRIPTION
**Pull request by dpiparo**
This PR is a proposed solution for a problem of MacOS builds. It is more of a policy decision than a technical discussion, even if there is a technical aspect involved.

Since 2019 U9, the one of 6.28, does not build any more on macos for C++ standards equal or greater than 2017 if the new sdk is used. Unfortunately, to continue to support older setups, branching has been put in place.

# This Pull request:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Sorry - I'm missing why updating builtin tbb unconditionally is off the table? Is it?

**Comment by dpiparo** [comment]
> Sorry - I'm missing why updating builtin tbb unconditionally is off the table? Is it?

Not really, for continuity this was a first proposal, also linked to some discussions in the LIM. The overall cost of maintaining just one TBB version would be much lower and I personally would be in favour of simplifying the configuration, if possible.

**Comment by Axel-Naumann** [comment]
Thanks. Could you maybe check with the CI whether an update to the tbb version we currently use in master is working well?

**Comment by dpiparo** [comment]
Now that the code has been thoroughly tested, the changes have been re-expressed as cherry-picks for the final round of builds before the nightlies.

**Review by Axel-Naumann — APPROVED** [review]
Perfect thanks!

**Comment by guitargeek** [comment]
Closes #7063.

**Pull request merged**
