### PR TITLE
[RF] Fix root-project/root#6408.

### PR DESCRIPTION
**Pull request by hageboeck**
Fix root-project/root#6408

Here, RooFit is bitten by a dangerous `FIXME` that wasn't fixed, see this:

https://github.com/root-project/root/blob/ee4e822e3413938b740850db68ab2221fd19744d/tree/tree/src/TBranch.cxx#L477-L499

What happens is that RooFit imports stuff from a Tree. To not disturb that tree, @pcanal suggested to clone it, and loop through it:
```c++
  std::unique_ptr<TTree> tClone(static_cast<TTree*>(t->Clone()));
  tClone->SetDirectory(t->GetDirectory());
```
For reasons I don't remember, I was instructed to set the directory of the clone to the original directory of the tree.

That now leads to a crash, because the cloned Tree closes the input file! I could work around the crash by instead using this:
```c++
  auto deleter = [](TTree* tree){tree->SetDirectory(nullptr); delete tree;};
  std::unique_ptr<TTree, decltype(deleter)> tClone(static_cast<TTree*>(t->Clone()), deleter);
  tClone->SetDirectory(t->GetDirectory());
```

But the `FIXME` might need a fix, though.

### CODE REVIEW

**Comment by eguiraud** [comment]
It seems that these lines here below in which TBranch's destructor deletes a TFile are causing the issue. I have never seen this behavior before and I would not expect `~TBranch` to cause a call to `~TFile` -- rather the opposite.

https://github.com/root-project/root/blob/ee4e822e3413938b740850db68ab2221fd19744d/tree/tree/src/TBranch.cxx#L477-L499

I don't know whether there is a better way to fix/work around this TBranch quirk, so I'll have to recuse myself as reviewer and ask for @pcanal 's input :sweat_smile:

**Comment by pcanal** [comment]
This code is for the (very rare this days) case where a TBranch is stored in a different file than its TTree.
I.e. in your use case is 
```fDirectory != fTree->GetDirectory()```
triggered?

**Review by lmoneta — APPROVED** [review]
Looks good

**Comment by hageboeck** [comment]
> This code is for the (very rare this days) case where a TBranch is stored in a different file than its TTree.
I.e. in your use case is
fDirectory != fTree->GetDirectory()
triggered?

Yes!
```
(gdb) print fDirectory
$3 = (TDirectoryFile *) 0x10af350
(gdb) print fDirectory->GetName()
$5 = 0x10af369 "test.root"

(gdb) print fTree->GetDirectory()
$4 = (TROOT *) 0x7ffff3fb46a8 <ROOT::Internal::GetROOT1()::alloc>
(gdb) print fTree->GetDirectory()->GetName()
$6 = 0x7ffff3fb46c1 <ROOT::Internal::GetROOT1()::alloc+25> "root"
```

**Comment by hageboeck** [comment]
So @pcanal, do I merge the workaround/fix that sets the Tree's directory to `nullptr` before deleting it or will you change something in TBranch/TTree?

FYI, the deletion happens via this stack trace:
```
#0  TDirectoryFile::~TDirectoryFile (this=0x10af350) at /home/shageboe/root-src/io/io/src/TDirectoryFile.cxx:180
#1  0x00007ffff546944a in TFile::~TFile (this=0x10af350) at /home/shageboe/root-src/io/io/src/TFile.cxx:542
#2  0x00007ffff54694b9 in TFile::~TFile (this=0x10af350) at /home/shageboe/root-src/io/io/src/TFile.cxx:504
#3  0x00007ffff6d0c788 in TBranch::~TBranch (this=0x1069140) at /home/shageboe/root-src/tree/tree/src/TBranch.cxx:496
#4  0x00007ffff6d0ce39 in TBranch::~TBranch (this=0x1069140) at /home/shageboe/root-src/tree/tree/src/TBranch.cxx:443
#5  0x00007ffff3adabc7 in TCollection::GarbageCollect (obj=0x1069140) at /home/shageboe/root-src/core/cont/src/TCollection.cxx:736
#6  0x00007ffff3aee10f in TObjArray::Delete (this=0x1b19e18) at /home/shageboe/root-src/core/cont/src/TObjArray.cxx:376
#7  0x00007ffff6dac053 in TTree::~TTree (this=0x1b19cc0) at /home/shageboe/root-src/tree/tree/src/TTree.cxx:951
#8  0x00007ffff6daca59 in TTree::~TTree (this=0x1b19cc0) at /home/shageboe/root-src/tree/tree/src/TTree.cxx:909
#9  0x00007ffff789aaaf in std::default_delete<TTree>::operator() (this=0x7fffffffcdf0, __ptr=0x1b19cc0)
<In RooFit as found in the diff of this PR>
```

**Comment by pcanal** [comment]
Since it is unlikely to be your intent to have a TTree that is in-memory (nullptr or associated with gROOT) but the TBranch associated with a file, I think we need to fix it on the I/O side.  It is "telling" that the fix is to switch the TTree from being associated with gROOT to being associated with nullptr.   So what's the reproducer :) ?

**Comment by hageboeck** [comment]
> So what's the reproducer :) ?

It's #6477

**Comment by pcanal** [comment]
thannks.

**Pull request merged**
