### PR TITLE
Removing mail address

### PR DESCRIPTION
**Pull request by martinmine**
Hi,

Hope everyone is doing well. I noticed my mail address_es_, nicknames and full names in this file and I want it removed since. I noticed it on Google after I looked up my mail address there. Idk if this PR will make it go away completely from GitHub but I guess it proves the point I am trying to make. 

Thanks!

PS: How is GDPR going?

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Hi Martin - well, that's inconsistent :-) This file collects the git identities you used for commits to this repo. It's a view of data that's in the repo anyway; github shows it, git clone has it. (Re GDPR: that's data that you willingly provided through your commits, without us asking, so I'm not sure how this relates.)

That said we can of course remove you from the mail map. As @amadio set this up I'd appreciate if we could wait for his review. But he is on a long multi-week trip. Please let me know whether we can wait.

**Comment by martinmine** [comment]
@Axel-Naumann The file has been out for a few months, so I'm sure it won't hurt being there a few more weeks till @amadio returns. I'm aware that git already has this information, the problem is that this is now a file in the repo itself and not just part of the git "metadata", leading to that my name + aliases + email addresses gets distributed in other channels than just source control.

**Comment by amadio** [comment]
Hi Martin! How are you doing? We can certainly remove the information from the mailmap file, but that file only repeats info already in the git log (i.e. the file only maps contributions with different emails to your CERN email). We cannot remove the information from the git log, so I don't see much gain from removing it from the mailmap file either. In any case, if you still prefer to remove, just let us know and either me or someone else will merge this PR.

**Comment by martinmine** [comment]
@amadio I'm doing pretty fine thanks, life out in the industry is quite different from CERN :) Like I said in my previous comment, the problem I have is that this information gets distributed with other channels as well. Currently it is part of git (which I am perfectly fine with), but by placing this information in a file makes it get distributed in the channels where the git history is not, such as a tar of the source code. Another example is search engines where Google is how I discovered my mail address was there. So yes, you can go ahead and merge this. Thanks!

**Pull request merged**
