### PR TITLE
[clad] Bump clad version to v1.1.

### PR DESCRIPTION
**Pull request by vgvassilev**
This new release includes some improvements:
  * Improvements in the array handling in the Error Estimation Framework
  * Fixed numerical stability of the pow pushforward
  * Fixed handling of for-loop conditions in reverse mode
  * LLVM15 Support

See more at: https://github.com/vgvassilev/clad/blob/v1.1/docs/internalDocs/ReleaseNotes.md

### CODE REVIEW

**Comment by vgvassilev** [comment]
@hahnjo, that when/if merged should fix your clad failures with llvm15...

**Comment by vgvassilev** [comment]
@lmoneta, that release should fix the issue you reported with `std::pow` and the hessian support.

**Comment by lmoneta** [comment]
Great! Thank you Vassil!

**Comment by vgvassilev** [comment]
The failures are seen elsewhere in the PRs and they seem unrelated to this particular proposed change.

**Review by hahnjo — APPROVED** [review]
I agree, failures are also seen in the nightlies and on other PRs

**Pull request merged**
