### PR TITLE
[gpad] Implement TRatioPlot::RecursiveRemove

### PR DESCRIPTION
**Pull request by linev**
`TRatioPlot` object was registered in list of cleanups, but recursive remove was not implemented.
Therefore if any internal object was deleted before - it make problem.

Fixes issue #14855

### CODE REVIEW

**Review by couet — APPROVED** [review]

**Comment by pcanal** [comment]
What does valgrind says about the crash?

**Comment by linev** [comment]
I rebase my commit - problem was little bit more complicated.

One need to add `TRatioPlot` to list of cleanups also in default constructor - when it read from the file.
And then correctly cleanup all refs. 

Crash was already in the first `safeDelete(fRatioGraph);` - while graph was drawn in subpads.
Workaround with `ROOT::Detail::HasBeenDeleted(obj)` was not really working here.

**Comment by linev** [comment]
Maybe it is not good idea with default constructor - but this is the only solution without creating custom streamer.

**Comment by pcanal** [comment]
>  Maybe it is not good idea with default constructor - but this is the only solution without creating custom streamer.

It is probably fine.  The alternative is to use an I/O rule to do the registration.

**Comment by pcanal** [comment]
> Workaround with ROOT::Detail::HasBeenDeleted(obj) was not really working here.

Indeed.  `HasBeenDeleted` by definition reads 'previously deleted' memory that may have been re-used for another purpose between the deletion and its execution and thus is not reliable at all.  (The main use for it is to issue diagnostic that a problem was detected but it can not be rely upon to actually avoid double deletion).

**Comment by linev** [comment]
Too many errors and it is not easy to make TRatioPlot working after reading from the file.

Need further investigations

**Comment by linev** [comment]
Close in favor of https://github.com/root-project/root/pull/14881

**Pull request closed without merging**
