### PR TITLE
Don't check CMAKE_GENERATOR use MSVC instead

### PR DESCRIPTION
**Pull request by Neumann-A**
## Changes or fixes:
Fix shared library output name if the generator is not `Visual Studio` but e.g. `Ninja`

## Checklist:
- [x] tested changes locally
- [x] ~~updated the docs (if necessary)~~

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@Neumann-A please ignore failures here - we're currently in rough waters; we know which failures to expect and which not, we'll tell you if we need you to look at any failure.

**Comment by guitargeek** [comment]
Hi @Neumann-A, thanks for the PR and sorry for the late reply!

Does that mean we should also remove this check (which is redundant with the `MSVC` check two lines before that)?
https://github.com/root-project/root/blob/master/builtins/zstd/cmake/AddZstdCompilationFlags.cmake#L43

If yes, maybe it can be changed in this PR too?

**Comment by Neumann-A** [comment]
> Does that mean we should also remove this check (which is redundant with the MSVC check two lines before that)?
https://github.com/root-project/root/blob/master/builtins/zstd/cmake/AddZstdCompilationFlags.cmake#L43

You probably want to check `CMAKE_CXX_COMPILER_ID` there instead of the generator since the /MP flag only works with cl and clang-cl will throw a warning. `/MP + ninja` is probably oversubscribing but ok. For me that code seems to come from upstream zstd so i would advise against patching that. Also why even vendor zstd, use conan or vcpkg to obtain it.

**Comment by guitargeek** [comment]
@phsft-bot build

**Review by bellenot — APPROVED** [review]
LGTM, thanks for the PR and sorry for the delay

**Pull request merged**
