### PR TITLE
[RGL] Allow disabling of display list usage

### PR DESCRIPTION
**Pull request by osschar**
Some MesaGL implementations (since 2016) have trouble (segv) when one tries
to store vertex array operations into display lists. The following options allow complete or partial
disablement of display list usage.
OpenGL.UseDisplayLists:                     1
OpenGL.UseDisplayListsForVertexArrays:      1

OpenGL.UseDisplayLists already works.

Handling of OpenGL.UseDisplayListsForVertexArrays still needs to be
implemented as it requires review of all GL rendering classes but the cover-all case should allow people to get past this hurdle already.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@osschar, could you look at the clang-format failures? All modulo few alignment suggestions are reasonable.

**Comment by osschar** [comment]
Hi @vgvassilev ... I went through it ... and this makes no sense. This is how all gl/eve are written. If you want to run clan-format on both whole packages it's fine with me but i'm not going to do it by hand on a set of random files that get touched for bugfixes :)

**Comment by vgvassilev** [comment]
@phsft-bot build!

I understand your point. I had mostly in mind the changes in the function bodies and the spacing in the `ClassDef`.

**Comment by petricm** [comment]
Hi,
what is the status of this PR?

**Comment by pcanal** [comment]
@phsft-bot build please

**Pull request merged**
