### PR TITLE
Unify data members initialization in TF1

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
Rebased to resolve conflicts

**Comment by xvallspl** [comment]
Wow, that's weird.

I don't see how is that test related to the changes.

**Comment by xvallspl** [comment]
Not related to this PR, I can reproduce it on the master. Investigating...

**Comment by xvallspl** [comment]
Found it. Merging this one.

**Pull request merged**
