### PR TITLE
[RF] Reduce global statics

### PR DESCRIPTION
**Pull request by hageboeck**
RooFit uses a lot of global statics in factories. These have been replaced by function-local statics.

### CODE REVIEW

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
Seems ready to merge. Due to absence next week, I will keep it open for now.

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by hageboeck** [comment]
The failure in Windows is
`21:22:41 C:\build\workspace\root-pullrequests-build\root\tree\dataframe\test\dataframe_nodes.cxx(97): error C3493: 'nBinsExpected' cannot be implicitly captured because no default capture mode has been specified [C:\build\workspace\root-pullrequests-build\build\tree\dataframe\test\dataframe_nodes.vcxproj]`
Therefore, ready to merge.

**Comment by hageboeck** [comment]
@phsft-bot build

**Pull request merged**
