### PR TITLE
[TDF] Resolve open issues of PR #423

### PR DESCRIPTION
**Pull request by bluehood**
With these commits the reshuffling of methods and objects between files should be over.
A couple of layering issues have been fixed.

### CODE REVIEW

**Comment by bluehood** [comment]
fixed formatting :)

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by bluehood** [comment]
None of the build errors seem related to this PR if I see correctly.

**Comment by dpiparo** [comment]
@phsft-bot build

**Pull request closed without merging**
