### PR TITLE
Fixed more race conditions in the build system.

### PR DESCRIPTION
**Pull request by Teemperor**
If the G__X filenames don't match with a module called X, then
CMake can't find the right dependencies and we get race conditions.
This patch fixes all a few more typos that caused those problems.

Found by our debug code in RootNewMacros (which is now nearly silent).

### CODE REVIEW

**Comment by Teemperor** [comment]
Eh, failed due to infrastructure problems... See https://epsft-jenkins.cern.ch/job/root-pullrequests-build/2859/console

**Comment by Teemperor** [comment]
By the way, #767 will also fix this, but I wanted to get this "functionality" change in master. That way it doesn't matter if #767 takes a while because it's otherwise cosmetics/refactoring with NFC.

**Comment by vgvassilev** [comment]
I think we can merge as is if @amadio is ok with it.

**Comment by amadio** [comment]
Sure, go ahead. I think these were just typos not caught before.

**Pull request merged**
