### PR TITLE
[DF] Isolate imports in distributed backend classes

### PR DESCRIPTION
**Pull request by vepadulano**
Uploading the logic for discussion. This needs a test that actually pinpoints the problem.

Brief description of original issue: 
When launching a distributed RDF application with Dask from SWAN (and only specifically from SWAN) to a cluster of VMs, a `ModuleNotFoundError` is triggered for a missing `pyspark` module, even though the application doesn't use Spark in any way. At the moment this issue cannot be reproduced launching the same application from one of the VMs to the others or on my local machine.

### CODE REVIEW

**Comment by etejedor** [comment]
Is there a place in our code where we import all the backend modules, independently of whether they are used or not? There must be some piece of code that triggers these imports.

**Comment by vepadulano** [comment]
> Is there a place in our code where we import all the backend modules, independently of whether they are used or not?

We import the [Python module of each backend](https://github.com/root-project/root/blob/f61d5ef82a8851f488318be8eefe06a7d5311744/bindings/experimental/distrdf/python/DistRDF/Backends/__init__.py#L18), for example  this is the Spark one https://github.com/root-project/root/blob/master/bindings/experimental/distrdf/python/DistRDF/Backends/Spark/__init__.py . Note that there are no exposed `pyspark` or `py4j` in the Python module. They are only written in the `Backend.py` submodule, which is only ever imported if the `RDataFrame` function of that specific module is called. So this should be already more than enough to isolate the different backends

**Comment by etejedor** [comment]
Ok so we do import every time. What is strange is that we don't hit this always, we should see the error every time e.g. there is no Spark on the worker side. Another option would be to keep the imports at module level as they are now, but make the import of the backend modules lazy?

**Comment by vepadulano** [comment]
> Ok so we do import every time.

We import an empty Python module every time, with a lazy function that only when called would import another Python module that contains the [pyspark, dask] module

**Comment by vepadulano** [comment]
> but make the import of the backend modules lazy?

I'm not sure how that could be done right now. Probably some modification in the function called by the facade. Need to think about it

**Comment by etejedor** [comment]
> We import an empty Python module every time, with a function that only when called would lazily import another Python module that contains the [pyspark, dask] module

But then the imports are already lazy, aren't they? E.g. the import of pyspark is only triggered when I call [this function](https://github.com/root-project/root/blob/f61d5ef82a8851f488318be8eefe06a7d5311744/bindings/experimental/distrdf/python/DistRDF/Backends/Spark/__init__.py#L13), and that only happens when I am constructing a Spark RDataFrame, not when I'm constructing a Dask RDataFrame. So I still don't see how we get those errors.

**Comment by vepadulano** [comment]
> Now I remembered our chat, and we get the errors because pyspark is always injected in sys.modules in SWAN. So then this PR is not necessary?

Yes indeed, after further digging we discovered that opening a notebook in a SWAN session (with no modifications on the environment from our side) already shows `"pyspark" in sys.modules == True`. No extra dependency is injected by ROOT, so this PR can be closed

**Pull request closed without merging**
