### PR TITLE
Make install improvements

### PR DESCRIPTION
**Pull request by ellert**
Don't install intermediate static libs (mathtext and minicern).
Don't add JupyROOT python extension to cmake exports.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by etejedor** [comment]
After discussing with @amadio it should be fine to add the proposed flag for JupyROOT, since it is a library only intended to be used internally from the ROOT Jupyter kernel.

**Comment by amadio** [comment]
Yes, this is probably OK to merge, but I will confirm with @Axel-Naumann first that minicern is not used by external users before removing it from the installation.

**Comment by Axel-Naumann** [comment]
Minicern *is* used, see e.g. https://github.com/cjpl/mdaq-midas/blob/master/roody/Makefile

**Comment by bellenot** [comment]
And maybe @couet can give feedback too, since this is related to hbook/PAW (if I remember correctly)

**Comment by ellert** [comment]
@Axel-Naumann: That Makefile looks for libminicern.so - and links to it if it is found. It does not link to libminicern.a. The Makefile is backward compatible with old root versions where minicern was a shared library. Now minicern is static and linked into libHbook. Linking to libHbook only is sufficient, and is what the Makefile does when there is no libminicern.so. That Makefile does NOT need libminicern.a.

**Comment by amadio** [comment]
Hi @ellert, I am a bit reluctant to remove minicern without any notice, but the other two changes should be fine. Even though you are right about the Makefile linked by Axel, I think that since this is a backward incompatible change, we should at least announce the removal in the development release (coming sometime soon), and then remove it only in ROOT 6.14. What do you think?

**Comment by ellert** [comment]
I split off the minicern change to a separate PR #1675.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
I see that the build had already passed, so I just merged it. Thanks!

**Pull request merged**
