### PR TITLE
[IMT] Improve docs for EnableImplicitMT

### PR DESCRIPTION
**Pull request by bluehood**

### CODE REVIEW

**Comment by bluehood** [comment]
clang-format failed...?

**Comment by bluehood** [comment]
First commit was wrong. I am not sure why Doxygen does not pick up the default value for `EnableImplicitMT`. It is specified in the header file.

**Comment by vgvassilev** [comment]
@bluehood, it seems the documentation line is longer than what ROOT's coding conventions expect.

To reproduce it locally you can run 'git-clang-format-3.9 --commit b550d3b74bdfd8efbff9ce52faa8652df0242d22 --diff --binary `which clang-format-3.9`'

**Comment by bluehood** [comment]
@vgvassilev I see, should be fixed

**Comment by dpiparo** [comment]
Excuse me, what is the maximum lenght?

**Comment by dpiparo** [comment]
Merged, thanks.

**Comment by pcanal** [comment]
> Excuse me, what is the maximum lenght?

ColumnLimit:     120

**Comment by pcanal** [comment]
> git-clang-format-3.9

Which package/version includes this?

**Comment by bluehood** [comment]
@pcanal Ubuntu 16.04 can get up to clang-format-3.8, which worked fine for me. My Debian stable machine has access to clang-format-3.5 at most, have not tried that

**Comment by dpiparo** [comment]
Hi @bluehood, I think I tried but it did not work. Can you try this version of the config file? https://root.cern.ch/coding-conventions#ClangFormat

**Pull request merged**
