### PR TITLE
Make sure the bar color is different from the frame color

### PR DESCRIPTION
**Pull request by couet**
Since the new defaults have been setup (ie the new "Clean Style")
the bar color for graphs was by default white (equal t the frame color).
As the bars are fill area only (no borders) they were invisible by default.
This patch make sure the bar color is different form the frame color.
This PR fixes: https://github.com/root-project/root/issues/9870

### CODE REVIEW

**Comment by linev** [comment]
Olivier, I cannot find place in code where `TGraph` line/fill attributes applied to the pad painter.
`gPad->GetPainter()->SetFillColor();` appears for the first time in your PR.

**Comment by couet** [comment]
the bars are painted with the low level graphics gPad->PaintBox. I do no what to change the colorer the bar I just want to paint them different if the color is equal to the Frame one. That's why I stay low level. At the Painter level

**Comment by linev** [comment]
> I do no what to change the colorer the bar I just want to paint them different if the color is equal to the Frame one. That's why I stay low level. At the Painter level

This I understand, but I do not find a place where fill attributes set by default for bars? 
That happens when from beginig: `theGraph->GetFillColor() != gPad->GetFrameFillColor()`

**Comment by couet** [comment]
You are right I will investigate a bit more.

**Comment by couet** [comment]
It is done on line 1448:
```
theGraph->TAttFill::Modify();
```
This line does:
```
gVirtualX->SetFillColor(fFillColor);
gVirtualX->SetFillStyle(fFillStyle);
```

**Comment by linev** [comment]
There are also lines like:
```
if (!gPad->IsBatch()) {
      gVirtualX->SetFillColor(fFillColor);
      gVirtualX->SetFillStyle(fFillStyle);
   }

   gPad->SetAttFillPS(fFillColor,fFillStyle);
```

Should it be similar also in your PR?

**Comment by couet** [comment]
I made a better version

**Review by linev — APPROVED** [review]
Yes, now it looks reasonable.

**Pull request merged**
