### PR TITLE
Reduce usage of TVirtualX.h in other includes

### PR DESCRIPTION
**Pull request by linev**
Via `TVirtualPad.h` it was spread over many sources.
But only `enum ECursor` was required in `TVirtualPad.h`
I just moved `ECursor` to `GuiTypes.h`, where many similar enum are defined.
Now one can fully remove `TVirtualX.h` from `TVirtualPad.h`, `TCanvas.h` and co.

Also GUI classes do not require to populate `TVirtualX` interface via headers - 
one can put `#include "TVirtualX.h"` in sources where it really used.
If necessary, we could place back TVirtualX.h into TGWindow.h - I can remove last commit.

### CODE REVIEW

**Comment by linev** [comment]
Bertrand @bellenot, are you ok with proposed PR.
Most changes appears in GUI classes, but as mention in description, I can keep `TVirtualX.h` include in `TGWindow.h`.

**Comment by bellenot** [comment]
> Bertrand @bellenot, are you ok with proposed PR.
> Most changes appears in GUI classes, but as mention in description, I can keep `TVirtualX.h` include in `TGWindow.h`.

@linev so you basically move the `#include "TVirualX.h"` from the headers to the sources, right? What is the benefit?

**Comment by linev** [comment]
> What is the benefit?

`TVirtualX.h` do not needed in headers while not used there. Reduce dependncies when during compilation and producing dictionaries.

**Comment by bellenot** [comment]
> > What is the benefit?
> 
> `TVirtualX.h` do not needed in headers while not used there. Reduce dependncies when during compilation and producing dictionaries.

OK, thanks for the explanation. It's fine with me.

**Pull request merged**
