### PR TITLE
In rootd, do not use a call to popen() to expand path names

### PR DESCRIPTION
**Pull request by gganis**
Addressed security threat reported by S. Luders.
Using the same technology used in TSystem::ExpandFileName .

### CODE REVIEW

**Comment by peremato** [comment]
@gganis Naive question. Why not to call TSystem::ExpandFileName from RootdExpandFileName instead of copying the code?

**Comment by gganis** [comment]
Because rootd is standalone (not a ROOT application in the strict sense) and it would have meant to link it with libCore.
It was the easiest mod, in the spirit of how rootd was initially written (there are other duplications).

**Comment by peremato** [comment]
OK. Thanks for the explanation. We could eventually statically link with the object files of libCore, but since is very obsolete does not make sense.

**Comment by vgvassilev** [comment]
Could somebody merge that in? Maybe we should backport it to 6.08.

**Comment by peremato** [comment]
Thanks @gganis

**Pull request merged**
