### PR TITLE
Avoid useless construction/destruction of imtHelper in TTree::Fill()

### PR DESCRIPTION
**Pull request by amadio**
If IMT is disabled, TTree::Fill() is constructing and destructing the
imtHelper object at every call and never using it. By moving its
declaration into the #ifdef, we avoid this penalty. This commit also
avoids the penalty of checking for fIMTEnabled if IMT is disabled.

VTune performance analysis (comparison of two basic hotspots analyses):

screenshot

Note the time difference in `TTree::Fill()`.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi,

very nice. Can you cite a performance improvement figure in terms of real time before and after the change?

**Comment by amadio** [comment]
Sure, I will attach some figures.

**Comment by dpiparo** [comment]
even single numbers: runtime of random generation and fill before and after is more than enough :)

**Comment by amadio** [comment]
Hi Danilo, I updated the description at the top to include a comparison of two runs of basic hotspots for the master and this branch. This is for the random number generation merged with TBufferMerger. Notice that most time saved is indeed in `TTree::Fill()`.

**Comment by bbockelm** [comment]
Relevant note after discussion on Mattermost / ROOT IO meeting -

1.  This avoids construction of the IMTHelper object on the stack when IMT is disabled at compile time.  @amadio plans to do another follow-up to try and avoid the object when IMT is enabled at compile time but disabled at runtime.
2.  ~1.3s of savings is distributed over 100M `TTree::Fill` calls, which amounts to something like 13ns of savings per call.  Still worth doing, the absolute order-magnitude wasn't easily apparent to me the first time I read through the ticket.

Thanks Guilherme!

**Pull request merged**
