### PR TITLE
Improve syntax of main hist classes

### PR DESCRIPTION
**Pull request by linev**
1. Use `override` syntax
2. Use `nullptr`
3. Mark as `= delete` not implemented methods
4. Replace `Form()` by `TString::Format().Data()`
4. `using TH1::GetBinContent` in TH2 and TH3, saves method call

### CODE REVIEW

**Comment by linev** [comment]
Failures with `filemerger` will be fixed after #9934  - @pcanal or @Axel-Naumann should approve it first

**Comment by linev** [comment]
> Note: this is a partial (?) duplicate 

As I can see, #9883 is automatically generated and can be redone after merging this PR.
Most interesting here is that commit - https://github.com/root-project/root/pull/9932/commits/cbd307b1f9b0416f0b92b651af5b661e727c31a0. It improves performance of plain `GetBinContent` for TH2 and TH3

**Comment by linev** [comment]
@phsft-bot build

**Review by lmoneta — APPROVED** [review]
LGTM !
Thank you Sergei for these improvements

**Pull request merged**
