### PR TITLE
[cmake] Turn on builtin_xrootd if external xrootd not found

### PR DESCRIPTION
**Pull request by eguiraud**
The downside is that builtin_xrootd requires an internet connection. So by making users that expect ROOT + remote files to "just work" happy, we might upset users that need want a way to build ROOT offline. There is a precedent: TBB is in the exact same situation and builtin_tbb is on by default.

### CODE REVIEW

**Comment by eguiraud** [comment]
@bellenot i don't know how, but [the windows PR build](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/74676/consoleFull) seems to show that xrootd is correctly turned off even after these changes. is that enough verification for you?

**Comment by bellenot** [comment]
> @bellenot i don't know how, but [the windows PR build](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/74676/consoleFull) seems to show that xrootd is correctly turned off even after these changes. is that enough verification for you?

Well, I think xrootd is explicitly disabled by the CI script on Windows...

**Comment by eguiraud** [comment]
> Well, I think xrootd is explicitly disabled by the CI script on Windows...

so what do we do?

**Comment by bellenot** [comment]
> > Well, I think xrootd is explicitly disabled by the CI script on Windows...
> 
> so what do we do?

As I said, adding `set(xrootd_defvalue OFF)` in the `if(WIN32)` block in `RootBuildOptions.cmake` should do it. Do you want me to do a separate PR for this?

**Comment by eguiraud** [comment]
sorry it was not clear to me that you were actually asking for this change. done.

**Comment by eguiraud** [comment]
@hageboeck done (in a separate commit for easier review of the changes)

**Comment by bellenot** [comment]
> sorry it was not clear to me that you were actually asking for this change. done.

Thanks, but I was just asking if you wanted me to do it, not for you to do it... 😉  sorry for the misunderstanding...

**Pull request merged**
