### PR TITLE
Use CMAKE_BINARY_DIRECTORY/ginclude instead of /include for tmva/sofie/test

### PR DESCRIPTION
**Pull request by lmoneta**

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Review by bellenot — APPROVED** [review]

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu20.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Comment by Axel-Naumann** [comment]
Do we really need to include `onnx_proto3.pb.h` in a header of Sofie, or can that be moved to a source? In its current state we need to add that header's directory to the include paths for the library.

**Comment by lmoneta** [comment]
`onnx_proto3.pb.h` is a file defining  the onnx schema and it is automatically generated by the protobuf compiler. 
It is included by the source and not the header file. I don't understand the warning coming from the module building. I will check with Vassil

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

**Review by sitongan — APPROVED** [review]
lgtm

**Pull request merged**
