### PR TITLE
[RF] Avoid factory language in HistFactory

### PR DESCRIPTION
**Pull request by guitargeek**
The RooWorkspace factory language should not be used inside the HistFactory implementation, because each time you use `RooWorkspace::factory()`, the interpreter is called.

For very large workspaces, the excessive number of interpreter calls can crash the process, because memory allocation is growing.

This avoids the memory allocation problem in the interpreter that was reported on the forum:

https://root-forum.cern.ch/t/cling-jit-session-error-cannot-allocate-memory/56744

### CODE REVIEW

**Review by lmoneta — APPROVED** [review]
LGTM!
Thank you Jonas for this improvement in the HF

**Comment by guitargeek** [comment]
Hi @punit15sharma! HistFactory has a large userbase, and backporting a large change like this to an existing release branch is very risky. ROOT 6.32 is coming out in one month, possibly even before the next 6.30 patch release that would include the backport, so I don't think it's worth taking this risk.

So is waiting for 6.32 which will come in a few weeks a solution for you? Maybe if you're using the LCG releases, you can also easily use the LCG nightlies to bridge the time: https://root.cern/install/nightlies/

The `dev3` nightlies include the current release candidate for ROOT 6.32.

**Comment by punit15sharma** [comment]
Hi @guitargeek 
Thanks a lot for the response, and I am sorry for the delay; I think waiting for ROOT 6.32 would be better in that case. We have already started looking into the possible options with the nightlies to bridge the gap.

**Comment by JacobKempster** [comment]
Hello! I apologise for re-opening this thread.  I tried to get the release candidate for ROOT 6.32 from the latest dev3 nightly as advised but this still seems to give me 6.30/06 , can you please advise?

**Comment by guitargeek** [comment]
Did you try the `dev4` nightlies? I think they have the 6.32 release candidate.

The ROOT team doesn't support centos7 anymore. But I think the LGC packages still support this platform, at least until the summer when it goes EOL I think.

**Comment by JacobKempster** [comment]
Thanks @guitargeek ,

Setting up with ```dev4``` on centos7 still gives the 6.30 release so I assume that perhaps 6.32 is not supported for centos7, which is ok - just good to understand.

On a related note, we may have managed to still reach the limits (hitting JIT error) with our workspace building in EL9 with root 6.33, so if that is the case i'll make a new issue to see if it can be debugged

**Comment by guitargeek** [comment]
Let's ping maybe @andresailer who is responsible for LCG. Andre, is there a LCG release that provides the 6.32 release candidate on centos7?

**Comment by andresailer** [comment]
Hi @guitargeek , @JacobKempster 
Since #14958 we no longer update ROOT for centos7 in the LCG nightly branches, see also our issue tracker for LCG releases https://its.cern.ch/jira/browse/SPI-2532 .
We currently have no plans for 6.32 on CentOS7.

**Pull request merged**
