### PR TITLE
Fix TGeo units for gdml output

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
# This Pull request:
In the GDML writing there is a confusion with the use of:
TGeoManager::fgDefaultUnits  or TGeoManager::GetDefaultUnits()

-- It is used both to determine if the length unit string is defined as  "cm" or "mm".
-- At the same time this variable is used by the elements and materials to discriminate
    between the system of units.

This confusion then ultimately leads to this bug:
-- If TGeo units are ON and the GDML should be written in the G4 convention (mm)
    automatically the densities and the atomic weights go wrong.

If in TGeoManager.cxx line 302
TGeoManager::EDefaultUnits TGeoManager::fgDefaultUnits = TGeoManager::kG4Units;
is changed to:
TGeoManager::EDefaultUnits TGeoManager::fgDefaultUnits = TGeoManager::kRootUnits;

This fixes the problem, because the usage of TGeoManager::GetDefaultUnits()
when the elements/materials were created is then consistent with the GDML writing.
See:
https://root-forum.cern.ch/t/problem-with-elements-in-exported-gdml-files/46473/5

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Review by agheata — APPROVED** [review]

**Comment by ianna** [comment]
@MarkusFrankATcernch - please, see comments on cms-sw/cmsdist#7274 
With this PR merged DD4hep cannot change units to G4 ones that is a default for CMS.

**Comment by mrodozov** [comment]
it gets in this condition:

https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/DDCore/src/DetectorImp.cpp#L205-L208

which changes the value to 
https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/DDCore/src/DetectorImp.cpp#L207

DD4HEP_USE_GEANT4_UNITS if DD4Hep is built with DD4HEP_USE_GEANT4_UNITS

should we build DD4Hep with DD4HEP_USE_GEANT4_UNITS=OFF then ?

**Comment by MarkusFrankATcernch** [comment]
@mrodozov 
If you have compiled with DD4HEP_USE_GEANT4_UNITS=ON, then the condition
https://github.com/AIDASoft/DD4hep/blob/9bbe12b080ce52615251facc6f6ff5dd58a60e69/DDCore/src/DetectorImp.cpp#L205-L208

should be correct. Or do I miss here something?
An explanation for the change can be found here:
https://github.com/root-project/root/commit/bcc8bb729c23873177b9cb3e250fa000a0b59035#commitcomment-56114745

**Comment by mrodozov** [comment]
@MarkusFrankATcernch 
it's all clear now, nothing is missing. with the ROOT changes should be integrating fine.
thank you :)

**Pull request merged**
