### PR TITLE
Hadd improve help message and Doxygen documentation

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:
https://github.com/root-project/root/issues/6438

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by eguiraud** [comment]
Thank you @ferdymercury ! I think this is really for @pcanal and @couet to review/approve -- removing myself as reviewer.

**Comment by guitargeek** [comment]
I assigned the PR to @couet because it relates to documentation.

**Review by couet — APPROVED** [review]
LGTM

**Comment by couet** [comment]
I am not the author of hadd. I dunno really the options.

**Comment by ferdymercury** [comment]
maybe @pcanal ?

**Comment by vepadulano** [comment]
> @vepadulano Should I rebase?

Hi! Sorry for the late reply, I think this PR could be merged, if you can rebase then we can proceed. Thank you so much!

**Comment by ferdymercury** [comment]
> 
> Hi! Sorry for the late reply, I think this PR could be merged, if you can rebase then we can proceed. Thank you so much!

Rebased, thanks :)

**Comment by ferdymercury** [comment]
@vepadulano is the fedora38 fail related to this PR ?

**Review by vepadulano — APPROVED** [review]
Failing tests are unrelated,  thanks a lot!

**Pull request merged**
