### PR TITLE
WIP: Minuit2 MPI move to C bindings

### PR DESCRIPTION
**Pull request by henryiii**
This was applied from a .patch from the PR GooFit/Minuit2#1 from @gudlaugu. All credit/blame should be directed to @gudlaugu, I'm just the middleman. This patch is useful because MPI 3 no longer even includes support for the C++ bindings.

I've added one small obvious fix to warnings, but otherwise all credit/blame should be directed to @gudlaugu.

Original discussion in #1689.

### CODE REVIEW

**Comment by amadio** [comment]
@henryiii Have you tried using the code after the patch? I remember seeing extra test failures with this patch compared to what we currently have (https://github.com/root-project/root/pull/1689#issuecomment-380143670).

**Comment by henryiii** [comment]
Not too much, I was mostly the middle man for this patch. I did try it briefly and saw some issues, but also got issues with master.

**Comment by lmoneta** [comment]
I agree with Henryjj. We should keep this as a base for start working and fixing the MPI bindings. 
Until then I think we should keep this PR open

**Comment by lmoneta** [comment]
Since no more work has been done on the MPI bindings, I close this PR for the time being

**Pull request closed without merging**
