### PR TITLE
[TMVA][SOFIE] Add new operators: MaxPool,AveragePool, Add, Reshape (Flattten) and faster Conv

### PR DESCRIPTION
**Pull request by lmoneta**
This Pull requests adds new Pooling operators: MAxPool, AveragePool, GlobalAveragePool, Add, and Flatten

In addition it provides a new faster implementation of ROPerator_COnv using a faster im2col inplementation.

After this PR Sofie is able to parse Resnet like models such as resnet18 (see https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet18-v1-7.onnx )

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by sitongan** [comment]
Looks good to me for the new operators. Thank you very much Lorenzo for adding these ones.

**Review by sitongan — APPROVED** [review]

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

**Pull request merged**
