### PR TITLE
[RF] Test schema evolution of RooDataHist from version 5 and 6

### PR DESCRIPTION
**Pull request by guitargeek**
Extend the RooDataHist tests to also validate the schema evolution
from version 5 and version 6.

Version 6 is the current version, so the `dataHistv6_ref.root` reference
file was produced with ROOT master. Version 5 was used in ROOT 6.24,
which was used to produce the `dataHistv5_ref.root` reference file.

The version 6 reference file is a little bit smaller than the version 5 file, as the `_realVars` member was removed with version 6.

A nice aspect of the version 6 update is also that it's backwards compatible. The `initialize()` function is called in the [custom streamer](https://github.com/root-project/root/blob/v6-24-00-patches/roofit/roofitcore/src/RooDataHist.cxx#L1995) of RooDataHist, so if the `_realVars` member is missing in the ROOT file it will still be initialized.

This fixes issue https://github.com/root-project/root/issues/8037.

### CODE REVIEW

**Review by hageboeck — APPROVED** [review]
LGTM! 👍

**Comment by hageboeck** [comment]
@guitargeek Maybe commit a comment on how to create the reference file above the test. Sorry that I didn't do that already.

**Comment by guitargeek** [comment]
> @guitargeek Maybe commit a comment on how to create the reference file above the test. Sorry that I didn't do that already.

The way I did this was simply to open the v4 file with a newer ROOT version, use the copy constructor of RooDataHist and save the copied object. Is this the way that you would document, or is there an easier way?

**Comment by hageboeck** [comment]
> The way I did this was simply to open the v4 file with a newer ROOT version, use the copy constructor of RooDataHist and save the copied object. Is this the way that you would document, or is there an easier way?

Ah, right. That will work. I thought you re-engineered that RooDataHist to document it in the style of:
https://github.com/root-project/root/blob/ef483dd32765470c702d72adf387d68663e28842/roofit/roofitcore/test/testProxiesAndCategories.cxx#L59-L80

In this case, it was probably this, but I don't remember:
https://github.com/root-project/root/blob/ef483dd32765470c702d72adf387d68663e28842/roofit/roofitcore/test/testRooDataHist.cxx#L242-L248

**Pull request merged**
