### PR TITLE
[DF] Fix 32bit failures

### PR DESCRIPTION
**Pull request by bluehood**
This works around an ABI compatibility issue between cling and gcc
on 32bit machines in which they disagree in the way arguments should
be passed to such a function.

### CODE REVIEW

**Comment by amadio** [comment]
@phsft-bot just on slc6-i686/gcc49

**Comment by bluehood** [comment]
@phsft-bot build just on slc6-i686/gcc49

**Comment by amadio** [comment]
So... looks like it's not working.

**Comment by Axel-Naumann** [comment]
"it" being this PR, or "it" being "ph-sft build on 32bit"?

**Comment by amadio** [comment]
The command given to the bot

**Pull request merged**
