### PR TITLE
[graf2d] Added additional marker styles with wider lines

### PR DESCRIPTION
**Pull request by Triple-S**
Up to now there was no way to draw open marker symbols or marker symbols consisting of lines with higher linewidths than the default 1.
I looked into several ways to implement this feature and at the end just added additional marker smbols above the current maximum of 50 with wider lines as proposed by @couet in #4721 

This example plot demonstrates the feature:
c2

Please note that I tested the feature as far as I could. However, I don't have a ROOT installation on Windows or a Mac, so I could not test the corresponding implementations which is why I consider further tests (and especially a build test) mandatory.

### CODE REVIEW

**Comment by Triple-S** [comment]
Could an admin please start a build of this PR to check whether it compiles and all tests pass?

**Comment by couet** [comment]
It starts automatically

**Comment by couet** [comment]
Hi Simon, On an other matter can you send me you email at olivier.couet@cern.ch. I have an issue with TGraphMultiErrors

**Comment by Triple-S** [comment]
> It starts automatically

I was refering to the Jenkins build, not the Travis-CI.
As far as I know it has to be started manually with "@phsft-bot build" but I don't have the permissions for it.

P.S.: I sent you my E-Mail adress.

**Comment by couet** [comment]
@phsft-bot build

**Comment by Triple-S** [comment]
I just resolved the conflicts caused by the merge of #4762

**Comment by Triple-S** [comment]
> This PR is fine for me. It works very well on my Mac !May be one thing to be changed is what we discussed offline about GetMarkerStyleBase ?

I just committed the changes.

**Comment by couet** [comment]
Now merged. Thanks !!

**Pull request merged**
