### PR TITLE
[buildsystem] Fixing path to source files for ROOTVecOps library

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by amadio** [comment]
Hi Oksana, `[Modulariz.]` looks a bit awkward. I'd remove, as the commit message is clear without it. If you want to keep it, maybe consider not abbreviating. We know you are working on modularization, but someone that doesn't know might be more confused than helped by the tag.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
Looks like infrastructure failed yesterday, so I'm restarting the build.

**Comment by amadio** [comment]
Hi Oksana, it seems the problem may be the branch for this PR didn't get mirrored. Could you please push again? I just started another PR before this and that PR works without problems.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
And what we've learned from the past 15 years: "modularization" means 100 different things, and not the same for any pair of people talking about it :-) Which is why I use the term "lazy building" for your "build parts of ROOT later" and you could use "libdep" or "builddep" for reducing or fixing/formalizing the library or build dependencies. Or "incldep" for header/including dependencies. Just a couple of ideas, I'm not suggesting that you should follow them (this is not a PR review)

**Pull request merged**
