### PR TITLE
[cmake] fix cpack for current master

### PR DESCRIPTION
**Pull request by linev**
* provide proper list of pythonization files for RootFit
* avoid empty string with extra . in produce file name

### CODE REVIEW

**Review by bellenot — APPROVED** [review]
Fine with me for the `CPack` part, but I'll let @etejedor  review the `pythonisation` part

**Comment by guitargeek** [comment]
Hi! The list of RooFit pythonization files is growing quickly thanks to @Harshalzzzzzzz. Is it possible to grep for all files in the `pythonization` directory, so we don't need to manually update the CMakeLists.txt every time? Also @etejedor's opinion is for sure valuable here.

**Comment by linev** [comment]
Yes, there is cmake command to get list of all files in directory.
If it fine, I can modify PR

**Comment by bellenot** [comment]
See https://cmake.org/cmake/help/latest/command/file.html#glob-recurse

**Comment by linev** [comment]
Problem with files globing - it takes alll files. 
But depending on compiled ROOT components, some pythonization files should be excluded.
It is already happens with `dataframe` component here.
Some time ago we redo all c++ cmake files to avoid files globing - I guess here we also should avoid it.

**Comment by linev** [comment]
I add https://github.com/root-project/root/pull/8509/commits/55d397ceeb02d2749343bf654f04d51e8824cab3 to follow naming convention for cmake

**Comment by etejedor** [comment]
I'd prefer to be specific and add an entry for every file (even if there are many and others will be added), as @linev explained this gives more control over what is added.

**Pull request merged**
