### PR TITLE
Zlib cleanup (QAT)

### PR DESCRIPTION
**Pull request by davidlt**
These 3 small patches I am using for ROOT + Intel QuickAssist Technology (QAT). QAT provides HW-accelerated (de)compression and crypto (incl. hashing). For easy integration Intel provides zlib-shim and openssl-shim, support the most common interfaces (but not everything). Note, that QAT also has software fallback mechanism.

More details are available in the commit messages.

### CODE REVIEW

**Comment by pcanal** [comment]
@davidlt Could you update to apply the clang-format recommendation (here it seems simply to use 3 characters for indentation rather than 2).

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by davidlt** [comment]
Btw, for anyone who is using Fedora to ROOT development. Sadly `git-clang-format` is explicitly removed from Clang package. I already created a ticket asking to have `git-clang-format` in future Clang builds. Anyone can copy `git-clang-format` from upstream and just put it into your `PATH`.

**Pull request merged**
