### PR TITLE
Fail if CMAKE_SYSTEM_PROCESSOR is not recognised

### PR DESCRIPTION
**Pull request by chrisburr**
Currently if `CMAKE_SYSTEM_PROCESSOR` is not set ROOT silently falls back to returning `-m32` in `root-config --cflags` among other things. This can easily happen when cross-compiling and caused an issue in the first build of 6.18.00 for Conda (see https://github.com/conda-forge/root-feedstock/issues/41).

I think it would be safer to fail immediately if the architecture is not recognised rather than allowing this to be missed and this is the approach used [elsewhere](https://boringssl.googlesource.com/boringssl/+/2272/CMakeLists.txt).

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by bellenot** [comment]
@chrisburr please fork also roottest in order to fix the failing build on Windows

**Comment by chrisburr** [comment]
Done

**Comment by amadio** [comment]
@phsft-bot build just on windows10/default

**Pull request merged**
