### PR TITLE
Removed cuda flag

### PR DESCRIPTION
**Pull request by reikdas**
TMVA GPU features are enabled only when both the cuda and tmva-gpu flags are enabled. These flags are not used anywhere else. It looks like the cuda flag is redundant in this case. 

Related forum post - https://root-forum.cern.ch/t/feature-request-enable-cuda-if-detected/32764

### CODE REVIEW

**Comment by reikdas** [comment]
Enabled the cuda flag if the tmva-gpu flag is enabled with regards to this forum post - https://root-forum.cern.ch/t/feature-request-enable-cuda-if-detected/32764/4

**Comment by amadio** [comment]
The underlying problem has been fixed on master, so this is not necessary.

**Comment by reikdas** [comment]
As per master, the tmva-gpu flag does not work unless the cuda flag is also enabled(enabling the tmva-gpu flag is then redundant because enabling the cuda flag enables the tmva-gpu flag by default). Do we want to keep it like that?

**Comment by amadio** [comment]
This behavior will be fixed today. The file `tmva/tmva/CMakeLists.txt` is using `if(CUDA_FOUND)`, so that will have to change to `tmva-gpu` instead, among other things.

**Pull request closed without merging**
