### PR TITLE
add fOverwrite option to Snapshot

### PR DESCRIPTION
**Pull request by goi42**
When one updates a file using `Snapshot`, one ends up with multiple cycles:
```python
In [10]: f.hi.ls()
TDirectoryFile*		hi	hi
 KEY: TTree	there;2	there
 KEY: TTree	there;1	there
```
This adds the `fOverwrite` option to the `RSnapshotOptions` class to overwrite an existing `TTree`. First mentioned in the forum [here](https://root-forum.cern.ch/t/no-way-to-overwrite-using-snapshot/37936).

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by bluehood** [comment]
Hi @goi42,
thank you for the PR! Do I understand correctly the usecase -- that you have a file with many trees/objects inside and you want to rewrite just one of them?

Namecycles are typically harmless, and the one with the highest index is the "true" object you get when you extract it from the file. Why don't you want namecycles? Is the problem that the data retrieved after a sequence of Snapshots like these not what you expect? Can you provide a reproducer in the form of a unit test added to dataframe's gtests (under `tree/dataframe/test`).

It also looks like these build errors are due to the PR -- it seems like the changes are not backward-compatible..?

**Comment by bellenot** [comment]
@goi42 please fork also [roottest](https://github.com/root-project/roottest) in order to prevent the failure on `windows10/cxx14`

**Comment by goi42** [comment]
@bluehood One might want to overwrite for aesthetic reasons (so that the file is not polluted with outdated cycles) or to save a little memory:
```python
In [1]: import ROOT

In [2]: df = ROOT.RDataFrame(10).Define('e', 'rdfentry_')

In [3]: df.Snapshot('tUpdate', 'fUpdate.root')
Out[3]: <ROOT.ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > object at 0x7f9a564e9fe0>

In [4]: snapopts = ROOT.RDF.RSnapshotOptions()

In [5]: snapopts.fMode = 'UPDATE'

In [6]: df.Snapshot('tUpdate', 'fUpdate.root', '', snapopts)
Out[6]: <ROOT.ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > object at 0x7f9a574a3c80>

In [7]: df.Snapshot('tOverwrite', 'fOverwrite.root')
Out[7]: <ROOT.ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > object at 0x7f9a576822d0>

In [8]: snapopts.fOverwrite = True

In [9]: df.Snapshot('tOverwrite', 'fOverwrite.root', '', snapopts)
Out[9]: <ROOT.ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > object at 0x7f9a58142590>
```
```bash
$ ls -l f*root
-rw-r--r--  1 michael  staff   5.9K Feb 13 11:20 fOverwrite.root
-rw-r--r--  1 michael  staff   6.0K Feb 13 11:19 fUpdate.root
```
Test coming soon.

**Comment by goi42** [comment]
@bluehood I added tests, as requested. There is currently no test for the multithreading case, however, due to a bug reported [here](https://root-forum.cern.ch/t/snapshot-fails-to-update-ttree-if-multithreading-enabled/37961). Once that is resolved, I can add in the MT test.

**Comment by goi42** [comment]
JIRA ticket [here](https://sft.its.cern.ch/jira/plugins/servlet/mobile#issue/ROOT-10573).

**Comment by bluehood** [comment]
Hi, sorry for the delay but I need to spend some time on this, probably next week. I have to figure out whether the MT case is fixable with reasonable effort, and if not we need to add diagnostics to warn users.

**Comment by goi42** [comment]
@bluehood Currently, Update does not work _at all_ with MT, and it is possible for a user to get the wrong output without an error ever being thrown. This is independent of this merge request and effectively breaks ROOT for this use case, hence the "critical" priority on the [JIRA task](https://sft.its.cern.ch/jira/plugins/servlet/mobile#issue/ROOT-10573). It would probably be best to resolve the JIRA task before dealing with this MR.

**Comment by bluehood** [comment]
Agreed! I'll make sure that is taken care of first, at the very least by throwing an exception if `fUpdate` is used with a multi-thread RDF. Again I am not sure that it can work at all, I need to go down the rabbit hole.

**Comment by eguiraud** [comment]
Given the planned resolution of [ROOT-10573](https://sft.its.cern.ch/jira/plugins/servlet/mobile#issue/ROOT-10573), implemented in #5193 , I don't think this is needed anymore?

**Comment by goi42** [comment]
Yes, you are right. Thanks for all your work on this @eguiraud.

**Pull request closed without merging**
