### PR TITLE
Multiclass RandomForest

### PR DESCRIPTION
**Pull request by satyarth934**
Implementation of Multiclass RandomForest.

### CODE REVIEW

**Comment by satyarth934** [comment]
May I please know as to what kinds of tests are these? It works fine on my machine.

**Comment by vgvassilev** [comment]
If you click on "Details" you will see.

**Comment by satyarth934** [comment]
Hi @vgvassilev ,
Following are the kinds of additional lines that I see added the original code when I clicked [Details](https://travis-ci.org/root-project/root/builds/212649006).

diff --git a/tmva/pymva/src/MethodPyRFOneVsRest.cxx b/tmva/pymva/src/MethodPyRFOneVsRest.cxx
index b1113d1..9b41b39 100644
--- a/tmva/pymva/src/MethodPyRFOneVsRest.cxx
+++ b/tmva/pymva/src/MethodPyRFOneVsRest.cxx
@@ -16,7 +16,7 @@

Similar lines are added all over.
Rest of the code looks like more like an output of `git diff`.

I am unable to understand, how to interpret these additional added lines and how to understand my mistakes.

**Comment by vgvassilev** [comment]
@phsft-bot build!

@satyarth934, it seems you found your way around this. The idea of the diff is that you can apply it without having clang format. You just open the log file in plain text copy the diff, store it on your machine and apply it with git apply.

**Comment by satyarth934** [comment]
@vgvassilev , Thanks.
Looks fine now.

**Comment by omazapa** [comment]
Dear @satyarth934 
This implementation is not under the architecture and design of TMVA, you dont need to create a new class to add support for multiclass in RandomForest for PyMVA.  
In the same class MethodPyRandomForest we must support regression, two class classification, multiclass-classification and variable ranking.
You can see how @stwunsch give support for multiclass-classification in AdaBoost by example 
https://github.com/root-project/root/pull/343/commits/a35fdf63205e75ed7ad7affff502c0a83afb94bd
and may you want to rewrite you code according to TMVA design.

Cheers
Omar.

**Pull request closed without merging**
