### PR TITLE
Add Python ML packages in requirements

### PR DESCRIPTION
**Pull request by lmoneta**
This PR is for testing on 6.28 in the Linux CI the using of Python ML tools in TMVA

### CODE REVIEW

**Comment by hahnjo** [comment]
This does not match what is in `requirements.txt` in the `master` branch; in particular the built Linux container images don't have `tensorflow` and `torch` installed. For that reason, all v6.28 builds are currently red (FYI @martamaja10)

**Comment by lmoneta** [comment]
They are red, it is expected because the installation of the package in the containers should happen the next day.
We need to see the results tomorrow

**Comment by hahnjo** [comment]
Installation in the containers happens from `requirements.txt` present in `master`. As of now, that one doesn't have entries for `tensorflow` and `torch` (that's why I called these two out) and the result will be the same as today.

**Comment by martamaja10** [comment]
the nightly built of 6.28 is still red today for the same reasons as yesterday

**Pull request merged**
