### PR TITLE
Fix updating of GED editors from EVE GL Viewer

### PR DESCRIPTION
**Pull request by osschar**
Also sanitize setting of TEveArrow parameters and propagation of bounding-box updates to GL viewer.

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build!

**Comment by bellenot** [comment]
Matevz, could you fix the errors reported by Travis? (clang-format and clang-tidy) Thanks! (I don't know why the Jenkins CI builds are failing...)

**Comment by osschar** [comment]
Sorry, I don't get this ... what I'm supposed to fix here? :) The logs don't seem to contain anything useful.

**Comment by bellenot** [comment]
If you look carefully, you'll see in the [clang-format log](https://travis-ci.org/root-project/root/jobs/231041859), a diff, starting from line 360.
(you can also run clang-format on your side)
And in the [clang-tidy log](https://travis-ci.org/root-project/root/jobs/231041860), an explanation of the issue, starting from line 3598.

**Comment by osschar** [comment]
OK, so I got it right :)

I'm not going to change formatting, it's consistent with the rest of eve/gl and what it's proposing to do is adding 4 lines 8 times with final effect of decreasing readability of the code.

The tidy errors are coming from TMath ...

**Comment by vgvassilev** [comment]
It does not follow RROTs coding conventions. It may increase the readability but decreases the debug-ability of this code.

The clang-tidy seems a real issue. TEveVector relies on memory alignment for fX, fY, fZ to be continuous in memory because Arr() returns &fX and then we access the others by indices.

**Comment by osschar** [comment]
Hmmh, I'm pretty sure c++ standard guarantees the members to be contiguous. I'll fix that ... there is a Cross() in TEveVector, probably I added it at some later time :)

You realize this is only picking up things that have been there since ~ forever ... nothing reported here has been changed by my commit. So I blame it on ex-CERN employees ...

**Comment by bellenot** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@osschar, C++ didn't have wording for class members. [C++ draft](http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/n4618.pdf), 9.2 [class.mem] 17) "Non-static data members of a (non-union) class with the same access control (Clause 11) are allocated so that later members have higher addresses within a class object. The order of allocation of non-static data members with different access control is unspecified (Clause 11). Implementation alignment requirements might cause two adjacent members not to be allocated immediately after each other; so might requirements for space for managing virtual functions (10.3) and virtual base classes (10.1)."

This means they indeed get higher addresses but are not guaranteed to be continuous in memory. The committed fix is just hiding the bug from the clang-tidy.

**Comment by bellenot** [comment]
Beside the clang-tidy issue, I'm fine with the coding style (i.e. You can let the code as it is)

**Comment by bellenot** [comment]
So I'm going to merge it, but be aware that next time it will complain again, and the day we run clang-format on the whole ROOT code base, one will have to fix it anyway.
And we would appreciate if next time you follow the coding conventions...

**Comment by bellenot** [comment]
Merged. Thanks!

**Comment by osschar** [comment]
Nono, thank you, B! :)

**Pull request merged**
