### PR TITLE
Move v7 files one level up excluing v7/ subfolder

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build with flags -DCMAKE_CXX_STANDARD=14 -Droot7=on

**Comment by amadio** [comment]
There are many special cases for ROOT 7 in the build system. If you are going to move the source files, please make sure to fix all those special cases as well. Search for "v7" in [RootMacros.cmake](https://github.com/root-project/root/blob/master/cmake/modules/RootMacros.cmake), for example.

**Comment by linev** [comment]
@amadio, thanks for tip, I will try to check it

**Comment by linev** [comment]
@amadio 
As I could see, in all places in RootMacros.cmake "v7" appears to handle situation when v7 and non-v7 classes are mixed in same library. In normal situation (only-v7 or only-nonv7 classes) all these workarounds not required. After this PR only place where such mix will remain - is core/base. 
But in "core/base" one could organize v7 files differently and fully avoid such workaround in cmake.

**Pull request merged**
