### PR TITLE
Remove special handling of gInterpreter in pyroot_experimental

### PR DESCRIPTION
**Pull request by linev**
Now all globals in ROOT are consistent.

### CODE REVIEW

**Comment by etejedor** [comment]
As discussed by e-mail, this needs to be a PR to the cppyy-backend repository:
https://bitbucket.org/wlav/cppyy-backend

**Comment by linev** [comment]
@etejedor Can you create PR for cppyy-backend repository yourself?

**Comment by etejedor** [comment]
@linev I believe it is much better if you do it. You made the changes, you know what they are about, and therefore you will be in a better position to discuss them with @wlav .

**Comment by linev** [comment]
https://bitbucket.org/wlav/cppyy-backend/pull-requests/17

**Comment by etejedor** [comment]
Thank you @linev , let's continue the discussion there.

**Comment by etejedor** [comment]
@phsft-bot build with flags -Dpyroot_experimental=ON

**Pull request closed without merging**
