### PR TITLE
[DF] Fix memleaks of dataframe nodes kept alive for jitted code 

### PR DESCRIPTION
**Pull request by eguiraud**
Before this patch, if a RLoopManager went out of scope before running
its event loop (a rare occurrence, but indeed possible, especially in
interactive sessions), we were leaking certain weak_ptrs and shared_ptrs
to components of the computation graph, that were meant to be used by
lazily jitted code that was never actually jitted in the end.

With this change, when _any_ RLoopManager runs the event loop, we
trigger execution of _all_ jitted code that was registered, even if
it was registered by an RLoopManager that is now out of scope. In the
latter case, the code only performs clean-up of the heap-allocated
weak_ptrs and shared_ptrs and exits. We still "leak" in the odd case
in which RDF jitted code is registered but the application never actually
triggers any RDF event loops, in which case the code to be lazily jitted
remains in the pipeline until the end of the application, and parts of
the computation graph are kept alive indefinitely by heap-allocated shared_ptrs.

For this to work, we need to detect when compiled objects went out of scope and we don't actually have to run the jitted code but just perform the clean-up, so we switch from heap-allocated shared_ptrs to heap-allocated weak_ptrs for those objects.

### CODE REVIEW

**Comment by eguiraud** [comment]
The failure in `dataframe_interface` is bad, investigating.

**Comment by hageboeck** [comment]
I started looking, but the first thing I noticed is that allocating weak_ptrs on heap, and making somebody responsible for deleting them seems to defy the point. Maybe I didn't get the logic yet, but wouldn't something like this be easier?
- Somebody needs code jitted. Makes a shared_ptr to it and holds it.
- Jitter gets a weak_ptr observing the shared_ptr.
- Common code is shared using shared_ptr.
- When jitter starts, it tries to lock weak_ptr.
 -- Success: Jit the code
 -- Failure: Throw away weak_ptr - nobody seems to need the code.

Can give it a second try to understand the code if that model doesn't work.

**Comment by eguiraud** [comment]
Hi Stephan, that's exactly how it works, and to pass a weak_ptr from compiled code to lazily jitted code, I have to put it on the heap and pass the address of the weak_ptr to the lazily jitted code.

**Comment by eguiraud** [comment]
Tests are green (at least on my machine, let's see if jenkins agrees) but valgrind is still not happy, to be investigated.

**Comment by eguiraud** [comment]
A bisect revealed that the valgrind errors were introduced by previous changes. They will be resolved by a different PR. Will merge this in the meanwhile.

**Pull request merged**
