### PR TITLE
[RF] Enable AD code-gen test for RooFit.

### PR DESCRIPTION
**Pull request by grimmmyshini**
Enable a previously disabled test to fix it if it still fails.

### CODE REVIEW

**Comment by grimmmyshini** [comment]
@phsft-bot build!

**Comment by grimmmyshini** [comment]
@phsft-bot build only on ubuntu18.04/nortcxxmod.

**Comment by grimmmyshini** [comment]
@phsft-bot build just on ubuntu18.04/nortcxxmod.

**Comment by grimmmyshini** [comment]
@phsft-bot build just on ubuntu18.04/nortcxxmod

**Comment by grimmmyshini** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/nortcxxmod

**Comment by grimmmyshini** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/nortcxxmod

**Comment by grimmmyshini** [comment]
@phsft-bot build just on ROOT-ubuntu18.04/nortcxxmod

**Review by guitargeek — APPROVED** [review]
Thank you very much for making this test work! Now we can continue developing the code generation engine based from this.

**Comment by guitargeek** [comment]
The failing unit test is unrelated.

**Pull request merged**
