### PR TITLE
[Math] Make tolerance less strict on matrix inversion tests

### PR DESCRIPTION
**Pull request by amadio**
- Improve diagnostic output of compare() function
- Test inverted matrix times original against identity using
  element by element comparison, and use less strict tolerance
  to account for innacuracies due to matrix inversion

*Note: I am still running this test many times to make sure it doesn't fail anymore. Please wait to merge until after the runs are finished.*

### CODE REVIEW

**Comment by amadio** [comment]
This code now has run more than 6000 times for me without failure. I believe it is safe to merge.

**Comment by vgvassilev** [comment]
Could you rebase, clang-format issue should be fixed now.

**Comment by amadio** [comment]
Sure, I will do that.

**Comment by amadio** [comment]
Since the potential for conflicts is small, I just formatted the whole test file. I hope that's ok.

**Comment by amadio** [comment]
I increased tolerance to 50000 ulps to be really safe, although 7300 runs went fine for 10000.
This comes down to a tolerance of approximately `1.1e-11 * x` for double, and `5.9e-03 * x` for float.
I did see errors of  ~0.0015x for float, so decreasing the tolerance may lead to the test failing again.

**Comment by vgvassilev** [comment]
Testing clang-tidy, sorry for the noise.

**Comment by martinmine** [comment]
@phsft-bot build

**Comment by martinmine** [comment]
@phsft-bot build!

**Pull request merged**
