### PR TITLE
Turn bundled afterimage ON by default and deprecate option

### PR DESCRIPTION
**Pull request by ferdymercury**
# This Pull request:

## Changes or fixes:

Use always bundled afterimage which contains many fixes that the obsolete upstream version does not (unmaintained package)

This is an exception of the general rule introduced by @amadio on https://github.com/root-project/root/commit/2b3250dc2a9cd828f6c8e398e69ecde0e1412111

## Checklist:

- [ ] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes https://github.com/root-project/root/issues/14247

### CODE REVIEW

**Comment by amadio** [comment]
Commenting just to document my agreement. As mentioned in #14247 by Olivier, the libafterimage in ROOT is patched, the upstream version is no longer in development since a long time. The version in ROOT is actually the better maintained version, so there are certain things that don't work with an external libafterimage. It's better to just drop the option altogether and only use the builtin one, like how it's done for the triangulation package, which has been recently updated.

**Review by couet — APPROVED** [review]
LGTM.
But as @amadio said, may-be it is better to completely remove this option?

**Comment by bellenot** [comment]
See also https://github.com/root-project/root/pull/14396

**Comment by vepadulano** [comment]
I agree with @couet , the better alternative would be to simply remove the option from cmake and always bundle libafterimage

**Comment by ferdymercury** [comment]
Suggestion: it could be done in two steps, first setting this to ON always and marking it as deprecated, and then removing the option completely.

**Comment by dpiparo** [comment]
I agree with what was written above (and mentioned here https://github.com/root-project/root/pull/14396#pullrequestreview-1836089909) Why offering the option if we know it's broken?

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
Let's try to merge this PR, I can't see the Jenkins output anymore so I restarted a build. Indeed deprecating a build option before removing it is our usual approach, so we can stick with it :+1:

**Comment by ferdymercury** [comment]
Thanks! Ok, if this gets merged, we'll have to address https://github.com/root-project/root/issues/14439

**Comment by vepadulano** [comment]
Thanks for bringing it up. Do we want this change to land also in 6.30? I didn't notice your release notes are for 6.30, I would have imagined this only goes in 6.32. In any case, the release note changes should also be written to 6.32

**Comment by vepadulano** [comment]
> I thought deprecation in 6.30 and removal 6.32, but whatever you think is best

I see more clearly what you were trying to do now. In that case I will have to say I don't agree. We cannot deprecate a feature and backport the deprecation of the feature to an already released branch. What we can do is to deprecate the build option for 6.32 and then remove it in 6.34 :+1: Sorry for my confusion :)

**Comment by ferdymercury** [comment]
> > I thought deprecation in 6.30 and removal 6.32, but whatever you think is best
> 
> I see more clearly what you were trying to do now. In that case I will have to say I don't agree. We cannot deprecate a feature and backport the deprecation of the feature to an already released branch. What we can do is to deprecate the build option for 6.32 and then remove it in 6.34 👍 Sorry for my confusion :)

Your plan sounds good to me, too. I was just thinking of backporting the deprecation because this option is broken from the very beginning. So just for speeding up.

**Comment by ferdymercury** [comment]
Rebased and now only changing 6.32 rel-notes

**Review by vepadulano — APPROVED** [review]
LGTM Thank you!

**Pull request merged**
