### PR TITLE
Use in Jupyter JSROOT from ROOT distribution ROOT-10116

### PR DESCRIPTION
**Pull request by linev**
This is try to use Jupyter static location for JSROOT files.
Should be tested

### CODE REVIEW

**Comment by linev** [comment]
@etejedor Can you check this PR?
On my machine ipython notebook does not work - I trying to use python3.
Maybe I could try python2 for that.

**Comment by etejedor** [comment]
I also get the error:
```
[E 14:44:59.024 NotebookApp] Exception while loading config file /home/etejedor/.rootnb/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/home/etejedor/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/etejedor/.local/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/etejedor/.local/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/etejedor/.local/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/home/etejedor/.rootnb/jupyter_notebook_config.py", line 9, in <module>
        c.NotebookApp.extra_static_paths = ['%s'] % jsrootsys
    TypeError: unsupported operand type(s) for %: 'list' and 'str'
```
The string substitution is not done properly, the % operator needs to be inside the square brackets.

**Comment by linev** [comment]
> The string substitution is not done properly, the % operator needs to be inside the square brackets.

@etejedor Can you try this? I do not have system where ipython notebooks runs.
Once server is up, you should have access to JSROOT files via:
http://server.url:port/static/scripts/JSRootCore.js

**Comment by linev** [comment]
@etejedor
Now it works for me. 
But there is another problem.
```
c.NotebookApp.ip = '*'
```
This does not work on my machine. 
If I replace address by hand to 127.0.0.1, then notebook starts and I can verify my changes.
Should we provide something like:
```
root --notebook --ip=localhost
```

**Comment by etejedor** [comment]
The `NotebookApp.ip = '*'` failure is a bug in older versions of Jupyter:
https://github.com/jupyter/notebook/pull/4139
Moving to a new version should fix the issue.

**Comment by linev** [comment]
> Moving to a new version should fix the issue.

I have:
```
% jupyter-notebook --version                                                                                                                                                            5.7.8
```
Is it old?

**Comment by linev** [comment]
Seems to be, fix in jupyter is not backported to version 5.7.x and there is still no 5.8 release.
I guess, we should provide some reasonable solution for users like me :)

**Comment by linev** [comment]
@etejedor I could propose PR with "--ip=value" argument (and may be some others).

**Comment by linev** [comment]
@etejedor Finally, this PR. 
It will work for any ROOT installation, while any ROOT ships correspondent JSROOT version.
Use of central web-server is dangerous, while not all ROOT versions can be covered by same JSROOT.

Unfortunately, I cannot make it optional - this will require more fundamental changes.

**Pull request merged**
