### PR TITLE
[cmake] fix escape characters in regex for header folders #7009

### LINKED ISSUE #7009: CMake fails when there is a '+' in the source directory.  It may have problems with other REGEX characters.
- [ x] Checked for duplicates

Root version: 6.22/06
OS: Linux Debian Buster
Compiler: GCC 8.3.0

CMake fails when there is a “+” in ${CMAKE_SOURCE_DIR}. I suspect any special regular expression character would cause a problem.

The problem can be reproduced in a debian:buster-slim docker image with the following commands:

`$ apt -y update && apt -y upgrade && apt -y install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python  libmariadb-dev  gfortran libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev  libfftw3-dev libcfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev libqt4-dev  libssl-dev git python3 python3-dev`                                               

`$ git clone --branch=v6-22-06 --depth=1 https://github.com/root-project/root.git root/root_src+tag`

`$ mkdir root/root_build && cd root/root_build`

`$ cmake -DCMAKE_CXX_STANDARD=11 -Druntime_cxxmodules=OFF  -Dthread=ON -Dshadowpw=ON -Dpythia8=ON -Dr=ON -Dminuit2=ON -Dmathmore=ON -Ddataframe=ON -Ddcache=ON -Dfortran=ON -Dgfal=ON -Dgsl_shared=ON -Dgviz=ON -Dmysql=ON -Dodbc=ON -Dopengl=ON -Dpgsql=ON -Dsoversion=ON -Dtmva-rmva=ON -Dunuran=ON -Dvmc=ON -Dxrootd=ON -Dbuiltin_xrootd=ON -Dbuiltin_gsl=OFF -Dgnuinstall=ON -Dimt=OFF -Ddavix=ON -Dmemstat=ON -Dbuiltin_vdt=OFF -Dvdt=ON -Dbuiltin_llvm=ON -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 ../root_src+tag`

CMake will fail trying to bulid the MultiProc dictionary.

I think the culprit is is in cmake/modules/RootMacros.cmake:301

`if(${dir} MATCHES "^${CMAKE_SOURCE_DIR}")`

It builds a regex out of $CMAKE_SOURCE_DIR without handling special characters.

### PR DESCRIPTION
**Pull request by SpectreVert**
If `CMAKE_SOURCE_DIR` contained a special regex character it would not be properly matched against header folders and  prevent relevant paths from being added into the `headerdirs` array.

`CMAKE_SOURCE_DIR` is now replaced by a temporary copy where special characters have been escaped.

### CODE REVIEW

**Review by oshadura — COMMENTED** [review]
@SpectreVert could you please fix a commit message with explanation what actually #7009 issue was about?  @Axel-Naumann could you please take a second look (my regex skills are still improving)?

**Comment by Axel-Naumann** [comment]
Can we not do a straight string comparison instead of a regex match with prior escaping?

**Comment by SpectreVert** [comment]
@Axel-Naumann would something like this be suitable? It's technically not the same but it works and fixes #7009

 I've noticed a few other occurences of the regex escaping/matching sequence that could be patched in a similar fashion.

**Comment by Axel-Naumann** [comment]
Hmm no the question we want to be asking is not "does the directory exist" but "is that directory the source directory". I was proposing the use of [`if( ... STREQUAL ...)`](https://cmake.org/cmake/help/latest/command/if.html#strequal)

**Comment by SpectreVert** [comment]
As the regex match was done with a prefix `^` and without a trailing `$` I think this is more of a "does this directory live in the `${CMAKE_SOURCE_DIR}`" question

**Comment by Axel-Naumann** [comment]
Ha, good point, I didn't see that! Then what about:
```
string(FIND ${dir} "${CMAKE_SOURCE_DIR}" src_dir_in_dir)
if(${src_dir_in_dir} EQUAL 0)
```

**Comment by oshadura** [comment]
@SpectreVert I beleive we can close this PR in favor of https://github.com/root-project/root/pull/8306?

**Pull request closed without merging**
