### PR TITLE
Revert "Fix detection of Python3 on Windows"

### PR DESCRIPTION
**Pull request by oshadura**
This reverts commit bb0d9ae4b97e16473d980c093dd00abf7da72972.

We have a problem in https://sft.its.cern.ch/jira/browse/ROOT-10725

### CODE REVIEW

**Comment by oshadura** [comment]
@bellenot sadly I will need to revert it because it broke discovery of python for 6.20 patches.
@maxgalli and me, we will think about how to fix it without creating breaking configuration of other people.

**Comment by bellenot** [comment]
> @bellenot sadly I will need to revert it because it broke discovery of python for 6.20 patches.
> @maxgalli and me, we will think about how to fix it without creating breaking configuration of other people.

Well, no problem, up to you, at least now you know one way to fix it... :wink:

**Comment by oshadura** [comment]
@maxgalli it is unbelievable......I can't believe my eyes....

**Comment by oshadura** [comment]
> @maxgalli it is unbelievable......I can't believe my eyes....

ah it was too early! :)

**Comment by oshadura** [comment]
Closing in favor of https://github.com/root-project/root/pull/5513

**Pull request closed without merging**
