### PR TITLE
[genreflex] Add support for noStreamer and noInputOperator xml attribute

### PR DESCRIPTION
**Pull request by breitwieserCern**
https://root-forum.cern.ch/t/linkdef-wildcarding-for-class-templates/25523/6

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Hey Lukas - thanks a lot!
@phsft-bot build!

**Comment by pcanal** [comment]
Nice.  One caveat though.  When running with genreflex the default is to use essentially the modifier + (request for new StreamerInfo based I/O) and there is no way (and should not) to request the old I/O implementation.  So it probably does not make sense to advertise the + (which is always a no-op).

**Comment by dpiparo** [comment]
I agree with philippe. The + could be left aside as the default. For what concerns the name of the field I am not sure "modifier" is the best name possible. "StreamerOption" ? Two simple fields, which can be "NoStreamer" and "NoInputOperator"?
E.g.
```
 ... NoStreamer = "true" />
 ... NoInputOperator = "true" />
```

**Comment by dpiparo** [comment]
...also the PR should be complemented with a test in roottest.

**Comment by breitwieserCern** [comment]
Thanks for the feedback Philippe and Danilo!
will modify it and send the corresponding tests

**Comment by martinmine** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
Hi @breitwieserCern ,
the functionality now looks good. Could you add a test in roottest about the new functionality?
This one should:
- Generate a dictionary with a selection xml
- Have a macro that loads it and checks that the custom streamer works fine
In order to achieve that, you can have a look to https://github.com/root-project/roottest/blob/master/root/meta/genreflex/CMakeLists.txt . Here you find the instructions about how to run tests: https://root.cern.ch/run-tests

In your case the CMake section could be something like:
```

ROOTTEST_GENERATE_REFLEX_DICTIONARY(customStreamer customStreamer.h SELECTION customStreamer_selection.xml)

ROOTTEST_ADD_TEST(customStreamer
                  MACRO customStreamer.C
                  OUTREF customStreamer.ref
DEPENDS ${GENERATE_REFLEX_TEST})
```
This will generate the dictionary from *customStreamer.h* and *customStreamer_selection.xml*. The macro *customStreamer.C* will be then executed and you can check there that your streamer does what is supposed to do (print something? your call :) ). The output will be compared to customStreamer.ref . You can start from a simplified version of the actual classes you are working with.
Do not hesitate to contact me privately if you need more info!

Cheers,
      D

**Comment by breitwieserCern** [comment]
Corresponding tests: https://github.com/root-project/roottest/pull/70

**Comment by dpiparo** [comment]
That was quick...

**Comment by breitwieserCern** [comment]
was interrupted between sending the 2 PR ;)

**Pull request merged**
