### PR TITLE
clang-tidy modernize 0 to nullptr

### PR DESCRIPTION
**Pull request by ferdymercury**
Modernize ROOT code to use nullptr instead of 0 or NULL.

Thanks to Clang-Tidy automatic modernizing function and QtCreator's GUI.

### CODE REVIEW

**Comment by linev** [comment]
@ferdymercury 
I really recommend that you split your HUGE commit on sub-components, that code owner can revisit it part separately.
And probably provide not one but several PRs.

**Comment by linev** [comment]
@phsft-bot build

**Comment by vgvassilev** [comment]
@ferdymercury, I'd not support such a change in interpreter/llvm. We do not accept generally patches to the llvm fork of that kind. You are welcome to propose such change to llvm mainline (https://llvm.org/docs/Contributing.html), although I do not think it will gain support there either.

**Comment by ferdymercury** [comment]
@vgvassilev I thought that llvm already modernized their NULL. Here are some comparisons of llvm master with ROOT master:

image <-- cling at ROOT master

image image <-- clang at LLVM master

image <-- ROOT master
image <-- LLVM master

Also, I see many commits in LLVM addressing this. Some of them are huge commits like the current one:
https://github.com/llvm/llvm-project/commit/248a13057a4adbdb8d511b1458daf39d01a4b520
https://github.com/llvm/llvm-project/commit/527a7fdfbd7461e2aaa9eb279543c5d9dc8efa5a
https://github.com/llvm/llvm-project/commit/49a2790fb329c5cf27d9735b97ef70a6760921e4
https://github.com/llvm/llvm-project/commit/0e6a36e17e07485ee511756e022263a59101c79a
https://github.com/llvm/llvm-project/commit/f61be9c971d20d1f30f5444e525990b78a71d65e

Or were you referring to a different fork?

(In any case, I don't see why ROOT should not follow the same path than llvm and modernize its NULLs.)

**Comment by jblomer** [comment]
@ferdymercury Can we close this PR in preparation of smaller ones per sub system?

**Comment by hageboeck** [comment]
> @vgvassilev I thought that llvm already modernized their NULL. Here are some comparisons of llvm master with ROOT master:
> Also, I see many commits in LLVM addressing this. Some of them are huge commits like the current one:
> Or were you referring to a different fork?
> 
> (In any case, I don't see why ROOT should not follow the same path than llvm and modernize its NULLs.)

Hi @ferdymercury,

it's not a different fork, but it's llvm 9. You have to know that ROOT has to put patches on top of llvm, which sometimes should not go upstream.
Now, if ROOT changes something in its llvm, there's two kind of changes
a) Something that should go upstream. ROOT patches llvm if something really needs to be changed, but that patch is brought into main llvm as well.
b) Something that has to be in ROOT only. Some "hacks" to make a compiler an interpreter will never go upstream.

The goal is to change things as infrequently as possible, and if necessary do a). If that doesn't work, it's going to be b). Anything that's neither a) or b) should not be done on the ROOT side, because that would make ROOT's llvm diverge too much from the fork point.

Something like using `nullptr` is neither a) nor b), so this should *only* happen on the llvm side (and you rightly pointed out that it's already happening). Eventually, it will automatically end up in ROOT.

I hope this clarifies a bit why you (we) should not touch ROOT's llvm with a modernisation like this.

**Comment by linev** [comment]
And if one starts replacing `0` by `nullptr`, probably one also can replace `NULL` by `nullptr` in C++ code

**Comment by ferdymercury** [comment]
> And if one starts replacing `0` by `nullptr`, probably one also can replace `NULL` by `nullptr` in C++ code

That's already included in my commit. See e.g.

image

**Comment by ferdymercury** [comment]
> @ferdymercury Can we close this PR in preparation of smaller ones per sub system?

Sure, I agree. I will close this.

I would say that every code-owner can decide if they want to open a 'null modernization' on their subsystem. I will just share the workflow I followed in case it helps them to reproduce. It's just a few steps a way.

- Install QtCreator (e.g. via the online installer, with the minimal installation, Qt not needed)
- File, Open File or Project, select main CMakeLists.txt of the ROOT git repository (or of their CMake subsystem if not full build)
- Click Build Icon
- Analyze, Clang and Tidy Analyzer
- When done, click on the Filter icon, select only modernize NULL option.
- Then, click on Select Fixits
- Optionally filter out the files that should be fixed.
- Click on Apply Fixits
- Sometimes, manual postprocessing is needed if there was e.g. ( flag ? pointer : 0 ) being used in a ternary operator, or overloaded int* pointer* functions. See postprocessing commits of my PR.
- git commit

I know that all this can be done with a command line script and no QtCreator, but I think the GUI is quite helpful to verify the fixits interactively before applying them. And at the same time it warns you of potential memory leaks ;) One can also select on the Settings Icon what warnings to get.

**Comment by ferdymercury** [comment]
> @ferdymercury, in the past we have taken an incremental approach to such modernization. In cases of `0->nullptr` which does not fix/avoid bugs in 99% of the cases. We have set up a travis builds based on clang-tidy which only triggers when people touch the area and remind them to modernize it. That's less intrusive in many ways including that it does not introduce git history bloats.
> 
> Why don't we start from there -- resurrect the `travis` builds and move it to github actions. Then add a few more checks (like that one). Take a look [here](https://github.com/root-project/root/blob/master/.travis.yml). IIRC, @reikdas was looking into this some time ago.

I completely support the idea that clang-tidy + clazy should run on the Travis build / github actions and warn users when doing 'deprecated' things like 0 as nullptr, or maybe also old C-style casts instead of static_cast.

**Comment by ferdymercury** [comment]
> Why don't we start from there -- resurrect the `travis` builds and move it to github actions.

Here an example on how it is done in KiCad:
https://github.com/KiCad/kicad-source-mirror/commit/f5793c598448bcaa52e377832e900b3bd63d6de2

**Comment by ferdymercury** [comment]
> That's less intrusive in many ways including that it does not introduce git history bloats.
> 

I agree, it sounds good. It seems it's already in the Travis CI builds from ROOT (allowed failures), and it even suggest you the option of doing the 'upgrading' without bloating the history.

image

**Pull request closed without merging**
