### PR TITLE
Fix running with macOS 12.0+ SDK after building with an older SDK

### PR DESCRIPTION
**Pull request by chrisburr**
# This Pull request:

This patch was proposed by @vgvassilev on mattermost.

When building with a macOS SDK before 12.0 and running with 12.0+ the
validation of private modulemaps fails due to a change in layout. This
change disables the check when DisablePCHValidation is active.

See these bug reports:
* https://root-forum.cern.ch/t/conda-root-and-macos-12-reprise/49135/5
* https://github.com/conda-forge/root-feedstock/issues/149
* https://github.com/conda-forge/root-feedstock/issues/167

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

**Comment by vgvassilev** [comment]
I am wondering if we should open a review at https://reviews.llvm.org

**Comment by chrisburr** [comment]
I'm very in favour of that, though I'm not sure I'd know how to properly explain the reason to them.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by vgvassilev** [comment]
> I'm very in favour of that, though I'm not sure I'd know how to properly explain the reason to them.

If you look a few lines above, there are also many cases where we check if we have disabled modules validation. I guess here the motivation is consistency with the rest when we have disabled the pcm validation...

**Comment by Axel-Naumann** [comment]
Can this be backported to v6-26-00-patches, @vgvassilev ?

**Comment by vgvassilev** [comment]
Done, thanks to @hahnjo

**Comment by hahnjo** [comment]
> Done, thanks to @hahnjo

Hm no, not that I'm aware of. I backported the fix to `std.modulemap` for GCC 12, but not this one...

**Comment by hahnjo** [comment]
Now backporting in https://github.com/root-project/root/pull/10669

**Comment by vgvassilev** [comment]
> Now backporting in #10669

Ah, apologies and thanks for the backport now! ;)

**Pull request merged**
