### PR TITLE
[Tree] Add support for branches of type long and unsigned long

### PR DESCRIPTION
**Pull request by eguiraud**
The corresponding leaflist letters are 'G' and 'g'.
A new class TLeafG is added -- basically a copy of TLeafL with
[U]Long64_t changed to [U]Long_t.

This fixes ROOT-8885, "Cannot create a branch of long, unsigned long,
std::size_t types".

For review convenience, I attach the diffs betwen `TLeafL.{h,cxx}` and `TLeafG.{h,cxx}`:
- [TLeafLGh.diff](https://github.com/root-project/root/files/5355689/TLeafLGh.txt)
- [TLeafLGcxx.diff](https://github.com/root-project/root/files/5355684/TLeafLGcxx.txt)

@Axel-Naumann `TTreeReader` seems to deal with long integers just fine. Nothing to do there, right?

~~@pcanal where can I add tests?~~

- [x] add tests in tree/treeplayer/test/leafs.cxx
- [x] update `TypeName2ROOTTypeName` in `tree/dataframe/src/RDFUtils.cxx`
- [x] update doc of class TTree
- [x] update doc of `TBranch::TBranch(TTree *tree, const char *name, void *address, const char *leaflist, Int_t basketsize, Int_t compress)`
- [x] update doc of `TBranch* TTree::Branch(const char* name, void* address, const char* leaflist, Int_t bufsize /* = 32000 */)`
- [x] update user's guide: documentation/users-guide/Trees.md

### CODE REVIEW

**Review by pcanal — CHANGES_REQUESTED** [review]
Looks good.  A few place I forgot we needed to update:

code of `TypeName2ROOTTypeName` in `tree/dataframe/src/RDFUtils.cxx`

doc of `class TTree`

doc of `TBranch::TBranch(TTree *tree, const char *name, void *address, const char *leaflist, Int_t basketsize, Int_t compress)`

doc of `TBranch* TTree::Branch(const char* name, void* address, const char* leaflist, Int_t bufsize /* = 32000 */)`

User's guide: documentation/users-guide/Trees.md

Thanks!

**Comment by eguiraud** [comment]
@pcanal @Axel-Naumann this is ready to merge as far as I can say.

**Comment by Axel-Naumann** [comment]
That's really for @pcanal I'm afraid

**Comment by pcanal** [comment]
Should we also update: User's guide: documentation/users-guide/Trees.md ?

**Comment by eguiraud** [comment]
Already updated.

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
> already updated

Sorry I somehow missed it :(

**Pull request merged**
