### PR TITLE
[Browser] Add option to run macro on double click

### PR DESCRIPTION
**Pull request by Falcort**
If enable double click on C, CPP or CXX file will run the macro, if the current that is not a code editor

### CODE REVIEW

**Comment by linev** [comment]
@Falcort  
One should decide on the server side if run or not run macro.
List of extensions you provide can be incomplete.
One can send "execution flag" with `DBLCLK:` message and let process it on server side

**Comment by Falcort** [comment]
@linev I have moved the verification to C++, I for now only put C and C++ file execution, but it is now easy to add more
Can you have a look again to my PR please ?

**Comment by linev** [comment]
Now is better!
Last comment - if execution mode is specified, one should not try to draw something.
Just do return after extensions are verified

**Comment by Falcort** [comment]
Oh yes you are completely true, i am changing that !

**Comment by Falcort** [comment]
Ok I found a bug that make running macro from the code editor or in some situations not possible, so i will try to resolve that as well before merging

**Comment by bellenot** [comment]
I confirm that the macro execution (with the `run` button from the editor) doesn't work on Windows anymore. I'll fix it

**Comment by Falcort** [comment]
@linev, everything is working now
Tell me if you need more changes

**Pull request merged**
