### PR TITLE
ROOT-9739 Build Configuration Fixes, master branch (2018.10.23.)

### PR DESCRIPTION
**Pull request by krasznaa**
This is meant to address the issues described in [ROOT-9739](https://sft.its.cern.ch/jira/browse/ROOT-9739).

The update to the Davix configuration should not be controversial, I just added arguments forcing Davix to use the same LibXml2 library found by ROOT as well.

The update to VDT is a bit weirder though. 😦 Unfortunately VDT executes a python script simply by calling `python <script>` during the CMake configuration. If there is not `python` executable in `$PATH` at this time, that fails.

Now, ideally the `python` name should not be hardcoded into the VDT code at all, it should be set dynamically to whatever [FindPythonInterp](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) finds as `PYTHON_EXECUTABLE`. But I wanted to solve it at "this level" for now. So I changed the code to call CMake explicitly for configuring VDT, in an environment in which `python` should be available. (As long as it **is** called `python`. But let's not worry about that for now...)

Overall, this is all for making it possible to build ROOT in the very small Ubuntu virtual machines that I use to provide ATLAS analysis release images for our users.

### CODE REVIEW

**Comment by amadio** [comment]
Hi Attila, to link commits to a JIRA issue, it's enough to just add the issue name somewhere in the commit message. I usually add `Fixes ROOT-NNNN` to the end of the message. That's already enough.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@krasznaa I added @dpiparo to the reviewers. I think it would be best to fix the Vdt issue upstream and update the builtin version of it in ROOT. The fix for Davix is fine as is, but remember that the same would be needed for libuuid, openssl, etc, if you try to pick them up from non-standard locations in the future. That's one of the drawbacks of having builtins as they are now...

**Comment by krasznaa** [comment]
😕 Davix already receives the location of `libuuid` and `openssl` explicitly.

https://github.com/root-project/root/blob/master/builtins/davix/CMakeLists.txt#L22-L24

The only thing that was left out was the location of `libxml2`. Which this PR should address.

Yes, the "VDT thing" is a lot less elegant. So I'll wait for Danilo's input.

**Comment by amadio** [comment]
> Davix already receives the location of libuuid and openssl explicitly.

You are right, I missed that somehow. I think we've added that so that Davix could find the builtin OpenSSL when that's enabled.

**Comment by krasznaa** [comment]
Hi @dpiparo,

I was trying to see if it would be easy to contribute to the VDT source. But apparently not. 😦

As far as I could find (http://lcginfo.cern.ch/pkg/vdt/), the code is maintained on: 
https://svnweb.cern.ch/trac/vdt But that site is down at the moment. And in any case, shouldn't that code have moved to git a while ago? Unfortunately I didn't find it on gitlab.cern.ch, so at this point I'm not sure where the code sits these days...

Cheers,
      Attila

**Comment by amadio** [comment]
@krasznaa Could you please drop the VDT commit so we can merge? I think we agree that the VDT part will be done via your PR to VDT at dpiparo/vdt#7.

**Comment by krasznaa** [comment]
Since I didn't know how to "drop" a commit from the open PR, I just opened #2833 instead...

**Comment by amadio** [comment]
For future reference: `git rebase -i master`, then remove the line with the commit you want to drop, then force push the branch you are working on.

Thanks Attila.

**Pull request closed without merging**
