### PR TITLE
[cmake] Tell llvm not to generate VCSRevision.h:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Virtually any git operation will trigger a regeneration of VCSRevision.h.
As cling, dictionaries, and libraries depend on this file, we need to
*not* regenerate it - we won't need it anyway.

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
Makes sense to me! LGTM!

**Review by vgvassilev — COMMENTED** [review]
Nice!

**Comment by Axel-Naumann** [comment]
BUT doesn't actually work; needs a fix in llvm upstream, but that won't apply to our llvm-9, so I'll develop both fixes independently...

**Comment by Axel-Naumann** [comment]
The feature was *meant* to work, but was later dropped (unintentionally?) from llvm. For now, #8044 will do for us, until @hahnjo will re-introduce this feature upstream.

**Comment by hahnjo** [comment]
> The feature was _meant_ to work, but was later dropped (unintentionally?) from llvm. For now, #8044 will do for us, until @hahnjo will re-introduce this feature upstream.

Already works upstream: The generated header files are marked as out-of-date whenever I switch branches, but the logic prevents updating / touching the files when not including the VCS revision, so `ninja` notices that it doesn't actually need to rebuild anything:
```
$ ninja -j1
[1/109] Generating VCSRevision.h
[2/33] Generating VCSVersion.inc
```

I think the reason this doesn't work in ROOT is that we don't have https://github.com/llvm/llvm-project/commit/fb5fafb23cc2d8613f8be2487afe94d8594a88ce, so `interpreter/llvm/src/tools/clang/lib/Basic/VCSVersion.inc` currently still contains the information and must be touched upon every switch.

**Pull request closed without merging**
