### PR TITLE
Eve-7 The first implementation of log view

### PR DESCRIPTION
**Pull request by alja**
This PR adds a message viewing accessible through top left  menu.
At the moment the view content is browser console messages and a checkbox to enable/disable debug mode.

There are also minor changes in log messages and additional try/catch blocks.

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check.

**Comment by alja** [comment]
Screenshot

**Comment by linev** [comment]
@phsft-bot build

**Review by linev — APPROVED** [review]

**Comment by linev** [comment]
@alja, I rebase your branch while it was not possible to automatically merge it

**Comment by linev** [comment]
@phsft-bot build

**Pull request merged**
