### PR TITLE
[PyROOT] Add __reduce__ method to ROOTFacade to help serialization tools

### LINKED ISSUE #6764: Pickling functions using the ROOT module with cloudpickle breaks
cloudpickle is the pickling package, which is used in dask and PySpark to serialize and distribute the work, e.g., functions or lambdas. The following reproducer breaks with cloudpickle (but is fine with the standard pickle) and throws the error `TypeError: cannot pickle 'ROOTFacade' object`, which is highly confusing.

```python
import ROOT
import cloudpickle


def foo():
    ROOT.TH1F()
    return 42

import cloudpickle as pickle # breaks with cloudpickle
#import pickle # works fine with the standard pickle

with open('f.pkl', 'wb') as f:
    pickle.dump(foo, f)
```

A workaround is moving the `import ROOT` line inside the function `foo`, which seems to omit the underlying issue in cloudpickle. We have submitted a bug report to the cloudpickle repository, see cloudpipe/cloudpickle#397.

### PR DESCRIPTION
**Pull request by vepadulano**
Fixes #6764 , see the comment with explanation there

### CODE REVIEW

**Comment by eguiraud** [comment]
Both the commit message and the code might use some comments, otherwise well done finding this out!

**Comment by vepadulano** [comment]
Alright, I added docstrings to the functions in _facade.py . I also added some unittests, we need to discuss whether we want to include the tests with `cloudpickle` which were the origin of the linked issue, but we would need to install the packages on the nodes and probably add another `ROOTTEST` envvar to avoid running them in certain nodes

**Comment by vepadulano** [comment]
Though it was worth for our reference to keep track also of the behaviour of the `dill` module in the tests (stemming from https://github.com/root-project/root/issues/6370)

**Comment by vepadulano** [comment]
After discussion, we decided to only keep pickle tests, whereas cloudpickle usecase is implicitly tested with distributed RDataFrame. See the sibling PR in rottest for the additional test of the serialization of the facade

**Review by etejedor — APPROVED** [review]
Thanks for investigating this @vepadulano !

**Pull request merged**
