### PR TITLE
[tmva] Fix Keras and PyTorch tutorials

### PR DESCRIPTION
**Pull request by lmoneta**
This PR fixes the TMVA tutorials for new Keras,PyTorch versions and for running them in parallel in the CI

### CODE REVIEW

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -Dtmva-sofie=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -Dtmva-sofie=On -DCTEST_TEST_EXCLUDE_NONE=On

**Review by omazapa — APPROVED** [review]
thanks @lmoneta

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -Dtmva-sofie=On -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by lmoneta** [comment]
@phsft-bot build just on ROOT-ubuntu2204/default with flags -Dtmva-sofie=On -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
