### PR TITLE
Upgrate builtins for zlib, lz4, and xxhash with new mechanism

### PR DESCRIPTION
**Pull request by amadio**
**Testing only, do not merge.**

### CODE REVIEW

**Comment by amadio** [comment]
I've tested with `-Dbuiltin_{lz4,xxhash,zlib}=ON/OFF` locally, but this is likely to break without cleaning the binary directory.

**Comment by amadio** [comment]
@phsft-bot build with flags -Dbuiltin_zlib=ON -Dbuiltin_xxhash=ON -Dbuiltin_lz4=ON

**Comment by amadio** [comment]
I've figured out why the test fails on macOS. There, libz.so gets autoloaded, so instead of failing with symbol not found (expected when builtin_zlib=ON), the test passes because of the autoloading (which is actually means failure for this test). However, I checked manually and the symbols are not exported:
```
macphsft20 $ file lib/libCore.so
lib/libCore.so: Mach-O 64-bit dynamically linked shared library x86_64
macphsft20 $ nm lib/libCore.so | grep zlib
00000000001ef410 t _zlibCompileFlags
00000000001ef400 t _zlibVersion
```

**Comment by pcanal** [comment]
> I've figured out why the test fails on macOS. There, libz.so gets autoloaded,

Why does it get autoloaded 'only' on macOS?

**Comment by amadio** [comment]
> Why does it get autoloaded 'only' on macOS? I.e. I don't see why it would be autoloaded on its own and so I am concerned another library is indirectly bringing it along ... i.e. we may (or may not) need to hide the libz symbol in that library too ....

Good question. I know it gets autoloaded because when I start ROOT, the symbol is not there. It's only there once I `#include <zlib.h>` in the interpreter.

**Comment by amadio** [comment]
Alright, this is ready for merging now. @oshadura Should I wait for your changes first?

**Comment by amadio** [comment]
The failures are because I merged. The build passed several times before, and I tested locally on Linux and Mac (and Windows for some cases).

**Pull request merged**
