### PR TITLE
Support undoing of #undef preprocessor tokens.

### PR DESCRIPTION
**Pull request by marsupial**
Updates DeclCollectorPPAdapter to new clang interface that reports an when every **#undef** encountered.

### CODE REVIEW

**Comment by marsupial** [comment]
Ping.

**Comment by marsupial** [comment]
Ping.

**Comment by vgvassilev** [comment]
@phsft-bot build!

@Teemperor, you've been working in this area, could you review?

@marsupial, sorry for the delay. This LGTM.

**Comment by Teemperor** [comment]
LGTM

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
Another infrastructure issue for one of the builds, all rest seem good.

**Pull request merged**
