### PR TITLE
[cmake] Use SHA256 instead of MD5 for external source verification

### PR DESCRIPTION
**Pull request by Teemperor**
Also now verify all downloaded software before installing.

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build with flags -Dbuiltin_all=On

**Comment by bbockelm** [comment]
warnings should be fixed in https://github.com/root-project/root/pull/1254

**Comment by Teemperor** [comment]
@bbockelm now it's all SHA256 and with a consistent style

**Comment by Teemperor** [comment]
@phsft-bot build with flags -Dbuiltin_all=Off

**Comment by pcanal** [comment]
> projectroot.roottest.root.meta.loadAllLibs.roottest_root_meta_loadAllLibs_LoadAllLibsAZ

Is this problem reproducible locally or is it a jenkins glitch?

**Comment by Teemperor** [comment]
Not sure, I rebased and let's retry.

**Pull request merged**
