### PR TITLE
Testing PR build.

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by amadio** [comment]
@phsft-bot build -Dclad=OFF -DCMAKE_INSTALL_PREFIX=/root

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by amadio** [comment]
@phsft-bot build with flags -Dclad=OFF

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclad=ON

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclad=ON

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclad=ON

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -Dclad=ON

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc52

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc52

**Comment by vgvassilev** [comment]
@phsft-bot build!

Testing the new roottest branch checkout...

**Comment by vgvassilev** [comment]
Looks like it works.

**Pull request closed without merging**
