### PR TITLE
Avoid C-Style Casts in Dictionary

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
# This Pull request:

## Changes or fixes:

We compile our code (including the dictionaries) with warnings about C-Style casts. We would like to also reduce the warnings about the dictionaries.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Review by pcanal — APPROVED** [review]
LGTM

**Comment by ChristianTackeGSI** [comment]
For me it looks like the CI failures are not related to my suggested change?

**Comment by pcanal** [comment]
Yes, they are transisent and pre-exisiting.

**Comment by ChristianTackeGSI** [comment]
Many thanks! :slightly_smiling_face:

**Pull request merged**
