### PR TITLE
[CPyCppyy] Auto-cast elements of std::vector<T*>, with T a class type

### PR DESCRIPTION
**Pull request by guitargeek**
Applying the following commit from CPyCppyy upstream: https://github.com/wlav/CPyCppyy/commit/9a792b231c73452d08686ea83c6588f5e98ca9a7

Closes #1523.

### CODE REVIEW

**Comment by vepadulano** [comment]
Thre is a timeout of `tutorial-rcanvas-df104-py` on mac14, let's rerun the CI and make sure it's not related to this PR

**Review by vepadulano — COMMENTED** [review]
Changes look good, but can we add the test from the linked issue?

**Comment by guitargeek** [comment]
@vepadulano, there is already a test in upstream cpycppyy: https://github.com/wlav/cppyy/commit/25398e665d157eb7ede8b3f81e18a5ab7c0da555

That's why I didn't add a unit test.

So this is actually a more general question: should we duplicate the cppyy tests as ROOT unit tests?

**Comment by vepadulano** [comment]
> So this is actually a more general question: should we duplicate the cppyy tests as ROOT unit tests?

IMHO we should inherit cppyy's testing suite, upstreaming all ROOT's Python unit tests (that do not use specifically ROOT classes).

**Review by vepadulano — APPROVED** [review]
Thank you! This PR can be merged and the discussion about unit tests can be held separately

**Pull request merged**
