### PR TITLE
[cling-cpt] Fixed argument nomenclature [skip-ci]

### PR DESCRIPTION
**Pull request by saisoma123**
# This Pull request: Rewrote parser arguments for better nomenclature.

## Checklist:

- [X] tested changes locally
- [NA] updated the docs (if necessary)

This PR fixes issue in list #406 (https://github.com/root-project/cling/issues/406)

### CODE REVIEW

**Comment by vgvassilev** [comment]
If we make this rename we need to make sure we rename all its uses in places such as `.github/workflows/ci.yml`.

**Comment by saisoma123** [comment]
Hi @vgvassilev, where are the places specifically I have to add the renames?

**Comment by vgvassilev** [comment]
> Hi @vgvassilev, where are the places specifically I have to add the renames?

```
interpreter/cling/.github/workflows/ci.yml:          python3 cpt.py -y --check-requirements --current-dev=tar --with-cmake-flags="$CLING_BUILD_FLAGS" --with-cling-url=https://github.com/$REPO --cling-branch=${{ github.head_ref }} --with-binary-llvm --with-llvm-tar
interpreter/cling/.github/workflows/ci.yml:          python3 cpt.py -y --check-requirements --current-dev=tar --with-cmake-flags="$CLING_BUILD_FLAGS" --with-cling-url=https://github.com/$REPO --cling-branch=${{ github.head_ref }} --with-binary-llvm
interpreter/cling/.travis.yml:      --with-binary-llvm \
interpreter/cling/.travis.yml:      --with-binary-llvm \
```

**Comment by saisoma123** [comment]
@vgvassilev just added the renames to the files you mentioned.

**Review by vgvassilev — APPROVED** [review]
LGTM! Could you rebase the PR and then I can merge it.

**Comment by saisoma123** [comment]
Hi @vgvassilev, just rebased the PR

**Comment by vgvassilev** [comment]
@saisoma123, I have squashed the commits. In future we should do these changes in a single commit to have a clearer history.

**Comment by saisoma123** [comment]
@vgvassilev, will keep that in mind for the future, thanks.

**Pull request merged**
