### PR TITLE
Improve FindRoot speed

### PR DESCRIPTION
**Pull request by ktf**
For some reason root-config calls on macOS 10.13.2 are extremely slow (not sure if this is related to the meltdown / spectre mitigations).

```bash
[O2/latest] ~/work/active/sw/BUILD/ROOT-latest/ROOT %> time root-config --version
6.13/01
root-config --version  0.24s user 1.06s system 131% cpu 0.989 total
```

which than means that whatever dependent project using `FindROOT.cmake` is slowed down quite a lot when trying to do incremental builds. This is because of the multiple `root-config` invocations in such a macro, which are also not cached so they get done on any `make` invocation.

### CODE REVIEW

**Comment by amadio** [comment]
@ktf Hi Giulio, thank you for bringing this issue to our attention (slow `FindROOT.cmake`). However, I'm not sure the approach taken here is the best. I think that it would be better to change `FindROOT.cmake` to not rely on the `root-config`, but be generated directly from a `FindROOT.cmake.in` with all the paths already computed. What do you think?

**Comment by ktf** [comment]
Yes, agreed. As long as all the variables are configurable, that's fine for me (no root-config invocations are better than one root-config invocation :-) ). Will you do it?

**Comment by amadio** [comment]
> Will you do it?

Yes. This year we plan to do a major upgrade to the build system to follow “modern CMake” constructs, and to make ROOT follow FHS more closely. This will definitely include updates to FindROOT.cmake and friends like root-config.

Since you agree that not using `root-config` is better, I am closing this PR, but we can open a JIRA issue to track progress on this particular problem (slowness of `FindROOT.cmake`) if you'd like.

**Comment by ktf** [comment]
JIRA -> Yes, please.

**Comment by amadio** [comment]
Done, this is now [ROOT-9230](https://sft.its.cern.ch/jira/browse/ROOT-9230). Thanks!

**Pull request closed without merging**
