### PR TITLE
Remove unused includes from graf2d classes

### PR DESCRIPTION
**Pull request by linev**

### CODE REVIEW

**Comment by couet** [comment]
not there's some mistakes with endl; ...

**Comment by linev** [comment]
> note there's some mistakes with endl; ...

Which one?

**Comment by couet** [comment]
see above, "Build failed on mac1015/cxx17."

[2020-06-02T14:08:18.652Z] /Users/sftnight/build/workspace/root-pullrequests-build/root/graf2d/asimage/src/TASImage.cxx:6767:16: error: no member named 'endl' in namespace 'std'

etc ...

**Comment by linev** [comment]
I add changes and rebase code after I saw this error

**Pull request merged**
