### PR TITLE
[cling] Switch to -O2 for JIT.

### PR DESCRIPTION
**Pull request by Axel-Naumann**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build with -Dctest_test_exclude_none=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -Dctest_test_exclude_none=On -Dimt=ON -Dccache=ON

**Comment by pcanal** [comment]
In the interactive mode (for the na49.C) type of macro do we have a mean to check and print on a regular basis (every minutes) that the compilation is 'making progress'?

**Comment by Axel-Naumann** [comment]
You mean as a progress bar? 'Cause I am *sure* that clang is making progress - I doubt that have a `if (opt == O2) sleep(120)` ;-)

**Comment by pcanal** [comment]
I am also sure that in some version of clang (and gcc) there will be bug leading to infinite loop on very specific code ...

But yes, the point is to reassuring the sure that something is happening (as opposed to be hang on open the source file for example) .. or stuck looping in their code.

**Comment by Axel-Naumann** [comment]
The benefits are all but obvious. Closing.

**Pull request closed without merging**
