### PR TITLE
Add option to draw hexagon type in the REveBoxsSet

### PR DESCRIPTION
**Pull request by alja**
# This Pull request:
Add hexagon shape type in REveBoxSet

## Changes or fixes:
Remove unnecessary slider in the left most view by using FlexBox instead of Splitter.

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check.

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@alja Something wrong with the PR - Jenkins fail to build it.
May be "-" sign in branch name is a problem.
Can you recreate PR with other branch name without "-" signs?

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
Multiple infra issues here:
- the PR build didn't start by itself because @alja wasn't part of ROOT-project in GitHub; invite is pending.
- we seem to have an issue picking up the PR branches on root.cern; I'm looking into this.

**Comment by Axel-Naumann** [comment]
The issue with this PR seems to be that the branch comes with a merge commit, while we require linear history. I don't know why GitHub isn't showing this. @alja could you rebase your branch on top of master, and make sure it applies cleanly without merge commit?

**Comment by linev** [comment]
@alja I closing this PR and create new one: https://github.com/root-project/root/pull/11277

I just rebase your code against master

**Comment by alja** [comment]
@linev Thanks, I working on redoing this PR.

**Comment by linev** [comment]
I already submit new one - #11277.
I will merge it soon

**Pull request closed without merging**
