### PR TITLE
Use nullptr

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by amadio** [comment]
Hi @vgvassilev, is this PR still relevant? Has another equivalent thing been merged?

**Comment by amadio** [comment]
Ping.

**Comment by vgvassilev** [comment]
@amadio, I wanted redo it without running clang-format on the changed lines.

**Comment by amadio** [comment]
Ok, just wanted to know if this should stay here or be closed... Thanks for the update.

**Comment by amadio** [comment]
Given the amount of conflicts, it may actually make sense to just close this pull request and start a new one later.

**Comment by vgvassilev** [comment]
I'd keep it open.

**Comment by bbockelm** [comment]
@vgvassilev - is it possible to break up this PR to a series of requests, one per module (or sub-module?)?

Would help prevent the merge conflicts from accumulating...

**Comment by vgvassilev** [comment]
We want to fix it in one go. I will take care of this as soon as I get a chance ;)

**Comment by vgvassilev** [comment]
I do not have the bandwidth now for this PR.

**Pull request closed without merging**
