### PR TITLE
[imt] Introduce env var ROOT_MAX_THREADS

### LINKED ISSUE #9805: Add env variable to limit number of threads used by ROOT
Hi,

ATLAS would like to request the addition of a mechanism to control the number of threads used by ROOT with implicit multi-threading enabled, ideally via an environment variable (e.g. `ROOT_MAX_THREADS`). The primary motivation for this is to give GRID sites an easier way to limit the number of threads to match that of a queue.

Thanks!

Ed

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Fixes #9805

### CODE REVIEW

**Review by eguiraud — APPROVED** [review]
Some comments for your consideration but looks good.

I'm not sure that ROOT_MAX_THREADS should have precedence over cgroups, maybe we should be taking the minimum.

It would be good to document that ROOT honors that env variable in the docs of `EnableImplicitMT`, I think that's where users would look for this information.

Errors might be degraded to warnings as execution will continue without problems in case of malformed ROOT_MAX_THREADS (I understand the will to make the error message "stand out" but that likely goes for every warning ever written :D ). Anyway we don't have a policy on when to use what so just a though :)

**Comment by pcanal** [comment]
I agree that the new setting should not be increasing the threads past `cgroup`.

I think a malformed `ROOT_MAX_THREADS` is an error as setting this specific variable is very unlikely to have been done 'casually/just-because' and hence the program is mis-behaving (using too many threads) compared to the user's expectations.

**Comment by eguiraud** [comment]
> I think a malformed ROOT_MAX_THREADS is an error as setting this specific variable is very unlikely to have been done 'casually/just-because' and hence the program is mis-behaving (using too many threads) compared to the user's expectations.

In that case `Error()` is certainly appropriate, but then that's an argument for aborting execution rather than continuing with the wrong amount of threads.

**Comment by pcanal** [comment]
`Error` is a bit of a middle ground.  It indicates it is bad but recoverable and more important offer the framework that have their own error handler to mark those (and only those) as fatal if they want.

**Comment by eguiraud** [comment]
@pcanal fair enough! :)

**Comment by Axel-Naumann** [comment]
> I'm not sure that ROOT_MAX_THREADS should have precedence over cgroups

I am convinced that it should. If you want to oversubscribe then that env var is your only chance.

> It would be good to document that ROOT honors that env variable in the docs of `EnableImplicitMT`,

Excellent point, will do.

**Review by jblomer — APPROVED** [review]

**Comment by pcanal** [comment]
> I am convinced that it should. If you want to oversubscribe then that env var is your only chance.

Since the `cgroup` limit will actually prevent the process from using more than the configured amount, I agree that you are right.  Using the env var, is a way to tell `ROOT` to use more threads than the effective number of core it will be allowed to use (i.e. oversubscribing).

**Review by pcanal — APPROVED** [review]

**Comment by eguiraud** [comment]
I'm not sure oversubscription will work as you expect, `RTaskArenaWrapper`'s ctor has this code:

```cpp
   const unsigned tbbDefaultNumberThreads = fTBBArena->max_concurrency(); // not initialized, automatic state
   maxConcurrency = maxConcurrency > 0 ? std::min(maxConcurrency, tbbDefaultNumberThreads) : tbbDefaultNumberThreads;
   const unsigned bcCpus = LogicalCPUBandwithControl();
   if (maxConcurrency > bcCpus) {
      Warning("RTaskArenaWrapper", "CPU Bandwith Control Active. Proceeding with %d threads accordingly", bcCpus);
      maxConcurrency = bcCpus;
   }
   if (maxConcurrency > tbb::global_control::active_value(tbb::global_control::max_allowed_parallelism)) {
      Warning("RTaskArenaWrapper", "tbb::global_control is active, limiting the number of parallel workers"
                                   "from this task arena available for execution.");
   }
   fTBBArena->initialize(maxConcurrency);
```

**Comment by Axel-Naumann** [comment]
Thanks, @eguiraud . I don't see this as a reason to complain if `ROOT_MAX_THREADS` is set to a value higher than what the TBB arena will use in the end - also because it's already fairly involved to figure out what that number will be... If I got you wrong and / or my above statement is incorrect then we will add that error message in a subsequent PR.

**Comment by Axel-Naumann** [comment]
The Windows failures seem spurious / build system issues unrelated to this PR.

**Comment by Axel-Naumann** [comment]
Indeed! How's https://github.com/root-project/root/pull/13126 looking for you?

**Pull request merged**
