### PR TITLE
[CMake] Don't fail configuration on macOS if textutil can't be found

### PR DESCRIPTION
**Pull request by guitargeek**
On macOS, we rely on the `textutil` executable to set some packaging metadata. However, we can't assume that it's always present. For example, in the nix packages build, it is not available, and there is a hack that disables setting the package metadata:
https://github.com/nixos/nixpkgs/blob/848699d4c1f669af01918b7cfdb438329667ddc2/pkgs/applications/science/misc/root/default.nix#L145

However, the `CPACK_PACKAGE_DESCRIPTION_FILE` and
`CPACK_RESOURCE_FILE_README` metadata that depends on `textutil` is optional and not crucial. It's used only in rare situations, like creating Windows installers automatically. See also the description here:
https://cmake.org/cmake/help/latest/module/CPack.html

It would be more appropriate to not fail the configuration if `textutil` is not found, but instead just to skip setting this metadata.

### CODE REVIEW

**Comment by vepadulano** [comment]
So just to understand the goal of this, it's to remove the patch for the nix package build of ROOT?

**Comment by guitargeek** [comment]
That's correct!

**Comment by dpiparo** [comment]
In general, I think this is a good change. Can you confirm that nothing we do in Windows is affected by this change? It is not clear to me what "creating Windows installers automatically" actually means.

**Comment by guitargeek** [comment]
I don't know, I just got this information from the CMake documentation I linked above. In any case, it's not relevant because the code is inside an `if (APPLE)`.

**Review by bellenot — APPROVED** [review]

**Pull request merged**
