### PR TITLE
Remove not used test files and makefiles

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by pcanal** [comment]
Actually we need to do the reverse and insert this test in ctest.

**Comment by oshadura** [comment]
@pcanal I found similiar (it is possibly duplicated) test in roottest, it was for sure not running in Make version of test because actually after porting it to CMake and correcting wrong code, I didn't manage to have it working correctly.

**Comment by pcanal** [comment]
Indeed test/*Draw* and roottest/root/treeformula/event/*Draw* are extremely similar but not identical.  In particular the one in test run on a couple more file layout and add several additional test inside (See the content of dt_RunDrawTest.sh and dt_DrawTest.C).

Before removing the one in test we should

a) make sure the one in roottest/root/treeformula/event/ is run and works.
b) extent it to cover the additional feature that are in the one in test
c) extent it (or understand why we could not) to the additional files that are testing in the one in test

Thanks,
Philippe.

**Comment by oshadura** [comment]
@pcanal, thanks you for feedback. Actually, I was talking about fastcloning test in roottest.git. I found in it's Makefile exactly the same macros and  bash scripts including also dt_RunDrawTest.sh and dt_DrawTest.C.

I tried to port it to CMake but code requires a lot of fixes and doesn't work from out of the box.

I have WIP PR https://github.com/root-project/roottest/pull/290 with commented out part including dt_RunDrawTest.sh and dt_DrawTest.C since it was not running for long time. Do you think I can remove in roottest PR https://github.com/root-project/roottest/pull/290 outdated code in favour of proposed solution in your comment - (a), b), c) steps?

**Comment by pcanal** [comment]
The goal of those scripts in fastcloning is to ensure that the merged files has the expected file and data (for all the use case in the DrawTest family, which includes many of the possible TTree structures).  They have been unfortunately disabled since we moved from CINT to Cling as the scripts are relying on CINT's dynamic scope feature that did not fully make it into Cling.   The script needs to be adapted accordingly, however it is likely they also do *not* have to be a set specific to this directory (to be verified), in the time of Makefiles it was easier to duplicate that try to deal with the dependencies.

**Comment by Axel-Naumann** [comment]
@pcanal thanks for sharing the history of this.

What do we do now? Keep the old files as markers that we still need to port these tests to cling/CMake?

**Comment by pcanal** [comment]
yes.

**Pull request closed without merging**
