### PR TITLE
[RF] Add overload of the Slice argument that takes map of categories

### PR DESCRIPTION
**Pull request by guitargeek**
Before, if one wanted to slice over mulitple categories in
`RooAbsReal::plotOn`, one had to repeatedly use the Slice command
argument. This is problematic for the keyword pythonizations in pyROOT,
because keyword arguments in python can't be repeated.

With this change, it is also not necessary anymore to repeat any command
arguements in RooFit. This will help to solve Jira issue [ROOT-2784](https://sft.its.cern.ch/jira/browse/ROOT-2784), as
we can just always throw an error (or issue a warning) if a RooCmdArg is repeated.

### CODE REVIEW

**Review by lmoneta — APPROVED** [review]
Looks good. I have just a question, what will happen in case of old C++ code using multiple commands ? Will they get a warning or an error ?

**Comment by guitargeek** [comment]
Hi! Nothing will happen to the old C++ code. The point of this PR is to have the possibility in C++ to use each command only one time. This is to make it consistent with the pyROOT interface, where the commands will be passed as keyword arguments that can't be repeated.

I was just saying that after this PR, we could easily resolve ROOT-2784 by issuing a warning when any command argument is repeated, since now every command that can be repeated has also an aggregate alternative (`Link`, `Import`, and `Slice`). I guess for the warning, we can even detect if the repeated command is one of these three commands and then suggest the `std::map` alternative in the warning.

**Comment by lmoneta** [comment]
Sounds good ! I agree with this, by emitting a warning and suggesting the alternative command for these special cases.

**Comment by guitargeek** [comment]
Added the pyROOT label, because the point of this PR was to improve the pyROOT experience: in pyROOT, the `Slice` command is a keyword argument. Keyword arguments can't be repeated, so we needed a mechanism to pass multiple slice commands at once via a dictionary/`std::map`.

**Pull request merged**
