### PR TITLE
[cling] Try to avoid crashes in llvm::identify_magic

### PR DESCRIPTION
**Pull request by hahnjo**
The overload taking a path opens the file and then `mmap` its contents. This can cause bus errors when another process truncates the file while we are trying to read it. Instead just read the first 128 bytes, which should be enough for `identify_magic` to do its work.

### CODE REVIEW

**Comment by hahnjo** [comment]
FWIW I managed to make `llvm::identify_magic` crash with a bus error like this:
```c++
#include <llvm/ADT/Twine.h>
#include <llvm/BinaryFormat/Magic.h>
#include <llvm/Support/MemoryBuffer.h>

#include <iostream>

#include <unistd.h>

int main(int argc, char *argv[]) {
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <file>" << std::endl;
    return 1;
  }

  llvm::Twine Path(argv[1]);

  auto FileOrError =
#ifdef FIXED
    llvm::MemoryBuffer::getFile(Path, /*IsText=*/false,
                                /*RequiresNullTerminator=*/true,
                                /*IsVolatile=*/true);
#else
    llvm::MemoryBuffer::getFile(Path, /*IsText=*/false,
                                /*RequiresNullTerminator=*/false);
#endif
  if (!FileOrError) {
    std::cerr << "Problem reading '" << argv[1] << "'!" << std::endl;
    return 1;
  }

  std::unique_ptr<llvm::MemoryBuffer> FileBuffer = std::move(*FileOrError);
  sleep(5);
  llvm::file_magic Magic = llvm::identify_magic(FileBuffer->getBuffer());

  std::cout << "Magic = " << Magic << std::endl;

  return 0;
}
```
Compile this into an executable, and then make a copy to use as input. While the program is sleeping, call `truncate -s 0` on the input and it should crash. (I *hope* this is also what happens in Jenkins with the random crashes we've been seeing...) The version with `FIXED` calls `getFile` with `IsVolatile=true` (and `RequiresNullTerminator=true`) to avoid using `mmap` and the crash. For Cling, I decided to just go with a `std::ifstream` to read the first 128 bytes.

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
> For Cling, I decided to just go with a std::ifstream to read the first 128 bytes.

what is the advantage of the solution in the reproducer you have?

**Comment by vgvassilev** [comment]
@hahnjo, this looks good to me but can we not fix the `llvm::identify_magic` as well or instead?

**Comment by hahnjo** [comment]
> > For Cling, I decided to just go with a std::ifstream to read the first 128 bytes.
> 
> what is the advantage over the solution in the reproducer you have (using llvm::MemoryBuffer::getFile with different arguments)?

It's plain C++ and we can guarantee that it's not using `mmap`. For `llvm::MemoryBuffer::getFile` I had to look at the source code because I would have argued that `IsVolatile=true` is enough, but it also requires `RequiresNullTerminator=true` to read in the file contents immediately. Additionally, `getFile` would try to read in the entire file, which we don't need here (and the reason why `mmap` is so efficient).

**Comment by hahnjo** [comment]
> @hahnjo, this looks good to me but can we not fix the `llvm::identify_magic` as well or instead?

The question is whether `llvm::identify_magic` should be prepared to deal with files that are modified concurrently. As far as I understand, Cling uses this code path to auto-detect libraries and distinguish them from random binary files. If the answer is yes, then I can try to fix `llvm::identify_magic` upstream so we get it with some future LLVM upgrade.

**Comment by vgvassilev** [comment]
> > @hahnjo, this looks good to me but can we not fix the `llvm::identify_magic` as well or instead?
> 
> The question is whether `llvm::identify_magic` should be prepared to deal with files that are modified concurrently. As far as I understand, Cling uses this code path to auto-detect libraries and distinguish them from random binary files. If the answer is yes, then I can try to fix `llvm::identify_magic` upstream so we get it with some future LLVM upgrade.

I think this is a valid use-case. Moreover, we are planning to upstream that functionality from cling which suggests which library is needed on a missing symbol to the jit infrastructure.

**Comment by hahnjo** [comment]
> > > @hahnjo, this looks good to me but can we not fix the `llvm::identify_magic` as well or instead?
> > 
> > 
> > The question is whether `llvm::identify_magic` should be prepared to deal with files that are modified concurrently. As far as I understand, Cling uses this code path to auto-detect libraries and distinguish them from random binary files. If the answer is yes, then I can try to fix `llvm::identify_magic` upstream so we get it with some future LLVM upgrade.
> 
> I think this is a valid use-case. Moreover, we are planning to upstream that functionality from cling which suggests which library is needed on a missing symbol to the jit infrastructure.

Ok, I've added a `FIXME` comment.

**Comment by vgvassilev** [comment]
> > > > @hahnjo, this looks good to me but can we not fix the `llvm::identify_magic` as well or instead?
> > > 
> > > 
> > > The question is whether `llvm::identify_magic` should be prepared to deal with files that are modified concurrently. As far as I understand, Cling uses this code path to auto-detect libraries and distinguish them from random binary files. If the answer is yes, then I can try to fix `llvm::identify_magic` upstream so we get it with some future LLVM upgrade.
> > 
> > 
> > I think this is a valid use-case. Moreover, we are planning to upstream that functionality from cling which suggests which library is needed on a missing symbol to the jit infrastructure.
> 
> Ok, I've added a `TODO` comment.

Note that we can fix it now, and backport the change. Otherwise I fear the `TODO` will just stay forever there.

**Comment by hahnjo** [comment]
> > Ok, I've added a `TODO` comment.
> 
> Note that we can fix it now, and backport the change. Otherwise I fear the `TODO` will just stay forever there.

We could, but I don't think this is the right approach: We're in the middle of an LLVM upgrade already and any change to LLVM prevents distributions from building against their vanilla LLVM libraries in the future. Moreover, I'm still not 100% convinced that it should be the original `llvm::identify_magic` that needs to handle this situation. In principle this would mean that `mmap` must never be used in LLVM since any file could randomly be truncated.

I can remove the `TODO` comment again if you prefer, I only added it because it sounded like you want a reminder.

**Comment by vgvassilev** [comment]
> > > Ok, I've added a `TODO` comment.
> > 
> > 
> > Note that we can fix it now, and backport the change. Otherwise I fear the `TODO` will just stay forever there.
> 
> We could, but I don't think this is the right approach: We're in the middle of an LLVM upgrade already and any change to LLVM prevents distributions from building against their vanilla LLVM libraries in the future. Moreover, I'm still not 100% convinced that it should be the original `llvm::identify_magic` that needs to handle this situation. In principle this would mean that `mmap` must never be used in LLVM since any file could randomly be truncated.
> 
> I can remove the `TODO` comment again if you prefer, I only added it because it sounded like you want a reminder.

Thanks for the clarification. Let's keep it as it is now.

**Pull request merged**
