### PR TITLE
Emulated Collection Proxy need to always use the VectorLooper for the StreamerInfoActions

### LINKED ISSUE #9136: [I/O] Cannot read RVecs written with v6.24 with TTreeReader in current master
Reading with TTree works.

This affects RDataFrame critically.

To reproduce at the prompt:

```
/tmp source /home/blue/ROOT/v6.24/_build/bin/thisroot.fish
/tmp root -l # with v6.24
root [0] ROOT::RDataFrame(10).Define("x", "ROOT::RVec<int>{1,2,3}").Snapshot("t", "f.root");
root [1] .q
/tmp source /home/blue/ROOT/master/_build/bin/thisroot.fish
/tmp root -l # now with master
root [0] ROOT::RDataFrame("t", "f.root").Display("x")->Print()
Fatal: 0 violated at line 1509 of `../io/io/src/TGenCollectionProxy.cxx'
aborting
#0  0x00007f4f9c4a99ea in wait4 () from /usr/lib/libc.so.6
#1  0x00007f4f9c427a2b in do_system () from /usr/lib/libc.so.6
#2  0x00007f4f9cdcc21c in TUnixSystem::Exec (this=0x55b0a9ebf800, shellcmd=0x55b0ae8f76d0 "/home/blue/ROOT/master/_build/etc/gdb-backtrace.sh 143932 1>&2") at ../core/unix/src/TUnixSystem.cxx:2120
#3  0x00007f4f9cdccb0e in TUnixSystem::StackTrace (this=0x55b0a9ebf800) at ../core/unix/src/TUnixSystem.cxx:2411
#4  0x00007f4f9cc5e089 in DefaultErrorHandler (level=6000, abort_bool=true, location=0x7f4f9c10b012 "", msg=0x55b0af523450 "0 violated at line 1509 of `../io/io/src/TGenCollectionProxy.cxx'") at ../core/base/src/TErrorDefaultHandler.cxx:174
#5  0x00007f4f9cd3a560 in ErrorHandler(Int_t, const char *, const char *, typedef __va_list_tag __va_list_tag *) (level=6000, location=0x7f4f9c10b012 "", fmt=0x7f4f9ce795d8 "%s violated at line %d of `%s'", ap=0x7ffe675d1310) at ../core/foundation/src/TError.cxx:152
#6  0x00007f4f9cd3ab94 in Fatal (location=0x7f4f9c10b012 "", fmt=0x7f4f9ce795d8 "%s violated at line %d of `%s'") at ../core/foundation/src/TError.cxx:249
#7  0x00007f4f9bf0a0fa in TGenCollectionProxy__VectorNext () at ../io/io/src/TGenCollectionProxy.cxx:1509
#8  0x00007f4f9c009167 in TStreamerInfoActions::GenericLooper::Numeric<int, int>::ConvertAction (items=0x55b0af2ac580, start=0x55b0af0e38d0, end=0x55b0af0e38dc, loopconf=0x7ffe675d1550) at ../io/io/src/TStreamerInfoActions.cxx:2447
#9  0x00007f4f9bff45fd in TStreamerInfoActions::GenericLooper::ConvertBasicType<int, int, TStreamerInfoActions::GenericLooper::Numeric>::Action (buf=..., start=0x55b0af0e38d0, end=0x55b0af0e38dc, loopconf=0x7ffe675d1550, config=0x55b0af070740) at ../io/io/src/TStreamerInfoActions.cxx:2467
#10 0x00007f4f9bf90e3b in TStreamerInfoActions::GenericLooper::ReadNumericalCollection<TStreamerInfoActions::GenericLooper::ConvertBasicType<int, int, TStreamerInfoActions::GenericLooper::Numeric> > (buf=..., addr=0x55b0af1eba40, conf=0x55b0af070740) at ../io/io/src/TStreamerInfoActions.cxx:2617
#11 0x00007f4f9bf6c208 in TStreamerInfoActions::GenericLooper::ReadCollectionBasicType<int> (buf=..., addr=0x55b0af1eba40, conf=0x55b0af070740) at ../io/io/src/TStreamerInfoActions.cxx:2650
#12 0x00007f4f9be4b627 in TStreamerInfoActions::TConfiguredAction::operator() (this=0x55b0af5360e0, buffer=..., object=0x55b0af1eba40) at ../io/io/inc/TStreamerInfoActions.h:123
#13 0x00007f4f9be49407 in TBufferFile::ApplySequence (this=0x55b0af1d9620, sequence=..., obj=0x55b0af1eba40) at ../io/io/src/TBufferFile.cxx:3572
#14 0x00007f4f826ebd17 in TBranchElement::ReadLeavesMember (this=0x55b0ae204b20, b=...) at ../tree/tree/src/TBranchElement.cxx:4499
#15 0x00007f4f826d0f25 in TBranch::GetEntry (this=0x55b0ae204b20, entry=0, getall=0) at ../tree/tree/src/TBranch.cxx:1691
#16 0x00007f4f826e47af in TBranchElement::GetEntry (this=0x55b0ae204b20, entry=0, getall=0) at ../tree/tree/src/TBranchElement.cxx:2714
#17 0x00007f4f82e8de93 in ROOT::Detail::TBranchProxy::Read (this=0x55b0af313140) at ../tree/treeplayer/inc/TBranchProxy.h:155
#18 0x00007f4f82f3269a in (anonymous namespace)::TCollectionLessSTLReader::GetCP (this=0x55b0af126050, proxy=0x55b0af313140) at ../tree/treeplayer/src/TTreeReaderArray.cxx:112
#19 0x00007f4f82f32746 in (anonymous namespace)::TCollectionLessSTLReader::GetSize (this=0x55b0af126050, proxy=0x55b0af313140) at ../tree/treeplayer/src/TTreeReaderArray.cxx:126
#20 0x00007f4f93fe3cf4 in ?? ()
#21 0x00007ffe675d19d0 in ?? ()
#22 0x000055b0af126050 in ?? ()
#23 0x000055b0af260770 in ?? ()
#24 0x000055b0af260770 in ?? ()
#25 0x00007ffe675d1bc0 in ?? ()
#26 0x00007f4f93fe1c4e in ?? ()
#27 0x0000000000000000 in ?? ()
```

### PR DESCRIPTION
**Pull request by pcanal**
This fixes #9136.

### CODE REVIEW

**Review by eguiraud — APPROVED** [review]
I'll have to trust you that the new logic is better than the old :smile: 

Maybe the commit message could be more verbose about what was wrong before and how this patch fixes it.

Also, should we have a test for the case this fixes?

**Comment by pcanal** [comment]
> Maybe the commit message could be more verbose about what was wrong before and how this patch fixes it.

Fair enough, I will expand.

> Also, should we have a test for the case this fixes?

Yes :)  Can you add the test you case you had?

**Comment by Axel-Naumann** [comment]
> Yes :) Can you add the test you case you had?

That needed valgrind to detect anything. @pcanal can we use `TStreamerInfo::ls()` or something to validate the layout? Like this?
```
root [0] TClass::GetClass("std::map<int, std::set<float>>")->GetStreamerInfo()->ls()

StreamerInfo for class: map<int,set<float> >, version=6, checksum=0xbe69c367
  map<int,set<float> > This            offset=  0 type=300 ,stl=4, ctype=61, <pair<int,set<float> >> Used to call the proper TStreamerInfo case
   i= 0, This            type=300, offset=  0, len=1, method=0
```

**Comment by pcanal** [comment]
No valgrind necessary.  The failure is a call to `R__ASSERT`.    There is not really any other means to inspect that.

**Comment by Axel-Naumann** [comment]
OK, I don't think we should wait for someone to add a test (unless it's you @pcanal ). Please merge this especially into v6-26...

**Pull request merged**
