### PR TITLE
[cxxmodules] Turn C++ modules by default on OSX.

### PR DESCRIPTION
**Pull request by vgvassilev**
Kudos to Alexander Penev (@alexander-penev)!

### CODE REVIEW

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On
--

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1014/cxx17

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1014/cxx17

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on mac1014/cxx17

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1015/cxx17

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1015/cxx17 with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1015/cxx17

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1015/cxx17 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug

**Comment by vgvassilev** [comment]
@phsft-bot build just on mac1015/cxx17

**Comment by vgvassilev** [comment]
Turns out that error is present in the C++11 builds and it is impossible for me to reproduce. @oshadura, I would like to land this PR enabling more osx platforms to increase the chances ot reproducing the failures we see here.

**Pull request merged**
