### PR TITLE
[skip-ci] mention how to change z axis title in tscatter

### PR DESCRIPTION
**Pull request by ferdymercury**
this was done by couet, I just copy-pasted from https://root-forum.cern.ch/t/scatter-plot-with-colorbar/59562/14

There is one outstanding issue though:
- Save the object as .C and reload it, then the axis title is lost.

So the function SavePrimitive should be amended, too.

Also: 

`scat->GetHistogram()->SetMinimum(100);`

has no effect, it seems there is not an easy way to control the color range?

### CODE REVIEW

**Review by couet — APPROVED** [review]
LGTN, Thanks !

**Comment by ferdymercury** [comment]
> LGTM, Thanks!

Thanksa lot!
What about the SavePrimitive function I mentioned above? Do you take care of it in a separate PR?

**Comment by couet** [comment]
Yes a separate PR is better

**Comment by couet** [comment]
I just looked at it. Indeed the histogram is there only to Draw the frame A deeper investigation is needed ...

**Comment by ferdymercury** [comment]
Thanks for checking! In that case I will open an issue to keep track of it for the future.

**Comment by hahnjo** [comment]
This broke the tests:
```
729: Processing /home/jhahnfel/ROOT/src/tutorials/graphs/scatter.C...
729: In file included from input_line_10:1:
729: /home/jhahnfel/ROOT/src/tutorials/graphs/scatter.C:39:43: error: use of undeclared identifier 'scat'
729:    TPaletteAxis *palette = (TPaletteAxis*)scat->GetGraph()->GetListOfFunctions()->FindObject("palette");
729:                                           ^
```

Tutorials are executed as part of the CI and therefore should *never* be merged with `[skip-ci]`! The simple fix is in https://github.com/root-project/root/pull/15923.

**Pull request merged**
