### PR TITLE
[PyROOT] Register custom converters and executors via CPyCppyy API

### PR DESCRIPTION
**Pull request by guitargeek**
Synchronizes with this upstream commit and directly makes use of the new
API to avoid a patch:
https://github.com/wlav/CPyCppyy/commit/993b17bce2f43516a85931b40035ac7252e2ab7e

### CODE REVIEW

**Comment by vepadulano** [comment]
The failures on Ubuntu 24 are very similar to those that led to https://github.com/root-project/root/pull/15415 . My first instinct is that the new global `gConvFactories` is not thread-safe and we are hitting this problem in distrdf as usual

**Comment by guitargeek** [comment]
Thanks a lot for the insight! I'm trying now what happens when we register the converters and executors on the Python side. Maybe the GIL will help then!

**Comment by guitargeek** [comment]
It works! Besides the small problem with `_finalSetup()` not being called when using the RDF namespace as the first statement in a macro. I'm fixing this up quickly

**Comment by guitargeek** [comment]
Some performance measurements of this PR, now that calling the interpreter is avoided:
```bash
perf stat -r 100 -B python -c 'import ROOT; ROOT._finalSetup()'
```
```
Without PR               : 0.448722 +- 0.000357
With PR (Python version) : 0.460973 +- 0.000869
```
So we're talking about a 3 % (or 12 ms) increase here, which is tolerable IMO

**Pull request merged**
