### PR TITLE
Re-enable sub-directory support in TXMLFile

### PR DESCRIPTION
**Pull request by linev**
Through continuous changes in TFile/TDirectoryFile functionality,
sub-directory support in TXMLFile was lost. Now reintroduced again.

Make similar changes for TSQLFile (only for historical reasons, seems to be nobody using it)

Reformat source code with clang format

### CODE REVIEW

**Comment by pcanal** [comment]
Was TDirectory::Streamer actually used in the previous state? (i.e. rather than changing the using classes we ought to fix the 'new' code to be keep the old behavior ... so we need to understand why it worked :) )

**Comment by linev** [comment]
> Was TDirectory::Streamer actually used in the previous state?

No, custom streamer of TDirectoryFile does not invoke TDirectory::Streamer() method.

> so we need to understand why it worked :)

Some years ago sub-TDirectory was read via TKey::ReadObj() method. In the TKeyXML there is special post-processing for TDirectoryFile. Now subdirectory read through TKey::ReadObjectAny() method. And I just add post-processing code in TKeyXML::ReadObjectAny().

**Comment by pcanal** [comment]
> No, custom streamer of TDirectoryFile does not invoke TDirectory::Streamer() method.

Fair enough.  But then I am confused ;) what changed?

**Comment by linev** [comment]
> Fair enough. But then I am confused ;) what changed?

As I said, sub-directory was not working in TXMLFile already many years.
While now GetObject() is called here:

https://github.com/root-project/root/blob/master/io/io/src/TDirectoryFile.cxx#L523

You can try to find in changes history of TDirectoryFile, when TDirectoryFile::GetObject() starts using of TKey::ReadObjectAny(). 

Now I fix problem, which nobody care of (or nobody report when problem appeared).

**Comment by pcanal** [comment]
thanks for the clarification.

**Comment by pcanal** [comment]
@phsft-bot build

**Pull request merged**
