### PR TITLE
io: introduce TBufferText class

### PR DESCRIPTION
**Pull request by linev**
This is base class for all text-based streamers like TBufferJSON, TBufferXML and TBufferSQL2

For all these classes dedicated list of I/O actions used for object streaming.
All data formats are preserved till now - all correspondent tests from roottest are working.

Main motivation - decouple basic functionality from TBufferFile. 

For the moment no changes done in TBufferFile, but as next step one can introduce intermediate TBufferImpl class, which will be base class for TBufferFile and TBufferText. There are many methods, which are similar and can be shared.

### CODE REVIEW

**Comment by linev** [comment]
@phsft-bot build just on centos7/gcc49

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
@pcanal 
Hi Philippe,
Should I try to introduce TBufferImpl class, which will be base for TBufferFile and TBufferText?
There are many similar methods, which could be collected there.

**Comment by pcanal** [comment]
@linev Yes but I am not fond of the name, any better idea?

**Pull request merged**
