### PR TITLE
[modules] Hooray RWrap_libcpp_string_view.h is dead.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by vgvassilev** [comment]
Starting build on slc6/clang_gcc62 with flags -Dvc=OFF -Dimt=ON -Dccache=ON -Dcxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
Starting build on slc6/clang_gcc62 with flags -Dvc=OFF -Dimt=ON -Dccache=ON -Dcxxmodules=On -Druntime_cxxmodules=On -Dctest_test_exclude_none=off

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On

**Comment by Axel-Naumann** [comment]
How did it die?

**Comment by vgvassilev** [comment]
Sigh, my find command did not find it but it is there...

**Pull request closed without merging**
