### PR TITLE
[Core] Replace lockguard with read lockguard in a hotspot

### PR DESCRIPTION
**Pull request by dpiparo**

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @pcanal , what do you think about this one?

**Comment by pcanal** [comment]
LGTM.  Thanks

**Comment by amadio** [comment]
@dpiparo Should we close this one?

**Comment by dpiparo** [comment]
we can even merge it! Will you do it @amadio ?

**Comment by amadio** [comment]
If I remember correctly, I measured in VTune the effect and this made performance a bit worse, actually.

**Comment by pcanal** [comment]
> within the scope where we take the write lock here,

Was the PR de-scoped?  The current diff only should one change and the scope only calls 'At' in a collection (which should be safe).

**Comment by amadio** [comment]
@pcanal, ah, I see. I think I was looking at the wrong diff before commenting here. This is probably fine, actually. I will measure tomorrow and merge if that's the case. I think the PR with the problematic change was already closed then.

**Comment by amadio** [comment]
@phsft-bot build

**Comment by amadio** [comment]
@dpiparo Please merge if you still think this should go in. Jenkins tests passed.

**Pull request merged**
