### PR TITLE
Eve-7 Add simple window management and improve message log

### PR DESCRIPTION
**Pull request by alja**
Improve logging:
* Add button in menu bar to show the highest severity message
* Show client log message in Dialog instead of popover

Add simple window management:  in view menu add items to switch sides, make single, and hide/show views

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check!

**Comment by linev** [comment]
@phsft-bot build

**Review by linev — CHANGES_REQUESTED** [review]
@alja 

Can you check report from LGTM : https://lgtm.com/projects/g/root-project/root/rev/pr-d6ca61ac9a15543f6e016c0241a992fd133c4490

It show several unused variable and one place, where logical expression always true - most probably some error.

Also in the new code you using `var i;` to declare variables. It is not good, while
this result in creation of global variable. It is much better to use `let i;`.

**Comment by alja** [comment]
@linev I have made corrections that reported in LGTM. I did not see 'var i' in the ClientLog or Main controller. I see that in the table and summary controller. Maybe this is better to fix in a separate PR.

**Review by linev — APPROVED** [review]
Now looks ok

**Pull request merged**
