### PR TITLE
Eve-7 Add server status info

### PR DESCRIPTION
**Pull request by alja**
# This Pull request:
* Add server status info
* Corrections in accessing table expression for derived classes
* Enable navigation to Lego view

### CODE REVIEW

**Comment by alja** [comment]
@linev Please check.

**Comment by alja** [comment]
@Linev The first(2cf3535) and the last commit(3262d53) should be deleted. The last commit undoes the first. I could make an new PR if you think it is necessary.

**Comment by linev** [comment]
@phsft-bot build

**Comment by linev** [comment]
> The last commit undoes the first. I could make an new PR if you think it is necessary.

Yes, please create new PR, removing these commits

**Comment by linev** [comment]
@alja Please check compiler error on Mac

**Pull request closed without merging**
