### PR TITLE
[backport-cxxmodules] Fix to the endless loop while generating roofit and tmva dicts

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
@phsft-bot build!

**Comment by Axel-Naumann** [comment]
Vassil convinced me that we can merge this *after* 6.14/08 - so let's keep it open!

**Comment by oshadura** [comment]
@phsft-bot  build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@vgvassilev, looks like modules does not stuck any more with new configuration (Ubuntu 16 + gcc5.4), should we merge this anyway?

**Comment by yamaguchi1024** [comment]
Should we close this?

**Pull request closed without merging**
