### PR TITLE
add fixture support to ROOT_ADD_TEST

### PR DESCRIPTION
**Pull request by SpectreVert**
This PR is related to https://github.com/root-project/root/issues/8707

ROOT_ADD_TEST now takes FIXTURES_SETUP, FIXTURES_CLEANUP and
FIXTURES_REQUIRED arguments (lists)

also add RESOURCE_LOCK to prevent parallel execution of a test
takes a single lock name

n.b: fixtures and resource lock namespaces are each different from
test namespaces

## Checklist:

- [x] tested changes locally
- [x] updated the docs (in the file)

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
Nice! LGTM! Also nice that you added resource lock feature!

**Comment by vgvassilev** [comment]
Can you add a test file with that fixture to show people how they should be using it?

**Comment by SpectreVert** [comment]
sure @vgvassilev, do you mean a example file in the repo or just an example in the PR message?

**Comment by vgvassilev** [comment]
> sure @vgvassilev, do you mean a example file in the repo or just an example in the PR message?

It'd be best to have an example test with a fixture. Maybe convert an already existing test to a fixture if appropriate?

**Comment by SpectreVert** [comment]
Ah yes. Well I've implemented this specially for a test! It will be merged soon too :+1:

**Review by Axel-Naumann — APPROVED** [review]
Love it. Go for it!

**Pull request merged**
