### PR TITLE
[geo] Remove deprecated are overlapping

### PR DESCRIPTION
**Pull request by dpiparo**
Remove deprecated method as per deprecation warning.

### CODE REVIEW

**Review by agheata — APPROVED** [review]
Removing the function is fine with me, however, it defies the deprecation macro behavior. AFAIK the macro is supposed to generate a compilation warning (error in overdue versions) in the user code calling this function. This function is not called in ROOT itself, so it should not trigger any warning.

**Comment by dpiparo** [comment]
Thanks. If the method had been a templatated one maybe. If not how can you have a compile time warning w/o runtime overhead for a regular method? Would you rather have a runtime warning/exception?

**Comment by agheata** [comment]
> Thanks. If the method had been a templatated one maybe. If not how can you have a compile time warning w/o runtime overhead for a regular method? Would you rather have a runtime warning/exception?

I don't know the magic behind the deprecation macro, but I know that the master is not generating warnings, unless I call explicitly this function, even if this is not templated, @guitargeek may have an explanation?

**Comment by guitargeek** [comment]
> Removing the function is fine with me, however, it defies the purpose of the deprecation macro. AFAIK the macro is supposed to generate a compilation warning (error in overdue versions) in the user code calling this function. This function is not called in ROOT itself, so it should not trigger any warning.

It's all correct, the macro serves two purposes: 1) give a user warning and 2) give a warning to developers if they don't have yet deleted the code, even though the current version tag is the number where they commited themselves to deprecating it

**Review by guitargeek — APPROVED** [review]
Looks good also to me!

IMHO this can be merged, because no matter what the next release will be called after 6.32, we don't want to ship it with this faulty function.

**Comment by ferdymercury** [comment]
Minor comment, maybe it could be replaced with

R__ALWAYS_SUGGEST_ALTERNATIVE("use now X or Y function") return 0;

**Comment by guitargeek** [comment]
Thanks for the comment @ferdymercury! You are right about the RooFit stuff, I will take care of it separately. I deprecated quite a bit in RooFit, maybe too much at once for the users to handle at once :laughing: I will probably only remove half of it and postpone some deprecations to 6.36

**Comment by agheata** [comment]
It's maybe just me, but I still don't understand why the ROOT compilation was throwing warnings before this merge in the branch made by @dpiparo since I could not see these warnings before.

**Comment by ferdymercury** [comment]
> It's maybe just me, but I still don't understand why the ROOT compilation was throwing warnings before this merge in the branch made by @dpiparo since I could not see these warnings before.

I guess because of:

```
#if ROOT_VERSION_CODE <= ROOT_VERSION(6,33,0)
# define _R__DEPRECATED_634(REASON) _R__DEPRECATED_LATER(REASON)
#else
# define _R__DEPRECATED_634(REASON) _R_DEPRECATED_REMOVE_NOW(REASON)
#endif
```

after https://github.com/root-project/root/commit/0e8e8454d09863e2d9e34f59b24081f658c216fc

**Comment by guitargeek** [comment]
@dpiparo, this needs to be merged now that it was decided that the next version is going to be called 6.34

**Comment by guitargeek** [comment]
Hi @dpiparo, this PR needs conflict resolution, and maybe also a mention in the 6.36 release notes that the code was actually removed now in compliance with #16818.

**Comment by guitargeek** [comment]
Superseded by #16830.

**Pull request closed without merging**
