### PR TITLE
[base] Make ClassDef `Class_Version()` constexpr:

### PR DESCRIPTION
**Pull request by Axel-Naumann**
allows to switch behavior based on the class version with `if constexpr`.

### CODE REVIEW

**Review by pcanal — APPROVED** [review]
Looks good but requires a `roottest` PR (and a successful ci build with `-DCTEST_TEST_EXCLUDE_NONE=On` on all platforms).

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on ROOT-debian10-i386/soversion with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by guitargeek** [comment]
Good to see these long test reports! I have opened an issue for the RooStats problem:
https://github.com/root-project/root/issues/11814

**Comment by Axel-Naumann** [comment]
Failure is unrelated

**Pull request merged**
