### PR TITLE
Allow for whitespace between last brace and quote

### LINKED ISSUE #14462: Parser for I/O customization rule is too strict.
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

A rule like:
```
#pragma read sourceClass="userClass" targetClass="userClass" source="" target="transientMember" version="[1-]" code="{ transientMember = true; } "
```
fails because of the trailing space in code.  Instead:
```
code="{ transientMember = true; }"
```
works.

### Reproducer

With class:
```
class userClass
{
   bool transientMember;
};
```

### ROOT version

master

### Installation method

any

### Operating system

any

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gemmeren**
# This Pull request:

## Changes or fixes:
Fixes #14462

## Checklist:

- [x] tested changes locally
- [n/a] updated the docs (if necessary)

This PR fixes #14462

### CODE REVIEW

**Comment by gemmeren** [comment]
I am not totally convinced that allowing misplaced whitespace at the end of the code block of a read rule is worth using regex. That decision is up to the ROOT team :) .

**Review by pcanal — APPROVED** [review]
LGTM.  Thanks.

**Comment by lmoneta** [comment]
@pcanal, @gemmeren : This PR causes a crash in loading PyTorch model with torch.jit, due to the usage of std::regex, see this open pytorch issue
https://github.com/pytorch/pytorch/issues/49460

and the failures happening in Jenkins after this commit: 
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=ROOT-ubuntu2204,SPEC=cxx20,V=master/3756/


Can we avoid here to use std::regexp ?

**Comment by gemmeren** [comment]
Hi @lmoneta ,
Sorry for that.  
To be honest I was not too happy with using regex either,  but that was the only thing I found that works and I limited it to case where the rule was mistyped. 
I feel the most robust solution may be to not change the original code, but make having no whitespace between } and  " a requirement. 
Peter

**Comment by lmoneta** [comment]
We already had this problem with `std::regexp` see https://github.com/root-project/root/pull/13674#issuecomment-1733208800.
This will affect any user of PyROOT and pytorch (if one imports ROOT before torch). 

Can you change the code to remove the whitespace to not use regexp,  for example with something like: 
```
 std::string str = " a b c ";
 char rep = 0;
  auto isSpaceChar = [](char ch) { return std::isspace(static_cast<unsigned char>(ch)); };
   std::replace_if(str.begin(),str.end(),isSpaceChar, rep);
```

**Pull request merged**
