### PR TITLE
Load all modules

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@phsft-bot build just on slc6/clang_gcc62 with flags -Dcxxmodules=On -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by etejedor** [comment]
Ping @Teemperor @vgvassilev

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Droofit=Off -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@yamaguchi1024 shall I close this one?

**Pull request closed without merging**
