### PR TITLE
Remove workaround to allow us fix the actual bug if still present.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Can you rebase, @vgvassilev ? Let's see what Jenkins says these days.

**Comment by Axel-Naumann** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by Axel-Naumann** [comment]
```
18:32:26    Assertion failed: !CurTokenLexer && "Cannot #include a file inside a macro!", file C:\build\workspace\root-pullrequests-build\root\interpreter\llvm\src\tools\clang\lib\Lex\PPLexerChange.cpp, line 71
```
Looks like it's still broken.

**Comment by vgvassilev** [comment]
Let's close this now.

**Pull request closed without merging**
