### PR TITLE
Fix for ROOT-8452

### PR DESCRIPTION
**Pull request by gganis**
Rewrite of  TChain::ParseTreeFilename and mods in TApplication::GetOptions.
Adds also full support for wildcards, at least for the backends supporting it,
and for generic paths on the command line, e.g. for

           $ root root://host.my.dom//my/dir/file.root?option#anchor

### CODE REVIEW

**Comment by pcanal** [comment]
looks good.

Can you fix the minor formatting issues?

**Comment by peremato** [comment]
@phsft-bot build

**Comment by gganis** [comment]
Apparently many tests are broken by the change in the command line processing.
I am having a look.

**Comment by gganis** [comment]
@phsft-bot build

**Comment by gganis** [comment]
I close this request and provide a new one with conflicts resolved and additional fixes.

**Pull request closed without merging**
