### PR TITLE
[cxxmodules] Add pthread_setname_np forward decl to avoid warning in

### PR DESCRIPTION
**Pull request by yamaguchi1024**
cxxmodules

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
This is a fix of
```
[582/3105] Building C object net/http/CMakeFiles/RHTTP.dir/civetweb/civetweb.c.o                                                                                                     
/home/yuka/root/net/http/civetweb/civetweb.c:2701:8: warning: implicit declaration of function 'pthread_setname_np' is invalid in C99 [-Wimplicit-function-declaration]              
        (void)pthread_setname_np(pthread_self(), threadName);                                                                                                                        
              ^                                                                                                                                                                      
1 warning generated. 
```

**Comment by linev** [comment]
Hi Yuka,

This is wrong and will not work on normal platform. Especially MacOS has other signature and I submit appropriate PR #2584 

pthread_setname_np() must be defined in `<pthread.h>` system include.
If it is not there - it is not allowed to use it.

I already provide simple app which shows if compilation works or not - see discussion #2581

**Comment by yamaguchi1024** [comment]
Ah Ok, I didn't see your PR. Is that PR solves this warning?

**Comment by linev** [comment]
> Ok, I didn't see your PR. Is that PR solves this warning?

My PR solves problem with compilation on Mac.
No idea if it helps with modules compilation.
Do you see problem with modules compilation on Linux?

**Comment by yamaguchi1024** [comment]
#2584 doesn't help this warning, maybe you can add forward decl in your PR?

> pthread_setname_np() must be defined in <pthread.h> system include.
If it is not there - it is not allowed to use it.

If it's not there, it shouldn't take a branch of `#elif defined(_GNU_SOURCE) && defined(__GLIBC__)..` so adding forward decl doesn't change semantic, IMHO

**Comment by vgvassilev** [comment]
The warning could be a false positive.

**Comment by oshadura** [comment]
@linev @vgvassilev I explained Yuka situation and we are going to try a minimal reproducer for clang to see if it is false-positive warning

**Comment by linev** [comment]
@oshadura @yamaguchi1024  

I from my side start more precise testing with civetweb.
I see several other compiler errors and warnings - will try to fix them.

**Pull request closed without merging**
