### PR TITLE
universal time in pdf file

### PR DESCRIPTION
**Pull request by musinsky**
Small improvements in header in pdf file
* universal timestamp (time zone and daylight saving time)
* add ModDate (same as CreationDate)

### CODE REVIEW

**Comment by couet** [comment]
does stressGraphics still run after the PR ?

**Comment by couet** [comment]
This is a nice patch, but as I suspected  it makes stressGraphics fail. stressGraphics.ref		stressGraphics_builtinzlib.ref need to be update. Can you add that to this PR ?

**Comment by musinsky** [comment]
in progress

**Comment by couet** [comment]
Let me know if you need some help. You need to go in the "test" directory of the ROOT sources et type make. Then run `./stressGraphics" you will get several  things like:
```
Test  4: Fill patterns............................................. OK
         PDF output.......................................... 4 FAILED
         Result    = 19386
         Reference = 19255
```
to fix this error you will need to replace 19225 by 19386 in stressGraphics.ref

**Comment by musinsky** [comment]
`stressGraphics.ref` updated
`stressGraphics_builtinzlib.ref` without changes (build ROOT with `-Dbuiltin_zlib=ON`)

**Comment by couet** [comment]
Many tanks for the new stressGraphics.ref It works. May be you can add a few word in edit README/ReleaseNotes/v622/index.md in the section "2D graphics Libraries" to annonce this new feature ? Meanwhile I will check stressGraphics_builtinzlib.ref

**Comment by couet** [comment]
I think that if you build ROOT with -Dbuiltin_zlib=ON you need to run stressGraphics with option -r
: `./stressGraphics -r` which will give you an output tu be put in `stressGraphics_builtinzlib.ref`. 

If act doing:
`./stressGraphics -r > stressGraphics_builtinzlib.ref`

should be fine.

**Comment by musinsky** [comment]
[builtinzlib_newPDF](https://paste.centos.org/view/0d1d17e7) PDF with new universal time
[builtinzlib_oldPDF](https://paste.centos.org/view/9222397b) original PDF

**Comment by couet** [comment]
Ok, lets merge it like that in that case. We will see. May be one more little thing: in the Release notes file you can add your name in the text to say it was implemented by you ?

**Comment by musinsky** [comment]
done

**Comment by couet** [comment]
Great, I merge.

**Comment by musinsky** [comment]
Thanks Olivier !

**Pull request merged**
