### PR TITLE
Implementation of Mollweide projection for TH2 histograms

### PR DESCRIPTION
**Pull request by xkzl**
# This Pull request:
It is an attempt to implement Mollweide projection for drawing 2D histograms in standard ROOT (and web-based ROOT).
https://github.com/root-project/root/pull/13211

## Changes or fixes:
I implemented a version of Mollweide projection today based on the litterature.

## Checklist:

- [X] tested changes locally
- [X] updated the docs (if necessary)

This PR fixes a missing features

### CODE REVIEW

**Comment by xKZL** [comment]
@linev I had implemented in root-project/jsroot the mollweide projection with this degeneration at pi/2.
wasn't it enough ?

**Comment by linev** [comment]
You should not try to change JSROOT in ROOT - I sync it from jsroot repository on regular basis.
I was asking to provide C++ implementation which is identical with JSROOT one.

**Comment by xKZL** [comment]
Great, this is done & ready! We are good to go, you can merge the PR if fine with the current implementation.

**Comment by linev** [comment]
> you can merge the PR

Not, I cannot. 
Once again - you should remove changes in JSROOT.

**Comment by xKZL** [comment]
I rollbacked the modifications for JSROOT

**Comment by linev** [comment]
I create proper PR based on your commit: https://github.com/root-project/root/pull/13234

**Pull request closed without merging**
