### PR TITLE
[RF] xRooFit: avoid having headers depending on preprocessor defines and other fixups

### PR DESCRIPTION
**Pull request by guitargeek**
A new `xRooFit/Config.h` header is introduced to configure the xRooFit
namespace without using compiler flags.

Also, a symlink to `inc/RooFit` is replaced with an
`add_include_directories` entry in the CMakeFiles, because the symlink
doesn't work on Windows.

In a separate commit: the right type to use `std::vector::at()` is `size_t`, and like this we
avoid the problem that `ssize_t` is not defined on Windows.

### CODE REVIEW

**Comment by guitargeek** [comment]
@phsft-bot build with flags -Droot7=ON

**Comment by guitargeek** [comment]
@phsft-bot build with flags -Droot7=ON @phsft-bot build with flags -Droot7=ON

**Comment by guitargeek** [comment]
@phsft-bot build with flags -Droot7=ON -DCMAKE_CXX_STANDARD=17

**Comment by guitargeek** [comment]
@phsft-bot build with flags -Droot7=ON -DCMAKE_CXX_STANDARD=17

**Review by Axel-Naumann — APPROVED** [review]

**Pull request merged**
