### PR TITLE
[cxxmodules] Reduce extra deserializations.

### PR DESCRIPTION
**Pull request by vgvassilev**

### CODE REVIEW

**Comment by pcanal** [comment]
You may want to make a note in the commit that the requirement laid down in the (removed) comment are now satisfied (if they are).

**Comment by vgvassilev** [comment]
That's what I am trying to see if we need that code there. Do you know what series of commits might be addressing it. Which were the commits making the lists lazy?

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@phsft-bot build just on slc6/gcc62 with flags -Druntime_cxxmodules=On -Dctest_test_exclude_none=on

**Comment by vgvassilev** [comment]
@pcanal, I fixed the commit message and I will merge it. Let me know if you have any objections.

**Pull request merged**
