### PR TITLE
[core/dictgen] modernize use nullptr

### PR DESCRIPTION
**Pull request by ferdymercury**

### CODE REVIEW

**Comment by pcanal** [comment]
The error is induced by these changes.  I am not sure why yet.

**Comment by ferdymercury** [comment]
> The error is induced by these changes. I am not sure why yet.

I believe my last commit might fix it

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Review by Axel-Naumann — APPROVED** [review]
Thanks!

**Pull request merged**
