### PR TITLE
Introduce PagedVector class

### PR DESCRIPTION
**Pull request by ktf**
The goal of the class is to be an (almost) drop in replacement for SmallVector and std::vector when those are presized and filled later, as it happens in SourceManager and ASTReader.

By splitting the actual vector in pages of the same size and allocating the pages only when they are needed, using this containers reduces the memory usage by a factor 4 for the cases relevant to the ALICE experiment ROOT / cling usage.

### CODE REVIEW

**Comment by vgvassilev** [comment]
@ktf, this is a backport of https://github.com/llvm/llvm-project/pull/66430 but does it include https://github.com/llvm/llvm-project/pull/67958?

**Comment by hahnjo** [comment]
@ktf this fails quite horribly in CI:
```
TFormulaGradientTests: /github/home/ROOT-CI/src/interpreter/llvm-project/clang/include/clang/Basic/SourceManager.h:1694: const clang::SrcMgr::SLocEntry& clang::SourceManager::getLocalSLocEntry(unsigned int) const: Assertion `Index < LocalSLocEntryTable.size() && "Invalid index"' failed.
```

@Axel-Naumann I'm not convinced this should be backported to 6.28, this has the potential to break *a lot* of things...

**Comment by vgvassilev** [comment]
Looks like we fail with ```TFormulaGradientTests: /github/home/ROOT-CI/src/interpreter/llvm-project/clang/include/clang/Basic/SourceManager.h:1694: const clang::SrcMgr::SLocEntry& clang::SourceManager::getLocalSLocEntry(unsigned int) const: Assertion `Index < LocalSLocEntryTable.size() && "Invalid index"' failed.```

**Comment by vgvassilev** [comment]
@hahnjo, the area in clang which @ktf touches hasn't been changing for years. Maybe we just discovered something that upstream has not and we need to tune the patch...

**Comment by hahnjo** [comment]
> Looks like we fail with [...]

Yes, that's exactly what I posted 45 minutes ago...

> @hahnjo, the area in clang which @ktf touches hasn't been changing for years. Maybe we just discovered something that upstream has not and we need to tune the patch...

Yes, that's what I'm saying. And IMHO that "tuning" should not happen after we broke everybody's ROOT in a minor patch release...

**Comment by vgvassilev** [comment]
> > Looks like we fail with [...]
> 
> Yes, that's exactly what I posted 45 minutes ago...
> 
> > @hahnjo, the area in clang which @ktf touches hasn't been changing for years. Maybe we just discovered something that upstream has not and we need to tune the patch...
> 
> Yes, that's what I'm saying. And IMHO that "tuning" should not happen after we broke everybody's ROOT in a minor patch release...

Agreed, let's fix the failures in the master and re-evaluate what should be done next.

**Comment by ktf** [comment]
I am checking what's going on. I might have simply screwed up the backport.

**Comment by ktf** [comment]
> @ktf, this is a backport of [llvm/llvm-project#66430](https://github.com/llvm/llvm-project/pull/66430) but does it include [llvm/llvm-project#67958](https://github.com/llvm/llvm-project/pull/67958)?

Not yet.

**Comment by ktf** [comment]
> @ktf the problem is that another patch release is _imminent_ and this PR seems not yet ready for prime time. It will have to miss this train but take the next one.

That's fine for me.

**Comment by ktf** [comment]
Needless to say that the (+ -DLLVM_ENABLE_ASSERTIONS=On) with my setup works fine. Investigating what difference I have in the build environment (I also already tried CXX20...).

**Comment by ktf** [comment]
The updated version should be closer to what is currently in llvm upstream...

**Comment by hahnjo** [comment]
> The updated version should be closer to what is currently in llvm upstream...

What are the differences? Ideally we should apply the exact patch from upstream, it should cleanly go away on a future LLVM upgrade...

**Comment by ktf** [comment]
Apparently ROOT's llvm-project is not up-to-date.

**Comment by hahnjo** [comment]
> Apparently ROOT's llvm-project is not up-to-date.

https://github.com/root-project/llvm-project/ matches what is currently in `master`. In this PR, you are modifying files in `interpreter/llvm-project/`, so *of course* these changes cannot be reflected in https://github.com/root-project/llvm-project/. This needs to be synchronized eventually, but first the test failures need to be addressed (across all platforms).

**Comment by vgvassilev** [comment]
@ktf ping...

**Comment by ktf** [comment]
Hi, I need to go back at this. Last time I tried I was unable to reproduce, though.

**Comment by vgvassilev** [comment]
@phsft-bot build!

**Comment by vgvassilev** [comment]
@ktf, what is your build configuration? To see these asserts one needs to enable assertions in LLVM with `-DLLVM_ENABLE_ASSERTIONS=On`. However, I'd suggest to build ROOT with debug LLVM with `-DLLVM_BUILD_TYPE=Debug`. This way you will be able to debug the failure directly.

**Comment by ktf** [comment]
I think I did all the various combinations (including what you suggest). I will try again.

**Comment by vgvassilev** [comment]
@ktf, I believe there is a way to download the container of the failing build. Not sure how. @Axel-Naumann probably knows.

**Comment by hahnjo** [comment]
There are instructions at the end of every (new) GitHub Actions run how to replicate the setup...

**Comment by vgvassilev** [comment]
@ktf, here is how to get the fedora38 debug build failure according to the bot:

```
 Grab the image:
  $ docker run --shm-size=1g -m 16g --security-opt label=disable -it registry.cern.ch/root-ci/fedora38:buildready
  Then:
  
  
  (
  rm -rf /github/home/ROOT-CI
              mkdir -p /github/home/ROOT-CI
  )
  (
  curl --output /github/home/ROOT-CI/artifacts.tar.gz https://s3.cern.ch/swift/v1/ROOT-build-artifacts/fedora38/master/Debug/c8bf26fbd62398395855e8d992e7688980a1d318/2023-10-05.tar.gz
  )
  (
  cd /github/home/ROOT-CI && tar -xf /github/home/ROOT-CI/artifacts.tar.gz
  )
  (
  cd '/github/home/ROOT-CI/src'
                  git checkout master
                  git fetch
                  git reset --hard @{u}
  )
  (
  cd '/github/home/ROOT-CI/src'
  
          git config user.email "rootci@root.cern"
          git config user.name 'ROOT Continous Integration'
  
          git fetch origin refs/pull/13808/head:reduce-memory-usage
          git checkout reduce-memory-usage
          git rebase master
  )
  (
  which cmake
          cmake --version
          which c++ || true
          c++ --version || true
          uname -a || true
          cat /etc/os-release || true
          sw_vers || true
          uptime || true
          df || true
  )
  (
  cmake -S '/github/home/ROOT-CI/src' -B '/github/home/ROOT-CI/build' -N -L
  )
  (
  cmake --build '/github/home/ROOT-CI/build' --config 'Debug' --parallel '16'
  )
  (
  cd '/github/home/ROOT-CI/build'
          ctest --output-on-failure --parallel 16 --output-junit TestResults.xml
  )```

**Comment by hahnjo** [comment]
@ktf we finally merged the upgrade to LLVM 16. Would you have time to rebase this, to apply the upstream version of `PagedVector`? If that one still fails, we will have to react quite soon to fix things upstream and avoid a "broken" LLVM 18.

**Comment by hahnjo** [comment]
ping, we need to imperatively test this asap because if the failures persist, we must take immediate action upstream to avoid releasing a broken Clang 18! @ktf can you help with this?

**Comment by ktf** [comment]
I will try to have a look this week.

**Comment by ktf** [comment]
Triggering a new build to regenerate the artifacts.

**Comment by hahnjo** [comment]
I believe you have to rebase, not merge the `master` branch...

**Comment by hahnjo** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by hahnjo** [comment]
Hi @ktf, as discussed yesterday the test failures are related to an issue in our incremental builds where Clad is not rebuilt after changes to the Clang headers. This leads to very weird symptoms because some "stale" functions access memory where they shouldn't and so on. I was hit by this problem already twice and it's tracked in https://github.com/root-project/root/issues/7977, so one would suppose that I remember by now but evidently I didn't... Apologies for the confusion and the delay it caused in integrating this.

I've now synchronized the changes to https://github.com/root-project/llvm-project/releases/tag/ROOT-llvm16-20240116-01, moving the header to `clang/include/clang/Basic` as mentioned yesterday to keep the ability to build against a vanilla version of LLVM). @vgvassilev I put the commit only into `ROOT-llvm16`, not `cling-llvm16` because I think it's not that relevant for Cling standalone. Let me know if you disagree and I can of course move it.

Some measurements of this change on my machine: for a simple `./bin/root.exe -q`, it reduces the maximum RSS from 217MB to 192MB and for `./bin/root.exe -q -e "std::vector<int> v" -e "return 0;"` from 255MB to 230MB :clap:

**Comment by ktf** [comment]
Very nice, thank you for your followup. Shall I close this one?

**Comment by ktf** [comment]
BTW, I think you can move IdentifiersLoaded to be a paged vector as well, although one would need to measure the effect on RSS.

**Comment by hahnjo** [comment]
> Very nice, thank you for your followup. Shall I close this one?

No, please leave it open: I hijacked your branch and directly pushed the slightly modified commit there. It's currently running through our CI (which is a bit congested at the moment). Once all is green, we can merge :smiley: 

> BTW, I think you can move IdentifiersLoaded to be a paged vector as well, although one would need to measure the effect on RSS.

Ok, that's for a follow-up PR I would say.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by hahnjo** [comment]
Hi @ktf, if we were to backport this to a release, which one would ALICE be interested in, 6.30? Or would you be fine keeping the patch locally in your stack for now?

**Comment by ktf** [comment]
Yes, we would need 6.30, but for now we are fine.

**Comment by hahnjo** [comment]
> Yes, we would need 6.30, but for now we are fine.

Ok, I prepared https://github.com/root-project/root/pull/14411. To be seen if we already include it in 6.30.04 or only in .06

**Comment by ktf** [comment]
Perfect, thanks.

**Pull request merged**
