### PR TITLE
Replace all backslashes by forward slashes on Windows + some cleanup

### PR DESCRIPTION
**Pull request by bellenot**

### CODE REVIEW

**Comment by dpiparo** [comment]
Could it be better to provide something like the "path" module of python also for ROOT? Is there anything we can use out of the box?

**Comment by bellenot** [comment]
Well, right, we could use gSystem->UnixPathname()...

**Comment by dpiparo** [comment]
even as an implementation detail perhaps of a higher level more usable 
interface. I fully get the need to have a working win alpha for may, 
support all efforts to arrive there  and have 2 worries:
- The amount of ifdefs
- The (non) sturdiness of string manipulations

**Comment by bellenot** [comment]
@phsft-bot build again, please

**Pull request merged**
