### PR TITLE
Miscellaneous fixes for warnings and deprecated std::auto_ptr

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Comment by amadio** [comment]
@vgvassilev Can you please comment on my last commit here? Thanks.

**Comment by amadio** [comment]
Is this really something they will accept or even that makes sense for them? They probably don't build on Win32 and want to keep the warning...

**Comment by vgvassilev** [comment]
We sent an email to the author of this commit in LLVM and will follow up with him.

**Comment by amadio** [comment]
Ok, thanks, Vassil. I will not merge that particular commit for now.

**Comment by amadio** [comment]
Test failed due to network issues.

**Comment by amadio** [comment]
This PR seemed to be stuck on Jenkins with the failed build above, but all builds passed. I'm merged manually after rebasing.

**Pull request closed without merging**
