### PR TITLE
[CI] load openstack credentials from file

### PR DESCRIPTION
**Pull request by olemorud**
[skip-ci]

# This Pull request:

Makes the CI load OpenStack object-store credentials from files on runners instead of using GitHub secrets.

When `pull_request` is a workflow trigger, the job can't access secrets, which means that the S3 secret token is unavailable. Adding S3 credentials to the runners themselves solves this issue.

The OpenStack credentials are defined [here](https://gitlab.cern.ch/ai/it-puppet-hostgroup-lcgapp/-/blob/rootci_test/code/manifests/build/root.pp#L43) (using [teigi](https://configdocs.web.cern.ch/secrets/adding.html))

If a malicious actor makes a PR with a job to print the credentials, or to upload a malicious artifact, it would still have to be approved by a maintainer.

A safer alternative is not allowing pull request jobs to upload artifacts at all but then we can't run tests in a separate job. It would also cause builds to take more time on average because the object storage will be less populated.

## Checklist:

- [x] tested changes locally

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
Do we need to keep the credential file around during the time that the build happens? Or can we delay the creation of this file until after the build? Or remove it before the build starts? I understand that the CI workflow can be maliciously changed - but a change to the CI workflow is a very visible change, more than a simple addition of `print some credential file` as part of the build system...

**Comment by Axel-Naumann** [comment]
I'd really like to see @hahnjo 's review as he is the one who found it.

**Comment by olemorud** [comment]
> Do we need to keep the credential file around during the time that the build happens? Or can we delay the creation of this file until after the build? Or remove it before the build starts? I understand that the CI workflow can be maliciously changed - but a change to the CI workflow is a very visible change, more than a simple addition of `print some credential file` as part of the build system...

You're saying that having the file available at certain steps such as in the workflow definition and right before uploading is managable but that that it should be unavailable while e.g. cmake is running?

**Comment by Axel-Naumann** [comment]
Yes. That would be an improvement IMO because then an attacker would need to modify the workflow, which is more visible.

**Comment by olemorud** [comment]
> Yes. That would be an improvement IMO because then an attacker would need to modify the workflow, which is more visible.

Can't think of an elegant solution right now but I guess it could be stored as a variable in python and then deleted/restored  at the right moments. (or never restored at all, it runs in a container)

**Comment by hahnjo** [comment]
Three questions from my side (may be naive because I didn't spend a lot of time to fully digest the CI setup):
1. Having the secrets stored as a file on the runners means we commit to self-hosted machines? GitHub hosted runners won't have the necessary setup.
2. The workflow run "would still have to be approved by a maintainer." - how does this work? https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ discusses a label; as far as I understand approval on GitHub itself is limited to first-time contributions. So everybody "external" who got one benign PR accepted, can afterwards run potentially malicious code without approval, no?
3. "A safer alternative is not allowing pull request jobs to upload artifacts at all but then we can't run tests in a separate job. It would also cause builds to take more time on average because the object storage will be less populated." What is the currently intended use case for this? I would have assumed that we don't want to use PR builds to feed back into incremental builds anyhow, we always want to start from a "known good" state, ie `master`, no?

**Comment by hahnjo** [comment]
@olemorud the last rebase seems to have gone wrong... You need to rebase your branch on `master`, not the other way around. There should never be commits from `master` with a different commit hashes in a PR.

**Comment by olemorud** [comment]
> @olemorud the last rebase seems to have gone wrong... You need to rebase your branch on `master`, not the other way around. There should never be commits from `master` with a different commit hashes in a PR.

Yeah I will fix it

**Comment by olemorud** [comment]
> ad 2: Ok, I didn't know this setting existed. Sounds reasonable then (at least not worse than right now). ad 3: This sounds complicated, but I'm probably missing the rationale behind. Can you remind me why we need to first build the target branch and not entirely rely on the incremental build downloaded from S3?

If the incremental build downloaded from S3 is up to date the build purely relies on it. It then behaves as if it's just downloading, rebasing the PR and building.

If the existing artifact is not up to date, or it doesn't exist, the job first builds the target branch to populate S3 with the newer version, and then continues as usual. This only adds a few minutes to that run and then proceeding runs will behave like usual as the artifacts are now up to date again.

Consider a CI where PR builds don't upload, and you have a PR where the CMake options are changed. An existing build artifact for the new options doesn't exist so the first run will be from scratch and take ~40 minutes. An issue arises and the PR is gets a new commit, and a new job starts. This job will then also take ~40 minutes to complete because the previous commit didn't upload any clean artifacts to use.

**Comment by hahnjo** [comment]
> If the incremental build downloaded from S3 is up to date the build purely relies on it. It then behaves as if it's just downloading, rebasing the PR and building.
> 
> If the existing artifact is not up to date, or it doesn't exist, the job first builds the target branch to populate S3 with the newer version, and then continues as usual. This only adds a few minutes to that run and then proceeding runs will behave like usual as the artifacts are now up to date again.

We should always have an up-to-date build from `master`, so this shouldn't be a problem in practice. Plus it generates a race condition between the build on `master` and any PR build.

> Consider a CI where PR builds don't upload, and you have a PR where the CMake options are changed. An existing build artifact for the new options doesn't exist so the first run will be from scratch and take ~40 minutes. An issue arises and the PR is gets a new commit, and a new job starts. This job will then also take ~40 minutes to complete because the previous commit didn't upload any clean artifacts to use.

I'm probably missing the place where it downloads a previous PR build, I only see `download_latest`. And in any case, I would argue it is ok for a PR changing CMake options to take ~40 minutes on subsequent pushes (the initial push will take that long anyway, and even spend time on first building the base, see above). You really want that to build cleanly, ROOT's build system is not always the greatest on incremental builds...

**Review by hahnjo — APPROVED** [review]
In any case, this is better than failing completely, so I'll go out of my way here.

**Comment by Axel-Naumann** [comment]
As another alternative (not sure that was mentioned or considered): we could have incremental builds on merge that "asynchronously" update the artifacts. That way we get newest artifacts to start from without the security issue of PR builds pushing. What do yous @hahnjo @olemorud think?

And yes, let's get this PR in and iterate afterwards!

**Comment by hahnjo** [comment]
This is what I meant with:

> We should always have an up-to-date build from `master`, so this shouldn't be a problem in practice. Plus it generates a race condition between the build on `master` and any PR build.

Ole's argument is that we may want incremental builds in PRs (between pushes), but I currently don't see this implemented and I'm not sure if this is actually a good idea.

**Pull request merged**
